### ISSUE TITLE
Support Samsung Galaxy A9 (2018) SM-A920F

### ISSUE THREAD

**Issue by smart734** [google-ar/arcore-android-sdk#1002]
### MISSING SUPPORT FOR THIS PHONE
Every phone from samsung galaxy A series is supported, only highest no. Please fix it. I can send you logs from android studio when I was testing application installed from this project.

### VERSIONS USED
- Android Studio: 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
- ARCore SDK for Android: v1.14.1
- Device manufacturer, model, and O/S: Samsung Galaxy A9 (2018), SM-A920F, Android 9
Kernel version: 4.4.148-16813757

### ISSUE
When I start app, there is no image, only black screen.

**Comment by smart734** [comment]
Tried with ARCore services v1.15 and still not working.

**Comment by smart734** [comment]
#89

**Comment by GabNet1975** [comment]
Please, add support for Samsung Galaxy A9... the older models have support but the A9.

**Comment by devbridie** [comment]
Sorry, no news to share on the A9.
