### ISSUE TITLE
Redmi note 8t support

### ISSUE THREAD

**Issue by GabiK65** [google-ar/arcore-android-sdk#1004]
My phone (xiaomi redmi note 8t) doesn't supports arcore.
![Screenshot_2020-02-16-10-03-31-083_com android vending](https://user-images.githubusercontent.com/42908443/74602733-40cd1300-50ac-11ea-8674-4080d945afee.jpg)

**Comment by jspranger** [comment]
Also interested in having the Redmi Note 8T supported.

**Comment by Socke81** [comment]
https://github.com/google-ar/arcore-android-sdk/issues/971

**Comment by kapilsisodia** [comment]
Hi ,Any update on this issue?
Any workaround available?

**Comment by devbridie** [comment]
Support for the Note 8T has been added.
