### ISSUE TITLE
Sceneform does not import texture for .obj file

### ISSUE THREAD

**Issue by suraj-0387** [google-ar/arcore-android-sdk#1008]
I am working on ar application with sceneform. I have purchased a 3d object from the site and I imported it using referring the steps mentioned in the arcore site.The object got imported but the  texture is not getting rendered (.png files).I could only see the grey skeleton of the object. The object which I am using has multiple .png files and I also kept all the files like .png,.mtl,.obj files sampleData directory .I also tried to include the .png files in .sfa file under samplers section but still the proper object is not getting loaded.
Is there any specification for 3d object in sceneform?

**Comment by devbridie** [comment]
In case somebody comes across this in search results-- the suggested approach under sceneform would probably be to create a GLTF and use that instead.
