### ISSUE TITLE
Sceneform does not load texture(.png) for OBJ file

### ISSUE THREAD

**Issue by suraj-0387** [google-ar/arcore-android-sdk#1009]
I downloaded a 3d object from turbosquid site. The object has support for multiple format like .obj,.fbx,.c4d,and .ma.The object also has files like PBR.7z,unity.7z,unreal.7z and Vray.7z,.I tried to import the .obj file in android studio(refered the scneform instructions) after placing .obj,.mtl and .png images from PBR folder to sampleData directory.Now, my object was getting displayed in the viewer but the texture is not getting displayed.How I could render the textures so that the proper object could be displayed and not just the skeletal  of the obj

**Comment by devbridie** [comment]
In case somebody comes across this in search results-- the suggested approach under sceneform would probably be to create a GLTF and use that instead.
