### ISSUE TITLE
What DisplayRotationHelper class will do?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#101]
In Ar -core developer preview2 samples new class added DisplayRotationHelper.I want to know what is the purpose of this class?

**Comment by inio** [comment]
DP1 tracked display rotation internally.  With DP2 instead we changed `setDisplayGeometry()` to additionally take the display rotation as an argument.  DisplayRotationHelper is basically that display rotation tracking logic pulled out into the sample code.

**Comment by ArigarasuthanRepo** [comment]
Thank you..
