### ISSUE TITLE
Cant install ARCore on Oppo realme x2 (its in the supported device list)

### ISSUE THREAD

**Issue by player11en** [google-ar/arcore-android-sdk#1010]
### SPECIFIC ISSUE ENCOUNTERED
Hi i buyed an oppo realme x2 it is in Googles ARCore support device list. But on playstore it tells me that the device is not supported. What can i do ? I just ordered the device because i needed ARCore for my WebXR Projekt 

It got 
Android: Android 9, 
OS-Version: ColorOS 6.1
Modell: RMX1993
Device Manufacurer: Oppo

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. Open Playstore
 2. Search for Google Play Services for AR (ARCore)
 3. Open ARCore window in Google Playstore

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
