### ISSUE TITLE
I don' think bottom sheet behavior works well with ArFragment

### ISSUE THREAD

**Issue by SGTjeong** [google-ar/arcore-android-sdk#1013]
Hi guys.

I am trying to make bottom sheet containing a list of items that can be placed in arScene.

The issue i am facing now is as follows.

When I slide up, bottom sheet does not expand at all, but only the recyclerview inside the bottom sheet is scrolled.

I checked my bottom sheet without ArFragment, and it worked just as I expected.

There is one more odd thing. If I set the bottom sheet's state as "expanded" when onCreate() is called, the bottom sheet works just as I want. But the thing is I don't want it to be expanded at the first time.

Is there a proper way to use bottom sheet with arFragment? or any workaround?

**Comment by SGTjeong** [comment]
I checked once again,

and I found out that actually bottom sheet does expand, but it's just behind the arFragment.

https://stackoverflow.com/questions/54800351/bottom-sheet-dont-appear-staying-behind-the-arfragment-in-android

The above is talking about the same issue.

**Comment by devbridie** [comment]
I tried adding a bottom bar to `hello_ar_java`, and there are no drawing or rendering issues using the bottom bar component.

As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale. If this is still an issue, you can use the newly [open-sourced Sceneform SDK sources](https://github.com/google-ar/sceneform-android-sdk/tree/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform) to try to diagnose the problem, or find a community-reared fork in which the issue has been addressed.
