### ISSUE TITLE
will it support ToF cameras?

### ISSUE THREAD

**Issue by wisockijunior** [google-ar/arcore-android-sdk#1016]
### SPECIFIC ISSUE ENCOUNTERED
will it support ToF cameras?

### VERSIONS USED
- ARCore SDK for Android: 1.16
- Device manufacturer, model, and O/S: 
Galaxy S10 5G, Note10+, iPad Pro 2020

**Comment by devbridie** [comment]
The [Supported Devices page](https://developers.devsite.corp.google.com/ar/discover/supported-devices) now details which devices support a ToF sensor.
