### ISSUE TITLE
Video Recorder sample has been deleted at version 1.16

### ISSUE THREAD

**Issue by dorp92** [google-ar/arcore-android-sdk#1018]
Is this intended?
Will it return?

**Comment by michaelmauzy** [comment]
When Sceneform was open sourced for version 1.16, it did not include samples. 

You can still access version 1.15 samples at https://github.com/google-ar/sceneform-android-sdk/releases/tag/v1.15.0. Documentation for those samples is maintained here: https://developers.google.com/sceneform/develop/samples.
