### ISSUE TITLE
Is Nova. 5t supported for AR Session

### ISSUE THREAD

**Issue by azaan4911** [google-ar/arcore-android-sdk#1019]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by devbridie** [comment]
No news on the Nova, sorry.
