### ISSUE TITLE
Could you add support for Lenovo Phab2 Pro?

### ISSUE THREAD

**Issue by romanvfp** [google-ar/arcore-android-sdk#102]
Could you add support for Lenovo Phab2 Pro, too, please? Otherwise it is kind of weird that it supports more advanced TangoCore but does not support ARCore, while I am sure that technologically it can support ARCore. The device was released just 1 year ago, so it is still quite new and up-to-date

**Comment by inio** [comment]
ARCore currently requires Android N or later, and Lenovo currently says that [the Phab2 Pro will not be getting updated to N](https://support.lenovo.com/us/en/solutions/ht501098#tablet), so this looks pretty unlikely.

**Comment by inio** [comment]
Duplicate of #89

**Comment by romanvfp** [comment]
@inio Thank you for the reply! Is there no way for ARCore developers to add support for more older versions of Android?
