### ISSUE TITLE
URGENT - Many crashes since ARCore 1.16.0

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1021]
# SPECIFIC ISSUE ENCOUNTERED

ARCore 1.16.0 has been recently released.

The corresponding 'Google Play Services for AR' app has been released on March 16th, 2020 and March 19th, 2020.

I note in my Google Vitals dashboard that the number of crashes increased dramatically since these two dates. A first small increase on March 16th, a second huge increase on March 19th.

I note this increase on both my free app and paid app, even if none of them was updated around these dates. I initially thought that it could be linked to the fact that my free and paid apps are compiled against ARCore 1.0 ; I submitted an update of my free app compiled with ARCore 1.16.0 but it changed nothing to this problem of crashes.

### VERSIONS USED
- Android Studio: versions in production around March 16th were compiled with a previous version of Android Studio ; new version of my free app compiled with Android Studio 3.6.1 => probably not a problem of Android Studio version
- ARCore SDK for Android: both 1.0 and 1.16.0
- O/S : Android 8, 8.1, 9, 10. The Android version crash distribution is the same as my Android version installation distribution => this crash does not seem linked to the Android version.  
- Device manufacturer: many and perhaps all of them (or almost)
- Models:  many and perhaps all of them (or almost) ; it seems that the crashes are not systematic on each type of model ; for example, I see crashes on Samsung S10+ models but I am unable to get a crash on my S10+. The device model crash distribution seems to be close to my Android version installation distribution => this crash does not seem linked to the device model.  

### CRASH LOGS

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
in libarcore_c.so


*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.mycompany.mybundle <<<

backtrace:
  #00  pc 000000000188f820  /data/app/com.google.ar.core-n9_4ZOyKlqHsVBy9pdiRaA==/lib/arm64/libarcore_c.so
  #01  pc 000000000091b6a0  /data/app/com.google.ar.core-n9_4ZOyKlqHsVBy9pdiRaA==/lib/arm64/libarcore_c.so
  #02  pc 000000000091c800  /data/app/com.google.ar.core-n9_4ZOyKlqHsVBy9pdiRaA==/lib/arm64/libarcore_c.so
  #03  pc 000000000198f160  /data/app/com.google.ar.core-n9_4ZOyKlqHsVBy9pdiRaA==/lib/arm64/libarcore_c.so
  #04  pc 0000000000090328  /system/lib64/libc.so (__pthread_start(void*)+36)
  #05  pc 0000000000023a28  /system/lib64/libc.so (__start_thread+68)
```

or:

```
pid: 0, tid: 0 >>> com.mycompany.mybundle <<<

backtrace:
  #00  pc 000000000188f820  /data/app/com.google.ar.core-epLyHv_I07_zxKz6ho-Gow==/lib/arm64/libarcore_c.so
  #01  pc 000000000091b6a0  /data/app/com.google.ar.core-epLyHv_I07_zxKz6ho-Gow==/lib/arm64/libarcore_c.so
  #02  pc 000000000091c800  /data/app/com.google.ar.core-epLyHv_I07_zxKz6ho-Gow==/lib/arm64/libarcore_c.so
  #03  pc 000000000198f160  /data/app/com.google.ar.core-epLyHv_I07_zxKz6ho-Gow==/lib/arm64/libarcore_c.so
  #04  pc 00000000000e3b14  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #05  pc 0000000000085330  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

### STEPS TO REPRODUCE THE ISSUE

Not able to reproduce this bug. Seems to be a random bug since the update of  'Google Play Services for AR' app released on March 16th, 2020 and March 19th, 2020.

### WORKAROUNDS (IF ANY)

No workaround at the moment.

### ADDITIONAL COMMENTS

My crash rate has been multiplied by 6, from 1% to 6% by this problem.
6% of my sessions crashing, it is really way too much... 

As the rating of the app didn't decrease, and as I have no comments saying that the app doesn't work, I have got the feeling that the app crashes on 6% of sessions, but do not crash systematically on a defined device. It may crash on a device and then works fine once the app relaunched by the user. I think that a user will have 6 crashes if he/she launches the app 100 times.

Thanks a lot for your help on this urgent matter.

**Comment by fredsa** [comment]
> The device model crash distribution seems to be close to my Android version installation distribution

Can you please indicate which Android o/s versions your app is experiencing issues on?

**Comment by Noltibus** [comment]
We see this issue in our vitals data, too. Slightly different PC but all in all the same problem I would say!

```
pid: 0, tid: 0 >>> one.realnote.app <<<

backtrace:
  #00  pc 00000000006158be  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #01  pc 00000000006161e7  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #02  pc 00000000006126c3  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #03  pc 0000000000611e5d  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #04  pc 0000000000610c6f  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #05  pc 000000000060fa57  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #06  pc 00000000005df543  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #07  pc 00000000005df37d  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #08  pc 00000000005e0a55  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #09  pc 00000000005e1ad5  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #10  pc 00000000005a84c3  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #11  pc 00000000005c2071  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
  #12  pc 000000000123714f  /data/app/com.google.ar.core-oOfq7S1on90C8D43VqbGbA==/lib/arm/libarcore_c.so
```

All our crashes are on Android 9 and on Samsung Galaxy A6 (a6lte) devices if that helps.

**Comment by shaulabalqis** [comment]
#1025 
We have encounter this issue, too. In our side, the device varies. These are the devices which have been tested and encounter the crash :
- Samsung A6
- Google Pixel 2016
- Samsung Galaxy Note 8 (SM-N950F)
- Samsung Galaxy S9+ (SM-G965F)
- Samsung Galaxy S8 (SM-G950F)

We have tried upgrading ARCore to v1.16.0 but the crash still occurs.

**Comment by idstein** [comment]
We also see exactly this issue. On our S10 devices we resolved it via explicit uninstallation of Google Play Services for AR and issued a new installation via Google Play.

However, that is an unacceptable resolution for real users.

**Comment by balarayen** [comment]
previous has many tracking issues and this version is crashing a lot :(

**Comment by agGitHub** [comment]
Issue solved with last release of ARCore app on Google Play. Closed.
