### ISSUE TITLE
How to draw custom line using ARCore

### ISSUE THREAD

**Issue by sahabe1** [google-ar/arcore-android-sdk#1023]
How to draw line similar to attached image,  i want add yellow circle stating and end

![google-measure-screenshot-3](https://user-images.githubusercontent.com/1065015/78021313-9e71a200-7370-11ea-93b4-12abcbb57bf0.jpg)

**Comment by devbridie** [comment]
Though this isn't exactly the forum for this, I'll give a rough outline on how to achieve an effect like this.

1. Create a hit test to start the beginning of the measurement. This hit test should hit a Plane.
2. [Plane.getCenterPose](https://developers.google.com/ar/reference/java/com/google/ar/core/Plane#getCenterPose()) reveals the hit-tested Y coordinate. (A)
3. Use vector calculations to calculate the intersection between [`Camera.getPose()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getPose()) and an extension of the previous plane. (B)
4. Draw a line from A to B using OpenGL.
