### ISSUE TITLE
object in portal

### ISSUE THREAD

**Issue by saeedhosseini** [google-ar/arcore-android-sdk#1027]
hi ... i need create app like this:
https://www.youtube.com/watch?v=ErEluPRrlVM
please guide me 
with java... i don't know about how handle portal

**Comment by chnouman** [comment]
This is possible in IOS unfortunately not in Android I believe. Someone correct me if I'm wrong.

**Comment by saeedhosseini** [comment]
> This is possible in IOS unfortunately not in Android I believe. Someone correct me if I'm wrong.

https://www.youtube.com/watch?v=BeoY5mRm1UY&t=61s
arcore + unity
i need create with java

**Comment by devbridie** [comment]
Once you have determined the location of some model with ARCore, you can render an object using a special shader that can give you the effect you're looking for. You'll probably need a good understanding of OpenGL to accomplish an effect like this, however.
