### ISSUE TITLE
Saving the data estimated under onDrawFrameARCore() to memory

### ISSUE THREAD

**Issue by vikasTmz** [google-ar/arcore-android-sdk#1029]
The [shared_camera_java](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/shared_camera_java/) sample contains a onDrawFrameARCore function in the [SharedCameraActivity](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/shared_camera_java/app/src/main/java/com/google/ar/core/examples/java/sharedcamera/SharedCameraActivity.java#L838) file.

I want to save data like the image (retrieved from frame), projection matrix (projmtx) and view matrix (viewmtx) to internal or external memory. Unfortunately, I cannot find enough resources online on how to do this.

Ideally, I would have asked this in stackoverflow (under the arcore tag) as recommended, but that thread is largely inactive.

**Comment by devbridie** [comment]
Check out the [Data and file storage overview](https://developer.android.com/training/data-storage) from the Android developer documentation for a quick overview of how to write values to storage. For Images, you can save [the Plane data](https://developer.android.com/reference/android/media/Image#getPlanes()) contained in `cpuImageReader`. I hope that can get you started in the right direction.
