### ISSUE TITLE
ARCore native error: session_lite_c_api.cc:47

### ISSUE THREAD

**Issue by Genoil** [google-ar/arcore-android-sdk#1031]
### SPECIFIC ISSUE ENCOUNTERED
HelloAR sample app for Unity crashes: 
`04-21 20:06:37.833 14139 14156 E native  : ################ ARCore Native Error ##################
04-21 20:06:37.833 14139 14156 E native  : ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:47	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=47`

### VERSIONS USED
- Unity 2019.3.8f1 
- ARCore SDK for Android: arcore-unity-sdk-1.16.0.unitypackage
- Device manufacturer, model, and O/S: Intrinsyc Open-Q uSOM845, Android 9 
- ARCore: 1.16.200302046
- Output of `adb shell getprop ro.build.fingerprint`: Android/sdm845/sdm845:9/Open-Q_845_P_v1.2-PKQ1.190127.001/42:userdebug/test-keys

### STEPS TO REPRODUCE THE ISSUE
1.  Follow quickstart on https://developers.google.com/ar/develop/unity/quickstart-android

### ADDITIONAL COMMENTS
Admittedly I haven't installed an IMU yet. Could that be the cause? Or does this simply mean this devkit is not in the list of supported devices?

**Comment by sandyfriend** [comment]
Your device is not ARCore support.

Android/sdm845/sdm845:9/Open-Q_845_P_v1.2-PKQ1.190127.001/42:userdebug/test-keys

it is  not a normal device fingerprint.

**Comment by Genoil** [comment]
Yes I know. It is a new device prototype. What can I do to make it pass device support validation?

**Comment by Genoil** [comment]
Installed an IMU. It doesn't crash anymore. Impossible to get tracking working without a calibrated device I guess.
