### ISSUE TITLE
How to achieve zoom for sample ar -core android app like ar-stickers in pixel camera?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#104]

**Comment by robertjuh** [comment]
On the web version i managed to accidently achieve something similar by decreasing the pixel ratio. The quality will suck but everything became larger. Not sure if it would work in Java

**Comment by ArigarasuthanRepo** [comment]
pixel ratio means scale factor?

**Comment by robertjuh** [comment]
Like 1280 x 960 or 1920 by 1200 or whatever. I'm sorry for being ignorant i'm just putting a suggestion, i dont have that much technical knowledge of this. But in the web version it made everything very large when i had put a low resolution on the canvas.

This is by no means the solution, maybe there's something in the API somewhere that can describe how to chop a part of the video feed and enlarge it?

**Comment by inio** [comment]
I just pushed #107 which demonstrates how to achieve software zoom in HelloAR java.

NOTE: hit test while zoomed will behave oddly (it acts as if you are un-zoomed).  Scaling the hit coordinates should be fairly straightforward though.

**Comment by inio** [comment]
Please let me know if you need more info.

**Comment by ArigarasuthanRepo** [comment]
surfaces are zooming.but background renderer image not shown.

**Comment by inio** [comment]
That's odd.   Did you pick up the changes to BackgroundRenderer as well?

**Comment by ArigarasuthanRepo** [comment]
Thank you its worked.i was wrongly given offset in frame.getProjectionMatrix.

**Comment by ArigarasuthanRepo** [comment]
why objects not zooming only background surfaces are zooming? How can i apply this zoom for objects?
