### ISSUE TITLE
How to draw an object center position of the camera in ar-core in android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#105]
How can i draw the object center position of the camera instead of anchor position in android?

**Comment by robertjuh** [comment]
Possible duplicate of: 
https://github.com/google-ar/arcore-android-sdk/issues/103

**Comment by hannesa2** [comment]
@ArigarasuthanRepo you have a lot of common interesting questions. Please provide a example/fork when you are able to fulfill one of your question

**Comment by ArigarasuthanRepo** [comment]
Ok Definitely.

**Comment by inio** [comment]
I believe my response to #103 should cover this with a modified camera-relative pose.
