### ISSUE TITLE
ARCore 1.17 with depth access

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#1052]
Hello everyone,

I updated my build.gradle to ARCore 1.17 a day before release and it downloaded the package. I played with it a lot but then I found that the release on GitHub has a different feature set. How is it possible?

In the package I downloaded using Android Studio building system are methods to read depth data, I tested it on Samsung Note10+ and it uses ToF sensor (unfortunately it is fusion of ToF sensor data and monodepth data). However am I allowed to share this package with other app developers?

@fredsa could you comment it? Thank you in advance.

**Comment by boehm-e** [comment]
@lvonasek  : What do you mean by monodepth data ? Are you able to get depth data from by using the "new..." [depth API](https://developers.googleblog.com/2019/12/blending-realities-with-arcore-depth-api.html) ?

**Comment by lvonasek** [comment]
By monodepth I mean depth data which are generated from RGB data sequence and yes it looks the same like what Google showed in the depth API video.

**Comment by boehm-e** [comment]
@lvonasek  Ok cool :), and which method do you use to get de depth data ?

**Comment by lvonasek** [comment]
ArFrame_acquireDepthImage

**Comment by boehm-e** [comment]
@lvonasek : Could you share it with me since there is now response?

**Comment by lvonasek** [comment]
I do not see here any response from Google

**Comment by boehm-e** [comment]
@lvonasek : No* sorry

**Comment by fredsa** [comment]
Hi @lvonasek — thank you for reporting the unexpected presence of `ArFrame_acquireDepthImage` in the maven artifacts that you downloaded. Can you confirm the file size of `core-1.17.0.aar`?

This file should exist in your local Gradle cache, most likely in the `.gradle` folder in your user/home directory. Easiest way to locate the file is something like:
```
$ find ~/.gradle -name core-1.17.0.aar -exec ls -l {} \;
```

Thanks

**Comment by lvonasek** [comment]
Hi @fredsa, unfortunatelly I do not have the aar anymore. I opened one project which was automatically cleaning Gradle cache. After redownloading it I received version without depth functionality. However I still have binary .so files:
lubos@lubos-Auron-Yuna:~/tango/3DScannerForARcore/arcore/jni/arm64-v8a$ ls -lA
total 208
-rw-rw-r-- 1 lubos lubos  68344 Mai 19 9:31 libarcore_sdk_c.so
-rw-rw-r-- 1 lubos lubos 139424 Mai 19 9:31 libarcore_sdk_jni.so

After adding missing headers, I can still use the depth functionality in native code.

I am closing this issue as the aar is not available anymore.
