### ISSUE TITLE
Unity ARCore Instant Preview not showing preview on device?

### ISSUE THREAD

**Issue by dorcatty** [google-ar/arcore-android-sdk#1053]
When I try to run my ARCore app on Unity via ARCore Instant Preview, I get the camera live view on my computer's screen, but nothing phone that's physically attached to my Mac. However the touch inputs on the phone are still works.  is there any solution of this issue ?

thanks

### VERSIONS USED
- Unity3D 2019.3.4f1 and 2019.3.14f1
- Android Studio: v3.6
- ARCore SDK for Android: 1.17 for Unity3D
- Device manufacturer, model, and O/S:  Samsung Galaxy S9+ with Android 10.
- ARCore: 
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
Packages:
    versionName=1.17.200420086
Hidden system packages:
    versionName=0
Active APEX packages:
Inactive APEX packages:
Factory APEX packages:

- Output of `adb shell getprop ro.build.fingerprint`: 
samsung/star2qltezh/star2qltechn:10/QP1A.190711.020/G9650ZHS6DTD5:user/release-keys

**Comment by sismoon2013** [comment]
See this thread in Unity forum: I searced "ARCore Samsung"
https://forum.unity.com/search/51841877/?q=Samsung+and+ARCore&o=date

**Comment by dorcatty** [comment]
are you kidding me ?

**Comment by Gjohnson6** [comment]
Hi dorcatty, this issue can happen when the resolution of the game preview in Unity is really high. If you set it to use an aspect ratio or a lower resolution, it should fix this issue. Let me know if this helps. If this doesn't help can you go to Help -> Generate ARCore Bug Report in the Unity Editor and attach the file it generates here? Thanks
