### ISSUE TITLE
ArAnchorTrackingState returns wrong values

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#1055]
### SPECIFIC ISSUE ENCOUNTERED
Using ArAnchor_getTrackingState returns AR_TRACKING_STATE_TRACKING even if the camera is covered by hand.

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 1.17
- Device manufacturer, model, and O/S: Samsung Note10+, Android 10
- ARCore: 1.17

### STEPS TO REPRODUCE THE ISSUE
 1. Use hello_c sample code
 2. Implement indication of tracking state
 3. Run it on phone and see that it indicates wrong state even if you cover camera by hand (at least for few seconds)

### ADDITIONAL COMMENTS
Huawei AREngine does not have this issue

**Comment by devbridie** [comment]
Do I understand correctly that ARCore will report the correct tracking state eventually? ARCore's understanding of the world is continually updated while the camera information is being processed. This means that some delay is expected between sudden changes in the camera's view and updating the model.

**Comment by lvonasek** [comment]
Yes, it is just extremely delayed. In Huawei AREngine after covering camera by hand all anchors are immediately indicated as not tracked. I do not have any single frame which is wrong there.

**Comment by lvonasek** [comment]
I close this as it is likely connected to the lowend motion tracking ARCore does. Fixing this has no value without resolving https://github.com/google-ar/arcore-android-sdk/issues/1347.
