### ISSUE TITLE
Feature Request: Add Support for LG V60 ToF Depth Sensor

### ISSUE THREAD

**Issue by Zenith222** [google-ar/arcore-android-sdk#1064]
Like the Huawei P30 Pro, Honor View 20, Samsung S10 5G, Samsung S20+, Samsung Note10, the LG V60 now has ToF depth sensing equipment. 

I think it would be great to support this device so environment mixing would be improved.

**Comment by devbridie** [comment]
My understanding is that the LG V60 ToF depth sensor has been supported since release; if this isn't the case, please let me know so I can get some more clarity on this.
