### ISSUE TITLE
How to reuse Anchor?

### ISSUE THREAD

**Issue by guofengw** [google-ar/arcore-android-sdk#1065]
In the arcore design principle, it is better to reuse anchor but not to create a new anchor if objects are near from.
So my question is:
If I have an anchor now, how can i attatch another object to this anchor?

**Comment by devbridie** [comment]
An Anchor describes a location in ARCore's understanding of the real world. Attaching another object to the anchor can be done by reusing the anchor's pose and drawing your other objects in relation to this pose.

**Comment by yvettemuki** [comment]
When in the arfoundation, whether I should set the anchor as the component for another game object?
