### ISSUE TITLE
Fix for crashing NDK native sample with depth SDK 1.18

### ISSUE THREAD

**Issue by Sumbera** [google-ar/arcore-android-sdk#1071]
fix crashing NDK hello_ar_c sample  https://github.com/google-ar/arcore-android-sdk/pull/1070/commits/23185bc7862d0f23901d743f3e332601978b16bd

### SPECIFIC ISSUE ENCOUNTERED
hello_ar_c  in the SDK 1.18 released yesterday 25th June  crashes 

### VERSIONS USED
- Android Studio: 3.6
- ARCore SDK for Android: 1.18
- Device manufacturer, model, and O/S: Samsung Galaxy 8 SM-G955F, Android 9
- ARCore: 1.18.200603036
- Output of `adb shell getprop ro.build.fingerprint`: samsung/dream2ltexx/dream2lte:9/PPR1.180610.011/G955FXXS8DTC1:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Download SDk for ARCore 1.18,
 2. run NDK hello_ar_c
 3. see it crashes 

### FIX

 https://github.com/google-ar/arcore-android-sdk/pull/1070/commits/23185bc7862d0f23901d743f3e332601978b16bd
  
ArFrame_transformCoordinates2d(
    -  session, frame, AR_COORDINATES_2D_OPENGL_NORMALIZED_DEVICE_COORDINATES, 6,
    + session, frame, AR_COORDINATES_2D_OPENGL_NORMALIZED_DEVICE_COORDINATES, 3,

### ADDITIONAL COMMENTS
there are just 3 'vertices' -   origin, x, y not 6.

**Comment by fredsa** [comment]
Thanks for the patch. Merged in.
