### ISSUE TITLE
Depth API documentation, sample code

### ISSUE THREAD

**Issue by brianm-sra** [google-ar/arcore-android-sdk#1072]
I noticed there is some sample code located in the developer guide document at

https://developers.google.com/ar/develop/java/depth/developer-guide

In the sample code for "Parse the depth information for the current frame"
a method named texture2D is used.  Where is texture2D method defined?
What about the sampler2D type ?
Actually, is that sample code (DepthGetMillimeters, DepthGetVisibility) in fact Java or C++ ?

Is there any sample code available which includes the DepthGetMillimeters and DepthGetVisibility methods
in context, with sample usage, etc. ?
I didn't see these included in the *.java files located in the arcore-android-sdk project under the samples directory.

**Comment by mpottinger** [comment]
Those are functions within the shader code. Under assets/shaders.

If you're not familiar with OpenGL shaders, you will have to practice and learn a bit about them. 

Shaders are written in glsl which is another C-like language that's compiled to run on the GPU.

**Comment by devbridie** [comment]
In addition to what was said above, these files are included in Hello AR in [assets/shaders/background_show_depth_color_visualization.frag](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/assets/shaders/background_show_depth_color_visualization.frag#L24). This sample renders the depth information using a shader that transforms a depth image acquired by [Frame#acquireDepthImage() ](https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/Frame#acquireDepthImage()) into a color representation.
