### ISSUE TITLE
Redmi note 8 pro Depth API support

### ISSUE THREAD

**Issue by AnassKartit** [google-ar/arcore-android-sdk#1074]
### SPECIFIC ISSUE ENCOUNTERED
Depth API support

### VERSIONS USED
- Android 10
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: Xiaomi redmi note pro 8
The device is capable of supporting Depth API Device support with a depth sensor but it is not working?

**Comment by EbadSyed** [comment]
I cant even access the depth16 using Camera2 api on Redmi note 8 pro. It seems Redmi doesnt give access to its depth sensor.

Also, only very few devices support Depth Api, and devices are mentioned in the list of ARCore devices. And Redmi Note 8 Pro isnt one of them

**Comment by khmaies5** [comment]
+1

**Comment by devbridie** [comment]
No update on this device, unfortunately. The depth sensor is not supported on ARCore for this device, likely because the depth sensor isn't accessible through camera2. #89 tracks device support requests.

**Comment by shubhammestyr22** [comment]
> I cant even access the depth16 using Camera2 api on Redmi note 8 pro. It seems Redmi doesnt give access to its depth sensor.
> 
> Also, only very few devices support Depth Api, and devices are mentioned in the list of ARCore devices. And Redmi Note 8 Pro isnt one of them

the latest gcam 8.1 mod can access depth camera and capture photos from it as a standard camera
