### ISSUE TITLE
Depth Map Image height and width do not change in portrait vs. landscape modes

### ISSUE THREAD

**Issue by brianm-sra** [google-ar/arcore-android-sdk#1075]
On Samsung Galaxy S20+ 5G device (which has ToF), I added some logcat messages to the file
arcore-android-sdk/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/HelloArActivity.java
in onDrawFrame(GL10 gl) method:

Image depthImage = frame.acquireDepthImage();
Log.d(TAG, "DEBUG: depthImage.getWidth()==" + depthImage.getWidth() + ", depthImage.getHeight()==" + depthImage.getHeight());

I ran the app and enabled depth and show depth map in settings.

I ran the app twice, once with the phone in portrait orientation, and once in landscape orientation.

In both cases, the reported width of the acquired depth map image was 160 and reported height was 90

I was expecting the two values to flip so that height was the larger value in portrait mode,
and width the larger value in landscape mode

Is this a bug, or expected behavior ?

**Comment by brianm-sra** [comment]
Note this device has installed on it Google Play Services for AR Version 1.18.200603066
and the HelloAR Java app was built with app/build.gradle containing dependency
implementation 'com.google.ar.core:1.18.0'

**Comment by devbridie** [comment]
This is expected behavior: the depth map orientation will match the intrinsics of the camera image.
