### ISSUE TITLE
Redmi k20 pro / Mi 9t pro

### ISSUE THREAD

**Issue by boehm-e** [google-ar/arcore-android-sdk#1077]
Hi, 

would the redmi k20 Pro / Mi 9T Pro support Arcore depth API ?
My honor 10, which is way less powerful does support it (even if laggy), 
so the specs doesn't seems to be the issue.
A lot of people got 9t / 9t pro phones, it would be great if these smartphones could have access to this API.

Thank you

**Comment by toolgate** [comment]
+

**Comment by devbridie** [comment]
The K20 pro is listed in supported devices, as well as the Mi 9T pro.

No updates on the other models. #89 is tracking other support requests.
