### ISSUE TITLE
upgrade samples from appcompat 28 to androidx

### ISSUE THREAD

**Issue by brianm-sra** [google-ar/arcore-android-sdk#1078]
SPECIFIC ISSUE ENCOUNTERED

The sample apps at https://github.com/google-ar/arcore-android-sdk/tree/master/samples/*_java
are using the old appcompat 28.0.0 instead of the new AndroidX

https://developer.android.com/jetpack/androidx/migrate

Note that useAndroidX is not yet specified in any of the gradle.properties files

If developers copy sample code such as CameraPermissionHelper.java
they must setup their gradle config etc. properly so that android.support.v4 is available
If they try to switch to compileSdkVersion greater than 28 they will run into build issues in Android Studio
telling them to migrate to androidx

It would be better if the sample app(s) were updated to androidx, for reference

**Comment by devbridie** [comment]
All sample apps have been updated to use androidx instead of v4/v7 appcompat.

**Comment by Serinadick12** [comment]
Please upgrade the app compatibility
