### ISSUE TITLE
FATAL Exception running any AR Core application

### ISSUE THREAD

**Issue by kulnaman** [google-ar/arcore-android-sdk#1080]
### SPECIFIC ISSUE ENCOUNTERED
I am currently using Android 10 on one plus 6 and running any arcore application results in a crash.

` Dimensions :Base[640x480], Preview [1920x1080], Original [640x360], Request [640x360]
07-16 23:32:19.926   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IFE maxImageBuffers(8) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:19.926   841  1899 I chatty  : uid=1047(cameraserver) HwBinder:841_1 identical 1 line
07-16 23:32:19.926   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IFE maxImageBuffers(8) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:19.926   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IFE maxImageBuffers(10) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:19.927   841  1899 I chatty  : uid=1047(cameraserver) HwBinder:841_1 identical 6 lines
07-16 23:32:19.927   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IFE maxImageBuffers(10) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:19.927   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IPE maxImageBuffers(9) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:19.927   841  1899 I chatty  : uid=1047(cameraserver) HwBinder:841_1 identical 1 line
07-16 23:32:19.927   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IPE maxImageBuffers(9) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:19.927   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IPE maxImageBuffers(10) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:19.927   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IPE maxImageBuffers(10) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:19.935   841  1386 I         : CalibrateActuatorDriverData [AFDBG] AF OTP Infinity:248 Macro:892 -> inf:184 macro:1085
07-16 23:32:19.942   841  1899 E CamX    : [ERROR][PPROC  ] camxipenode.cpp:2499 FinalizeBufferProperties() __debug: IPEInputPortFull: 1920 x 1440
07-16 23:32:19.963   576   576 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.
07-16 23:32:19.963 25946 25967 W Gralloc3: mapper 3.x is not supported
07-16 23:32:19.965   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:19.974   841  1899 E CamX    : [ERROR][STATS_AEC] ctuningdataadapter.cpp:102: setChromatix m_numSelectors 2 mode 0 submode value 4 usecase 0 feature1 -627123584 feature2 0 scene -463374984 effect 1
07-16 23:32:19.974   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:19.975   841  1899 E CamX    : [ERROR][STATS_AEC] caeccoredatamanager.cpp:1268: getFrameHistory No start configuration is recorded in the history!
07-16 23:32:19.975   841  1899 E CamX    : [ERROR][STATS_AEC] caecmodarbitration.cpp:372: ArbitrateExposure start config: no exposure sync up
07-16 23:32:19.975   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:19.975   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:19.975   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:19.976   841  1899 D CamX    : [DEBUG][STATS_AWB] camxcawbstatsprocessor.cpp:728 SetOperationModetoAlgo() Mode set to Algo: 1
07-16 23:32:19.977   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:19.982   841  1899 I         : CAFIOUtil() m_EnableLCR:1
07-16 23:32:19.988   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:19.988   841  1899 I mm-camera-CORE: [AFDBG] af_util_adjust_roi MainCamera = 1, Calculated new ROI: (1862, 1398, 930 698) roi_type:0 spotlight:0 lowlight:0 camif[4656,3496] zoom_ratio:1.000000
07-16 23:32:19.988   841  1899 I chatty  : uid=1047(cameraserver) HwBinder:841_1 identical 1 line
07-16 23:32:19.988   841  1899 I mm-camera-CORE: [AFDBG] af_util_adjust_roi MainCamera = 1, Calculated new ROI: (1862, 1398, 930 698) roi_type:0 spotlight:0 lowlight:0 camif[4656,3496] zoom_ratio:1.000000
07-16 23:32:19.989   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:19.989   841  1899 E CamX    : [ERROR][STATS_AF] camxautofocusnode.cpp:930 InitializeMultiStats() FATAL: Failed to get peer pipeline ID!
07-16 23:32:19.991   841  1899 E CamX    : [ERROR][ISP    ] lsc34setting.cpp:172 CalculateTintlessSetting() ERROR!!! input 0xdad5b224,pData 0xe490ac28,pOutput 0xe4908158, tintless Config 0xcfd57070,0xe8ce0648,0x0,0xe4651980, isValid: 0
07-16 23:32:19.992   841  1386 I         : StepToDAC [AFDBG] step:360 dac:271 actuatorName:imx519_lc898217xc OIS shift X:0 shift Y:0
07-16 23:32:20.022   841  1899 I OPFDManager: FD node created in pipeline
07-16 23:32:20.022   841  1899 I OPFDManager: widthRatio=1.000000, heightRatio=1.000000
07-16 23:32:20.022   841  1899 I OPFDManager: CAMIF Map in ActiveArray (0, 0), 4656x3496
07-16 23:32:20.022   841  1899 I OPFDManager: VendorFDInit: E
07-16 23:32:20.022   841  1899 I OPFDManager: VendorFDLoad_init_flag = Thread_Load_Init_Lib_OK
07-16 23:32:20.022   841  1899 I OPFDManager: VendorFDInit: X
07-16 23:32:20.022   841  1899 E OPFDManager: Succeed to create the face_attr_thread_loop thread
07-16 23:32:20.040   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:20.040   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:20.041   841  1899 D CHIUSECASE: [chi_initialize_override_session][221] "[OP_EXT] CREATE_SESSION X"
07-16 23:32:20.041  1111  1111 E Camera3-Device: configureStreams: Stream 1: DataSpace override not allowed for format 0x23
07-16 23:32:20.044  1111  1111 D Camera3-Device: Set real time priority for request queue thread (tid 26045)
07-16 23:32:20.044 25946 25999 I native  : logger.h:28 CameraMetrics: CreateCaptureSession: 163.252969ms
07-16 23:32:20.045 25946 25999 E ACameraMetadata: filterDurations: malformed duration key 1638402! count 0, type 3
07-16 23:32:20.045 25946 25999 E ACameraMetadata: filterDurations: malformed duration key 1638403! count 0, type 3
07-16 23:32:20.045 25946 25999 E ACameraMetadata: filterDurations: malformed duration key 1835009! count 0, type 3
07-16 23:32:20.045 25946 25999 E ACameraMetadata: filterDurations: malformed duration key 1835010! count 0, type 3
07-16 23:32:20.045 25946 25999 E ACameraMetadata: filterDurations: malformed duration key 1638407! count 0, type 3
07-16 23:32:20.045 25946 25999 E ACameraMetadata: filterDurations: malformed duration key 1638408! count 0, type 3
07-16 23:32:20.045 25946 25999 I native  : capture_request_utils.cc:204 Flash: ConfigureRequestFlashMode - OFF
07-16 23:32:20.045 25946 25999 E Camera2-Metadata: Update metadata entry: Unknown tag -1073741823
07-16 23:32:20.046   841  1899 D CHIUSECASE: [TeardownOverrideSession][1947] "[OP_EXT] DESTROY_SESSION E"
07-16 23:32:20.054  1068  1197 I ActivityTaskManager: Displayed fr.smarquis.ar_toolbox/.SceneActivity: +702ms
07-16 23:32:20.065   841  1899 I OPFDManager: FD frames processed 0 skipped 0 total frames 0
07-16 23:32:20.065   841  1899 I OPFDManager: Wait for attr thread thread_join E
07-16 23:32:20.065   841  1899 I OPFDManager: Wait for attr thread thread_join X
07-16 23:32:20.066   841  1899 I OPFDManager: VendorFDDeinit: FD deinit spends 0 ms (pending engine: 0)
07-16 23:32:20.072   841  1899 I OP_META : ~OPMetaManager
07-16 23:32:20.073   841  1899 D OP_META : [FlushOffline][2271] "OP_EXT Flush E"
07-16 23:32:20.073   841  1899 I OPCAMERA_EAGLEEYE: init_module: module=0xe46090d0 private=0xe464b300 list=0xe4607300
07-16 23:32:20.073   841 26062 I OPCAMERA_EAGLEEYE: flush_image: E
07-16 23:32:20.073   841 26062 I OPCAMERA_EAGLEEYE: flush_image: X
07-16 23:32:20.074   841  1899 I OPCAMERA_EAGLEEYE: deinit_module: module=0xe46090d0 private=0xe464b300 list=0x0
07-16 23:32:20.074   841  1899 D OP_META : [FlushOffline][2294] "OP_EXT Flush X"
07-16 23:32:20.079   841  1899 D CHIUSECASE: [TeardownOverrideSession][2011] "[OP_EXT] CAM Perflock: Release Perflock 0 and acquire CLOSE_CAMERA"
07-16 23:32:20.079  2515  2515 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3162
07-16 23:32:20.079   841  1899 D CHIUSECASE: [TeardownOverrideSession][2021] "[OP_EXT] DESTROY_SESSION X"
07-16 23:32:20.080   841  1899 D CHIUSECASE: [chi_initialize_override_session][217] "[OP_EXT] CREATE_SESSION E"
07-16 23:32:20.080  2515  2515 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1831
07-16 23:32:20.083  1068  1087 D ActivityTrigger: ActivityTrigger activityStopTrigger
07-16 23:32:20.094   841  1899 D CHIUSECASE: [InitializeOverrideSession][1529] "[OP_EXT] CAM Perflock: Release Perflock 1 and acquire OPEN_CAMERA"
07-16 23:32:20.094   841  1899 D CHIUSECASE: [InitializeOverrideSession][1706] "[OP_EXT] CAM Perflock: Select powerHintType=5"
07-16 23:32:20.094   841  1899 I OP_META : OPMetaManager, addr 0xcfd29800, usecaseId 1
07-16 23:32:20.094   841  1899 D CHIUSECASE: [Initialize][2427] "[OP_EXT] stream = 0xe46115f4 streamType = 0 streamFormat = 34 streamWidth = 320 streamHeight = 240"
07-16 23:32:20.094   841  1899 D CHIUSECASE: [Initialize][2448] "[OP_EXT] Usecase UsecasePreview selected"
07-16 23:32:20.094   841  1899 D CHIUSECASE: [Initialize][2466] "[OP_EXT][0/1], pipeline name:Preview, pipeline type:0, session id:0, camera id:0"
07-16 23:32:20.098   841  1899 D CHIUSECASE: [CreatePipeline][671] "[OP_EXT] CreatePipeline E Preview"
07-16 23:32:20.099   841  1899 I OPFDManager: Create
07-16 23:32:20.099   841  1899 I OPFDManager: FDManagerNode: E
07-16 23:32:20.099   841  1899 I OPFDManager: FDManagerNode: FDHWDimension: 640 x 480
07-16 23:32:20.099   841  1899 I OPFDManager: VendorFDLoad: FD lib ptr existed
07-16 23:32:20.099   841  1899 I OPFDManager: FDManagerNode: X
07-16 23:32:20.100   841  1899 I OPFDManager: FD manager node : max input ports 1, max output ports 4
07-16 23:32:20.100   841  1899 W OPFDManager: Failed to get preview dimension, result=0, width=0, height=0
07-16 23:32:20.100   841  1899 I OPFDManager: Dimensions :Base[640x480], Preview [0x0], Original [640x480], Request [640x480]
07-16 23:32:20.100   841  1899 I OPFDManager: FD frames processed 0 skipped 0 total frames 0
07-16 23:32:20.100   841  1899 I OPFDManager: VendorFDDeinit: FD deinit spends 0 ms (pending engine: 0)
07-16 23:32:20.100   841  1899 D CHIUSECASE: [FindBestSensorMode][596] "[OP_EXT] SelectedMode W=4656, H=3496, FPS:30, NumBatchedFrames:1, modeIndex:3"
07-16 23:32:20.100   841  1899 D CHIUSECASE: [CreatePipeline][752] "[OP_EXT] CreatePipeline X"
07-16 23:32:20.100   841  1899 E CHIUSECASE: [PipelineCreated][2670] "MULTIFRAME AdvancedCameraUsecase pipelineId: 0"
07-16 23:32:20.101   841  1899 I OPFDManager: Create
07-16 23:32:20.101   841  1899 I OPFDManager: FDManagerNode: E
07-16 23:32:20.101   841  1899 I OPFDManager: FDManagerNode: FDHWDimension: 640 x 480
07-16 23:32:20.101   841  1899 I OPFDManager: VendorFDLoad: FD lib ptr existed
07-16 23:32:20.101   841  1899 I OPFDManager: FDManagerNode: X
07-16 23:32:20.101   841  1899 I OPFDManager: FD manager node : max input ports 1, max output ports 4
07-16 23:32:20.101   841  1899 W OPFDManager: Failed to get preview dimension, result=0, width=0, height=0
07-16 23:32:20.101   841  1899 I OPFDManager: Dimensions :Base[640x480], Preview [0x0], Original [640x480], Request [640x480]
07-16 23:32:20.106   841  1899 E CamX    : [ERROR][STATS_AF] camxpdlibinterface.cpp:270 CreatePDLib() PDLibData creation07-16 23:32:20.106   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IFE maxImageBuffers(8) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:20.106   841  1899 I chatty  : uid=1047(cameraserver) HwBinder:841_1 identical 1 line
07-16 23:32:20.106   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IFE maxImageBuffers(8) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:20.106   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IFE maxImageBuffers(10) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:20.106   841  1899 I chatty  : uid=1047(cameraserver) HwBinder:841_1 identical 6 lines
07-16 23:32:20.106   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IFE maxImageBuffers(10) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:20.106   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IPE maxImageBuffers(9) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:20.106   841  1899 I chatty  : uid=1047(cameraserver) HwBinder:841_1 identical 1 line
07-16 23:32:20.106   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IPE maxImageBuffers(9) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:20.106   841  1899 E CamX    : [ERROR][CORE   ] camxnode.cpp:4549 FinalizeInitialization() Node::IPE maxImageBuffers(10) from link properties should be atleast requiredMaxImageBuffers(11). So replacing maxImageBuffers with requiredMaxImageBuffers
07-16 23:32:20.106   841  1385 I         : CalibrateActuatorDriverData [AFDBG] AF OTP Infinity:248 Macro:892 -> inf:184 macro:1085
07-16 23:32:20.106   841  1385 I         : StepToDAC [AFDBG] step:360 dac:271 actuatorName:imx519_lc898217xc OIS shift X:0 shift Y:0
07-16 23:32:20.121   841  1899 E CamX    : [ERROR][PPROC  ] camxipenode.cpp:2499 FinalizeBufferProperties() __debug: IPEInputPortFull: 1280 x 960
07-16 23:32:20.124   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:20.130   841  1899 E CamX    : [ERROR][STATS_AEC] ctuningdataadapter.cpp:102: setChromatix m_numSelectors 2 mode 0 submode value 3 usecase 0 feature1 -627211904 feature2 0 scene -463374864 effect 1
07-16 23:32:20.130   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:20.130   841  1899 E CamX    : [ERROR][STATS_AEC] caeccoredatamanager.cpp:1268: getFrameHistory No start configuration is recorded in the history!
07-16 23:32:20.130   841  1899 E CamX    : [ERROR][STATS_AEC] caecmodarbitration.cpp:372: ArbitrateExposure start config: no exposure sync up
07-16 23:32:20.130   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:20.130   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:20.130   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:20.130   841  1899 D CamX    : [DEBUG][STATS_AWB] camxcawbstatsprocessor.cpp:728 SetOperationModetoAlgo() Mode set to Algo: 1
07-16 23:32:20.132   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:20.136   841  1899 I         : CAFIOUtil() m_EnableLCR:1
07-16 23:32:20.139   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:20.139   841  1899 E CamX    : [ERROR][HAL    ] camxsession.cpp:3408 GetIntraRealtimePipelineId() Less than two realtime pipelines, no intra result
07-16 23:32:20.139   841  1899 E CamX    : [ERROR][STATS_AF] camxautofocusnode.cpp:930 InitializeMultiStats() FATAL: Failed to get peer pipeline ID!
07-16 23:32:20.141   841  1899 E CamX    : [ERROR][ISP    ] lsc34setting.cpp:172 CalculateTintlessSetting() ERROR!!! input 0xdacc084c,pData 0xe490ab80,pOutput 0xe49080b0, tintless Config 0xcfd55070,0xe8ce0648,0x0,0xe4607de0, isValid: 0
07-16 23:32:20.165   841  1899 I OPFDManager: FD node created in pipeline
07-16 23:32:20.165   841  1899 I OPFDManager: widthRatio=1.000000, heightRatio=1.000000
07-16 23:32:20.165   841  1899 I OPFDManager: CAMIF Map in ActiveArray (0, 0), 4656x3496
07-16 23:32:20.165   841  1899 I OPFDManager: VendorFDInit: E
07-16 23:32:20.165   841  1899 I OPFDManager: VendorFDLoad_init_flag = Thread_Load_Init_Lib_OK
07-16 23:32:20.165   841  1899 I OPFDManager: VendorFDInit: X
07-16 23:32:20.165   841  1899 E OPFDManager: Succeed to create the face_attr_thread_loop thread
07-16 23:32:20.165   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:20.165   841  1899 E CamX    : [ERROR][HAL    ] camxmetadatapool.cpp:1434 GetMetadataByTag() Invalid Slot to get a metadata from
07-16 23:32:20.165   841  1899 D CHIUSECASE: [chi_initialize_override_session][221] "[OP_EXT] CREATE_SESSION X"
07-16 23:32:20.166  1111  1111 D Camera3-Device: Set real time priority for request queue thread (tid 26045)
07-16 23:32:20.166 25946 25999 I native  : logger.h:28 CameraMetrics: CloseCaptureSession: 120.963802ms
07-16 23:32:20.166 25946 25991 I native  : cameras.cc:1306 Camera 0 changed state CLOSED->OPEN; Camera device opened successfully. i=0
07-16 23:32:20.173   841  1899 D CHIUSECASE: [OverrideFlush][2252] "[OP_EXT] CAM Perflock: Release Perflock 0 and acquire CLOSE_CAMERA"
07-16 23:32:20.173  1111  1111 I Camera3-Device: disconnectImpl: E
07-16 23:32:20.173   841  1899 D CHIUSECASE: [chi_extend_close][159] "[OP_EXT] CLOSE_CAMERA E"
07-16 23:32:20.173   841  1899 D CHIUSECASE: [chi_extend_close][163] "[OP_EXT] CLOSE_CAMERA X"
07-16 23:32:20.173   841  1899 D CHIUSECASE: [TeardownOverrideSession][1947] "[OP_EXT] DESTROY_SESSION E"
07-16 23:32:20.199   841  1899 I OPFDManager: FD frames processed 0 skipped 0 total frames 0
07-16 23:32:20.199   841  1899 I OPFDManager: Wait for attr thread thread_join E
07-16 23:32:20.199   841  1899 I OPFDManager: Wait for attr thread thread_join X
07-16 23:32:20.199   841  1899 I OPFDManager: VendorFDDeinit: FD deinit spends 0 ms (pending engine: 0)
07-16 23:32:20.206   841  1899 I OP_META : ~OPMetaManager
07-16 23:32:20.206   841  1899 D OP_META : [FlushOffline][2271] "OP_EXT Flush E"
07-16 23:32:20.206   841  1899 I OPCAMERA_EAGLEEYE: init_module: module=0xe4609348 private=0xe464bbd0 list=0xe46072f0
07-16 23:32:20.206   841 26073 I OPCAMERA_EAGLEEYE: flush_image: E
07-16 23:32:20.206   841 26073 I OPCAMERA_EAGLEEYE: flush_image: X
07-16 23:32:20.206   841  1899 I OPCAMERA_EAGLEEYE: deinit_module: module=0xe4609348 private=0xe464bbd0 list=0x0
07-16 23:32:20.206   841  1899 D OP_META : [FlushOffline][2294] "OP_EXT Flush X"
07-16 23:32:20.213   841  1899 D CHIUSECASE: [TeardownOverrideSession][2011] "[OP_EXT] CAM Perflock: Release Perflock 1 and acquire CLOSE_CAMERA"
07-16 23:32:20.213   841  1899 D CHIUSECASE: [TeardownOverrideSession][2021] "[OP_EXT] DESTROY_SESSION X"
07-16 23:32:20.213  1111  1111 I CameraProviderManager: Camera device device@3.3/legacy/0 torch status is now AVAILABLE_OFF
07-16 23:32:20.213  1111  1111 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=1
07-16 23:32:20.214  1111  1111 I CameraProviderManager: Camera device device@3.3/legacy/1 torch status is now AVAILABLE_OFF
07-16 23:32:20.214  1111  1111 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=1, newStatus=1
07-16 23:32:20.214  1111  1111 E CameraService: onTorchStatusChangedLocked: cannot get torch status of camera 1: No such file or directory (-2)
07-16 23:32:20.214  1111  1111 I CameraProviderManager: Camera device device@1.0/legacy/2 torch status is now AVAILABLE_OFF
07-16 23:32:20.214  1111  1111 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=2, newStatus=1
07-16 23:32:20.214  1111  1111 E CameraService: onTorchStatusChangedLocked: cannot get torch status of camera 2: No such file or directory (-2)
07-16 23:32:20.214  1111  1111 I CameraProviderManager: Camera device device@3.3/legacy/2 torch status is now AVAILABLE_OFF
07-16 23:32:20.214  1111  1111 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=2, newStatus=1
07-16 23:32:20.214  1111  1111 E CameraService: onTorchStatusChangedLocked: cannot get torch status of camera 2: No such file or directory (-2)
07-16 23:32:20.214  1111  1111 I CameraProviderManager: Camera device device@1.0/legacy/3 torch status is now AVAILABLE_OFF
07-16 23:32:20.214  1111  1111 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=3, newStatus=1
07-16 23:32:20.214  1111  1111 E CameraService: onTorchStatusChangedLocked: cannot get torch status of camera 3: No such file or directory (-2)
07-16 23:32:20.214  1111  1111 I CameraProviderManager: Camera device device@3.3/legacy/3 torch status is now AVAILABLE_OFF
07-16 23:32:20.214  1111  1111 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=3, newStatus=1
07-16 23:32:20.214  1111  1111 E CameraService: onTorchStatusChangedLocked: cannot get torch status of camera 3: No such file or directory (-2)
07-16 23:32:20.214  1111  1111 I Camera3-Device: disconnectImpl: X
07-16 23:32:20.215   576   576 I hwservicemanager: getTransport: Cannot find entry vendor.pa.camera.motor@1.0::ICameraMotor/default in either framework or device manifest.
07-16 23:32:20.215  1111  1111 I CameraService: disconnect: Disconnected client for camera 0 for PID 25946
07-16 23:32:20.216 25946 25999 I native  : logger.h:28 CameraMetrics: CloseCamera: 49.233907ms
07-16 23:32:20.216 25946 25999 I native  : android_camera.cc:755 [Camera=0; State=CLOSED] Reset cleanly got to CLOSED state.
07-16 23:32:20.216 25946 25991 I native  : cameras.cc:1306 Camera 0 changed state OPEN->CLOSED; Camera device closed successfully. i=1
07-16 23:32:20.216 25946 25999 E native  : cameras_async.cc:255 INVALID_ARGUMENT: [Camera=0; State=OPEN] ACaptureRequest_setEntry_u8 ACAMERA_ERROR_INVALID_PARAMETER [type.googleapis.com/util.ErrorSpacePayload='CameraStatusErrorSpaceClass::ACAMERA_ERROR_INVALID_PARAMETER']
07-16 23:32:20.216 25946 25999 I native  : logger.h:28 DataSourceMetrics: kFirstGlCallback: 349.796719ms
07-16 23:32:20.231 25946 25946 E native  : error_policy_util.cc:260
07-16 23:32:20.231 25946 25946 E native  : ################ ARCore Native Error ##################
07-16 23:32:20.231 25946 25946 E native  : BUILD_CHANGELIST:319846266
07-16 23:32:20.231 25946 25946 E native  : BUILD_BASELINE_CHANGELIST:314554407
07-16 23:32:20.231 25946 25946 E native  : ################### Stack Trace Begin ################
07-16 23:32:20.231 25946 25946 E native  : ARCoreError: third_party/arcore/ar/core/session.cc:1429      https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/session.cc?g=0&l=1429
07-16 23:32:20.231 25946 25946 E native  : ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:63       https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=63
07-16 23:32:20.231 25946 25946 E native  : ################### Stack Trace End #################
07-16 23:32:20.231 25946 25946 E native  :
07-16 23:32:20.231 25946 25946 D AndroidRuntime: Shutting down VM
07-16 23:32:20.232 25946 25946 E AndroidRuntime: FATAL EXCEPTION: main
07-16 23:32:20.232 25946 25946 E AndroidRuntime: Process: fr.smarquis.ar_toolbox, PID: 25946
07-16 23:32:20.232 25946 25946 E AndroidRuntime: com.google.ar.core.exceptions.FatalException
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:143)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at com.google.ar.core.Session.nativeUpdate(Native Method)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at com.google.ar.core.Session.update(Session.java:67)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at com.google.ar.sceneform.ArSceneView.onBeginFrame(SourceFile:102)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at com.google.ar.sceneform.SceneView.doFrameNoRepost(SourceFile:90)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at com.google.ar.sceneform.SceneView.doFrame(SourceFile:86)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1039)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:864)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:794)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7397)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-16 23:32:20.232 25946 25946 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)`
### VERSIONS USED
- Android Studio: 4.0.1
- ARCore SDK for Android: 1.18.200603086
- Device manufacturer, model, and O/S: One Plus , A6003, Paranoid Android Quartz 3
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. Simply open any ar core application.
 1.
 1.

**Comment by devbridie** [comment]
Thanks for reporting. Can you please add the following values:

* ARCore version:
   * On Windows, use: adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"
   * On macOS, use: adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:

* Output of adb shell getprop ro.build.fingerprint:

**Comment by kulnaman** [comment]
- ARCore Version : 1.18.200603086

- google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys

**Comment by devbridie** [comment]
Sounds like that's probably the case: your device's hardware doesn't match up with what the ROM reports. I don't think we will support this situation, sorry about that.
