### ISSUE TITLE
Huawei Nova 5T\Honor 20 support of ARcore

### ISSUE THREAD

**Issue by SignFinder** [google-ar/arcore-android-sdk#1081]
Hi team,
I have received the confirmation from local Russia Huawei support that Huawei Nova 5T meets all requirements for ARCore.
But they do not not understand how to certify and aadd this model to be able to install Google Services for AR.

I would like to ask you to add the device to certified. If it is necessary to make any tests - I can spend my time for this.
Let me know how I can do it and help to add this phone to supported.

Huawei Nova 5T is renamed Honor 20. 
I had old Honor 10 certified for ARCore. What is a reson not to add new modern Honor 20\Huiawei Nova 5T phone to supported list.

**Comment by luiscrocab** [comment]
I have one too, hope the Arcore support is available soon

**Comment by irishchan92** [comment]
Me too. i have a nova 5t and it doesn’t support ar core. Hope they can add this feature very soon

**Comment by Asatopskii** [comment]
The thing is, that Nova 5T is actually WORKING with ARCore up to 1.12 version if you will DL it from an external source (Used to play FNAF SD). And it's really smooth and had 0 lags, hardware in this phone is capable of playing AR games. But after 1.12 it's not working anymore for close to no reason. What i mean is that i don't get why laggy phones with insane performance rollercoasters does get AR support, and a powerful phone doesn't. It's been so long after the phone release and im really losing all hope for this to be added. But this has to be an unfortunate mistake

**Comment by irishchan92** [comment]
Yes... i hope they get to hear our feedbacks and still be able to add it in huawei nova 5t.. ar core has amazing features.. it would be cool to use them in nova 5t

**Comment by hoangnguyen92dn** [comment]
I am using Nova 5T for Android development, hope will receive supported news soon 🙏

**Comment by devbridie** [comment]
Sorry, no updates on these devices. #89 is where we're collecting device support requests.

**Comment by luiscrocab** [comment]
Im still waiting for the ARCORE support for my Huawei Nova 5T, os a power full smartphone, why didnt certificate???

**Comment by Tomsn16** [comment]
Im waiting for support on my phone too.. and im already really frustrated... i bought this phone becouse i has nice performance with games but this is just sad......
