### ISSUE TITLE
Lenovo 10e Chromebook tablet not available in Google Play

### ISSUE THREAD

**Issue by joensaar** [google-ar/arcore-android-sdk#1088]
### SPECIFIC ISSUE ENCOUNTERED
The Lenovo 10e Chromebook tablet is advertised as an ARCore supported device. The 'Google Play Services for AR' app is not available as it should be.

**Comment by sandyfriend** [comment]
Hi Joensaar,
  Could provide more info like the ads or info saying Lenovo 10e Chromebook tablet is ARCore support device?
Thanks.

**Comment by joensaar** [comment]
**ARCore support is mentioned twice here:**

https://www.lenovo.com/gb/en/laptops/lenovo/student-chromebooks/Lenovo-10e-Chromebook-Tablet/p/22ED10E10E1

_"And with its world-facing camera with ARCore, it lets students explore new worlds through immersive 3D augmented reality."_

and

_"Camera | 2MP front-facing, 5MP world-facing camera with ARCore"_

**Comment by fredsa** [comment]
@joensaar Thank you for reporting this issue.

The ARCore supported devices page (https://developers.google.com/ar/discover/supported-devices) and (non)availability of Google Play Services for AR (https://play.google.com/store/apps/details?id=com.google.ar.core) from the Play Store are in this case correct.

We will work with Lenovo to remove the mentioned of "augmented reality" on the product page you mentioned.
