### ISSUE TITLE
Depth API: problem of matching between Depth Image and real image

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1089]
# SPECIFIC ISSUE ENCOUNTERED

I acquire the depth image thanks to:
Image depthImage = frame.acquireDepthImage();

I manage to display in gray scale color this Depth image on my screen but it is shifted (shapes not aligned) compared to:
- the real video image (RGB)
- the hello_ar_java demo project colored Depth map (this depth map (named depthTexture) seems to be aligned on video)

I don't understand why I don't manage to align depthImage (obtained thanks to frame.acquireDepthImage() ) on the real video RGB image and on the demo project colored Depth map (= depthTexture). 

What is surprising is that the size of the depthImage (obtained thanks to frame.acquireDepthImage() ) on my Samsung S10+ has the following size : 

Width=160
Height=90

So, I have to rotate it of 90° to display it on my screen (as its width is smaller than its height). So 1st question : Why do I have to do this rotation ? Why is it not given with the correct orientation ?

Also, my screen resolution is 1440 x 3040 (screen ratio = 2.11) whereas the depthImage obtained thanks to frame.acquireDepthImage() ) is 160 x 90 (image ratio = 1.77) (nota: depthTexture is also 160 x90). So 2nd question: why are these ratios different ? (already make it difficult to align the depthImage and RGB image of my camera)

If I scale the depthImage in order to be full screen (so the image is not scaled proportionally but a little bit stretched as the scale ratios are different), the depthImage and RGB image are still not aligned (seems quite aligned vertically but shifted right/left). 3rd question: why do I still have alignement problems between depthImage and RGB image ? (whereas depthTexture is correctly aligned as already said)

Thanks a lot for your help !

### VERSIONS USED
- Android Studio: 4.0
- ARCore SDK for Android: 1.18.0
- Device manufacturer, model, and O/S: Samsung S10+, Android 10
- ARCore: 1.18.0

**Comment by brianm-sra** [comment]
FYI: according to this comment on a previous issue : https://github.com/google-ar/arcore-android-sdk/issues/1075#issuecomment-651290147

Question:

> "I ran the app twice, once with the phone in portrait orientation, and once in landscape orientation.
> 
> In both cases, the reported width of the acquired depth map image was 160 and reported height was 90
> 
> I was expecting the two values to flip so that height was the larger value in portrait mode,
> and width the larger value in landscape mode
> 
> Is this a bug, or expected behavior ?"

Answer:

> "This is expected behavior: the depth map orientation will match the intrinsics of the camera image."

**Comment by agGitHub** [comment]
> FYI: according to this comment on a previous issue : [#1075 (comment)](https://github.com/google-ar/arcore-android-sdk/issues/1075#issuecomment-651290147)
> Answer:
> 
> > "This is expected behavior: the depth map orientation will match the intrinsics of the camera image."

Thanks but I don't understand this answer. And it doesn't answer my question which is about the non-matching between RGB image and Depth Image.

**Comment by agGitHub** [comment]
Ok, you can close this ticket. I made a mistake in my code... Sorry for that.
