### ISSUE TITLE
Integration of Arcore + Ai in java android ?? 

### ISSUE THREAD

**Issue by Adityavj2699** [google-ar/arcore-android-sdk#1090]
How can i pass the Arfragment continues frame to the tflite model so that they can detect if the particular gesture has been detected or not and based on that result how can i display AR in Arfragment ???

**Comment by devbridie** [comment]
[Frame#acquireCameraImage()](https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/Frame#acquireCameraImage()) retrieves the camera image that can be used as input in your model. You can display the results from your model using either the Android SDK or by rendering your own elements on the canvas view.

**Comment by Adityavj2699** [comment]
Can i have a reference code ?? 
I didn't find solution on Web, can you please Help me on this ?

**Comment by Nihar1989** [comment]
@devbridie,any idea about how do you create an anchor node at the location of the detected object in the camera image,like i pass the image through a object detection model and get the location of detected object ,im struck at how to use these coordinates to create an anchor node,please help me out
