### ISSUE TITLE
ARCore can't support Xiaomi Pad

### ISSUE THREAD

**Issue by AlanJiang98** [google-ar/arcore-android-sdk#1091]
I can run ARCore demo successfully on Xiaomi K30 Pro smartphone but failed on Xiaomi Pad 4. Why is Xiaomi Pad 4  not on the supported device list?

**Comment by b29b** [comment]
its hopeless, google only cares about its pixel
probably better off switching to apple at this point 😥

**Comment by devbridie** [comment]
No update on this device at the moment. The lack of support for this device could have multiple reasons; OEM support, hardware constraints, software constraints, or lack of volume. #89 is tracking device support requests.
