### ISSUE TITLE
ARcore not available for Redmi Note 9 Pro max.

### ISSUE THREAD

**Issue by anujroadrage** [google-ar/arcore-android-sdk#1092]

**Comment by livedtrid** [comment]
Please add support for Xiaomi Redmi Note 9 Pro. Thanks 🙂

**Comment by abdulrahim-a** [comment]
hi any idea when would the note 9 pro max get arcore support?

**Comment by devbridie** [comment]
Support for the 9 Pro and 9 Pro Max has been added.

**Comment by livedtrid** [comment]
> Support for the 9 Pro and 9 Pro Max has been added.

Since after the MIUI update to Android 10, the ARCore isn't working properly. Sometimes it works, sometimes doesn't. I wish I haven't updated my phone.

**Comment by devbridie** [comment]
Could you elaborate on what it means when ARCore doesn't work? I'll ask the device team about what this could be.

**Comment by Narendra186** [comment]
> Could you elaborate on what it means when ARCore doesn't work? I'll ask the device team about what this could be.

Surface is not being detected most of the times.
