### ISSUE TITLE
Possible to control the camera at my end and pass the image raw data to android ar core for ar functionality?

### ISSUE THREAD

**Issue by kafan1986** [google-ar/arcore-android-sdk#1094]
I have a usb based camera and it works with android. I can control the camera and access raw rgb data frame (NV12) using standard Android camera 2 API. Is it possible to control the camera at my end on my own in the app and then call rest of the ar functionality?

**Comment by devbridie** [comment]
Currently, there is no support for external cameras in ARCore.

**Comment by kafan1986** [comment]
@devbridie For a supported android phone and internal camera. If I want to perform some computer vision task on the camera frame before the AR functionality takes over. Is it possible? So that I can create some kind of computer vision hook in the AR core pipeline.
