### ISSUE TITLE
Depth API with front camera and faceTracking

### ISSUE THREAD

**Issue by grigM** [google-ar/arcore-android-sdk#1095]
Is there any way to use Depth API with front camera ?
If it's not, do the team have any plan to implement this feature in near future ?

i wan't to try to use DepthApi for portrait background segmentation with faceMesh but it's look like it's not possible at this moment. 
Maybe someone know better way to make it with arcore ?

**Comment by devbridie** [comment]
The Depth API currently only enables new features for rear-facing camera experiences. I don't have much to share regarding front-camera support at the moment, sorry.
