### ISSUE TITLE
Application manifest must contain meta-data com.google.ar.core.min_apk_version

### ISSUE THREAD

**Issue by TresorEscape** [google-ar/arcore-android-sdk#1097]
I try to follow this guide for ARCore in Android Studio : https://developers.google.com/ar/develop/java/enable-arcore#manifest
I follow the steps but when I try to check if ARCore is supported on the device i have an error :
`E/ARCore-ArCoreApk: Error while checking app details and ARCore status
com.google.ar.core.exceptions.FatalException: Application manifest must contain meta-data com.google.ar.core.min_apk_version
    at com.google.ar.core.k.e(ArCoreApkImpl.java:41)
    at com.google.ar.core.k.b(ArCoreApkImpl.java:52)
    at com.google.ar.core.k.checkAvailability(ArCoreApkImpl.java:5)`

I don't understand why i should specify the min apk version in the manifest. I have it in the build.gradle(:app) :
`minSdkVersion 21`

In the dependencies I have :
`implementation 'com.google.ar:core:1.18.0'`

In the repositories I have :
`    repositories {
    google()`

In the manifest I have, just under <application .... > :
`<meta-data android:name="com.google.ar.core" android:value="optional" />`

If i look at the Merged manifest, i can see :
`<uses-sdk
android:minSdkVersion='21
android:targetSdkVersion='29' />`

I also see the meta-data.

What did I miss ?
Thank you

### VERSIONS USED
- Android Studio: 4.0.1
- ARCore SDK for Android: 1.18.0
- Device manufacturer, model, and O/S: Galaxy S9 android 10

**Comment by devbridie** [comment]
`com.google.ar.core.min_apk_version` is an attribute added to your application via a manifest merge. You should have a log file `/app/build/outputs/logs/manifest-merger-debug-report.txt` which contains something like this:

```
meta-data#com.google.ar.core.min_apk_version
ADDED from [com.google.ar:core:1.18.0] ~/.gradle/caches/transforms-2/files-2.1/9aa900d6fbb2af2587a1b20f9a4868b8/jetified-core-1.18.0/AndroidManifest.xml:32:9-34:41
	android:value
		ADDED from [com.google.ar:core:1.18.0] ~/.gradle/caches/transforms-2/files-2.1/9aa900d6fbb2af2587a1b20f9a4868b8/jetified-core-1.18.0/AndroidManifest.xml:34:13-38
	android:name
		ADDED from [com.google.ar:core:1.18.0] ~/.gradle/caches/transforms-2/files-2.1/9aa900d6fbb2af2587a1b20f9a4868b8/jetified-core-1.18.0/AndroidManifest.xml:33:13-62
```

**Comment by TresorEscape** [comment]
Hello,
Sorry for timing, i just come home from holiday !
I have check the file manifest-merger-debug-report.txt and I have : 

meta-data#com.google.ar.core
ADDED from C:\Users\Ben-PC\AndroidStudioProjects\XXXX\app\src\main\AndroidManifest.xml:48:9-80
	android:value
		ADDED from C:\Users\Ben-PC\AndroidStudioProjects\XXXX\app\src\main\AndroidManifest.xml:48:54-78
	android:name
		ADDED from C:\Users\Ben-PC\AndroidStudioProjects\XXXX\app\src\main\AndroidManifest.xml:48:20-53

I think this is not OK compare to your answer ?

**Comment by TresorEscape** [comment]
I performed some tests and it turns out if I delete the row `tools:node="replace"` of the manifest, the fusion of the manifests is OK.
I have then the line `meta-data#com.google.ar.core.min_apk_version`.


If i change to tools:node="merge, i got : `Manifest merger failed : Attribute application@label value=(XXXX) from AndroidManifest.xml:17:9-37`

**Comment by devbridie** [comment]
Is the issue then resolved? It sounds like the app should run if `min_apk_version` is in your manifest.

**Comment by TresorEscape** [comment]
Yep problem solved !
Thank you !

**Comment by cliffhorse** [comment]
> Yep problem solved ! Thank you !

Hello，how is the problem solved ?

**Comment by joyozhou** [comment]
> 

Delete the row tools:node='replace' of the manifest.

**Comment by joyozhou** [comment]
> > Yep problem solved ! Thank you !
> 
> Hello，how is the problem solved ?
Delete the row `tools:node="replace"` of the manifest.
