### ISSUE TITLE
Can i place a anchor of the object in air instead of plane in ar-core android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#110]
How to place a anchor of the object in air instead of placing plane(instead of anchoring object in tables and other horizontal planes?

**Comment by inio** [comment]
You can create an anchor at any Pose.  Getting a pose "in the air" probably means doing something relative to the current camera pose, or offsetting the pose returned by a hit test.

For the later, if for example you wanted to place anchors 20cm above the hit point, you could replace

    mAnchors.add(hit.createAnchor());

with

    mAnchors.add(hit.getTrackable().createAnchor(
        hit.getPose().compose(Pose.makeTranslation(0, 0.2f, 0))));

**Comment by ArigarasuthanRepo** [comment]
Thank you so much.

I did with 

```
Pose mCameraRelativePose=Pose.makeTranslation(0.0f, 0.0f, -0.5f);

mSession.createAnchor(mCameraRelativePose)
```

above code placed anchor at center position is it correct?

**Comment by inio** [comment]
That would place the anchor at an arbitrary point in space, 50cm from the origin (which has no specified location) and offset in a random horizontal direction.

By our *current* behavior, that object would be 50cm horizontally in front of the initial device location, but that could change in the future.   If you want to do this, create an anchor as soon as you have a valid pose and position things relative to that.

**Comment by ArigarasuthanRepo** [comment]
Thank you for your response.

**Comment by ArigarasuthanRepo** [comment]
is it possible to create object 50 from the straight of the hit location in plane

**Comment by sjfricke** [comment]
So does the C api not offer a way to translate the `ArPose`? Like the only workaround I was able to find is track the spot at Pose and then add the offset (like 20cm or whatever) when rendering it

**Comment by izdi** [comment]
Hi @inio, have this approach changed since 1.0 ?
```
mAnchors.add(session.createAnchor(
    frame.getCamera().getPose()
        .compose(Pose.makeTranslation(0, 0, -1f))
        .extractTranslation()))
```

I'm trying to create object in front of the wall and nothing's happening, there is no points to attach to.

**Comment by inio** [comment]
`getPose` should now be `getDisplayOrientedPose()` but otherwise that should work.

**Comment by izdi** [comment]
When I try to tap in front of the wall where no points around nothings happening. The log message is `hit_test.cc:360 generic::internal: No point hit.`

Does it mean that this approach won't work and you still need a point or plane to create anchor for objects? Otherwise it has not enough features to track.

**Comment by izdi** [comment]
OK, looks like I understand the issue now. I was doing it inside of a hitTest loop, switch to handle on a tap and when tracking state is active. However sometimes models disappear right after adding to world.
Thanks for clarifying !

Not related to the thread.
Is there any documentation I could read about how feature points calculated? I would like to know what type of environment a user should be in order to successfully the AR app if i'm trying to attach my objects not the plain, but a bottle on a table or toothbrush etc. Does this make any sense?

**Comment by inio** [comment]
Sorry I didn't get to this earlier:

Feature points are based on areas of high and unique visual contrast.  White walls/tabletops and flat-colored carpet are bad.  More dramatically textured surfaces (wood, brick, tile patterns) as well as shadow edges produce features.

The easiest way is to just get a sense for it by playing with it.  HelloAR visualizes the debug point cloud, which lets you get a sense of where ARCore finds features.

**Comment by vishalvanpariya** [comment]
@inio if I want to detect the only table surface, not floor surface so what I want to do?


            var anchor = hitResult.createAnchor()
            var anchorNode = AnchorNode(anchor)
            anchorNode.setParent(arFragment.arSceneView.scene)
            var transformableNode =TransformableNode(arFragment.transformationSystem)
            transformableNode.setParent(anchorNode)
            transformableNode.setRenderable(andyRenderable)
            transformableNode.localPosition = Vector3(0f,0f,0f)
            transformableNode.select()

please give me some solution

**Comment by Wangxuefeng92** [comment]
hi, can we do this in ARCore2.0? how can i use the API?

**Comment by aymusbond** [comment]
Does this work for Cloud Anchors as well?

**Comment by KevinChavda007** [comment]
### How can i place an anchor of the object on a horizontal surface parallelly???

I'm currently working on Indoor navigation with ARCore from source to destination place. So i want to load navigation arrows from source to destination place on a horizontal surface(land) parallelly with zero height(not in the air). I tried many solutions and documentation of ARCore but didn't get the proper and accurate output.

**Comment by KevinChavda007** [comment]
### How can i place an anchor of the object on a horizontal surface parallelly(not in the air)???

I'm currently working on Indoor navigation with ARCore from source to destination place. So i want to load navigation arrows from source to destination place on a horizontal surface(land) parallelly with zero height(not in the air). I tried many solutions and documentation of ARCore but didn't get the proper and accurate output.

**Comment by KevinChavda007** [comment]
### How can i place an anchor of the object on a horizontal surface parallelly(not in the air)???

I'm currently working on Indoor navigation with ARCore from source to destination place. So i want to load navigation arrows from source to destination place on a horizontal surface(land) parallelly with zero height(not in the air) from surface. I tried many solutions and documentation of ARCore but didn't get the proper and accurate output.
