### ISSUE TITLE
Depth Resolution | CPU Visibility Mask

### ISSUE THREAD

**Issue by fkanvaly** [google-ar/arcore-android-sdk#1102]
Hello, 
Please help me with these two questions that I am struggling with. First, with my Samsung s10+ I got 160x90 for the depth map resolution. Why the resolution is so low but I am still getting a good depth map on my phone surfaceview? Secondly, I want to use the depth map with CPU to compute the visibility of 3d points. To do that I think about using ModelViewProjectionMatrix to project 3d point into 2d point on CPU, then use depth map value as a threshold. How can I get the depth map pixel that corresponds to my projected 2d point? Thank you for your time.

**Comment by devbridie** [comment]
The 160x90 depth (and similar resolutions) image is interpolated and stretched to cover the camera image.

For a given `depthImage` and desired position (`x`,`y`) you can find the distance in mm using the following snippet:

    public int getMillimetersDepth(Image depthImage, int x, int y) {
      // The depth image has a single plane, which stores depth for each
      // pixel as 16-bit unsigned integers.
      Image.Plane plane = depthImage.getPlanes()[0];
      int byteIndex = x * plane.getPixelStride() + y * plane.getRowStride();
      ByteBuffer buffer = plane.getBuffer().order(ByteOrder.nativeOrder());
      short depthSample = buffer.getShort(byteIndex);

      // Only the lowest 13 bits are used to represent depth in millimeters.
      return (depthSample & 0x1FFF);
    }

**Comment by fkanvaly** [comment]
I get it. Thank you

**Comment by dodaithach** [comment]
Hi @devbridie, I want to follow up on this topic.
- The camera image from `Frame.acquireCameraImage()` has `640x480` resolution.
- The depth image from `Frame.acquireDepthImage()` has `160x90` resolution, pixel stride is `2` and row stride is `320`. It results in `28800` bytes in the buffer.

I want to get the depth value for every pixel on the camera image. However, your formula seems to cause array out of index. Let's take the position `(639, 479)` in the camera image for example. According to your formula, the `byteIndex` should be:

```
639 * 2 + 479 *320 = 154558
```

That is far out of the buffer size. Do I need to stretch the depth image to `640x480` resolution before applying you formula? Thank you.

**Comment by devbridie** [comment]
`x` should be between `0 until image.getWidth()`, where `image` is either depth image or camera image.

**Comment by dodaithach** [comment]
Thank you for the response @devbridie, please help address the below question as I haven't found the connection between depth image and camera image in any documents so far.

Do I need to stretch the `160x90` depth image to `640x480` resolution before applying you formula?

**Comment by devbridie** [comment]
Stretching the depth image is probably more expensive than scaling the coordinates you're using as inputs for `getMillimetersDepth`.

**Comment by dodaithach** [comment]
I've got your point. Thank you @devbridie.

**Comment by sieme97** [comment]
> The 160x90 depth (and similar resolutions) image is interpolated and stretched to cover the camera image.
> 
> For a given `depthImage` and desired position (`x`,`y`) you can find the distance in mm using the following snippet:
> 
> ```
> public int getMillimetersDepth(Image depthImage, int x, int y) {
>   // The depth image has a single plane, which stores depth for each
>   // pixel as 16-bit unsigned integers.
>   Image.Plane plane = depthImage.getPlanes()[0];
>   int byteIndex = x * plane.getPixelStride() + y * plane.getRowStride();
>   ByteBuffer buffer = plane.getBuffer().order(ByteOrder.nativeOrder());
>   short depthSample = buffer.getShort(byteIndex);
> 
>   // Only the lowest 13 bits are used to represent depth in millimeters.
>   return (depthSample & 0x1FFF);
> }
> ```

Is this give absolute depth values? I have tried this function but depth values seem to be wrong.

**Comment by ruipcf** [comment]
The output is in milimeters from 50 to 8000.

**Comment by wasimsafdar** [comment]
> > The 160x90 depth (and similar resolutions) image is interpolated and stretched to cover the camera image.
> > For a given `depthImage` and desired position (`x`,`y`) you can find the distance in mm using the following snippet:
> > ```
> > public int getMillimetersDepth(Image depthImage, int x, int y) {
> >   // The depth image has a single plane, which stores depth for each
> >   // pixel as 16-bit unsigned integers.
> >   Image.Plane plane = depthImage.getPlanes()[0];
> >   int byteIndex = x * plane.getPixelStride() + y * plane.getRowStride();
> >   ByteBuffer buffer = plane.getBuffer().order(ByteOrder.nativeOrder());
> >   short depthSample = buffer.getShort(byteIndex);
> > 
> >   // Only the lowest 13 bits are used to represent depth in millimeters.
> >   return (depthSample & 0x1FFF);
> > }
> > ```
> 
> Is this give absolute depth values? I have tried this function but depth values seem to be wrong.

How can we interpolate 160x90 depth image? I have camera resolution of 2219*1080. When I interpolate it according to formula in the documentation, I am getting 539*270 but the depth Image is of 160x90.
