### ISSUE TITLE
[Bug] Detecting a tracking image with AR Foundation on Android devices freezes the application

### ISSUE THREAD

**Issue by RVerhoef** [google-ar/arcore-android-sdk#1103]
**Description**
When running a Unity3D application on Android, using AR Foundation, the application experiences randomly freezes when detecting a tracking image. The camera feed will freeze and all code running on the main thread will stop executing. The app itself doesn't seem to crash however.

The issues occurs both when using a mutable image library, or when a predefined library is set up in the editor and used in the build. The issue doesn't seem to have a very clear cause, it could happen after detecting 10 tracking images or when you're detecting the first one. Trying to debug the application through the monitor application of Android Studio or through Visual Studio's debug function doesn't seem to give any results of warnings or errors.

This issue doesn't occur when running the application on iOS devices, probably because under the hood it's AR Kit running the show, not AR Core.

**Additional information**
Builds were tested on these devices:

Motorola One Macro, Android Version 9
One Plus 5, Android Version 10

Builds were made with AR Foundation version 4.1.0 on Unity version 2019.4.6f1. The issue seems less persistent on the Motorola then on the One Plus.

**Comment by devbridie** [comment]
This repository is for `arcore-android-sdk` only, please repost to [`arcore-unity-extensions`](https://github.com/google-ar/arcore-unity-extensions/issues/new) for tracking & triage. Thank you!
