### ISSUE TITLE
SUPPORT DEVİCE?

### ISSUE THREAD

**Issue by yessGlory17** [google-ar/arcore-android-sdk#1105]
Hello, I would like to know if there is a Galaxy Tab S7 + ArCore support. I talked to Samsung and they asked me to ask you.

**Comment by toolgate** [comment]
Hello.
"ARcore Depth Lab" application is not available on my Xiaomi mi 9t pro.
But it is on the list of supported devices (redmi K20 pro)

**Comment by devbridie** [comment]
There is support for the Galaxy Tab S7-- no news on that specific xiaomi phone.
