### ISSUE TITLE
Please stop this ilegal behaviour

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#1111]
My app for showing depthmaps from ToF sensor was suspended from the Google Play Store:

![Screenshot_20200820_080548](https://user-images.githubusercontent.com/6472545/90723119-756c9200-e2bc-11ea-9899-2aa8ff34ef8b.png)

This action from Google is against Google's own policy. The app is showing depthmaps from ToF sensor which works independly on light conditions and it works as a night vision. What I see on Google Play console looks like this:
![Screenshot_20200820_081013](https://user-images.githubusercontent.com/6472545/90723497-207d4b80-e2bd-11ea-8b14-847863b04b39.png)

As you see on following screenshot, Google blocked me to do any operation to resolve "the issue":
![Screenshot_20200820_080305](https://user-images.githubusercontent.com/6472545/90723579-4c003600-e2bd-11ea-9389-89b203ad4ebc.png)

I consulted this with one of my contacts (who had similar issues with Google in the past), his answer is:
### _"We’ve seen this sort of thing before. Normally it’s because they’re planning an AR announcement and they want to knock out any third party apps that are competitive or off-message. I guess something’s coming. Certainly the number of apps in the AR categories has gone down."_

What I see as a possible reason, is that my night vision app showed 100x better depthmaps than DepthAPI can do.

### **Could Google give any statement on this before I do any further steps?**

**Comment by floor51** [comment]
Hi Lubos,

I'm a fan of your work. Your depthmap sensor is really brilliant.

Can you not just change the app's title to be "Tof Viewer" and drop the "Night Vision" bit? 

Possibly there is some kind of CE/medical device style requirement for something to be classed as night vision, and perhaps the hardware itself doesn't meet this.

**Comment by lvonasek** [comment]
Just for info: I received instructions to resubmit my app and my Google Play Console was unblocked, also I can do that. No explanation why it was removed.
