### ISSUE TITLE
Problem with checkAvailibility api

### ISSUE THREAD

**Issue by ehsanbayat** [google-ar/arcore-android-sdk#1115]
hi guys i faced a situation that my device is api level 24 so the api checkAvailability returns supported but not installed but actually the device is not supported in the list of devices in arcore supported list how can id check this ???

my device is sumsung note5

at runtime returns supported but not installed so user is guided to google play services for arcore page in app store but because of unsupported version says its not compatible with this version of your device and when user press back button it throws user decline exception but actually device is not supported and not exists in arcore supported devices just because of api level it passes the conditon !!!!

how can i control this situation and find out device is not actually supported ?????????

**Comment by devbridie** [comment]
Hey,
Thanks for reporting. Please supply the following information so we can diagnose this exact device:

- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

Thanks.
