### ISSUE TITLE
Device not Supported DepthAPI 

### ISSUE THREAD

**Issue by ValentijnSlijper** [google-ar/arcore-android-sdk#1120]
I am trying to get the HelloAR app working properly everything works fine like it should beside de Depth API once i try to enable this it says that my device is not supported even though my device (Xiaomi MI MIX 3) is listed in the supported devices for ARcore and Depth API.

I have been trying to find a solution online but haven't been able to find one yet.

Loving the work so far with the DepthAPI!

- Android Studio: 401
- ARCore SDK for Android: 1.19
- Device manufacturer, model, and O/S: Android / MIUI 11 | Xiaomi MI MIX 3

![Screenshot_2020-09-02-11-33-17-639_com google ar core examples java helloar](https://user-images.githubusercontent.com/54978044/91965151-63eda600-ed10-11ea-805c-8b31a4abd661.jpg)

**Comment by devbridie** [comment]
Could you please link the resource that says that the Mi Mix 3 supports Depth API? The [Supported devices page](https://developers.google.com/ar/discover/supported-devices) does not have Depth API listed for the Mi Mix 3.

![image](https://user-images.githubusercontent.com/442644/92004902-18a0bb00-ed43-11ea-8d80-b6c0c9c459e4.png)
