### ISSUE TITLE
Unable to Change Camera Quality using setCameraConfig

### ISSUE THREAD

**Issue by kehobert** [google-ar/arcore-android-sdk#1121]
### SPECIFIC ISSUE ENCOUNTERED
I tried the demo from the hello_ar_java sample from https://github.com/google-ar/arcore-android-sdk/tree/master/samples/hello_ar_java and it works well, except the quality of the camera was so bad (I think it was 640x480). I already read documentation about setCameraConfig and tried it.

I managed to get list of my supported config, even tried to set the config. But it still does not work 

### VERSIONS USED
- Android Studio: 4.0.1
- ARCore SDK for Android: 1.18.0
- Device manufacturer, model, and O/S: Realme 5 Pro using Color OS 10

### STEPS TO REPRODUCE THE ISSUE
So I created button on the top right of the screen, and when it pressed, it will run the function below. I already printed the cameraConfig data and it returns `com.google.ar.core.CameraConfig@d8a9c6`. I assume the config has been successfully passed to this function.

```
private void onCameraConfigChanged(CameraConfig cameraConfig){
    if (session != null) {
      session.pause();
      session.setCameraConfig(cameraConfig);
      try {
        session.resume();
      } catch (CameraNotAvailableException ex) {
        messageSnackbarHelper.showError(this, "Camera not available. Please restart the app.");
        session = null;
        return;
      }
  }
}
```

I already paused the session then setting the camera Config, but it still doesn't work. Please help with this issue. And thank you very much in advance!

### ADDITIONAL COMMENTS
I'll just attached the photo to describe the issue better
![Screenshot_2020-09-02-22-15-58-69_37b5a2332b97f6915ae7c945061449fd](https://user-images.githubusercontent.com/34390688/92003716-8eb91800-ed6b-11ea-97ee-de6d5987b67f.jpg)

**Comment by devbridie** [comment]
I don't think it's a bug in the SDK. I created [a small patch](https://github.com/devbridie/arcore-android-sdk/commit/89212051eb0636d4a8bb4774596c707ccc91f99c) that co-opts the settings button to switch to the next available camera config. On my device, it shows that pressing the settings button will change the image dimensions of the incoming camera frames.

**Comment by kehobert** [comment]
Hello @devbridie thank you for your reply. I already printed the available camera dimensions and it shows 3 available resolution (the highest one is 1440 x 1080). I already tried to applied that config but it still doesn't work. Maybe later on I'll try your solution.

**Comment by devbridie** [comment]
I'll be closing this bug since it appears to be stale; please feel free to comment if this is still relevant for you. Thanks!
