### ISSUE TITLE
Asus Zenfone 7 Pro not supported

### ISSUE THREAD

**Issue by XcellMiguel** [google-ar/arcore-android-sdk#1126]
Just as the title said, the new Asus Zenfone 7 Pro is not supported, making many apps unavailable or not working properly despite the phone having everything required for AR.

Please allow this phone to use ARCore.

Thanks.

**Comment by devbridie** [comment]
The Zenfone has been added to the [supported devices](https://developers.google.com/ar/discover/supported-devices).
