### ISSUE TITLE
ARCore not compatible with Vivo S7 

### ISSUE THREAD

**Issue by sleepy-Pen** [google-ar/arcore-android-sdk#1129]
HI,

although the Vivo S7 5G is listed among the compatible device, it is actually unable to run it. All the apps (have try with PokemonGo, Houzz and Vuforia View) will crash when the AR mode is on.
pls fix it. Thank you.

**Comment by sandyfriend** [comment]
What is your ARCore version,
It should be running on ARCore 1.19.
Also could you provide below details:
Device manufacturer, model, and O/S: LG Stylo 6 10.0
ARCore:
On Windows, use: adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"
On macOS, use: adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:
Output of adb shell getprop ro.build.fingerprint:

Thanks.

**Comment by sleepy-Pen** [comment]
> What is your ARCore version,
> It should be running on ARCore 1.19.
> Also could you provide below details:
> Device manufacturer, model, and O/S: LG Stylo 6 10.0
> ARCore:
> On Windows, use: adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"
> On macOS, use: adb shell pm dump com.google.ar.core | egrep -i versionName|packages:
> Output of adb shell getprop ro.build.fingerprint:
> 
> Thanks.

Thank you for your reply.
1.19 runs now perfectly. The version from the Application Store might be not up-to-date.
