### ISSUE TITLE
how to load multiple 2D texture on a single 3D Object in AR Core

### ISSUE THREAD

**Issue by RajkumarRepo** [google-ar/arcore-android-sdk#113]
This is load a single texture place in single Object

         Bitmap textureBitmap = BitmapFactory.decodeStream(
            context.getAssets().open(diffuseTextureAssetName));
        GLES20.glActiveTexture(GLES20.GL_TEXTURE0);
        GLES20.glGenTextures(mTextures.length, mTextures, 0);
        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, mTextures[0]);

        GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,
            GLES20.GL_TEXTURE_MIN_FILTER, GLES20.GL_LINEAR_MIPMAP_LINEAR);
        GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,
            GLES20.GL_TEXTURE_MAG_FILTER, GLES20.GL_LINEAR);
        GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, textureBitmap, 0);
        GLES20.glGenerateMipmap(GLES20.GL_TEXTURE_2D);
        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, 0);  

I need to add Multiple image texture load in to the single 3D object using java code

**Comment by inio** [comment]
OpenGL application development is not within the scope of problems we can help with here.   Try StackOverflow?

**Comment by CuteManiMca** [comment]
am also need a solution for that texture changing if you find any solution please update me thanks in advance!

**Comment by inio** [comment]
@CuteManiMca  ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.  Consider using Unreal or Unity, and watch #52 .
