### ISSUE TITLE
Depth API does not work when using with sceneform

### ISSUE THREAD

**Issue by HemanParbhakar** [google-ar/arcore-android-sdk#1131]
### VERSIONS USED
- Android Studio: 4.0.1
- ARCore SDK for Android: com.google.ar:core:1.19.0
- Device manufacturer, model, and O/S:  Samsung S10
- ARCore: com.google.ar.sceneform.ux:sceneform-ux:1.17.1
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. Create a new project.
 2. Add arcore library along with sceneform library. 
 3. Make ar object place upon tap of ARFragment.
 4. Now as the session have enabled depth api as AUTOMATIC.
 5. When you place the AR Object behind any physical object it will be visible as well.

**Comment by devbridie** [comment]
Sceneform doesn't have support for the Depth API, as enhancements to Sceneform had ceased before Depth API's release. No depth information will be used to occlude objects in Sceneform.

**Comment by HemanParbhakar** [comment]
If i want to do the depth API without having knowledge of OpenGL what are the alternatives to that.
