### ISSUE TITLE
Support for Samsung Galaxy A21 missing.

### ISSUE THREAD

**Issue by y2kbadbug** [google-ar/arcore-android-sdk#1136]
Hello,

The Samsung Galaxy A21 is currently missing support for Google ARCore.  I noticed that the Samsung Galaxy A20 is supported and the A21 is similar to the A20 with a few higher specs.  I was hoping you guys could add that support in.

Thank you!

**Comment by devbridie** [comment]
Unfortunately, device similarity doesn't guarantee ARCore certification. No news on the A21 so far. Closing this issue to keep device support requests to the appropriate thread.
