### ISSUE TITLE
Cannot access ARCoreProjectSettings outside of Unity Editor

### ISSUE THREAD

**Issue by TibebuAbera** [google-ar/arcore-android-sdk#1138]
### SPECIFIC ISSUE ENCOUNTERED
Cannot access ARCoreProjectSettings outside of Unity Editor

### VERSIONS USED
- ARCore SDK for Android: 2019.4.5f1

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by JuanDiegoAW** [comment]
Did you manage to find a solution? It's happening to me.

**Comment by TibebuAbera** [comment]
I created a new project, then it was gone. I didn't found a real cause and solution for it.
Good luck.
