### ISSUE TITLE
What are the 3d object file formats ar-core support?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#114]
ar-core sample support only obj file format and one textures.what are the 3d file formats will ar-core support in future,is it possible to  render multiple textures for single obj file?

**Comment by inio** [comment]
ARCore does not support *any* 3d object file formats.  Our sample code supports OBJ, but that shouldn't be considered a capability of ARCore itself.  It's only there so that we have something to draw to demonstrate the use of anchors.

**Comment by ArigarasuthanRepo** [comment]
Ok.with the use of opengl can i render any kind of 3d objects and implement this into ar-core?
