### ISSUE TITLE
Duplicate class issue

### ISSUE THREAD

**Issue by shahviral9990** [google-ar/arcore-android-sdk#1140]
Related to the ARCore SDK for Android.
Library used
    implementation ('com.google.ar.sceneform.ux:sceneform-ux:1.17.1')
which uses com.google.ar:core:1.15.0@aar

com.google.ar:core:1.15.0@aar -> classes.jar has package a.a with class a and b (obfustication)

Because of that facing issue with another library used 
Duplicate class a.a.a found in modules jetified-core-1.15.0-runtime.jar (com.google.ar:core:1.15.0) and jetified-tapcashgo-1.0.0-runtime.jar (id.co.bni:tapcashgo:1.0.0)
Duplicate class a.a.b found in modules jetified-core-1.15.0-runtime.jar (com.google.ar:core:1.15.0) and jetified-tapcashgo-1.0.0-runtime.jar (id.co.bni:tapcashgo:1.0.0)

### VERSIONS USED
- Android Studio: 4.0.1
- ARCore SDK for Android: 1.15.0
- Device manufacturer, model, and O/S: Mac Catalina
- ARCore: 
  adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:
Packages:
    versionName=1.19.202100803
Active APEX packages:
Inactive APEX packages:
Factory APEX packages:
- Output of `adb shell getprop ro.build.fingerprint`: 
Nokia/Plate2_00WW/PL2_sprout:10/QKQ1.190828.002/00WW_4_15G:user/release-keys

Step to reproduce :
- Any other library with obfustication in classes.jar as shown above in error
![image](https://user-images.githubusercontent.com/22595723/94395595-a7a3c600-017d-11eb-86b1-80fe2f933098.png)

**Comment by devbridie** [comment]
I'll try to see if we can prefix our obfuscated outputs in a future release; in the meantime, does a workaround like [this suggestion](https://stackoverflow.com/questions/59991168/duplicate-class-names-in-two-external-third-party-obfuscated-libraries) help?

**Comment by shahviral9990** [comment]
Sure, Thank you

> I'll try to see if we can prefix our obfuscated outputs in a future release; in the meantime, does a workaround like [this suggestion](https://stackoverflow.com/questions/59991168/duplicate-class-names-in-two-external-third-party-obfuscated-libraries) help?

**Comment by Lans** [comment]
> That's great, Thank you
> 
> > I'll try to see if we can prefix our obfuscated outputs in a future release; in the meantime, does a workaround like [this suggestion](https://stackoverflow.com/questions/59991168/duplicate-class-names-in-two-external-third-party-obfuscated-libraries) help?

so,how to slove it . could you show you code?

**Comment by cpsauer** [comment]
@devbridie, any chance of still getting a fix for the root cause? Looks like  there are still a few classes making their way through without a prefix as of 1.25. 

Maybe `--keeppackagenames` [would fix things](https://stackoverflow.com/questions/5784281/proguard-avoiding-naming-collisions-with-pre-obfuscated-library-jars)?

**Comment by devbridie** [comment]
We're looking to distribute a fix with the upcoming release!

**Comment by prawnpie** [comment]
@devbridie FYI: I'm seeing the a.a.a class conflict with a class in `com.android.installreferrer:installreferrer:2.2`
![image](https://user-images.githubusercontent.com/3914688/126413712-f1375db1-ad3c-4079-be42-7bbc260daeba.png)
Maybe you could reach out to that team to scope the proguard outputs as well.

**Comment by devbridie** [comment]
I've sent out a patch for the Install Referrer team; thanks for that!

**Comment by cpsauer** [comment]
:) Great to see this fixed in 1.26
