### ISSUE TITLE
Drawing Line between two anchors Android ?

### ISSUE THREAD

**Issue by HemanParbhakar** [google-ar/arcore-android-sdk#1141]
### VERSIONS USED
- Android Studio: 4.0.1
- ARCore SDK for Android: 1.19.0
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. Place two anchors connect them using line.
 1.
 1.

**Comment by devbridie** [comment]
[`Anchor.getPose()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Anchor#getPose()) can be used to determine the location of anchors in world coordinates. After that, you'll need to use OpenGL to draw a line between the two coordinates; the ARCore SDK doesn't provide any functionality for graphics.
