### ISSUE TITLE
Question about v 19 example code and PointCloud

### ISSUE THREAD

**Issue by brianm-sra** [google-ar/arcore-android-sdk#1142]
Sorry, this is probably not the right place to ask this question, but I just noticed that in 
the latest release ( 19 ) this file from the hello_ar_java sample app was removed

src/main/java/com/google/ar/core/examples/java/common/rendering/PointCloudRenderer.java

I am curious why it was removed?

Is Google planning to deprecate or change PointCloud or Frame.acquirePointCloud() 
in the near future (next 3-6 months) ?

**Comment by devbridie** [comment]
There currently aren't any plans to change PointCloud or acquirePointCloud-- it's just that the rendering logic was changed and moved into [the activity](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/HelloArActivity.java#L332).
