### ISSUE TITLE
Need the AR image generated by ARCore

### ISSUE THREAD

**Issue by jaggar28** [google-ar/arcore-android-sdk#1144]
Hi,
I'm currently developing an ARCore app based on Unreal engine 4. Apparently, there is no way I can get access to the generated AR Image (processed by ARCore). 

1. I was going through the "arcore_c_api.h" file, and I've found a function "ArFrame_acquireCameraImage()" which reads the "CPU image for the current frame". Is this the unprocessed image from the camera? Or is this Augmented?

2.  In the header file it's mentioned that, in order to get the RAW image, i need to call ArFrame_acquireCameraImage() -> ArImage_getNdkImage() -> ArImage_release();

3. The RAW image format is called AIMAGE_FORMAT_YUV_420_888. Where can I get more info about this format?

Many thanks in advance.

Regards

**Comment by devbridie** [comment]
Hey,
* CPU image refers to the image that ARCore uses for computation and world-sensing. It's usually a smaller size than the GPU image to save computational resources. 
* `ArImage_getNdkImage()` is deprecated ([see developer documentation](https://developers.google.com/ar/reference/c/group/ar-image#group___ar_image_1gac88574bf3291ccf0c8a80a2e490fb4fd)). In general, you'd probably want to use the data supplied on ArImage itself (eg ArImage_getPlaneData and friends).
* `AIMAGE_FORMAT_YUV_420_888 ` refers to the Android YUV 420 image format. [Here's some documentation on that](https://developer.android.com/ndk/reference/group/media#group___media_1gga9c3dace30485a0f28163a882a5d65a19aea9797f9b5db5d26a2055a43d8491890).

**Comment by jaggar28** [comment]
Hi, 
Many thanks for the reply. I'm developing an AR application in Unreal Engine 4. I desperately need to Augmented Camera image (Augmented object overlaid on the camera image). Could you give me some idea where I can find this image? ARCore is processing it, but I cannot access it via Unreal Engine. I've been looking into the ARCore source code, but its not commented, so it's very hard to understand.

Also, if I could get the Augmented Video feed, then that would be even better!

Many thanks in advance.

**Comment by devbridie** [comment]
I'm not exactly familiar on that platform, but I don't think ARCore has such a capability-- it will likely leave the rendering up to UE and be done with it. Is it possible for you to render to some sort of framebuffer and query this framebuffer?

**Comment by jaggar28** [comment]
Thank you very much. I'll look into the frame buffer you mentioned, but this will probably require me to dive into the Unreal render engine code which is a nightmare lol, as its uncommented as well. But its a useful suggestion, thx.

**Comment by zhmxiaowo** [comment]
ArImage_getNdkImage() is deprecated
so how can i get the image data?
is the ArImage_getPlaneData()
