### ISSUE TITLE
Hello_ar_java will quit when running in Vivo S7 5G

### ISSUE THREAD

**Issue by EmilyChai** [google-ar/arcore-android-sdk#1145]
### SPECIFIC ISSUE ENCOUNTERED
Hi,

I buy vivo s7 5G for ARCore development according to
https://developers.google.com/ar/discover/supported-devices#android_china

However, when I use Android studio 4.0.1 to run ARCore sample app Hello_ar_java from source code from
https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.19.0

At first, the app can run smoothly, when run for a while, the app will quit suddenly. Checking the log, there is no any fatal exception or system error.

### VERSIONS USED
- Android Studio: 4.0.1
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: Vivo s7 5G,  V2020A, Funtouch OS_10.5, Android 10
- Google Play Services for AR (ARCore):  
Packages:
    versionName=1.19.202100863
    signatures=PackageSignatures{c9b2cc9 version:3, signatures:[53bcc66f], past signatures:[]}
    Packages
      PackageSetting{60378d com.google.ar.core/10255}
Active APEX packages:
Inactive APEX packages:
Factory APEX packages:
    mLockTaskPackages (userId:packages)=
    packages
    packages
    packages
    packages

- Output of `adb shell getprop ro.build.fingerprint`: 
vivo/PD2020/PD2020:10/QP1A.190711.020/compiler09232245:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Download source code from https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.19.0
 2. Use android studio to load the hello_ar_java project to run the app in Vivo s7 5G
 3. Open the app, notification for download arcore apk shown, download from vivo store.
 4. Open the app again, app run ok, searching for plane, then searching for another plane in different direction...
 4. Run for a while, the app will quit suddenly, no fatal exception or system error shown.

### WORKAROUNDS (IF ANY)
No

### ADDITIONAL COMMENTS
Could you please help to check if I miss something, or use the wrong version for arcore apk?
Why my vivo s7 cannot run even the basic sample app smoothly?

**Comment by devbridie** [comment]
There definitely should be an error in the logcat-- could you reproduce the crash and provide the logcat filtered by `com.google.ar.core.examples.java.helloar`?

**Comment by EmilyChai** [comment]
Hi, @devbridie , Thanks a lot for your quick response.
This is the log I catch using adb logcat > helloarcrash_whole_log.txt
[helloarcrash_whole_log.txt](https://github.com/google-ar/arcore-android-sdk/files/5358316/helloarcrash_whole_log.txt)

This is the log I catch using Android studio log tool filter by "com.google.ar.core.examples.java.helloar"
[helloarcrash_filter_log.txt](https://github.com/google-ar/arcore-android-sdk/files/5358315/helloarcrash_filter_log.txt)

Please check. Thanks!

**Comment by jewelcai** [comment]
I also met with this issue, any idea now?

**Comment by EmilyChai** [comment]
Hi, @devbridie  Any updates for this issue?

**Comment by devbridie** [comment]
Does this patch fix the problem? Please see [my branch](https://github.com/google-ar/arcore-android-sdk/commit/3192252a79ec76b82753b505b4397dddf3f65706).
