### ISSUE TITLE
HelloAR Sample App Issues across Various Emulator System Images

### ISSUE THREAD

**Issue by maluhia** [google-ar/arcore-android-sdk#1148]
### SPECIFIC ISSUE ENCOUNTERED
Cannot have both the HelloAR Sample app and a prebuilt armeabi-v7a + arm64-v8a APK working on any AVD.

### VERSIONS USED
- Android Studio: 4.1
- ARCore SDK for Android: 1.20
- Device manufacturer, model, and O/S: Emulator Pixel 4 API 28
- Google Play Services for AR (ARCore): 1.20.202550253
- Output of `adb shell getprop ro.build.fingerprint`: google/sdk_gphone_x86_64/generic_x86_64:9/PSR1.180720.122/6736742:userdebug/dev-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Create new AVD
 2. Install `Google_Play_Services_for_AR_1.20.0_x86_for_emulator.apk`
 3. Run HelloAR app. If it works, attempt to install an ARM APK such as [this](https://play.google.com/store/apps/details?id=com.csreporters.HoloModels)

### WORKAROUNDS (IF ANY)
I have tried all configurations of the emulator to see if I can have both AR and this app working, to no avail. See below.
Pixel 4 Emulator with the following Google APIs Intel x86 Atom System Image:
- API 27 rev 11 x86:		HelloAR works, APK doesn't install (endless load)
- API 28 rev 9 x86:		HelloAR crashes, APK installs (no Google APIs Intel x86 Atom System Image?)
- API 28 rev 11 x86_64:	HelloAR works, APK doesn't install (no matching ABIs)
- API 28 x86_arm rev 10:	HelloAR crashes, APK installs but get warning that device does not meet requirements
- API 29 rev 11 x86:		HelloAR works, APK doesn't install (no matching ABIs)
- API 29 rev 11 x86_64:	HelloAR works, APK doesn't install (no matching ABIs)
- API 30 rev 8 x86:		HelloAR crashes, APK installs
- API 30 rev 8 x86_64:	HelloAR crashes, APK installs

### ADDITIONAL COMMENTS
The [AR emulator guide](https://developers.google.com/ar/develop/java/emulator#get_android_studio_and_sdk_tools_for_arcore) mentions to use `Android 8.1 (Oreo), Google APIs Intel x86 Atom System Image API Level 27, version 4 or later,` but as you can see above, HelloAR works with API 28 rev 11 x86_64, API 29, and not in API 30. Will we see AR Emulation working in API 30 in the future, or is only API 27 officially supported?

Also, it says [here](https://www.reddit.com/r/androiddev/comments/frsgwl/run_arm_apps_on_the_x86_android_11_emulator/flz1osz/?utm_source=reddit&utm_medium=web2x&context=3) that Android 10 (29) is also getting ARM translation support in the emulator. Would this be another x86_arm system image which doesn't work with ARCore then, as with API 28 x86_arm?

**Comment by devbridie** [comment]
This was fixed in 1.24!
