### ISSUE TITLE
Duplicate class a.a.a in core-1.15.0-runtime.jar 

### ISSUE THREAD

**Issue by Lans** [google-ar/arcore-android-sdk#1149]
### SPECIFIC ISSUE ENCOUNTERED

 VERSIONS USED
- Android Studio: 4.1
- ARCore SDK for Android: 1.15
- Device manufacturer, model, and O/S: android

Duplicate class a.a.a found in modules ad-sdk-open.jar  and core-1.15.0-runtime.jar (com.google.ar:core:1.15.0)

**Comment by devbridie** [comment]
Duplicated by #1140, please check that thread for a workaround.

**Comment by Lans** [comment]
Download Core.aar, then unzip it, modify classes.jar. Modify a.a to another name, and repackage classes.jar. Replace the original classes.jar. Finally pack the new aar

**Comment by kimljx** [comment]
i changed my proguard-rules file,just remain my class name
