### ISSUE TITLE
Is it possible to load .mtl files in ar-core android sample?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#115]
In ar-core sample .obj files and texture files for obj files were rendered.is it possible to load .mtl files?

**Comment by inio** [comment]
General OpenGL application development questions are not within the scope of problems we can help with here. Our sample code uses obj files only as an example of how someone *could* use ARCore, not as a core capability.  Maybe try StackOverflow?
