### ISSUE TITLE
Occlusion bug using Depth API in Unity 2018.4 ('HelloAR' demo scene) 

### ISSUE THREAD

**Issue by kyeong-min-kim** [google-ar/arcore-android-sdk#1153]
### VERSIONS USED
Unity: 2018.4.28f1
ARCore SDK for Unity: 1.2.0
Gradle: 5.6.4
Device manufacturer, model, and O/S: Galaxy Note 8(Andorid OS 9), Galaxy s10(Andorid OS 10)
Unity Editor PC: Windows10 Pro

### STEPS TO REPRODUCE THE ISSUE
Currently, there is a bug where an afterimage appears in the camera background when using the Depth API. (See attached image)
https://www.dropbox.com/s/0404grnjr9ctd13/Screenshot_20201029-210437_SpectatorV.jpg?dl=0
https://www.dropbox.com/s/sbm8ctyn3123j83/Screenshot_20201029-210458_SpectatorV.jpg?dl=0

Testing took place in the'HelloAR' demo scene

The afterimage is continuously updated every 5 to 10 seconds, and the occluded object is not properly occluded because it is covered by the afterimage texture.

What I further discovered is that when I disable the'DepthEffect' script the bug goes away. It seems to have something to do with the DepthEffect script.

Is there any way to fix this issue?

### WORKAROUNDS (IF ANY)
In Unity 2017.4.40f1, we have confirmed that the Depth API is working properly and functions neatly without afterimages.

It seems unclear whether it is a problem with the Unity version or the Gradle version.

**Comment by kyeong-min-kim** [comment]
#745
It is the same issue as this one.

**Comment by devbridie** [comment]
Are you using a recent version of the [DepthEffect](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/Common/Scripts/DepthEffect.cs) script? It seems that this problem was fixed in March. Try using this version and let me know if that fixes the after images.
