### ISSUE TITLE
Facing issue while installing demo builds of Augmented Reality into emulator

### ISSUE THREAD

**Issue by appinfoindia** [google-ar/arcore-android-sdk#1154]
Hi,

I am working on Augmented reality in android. I have done setup of emulator to run the demo apk provided on GitHub with name “Google_Play_Services_for_AR_1.20.0_x86_for_emulator.apk”. But when I am trying to install the apk, it not showing into the application section in emulator.  I tried to install the apk on API version 30, CPU/ABI x86_64 and x86 both. Emulators were pixel 4 and pixel 3.

I found another demo code for the same functionality, I have done the setup for same as well but in this case demo is installing in the emulator and I have also installed the Google Services for AR into both emulators. But when I am opening the application I am getting toast every time “This device does not support AR”. Code link is below for this demo code:

https://www.journaldev.com/21479/android-augmented-reality-arcore-example

Can anyone help me out in this problem?

Thanks!

**Comment by devbridie** [comment]
Just to make sure-- did you try the instructions on [the developer site](https://developers.google.com/ar/develop/java/emulator#update-arcore), and are you using `hello_ar_java`? Are you using the Google APIs system image? Please send a screenshot of the emulator configuration.

**Comment by appinfoindia** [comment]
Yes, i am using "hello_ar_java". But when I am opening the application I am getting snackbar with message “This device does not support AR” every time. Please check the configuration of my emulator in attached screenshot.
<img width="1278" alt="Screenshot 2020-11-09 at 3 29 47 PM" src="https://user-images.githubusercontent.com/55690565/98527258-cdee7280-22a0-11eb-9db4-5c08b63b8433.png">

**Comment by somethingbeta** [comment]
@appinfoindia  Try with API 29 -

**Comment by devbridie** [comment]
This was fixed in 1.24!
