### ISSUE TITLE
Is WebAR dead?

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#1157]
None of repositories for WebAR were updated since May 2019 and the experience of WebXR demos experiences are far behind of any recent native app experience. E.g. here:
https://immersive-web.github.io/webxr-samples/hit-test.html

I would like to know what's the status of it as there is a huge distrust in Google AR/VR projects from app developers side (because of too many discontinued projects last two years).

Thank you for any kind of information on this topic.

**Comment by rkochman** [comment]
Yes, we continue to work on WebXR AR features. You can see recent discussions here: 
https://github.com/immersive-web/webxr/issues

You can see some of the work we've been doing in Chrome here: 
https://web.dev/web-ar/

**Comment by jmscxnulleins** [comment]
> Yes, we continue to work on WebXR AR features. You can see recent discussions here: https://github.com/immersive-web/webxr/issues
> 
> You can see some of the work we've been doing in Chrome here: https://web.dev/web-ar/

Thanks!
