### ISSUE TITLE
Flutter plugin not installed!!!(Bug!)

### ISSUE THREAD

**Issue by tanny99** [google-ar/arcore-android-sdk#1158]
### SPECIFIC ISSUE ENCOUNTERED
Its a bug, my android studio runs flutter properly just doesn't show on Windows PowerShell when i run "flutter doctor"!!

### VERSIONS USED
- Android Studio: 4.1.1 

### ADDITIONAL COMMENTS
-Not able to find path of flutter plugin in this new version.

**Comment by devbridie** [comment]
Hi, I don't think this is in the correct section; we're not related to Flutter. Perhaps [the StackOverflow tag for flutter](https://stackoverflow.com/tags/flutter) would be better?
