### ISSUE TITLE
how can i add .mtl and .png together to load 3d model

### ISSUE THREAD

**Issue by plutomen** [google-ar/arcore-android-sdk#1159]
I want to add 3d model which is having .obj , .mtl ,.png all of files 
how can i add .mtl and .png together to load 3d model
 virtualObject.createOnGlThread(/*context=*/ this, "models/andy.obj", "models/andy.png");
I have .mtl file for .obj 
how to add this 
please help

**Comment by devbridie** [comment]
Our sample renderer doesn't support mtls. For more complicated rendering solutions, you'll probably want a library like [Filament](https://github.com/google/filament) ([see a sample rendering using a gltf](https://github.com/google/filament/blob/main/android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt)).

**Comment by plutomen** [comment]
okay thank you
