### ISSUE TITLE
Android Arcore crashes in Moto G4 OS 7.0

### ISSUE THREAD

**Issue by AkJoshi99** [google-ar/arcore-android-sdk#116]
Hello,
 I am following the steps from the source
 https://developers.google.com/ar/develop/java/getting-started

After Setup and build the code successfully , while I am opening the app in Moto G4 OS 7.0 the Arcore (hello_ar_java) crashes every time. Please check the issue

**Comment by AkJoshi99** [comment]
oops, I just chek this link

https://developers.google.com/ar/discover/#supported_devices

Acore support is rlimited to that device

**Comment by inio** [comment]
Duplicate of #89
