### ISSUE TITLE
HelloAR_java example crash

### ISSUE THREAD

**Issue by heartfeather** [google-ar/arcore-android-sdk#1162]
### SPECIFIC ISSUE ENCOUNTERED
HelloAR_java example crashes on Pixel 3a and Pixel 4 emulators with API 29 and API 30

### VERSIONS USED
- Android Studio: 4.1.1
- ARCore SDK for Android: 1.21.0
- Device manufacturer, model, and O/S: Pixel 3a API 29 and API 30 emulator, Pixel 4 API 29 and API 30 emulator
- Google Play Services for AR (ARCore):  version 1.21.202940553, version 1.20.202550253, version 1.19.202100853
- Output of `adb shell getprop ro.build.fingerprint`: N/A

### STEPS TO REPRODUCE THE ISSUE
 1. Install Android Studio
 2. download ARCore SDK and built it following ARCore Quickstart guide: https://developers.google.com/ar/develop/java/quickstart
 3. Run the app and it crashes with the error message:
E/AndroidRuntime: FATAL EXCEPTION: GLThread 447
    Process: com.google.ar.core.examples.java.helloar, PID: 12543
    java.lang.IllegalArgumentException: eglChooseConfig failed
        at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:883)
        at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1054)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1431)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
I/Process: Sending signal. PID: 12543 SIG: 9

**Comment by heartfeather** [comment]
Setting OpenGL ES support to 3 and use desktop native opengl render solved the issue. Wish these are mentioned in the ARCore Quickstart documentation.

**Comment by somethingbeta** [comment]
new to all this when you say:

> Setting OpenGL ES support to 3 and use desktop native opengl render solved the issue. Wish these are mentioned in the ARCore Quickstart documentation.

where/how do you do this please

**Comment by devbridie** [comment]
(screenshot attached)
1. Open your AVD.
2. Use the overflow button on the right-hand pane,
3. Choose Settings.
4. Choose Advanced.
5. Change  OpenGL ES API Level and OpenGL ES renderer.

**Comment by somethingbeta** [comment]
> (screenshot attached)
> 
> 1. Open your AVD.
> 2. Use the overflow button on the right-hand pane,
> 3. Choose Settings.
> 4. Choose Advanced.
> 5. Change  OpenGL ES API Level and OpenGL ES renderer.
> 
> ![image](https://user-images.githubusercontent.com/442644/103536349-a37cf800-4e92-11eb-8756-ff8217e9c496.png)

OpenGL ES support to 3 
Presumably this is via Android Manifest file i.e. using this 

  <uses-feature android:glEsVersion="0x00030000" android:required="true" />

instead of 
  <uses-feature android:glEsVersion="0x00020000" android:required="true" />


Thanks

**Comment by somethingbeta** [comment]
For reference in case some stumbles across this again 

At the time of writing, worked for me with @devbridie  suggestion, using the below as the selected options

Desktop Native Open GL
Renderer maximum (up tp OPenGL ES 3.1)

`<uses-feature android:glEsVersion="0x00020000" android:required="true" />`

Pixel 4 0 API 29 .. 

It did not work for API 30 ..
