### ISSUE TITLE
 library "libarcore_sdk_c.so" not found at com.google.ar.core.Session.<init>(Session.java:6)

### ISSUE THREAD

**Issue by steven-gao** [google-ar/arcore-android-sdk#1163]
### SPECIFIC ISSUE ENCOUNTERED
hi,
today i run my app ,crashed many times in my aractivity,
the log as follows 

java.lang.UnsatisfiedLinkError: dlopen failed: library "libarcore_sdk_c.so" not found at com.google.ar.core.Session.<init>(Session.java:6)
thank you for your time
### VERSIONS USED
- Android Studio: 4.1.1
- ARCore SDK for Android: 1.16.0
- Device manufacturer, model, and O/S: huawei mate20
- Google Play Services for AR (ARCore):  1.20.202550263
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. show ar page

**Comment by devbridie** [comment]
Are you using [`checkAvailability`](https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk#checkAvailability(android.content.Context)) and [`requestInstall`](https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk#requestInstall(android.app.Activity,%20boolean))? What values do they report?

**Comment by steven-gao** [comment]
> Are you using [`checkAvailability`](https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk#checkAvailability(android.content.Context)) and [`requestInstall`](https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk#requestInstall(android.app.Activity,%20boolean))? What values do they report?
i created a class which extends com.google.ar.sceneform.ux.BaseArFragment,in it i see the method initializeSession() using requestInstall and i override method handleSessionException,but i not using checkAvailability, do i using checkAvailability method necessary ？
thany you for your time

**Comment by devbridie** [comment]
I had missed that you reported ARCore 1.16-- this has most likely been fixed on the latest release. Try updating the ARCore version.

**Comment by jinglebiscuitsHL** [comment]
I'm also running into this issue. Updating ARCore did not fix the problem. A team mate suggests that this issue only exists on debug builds, but I can't confirm that.

**Comment by devbridie** [comment]
@jinglebiscuitsHL, does the Hello AR sample run on the device?

**Comment by jinglebiscuitsHL** [comment]
Yes. My app also runs most of the time. However, I will see this error once every few days.

**Comment by Harichachi** [comment]
I am having the same issue as @jinglebiscuitsHL and I have checked if I have that library and I have it :(
Does someone knows how to solve it?
