### ISSUE TITLE
Device is not supported

### ISSUE THREAD

**Issue by piotr-onyszczuk** [google-ar/arcore-android-sdk#1165]
### SPECIFIC ISSUE ENCOUNTERED

With my configuration I'm getting 'Device is not supported' when creating session in hello_ar java project. I've installed Google Play Services for AR. According to documentation device should be supported with this version of API?

Full logs in attachment

[logs2.txt](https://github.com/google-ar/arcore-android-sdk/files/5624596/logs2.txt)

### VERSIONS USED
- Android Studio: 

> Android Studio 4.1.1
> Build #AI-201.8743.12.41.6953283, built on November 5, 2020
> Runtime version: 1.8.0_242-release-1644-b01 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1246M
> Cores: 4
> Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
> Non-Bundled Plugins: Dart, io.flutter

- ARCore SDK for Android: v1.21.0
- Device manufacturer, model, and O/S: 

> Name: pixel_2_pie_9_0_-_api_28
> CPU/ABI: Google Play Intel Atom (x86)
> Path: C:\##\.android\avd\pixel_2_pie_9_0_-_api_28.avd
> Target: google_apis_playstore [Google Play] (API level 28)
> Skin: pixel_2
> SD Card: 512M
> hw.dPad: no
> hw.lcd.height: 1920
> hw.accelerometer: yes
> hw.device.name: pixel_2
> vm.heapSize: 256
> hw.device.manufacturer: Google
> hw.lcd.width: 1080
> hw.gps: yes
> image.androidVersion.api: 28
> hw.audioInput: yes
> image.sysdir.1: system-images\android-28\google_apis_playstore\x86\
> tag.id: google_apis_playstore
> showDeviceFrame: yes
> hw.camera.back: virtualscene
> hw.mainKeys: no
> hw.camera.front: emulated
> hw.lcd.density: 420
> avd.ini.displayname: Pixel 2 Pie 9.0 - API 28
> hw.arc: no
> hw.gpu.mode: auto
> hw.device.hash2: MD5:55acbc835978f326788ed66a5cd4c9a7
> fastboot.forceFastBoot: yes
> hw.ramSize: 1536
> hw.trackBall: no
> PlayStore.enabled: true
> fastboot.forceColdBoot: no
> hw.battery: yes
> hw.cpu.ncore: 4
> hw.sdCard: yes
> tag.display: Google Play
> hw.keyboard: yes
> hw.sensors.proximity: yes
> disk.dataPartition.size: 6442450944
> hw.sensors.orientation: yes
> avd.ini.encoding: UTF-8
> hw.gpu.enabled: yes

- Google Play Services for AR (ARCore):  1.21.202940533
- Output of `adb shell getprop ro.build.fingerprint`: google/sdk_gphone_x86_arm/generic_x86_arm:9/PSR1.180720.117/5875966:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Run the newest version of hello_ar project with mentioned configuration.

**Comment by devbridie** [comment]
I'm still working on the root cause of this, but `sdk_gphone_x86_arm` (from your fingerprint) doesn't seem to be on the allowed list. Instead the system image you used in #1164 is the correct one.

**Comment by piotr-onyszczuk** [comment]
Thank you for explanation. Closing then.
