### ISSUE TITLE
Android studio dont regonize hand_tracking_aar file 

### ISSUE THREAD

**Issue by ShahmirJlavyan** [google-ar/arcore-android-sdk#1168]

**Comment by devbridie** [comment]
What is `hand_tracking_aar`?

**Comment by ShahmirJlavyan** [comment]
@devbridie hand_tracking_aar is medipipe lib hand_tracking_aar.aar in project -> lib folder all medipipe imports dont regonized for exampale
import com.google.mediapipe.components.CameraHelper;
import com.google.mediapipe.components.CameraXPreviewHelper;
import com.google.mediapipe.components.ExternalTextureConverter;
import com.google.mediapipe.components.FrameProcessor;
import com.google.mediapipe.components.PermissionHelper;
import com.google.mediapipe.formats.proto.LandmarkProto;
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmark;
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmarkList;
import com.google.mediapipe.framework.AndroidAssetUtil;
import com.google.mediapipe.framework.PacketGetter;
import com.google.mediapipe.glutil.EglManager;
all show red and dont regonized

**Comment by devbridie** [comment]
This isn't an ARCore issue, but try https://google.github.io/mediapipe/getting_started/android_archive_library.html/
