### ISSUE TITLE
Is it possible to run the Android ARCore Augmented Faces example on a prerecorded video (i.e. not live session)?

### ISSUE THREAD

**Issue by alexrichardson21** [google-ar/arcore-android-sdk#1169]
I am running the augmented_faces_java example from arcore-android-sdk and there seems to be no simple way to get the example running on a prerecorded mp4 video. A call to `session.update()` always returns a frame containing the current live camera image. Is there a way to maybe get the camera to see another image/video instead of live camera feed?
```
// Obtain the current frame from ARSession. When the configuration is set to
// UpdateMode.BLOCKING (it is by default), this will throttle the rendering to the
// camera framerate.
Frame frame = session.update();
Camera camera = frame.getCamera();
```

**Comment by devbridie** [comment]
Check out [Playback and Recording](https://developers.google.com/ar/develop/java/recording-and-playback), if you can still re-record your video. There's no support for mp4s that weren't created with ARCore, however.

**Comment by alexrichardson21** [comment]
Yes I looked through that but I'd like to get ARCore working on a given video from a user's camera roll. I know Augmented Faces doesn't actually need the gyroscope or depth data to predict a 3D face mesh. It seems like the network only utilizes the current image for mesh predictions so why limit the functionality to live camera feed?

**Comment by devbridie** [comment]
No guarantees here, but you might be able to swap out just the CPU track from a skeleton ARCore recording using ffmpeg or a similar solution, allowing your mp4 to retain ARCore metadata.

No word on supporting recordings that weren't generated with ARCore, though.
