### ISSUE TITLE
Where is the code of recognizing plane?

### ISSUE THREAD

**Issue by wzywzy** [google-ar/arcore-android-sdk#117]
Recently, I've noticed the Google ARCore demo on github (HelloAR). The source code is about how to render pointcloud, plane, robot... If I want to test the latency of recognizing plane (the core function of AR), how should I do? If you would like to give me some advice, I'd be very grateful!

**Comment by inio** [comment]
Plane detection happens deep within ARCore and is not part of our released sample code.

**Comment by wzywzy** [comment]
a. recognizing plane
b. render something

Are these two procedure serialized, which means the program must do a, then do b?

Can you give me your email address? :)

**Comment by inio** [comment]
Plane detection time is a function of surface texture (diffuse color texture good, speculars bad), device motion, and camera details (FOV, sharpness, noise).  Once detected, the plane will be reported in the next `Frame`'s `getUpdatedTrackables()` (0-33ms latency).  From there it's entirely under the control of application code as to when it shows up on the screen (generally ~15ms rendering and ~30ms waiting for the rendered buffer to actually make it through the graphics stack to the screen).

**Comment by haris-tankovic** [comment]
@inio  Is it possible to expand detected plane to infinity? If so, how can I do it?

**Comment by wzywzy** [comment]
But when I insert timestamp into the code, I find the latency can be few seconds rather than milliseconds. Would you like to give me your email address? :)

**Comment by inio** [comment]
@haris-tankovic I think that's more of a StackOverflow question.  We provide sufficient state to compute a plane equation, if you want to do hit tests against an infinite extension of a particular plane, you should be able to work out the math.

@wzywzy Detection can take an uncertain amount of time as a function of plane texture and device motion.  This can be seconds for common situations but some things (for example a flat-colored desk) detection may never occur as there's not enough visual information.  The reporting and rendering once detected is effectively immediate.

**Comment by syedabdullahshahkazmi** [comment]
> @inio Is it possible to expand detected plane to infinity? If so, how can I do it?

i need answer
