### ISSUE TITLE
ARcore drift in auto focus mode

### ISSUE THREAD

**Issue by happyfrank** [google-ar/arcore-android-sdk#1171]
Is the fixed-focus mode much more stable than auto-focus mode in ARcore?

I tested it. It is easy to drift in auto focus mode.

**Comment by devbridie** [comment]
I'm not aware of any difference in tracking between fixed-focus mode and auto-focus mode. Are you fixing your object against an Anchor instead of in fixed world space?

**Comment by lvonasek** [comment]
I also experienced worse motion tracking when autofocus is enabled, especially on phones with low quality of camera calibration (typically Samsung devices).
