### ISSUE TITLE
Gltf model rendered into the head

### ISSUE THREAD

**Issue by MatHeartGaming** [google-ar/arcore-android-sdk#1172]
### SPECIFIC ISSUE ENCOUNTERED
Hi everyone! I stumbled upon a weird issue while using ARCore and Sceneform. The issue on hand regards the fact that the object's center is rendered in the center of the region pose. It's a bit hard to explain actually. We're loading gltf models at runtime, I don't know if it could be of some use. The thing is that models are being rendered literally into the head of the user when they are not "long" enough so that the model's center can be located into the user's head center. I'm attaching a Blender file with the placement of the model hoping that someone may help.

### VERSIONS USED
- Android Studio: 4.1.1
-Using: com.google.ar.sceneform.ux:sceneform-ux:1.12.0
            com.google.ar.sceneform:assets:1.15.0
            com.google.ar.sceneform:core:1.12.0
- Google Play Services for AR (ARCore): Latest version 

### WORKAROUNDS (IF ANY)
The only workaround is to duplicate the model and place it behind the original model looking backwards and with proper spacing between the two so the center of the two models falls between the models and on the center of the head.

This is the gltf model: https://drive.google.com/file/d/1HKSwmxlc2VhZr1OXIBRvylgxIKsxaLuf/view?usp=sharing

Thanks to anyone that can give us some help!

**Comment by devbridie** [comment]
This isn't exactly an ARCore issue, but you could try using the latest OSS sceneform and checking it there. Otherwise you might want to look into deriving from a Node to apply your offset / duplication rendering workaround.
