### ISSUE TITLE
How to make my app available on GPlay only to devices that support Depth API ?

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1174]
Hi,

I have an app that uses Depth API. 

As mentioned here:
https://developers.google.com/ar/discover/supported-devices

Depth API is not supported by all devices that support ARCore.

How can I specify in my Manifest (or elsewhere) that my app requires a device compatible with Depth API ? Indeed, I don't want to see my app to be downloaded by users who can't use it!

Thanks

**Comment by lvonasek** [comment]
<uses-feature android:name="com.google.ar.core.depth" android:required="true" />
