### ISSUE TITLE
Black camera texture when using shared front camera with AugmentedFaceMode.MESH3D enabled

### ISSUE THREAD

**Issue by FabianRueckert** [google-ar/arcore-android-sdk#1176]
### VERSIONS USED
- Android Studio: 4.1.1
- ARCore SDK for Android: v1.22.0
- Device manufacturer, model, and O/S: Google Pixel 3, Samsung S10
- Google Play Services for AR (ARCore):  1.22.203220503
- Output of `adb shell getprop ro.build.fingerprint`: google/blueline/blueline:11/RQ1A.201205.003/6906706:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
Modify [shared camera example](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/shared_camera_java/app/src/main/java/com/google/ar/core/examples/java/sharedcamera/SharedCameraActivity.java):

Use 
```
new Session(this, EnumSet.of(Session.Feature.SHARED_CAMERA, Session.Feature.FRONT_CAMERA));
```
and
```
config.setAugmentedFaceMode(Config.AugmentedFaceMode.MESH3D);
```

1. Launch modified shared camera example
2. Toggle between AR and non-AR camera
Result: 
When started in non-AR mode, the camera texture flickers then stays black.
When started in AR mode, the camera texture is always black after switched to non-AR mode.

### WORKAROUNDS (IF ANY)

When the camera is black during non-AR mode
```
      sharedCamera.getSurfaceTexture().detachFromGLContext();
      sharedCamera.getSurfaceTexture().attachToGLContext(backgroundRenderer.getTextureId());
```
temporarily seems to fix the issue, however when going back to AR mode the camera is black again.

**Comment by gigadeplex** [comment]
I can't even detatch because it says "detachFromContext: invalid current EGLDisplay" and I can't attach it because it's already attached.

**Comment by devbridie** [comment]
This issue has been fixed in 1.23. If you're still seeing this, please let me know.

**Comment by verma-akash** [comment]
[QUESTION]
@devbridie @FabianRueckert 
With the recent updates **Session.Feature.FRONT_CAMERA** is deprecated.
How do we create a session with Front Camera?

Tried the CameraConfig.FacingDirection FRONT, but it is causing a crash with TextureNotSetException.
Working fine when using Session.Feature.FRONT_CAMERA.

**Comment by gptshubham595** [comment]
https://stackoverflow.com/a/76452017/14576798
yeah it worked
