### ISSUE TITLE
Will ARCore limit the resolution of color images the way Project Tango does?

### ISSUE THREAD

**Issue by waitaria** [google-ar/arcore-android-sdk#118]
In Project Tango, the image from the color camera intrinsics limit the resolution of the image to 1920x1080 pixels. Will ARCore place a similar limitation on the resolution of the color images? If so, what will this limitation be?

**Comment by inio** [comment]
For now the GPU texture is the only image access is all we're committing to (currently always 1920x1080 on DP2-supporte devices).  We realize there's strong interest in user the camera in myriad ways, so in the future may add APIs that allow more flexible camera control.

**Comment by 544531645** [comment]
In the future we can get Camera onFrame data?

**Comment by inio** [comment]
@544531645 As it seems you noticed, #92 covers that request.

**Comment by inio** [comment]
Duplicate of #153
