### ISSUE TITLE
How do I set the duration of interpolation for 'setSmoothed(boolean smoothed)'

### ISSUE THREAD

**Issue by agh372** [google-ar/arcore-android-sdk#1180]
### SPECIFIC ISSUE ENCOUNTERED

This documentation specified to interpolate the anchor node, we can use `setSmoothed(true)`, but how do I specify the duration of that interpolation?
https://developers.google.com/sceneform/reference/com/google/ar/sceneform/AnchorNode#setSmoothed(boolean)

**Comment by devbridie** [comment]
Sceneform isn't on topic for this issue tracker, but I'd imagine you can find the answer here: [AnchorNode](https://github.com/google-ar/sceneform-android-sdk/blob/b33fa25987561e5bf2129a25fbce6ad3b43ac4ee/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform/AnchorNode.java#L190)
