### ISSUE TITLE
Lack of elaboration in Persistent Cloud Anchors documentation

### ISSUE THREAD

**Issue by vortice3D** [google-ar/arcore-android-sdk#1184]
By consulting the documentation related to the use of Cloud Anchors / Persistent Cloud Anchors, I find is not well covered the matter about the need of an API Key and the Authentication process in general. (By the way, the (non-trivial) process of establishing anchorage identification actions through Firebase is not explained in enough depth either.)

The case is that the [Quickstart page](https://developers.google.com/ar/develop/java/cloud-anchors/quickstart-android), seems to be focus exclusively on the (Former) **Cloud Anchors**, and so **_it instructs the reader to employ API Keys_**:
1) Obtain an API Key. See Setting up API keys in the Google Cloud Platform Console Help Center if you are new to working with API keys.
2) Enable the ARCore Cloud Anchor API for your Google Cloud Platform project.
3)  In Android Studio, add your ARCore Cloud Anchor API key to your project.

But, however, in the [Developer Guide page](https://developers.google.com/ar/develop/java/cloud-anchors/developer-guide-android) it is stated that in order to use **Persistent Cloud Anchors** (with a TTL longer than twenty-four hours), the API will need to use keyless authentication, so if our app’s AndroidManifest.xml file contains an **_API key, we must remove it_**.

A side by side explanation (Former Cloud Anchors vs Persistent Cloud Anchors) would help a lot in the task to adapt existing code to the new functionality. Going in this direction, is it correct to say that in order to use Persistent Cloud Anchors, the info in the Quickstart page would be valid, eliminating the [Add an API Key](https://developers.google.com/ar/develop/java/cloud-anchors/quickstart-android#add_an_api_key) section, substituting it with the [Authentication](https://developers.google.com/ar/develop/java/cloud-anchors/developer-guide-android#authentication) section (of Developer Guide page)?

Thanks for your time.

**Comment by devbridie** [comment]
I totally get what you mean. I think there's a good opportunity to pull the docs together here; thanks for letting us know.

Currently, the authentication can be done:
- Using a key or keyless for TTL < 24h
- Only keyless for TTL >24h.

> (By the way, the (non-trivial) process of establishing anchorage identification actions through Firebase is not explained in enough depth either.)

Firebase is used only as an example to get the sample up-and-running with a shared database-- that's why it isn't treated in detail in the document. It isn't mandatory to use Firebase; and database store will do. In this case, one would replace the implementation of [FirebaseManager](https://github.com/google-ar/arcore-android-sdk/blob/9461160f6b1ebaf9070368b52795444267b7acab/samples/cloud_anchor_java/app/src/main/java/com/google/ar/core/examples/java/cloudanchor/FirebaseManager.java#L94) to do your own saving/loading of anchors in a given room.

I do agree that the relationship to Firebase could be a little more clear. Thank you for raising that point.

**Comment by nikhilsawlani** [comment]
Hi @devbridie I was also exploring Cloud Anchor API authentication and had a doubt regarding the Keyless authentication

So when using Keyless authentication is there any way of sharing Anchors across different users/devices for more than 24 hours? or it can be resolved on the same device when using Keyless authentication?

**Comment by devbridie** [comment]
Yes. In fact, keyless is the only method of creating a cloud anchor that will live for more than 24 hours. No matter the authentication method, cloud anchors can be shared across different devices.

**Comment by nikhilsawlani** [comment]
Thanks for the quick response @devbridie, in the case of keyless authentication how can we share anchors across different devices for more than 24 hours? using the Cloud Anchors Management API? are there any examples you can point me out?

**Comment by devbridie** [comment]
Generally,

1. Use hostCloudAnchorWithTtl to transform an Anchor into a CloudAnchor,
2. Continually [check the state](https://developers.google.com/ar/reference/java/com/google/ar/core/Anchor#public-anchor.cloudanchorstate-getcloudanchorstate) of the new anchor until it's [SUCCESS](https://developers.google.com/ar/reference/java/com/google/ar/core/Anchor.CloudAnchorState#public-static-final-anchor.cloudanchorstate-success),
3. At this point [getCloudAnchorId](https://developers.google.com/ar/reference/java/com/google/ar/core/Anchor#getCloudAnchorId()) should be populated.
4. This is the ID that you share with other clients and use in [resolveCloudAnchor](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#resolveCloudAnchor(java.lang.String)).

**Comment by nikhilsawlani** [comment]
Also, I was another question while going through the documentation for [Cloud Anchors](https://developers.google.com/ar/develop/java/cloud-anchors/overview-android#:~:text=users%20can%20share.-,What%20is%20a%20Cloud%20Anchor%3F,in%20a%20shared%20physical%20space.&text=This%20hosting%20enables%20users%20to%20share%20experiences.)
In the second point, it's mentioned that visual data is discarded within 24 hours after hosting, so visual data is converted into a 3D map and then discarded?

<img width="1161" alt="Screenshot 2021-02-08 at 10 32 05 AM" src="https://user-images.githubusercontent.com/25587983/107177975-23016800-69f9-11eb-869a-15d72f6154e9.png">
