### ISSUE TITLE
Shared Camera + Augmented Database = Black screen.

### ISSUE THREAD

**Issue by gigadeplex** [google-ar/arcore-android-sdk#1190]
### SPECIFIC ISSUE ENCOUNTERED
Cannot use Shared Camera with the detector. Preview turns black when toggling between AR mode

### VERSIONS USED
- Android Studio: 3.6.3
- ARCore SDK for Android:  1.22.0
- Device manufacturer, model, and O/S: Samsung, Galaxy S9+ Exynos, Android
- Google Play Services for AR (ARCore):   1.22.203220523
- Output of `adb shell getprop ro.build.fingerprint`: samsung/star2ltexx/star2lte:8.0.0/R16NW/G965FXXS2BRI1:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Using shared camera example:
 2. Add an image to assets and load it as a bitmap in runtime.
 3. Create an augmented database, add that bitmap as an augmented image, set the augmented database into your configuration and configure your session.
 4.  Toggle AR mode and you see the specific issue encountered.

### ADDITIONAL COMMENTS
This is horrible.

**Comment by devbridie** [comment]
This issue has been fixed in 1.23. If you're still seeing this, please let me know.
