### ISSUE TITLE
[Honor View20] No ArCameraConfig with AR_CAMERA_CONFIG_DEPTH_SENSOR_USAGE_REQUIRE_AND_USE

### ISSUE THREAD

**Issue by sajusathyan** [google-ar/arcore-android-sdk#1191]
### SPECIFIC ISSUE ENCOUNTERED
I assume Honor View20 has a ToF sensor - according to https://www.hihonor.com/global/products/smartphone/honorview20/spec/ and https://www.gsmarena.com/honor_view_20-9468.php.

But the ARCore ArSession_getSupportedCameraConfigsWithFilter do not return any ArCameraConfig in ArCameraConfigList when queried with ArCameraConfigFilter set to AR_CAMERA_CONFIG_DEPTH_SENSOR_USAGE_REQUIRE_AND_USE

Code:
```int numCameraConfigs = 0;

ArCameraConfigFilter* cameraConfigFilter = nullptr; 
ArCameraConfigFilter_create(mArSession, &cameraConfigFilter);

ArCameraConfigList* cameraConfigList  = nullptr; 
ArCameraConfigList_create(mArSession, &cameraConfigList);

ArCameraConfigFilter_setDepthSensorUsage(mArSession, cameraConfigFilter, AR_CAMERA_CONFIG_DEPTH_SENSOR_USAGE_REQUIRE_AND_USE);
ArSession_getSupportedCameraConfigsWithFilter(mArSession, cameraConfigFilter, cameraConfigList);
ArCameraConfigList_getSize(mArSession, cameraConfigList, &numCameraConfigs);

LOGI("Number of camera configs that supports ToF Sensor = %d", numCameraConfigs);
```

Output:
Number of camera configs that supports ToF Sensor = 0

### VERSIONS USED
- Android Studio: **4.1.1**
- ARCore SDK for Android: **1.22.202940000**
- Device manufacturer, model, and O/S: **Honor/Honor View20/Build Number: 10.0.0.201/Android 10**
- Google Play Services for AR (ARCore): **1.22.203220523**
- Output of `adb shell getprop ro.build.fingerprint`: **HONOR/PCT-L29/HWPCT:10/HUAWEIPCT-L29/10.0.0.201C432:user/release-keys**

### STEPS TO REPRODUCE THE ISSUE
 1. See code above

### WORKAROUNDS (IF ANY)
None

### ADDITIONAL COMMENTS
None

**Comment by devbridie** [comment]
Unfortunately, not all devices with ToF sensors currently have support for ToF usage within ARCore. In this case, the ToF sensor can't be used because huawei's ToF API isn't open and there isn't any camera2 support.

**Comment by sajusathyan** [comment]
@devbridie Thank you!

[https://developers.google.com/ar/develop/java/depth/overview](Depth API overview for Android) says "If the device has an active depth sensor, such as a time-of-flight sensor (or ToF sensor), that data is automatically included in the processed depth."
This made me assume that ARCore provides ToF sensor data for all devices equipped with ToF sensors.

Is there a list of devices with ToF sensors which supports ToF usage with ARCore?

**Comment by devbridie** [comment]
That's a good point. I'll try to update the verbiage on this page and other pages to clarify supported ToF devices. I'll also look into including ToF support indicators on the supported devices page; currently there's no list I can share right now. From what I can see, supported Samsung devices with ToF are generally a safe bet.

**Comment by lvonasek** [comment]
> Unfortunately, not all devices with ToF sensors currently have support for ToF usage within ARCore. In this case, the ToF sensor can't be used because huawei's ToF API isn't open and there isn't any camera2 support.

I would like to correct you. Honor View 20 and other Huawei devices have Camera2 API support. The only difference to Samsung device is that Huawei devices are using for ToF sensor the same camera ID like main RGB camera.

Some time ago I shared this demo running on Honor View 20 on ARCore using Shared Camera feature: https://www.linkedin.com/posts/lubo%C5%A1-von%C3%A1sek-9682a314b_i-collaborated-on-this-arcore-demo-which-activity-6595007472094720000-PPN9

**Comment by devbridie** [comment]
The [Supported Devices](https://developers.google.com/ar/discover/supported-devices) list has been updated to specify devices that support the ToF sensor. Changes to the documentation are in-flight.
