### ISSUE TITLE
ARCore Services Not Working on Xiaomi 10i Devices

### ISSUE THREAD

**Issue by siran10289** [google-ar/arcore-android-sdk#1196]
UnavailableDeviceNotCompatibleException

### VERSIONS USED
- Android Studio:  4.1.2
- ARCore SDK for Android:  com.google.ar:core:1.22.0
- Device manufacturer, model, and O/S:  Xiaomi, 10i (M2007J17I)
- Google Play Services for AR (ARCore):  1.23.210260603

### STEPS TO REPRODUCE THE ISSUE
 1. Compile sample app from https://github.com/google-ar/arcore-android-sdk/tree/master/samples 
 1. Getting an exception UnavailableDeviceNotCompatibleException

### ADDITIONAL COMMENTS
According to your supported devices list from  https://developers.google.com/ar/discover/supported-devices Mi 10i in list but not support with ARCore services..

**Comment by devbridie** [comment]
Hi, please provide the following information so I can get this checked out:

- Output of `adb shell getprop ro.build.fingerprint`:

**Comment by siran10289** [comment]
Hi Dereck Bridie
Thanks for the quick replay 
Output of adb shell getprop ro.build.fingerprint:
Xiaomi/gauguininpro/gauguininpro:10/QKQ1.200628.002/V12.0.4.0.QJSINXM:user/release-keys

I don't why the AR Services not working on my device.. Please guide me.

**Comment by sandyfriend** [comment]
Mi 10i current should only support Android 11 and later. Please update the android Build to Android 11. thanks

**Comment by siran10289** [comment]
Thanks @sandyfriend 

You mean The AR Services only run with Android 11 and above on MI 10i Devices. Right now Mi 10i runs with Android 10 only.

**Comment by sandyfriend** [comment]
correct, it seem Xiaomi current have both android 10 and android 11 version available.   Android 11 is first supported on Mi 10i. will working with Xiaomi fixing the android 10 in the next release.

**Comment by siran10289** [comment]
Thanks @sandyfriend 
Expecting ARCore's next update as soon as possible.

**Comment by siran10289** [comment]
Hi @sandyfriend , @devbridie 
Any updates on ARCore support in Mi 10 i

**Comment by harsha-main** [comment]
@sandyfriend I have updated my 10 i 5G to android 11, but I still cannot run Sceneform apps on it. 

Xiaomi/gauguininpro/gauguininpro:11/RKQ1.200826.002/V12.5.3.0.RJSINXM:user/release-keys is my output of the command.
Please help me as I had purchased this model just for the sake of the ARCore support.

**Comment by sandyfriend** [comment]
could you try other arcore application? or provide bugreport for that.
I do see  
Xiaomi/gauguininpro/gauguininpro:11/RKQ1.200826.002/V12.5.3.0.RJSINXM:user/release-keys
is supported.

**Comment by harsha-main** [comment]
Only very specific apps like ARCore elements work on my phone, the play store does not even show most of the apps that require ARCore on my MI 10 i 5G device. I believe that the 5G device, is maybe considered different from the same model without 5G support.
So I'm not sure what the problem could have been. I am actually not sure how I can provide a bug-report(maybe because I'm not very experienced with this), however I could see that the following code returns true
ArCoreApk.getInstance().checkAvailability(this).isUnknown();

So the framework considered this Device's support status to be unknown.

**Comment by harsha-main** [comment]
@sandyfriend I also noticed that if I use the compileSdkVersion as 28, sceneform works alright. But if I upgrade it to 32, it does not work on my Redmi 10i
