### ISSUE TITLE
Feature Request: Add support for Huawei P30 Pro ToF depth sensor

### ISSUE THREAD

**Issue by pawegio** [google-ar/arcore-android-sdk#1198]
According to the [official Huawei P30 Pro specification](https://consumer.huawei.com/en/phones/p30-pro/specs/), time-of-flight hardware depth sensor is available on the device. However, both [ARCore supported devices](https://developers.google.com/ar/discover/supported-devices) list and camera configs list (checked on runtime) mark that it's not supported in ARCore yet (including recent release - v1.23.0).

I've noticed that it applies to all other Huawei devices.

**Comment by devbridie** [comment]
Please see #1191. Unfortunately, we can't support Huawei devices' ToF at this time.

**Comment by pawegio** [comment]
@devbridie Thank you for clarifying that! I've been guessing it might be caused by Huawei closed API...

**Comment by alexx-ftw** [comment]
Is the situation still the same now in 2023?
