### ISSUE TITLE
### SPECIFIC ISSUE ENCOUNTERED   ### VERSIONS USED - Android Studio:  - ARCore SDK for Android:  - Device manufacturer, model, and O/S:  - Google Play Services for AR (ARCore):     On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`   On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:` - Output of `adb shell getprop ro.build.fingerprint`:    ### STEPS TO REPRODUCE THE ISSUE  1.  1.  1.   ### WORKAROUNDS (IF ANY)   ### ADDITIONAL COMMENTS

### ISSUE THREAD

**Issue by lumangga** [google-ar/arcore-android-sdk#1203]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- Google Play Services for AR (ARCore):  
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by devbridie** [comment]
Hey, I think this issue didn't go through well.
