### ISSUE TITLE
glTF issues

### ISSUE THREAD

**Issue by kinectsources** [google-ar/arcore-android-sdk#1204]
### SPECIFIC ISSUE ENCOUNTERED
There is issue with multi objects contained glTF or fbx or obj models. The problem is from UV maps side. For reference I am linking screenshots here. The third image is from blender and it works fine. But in Sceneform viewer it messed up.

*Used latest anndroid ARCore SDK also.

![2](https://user-images.githubusercontent.com/48123837/109926174-abb5b000-7ce8-11eb-8493-ff29890c0494.PNG). 

![1](https://user-images.githubusercontent.com/48123837/109926147-a35d7500-7ce8-11eb-9588-39ff4d43c5cb.PNG) 

![3](https://user-images.githubusercontent.com/48123837/109926079-8b85f100-7ce8-11eb-96ef-3f70b2438139.png)

### VERSIONS USED
- Android Studio: 3.5.3
- ARCore SDK for Android: 1.15.0/1.16.0 & 1.23.1
- Sceneform tools 1.15.0
- Device manufacturer, model, and O/S: Honor 10, Android 10
- Google Play Services for AR (ARCore):  
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

### ADDITIONAL COMMENTS
Or is it a bug from filament engine? Though Sceneform tools archieved for further development.

**Comment by devbridie** [comment]
Unfortunately, Google doesn't offer support for Sceneform after [open-sourcing the SDK](https://github.com/google-ar/sceneform-android-sdk), so this issue is off-topic here. Consider looking for a community-reared fork of sceneform that could help you with this issue or having a look at the SDK sources.
