### ISSUE TITLE
Depth API appears to return images in little endian format

### ISSUE THREAD

**Issue by ameliaholcomb** [google-ar/arcore-android-sdk#1207]
### SPECIFIC ISSUE ENCOUNTERED
The documentation (https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#public-image-acquiredepthimage) states that acquireDepthImage() returns a DEPTH16 buffer in big-endian format. However, this does not seem to be the case. 

The following code, adapted from https://developer.android.com/reference/android/graphics/ImageFormat#DEPTH16:
```
        Image imgTOF = frame.acquireDepthImage();
        Image.Plane plane = imgTOF.getPlanes()[0];
        ShortBuffer shortDepthBuffer = plane.getBuffer().order(ByteOrder.BIG_ENDIAN).asShortBuffer();
        int depthSample = shortDepthBuffer.get() & 0xFFFF;
        short depthSampleShort = (short) depthSample;
        short depthRange = (short) (depthSampleShort & 0x1FFF);
```
Produces a garbled value on both a Pixel 4a and Huawei phone. 

### VERSIONS USED
- ARCore SDK for Android: 1.22.0

### WORKAROUNDS (IF ANY)
Changing the order to little endian 
```
        ShortBuffer shortDepthBuffer = plane.getBuffer().order(ByteOrder.LITTLE_ENDIAN).asShortBuffer();
```
works. 

### APPENDIX
The full code I am using to parse the image is this, in case it is useful:

```
public TofArrays parseTof(Image imgTOF) {

        // Buffers for storing TOF output
        TofArrays arrays = new TofArrays(imgTOF.getWidth() * imgTOF.getHeight());
        Image.Plane plane = imgTOF.getPlanes()[0];
        ShortBuffer shortDepthBuffer = plane.getBuffer().order(ByteOrder.LITTLE_ENDIAN).asShortBuffer();
       
        int stride = plane.getRowStride();
        int offset = 0;

        int i = 0;
        for (short y = 0; y < imgTOF.getHeight(); y++) {
            for (short x = 0; x < imgTOF.getWidth(); x++) {
                // Parse the data. Format is [depth|confidence]
                int depthSample = shortDepthBuffer.get((int) (y / 2) * stride + x) & 0xFFFF;
                short depthSampleShort = (short) depthSample;
                short depthRange = (short) (depthSampleShort & 0x1FFF);
                short depthConfidence = (short) ((depthSampleShort >> 13) & 0x7);
                float depthPercentage = depthConfidence == 0 ? 1.f : (depthConfidence - 1) / 7.f;

                // Store data in buffer
                arrays.xBuffer[i] = x;
                arrays.yBuffer[i] = y;
                arrays.dBuffer[i] = depthRange / 1000.0f;
                arrays.percentageBuffer[i] = depthPercentage;
                i++;
            }
            offset += imgTOF.getWidth();
        }
        return arrays;
    }
```

**Comment by ameliaholcomb** [comment]
The only place I can find acquireDepthImage() used in the samples in this repo is in HelloArActivity.java.

There, the depth image is passed to this function, which appears to interpret the first byte as green values and the second byte as red, so the endianness would just flip colors.
(https://github.com/google-ar/arcore-android-sdk/blob/eaa85941f2d724c60671bf94f46de7178baba7e6/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/common/samplerender/arcore/BackgroundRenderer.java#L195-L212)

**Comment by devbridie** [comment]
Thanks for the note. I'm working to update the documentation now.

**Comment by devbridie** [comment]
Resolved, thank you.
