### ISSUE TITLE
Will ar-core 1.0 provide Drag and Drop,Zoom,rotate functionalities?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#121]
Iam using ar-core developer preview2 there is no drag and drop,zoom,rotate functionalities,is it possible ar-core 1.0 coming with these functionalities?

**Comment by inio** [comment]
I anticipate the sample application for 1.0 will be very similar to those released with DP2.

The ARCore API provides sufficient scene understanding data to implement these behaviors, but the actual implementation is up to developers.
