### ISSUE TITLE
Google Play Services for AR does not support Nokia 5.4

### ISSUE THREAD

**Issue by anocean2** [google-ar/arcore-android-sdk#1212]
When I install the sample HelloAR，it toasted “This device does not support AR”. But the device Nokia 5.4 have in list of supported devices. Please, look in the screenshots in attach.
![Screenshot_20210324-121649](https://user-images.githubusercontent.com/54744894/112288033-ff8b3780-8c9d-11eb-8172-4859dc32e388.png)
![Screenshot_20210324-121513](https://user-images.githubusercontent.com/54744894/112288037-0023ce00-8c9e-11eb-90f0-42b6ccfd2f95.png)

**Comment by devbridie** [comment]
Please provide the following information so I can look into this:

- Output of `adb shell getprop ro.build.fingerprint`:

**Comment by anocean2** [comment]
> Please provide the following information so I can look into this:
> 
> * Output of `adb shell getprop ro.build.fingerprint`:

Nokia/DoctorDoom_00RU/DRD:10/QKQ1.200719.002/00WW_1_15B:user/release-keys

**Comment by sandyfriend** [comment]
We will work with OEM on that issues. thank you for the reporting.

**Comment by devbridie** [comment]
I've been informed that this issue has been resolved by the team; thanks for the patience.

**Comment by Thang150898** [comment]
Good
