### ISSUE TITLE
Samsung A52 5G doesn't support Depth API

### ISSUE THREAD

**Issue by 17618-RuiFernandes** [google-ar/arcore-android-sdk#1214]
So today Samsung A52 5G launched and I already tried to execute a sample project which uses depth API but the message "... Device doesn't support depth API" shows up.

Is it because the device is recently or it will never be able to use depth API? I don't understand why Samsung A51 5G is able but A52 is not.

**Comment by sandyfriend** [comment]
Currently, it is in the progress. will update it, Once we have the result.

**Comment by Jasonp8000** [comment]
Hi everyone, is there any update on this ?
