### ISSUE TITLE
Add support for OnePlus 9 Pro 

### ISSUE THREAD

**Issue by br-matt** [google-ar/arcore-android-sdk#1216]
### SPECIFIC ISSUE ENCOUNTERED
OnePlus 9 Pro is not supported

### STEPS TO REPRODUCE THE ISSUE
 1. Visit https://developers.google.com/ar/discover/supported-devices and look for **OnePlus 9 Pro**
or
2. Open google play and search "Google Play Services for AR"

**Comment by devbridie** [comment]
This device is currently undergoing certification; nothing new to share at the moment.
