### ISSUE TITLE
depth sensor usage set to DO_NOT_USE in all camera configurations

### ISSUE THREAD

**Issue by jinglebiscuitsHL** [google-ar/arcore-android-sdk#1218]
### SPECIFIC ISSUE ENCOUNTERED
session.getSupportedCameraConfigs returns 9 configurations for Google Pixel 5. None of these configurations use depth api.

### VERSIONS USED
- Android Studio: 4.1.3
- ARCore SDK for Android: 1.22.0 && 1.23.0
- Device manufacturer, model, and O/S: Google Pixel 3 and Google Pixel 5
- Google Play Services for AR (ARCore):  1.23.210260603
- Output of `adb shell getprop ro.build.fingerprint`: google/redfin/redfin:11/RQ2A.210405.005/7181113:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. session = new Session(context);
 2. final CameraConfigFilter filter = new CameraConfigFilter(session);
 3. List<CameraConfig> configs = session.getSupportedCameraConfigs(filter);
 4. Observe that all of the CameraConfigs in configs report DO_NOT_USE for getDepthSensorUsage()

### WORKAROUNDS (IF ANY)
None that I know of.

### ADDITIONAL COMMENTS
I'm curious if ARCore will still use depth sensor api in the background even if this camera config says it won't be used.

**Comment by jinglebiscuitsHL** [comment]
I think I've mistaken depth sensor and depth api. Google Pixel 5 supports the depth api, but it does not have a depth sensor. Leaving the ticket open for now until someone who knows more addresses the issue.

**Comment by devbridie** [comment]
That's correct. [`CameraConfig.DepthSensorUsage.DO_NOT_USE`](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.DepthSensorUsage#public-static-final-cameraconfig.depthsensorusage-do_not_use) indicates that the camera configuration (when it comes from `getSupportedCameraConfigs()`) will not use a depth sensor, even if it is available.

This is seperate from depth API usage, as depth can also be derived from motion. For checking depth support, one would use [`Session.isDepthModeSupported()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#isDepthModeSupported(com.google.ar.core.Config.DepthMode)), and use [`Config.setDepthMode()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Config#setDepthMode(com.google.ar.core.Config.DepthMode)) to use it.
