### ISSUE TITLE
[QUESTION] Can I use depth api and cloud anchors at the same time??

### ISSUE THREAD

**Issue by kawaiipss** [google-ar/arcore-android-sdk#1219]
### SPECIFIC ISSUE ENCOUNTERED

HI, I am now trying to build a multiplayer AR app that interacts with the real world using ARCore.

However, since the Depth API and Cloud anchors are used at the same time, the anchor object created in the host is not visible in the client.

So I wonder if both features are not originally supported at the same time or if there is something I am missing.

Thanks! 

### VERSIONS USED
- Android Studio: 4.1.1
- ARCore SDK for Android: ARCore SDK ver.1.23
- Device manufacturer, model, and O/S: Samsung Galaxy S21, Android
- Google Play Services for AR (ARCore):  
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`:

**Comment by bounty-torn** [comment]
Is the S21 your host or client device? What is the other device? Is the other device a Depth API-supported one?

**Comment by kawaiipss** [comment]
When testing, I used S21 for both the client and the host, but in reality I think the Galaxy S10 will be the host. It is known that both S21 and S10 support Depth API.

**Comment by kawaiipss** [comment]
> Is the S21 your host or client device? What is the other device? Is the other device a Depth API-supported one?

When testing, I used S21 for both the client and the host, but in reality I think the Galaxy S10 will be the host. It is known that both S21 and S10 support Depth API.

**Comment by devbridie** [comment]
Could you elaborate on what behavior you're seeing? Does [`hostCloudAnchor`](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#hostCloudAnchor(com.google.ar.core.Anchor)) host the anchor successfully? What about [`resolveCloudAnchor`](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#resolveCloudAnchor(java.lang.String)), does it resolve that specific anchor or fail with an error?

**Comment by kawaiipss** [comment]
> Could you elaborate on what behavior you're seeing? Does [`hostCloudAnchor`](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#hostCloudAnchor(com.google.ar.core.Anchor)) host the anchor successfully? What about [`resolveCloudAnchor`](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#resolveCloudAnchor(java.lang.String)), does it resolve that specific anchor or fail with an error?

When using only Cloud Anchors, it is good to host anchors, but it is not possible to host anchors with the Depth API option turned on.

**Comment by devbridie** [comment]
I'm seeing success with the `cloud_anchor_java` sample with depth API enabled.

Could you try reproducing with [this fork of cloud_anchor_java](https://github.com/devbridie/arcore-android-sdk/tree/bd5b273804301e93dfdef61f21182cde385b7113/samples/cloud_anchor_java), and upload logs from this trial? 

Thanks.

**Comment by kawaiipss** [comment]
> I'm seeing success with the `cloud_anchor_java` sample with depth API enabled.
> 
> Could you try reproducing with [this fork of cloud_anchor_java](https://github.com/devbridie/arcore-android-sdk/tree/bd5b273804301e93dfdef61f21182cde385b7113/samples/cloud_anchor_java), and upload logs from this trial?
> 
> Thanks.

Oh thank you so much!!!!!!!!!! 

I'll try it.

**Comment by kawaiipss** [comment]
> I'm seeing success with the `cloud_anchor_java` sample with depth API enabled.
> 
> Could you try reproducing with [this fork of cloud_anchor_java](https://github.com/devbridie/arcore-android-sdk/tree/bd5b273804301e93dfdef61f21182cde385b7113/samples/cloud_anchor_java), and upload logs from this trial?
> 
> Thanks.

I'm sorry, but I have a question. 

I built the example you provided on my device and it ran well, but I don't know how to create the 3D anchor object. 

How can I create an anchor on the host while running the sample app?

**Comment by devbridie** [comment]
The sample app I provided works as follows:

1. Start the app. Detect a plane by providing motion in the device.
2. Select "Host" in the top left.
3. Tap a plane to place an Andy. The hosting process will start.

(note: you'll need [a `google-services.json`](https://developers.devsite.corp.google.com/ar/develop/java/cloud-anchors/quickstart-android#set_up_anchor_id_sharing), see screenshot)

![image](https://user-images.githubusercontent.com/442644/114716864-c55d0500-9d34-11eb-8889-20a6f90ea9a1.png)

**Comment by kawaiipss** [comment]
> The sample app I provided works as follows:
> 
> 1. Start the app. Detect a plane by providing motion in the device.
> 2. Select "Host" in the top left.
> 3. Tap a plane to place an Andy. The hosting process will start.
> 
> (note: you'll need [a `google-services.json`](https://developers.devsite.corp.google.com/ar/develop/java/cloud-anchors/quickstart-android#set_up_anchor_id_sharing), see screenshot)
> 
> ![image](https://user-images.githubusercontent.com/442644/114716864-c55d0500-9d34-11eb-8889-20a6f90ea9a1.png)


I did what you told me, but nothing happens when I touch the plane. T^T

**Comment by devbridie** [comment]
Are you seeing something like this (ie, with the plane texture covering the detected area?

![image](https://user-images.githubusercontent.com/442644/115029664-81016e80-9ec6-11eb-9f98-35e05fa91891.png)

**Comment by kawaiipss** [comment]
> Are you seeing something like this (ie, with the plane texture covering the detected area?
> 
> ![image](https://user-images.githubusercontent.com/442644/115029664-81016e80-9ec6-11eb-9f98-35e05fa91891.png)

I'm really sorry for the late confirmation. 

I solved this problem in a different way. 

Thank you so much for helping me in the meantime.

**Comment by devbridie** [comment]
Good to hear!
