### ISSUE TITLE
eglChooseConfig failed on Android Emulator using HelloAR

### ISSUE THREAD

**Issue by amida47** [google-ar/arcore-android-sdk#1220]
### SPECIFIC ISSUE ENCOUNTERED
can't launch the app in android emulator, it closes just after being launched

### VERSIONS USED
- Android Studio: 4.1
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
![image](https://user-images.githubusercontent.com/49212088/114322583-90706880-9b10-11eb-8d8b-46785bb40680.png)

- Google Play Services for AR (ARCore):  
  Packages:
    versionName=1.23.210260653
Active APEX packages:
Inactive APEX packages:
Factory APEX packages:
- Output of `adb shell getprop ro.build.fingerprint`: 
google/sdk_gphone_x86_arm/generic_x86_arm:11/RSR1.201013.001/6903271:userdebug/dev-keys

### STEPS TO REPRODUCE THE ISSUE
 1.downloaded the samples
 2.opened the sample folder hello_ar_java in Android studio
 3.hit run 
4- installed Google_Play_Services_for_AR_1.23.0_x86_for_emulator.apk
5- hit run again 
 

### ADDITIONAL COMMENTS
this is what appeared in the run section
04/11 21:38:53: Launching 'app' on No Devices.
Install successfully finished in 2 s 540 ms.
$ adb shell am start -n "com.google.ar.core.examples.java.helloar/com.google.ar.core.examples.java.helloar.HelloArActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 6363 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/es.java.helloa: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/es.java.helloa: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/ARCore-ArCoreApk: Starting setup activity
D/HostConnection: HostConnection::get() New Host Connection established 0xf5da1800, tid 6403
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0xf5da11e0: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xf5da11e0: ver 2 0 (tinfo 0xf60eec90) (first time)
D/HostConnection: HostConnection::get() New Host Connection established 0xf5da1790, tid 6406
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
E/AndroidRuntime: FATAL EXCEPTION: GLThread 536
    Process: com.google.ar.core.examples.java.helloar, PID: 6363
    java.lang.IllegalArgumentException: eglChooseConfig failed
        at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:883)
        at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1054)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1431)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
I/Process: Sending signal. PID: 6363 SIG: 9

**Comment by devbridie** [comment]
Can you try an Emulator API version of 29? There's currently an issue with API 30 on emulator, with a fix targeted for next release.

**Comment by devbridie** [comment]
Also, please see #1162.

**Comment by amida47** [comment]
> Also, please see #1162.

yeah I saw it and I applied the suggested fix but it just produce the same error plus others.

**Comment by amida47** [comment]
> Also, please see #1162.
device I'm using now
![image](https://user-images.githubusercontent.com/49212088/114431420-00cdc700-9baf-11eb-8614-bd1aa0900e2d.png)
the logs
`04/12 16:53:06: Launching 'app' on Pixel 4 API 29.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.google.ar.core.examples.java.helloar/com.google.ar.core.examples.java.helloar.HelloArActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 5908 on device 'Pixel_4_API_29 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/es.java.helloa: Not late-enabling -Xcheck:jni (already on)
E/es.java.helloa: Unknown bits set in runtime_flags: 0x8000
W/es.java.helloa: Unexpected CPU variant for X86 using defaults: x86_64
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
W/RenderThread: type=1400 audit(0.0:24): avc: denied { write } for name="property_service" dev="tmpfs" ino=880 scontext=u:r:untrusted_app:s0:c135,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 app=com.google.ar.core.examples.java.helloar
D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
W/es.java.helloa: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
W/es.java.helloa: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/third_party/arcore/ar/core/android/sdk/session_create.cc: Entering ArSession_createWithFeatures
    ARCore Version: SDK build name: 1.23
I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: APK version code: 210260653
I/third_party/arcore/ar/core/android/sdk/session_create.cc: Dynamite load ok.
I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Attempting to load native library arcore_c from package com.google.ar.core
I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Dynamite::LoadNativeRemoteLibrary handle=-8133599993958189023
I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore SDK: dynamite number_of_symbols_loaded=226
I/native: session_create_implementation.cc:237 Entering createImplementationWithFeaturesAndSettings. ARCore SDK version: [1.23.210210000].
I/native: session_create_implementation.cc:201 AugmentedRegion downsample mode from Phenotype: true
V/third_party/redwood/infrastructure/jni_common/jni_helper.cc: JniHelper: attached thread (Called from line 364).
I/native: session_create_implementation_shared.cc:1851 min_apk_version_code is: 210210000, phenotype flag of enable_dual_camera_support is: false, phenotype flag of unified_data_source_status is: 1, is_dual_camera_supported based on device profile is: false
    session_create_implementation_shared.cc:1862 Settings.camera_stack_option is not specified
    session_create_implementation_shared.cc:1928 Datasource will be created with camera_stack_option = kNdk
I/native: session_create_implementation_shared.cc:2020 Persistent online recalibration is enabled by Phenotype.
I/tflite: Initialized TensorFlow Lite runtime.
I/native: online_calibration_manager.cc:90 OnlineCalibrationManager: Could not open /data/user/0/com.google.ar.core.examples.java.helloar/cache/arcore-online-recalibration for reading.
W/es.java.helloa: Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/es.java.helloa: Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/es.java.helloa: Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
    Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
W/ARCore-ContextUtils: The API key for use with the Google AR service could not be obtained!
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
E/ARCore-LocationProvider: Exception during FLP api client construction: com.google.android.gms.location.LocationServices
    java.lang.ClassNotFoundException: com.google.android.gms.location.LocationServices
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.google.ar.core.services.LocationProvider.loadClass(PG:1)
        at com.google.ar.core.services.LocationProvider.setupFusedLocationProviderApi(PG:1)
        at com.google.ar.core.services.LocationProvider.<init>(PG:7)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:11)
        at com.google.ar.core.Session.<init>(Session.java:4)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:256)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationServices" on path: DexPathList[[zip file "/data/app/com.google.ar.core.examples.java.helloar-YaOfb2k0wTUmzA9q8OfzJg==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.ar.core.examples.java.helloar-YaOfb2k0wTUmzA9q8OfzJg==/lib/x86_64, /data/app/com.google.ar.core.examples.java.helloar-YaOfb2k0wTUmzA9q8OfzJg==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at com.google.ar.core.services.LocationProvider.loadClass(PG:1) 
        at com.google.ar.core.services.LocationProvider.setupFusedLocationProviderApi(PG:1) 
        at com.google.ar.core.services.LocationProvider.<init>(PG:7) 
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method) 
        at com.google.ar.core.Session.<init>(Session.java:11) 
        at com.google.ar.core.Session.<init>(Session.java:4) 
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:256) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446) 
        at android.app.Activity.performResume(Activity.java:7939) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
I/native: session_create_implementation_shared.cc:859 Datasource will be created with timeout = 4s, should_wait = false, should_use_greedy_recovery = true
I/native: android_camera.cc:169 Camera start operation timeout set to 4000 ms.
I/native: android_camera.cc:1827 Initializing camera manager.
E/ACameraMetadata: filterDurations: malformed duration key 1638402! count 0, type 3
    filterDurations: malformed duration key 1638403! count 0, type 3
    filterDurations: malformed duration key 1835009! count 0, type 3
    filterDurations: malformed duration key 1835010! count 0, type 3
    filterDurations: malformed duration key 1638407! count 0, type 3
    filterDurations: malformed duration key 1638408! count 0, type 28
E/ACameraMetadata: filterDurations: malformed duration key 1638402! count 0, type 3
    filterDurations: malformed duration key 1638403! count 0, type 3
    filterDurations: malformed duration key 1835009! count 0, type 3
    filterDurations: malformed duration key 1835010! count 0, type 3
    filterDurations: malformed duration key 1638407! count 0, type 3
    filterDurations: malformed duration key 1638408! count 0, type 28
E/ACameraMetadata: filterDurations: malformed duration key 1638402! count 0, type 3
    filterDurations: malformed duration key 1638403! count 0, type 3
    filterDurations: malformed duration key 1835009! count 0, type 3
    filterDurations: malformed duration key 1835010! count 0, type 3
    filterDurations: malformed duration key 1638407! count 0, type 3
    filterDurations: malformed duration key 1638408! count 0, type 28
E/ACameraMetadata: filterDurations: malformed duration key 1638402! count 0, type 3
    filterDurations: malformed duration key 1638403! count 0, type 3
    filterDurations: malformed duration key 1835009! count 0, type 3
    filterDurations: malformed duration key 1835010! count 0, type 3
    filterDurations: malformed duration key 1638407! count 0, type 3
    filterDurations: malformed duration key 1638408! count 0, type 28
I/native: android_camera.cc:1853 Camera manager initialized successfully with 2 cameras.
I/native: imagereader_ndk_wrapper.cc:45 Loading Android NDK 26 symbols from libmediandk.so
    imagereader_ndk_wrapper.cc:68 Successfully loaded Android NDK 26 libmediandk.so symbols.
I/native: cameras.cc:119 Number of hardware buffers is 16. sdk_version=29, is_hardware_buffer_supported=true
I/native: android_sensors.cc:99 Using calibrated accelerometer.
    android_sensors.cc:135 Uncalibrated magnetometer available.
I/native: android_sensors.cc:139 Calibrated magnetometer available.
    android_sensors.cc:152 Using SENSOR_TYPE_LIGHT
    android_sensors.cc:152 Using SENSOR_TYPE_PRESSURE
    android_sensors.cc:152 Using SENSOR_TYPE_PROXIMITY
    android_sensors.cc:152 Using SENSOR_TYPE_GRAVITY
    android_sensors.cc:152 Using SENSOR_TYPE_ROTATION_VECTOR
    android_sensors.cc:152 Using SENSOR_TYPE_GAME_ROTATION_VECTOR
I/native: android_sensors.cc:152 Using SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR
    android_sensors.cc:155 Could not find SENSOR_TYPE_STEP_DETECTOR
I/native: android_platform_checks.cc:195 IsZeroRotationLandscape = false
I/native: app_version_util.cc:50 Package name: com.google.ar.core App version: 1.23.210260653
    logger.h:28 DataSourceMetrics: CamerasInit: 22.057us
    session_create_implementation_shared.cc:1171 CPU Image enable frame delay to compensate delay: false
I/native: config_helpers.cc:396 Legacy IMU sigma values are used
    config_helpers.cc:349 Failed to find IMU intrinsic covariance matrix in profile for id: 100
    config_helpers.cc:107 Does not find camera intrinsic covariance matrix in profile for id 0
    config_helpers.cc:180 Does not find extrinsic covariance matrix in profile for IMU id 100
I/native: feature_matcher_and_filter.cc:91 Enabled the robustification to large-sized and fast-moving objects on this mono-camera device.
I/native: pose_confidence_estimator.cc:231 Pose confidence model loaded successfully
    estimator_impl.cc:401 Ralph is enabled.
I/native: asset_manager_util.cc:59 Created global reference to asset manager.
    session_create_implementation_shared.cc:1199 Normal detector created.
I/native: planar_target_tracking_manager.h:114 Config of PlanarTargetTrackingManager:
    -pose_refinement_with_detection_interval_ns: 0
    -min_interval_between_detections_ns: 500000000
    -filter_parallax: false
    -filter_result: true
    -multiple_targets: true
    -mini_detection: true
    -tracking_mode: 1
    -camera_id: 0
I/native: camera_config_manager.cc:718 UpdateBugFixes on CameraConfigManager is unimplemented!
I/third_party/arcore/ar/core/android/sdk/arimage_jni.cc: Loading AImage symbols
I/native: session.cc:544 Session::CheckAndWriteCurrentConfig returning OK.
I/native: session.cc:1152 Entering Session::Resume.
I/native: camera_config_manager.cc:718 UpdateBugFixes on CameraConfigManager is unimplemented!
I/CameraManagerGlobal: Connecting to camera service
I/native: session.cc:3141 Update Frame Delay to 0 frames.
    android_sensors.cc:174 Starting thread.
I/native: android_camera.cc:763 [Camera=0; State=CLOSED] Reset cleanly got to CLOSED state.
I/native: cameras.cc:1143 Included camera stream {camera_id = "0", stream_index = 0} as feature extraction streams.
I/native: logger.h:28 DataSourceMetrics: kStartImageSubSystem: 863.9us
    session.cc:1314 Session::ResumeWithAnalytics returning OK.
I/native: android_sensors.cc:44 Gyro min delay 10ms requesting 10ms
I/native: android_sensors.cc:44 Accel min delay 10ms requesting 10ms
E/ACameraMetadata: filterDurations: malformed duration key 1638402! count 0, type 3
E/ACameraMetadata: filterDurations: malformed duration key 1638403! count 0, type 3
    filterDurations: malformed duration key 1835009! count 0, type 3
    filterDurations: malformed duration key 1835010! count 0, type 3
    filterDurations: malformed duration key 1638407! count 0, type 3
E/ACameraMetadata: filterDurations: malformed duration key 1638408! count 0, type 28
D/HostConnection: HostConnection::get() New Host Connection established 0x791be2707dc0, tid 5943
    HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/HostConnection: HostConnection::get() New Host Connection established 0x791c3608d380, tid 5946
D/EGL_emulation: eglCreateContext: 0x791be2707fa0: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0x791be2707fa0: ver 2 0 (tinfo 0x791c35a8b520)
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
W/Gralloc3: mapper 3.x is not supported
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: GLThread 301
    Process: com.google.ar.core.examples.java.helloar, PID: 5908
    java.lang.IllegalArgumentException: eglChooseConfig failed
        at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:883)
        at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1054)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1431)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x791be27085e0, tid 5943
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
D/eglCodecCommon: allocate: Ask for block of size 0x1000
    allocate: ioctl allocate returned offset 0x3ffff8000 size 0x2000
D/EGL_emulation: eglMakeCurrent: 0x791be2707fa0: ver 2 0 (tinfo 0x791c35a8b520)
I/OpenGLRenderer: Davey! duration=797ms; Flags=1, IntendedVsync=226979356202, Vsync=226979356202, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=226985600200, AnimationStart=226985672600, PerformTraversalsStart=226985727900, DrawStart=227568801800, SyncQueued=227570493400, SyncStart=227572656200, IssueDrawCommandsStart=227573994200, SwapBuffers=227727808100, FrameCompleted=227779462400, DequeueBufferDuration=30317000, QueueBufferDuration=681000, 
I/Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=842ms; Flags=1, IntendedVsync=226996035017, Vsync=227779368319, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=227781350900, AnimationStart=227781417500, PerformTraversalsStart=227781471200, DrawStart=227789661300, SyncQueued=227789698000, SyncStart=227791202300, IssueDrawCommandsStart=227791464800, SwapBuffers=227791959000, FrameCompleted=227839808200, DequeueBufferDuration=31903000, QueueBufferDuration=3708000, 
I/native: session.cc:1478 Entering Session::Pause.
I/Process: Sending signal. PID: 5908 SIG: 9
`

**Comment by amida47** [comment]
@devbridie is there a solution ?

**Comment by devbridie** [comment]
Could you please show the values you have selected in **Settings > Advanced**?

![image](https://user-images.githubusercontent.com/442644/114717567-74014580-9d35-11eb-9d65-148e7b5f8c30.png)

And how about the values in **AVD Manager > (API 29 device) > Show Details**?

![image](https://user-images.githubusercontent.com/442644/114717818-baef3b00-9d35-11eb-861d-43add29f4a85.png)

**Comment by amida47** [comment]
@devbridie thank you for your time.
here is the details:


Name: Pixel_4_API_29

CPU/ABI: Google APIs Intel Atom (x86_64)

Path: ......\.android\avd\Pixel_4_API_29.avd

Target: google_apis [Google APIs] (API level 29)

Skin: pixel_4

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_4

hw.lcd.width: 1080

hw.initialOrientation: Portrait

image.androidVersion.api: 29

tag.id: google_apis

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Pixel 4 API 29

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 2

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 2280

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images\android-29\google_apis\x86_64\

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Pixel_4_API_29

hw.lcd.density: 440

hw.arc: false

hw.device.hash2: MD5:6b5943207fe196d842659d2e43022e20

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes

and 
![image](https://user-images.githubusercontent.com/49212088/114757215-1aa41100-9d4b-11eb-8919-ee7b7018e0f7.png)
![image](https://user-images.githubusercontent.com/49212088/114757272-28f22d00-9d4b-11eb-9fb5-a4ea1dd4150e.png)

**Comment by devbridie** [comment]
Do you have this one as well?

**Comment by devbridie** [comment]
Have you tried `Desktop native OpenGL` and `Renderer Maximum` in the `Advanced` settings?

**Comment by amida47** [comment]
@devbridie thank you it finally worked after trying Desktop native OpenGL and Renderer Maximum
![image](https://user-images.githubusercontent.com/49212088/114759813-293ff780-9d4e-11eb-8daa-b31cf6ed111e.png)
but I think it is failing to detect surfaces

**Comment by devbridie** [comment]
Are you panning and rotating the camera? ARCore works best at detecting features and understanding the environment when motion information is supplied.

**Comment by amida47** [comment]
after moving the camera the app starts to pick up surfaces.
![image](https://user-images.githubusercontent.com/49212088/114768921-049d4d00-9d59-11eb-840b-7d6196791e38.png)
thank you.

**Comment by devbridie** [comment]
Glad to see it's working!
