### ISSUE TITLE
'Session.getConfig()' on a null object reference

### ISSUE THREAD

**Issue by duongbaoquy** [google-ar/arcore-android-sdk#1221]
### SPECIFIC ISSUE ENCOUNTERED
Hi, I am new to Android developer, I am trying to build a simple app on my own using ARCore. Currently I have difficulty using the Depth function. In my case, user press a Button will activate the check_depth_support function, this the check_depth_support funtion:

```
public void check_depth_support() {
        Config config = session.getConfig();
        boolean isDepthSupported = session.isDepthModeSupported(Config.DepthMode.AUTOMATIC);

        if (isDepthSupported)
        {
            config.setDepthMode(Config.DepthMode.AUTOMATIC);
            checked = true;
        }
        else
        {
            Toast.makeText(getApplicationContext(),"Depth not support on this devices",Toast.LENGTH_SHORT);
            checked = false;
        }
        session.configure(config);
    }
```

And when I press the button, I get an error: "Attempt to invoke virtual method 'com.google.ar.core.Config com.google.ar.core.Session.getConfig()' on a null object reference"
I'm following [this guide](https://developers.google.com/ar/develop/java/depth/developer-guide)
Thanks for reading

### VERSIONS USED
- Android Studio: 4.1.2
- ARCore SDK for Android: ARCore SDK ver.1.23
- Device manufacturer, model, and O/S: Android Emulator on Window 10
- Google Play Services for AR (ARCore): 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`:

**Comment by devbridie** [comment]
A [`NullPointerException`](https://stackoverflow.com/a/218510) occurred, in this instance, because `session` is `null` at the time of calling `session.getConfig()`.

**Comment by devbridie** [comment]
Check out [this section](https://developers.google.com/ar/develop/java/session-config#create_a_session) of the docs for an example on how to create and configure an ARCore session.

**Comment by duongbaoquy** [comment]
Thanks for your reply, i've tried that section, but its still not working. This is what I did:
`private Session session; // Global

    public void check_depth_support() {
        try {
            session = new Session(this);
        } catch (UnavailableArcoreNotInstalledException e) {
            e.printStackTrace();
        } catch (UnavailableApkTooOldException e) {
            e.printStackTrace();
        } catch (UnavailableSdkTooOldException e) {
            e.printStackTrace();
        } catch (UnavailableDeviceNotCompatibleException e) {
            e.printStackTrace();
        }
        Config config = new Config(session);
        boolean isDepthSupported = session.isDepthModeSupported(Config.DepthMode.AUTOMATIC);
        if (isDepthSupported)
        {
            config.setDepthMode(Config.DepthMode.AUTOMATIC);
            checked = true;
        }
        else
        {
            Toast.makeText(getApplicationContext(),"Depth not support on this devices",Toast.LENGTH_SHORT);
            checked = false;
        }
        session.configure(config);
    }`
