### ISSUE TITLE
Point cloud rendering

### ISSUE THREAD

**Issue by grassydragon** [google-ar/arcore-android-sdk#1224]
Hello!
Because the quality of the point is passed in the fourth coordinate we need to update the following line to fix the point cloud rendering:
https://github.com/google-ar/arcore-android-sdk/blob/c684bbda37e44099c273c3e5274fae6fccee293c/samples/hello_ar_java/app/src/main/assets/shaders/point_cloud.vert#L24
The correct code is:
`gl_Position = u_ModelViewProjection * vec4(a_Position.xyz, 1.0);`

Alternatively, it is possible to support the stride in the `VertexBuffer` class to pass the `a_Position` attribute as `vec3`. However, we can use the quality to set the point color based on that.

**Comment by devbridie** [comment]
Thanks, this should make it out in the next release.
