### ISSUE TITLE
Differentiate between two planes detected in adjacent vertical walls in the room

### ISSUE THREAD

**Issue by agh372** [google-ar/arcore-android-sdk#1225]
### SPECIFIC ISSUE ENCOUNTERED
I'm working on Vertical plane detection. 

When I'm pointing at wall 1 of my room, plane1 here is the vertical plane detected in wall 1...
I'm recording the quaternion via this formula
```
 val quat =  Quaternion(plane1.centerPose.qx(), plane1.centerPose.qy(), plane1.centerPose.qz(), plane1.centerPose.qw())
```
Now, when I point my phone to the other wall (adjacent) of my room and check its rotation, I get the same values, I assumed this is the world rotation. Let me know if I'm wrong.

Is there any other way where I could differentiate between vertical planes detected in adjacent walls

I'm using this to loop through the detected planes

```
 for (plane1 in frame.getUpdatedTrackables(Plane::class.java)) {
                if (plane1.trackingState === TrackingState.TRACKING) {
                    val type: Plane.Type = plane1.type
                    if (type == Plane.Type.VERTICAL) {
```

### VERSIONS USED
- Android Studio: 4.1.1
- ARCore version: 1.15.0

**Comment by devbridie** [comment]
I'm unable to reproduce; checking the quaternions for vertical planes shows that the planes are oriented differently:

```
E/PLANEORIENTATION: Plane -1895584923: Quaternion: 0.64778304 -0.5840759 0.28350863 0.3985666
E/PLANEORIENTATION: Plane -1895527579: Quaternion: 0.7043425 -0.7027302 0.062463317 -0.07855108
```

Please try out the following for on your device (I'm using https://quaternions.online/ to visualize the quaternion result).


```
    Log.e("PLANEORIENTATION", "------------");
    for (Plane plane : session.getAllTrackables(Plane.class)) {
      if (plane.getTrackingState() == TrackingState.TRACKING && plane.getType() == Plane.Type.VERTICAL) {
        Pose p = plane.getCenterPose();
        Log.e("PLANEORIENTATION", "Plane " + plane.hashCode() + ": Quaternion: " + p.qw() + " " + p.qx() + " " + p.qy() + " " + p.qz());
      }
    }
```

**Comment by agh372** [comment]
Yeah, my bad! I assumed the list of planes that I get from `session.getAllTrackables(Plane.class)` are the ones that appear on the current frame. But it turns out, the planes which appeared in previous frames are getting looped here as well. We can close this.
