### ISSUE TITLE
Invalid plane finding on devices with ToF depth sensor when pitching device up and down

### ISSUE THREAD

**Issue by Alex-MSFT** [google-ar/arcore-android-sdk#1226]
### SPECIFIC ISSUE ENCOUNTERED
We recently encountered a regression in plane finding in the [BabylonNative](https://github.com/BabylonJS/BabylonNative) playground application when running on Samsung devices that have a ToF hardware depth sensor.  Plane finding will find invalid planes at the height of the device when pitching the device up and down.

After some investigation we found this also occurs in other AR applications including the Google Measure App.

### VERSIONS USED
- Android Studio: 4.1.1
- ARCore SDK for Android: 1.14.0
- Device manufacturer, model, and O/S: Samsung Galaxy Note 10+ & S10+
- Google Play Services for AR (ARCore):  1.23.210260603
- Output of `adb shell getprop ro.build.fingerprint`: samsung/d2que/d2q:11/RP1A.200720.012/N975U1UEU6FUCD:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Install the Google Measure App
 2. Find tracking on the floor
 3. Pitch phone up and down, and observe there is a plane that follows the device's pitch vertically until the device is no longer pointed towards the floor.

Gif of issue in the Google Measure App:
![depth_sensor](https://user-images.githubusercontent.com/27031140/116485128-52c54c80-a83f-11eb-8b96-ca7374d4d0f8.gif)

### WORKAROUNDS (IF ANY)
Disabling the depth sensor in the ARCore camera configuration seems to correct this issue, but results in a regression to plane finding time and plane accuracy for real planes.

eg. 

            ArCameraConfigFilter* cameraConfigFilter{};
            ArCameraConfigFilter_create(session, &cameraConfigFilter);
            ArCameraConfigFilter_setDepthSensorUsage(session, cameraConfigFilter, 2 /* AR_CAMERA_CONFIG_DEPTH_SENSOR_USAGE_DO_NOT_USE */);

            ArCameraConfigList* cameraConfigList{};
            ArCameraConfigList_create(session, &cameraConfigList);
            ArSession_getSupportedCameraConfigsWithFilter(session, cameraConfigFilter, cameraConfigList);

            ArCameraConfig* cameraConfig{};
            ArCameraConfig_create(session, &cameraConfig);
            ArCameraConfigList_getItem(session, cameraConfigList, 0, cameraConfig);
            ArSession_setCameraConfig(session, cameraConfig);

**Comment by devbridie** [comment]
Could you try HelloAR (Java) to rule out app behavior? If you don't have a compatible build environment set up, I could provide a build.

**Comment by devbridie** [comment]
It would also be great if you had access to a non-ToF device that supports Depth API to ensure that the problem is ToF-related. I can't reproduce on two devices I have at home (non-tof, unfortunately).

**Comment by Alex-MSFT** [comment]
Overnight my ARCore package updated to version: 1.24.210950403, and I have not been able to repro yet, so it might already be resolved.

If I roll back to version 1.23.210260603 then for the Hello AR application the first few AR sessions on the device will work as expected, but eventually the device seems to get into some kind of bad state and all subsequent AR sessions will reproduce the issue.  I also tested on a Pixel 3A device with the same version of ARCore and was not able to reproduce the issue.

I will roll my version forward to the latest from the Google Play store and let you know if I get a repro on the latest version.

![hello_ar](https://user-images.githubusercontent.com/27031140/116600517-3cba9900-a8de-11eb-9cda-0e038a85af23.gif)

**Comment by devbridie** [comment]
Thanks for following up; looking forward to hearing the results.

**Comment by Alex-MSFT** [comment]
After many sessions of usage this issue has not been reproducible on 1.24.210950403.  Closing this issue for now.
