### ISSUE TITLE
ClassCastException: Cannot cast DepthPoint to Point

### ISSUE THREAD

**Issue by SimonMarquis** [google-ar/arcore-android-sdk#1230]
### SPECIFIC ISSUE ENCOUNTERED

Calling `session.getAllTrackables(Point::class.java)` sometimes triggers the following exception:

```
    java.lang.ClassCastException: Cannot cast com.google.ar.core.DepthPoint to com.google.ar.core.Point
        at java.lang.Class.cast(Class.java:2446)
        at com.google.ar.core.Session.convertNativeTrackablesToCollection(Session.java:4)
        at com.google.ar.core.Session.getAllTrackables(Session.java:4)
```

### VERSIONS USED
- Android Studio: Android Studio Bumblebee | 2021.1.1 Canary 1
- ARCore SDK for Android: 1.24.0
- Device manufacturer, model, and O/S: Pixel 4 XL on Android 11
- Google Play Services for AR (ARCore): `1.24.210950403`
- Output of `adb shell getprop ro.build.fingerprint`:  `google/coral/coral:11/RQ2A.210505.002/7246365:user/release-keys`

### STEPS TO REPRODUCE THE ISSUE

Happens when DepthMode is enabled:

```kotlin
config.depthMode = Config.DepthMode.AUTOMATIC
```

And calling `session.getAllTrackables(Point::class.java)` on each frame.

### WORKAROUNDS (IF ANY)

Request every kind of `Trackable` and do the filtering on the caller side:

```kotlin
session.getAllTrackables(Trackable::class.java).filterIsInstance<DepthPoint>()
```

**Comment by devbridie** [comment]
Confirmed. This occurs in the case specified by the original post, using `session.getAllTrackables(Point::class.java)` (Java: `session.getAllTrackables(Point.class)`) mistakenly returns `DepthPoint`s, which are incorrectly casted  as `Point`s in Java-side JNI. Furthermore, `session.getAllTrackables(DepthPoint::class.java)` will always be empty.

We're discussing the follow-up steps at the moment. In the mean time, please use the workaround specified in the original comment by requesting all trackables using `Trackable::class.java` and filtering on the client-side:

```kotlin
session.getAllTrackables(Trackable::class.java).filterIsInstance<DepthPoint>()
```
