### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException:

### ISSUE THREAD

**Issue by akshatbahety** [google-ar/arcore-android-sdk#1232]
### SPECIFIC ISSUE ENCOUNTERED
Error is only present during the Release version and not in Debug Versions.

```
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.google.android.filament.NioUtils" 
```

The issue happens when the intent is clicked to open a AR fragment I am using [SceneForm maintained here](https://github.com/ThomasGorisse/sceneform-android-sdk) to display the models

```
      Intent intent = new Intent(v.getContext(), MainActivity.class);
     startActivity(intent);
```

### VERSIONS USED
- Android Studio: 4.2
- ARCore SDK for Android: 1.23
- Device manufacturer, model, and O/S:  One Plus 7,7T,8T

### STEPS TO REPRODUCE THE ISSUE
 1. Create an Intent to open another activity
 2. With the following in onCreate
```
super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);
        getSupportFragmentManager().addFragmentOnAttachListener((fragmentManager, fragment) -> {
            if (fragment.getId() == R.id.arFragment) {
                arFragment = (ArFragment) fragment;
                arFragment.setOnTapArPlaneListener(MainActivity.this);
            }
        });

        if (savedInstanceState == null) {
            if (Sceneform.isSupported(this)) {
                getSupportFragmentManager().beginTransaction()
                        .add(R.id.arFragment, ArFragment.class, null)
                        .commit();
            }
        }
```
 3. 

### WORKAROUNDS (IF ANY)
Still finding out

### ADDITIONAL COMMENTS
I opened this on SO too - https://stackoverflow.com/questions/67685693/jni-detected-error-in-application-jni-newglobalref-called-with-pending-exceptio
got some feedback but only coming up with JNI exception in NDK I am working on android SDK

New to AR core could be missing something that I should know about thanks in Advance for any help.

**Comment by akshatbahety** [comment]
I really want to understand why this is happening only in release build and the Debug build runs perfectly.

**Comment by devbridie** [comment]
Sounds like your application has some wrong proguard rules; the symbol `com.google.android.filament.NioUtils` is probably being renamed in production builds, but not in debug builds.

See https://github.com/google/filament/blob/main/android/proguard-rules.pro and https://github.com/google/filament/blob/main/android/filament-android/src/main/java/com/google/android/filament/NioUtils.java.

Closing as this is not an ARCore related issue.

**Comment by akshatbahety** [comment]
@devbridie thanks a lot
