### ISSUE TITLE
Is there demo about arcore get byte data from camera  without glsurfaceview?

### ISSUE THREAD

**Issue by mikelhm** [google-ar/arcore-android-sdk#1233]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- Google Play Services for AR (ARCore):  
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by devbridie** [comment]
ARCore requires an active GL context to function; currently, there's no support for ARCore functionality without a GLSurface view (or similar methodology used to obtain a GL context).
