### ISSUE TITLE
Depth API is not supported in realme 8 Pro even if its mentioned in the AR core supported device list.

### ISSUE THREAD

**Issue by shrungBhatt** [google-ar/arcore-android-sdk#1237]
### SPECIFIC ISSUE ENCOUNTERED
As mentioned in the list of [AR Core supported devices](https://developers.google.com/ar/devices), realme 8 pro is one of the device that supports the Depth API. However, when I run the [depth API sample project](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/raw_depth_java), The application keeps showing the snack bar "This device does not support the ARCore Raw Depth API."

### VERSIONS USED
- Android Studio: 4.2.1
- ARCore SDK for Android:  1.24.0
- Device manufacturer, model, and O/S: realme, 8 pro, Android 11
- Google Play Services for AR (ARCore):  1.24.210950403
- Output of `adb shell getprop ro.build.fingerprint`: realme/RMX3081/RMX3081L1:11/RKQ1.201112.002/1610790354385:user/release-keys

**Comment by devbridie** [comment]
This device has since been removed from the page, where it was incorrectly listed as having depth support.
