### ISSUE TITLE
PointCloud.getPoints returning some NaN on Pixel 2

### ISSUE THREAD

**Issue by achuvm** [google-ar/arcore-android-sdk#124]
On our Pixel 2, PointCloud.getPoints is returning NaN for some position values.

We do not see this on the S8, the Pixel or the Pixel XL (we don't have a Pixel 2 XL to test with).

**Comment by achuvm** [comment]
Actually, ARCore Preview 1 did return NaN for all values, if the camera was covered/obscured.

**Comment by pawlusmall** [comment]
On Pixel 2 XL I'm trying to read points like this:

`FloatBuffer pb = pointCloud.getPoints();
  int nPoints = pb.remaining() / 4;
  for (int i = 0; i < nPoints; i++) {
      float x = pb.get(i * 4);
      float y = pb.get(i * 4 + 1);
      float z = pb.get(i * 4 + 2);
      float confidence = pb.get(i * 4 + 3);
 }`

But I'm getting very strange point and confidence values:

x: 1.3468527E-19 y: -2.1316514E-30 z: 0.0 confidence: 1.34690185E13 (why not between 0-1?)
x: 2.0026862E-9 y: 0.67168957 z: -1.3817235E-30 confidence: 1.7454151
...

**Comment by achuvm** [comment]
Actually this isn't an issue(?) any longer? The Pixel 2 I was using had ARCore Preview 1 install, the ARCore App installed from the Play Store (to use with the [AR Stickers](https://play.google.com/store/apps/details?id=com.google.vr.apps.ornament&hl=en)), ARCore Preview 2, as well as a smattering of other test apps dependent on Preview 1 and 2.

**Comment by pawlusmall** [comment]
Ok, I think I also had an old version of ARCore installed, probably the one from Play Store. (0.91.171127...) With the last build from github (0.91.171204...) I can get good values from point cloud.

**Comment by inio** [comment]
@achuvm @pawlusmall Thanks for the update!  Closing.
