### ISSUE TITLE
Unused shaders in hello_ar_java project

### ISSUE THREAD

**Issue by ts-stevem** [google-ar/arcore-android-sdk#1241]
[ambient_intensity.vert](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/assets/shaders/ambient_intensity.vert) and [ambient_intensity.frag](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/assets/shaders/ambient_intensity.frag) shaders in assets folder not used in project, would be great if they could be wired up to demonstrate refinement of lighting model (or removed to reduce confusion if they've been replaced by `environmental_hdr.frag/.vert`)

**Comment by devbridie** [comment]
Removed in 3847878dae324c53f5dace1a4b1736df9ce070c9.
