### ISSUE TITLE
raw_depth_java sample project: how to change transparency of the point cloud ?

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1244]
Hi,

I would like to add a alpha channel on the point cloud in order to make it transparent. I want to apply the same transparency to the whole point cloud, like if the point cloud was drawn in a layer and that this layer has an alpha, in order to avoid that several superimposed points are less transparent than one single point. 

How can I do that ? (probably in Renderer.java of in depth_point_cloud.frag or depth_point_cloud.vert)

Thanks.

**Comment by devbridie** [comment]
I'd imagine that you'd have to first render the point cloud to a [frame buffer](https://learnopengl.com/Advanced-OpenGL/Framebuffers). Then you could re-render this frame buffer on top of your scene with an alpha color transformation applied to the framebuffer tex.

Closing as this issue isn't related to ARCore in particular.
