### ISSUE TITLE
Bug: PointCloud confidence values very low

### ISSUE THREAD

**Issue by achuvm** [google-ar/arcore-android-sdk#125]
We used to get a good spread of values between 0 and 1, but now we're getting values much much lower such that we used to filter bad points out at around .1, but now are filtering bad points out at .0001 to observe the same point cloud density.

The environment and devices are the same.

**Comment by inio** [comment]
That's interesting.  Not quite sure it's a bug as we don't document the meaning of the confidence values, but we'll take a look into the behavior change.

**Comment by inio** [comment]
After some digging - it turns out that this is an already-known issue with DP2 that will be fixed in 1.0.

**Comment by inio** [comment]
This should be fixed with 1.0 released today on the Play Store.  Update your ARCore and point cloud confidence values should be more reasonable.
