### ISSUE TITLE
ArPose jumps

### ISSUE THREAD

**Issue by blackarrow13** [google-ar/arcore-android-sdk#1252]
### SPECIFIC ISSUE ENCOUNTERED
I have an app that uses the native ARCore library. The app renders the camera image, onDrawFrame of GLSurfaceView.Renderer I call the native code to update the ArSesson and frame and get the latest ArPose. For each frame I print the pose matrix.
When I use the app and slowly move around the room, I have seen that sometimes the ArPose jumps by a few meters without any apparent reason (the tracking state does not change to limited or anything like that), just in one frame. These jumps do not look like some drift correction (sometimes the pose corresponds to a location outside of the room where I never walked).
I have observed this behavior on several devices - the best one was Galaxy s10e which normally has pretty good performance (it does not look like the device was too slow to process a frame). It does not happen too often (roughly once per few minutes) and there is no clear pattern to these jumps.
Any idea what could be behind this behavior?

### VERSIONS USED
- Android Studio: 4.2.1
- ARCore SDK for Android: 1.25.0, 1.23.0
- Device manufacturer, model, and O/S: Samsung Galaxy s10e, Google Pixel 2 XL, ASUS ZenFone A002 V570KL 
- Google Play Services for AR (ARCore):  1.25.211460003

### STEPS TO REPRODUCE THE ISSUE
Simply look at the ArPose matrix values for each frame, print them if a jump happened.
The code snippet looks like this:

```c
	ArCamera_getPose(ar_session, ar_camera, ar_pose);

	std::array<float, 16> pose_matrix = {0., 0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.};
	ArPose_getMatrix(ar_session, ar_pose, pose_matrix.data());

	float x_diff = std::fabs(pose_matrix[12] - previous_pose_matrix_[12]);
	float y_diff = std::fabs(pose_matrix[13] - previous_pose_matrix_[13]);
	float z_diff = std::fabs(pose_matrix[14] - previous_pose_matrix_[14]);

	if (x_diff > 1.5 || y_diff > 1.5 || z_diff > 1.5) {
		     LOGE"\n ArCore pose matrix : %f %f %f %f \n %f %f %f %f \n %f %f %f %f \n %f %f %f %f ",
		     pose_matrix[0], pose_matrix[1],pose_matrix[2],pose_matrix[3],
		     pose_matrix[4],pose_matrix[5],pose_matrix[6],pose_matrix[7],
		     pose_matrix[8],pose_matrix[9],pose_matrix[10],pose_matrix[11],
		     pose_matrix[12],pose_matrix[13],pose_matrix[14],pose_matrix[15]);

		    LOGE("\n previous ArCore pose matrix : %f %f %f %f \n %f %f %f %f \n %f %f %f %f \n %f %f %f %f ",
		     previous_pose_matrix_[0], previous_pose_matrix_[1],previous_pose_matrix_[2],previous_pose_matrix_[3],
		     previous_pose_matrix_[4],previous_pose_matrix_[5],previous_pose_matrix_[6],previous_pose_matrix_[7],
		     previous_pose_matrix_[8],previous_pose_matrix_[9],previous_pose_matrix_[10],previous_pose_matrix_[11],
		     previous_pose_matrix_[12],previous_pose_matrix_[13],previous_pose_matrix_[14],previous_pose_matrix_[15]);
	}

	previous_pose_matrix_ = pose_matrix;
```

In the logs sometimes I see pose jumping by a few meters in just one frame (I am looking at the last row):

```
 ArCore pose matrix : 
0.167431 -0.915235 -0.366485 0.000000 
 -0.962465 -0.071199 -0.261901 0.000000 
 0.213608 0.396579 -0.892803 0.000000 
 -0.491471 0.467110 -4.628103 1.000000 

 previous ArCore pose matrix : 
0.260916 -0.925241 0.275412 0.000000 
 0.580681 -0.077487 -0.810435 0.000000 
 0.771189 0.371382 0.517052 0.000000 
 -2.597998 0.357178 1.076960 1.000000
```

### COMMENTS
I have seen a similar issue in the tracker https://github.com/google-ar/arcore-android-sdk/issues/1001 , but in my case I do not use anchors.

**Comment by devbridie** [comment]
Could you elaborate what happens to the relative difference between your camera's pose and the pose of objects in the AR scene? E.g. if you're looking at an anchor when the camera pose jumps, does the anchor move out of view or stay fixed in the viewport of the camera?

**Comment by blackarrow13** [comment]
My real project setup is more complicated - I use the relative movement from ArCore to visualize my position on the building map, I do not use anchors. I do, however, see the position jumps on the building map when I walk around. When investigating this issue I printed the ArCore pose and saw the jumps in the logs. 
I suppose I could create a minimal example to reproduce the issue, but there would be no easy way to visualize the jumps except for printing them.

**Comment by devbridie** [comment]
There are no guarantees on relationships between coordinates in different invocations of `Session.update`. The numerical values of poses shouldn't be used outside of the scope of these frames for this reason. See [Pose documentation](https://developers.google.com/ar/reference/java/com/google/ar/core/Pose#world-coordinate-space) for more details.

**Comment by blackarrow13** [comment]
Thank you for the explanation, it seems I had a wrong understanding of how things work.
If I now get it right, I can, however, track my relative movement by calculating the distance the between anchor and the camera, this distance should not suddenly jump. Is that correct?

**Comment by devbridie** [comment]
That's correct!

**Comment by blackarrow13** [comment]
Great, thank you! I will close this issue.
