### ISSUE TITLE
java.lang.IllegalStateException  in  method acquireDepthImage

### ISSUE THREAD

**Issue by mikelhm** [google-ar/arcore-android-sdk#1256]
java.lang.IllegalStateException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:16)
        at com.google.ar.core.Frame.nativeAcquireDepthImage(Native Method)
        at com.google.ar.core.Frame.acquireDepthImage(Frame.java:1)

**Comment by devbridie** [comment]
Did you enable a depth mode? Please see the docs for [`acquireDepthImage`](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquireDepthImage-).

> 


IllegalStateException | if a supported depth mode was not enabled in Session configuration.
-- | --


<br class="Apple-interchange-newline">

**Comment by mikelhm** [comment]
> Did you enable a depth mode? Please see the docs for [`acquireDepthImage`](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquireDepthImage-).
> 
> > 
> 
> IllegalStateException	if a supported depth mode was not enabled in Session configuration.

**Comment by mikelhm** [comment]
> Did you enable a depth mode? Please see the docs for [`acquireDepthImage`](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquireDepthImage-).
> 
> > 
> 
> IllegalStateException	if a supported depth mode was not enabled in Session configuration.

session.isDepthModeSupported(Config.DepthMode.AUTOMATIC)  return false  In my phone.

at this time ,  can Session configuration be set supported depth mode??

**Comment by devbridie** [comment]
No, only supported depth modes (i.e. `session.isDepthModeSupported` returns `true`) can be used as a value for `config.setDepthMode`.

**Comment by mikelhm** [comment]
> No, only supported depth modes (i.e. `session.isDepthModeSupported` returns `true`) can be used as a value for `config.setDepthMode`.

that is to say ： the phone that is  unsupported depth modes can not call acquireDepthImage？？？

What api can i use to get the camera preview data??

**Comment by devbridie** [comment]
> the phone that is unsupported depth modes can not call acquireDepthImage

That's correct; depth mode can only be used on [Depth-supported devices](https://developers.google.com/ar/devices#google_play).

> What api can i use to get the camera preview data?? 
Yes, [`frame.acquireCameraImage`](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquireCameraImage-) retrieves a colored image as it might appear in the camera preview.

**Comment by mikelhm** [comment]
> > the phone that is unsupported depth modes can not call acquireDepthImage
> 
> That's correct; depth mode can only be used on [Depth-supported devices](https://developers.google.com/ar/devices#google_play).
> 
> > What api can i use to get the camera preview data??
> > Yes, [`frame.acquireCameraImage`](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquireCameraImage-) retrieves a colored image as it might appear in the camera preview.

thank you very much.
