### ISSUE TITLE
About subsumed plane

### ISSUE THREAD

**Issue by guofengw** [google-ar/arcore-android-sdk#1258]
Hi guys,

I have a little doubt about why arcore pop up a API named ArPlane_acquireSubsumedBy.
everytime, when we draw planes, we need to call this API, then filter the plane if its subsumed plane is not nullptr.

Why not just pop up the only one plane when these planes merge together? Thanks.

**Comment by devbridie** [comment]
Imagine your app has detected a plane and you have designated this as your game's arena, which is the plane that the game is played on, for example. However, these planes may be joined together (subsumed) at some point if ARCore thinks the planes are actually the same physical plane. Without the subsumed function, in the eyes of your app, the plane `A` would just disappear and a new one would spawn, and you would lose information on which plane was the arena in a previous frame. 

With subsuming you could now know that the plane has become larger by means of merging. The subsumed function designates the relationship between the old plane and the new plane.

Hope that clears it up a little!

**Comment by guofengw** [comment]
Thanks for reply.
I know you meaning, but the problem i think may be solved by anchor.
If two or more planes are merged, the anchor located from plane A can change to locate in its parent plane (the user don't know this process), in that way, the anchor still exist, so the user will not affect.

**Comment by devbridie** [comment]
That would be correct for an anchor, but an anchor can only designate one point in space. You may be using the plane to draw the playing field, for example; this is more difficult to do using just anchors.

**Comment by guofengw** [comment]
Ok. i have one question, if the user don't use plane A, when it is merged, the arcore will delete this plane, or this plane will exist for ever?

**Comment by devbridie** [comment]
From the view of the API, I think it will appear to continue to exist, though there's definitely some optimization happening there. Not certain on the memory details, sorry.
