### ISSUE TITLE
How to get camera preview data without using glsurfaceview in ar core

### ISSUE THREAD

**Issue by mikelhm** [google-ar/arcore-android-sdk#1259]
In  hello_ar demo,  it use glsurfaceview to show camera preview data.

but in my demand， i don't need to show camera preview.  

so my solution is to use 1px glsurfaceview.   Then i can get the camera preview data in the callback : onDrawFrame(SampleRender render),    I know that is not a best way.

Does someone know how to get camera preivew data without using glsurfaceview in ar core ??

**Comment by devbridie** [comment]
ARCore requires a GL context. Thus, a GLSurfaceView or similar is required; you could look at taking out the parts you'd need from [`GLSurfaceView`](https://android.googlesource.com/platform/frameworks/base/+/master/opengl/java/android/opengl/GLSurfaceView.java) but that seems more difficult than [`setRenderMode`](https://developer.android.com/reference/android/opengl/GLSurfaceView#setRenderMode(int)).
