### ISSUE TITLE
Phone locked out can't get service

### ISSUE THREAD

**Issue by Jeff197911** [google-ar/arcore-android-sdk#1264]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- Google Play Services for AR (ARCore):  
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by Jeff197911** [comment]
How can I put service

**Comment by devbridie** [comment]
Sorry to hear you're having problems with your device. Unfortunately, I can't help you out here; this board is intended for ARCore developers.
