### ISSUE TITLE
Why does the size of the virtual object change

### ISSUE THREAD

**Issue by wangni-bupt** [google-ar/arcore-android-sdk#1267]
When using hello_ar, I noticed that the model might be small after clicking and then bigger after moving. I wonder why

note:I canceled the plane recognition

https://user-images.githubusercontent.com/54091157/125561174-6587d68c-9fa6-44b7-b7e9-e2a803c26ef9.mp4

**Comment by devbridie** [comment]
This could depend on the options you may have enabled in the sample:

When Instant Placement is enabled, ARCore will give you an anchor at an estimated pose and will update this pose when the real position of the object becomes known. This could cause the pop-in that's observable in your video. 

If depth mode is enabled, you could verify if the depth map looks strange.

**Comment by GokulDas027** [comment]
@devbridie Is it possible to prevent this instant size change? I have plane tracking disabled in my app, yet this size change happens

**Comment by devbridie** [comment]
ARCore will report the best-known positions for anchors and other trackables in the world; if you want to prevent pop-in and other effects caused by the changes in these positions, you'll need to detect this case (e.g. delta shift in position is too large) and do some interpolation.
