### ISSUE TITLE
Open a thread to get the camera image

### ISSUE THREAD

**Issue by wangni-bupt** [google-ar/arcore-android-sdk#1274]
I want to open a new thread to get the image of the camera and do identification detection and other operations, but it cannot be implemented.
First I start threads execute camera.updata() in onresume, but will report MissingGlContextException, according to the answer, know that calls the method must be invoked in the gl thread.
I guess I can't do that, so what should I do?
At present, my other idea is to access camera images through Shared camera access with ARCore. Is this feasible?

**Comment by devbridie** [comment]
This isn't a usecase supported by ARCore. You could look at deconstructing [`GLSurfaceView`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/opengl/java/android/opengl/GLSurfaceView.java;l=1245;drc=53ada2ab282c1b6b72365bc1c6b7aaa29e170eca) for its implementation of GLThread, or you could create a dummy invisible surface view and operate ARCore normally within those constraints.
