### ISSUE TITLE
Ability to use front facing camera [Change default camera]

### ISSUE THREAD

**Issue by mehdiae** [google-ar/arcore-android-sdk#128]
Is there any way to use front camera instead of back camera for ARCore applications? I am using a system which has a HDMI input and a camera. The HDMI is mapped into Back_Camera and the camera is mapped into Front_Camera.

**Comment by inio** [comment]
ARCore is currently only supported on the Pixels and S8.  Are you working with one of those devices?

**Comment by fredsa** [comment]
Updated issue title to "Ability to use front facing camera" as the feature request.

> Note, ARCore uses a combination of the camera image, device sensor data, and a device calibration profile, to determine the device's position and orientation in the world. This means that arbitrary HDMI camera input wouldn't work.

**Comment by devbridie** [comment]
[CameraConfig.FacingDirection.FRONT](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.FacingDirection#public-static-final-cameraconfig.facingdirection-front) can be used to use the front-facing camera.

**Comment by gptshubham595** [comment]
this can help one, I wrote article to switch cameras!

https://gptshubham595.medium.com/unveiling-the-world-of-ar-with-arcore-my-journey-of-exploration-practical-guide-86ac7f54b34
