### ISSUE TITLE
Is it possible to track pose with ARCore without rendering anything on the UI?

### ISSUE THREAD

**Issue by jayathu** [google-ar/arcore-android-sdk#1286]
I would like to use ARCore in my existing app to simply gather device data such as Camera Pose, Planes, Objects etc as I run the session and move around using the app. I DO NOT want to render any camera feed in my app though, since there's no use case for rendering anything. Is it something that's possible to do with the existing APIs? Does ARCore officially support this type of a use case? Any sample code or references would be appreciated! Thanks much.

**Comment by GMAGD** [comment]
maybe use world anchors ( spacial anchors) 

https://developers.google.com/ar/develop/c/anchors

**Comment by jayathu** [comment]
Thanks for the response! Can you elaborate more that? I am aware of anchors but that doesn't explain how I can get away with not rendering anything and still be able to get Camera Pose. I am very new to ARCore SDK (especially on native Android) and I couldn't find any example that showcase this type of a usecase. Any code samples that can show how to achieve this would be appreciated.

**Comment by devbridie** [comment]
Currently there's no official support for using ARCore without displaying a camera feed, though I would suspect that you could follow the normal steps to create an AR session and read session data using a 1x1 SurfaceView (or even 0x0?).

You could give it a shot with hello_ar_java and modifying [this layout file](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/res/layout/activity_main.xml#L22).

**Comment by devbridie** [comment]
Please see this commit on my fork: https://github.com/devbridie/arcore-android-sdk/commit/b764e31e015628c2c1ff79ac7044fcb8d71ec6f9. Using these modifications to HelloAR, I'm seeing that the camera pose updates in real-time as the device is moved.
