### ISSUE TITLE
Objects not placing touched place in ar-core sample

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#129]
I have heart 3d object i was rendered the object in ar-core sample project,objects were rendered successfully but objects placing based on touch not working properly,when i was touch the plane objects not drawing exact position of touch,objects drawing another place in plane instead of touched place. how can i solve this issue?

**Comment by robertjuh** [comment]
Which device and which ARCore are you using?

If you download the sample project again and load in android studio and run on a compatible device, it should place andy (the 3d model for android) in the place you touched

**Comment by ArigarasuthanRepo** [comment]
iam using pixel xl and ARCore developer preview 2.Andy object placed correctly but my heart model not placed correctly

**Comment by robertjuh** [comment]
Try it with another model, or fix the pivot point of the model maybe thats the problem. It's not centered

**Comment by inio** [comment]
@ArigarasuthanRepo: I think @robertjuh is on to something.  Sounds like the model is positioned incorrectly relative to the origin.

**Comment by ArigarasuthanRepo** [comment]
yes andy model placed perfectly.

**Comment by ArigarasuthanRepo** [comment]
the object centered in blender but the object not placing touched position @robertjuh

**Comment by VidhiLatitude** [comment]
How can I put 3D object on onTouchevent and setScale for see far object ?
