### ISSUE TITLE
Question about UpdateMode.Blocking

### ISSUE THREAD

**Issue by dkmoon** [google-ar/arcore-android-sdk#1290]
Hi,

1. Does _**UpdateMode.Blocking**_ do busy waiting?
2. If time drift happens, does the mode catch up next time? (i.e. If this frame exceeds by 10msec for rendering, does the mode sleep for 10sec less or for the same 33msec next time?)

Best regards,

DK

**Comment by devbridie** [comment]
1. Does UpdateMode.Blocking do busy waiting?
    The calling thread will be blocked until the frame arrives, implemented as a while loop until the deadline is exceeded.
2. The deadline will start ticking immediately after `update()` is called; so no catch-up is used.

**Comment by dkmoon** [comment]
Thank you for the clarification.
