### ISSUE TITLE
Exception after a prompt to update Google AR service

### ISSUE THREAD

**Issue by dkmoon** [google-ar/arcore-android-sdk#1294]
### SPECIFIC ISSUE ENCOUNTERED

I tested with a smartphone with an old ARCore service.
As specified, I checked if AR core is installed and is up-to-date.
ARCore SDK detected it need to be updated and redirected to the Google Play store.
After updating the AR service, suddenly I got an exception like this:

```
E/ActivityThread(13425): Failed to find provider info for com.google.ar.core.services.arcorecontentprovider
I/ARCore-SetupContentResolver(13425): Post-install failed
I/ARCore-SetupContentResolver(13425): java.lang.IllegalArgumentException: Unknown authority com.google.ar.core.services.arcorecontentprovider
I/ARCore-SetupContentResolver(13425): 	at android.content.ContentResolver.call(ContentResolver.java:2405)
I/ARCore-SetupContentResolver(13425): 	at android.content.ContentResolver.call(ContentResolver.java:2388)
I/ARCore-SetupContentResolver(13425): 	at com.google.ar.core.ag.a(SetupContentResolver.java:8)
I/ARCore-SetupContentResolver(13425): 	at com.google.ar.core.j.k(ArCoreApkImpl.java:1)
I/ARCore-SetupContentResolver(13425): 	at com.google.ar.core.j.requestInstall(ArCoreApkImpl.java:9)
I/ARCore-SetupContentResolver(13425): 	at com.google.ar.core.j.requestInstall(ArCoreApkImpl.java:5)
...
```

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 2020.3.1 patch 2
- Device manufacturer, model, and O/S:  Samsung A32 (SM A325N)
- Google Play Services for AR (ARCore):  1.27.212430123
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: samsung/a32ks/a32:11/RP1A.200720.012/A325NKSU1AUC5:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Test with a smartphone with an old AR service.
 1.  `ArCoreApk.getInstance().requestInstall()`  will redirect to the Google Play store.
 1. Update Google AR service there. 
 1. After being updated, the app which invoked _requestInstall()_ throws the exception.

**Comment by devbridie** [comment]
This may occur when updating from a very old version of Play Services for AR to a newer one. I think this issue should be one-off, as generally large jumps in APK version do not occur.

However, it seems that though the exception is logged and not thrown. Was the `ArCoreApk.Availability` `SUPPORTED_INSTALLED`, and is it correct that your app did not crash or show otherwise strange behavior?
