### ISSUE TITLE
Frequently occurring black screen

### ISSUE THREAD

**Issue by unixzii** [google-ar/arcore-android-sdk#13]
My device is Samsung Galaxy S8 (SM-G950FD) and I've installed the ARCore service app correctly. When it's my first time to launch the sample app, everything worked fine, but after I swiped the app off from recents screen and launched again, it just showed me a black screen and a "Searching for surfaces..." toast. It wouldn't recover if reinstall it or reboot my device.

During this period, I noticed that there are no logs look wrong in Logcat.

**Comment by nathanmartz** [comment]
Very strange. What version of the OS are you running?

**Comment by unixzii** [comment]
Android 7.0 (Samsung Experience 8.1). And one important clue is that it worked fine every time I plugged the USB, once I pulled it out, the app just went black.

**Comment by nathanmartz** [comment]
Interesting. My guess is that this is a device specific issue, either the battery isn't able to deliver enough power when ARCore is running or perhaps there are specific power saver features that are disabled when the USB cable is plugged in. Given that, I don't think there's anything more we can do here, but please reopen if you find there are specific phone settings which make this problem go away when the device is unplugged.

**Comment by unixzii** [comment]
Thanks for your reminding, I'll check out those settings.
