### ISSUE TITLE
hello_ar_java Crash within 30 minutes

### ISSUE THREAD

**Issue by canaee** [google-ar/arcore-android-sdk#1311]
### SPECIFIC ISSUE ENCOUNTERED
Hello, I am using android studio for arcore development.
When I run hello_ar_java, the screen freezes and the application crashes within 30 minutes.

### VERSIONS USED

- Android Studio: 4.2.1
- ARCore SDK for Android: 1.28.0
- Device manufacturer, model, and O/S: google Pixel6 ,Android version 12
- Google Play Services for AR (ARCore):1.28.212840293  
- Output of `adb shell getprop ro.build.fingerprint`: google/oriole/oriole:12/SD1A.210817.036/7805805:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. run hello_ar_java.
 1. Continuous use.
 1. it will crash within 30 minutes.

**Comment by devbridie** [comment]
This issue was first, but still closing for duplicated at #1315 since it has a bit more information.
