### ISSUE TITLE
Google Play Developer Console: most devices listed as 'Unsupported' in 'Device Catalog'

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1317]
Hi,

I have an app that uses ARCore.

When I do to Google Play Developer Console, in the 'Device Catalog' section, I see that there are only '30 devices' listed as supporting my app.

When I set the filter to 'All devices' instead of 'Supported devices', I see that there are 19668 devices listed, almost all of them are listed as 'unsupported' (except the 30 supported devices previously mentioned).

That is really weird as I can see that all my test devices are listed as unsupported but I can see my app in Google Play and install it from Google Play without problem (my devices : Samsung A50, Samsung S7)

Note that when I check in Google Play Developer Console why the devices are not supported, the reason mentioned is:

'Doesn't support required feature: android.hardware.camera, android.hardware.camera.ar'

But this feature request is needed in the manifest in order to say that the app requires ARCore.

May you check what is happening? I don't check very often this list of devices in Google Play Developer Console but I am 100% sure that this bug with a very short supported list of devices didn't exist before (6 months-1 year ago). 

I wonder what is the impact of this bug on thee SEO in Google Play or my Google Ads campaigns. Any idea ?

Would be grateful if you could check what is the problem and solve it quickly.

Thanks.

**Comment by RGregat** [comment]
It's the same with me, I see 28 devices. A few weeks ago it was around 300

**Comment by devbridie** [comment]
I'm seeing the same. I can't speak to the effect on this on SEO or Ads; following up with the Play team.

**Comment by XubeiX** [comment]
Im have the same problem. Few weeks ago was around 300 devices. Now most of them are unsupported. 
For example Samsung Galaxy S7 is listed on https://developers.google.com/ar/devices in Google Console is unsupported - device don't support android.hardware.camera.ar feature.

On Galaxy S7 device I can install Google Play For AR from Play Store, and also I can list AR apps on Store like ARCore Elements - but I can't install them. 

I have several AR apps pre-installed and they work.

**Comment by idstein** [comment]
Google Pixel 3 is also not listed, but clearly supported according to the listening.

**Comment by HardBits** [comment]
Same issue here. This was a really troubling day. We had everything setup for an app launch preemptively, and when published today, complains started to happen about most of the devices showing as incompatible with the app. Blows my mind how could a bug as critical as this went through to affect the Play Store like this. 

Best workaround we found for this problem was to build the app with ARCore optional, and then exclude **EVERY** device except the ones supported in the ARCore documentation list. But even this is very unreliable, as some devices are ARCore compatible and not updated on the list yet. And also, there's even some devices that are listed on the ARCore supported devices and not visible on Device Catalog or using different names, making this whole situation a big big mess. 

This 'android.hardware.camera.ar' mising on the AR compatible devices seems to be the biggest culprit here. I have a Huawei P20 Pro and when looking into its System features on the Device Catalog, it just isn't there. Thus why it removes the phones from the compatible devices. 

Please fix this ASAP.

**Comment by coder89** [comment]
> Same issue here. This was a really troubling day. We had everything setup for an app launch preemptively, and when published today, complains started to happen about most of the devices showing as incompatible with the app. Blows my mind how could a bug as critical as this went through to affect the Play Store like this.
> 
> Best workaround we found for this problem was to build the app with ARCore optional, and then exclude **EVERY** device except the ones supported in the ARCore documentation list. But even this is very unreliable, as some devices are ARCore compatible and not updated on the list yet. And also, there's even some devices that are listed on the ARCore supported devices and not visible on Device Catalog or using different names, making this whole situation a big big mess.
> 
> This 'android.hardware.camera.ar' mising on the AR compatible devices seems to be the biggest culprit here. I have a Huawei P20 Pro and when looking into its System features on the Device Catalog, it just isn't there. Thus why it removes the phones from the compatible devices.
> 
> Please fix this ASAP.

Same here bro. And what's the most worrying for me is that 3 days have passed and there is no fix nor official response from Google. Some weeks/months back I was wondering why ARCore enabled apps that used to be available for both iOS and Android became iOS only. Just check the issues backlog counter - I believe this is the answer. Android development used to be crap some years back and really I hoped things have changed - oh how foolish I was....

**Comment by devbridie** [comment]
No updates to share at the moment, but the Google Play team is actively looking at this. My understanding is that this is a bug in how Play Console is enumerating the devices in this view; the actual availability of the app should not be impacted by this bug.

**Comment by HardBits** [comment]
Hey @devbridie, Thanks for the update. Just to clarify on that point, **the actual availability is being impacted by this bug**. we've had numerous reports of devices that weren't able to install with the message "your device isn't compatible with this version". The solution here was to build the app with ARCore optional (so it doesn't add the 'android.hardware.camera.ar' to the manifest) and then only allow the specific devices we want through the Device Catalog on the Play Console. 

Some of the devices where we've encontered the problem: 
- Xiaomi Redmi Note 7
- Samsung Galaxy A21S
- Xiaomi Mi Note 10 Lite

**Comment by coder89** [comment]
> No updates to share at the moment, but the Google Play team is actively looking at this. My understanding is that this is a bug in how Play Console is enumerating the devices in this view; the actual availability of the app should not be impacted by this bug.

Our experience is different. Most of our test devices we use daily suddenly (starting last Wednesday) weren't able to install new versions published to Google Play. The bad-solution was to disable "depth camera/api" requirement from the manifest manually (even though AR Foundation depends on it and even if we use Depth API in our app. Doing so made Play Console to list 29 devices as compatible (none of them being our test devices models) and we were able to install apps. However, "camera.ar" feature in manifest requirement still remains to be a problem in listing the app correctly.

So it definitely is not "just" the Play Console listing view issue but something more serious than that.

**Comment by devbridie** [comment]
Got it; escalating asap.

**Comment by devbridie** [comment]
The issue with the Play Console has been resolved; you should see all eligible devices in the Device Catalog section in the Play Console.

I'm still looking into previously-eligible devices suddenly being ineligible. If you have such a case, please share (either here, or privately to dereckbridie@google.com) the following information with me:

 * Affected device make and model;
 * The e-mail address of an affected user's Google account as registered with the Play Store.

**Comment by agGitHub** [comment]
Thanks. I have now:
- 525 devices supported for my ARCore app that doesn't use Depth API
- 252 devices supported for my app that uses Depth API

Would be great if other developers here could say if they get similar values. And if Google team could say if these numbers seem correct.

Thanks a lot for your support.

**Comment by RGregat** [comment]
Same on my side
* 525 supported devices

DepthAPI is optional in my App.

**Comment by coder89** [comment]
Same here.

**Comment by XubeiX** [comment]
Same on my side.

**Comment by l9sheen** [comment]
This has now started to become an issue again. currently I have 126 devices available when filtering with android.hardware.camera.ar on device catalog > all devices. Last week I was only getting 1 device. 

How is this a problem that has occurred again after 2 years? 
Was there any notice to this change? 

It's extremely hard to run a production app when things like this happen and limit the ability for users to download my app. Very frustrating

**Comment by MohamedPresident** [comment]
@l9sheen Same here.

**Comment by l9sheen** [comment]
@MohamedPresident You can add a comment on #1644 as that is an open issue. Hopefully devs will be looking at that one.

**Comment by agGitHub** [comment]
Any news ? Only 125 devices written as supported in GPlay Console whereas around 900 compatible devices are written in ARCore compatibility list... https://developers.google.com/ar/devices Any impact on downloads ? Please Google team, give feedback on this issue.

**Comment by makakaorg** [comment]
> Any news ? Only 125 devices written as supported in GPlay Console whereas around 900 compatible devices are written in ARCore compatibility list... https://developers.google.com/ar/devices Any impact on downloads ? Please Google team, give feedback on this issue.

Yes, the app is not listed in the Play Search for unsupported devices!
