### ISSUE TITLE
Question about the trigger condition of a specific log message..

### ISSUE THREAD

**Issue by dkmoon** [google-ar/arcore-android-sdk#1323]
I'm seeing this log message even with the sample augmented_face_java project. Wondering what causes the message and whether it's safe to ignore. Thanks.

```
E/native: E1202 09:29:45.586697    8915 aimatter_landmarks_3Dmesh.cc:749] Not able to find preprocess rotation with expected timestamp: 154037277565
```

**Comment by Android-Course-saeedi** [comment]
Is the problem solved?

**Comment by 15kingben** [comment]
This is probably safe to ignore, it's most likely caused by the cpu image stream skipping frames
