### ISSUE TITLE
Convert Pose to OpenGL ES coordinate 

### ISSUE THREAD

**Issue by majidfeyzi** [google-ar/arcore-android-sdk#1330]
Hi,
I have poses of my models and I want to connect them with line. To draw line in OpenGL ES I need two coordinate for each line. So I need to convert Pose to (x, y, z). 
How I can convert Pose to OpenGL ES coordinate (x, y, z) in android?

**Comment by devbridie** [comment]
Poses, generally, are already in OpenGL coordinate space. See https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_c/app/src/main/assets/shaders/object.vert#L32, for example.
