### ISSUE TITLE
Unable to find tracking point on plane wall with verticle plane

### ISSUE THREAD

**Issue by niravsculptsoft** [google-ar/arcore-android-sdk#1334]
### VERSIONS USED
- Android Studio: 11.0.10
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: S20 plus with Android 11
- Google Play Services for AR (ARCore):  1.29.2132

### STEPS TO REPRODUCE THE ISSUE
 1. Go to any plane wall and try to create and put object their you got following errror

Cannot create anchors while the camera is not tracking. [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_ERROR_NOT_TRACKING']
    === Source Location Trace: === 
    third_party/arcore/ar/core/status.cc:171
    third_party/arcore/ar/core/session.cc:2286
2021-12-27 14:43:57.032 26535-26535/com.incenteram.remoteval I/System.out: ============>gocom.google.ar.core.exceptions.NotTrackingException
2021-12-27 14:43:57.064 26535-26535/com.incenteram.remoteval E/native: E1227 14:43:57.064413   26535 status.cc:162] FAILED_PRECONDITION: 
    ARCoreError: third_party/arcore/ar/core/session.cc:2286
     at third_party/arcore/ar/core/session.cc:2288Cannot create anchors while the camera is not tracking. [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_ERROR_NOT_TRACKING']
    === Source Location Trace: === 
    third_party/arcore/ar/core/status.cc:171
    third_party/arcore/ar/core/session.cc:2286
2021-12-27 14:43:57.066 26535-26535/com.incenteram.remoteval I/System.out: ============>gocom.google.ar.core.exceptions.NotTrackingException
2021-12-27 14:43:57.096 26535-26535/com.incenteram.remoteval E/native: E1227 14:43:57.096217   26535 status.cc:162] FAILED_PRECONDITION: 
    ARCoreError: third_party/arcore/ar/core/session.cc:2286
     at third_party/arcore/ar/core/session.cc:2288Cannot create anchors while the camera is not tracking. [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_ERROR_NOT_TRACKING']
    === Source Location Trace: === 
    third_party/arcore/ar/core/status.cc:171
    third_party/arcore/ar/core/session.cc:2286
2021-12-27 14:43:57.097 26535-26535

**Comment by devbridie** [comment]
Please see docs for [NotTrackingException](
 https://developers.google.com/ar/reference/java/com/google/ar/core/exceptions/NotTrackingException). In this instance, the AR session doesn't have enough understanding of the world in order to create an anchor just yet. This often occurs when you're looking at a featureless white wall without extra assistance from a hardware sensor such as a time-of-flight sensor: there's not enough information there to create anchors.
