### ISSUE TITLE
Bug: Session constructor failure behavior not useful for detecting device compatability

### ISSUE THREAD

**Issue by JimEH42g** [google-ar/arcore-android-sdk#134]
I'm working on an app with AR content, but it isn't just an AR app. I'd like to be able to detect whether the current device supports ARCore so I can hide the AR section if it's not supported. The Session-based error handling in the sample code gives me UnavailableArcoreNotInstalledException in this situation, which isn't helpful because it doesn't distinguish between a compatible device that needs to have ARCore installed (in which case I want to show the AR section and prompt the user to install it if they go there) and an incompatible device (in which case I want to keep it hidden.)

Is there an API that will do this, or is the only solution to check against a list of compatible devices, updating it for each new version of ARCore?

**Comment by inio** [comment]
We'll be announcing APIs for handling proper device compatibility checks soon.

**Comment by JimEH42g** [comment]
Cool. Thanks.

**Comment by fredsa** [comment]
Created #162 to track the feature request.

**Comment by ianyuen** [comment]
Please give me new information of this issue?
