### ISSUE TITLE
Deprecation of Frame.acquireCameraImage() : replacement? This is not mentiond in the docs

### ISSUE THREAD

**Issue by sarimmehdi** [google-ar/arcore-android-sdk#1340]
It appears we are no longer able to acquire the camera image but then what is the replacement for it? This is not mentioned [here](https://developers.google.com/ar/whatsnew-arcore#whats_new_in_arcore_v1280)

**Comment by devbridie** [comment]
To clarify: **acquireCameraImage** is NOT being deprecated. Please see the [announcement](https://developers.google.com/ar/develop/java/ndk-camera-deprecation) for a more detailed explanation, but to summarize:

* There are no changes to `acquireCameraImage` if your app is compiled with a recent version of the ARCore SDK.
* If your app was compiled with an old version (1.19 or older) of the ARCore SDK, please update to a recent version to ensure your app continues to work.
