### ISSUE TITLE
How to disable ToF sensor properly ?

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1346]
Hi,

For some tests, I want to disable the ToF sensor. I wonder how to disable it properly.

At the moment, I use this code:

```
CameraConfigFilter filter = new CameraConfigFilter(session);
filter.setDepthSensorUsage(EnumSet.of(CameraConfig.DepthSensorUsage.DO_NOT_USE));
List<CameraConfig> cameraConfigList = session.getSupportedCameraConfigs(filter);
session.setCameraConfig(cameraConfigList.get(0));
```

Nevertheless, I don't know if it is the clean way to disable only the ToF without changing any of the other parameters.

Indeed, it seems that when I add this code to disable the ToF, the FPS increases from 30 to 60 FPS.

Also, I am surprised by this line of code:

`session.setCameraConfig(cameraConfigList.get(0));`

as cameraConfigList contains 18 items on my device. Why should I use only the first element for setCameraConfig ?

Any help would be appreciated!

Thanks.

**Comment by devbridie** [comment]
The first element of `getSupportedCameraConfigs` has the following [defined order](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#getSupportedCameraConfigs-cameraConfigFilter):

> * Prefer [CameraConfig.StereoCameraUsage.REQUIRE_AND_USE](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.StereoCameraUsage#REQUIRE_AND_USE) over [CameraConfig.StereoCameraUsage.DO_NOT_USE](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.StereoCameraUsage#DO_NOT_USE)
> * Prefer [CameraConfig.TargetFps.TARGET_FPS_60](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.TargetFps#TARGET_FPS_60) over [CameraConfig.TargetFps.TARGET_FPS_30](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.TargetFps#TARGET_FPS_30)
> * Prefer [CameraConfig.DepthSensorUsage.REQUIRE_AND_USE](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.DepthSensorUsage#REQUIRE_AND_USE) over [CameraConfig.DepthSensorUsage.DO_NOT_USE](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.DepthSensorUsage#DO_NOT_USE)
> 
> No guarantees are made about the order in which the remaining elements are returned.

The reason why the FPS increases to 60 FPS is because of these rules, in which 60 FPS profiles come before 30 FPS profiles.

If you want everything the same except DepthSensorUsage from ON to OFF, you could try the following snippet:

```
    val filter = CameraConfigFilter(session).apply {
      val currentConfig = session.cameraConfig
      this.facingDirection = currentConfig.facingDirection
      this.stereoCameraUsage = EnumSet.of(currentConfig.stereoCameraUsage)

      this.depthSensorUsage = EnumSet.of(CameraConfig.DepthSensorUsage.DO_NOT_USE)
      this.targetFps = EnumSet.of(if (currentConfig.fpsRange.upper >= 60) CameraConfig.TargetFps.TARGET_FPS_60 else CameraConfig.TargetFps.TARGET_FPS_30)
    }
```

Then selecting one of the camera configs that suits your needs best (arising from processing times for larger CPU and GPU textures).
