### ISSUE TITLE
Augmented face may run on PC or Mac?

### ISSUE THREAD

**Issue by cinita** [google-ar/arcore-android-sdk#1349]
Hi developers, thanks to spend your time to help answer some question here~

1. Is ARCore an open-source project? only see sample on github without source code, If is, how and where to contribute code?
2. Augmented face may run on PC and Mac currently or in future?

**Comment by devbridie** [comment]
ARCore only has open source samples, which are contained in this repository. Currently, there isn't any way to contribute to ARCore itself, though improvements to the samples are welcomed!

ARCore only runs on supported Android and iOS devices; no plans for PC or Mac.

**Comment by cinita** [comment]
Got you! thanks a lot, best wishes for you.
