### ISSUE TITLE
Transfer persistent cloud anchors from one package to another package

### ISSUE THREAD

**Issue by sarimmehdi** [google-ar/arcore-android-sdk#1352]
### SPECIFIC ISSUE ENCOUNTERED
I have two apps that wish to share cloud anchors but both have different package names. Is it possible?

**Comment by devbridie** [comment]
My understanding is that projects under the same GCP project should be able to share Cloud Anchors, no matter the package name.

**Comment by sarimmehdi** [comment]
@devbridie thank you very much, I created a new oauth 2.0 client under my GCP (with a different package name) and I was able to resolve the anchor that I created with another app (both apps have different package names that are under the same GCP).
