### ISSUE TITLE
3D model showing on the top of other view

### ISSUE THREAD

**Issue by Amitdygon** [google-ar/arcore-android-sdk#1367]
My 3D model showing on the front of other view i tried alots with differnt xml and ui but its still show like this. Thanks

[Screenshot_20220324_124156.zip](https://github.com/google-ar/arcore-android-sdk/files/8339221/Screenshot_20220324_124156.zip)

https://user-images.githubusercontent.com/45029280/159863084-74eb5b42-8606-4099-b388-8f412746df62.mp4

**Comment by devbridie** [comment]
Hi,
This doesn't seem related to the ARCore SDK for Android.
