### ISSUE TITLE
Feature Request: Support x86 processor architecture

### ISSUE THREAD

**Issue by ianyuen** [google-ar/arcore-android-sdk#138]
I tried decompress core-0.91.0.aar and see you have not x86 library.

**Comment by inio** [comment]
For DP2 we only support on-device testing on the supported models, all of which are arm64-v8a (with backwards compatibility to armeabi-v7a).

**Comment by inio** [comment]
With the release of 1.0, ARCore is now [supported in the emulator](https://devsite.googleplex.com/ar/develop/java/emulator), including for x86 architectures.

Does that satisfy your needs?

**Comment by codehero3** [comment]
Hi inio,
Is it possible to run ARCore on a x86 device, not by emulator?
