### ISSUE TITLE
Crashes and reboots when adding anchors

### ISSUE THREAD

**Issue by soderbjorn** [google-ar/arcore-android-sdk#141]
I am experimenting with a codebase originally derived from the sample application. Instead of attaching anchors to a plane, I store the camera pose on specific occasions and later attach anchors based on that stored pose but with some position offset. This usually works fine but occasionally I get one of the following problems:
1) Exception without further detail when I try to create the anchor, with a prior log entry of: `query_timestamp_s is not in the valid range` (may be just a coincidence)
2) Exception without further detail when I try to create the anchor, with a prior cryptic log message saying: `Could not create PoseNode`
3) The phone freezes for about three seconds and then reboots (Google Pixel 2)

Although I'm not sure, my feeling is that these problems tend to happen more when the camera is closer to a wall at the time the anchor is being created (but still in tracking state). In any case, this makes ARCore unreliable for me. I would appreciate any ideas about what could cause anchor creation to fail and/or how to trouble-shoot this on a deeper level.

Thanks in advance,

Best Regards,
Robert

**Comment by inio** [comment]
If you want to store a physical location across calls to Session.update(), you always need to create a anchor immediately.  Admittedly, we should be producing better error messages.

Are you holding onto an old Frame object and creating the anchor using that?

That said, anything causing a device reboot is ... pretty crazy.  We shouldn't be able to do that from a normal app (ARCore doesn't have any magical permissions).  How reliably can you produce the reboot?  Could we get an APK to test locally?

**Comment by soderbjorn** [comment]
Thank you for your quick reply, @inio -- much appreciated. In fact, I was inadvertently re-using Pose objects between frames in some cases. I have fixed this and will report back when I have tested more exhaustively.

**Comment by inio** [comment]
@soderbjorn BTW, If you keep seeing these error, please attach a full logcat.  There's a lot of useful signal in the exception and preceding warning/error messages.

**Comment by soderbjorn** [comment]
I couldn't reproduce this easily. For the time being I'm assuming the cause was my occasional re-use of Pose objects and closing this for now. Will return if problem comes back up. Thanks for the feedback!
