### ISSUE TITLE
Is it possible to add focus square marker like ARKit focus square marker in ar-core android ?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#142]
i have working sample ar-core app.i want to add a focus square marker like ARkit focus square marker. inside of focus square marker i want to add object. is it possible to create a foucs square marker in ar-core android?

**Comment by inio** [comment]
This is a higher level capability than we intend to provide with the core AR engine.  Engine integrations our our sample code may provide this sort of thing in the future.

**Comment by inio** [comment]
Duplicate of #154

**Comment by ArigarasuthanRepo** [comment]
Ok thank you.

**Comment by jayesh8585** [comment]
Hello There,
We want the same kind of functionality but didn't get anywhere the proper solution and finally, we did it our custom focus square 
Please check below Link :

https://youtu.be/SbyB220KJqo

I hope you like it , It is done using ARcore

**Comment by ivstka95** [comment]
> Hello There,
> We want the same kind of functionality but didn't get anywhere the proper solution and finally, we did it our custom focus square
> Please check below Link :
> 
> https://youtu.be/SbyB220KJqo
> 
> I hope you like it , It is done using ARcore

looks very cool, good job!
can you share your solution please?
also i noticed that you customized rendering of shadow under the object - how did you do this?

**Comment by chnouman** [comment]
@jayesh8585 buddy you did a great thing can you share us some knowledge?

**Comment by jayesh8585** [comment]
Thank you Guys 
I'm going to upload the package on the asset store within a few days 
will inform you
