### ISSUE TITLE
Ray,Vector2f,Vector3f classes were not shown in ar-core developer preview2 in android

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#148]
I have using ar-core sample in developer preview2.i want to convert touch coordinates to world coordinates using Ray,Vector2f,Vector3f classes,but in developer preview2 those classes were not shown any alternative for these classes?

**Comment by hvmien** [comment]
what 's Ray?

**Comment by ArigarasuthanRepo** [comment]
Ray is a class in ar-core library.

**Comment by fredsa** [comment]
See issue #150
