### ISSUE TITLE
how can support common mobile can run this sdk?

### ISSUE THREAD

**Issue by yuxingfafu** [google-ar/arcore-android-sdk#15]
i dowload and run this sdk,it toast  This device does not support AR.
how can support common mobilephone can run this sdk? thank you very much

  mDefaultConfig = Config.createDefaultConfig();
     if (!mSession.isSupported(mDefaultConfig)) {
          Toast.makeText(this, "This device does not support AR", Toast.LENGTH_LONG).show();
          finish();
           return;
      }

**Comment by wbwz1992** [comment]
Is is supported on Google Pixel  and Samsung S8 only?

**Comment by nathanmartz** [comment]
During the SDK preview, ARCore is only supported on [specific devices](https://developers.google.com/ar/discover/#supported_devices).
