### ISSUE TITLE
How to convert motion event x and y coordinates to world coordinates in ar-core android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#150]
Iam using ar-core sample i want to convert x and y coordinates from touch to world coordinates.any examples there?

**Comment by fredsa** [comment]
See HelloAR which includes sample code for handling touches on the screen and determining world coordinates. See:

https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/HelloArActivity.java#L272

**Comment by inio** [comment]
@fredsa I think @ArigarasuthanRepo is asking more about generic touch-to-ray.

**Comment by inio** [comment]
Duplicate of #147

**Comment by jalaldev1980** [comment]
@ArigarasuthanRepo 
did you get any solution, please advice

**Comment by ivstka95** [comment]
@ArigarasuthanRepo 
`
    protected Anchor getScreenCenterPositionOnTheFloor() {
        Frame frame = getArSceneView().getArFrame();
        if (frame != null) {
            Collection<Plane> planes = frame.getUpdatedTrackables(Plane.class);
            for (Plane plane : planes)
                if (plane.getTrackingState() == TrackingState.TRACKING
                        && plane.getType() == Plane.Type.HORIZONTAL_UPWARD_FACING) {
                    List<HitResult> hitResults = frame.hitTest(centerX, centerY);
                    if (hitResults.size() > 0)
                        return hitResults.get(0).createAnchor();
                }
        }
        return null;
    }
    
    private static Vector3 convertToWorldPosition(Anchor anchor, NodeParent scene) {
        AnchorNode anchorNode = new AnchorNode(anchor);
        anchorNode.setParent(scene);
        return anchorNode.getWorldPosition();
    }`

centerX, centerY are the coordinates of touch event

**Comment by softlion** [comment]
See [here](https://github.com/ThomasGorisse/sceneform-android-sdk/blob/master/core/src/main/java/com/google/ar/sceneform/Camera.java)
