### ISSUE TITLE
ARCore samples with the new engine do not show how to scale / move a virtual object

### ISSUE THREAD

**Issue by jacquesgiraudel** [google-ar/arcore-android-sdk#1510]
ARCore samples with the new engine do not show how to scale / move a virtual object. The old sceneform samples permitted to see how to do that, can you add an example of how to do this ?
Also, can you add a sample with a tap listener on a virtual object drawn on the scene ?

Thanks

**Comment by devbridie** [comment]
ARCore doesn't provide functionality outside of the sample renderer; for rendering virtual objects it's best to become familiar with OpenGL, or alternatively to use a rendering engine that has a close integration with ARCore, e.g. [`sceneview-android`](https://github.com/SceneView/sceneview-android)
