### ISSUE TITLE
How to control an animation state using ui button in ar core?

### ISSUE THREAD

**Issue by sajidsrt** [google-ar/arcore-android-sdk#152]
I want to control an animation state through a ui button in ar core. I had tried these steps but no result

![catanim](https://user-images.githubusercontent.com/22423463/35627879-31d4bea4-0692-11e8-86bb-24fb1b3837f6.PNG)
![catanim2](https://user-images.githubusercontent.com/22423463/35627880-321aab9e-0692-11e8-85b0-4802fdede928.PNG)
![catanim3](https://user-images.githubusercontent.com/22423463/35627881-32588432-0692-11e8-830e-712009bf261e.PNG)
![catanim4](https://user-images.githubusercontent.com/22423463/35627882-32930d8c-0692-11e8-84e3-758cc68576be.PNG)
![catanim5](https://user-images.githubusercontent.com/22423463/35627883-32d2f4ce-0692-11e8-9c9b-b7585bf32ee9.PNG)

**Comment by inio** [comment]
First off, this appears Unity-related so, were it appropriate, it should be posted over on the [Unity issues board](https://github.com/google-ar/arcore-unity-sdk/issues).  However, there's really nothing ARCore-specific about this question, so maybe try the general StackOverflow unity board instead?
