### ISSUE TITLE
how to make model transparent

### ISSUE THREAD

**Issue by weijiaqi** [google-ar/arcore-android-sdk#1537]
https://download.redph.cn/meta/ar/q1.glb
https://download.redph.cn/meta/ar/q2.glb

I have two models, superimpose these two models, how to make the outermost mask transparent, only see the gap？

   ModelRenderable.builder()
                .setSource(this, Uri.parse("models/baike1.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(model -> {
                    MainActivity activity = weakActivity.get();
                    if (activity != null) {
                        activity.model3 = model;
                        activity.model3.setRenderPriority(Renderable.RENDER_PRIORITY_FIRST);
                        activity.model3.setShadowCaster(true);
                        activity.model3.setShadowReceiver(true);
                    }
                })
                .exceptionally(throwable -> {
                    Toast.makeText(
                            this, "Unable to load model", Toast.LENGTH_LONG).show();
                    return null;
                });

        ModelRenderable.builder()
                .setSource(this, Uri.parse("models/tiankongdimian1.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(model -> {
                    MainActivity activity = weakActivity.get();
                    if (activity != null) {
                        activity.model4 = model;
                        activity.model4.setRenderPriority(Renderable.RENDER_PRIORITY_LAST);
                    }
                })
                .exceptionally(throwable -> {
                    Toast.makeText(
                            this, "Unable to load model", Toast.LENGTH_LONG).show();
                    return null;
                });

I set the rendering priority, but it doesn't work, after running, I can still see the white mask。

  AnchorNode anchorNode = new AnchorNode();
        //设置锚点在世界坐标系的位置
        Vector3 point = new Vector3(0, -1, -2);
        anchorNode.setWorldPosition(point);
        anchorNode.setParent(arFragment.getArSceneView().getScene());

        TransformableNode andy = new TransformableNode(transformationSystem);
        andy.setParent(anchorNode);
        andy.setRenderable(this.model3);
        //  andy.setWorldScale(new Vector3(0.1f, 0.1f, 0.1f));
        // andy.setLocalPosition(new Vector3(0f, 2f, -7f));
        //  andy.setLocalRotation(Quaternion.axisAngle(new Vector3(0f, 1f, 0f), 180f));

        andy.getScaleController().setEnabled(false);
    
        andy.getRotationController().setEnabled(false);
        andy.select();

        Node roomNode = new Node();
        roomNode.setParent(andy);
        roomNode.setRenderable(this.model4);
        roomNode.setLocalScale(new Vector3(
                andy.getLocalScale().x - 0.01f,
                andy.getLocalScale().y - 0.01f,
                andy.getLocalScale().y - 0.01f
        ));

**Comment by weijiaqi** [comment]
![微信图片_20220812111822](https://user-images.githubusercontent.com/16206185/184867491-a897ca20-4f2b-4653-881f-0bb1b8261e9f.png)
The effect I want to achieve is ar portal, but I have been unable to make the white mask transparent

**Comment by devbridie** [comment]
Hi, this isn't the repository for `AnchorNode` and other Sceneform components; ARCore no longer handles rendering objects in a scene.
