### ISSUE TITLE
Difference between imageIntrinsics and textureIntrinsics?

### ISSUE THREAD

**Issue by sarimmehdi** [google-ar/arcore-android-sdk#1544]
Shouldn't they be the same? I looked at the documentation but it is quite vague:

```
/** Returns the unrotated camera intrinsics for the CPU image. */
public com.google.ar.core.CameraIntrinsics getImageIntrinsics() {
  // Method contents removed.
}

/** Returns the unrotated camera intrinsics for the GPU texture. */
public com.google.ar.core.CameraIntrinsics getTextureIntrinsics() {
  // Method contents removed.
}
```
What is the GPU texture here? My understanding is that the CPU image is what the SLAM is performed on and all the calculations for the pose of the camera and other surrounding virtual objects (anchors) are done based on the CPU image. What is the GPU texture then?

**Comment by devbridie** [comment]
> My understanding is that the CPU image is what the SLAM is performed on and all the calculations for the pose of the camera and other surrounding virtual objects (anchors) are done based on the CPU image. What is the GPU texture then?

Yup! The "CPU image" refers to the image controlled by [`Config.getImageSize()`](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig#getImageSize()), obtained by [`Frame.acquireCameraImage()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquireCameraImage-) and the "GPU image" refers to the image controlled by [`Config.getTextureSize()`](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig#getTextureSize-) that's available in the GL texture set by [`Session.setCameraTextureNames()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#setCameraTextureNames-textureIds).

**Comment by sarimmehdi** [comment]
Ok, I double-checked and both imageIntrinsics and textureIntrinsics provide the same values
