### ISSUE TITLE
i have stored and get fbx model from internal storage. object placed successfully    but   getAnimationData not working how to fix it 

### ISSUE THREAD

**Issue by DevaPandiyan** [google-ar/arcore-android-sdk#1550]
![errorcode](https://user-images.githubusercontent.com/25933803/200634031-58a069df-8990-41f8-a2e3-82b94ab9f5a6.PNG)
![code](https://user-images.githubusercontent.com/25933803/200634043-5b1b741a-66e8-4092-8680-e72b68f5db0e.PNG)
![internalstorage](https://user-images.githubusercontent.com/25933803/200634049-ed1b21ea-5980-4033-bd2b-3019f37a7745.PNG)
![sfafile](https://user-images.githubusercontent.com/25933803/200634458-59dadd21-87b9-471d-ace5-132fcffda625.PNG)

**Comment by devbridie** [comment]
Hi,
This looks like this question is for Sceneform, which is not on-topic for this repo. 
Looks like the renderer can't have multiple ModelAnimator.

**Comment by DevaPandiyan** [comment]
so how to fix it , there no running currently ModelAnimator here. i found it path problem 
  animations: [
    {
      clips: [
        {
          name: 'Default Take',
          runtime_name: 'animation_1',
        },
        {
          name: 'Fly_New',
          runtime_name: 'animation_2',
        },
        {
          name: 'Idel_New',
          runtime_name: 'animation_3',
        },
        {
          name: 'Run_New',
          runtime_name: 'animation_4',
        },
        {
          name: 'Walk_New',
          runtime_name: 'animation_5',
        },
      ],
      path: '/data/user/0/com.Shrewd.TilesAR/files/SampleData/Model/dragon_Model/Dragon_Baked_Actions_fbx_6.1_ASCII.fbx',
    },
