### ISSUE TITLE
Honor 8 pro

### ISSUE THREAD

**Issue by ragavendranbala** [google-ar/arcore-android-sdk#157]
ARCORE is not supported for my Honor 8 pro..  tell me a alternate way to support or.  Give an update soon

**Comment by JamiesonPryor** [comment]
Hi Raga:  I apologize but it's not supported yet, and I can't speak to when or if it will be.  For now, unfortunately early adopting will mean you have to use a supported device.

**Comment by fredsa** [comment]
See #89.
