### ISSUE TITLE
Cannot run emulator APK on M1 Mac arm emulator

### ISSUE THREAD

**Issue by Mehequanna** [google-ar/arcore-android-sdk#1571]
### SPECIFIC ISSUE ENCOUNTERED
After installing the emulator apk for AR Core on an M1 Mac, Google Play Services for AR keeps crashing. I'm unable to run AR on the emulator. I realize the apk was built for x86 architecture, so it shouldn't work any way. What I'm curious about is there any plan to create an ARM version of the emulator apk? Are there any work arounds for this?

### VERSIONS USED
- Android Studio: 2022.1.1 Patch 1 Electric Eel
- ARCore SDK for Android: 1.36.0 emulator apk
- Device manufacturer, model, and O/S: Arm Emulator, API 33
- Google Play Services for AR (ARCore):  1.36.230390493
- Output of `adb shell getprop ro.build.fingerprint`: google/sdk_gphone64_arm64/emu64a:13/TE1A.220922.021/9526604:userdebug/dev-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Download 1.36.0 Emulator APK from Releases page
 1. On M1 Mac, run emulator. Drag apk onto emulator to install.
 1. Try running an AR app.
 2. It looks mostly unresponsive with periodic messages about Google Play Services for AR crashing

**Comment by chiangandy** [comment]
I got sam issue, even I change emulator from API level 24,27,33. It still has issue. the error message "unable to unitize the Unity engine Gfx API". But I can run app in my android phone device.

**Comment by Mehequanna** [comment]
I'm not sure when this was fixed, but I tried again today with the latest ARCore [release 1.44.0](https://github.com/google-ar/arcore-android-sdk/releases/tag/1.44.0) and it worked 🎉 

Steps:
1. Download the latest apk (not the one listed for emulator) [Google_Play_Services_for_AR_1.44.0.apk](https://github.com/google-ar/arcore-android-sdk/releases/download/1.44.0/Google_Play_Services_for_AR_1.44.0.apk)
2. Create an emulator using the latest Pixel Pro for speed.
3. With only that emulator running and no device plugged in, go to terminal and run `adb install -r [path/to/]Google_Play_Services_for_AR_1.44.0.apk`
4. Open your AR app and test 🎉
