### ISSUE TITLE
ARCore Android: unable to find the child nodes for a parent object?

### ISSUE THREAD

**Issue by gptshubham595** [google-ar/arcore-android-sdk#1597]
I was working on ArCore in android; I was looking for these nodes with names inside my 3d model. 

I tried creating a function and search for a specific name but when I checked it in android studio the only name which i get is "Node" and nothing else.

    val childNode = getChildNodeByName(transformableNode, "TEXT_BOUNDING_BOX")

    private fun getChildNodeByName(
            parentNode: TransformableNode,
            targetName: String,
        ): TransformableNode? {
            for (childNode in parentNode.children) {
                Log.d("3DTag", "Child Node Name: ${childNode.name}")
                if (childNode.name == targetName) {
                    return childNode as TransformableNode
                }
            }
            return null
        }

I tried checking tranformableNode.scene.children but still the names inside that I found to be "Node" and nothing else which I can see in blender. How to get these child?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/qtp8V.png

### VERSIONS USED
- Android Studio: Flamingo 2022
- ARCore SDK for Android: 1.37.0
- Device manufacturer, model, and O/S: Android Oneplus Nord 2T
- Google Play Services for AR (ARCore):  Yes

**Comment by devbridie** [comment]
Hi, this doesn't seem to be an [ARCore SDK](https://developers.google.com/ar/reference/java/com/google/ar/core/package-summary) issue.
