### ISSUE TITLE
does samsung s8 in China is supported? how to make it support arcore?

### ISSUE THREAD

**Issue by johnnyz2017** [google-ar/arcore-android-sdk#16]
Hi all,

I used a Samsung S8 in China, model is SM-G9500(http://www.samsung.com/hk_en/business/business-products/mobile-device/smartphones/SM-G9500ZVDTGY), and updated system to the newest version.

First I install the arcore-preview.apk, and then build this example, then install and run, got the following error:
com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable.

then I found a project which can make it work:
https://github.com/tomthecarrot/arcore-for-all

after changed the library, yes it won't crash again, but still can not work normally, from the logcat I can see the following errors:
08-31 14:34:09.355 25737-25737/? E/Zygote: v2
08-31 14:34:09.356 25737-25737/? E/Zygote: accessInfo : 0
08-31 14:34:09.604 25737-25737/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
08-31 14:34:09.622 25737-25737/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
08-31 14:34:09.636 25737-25737/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
08-31 14:34:09.636 25737-25737/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
08-31 14:34:09.637 25737-25737/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
08-31 14:34:09.637 25737-25737/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
08-31 14:34:09.637 25737-25737/com.google.ar.core.examples.java.helloar E/tango_camera_native: 2 is not a valid camera index.
08-31 14:34:09.637 25737-25737/com.google.ar.core.examples.java.helloar E/tango_camera_native: 3 is not a valid camera index.

the full version of logs you can see from https://jpst.it/141kY

So I guess maybe 1)device 2)system has no ability to run arcore normally?
Can anyone tell me is it possible to use this phone to run this arcore demo? What need I do to make it work.

Thanks in advance!

**Comment by hanhailong** [comment]
I have the same problem as you

**Comment by juemuren4449** [comment]
Me too.

**Comment by Ernie1998** [comment]
I don't think G9500 is on the support list. We will have to wait.

**Comment by nathanmartz** [comment]
That is correct. We currently do not support this model of S8 in the SDK preview.

**Comment by johnnyz2017** [comment]
@nathanmartz  @Ernie1998  thanks, and do you know it is due to the device itself or it is due to the firmware/system?

I need this confirmation information, thanks for your help.

**Comment by Ernie1998** [comment]
@johnnyz2017 Non of the above, our hardware support it. It is not related to firmware. It is something about Certification...

**Comment by Ernie1998** [comment]
We may need to wait for the update of ar_client.aar. Or maybe it will update by the server automatically. This will need @nathanmartz for further info.

**Comment by johnnyz2017** [comment]
@Ernie1998 got it,  thank you very much!

**Comment by rightgenius** [comment]
Any news on this model's compatibility?

It is really awful to buy a s8 and try the demo only to find it is not supported.
Since pixel is not officially available in China, developers here can not get a supported device easily.

Plz consider supporting s8 SM-G9500.  @nathanmartz 
Thanks.
