### ISSUE TITLE
Usage of  mSession.setCameraTextureName()

### ISSUE THREAD

**Issue by namnov** [google-ar/arcore-android-sdk#161]
Is it possible to use `mSession.setCameraTextureName` in `onDrawFrame`? I am trying to maintain a ring buffer of previous frames and that's why I would like to change CameraTextureName to a different target after every `onDrawFrame`. However it seems that once CameraTextureName is set in `onSurfaceCreated`, later calls to `setCameraTextureName`  in `onDrawFrame` have no effect. Thank you!

**Comment by avirodov** [comment]
Hello. This functionality currently has a bug that sets texture only once, as you observed. The intent is indeed to allow calling setCameraTextureName as often as needed. The bug was observed here as well, and will be fixed as part of the next release.

**Comment by inio** [comment]
@namnov wrote:

> I am trying to maintain a ring buffer of previous frames 

FYI: This will not work.  You need to copy the texture.  ARCore's texture is built on the [SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture.html) API which allows only a single texture to be held.

**Comment by namnov** [comment]
@inio got it, thank you!

**Comment by inio** [comment]
This should be fixed with the 1.0 release today.  Update your ARCore and you should be able to change the textutre per-frame.

Note: This still doesn't allow holding multiple textures since we're limited by `SurfaceTexture`'s capabilities.
