### ISSUE TITLE
arcoreimg tool with url browser link

### ISSUE THREAD

**Issue by SabeeenoGH** [google-ar/arcore-android-sdk#1619]
Hi, I am trying to integrate arcoreimg evaluation into a detection project.
I want to understand if any of you have already addressed this issue.
I know for sure that arcoreimg for using eval-img needs the path, on disk, of the image.
However, what happens if I want to use an image that is on the web?
I tried to pass any image present on the web, ending with compatible extension (.jpg, .png), but it gives me a File not found error.

Does anyone know if this is possible or if they have already done something similar?
Thanks

**Comment by devbridie** [comment]
Hey, arcoreimg requires a file path and will not retrieve files from external sources.
