### ISSUE TITLE
Need API to detect whether devices supports ARCore

### ISSUE THREAD

**Issue by fredsa** [google-ar/arcore-android-sdk#162]
Apps that wish to run on both ARCore supported and ARCore unsupported device need a runtime API to be able to determine whether the current device supports ARCore.

**Comment by inio** [comment]
The 1.0 release today introduces a [new API for detecting device compatability](https://devsite.googleplex.com/ar/develop/java/enable-arcore#check_supported) ([reference docs](https://devsite.googleplex.com/ar/reference/java/com/google/ar/core/ArCoreApk)).

**Comment by eAi** [comment]
@inio Those links don't work outside Google, you presumably intended to link to https://developers.google.com/ar/develop/java/enable-arcore and https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk

**Comment by inio** [comment]
@eAi  Thanks!  Fixed it.

**Comment by inio** [comment]
At the moment the `checkAvailability` test works by asking the Google Play Store if the device can download ARCore.  This obviously won't work in cases where the device cannot access the Google Play Store, such as networks with aggressive egress firewalls.  In these cases, the only way for a device to be deemed "supported" is if *some* version of ARCore is present on the device.

In the case of devices in China, we're working on improving this situation.

**Comment by petermauger** [comment]
Any update on the China 'situation'?

**Comment by tandemInnovation** [comment]
I've tested this feature and gives me a false positive in Nvidia shield device. I will release this to production but I'm afraid of this false positives cases.
