### ISSUE TITLE
No Arcoreimg folder in 1.40 release

### ISSUE THREAD

**Issue by mrajkovicpta** [google-ar/arcore-android-sdk#1621]
### SPECIFIC ISSUE ENCOUNTERED
Arcoreimg part of sdk is missing in the sdk release zip for 1.40

### VERSIONS USED
ARCoreSDK 1.40.0

### STEPS TO REPRODUCE THE ISSUE
 1. Download sdk for 1.40.0
 2. Open ./tools
 3. See there is no arcoreimg folder

### WORKAROUNDS (IF ANY)
Download the sdk for 1.39.0

**Comment by devbridie** [comment]
Binaries are back in the releases since 1.41!
https://github.com/google-ar/arcore-android-sdk/releases/tag/1.41.0
