### ISSUE TITLE
The latest Samsung Galaxy A15 phone cannot install ARCore

### ISSUE THREAD

**Issue by americanidler** [google-ar/arcore-android-sdk#1642]
### SPECIFIC ISSUE ENCOUNTERED
Samsung Galaxy A15 phone **cannot** install Google's **ARore** or **Play service for AR,** though it is the latest and older phones like Galaxy A14 and A13 both **can** install. 

I looked up and found Galaxy A15 isn't in supported device list. The phone was released on December 13, 2023 and is powerful enough to support AR, I am sure.

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android:  1.41
- Device manufacturer, model, and O/S:  Samsung Galaxy A15 phone. O/S: Android 14
- Google Play Services for AR (ARCore):  Latest from Google Play store
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 
`samsung/a15ub/a15:14/UP1A.231005.007/A155MUBS1AXA1:user/release-keys`

### STEPS TO REPRODUCE THE ISSUE
 1. Get a Samsung Galaxy A15
 2. Try to install Google Play service for AR or ARcore
 3. Verify that it cannot be installed because "device is not supported"

**Comment by mrichards** [comment]
@americanidler The A15 is supported, and Google Play Services for AR was installed by default on our local A15 test device -- though not visible in the Play Store.

Please check in the phone's app list to see if Google Play Services for AR is already installed as a system app. Got to `Settings` > `Apps` and then click the filter button to display system apps, as only user apps will be displayed by default. Is it there?

Also please provide the output of `adb shell getprop ro.build.fingerprint`.

**Comment by americanidler** [comment]
Thanks for the comment! I did a bit research and I learned that Galaxy A15 was released on Dec. 11th, 2023, which is later than the latest release of this repo. It is also not listed in here https://developers.google.com/ar/devices#google_play

### Here are my screen shots
Google play services for AR is not listed as installed in my Apps.
![Screenshot_20240314_234755_Settings](https://github.com/google-ar/arcore-android-sdk/assets/162663548/6278c2d7-af7d-4066-9006-e11d09de1c5b)

Live View in Google map is greyed out
![Screenshot_20240314_234732_Maps](https://github.com/google-ar/arcore-android-sdk/assets/162663548/729c502a-3314-444d-ac35-12a6eadc5965)

When I land myself to google play service for AR in the play store, it appears "uninstall-able"
![Screenshot_20240314_104755_Google Play Store](https://github.com/google-ar/arcore-android-sdk/assets/162663548/802ef7b7-27fb-4454-843a-9fb8b754878e)

**Comment by americanidler** [comment]
And here is my phone's fingerprint. `samsung/a15ub/a15:14/UP1A.231005.007/A155MUBS1AXA1:user/release-keys`. 

Much thx for helping out.

**Comment by sandyfriend** [comment]
Google side support A15 5G devices, not A15 4G. A15 4G is not supported.

**Comment by americanidler** [comment]
> Google side support A15 5G devices, not A15 4G. A15 4G is not supported.

OMG, no way. That is why? OK

**Comment by 15kingben** [comment]
Closing this as resolved per the info from Chen

**Comment by ajmv78** [comment]
I swear these Google developers lose perspective on what this tech is all about. Of course, if you live in SF and have an iPhone 1241241 (or a Pixel 134124 or whatever) you could care less if your "policies" block useful functionality to the rest of the world, but my god. Are we really going to sit here and pretend than a 2023 phone cannot run basic AR? What's this about?

**Comment by Hsoofi82** [comment]
My Phone is a Samsung A15 4G , im Game Developer and i Want Create AR Game But My Phone Dont Suported Please Help Me
