### ISSUE TITLE
Discrepancy between the list of devices that support ARCore from the Google Play Console and the ARCore documentation website

### ISSUE THREAD

**Issue by zachary-dpt** [google-ar/arcore-android-sdk#1644]
### SPECIFIC ISSUE ENCOUNTERED
When I upload a bundle to the Google Play Console with ARCore being set up as "required", the list of supported devices is made only of 118 devices. When I inspect further, devices that should support ARCore are specified as being not supported (for example: the entire Google line of phones is marked as unsupported except the Google Pixel 2 and 2XL, even though the list from the ARCore documentation mentions that pretty much all of the Google phones support ARCore). 

The reason why it's unsupported is always:
> Doesn't support required feature: android.hardware.camera.ar

Example: Google Pixel 6a from Google Play Console
![image](https://github.com/google-ar/arcore-android-sdk/assets/71455257/0f83ea3f-784f-4700-9361-4b409d15118b)

Google Pixel 6A being part of the supported list from here: [https://developers.google.com/ar/devices](https://developers.google.com/ar/devices)
![image](https://github.com/google-ar/arcore-android-sdk/assets/71455257/7ebeaf0d-f86a-4d21-9812-85f97abbbff2)

### VERSIONS USED
- Android Studio: Not applicable
- ARCore SDK for Android: Not applicable
- Device manufacturer, model, and O/S: Not applicable
- Google Play Services for AR (ARCore):  Not applicable 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: Not applicable

### STEPS TO REPRODUCE THE ISSUE
 1. Follow steps to include ARCore in the app manifest from here: [https://developers.google.com/ar/develop/java/enable-arcore](https://developers.google.com/ar/develop/java/enable-arcore)
 1. Upload app bundle to Google Play Console
 1. The supported Device Catalog is short(118 devices) and excludes devices that should be supported.

### WORKAROUNDS (IF ANY)
Should I mark the app as not being AR Required? The core functionnality of the app is based on AR and I don't think it's a viable solution.

### ADDITIONAL COMMENTS
Is 118 devices a normal amount of devices that should support ARCore? Should I have more devices in the Device Catalog of my app? Should I not worry about this and the users of unsupported devices (based on this list) will still have access to my app on the Google Play Store?

Thank you

**Comment by zacharylr** [comment]
My problem seems to be similar to this issue that was logged a little over 2 years ago
#1317

**Comment by devbridie** [comment]
Confirming that the list, indeed, has regressed again. Checking in with the Play folks to see what's up.

I would suspect that this doesn't affect the actual availability in the Store, but looking into this immediately.

**Comment by zacharylr** [comment]
Hello @devbridie 
Was there any news regarding this?
Thank you!

**Comment by l9sheen** [comment]
Currently I have 126 devices available when filtering with android.hardware.camera.ar on device catalog > all devices. With com.google.ar.core.depth I only get 1 device. As mentioned on #1317 this is affecting users on their phones for instance, I have a had a user with a Samsung A34 unable to download my app because they get a "your device isn't compatible with this version", this phone is listed on the supported devices documentation.

How is this a problem that has occurred again after 2 years?
Was there any notice to this change?

It's extremely hard to run a production app when things like this happen and limit the ability for users to download my app. Very frustrating

**Comment by MohamedPresident** [comment]
Same here just 127 devices and the reason for the unsupported devices is:

> Doesn't support required feature: android.hardware.camera.ar

**Comment by l9sheen** [comment]
Hi @devbridie 

It is coming up to a month since we have had an update on this. Is this something you are looking into? It is affecting the availability of my app in the Play Store.

Regards

**Comment by devbridie** [comment]
The Play Console team is still actively looking into this. However, we're all convinced that this only affects the display of the list on the Play Console Device Catalog page, and does not affect availability. My test devices are not shown on the list and are able to see [Depth Lab](https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab&hl=en&gl=US) in the Play Store.

If you believe this is affecting availability on the device, please ensure that your device cannot see [Depth Lab](https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab&hl=en&gl=US) and post the `adb shell getprop ro.build.fingerprint`.

**Comment by l9sheen** [comment]
Okay thanks, I think I had the depth api on required will change that and let you know if there are any further problems

**Comment by honzasvarc** [comment]
Same here, 124 devices, unsupported: android.hardware.camera.ar :/

**Comment by 286ljb** [comment]
We have also encountered the same problem. Please fix it asap. Thanks.

**Comment by Roborino** [comment]
URGENT assistance required!  Our app now shows 0 supported device!  Previously our app showed 1000s of devices, now 0.  Nobody can download our app any more.

**Comment by agGitHub** [comment]
Any news ? Only 125 devices written as supported in GPlay Console whereas around 900 compatible devices are written in ARCore compatibility list... https://developers.google.com/ar/devices Any impact on downloads ? Please Google team, give feedback on this issue.

**Comment by nudge411** [comment]
Any news? Due to the fact that I also do not support android.hardware.camera.ar, the number of devices supported was reduced from 6,896 to 127. Distribution cannot proceed simply because of a typographical error. Please share the latest news! thank you

**Comment by agGitHub** [comment]
@nudge411 What do you mean by 'Distribution cannot proceed simply because of a typographical error.' ? What typographical error ?

**Comment by nudge411** [comment]
@agGitHub It seems to be a translation problem.
Above, devbridie mentioned, "There is no problem with functionality, it is simply a problem with displaying the list of devices in the catalog." But I want more concrete information. We need clear information that there is no real impact on users. Because of this, application deployment is being postponed.

**Comment by makakaorg** [comment]
My App that can be downloaded with a direct link to Google Play via "unsupported device" Galaxy A71, can NOT be found using Google Play search. This is a big problem.

My app works on Galaxy A71.

**Comment by alamboley** [comment]
Any news on this @devbridie ? I'm running into this issue also. I confirm it **does** affect the actual availability in the store.

**Comment by ta-david-yu** [comment]
We are also having this issue at the moment, the best I can do now for our project is to make ar core requirement as optional
so at least devices that are actually supported with ARCore can download the app. (127 devices -> 7,489 devices)

I haven't looked into the details but I am considering checking the feature availability at runtime and show warnings to the users that the main features are not supported.
 
Please fix this asap!

**Comment by DTsoukalos** [comment]
I have the same problem with all of my AR apps.
Some of my apps are for clients with a very big budget (with over 500k downloads), and we have chosen AR Core because we thought it was stable for creating AR apps.
Really, this bug, as well as the time to solve it (still open), shows that AR core is probably something that Google is abandoning! I would call it unprofessional from such a big company.

**Comment by lferrer** [comment]
Thanks folks for reporting the issue. We are currently engaging with the Play Store team to address the situation.

We are under the impression that the issue is only affecting the list of devices shown on the Play Console and not app distribution itself (given our experiments with [Depth Lab](https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab&hl=en&gl=US)). However it seems like there are apps like [AR Masker](https://play.google.com/store/apps/details?id=org.makaka.armasker) are a counter-example as I can see it not being compatible with our test devices.

If your application is affected, would you mind sharing:
- Your application's package name (or a link to your Play Store entry)
- Whether your application is AR Required or AR Optional

While we are working with the Play Store to get a fix deployed soon, the more data points that we can gather the easier it will be to expedite the process.

Thanks again for your patience and your support!

**Comment by makakaorg** [comment]
> Thanks folks for reporting the issue. We are currently engaging with the Play Store team to address the situation.
> 
> We are under the impression that the issue is only affecting the list of devices shown on the Play Console and not app distribution itself (given our experiments with [Depth Lab](https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab&hl=en&gl=US)). However it seems like there are apps like [AR Masker](https://play.google.com/store/apps/details?id=org.makaka.armasker) are a counter-example as I can see it not being compatible with our test devices.
> 
> If your application is affected, would you mind sharing:
> 
> * Your application's package name (or a link to your Play Store entry)
> * Whether your application is AR Required or AR Optional
> 
> While we are working with the Play Store to get a fix deployed soon, the more data points that we can gather the easier it will be to expedite the process.
> 
> Thanks again for your patience and your support!

[Full report](https://discussions.unity.com/t/arcore-this-release-will-cause-a-significant-drop-in-the-number-of-devices-your-apps-supports/949694) about the AR Masker.

**Comment by DTsoukalos** [comment]
> Thanks folks for reporting the issue. We are currently engaging with the Play Store team to address the situation.
> 
> We are under the impression that the issue is only affecting the list of devices shown on the Play Console and not app distribution itself (given our experiments with [Depth Lab](https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab&hl=en&gl=US)). 

I confirm that the same happens with the AR apps I manage.
For example, the applications with bundle id
com.mathcoder.ARSpaceblocks
com.virtual.street
com.hmcs.aitoloakarnaniafortifications
they have the same problem. All these currently show me 110-130 supported Android devices. The device I am testing them on (Redmi Note 8 Pro) is not on the list of these devices, but if I search the Play Store, I can find those apps and install them.

I should also mention that the number of supported Android devices has changed in the App bundle Explorer - the old bundle ID versions.

For example for com.hmcs.aitoloakarnaniafortifications, if I go to "App bundle explorer" I see that the bundle id version: 1 currently has Supported Android devices 124 and I am sure that earlier this number was much higher.

**Comment by lferrer** [comment]
Thanks for the additional information folks!

I'm happy to share that the Play team has addressed this issue and that you should see the correct information populated in your app's Device Catalog in the Play Console. 

Please let us know if you are still facing issues.

**Comment by alamboley** [comment]
My app grew up to 1,586 supported device models 🚀

**Comment by mobile-appz** [comment]
> Confirming that the list, indeed, has regressed again. Checking in with the Play folks to see what's up.
> 
> I would suspect that this doesn't affect the actual availability in the Store, but looking into this immediately.

Hi any news on Samsung Galaxy S7 support please? I was previously able to install Google Play For AR from Play Store, but having updated the device to Android 14, I can't any more.

**Comment by Thaina** [comment]
My phone is NokiaX10 totally support both AR and AR Depth with the hardware, I can even build AR system app in it and install directly. But then I can't install it from google play
