### ISSUE TITLE
Is it possible to install arcore on project without relying on the app "google play services for ar"

### ISSUE THREAD

**Issue by stewForAni** [google-ar/arcore-android-sdk#1646]
why not use SDK ,and implementation it in android project?
why need to install the app "google play services for ar"?
In China, it's not a goog way to develop arcore app while user need to install 2 apps?
so, is there any idea to solve this problem ?
thank you!

**Comment by 15kingben** [comment]
ARCore is split between the SDK and a shared APK to reduce binary size for app downloads. On some devices this is included in the system image, however on other devices the apk must be downloaded from the app store.

**Comment by tsoen** [comment]
> ARCore is split between the SDK and a shared APK to reduce binary size for app downloads. On some devices this is included in the system image, however on other devices the apk must be downloaded from the app store.

Hello @15kingben, 
Do you have any idea on how we could install the "Google Play Services for AR" on devices that can only access a restricted network, i.e. if we cannot access the App Store at all ?
Is is possible to side-load it ?
Regards,

**Comment by devbridie** [comment]
There's currently no alternative to obtaining the Google Play Services for AR binary files than through the Play Store or through other application stores in China. Sideloading the binary from other channels may yield undesirable results as devices may need to connect to the internet once to download device calibration data.
