### ISSUE TITLE
ARCore Stops working for Samsung Note 8  (SM-N950W)

### ISSUE THREAD

**Issue by kgmitch** [google-ar/arcore-android-sdk#165]
Hi everyone,

I am testing ARCore for the first time. I am using Unity and have setup all the necessary stuff.

![image](https://user-images.githubusercontent.com/36268728/35976765-207be006-0caf-11e8-9cd4-46cd18ae9ce8.png)

I am using the following SDK (but I did try all the higher versions also)
![image](https://user-images.githubusercontent.com/36268728/35976953-b16af7be-0caf-11e8-935b-39e240b8babe.png)

Get a popup on phone stating ARCore "stopped working";  this is what I see if i view the log:

![image](https://user-images.githubusercontent.com/36268728/35976612-ac98b93e-0cae-11e8-95cc-c4b9452a247f.png)

I reviewed the list of devices supported, which I have hlited mine:
![image](https://user-images.githubusercontent.com/36268728/35976686-e80c035e-0cae-11e8-9cfa-ea93c12384cf.png)

Any ideas? Is Note 8 actually supported yet?

Thanks in advance!

**Comment by JamiesonPryor** [comment]
Hi Kgmitch:  Unfortunately I think you've caught a real issue.  We have this issue resolved in the upcoming release.  Sorry.

**Comment by drinikol** [comment]
Same issue with the crash, I am using a SM-N950F/DS is it the same as the SM-N950F?

**Comment by mcmaillet** [comment]
Hi I can't seem to find your release schedule, when do you think this will be patched?

**Comment by inio** [comment]
This should be fixed with 1.0 released today.  If you can download ARCore from the Play Store (and the N950F should be able to) it should work.

**Comment by stanchostanchev** [comment]
ARCore ver 1.0 does not work on Note 8 (SM-N950F)

**Comment by inio** [comment]
@kkirov00 the "0" and "8" variants of Samsung devices are not supported at this time.

**Comment by kkirov00** [comment]
Thanks @inio! What are the plans? When will my device be supported?

**Comment by inio** [comment]
@kkirov00 We hope to add support for developers with some Samsung Hong Kong devices in a future, but cannot provide an estimate of when that will be.
