### ISSUE TITLE
Samsung Galaxy A14 5G not supported

### ISSUE THREAD

**Issue by BigGiantHead** [google-ar/arcore-android-sdk#1652]
### SPECIFIC ISSUE ENCOUNTERED
Hello,

We've encountered an issue where on Google Play Store it says that Samsung Galaxy A14 5G is not supported:

![image](https://github.com/google-ar/arcore-android-sdk/assets/7494617/182c208e-fedc-4378-a785-8b9a93c5d494)

but when I check in the supported devices list it clearly says that it should be supported:

![image](https://github.com/google-ar/arcore-android-sdk/assets/7494617/82e70973-bfc8-49a4-8bca-763c61c66825)

Maybe the list has not be update?

Thank you in advance for your help.

**Comment by 15kingben** [comment]
See https://github.com/google-ar/arcore-android-sdk/issues/1644 (note: this is a bug in the play services console, but does not affect the ability of users to install the app with that device)
