### ISSUE TITLE
Arcore cannot be included in dynamic feature module with shrinkResources enabled

### ISSUE THREAD

**Issue by sangrao** [google-ar/arcore-android-sdk#1657]
### When arcore dependency is included in featuremodule with base app that uses `shrinkResource` build feature, build fails with the following error message when attempting to make the App bundle/apk.

Resource table of module <dynamic-feature-module> contains references to non-existing files: [res/raw/keep_arcore.xml]

### VERSIONS USED
- Android Studio: Jellyfish
- ARCore SDK for Android: com.google.ar:core:1.43.0
- Device manufacturer, model, and O/S: NA
- Google Play Services for AR (ARCore):  NA
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. run makeApkFromBundleForDebug from the attached demo project
[shrinkResourceExample.zip](https://github.com/user-attachments/files/15566172/shrinkResourceExample.zip)

**Comment by devbridie** [comment]
Here's a workaround for you:

Add `module/src/res/raw/keep.xml` with the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="
       @raw/keep_arcore,
       @raw/keep"
    />
```

I can't see the resources in the output artifacts so this should be minified.

**Comment by sangrao** [comment]
Thanks, the suggestion in https://github.com/google-ar/arcore-android-sdk/issues/1657#issuecomment-2152894739  worked.
