### ISSUE TITLE
ARCore app not available at Google Play for Galaxy S7 SM-G930F

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#166]
Hi,
I'm trying to run my app that uses the ARCore sdk on a Galaxy S7, SM-G930F, Android 7.0
I receive the `UnavailableArcoreNotInstalledException`, although the device is listed under the "Supported Devices".
I'm unable to download the [ARCore app](https://play.google.com/store/apps/details?id=com.google.ar.core) from the Google Play as the indication is that the device isn't suitable.

Thanks

**Comment by Xanvial** [comment]
You should side load the arcore apk from here https://github.com/google-ar/arcore-android-sdk/releases/tag/sdk-preview2

**Comment by itanbp** [comment]
@Xanvial thanks!

**Comment by inio** [comment]
ARCore is currently only available on the Play store for Pixel devices running Android O MR1.  With the 1.0 release we'll be making it available for all supported devices.

For now, this means you need to side-load both the ARCore APK and your application.
