### ISSUE TITLE
Earth state is INTERNAL when starting the app without an active internet connection

### ISSUE THREAD

**Issue by Tom3652** [google-ar/arcore-android-sdk#1671]
### SPECIFIC ISSUE ENCOUNTERED

Build the [sample](https://developers.google.com/ar/develop/java/quickstart#open-sample) app and turn off your wifi / internet connection.
See that `Earth.EarthState` is `ERROR_INTERNAL`. 

### VERSIONS USED
- Android Studio: 2024.1.2
- ARCore SDK for Android: 1.45.0
- Device manufacturer, model, and O/S: Motorola 
- Google Play Services for AR (ARCore):  versionName=1.45.242050483
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: motorola/sofiar_reteu/sofiar:11/RPES31.Q4U-47-35-12/24aaf7:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Turn off all internet connectivity on your phone
 2. Log the earth state 
 3. Run the sample quickstart
 4. See the earth state is in `ERROR_INTERNAL`

### WORKAROUNDS (IF ANY)
No workarounds unfortunately

### ADDITIONAL COMMENTS

Note : turning on wifi when the app is already running doesn't make it work, you have to kill the app and restart it with internet connection to get a "normal" earth state.

**Comment by Tom3652** [comment]
I just think about it now, but is it possible that the ARCore sdk is checking for the API availability before starting the session ? 
And thus encounter an error because there is no internet connection ?

**Comment by 15kingben** [comment]
Geospatial requires an internet connection, so you will get EarthState Error Internal starting the app without an internet connection. I think at that point the only way to fix the issue would be to call [Session.configure](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#configure(com.google.ar.core.Config)) and disable/reenable the geospatial api once internet has been restored (or wait for internet access before configuring the arcore session initially).
