### ISSUE TITLE
is there a way to get the pixel buffer from ARCore camera ?  

### ISSUE THREAD

**Issue by deeppandya-traderev** [google-ar/arcore-android-sdk#169]
I am currently working with ARCore to classify images and put objects on the images. But it seems like ARCore camera doesn't provide any way to get the pixelbuffer. then i came across How to take picture with camera using ARCore and according this we can copy the frame from OpenGL using GLES20.glReadPixels. But sadly GLES20.glReadPixels works only from main thread.

**Comment by itanbp** [comment]
Hi,
you can look at google's [computer vision](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision) sample:
> The provided Computer Vision sample is useful for running custom computer vision algorithms or image analysis on the camera image data.

**Comment by inio** [comment]
Thanks @itanbp .

**Comment by inio** [comment]
Duplicate of #30
