### ISSUE TITLE
Is it  support Nexus 5??

### ISSUE THREAD

**Issue by kevintank** [google-ar/arcore-android-sdk#17]
"This device does not support AR"

**Comment by Aiuspaktyn** [comment]
No

**Comment by hanhailong** [comment]
No, wait for the release version

**Comment by jason0539** [comment]
Try [this](https://github.com/jason0539/arcore-android-sdk/),it is support Nexus 6.

**Comment by nathanmartz** [comment]
This behavior is expected as the ARCore SDK preview does not support the Nexus 5.
