### ISSUE TITLE
Demo app hello_ar_java : improper use of the term 'Renderer'

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#170]
In the demo app, the term 'Renderer' is used to name the classes 'BackgroundRenderer', 'ObjectRenderer', 'PlaneRenderer', etc...

I think that this naming is confusing because these classes do not extend GLSurfaceView.Renderer. Especially for OpenGL beginners.

You should call these classes 'Drawer' or whatever but not Renderer. 

It would help to understand the whole code.

**Comment by inio** [comment]
Thank you for the suggestion.
