### ISSUE TITLE
"Signature check failed for com.google.ar.core"

### ISSUE THREAD

**Issue by bhin293** [google-ar/arcore-android-sdk#172]
I'm trying to get the arcore demo working with unreal (using arcore-preview2). When I start the app, I'm getting an 'arcore has stopped' message with a prompt to close the app. The app does seem to keep running, displaying and updating a visible grid as I move the phone around. If I respond to the message or touch outside of the message on the screen, the app closes. I get the same result using unity. It also displays the stopped message using an Android studio version of the app using preview2. However, with android studio, when I touch around the stopped message, the message goes away and the app will produce visible Andys. The original ARCore SDK Developer Preview works perfectly. I seem to be having an issue with the preview2 version. I have a samsung galaxy s8 phone. I havent' made any changes to the demo code. I'm just downloading and trying it. The computervision demo has the same problem. I've attached the logcat error that appears when I start the app.  

02-18 08:30:51.287: E/AndroidRuntime(9547): FATAL EXCEPTION: main
02-18 08:30:51.287: E/AndroidRuntime(9547): Process: com.google.ar.core, PID: 9547
02-18 08:30:51.287: E/AndroidRuntime(9547): java.lang.SecurityException: Signature check failed for com.google.ar.core
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at android.os.Parcel.readException(Parcel.java:1693)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at android.os.Parcel.readException(Parcel.java:1646)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at vu.a(Unknown Source)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at uo.a(Unknown Source)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at abf.a(Unknown Source)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at abj.run(Unknown Source)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at xn.run(Unknown Source)
02-18 08:30:51.287: E/AndroidRuntime(9547): 	at java.lang.Thread.run(Thread.java:762)

**Comment by inio** [comment]
That's quite odd.  Asking a few people.

**Comment by bhin293** [comment]
I added some logging before and after each statement in the source (yea, took a little time) and the problem seems to happen in the   __mSession = new Session(this);__   statement in onCreate about 47 or so lines in. Here is the fragment of  code:
...
  Exception exception = null;
        String message = null;
        Log.i(TAG, "11");
        try {
            mSession = new Session(this);
            Log.i(TAG, "12");
         } catch (UnavailableArcoreNotInstalledException e) {
...

The error I posted earlier displays between the "11" and "12" log messages.

**Comment by inio** [comment]
Is it possible your device hasn't been able to update it's Google Play Services or GMSCore in a while?  Make sure your Play Store and any Google services are up to date.  Failing that, try leaving the device connected to wifi for 24 hours and see if it starts working after that.

**Comment by bhin293** [comment]
OK. I have a software upate command (?) in settings that I've touched several times. It says "current software is up to date". I don't have any google accounts. I'll let you know what happens tomorrow.

**Comment by inio** [comment]
That's android OS update.  You also can try opening Google Play Store and going to Hamburger Menu -> Settings, scrolling down, and tapping "Play Store version" to start an self-update.

**Comment by bhin293** [comment]
The only option under the hamburger menu when I start the google play store app is 'Find my account'. 

When I go to settings, apps, google play store, the hamburger menu has 'Uninstall Updates' as the only option.

Here is the Version text that displays there beneath the google play store app name:

Version 8.9.24-all[0][PR]
184891514

**Comment by bhin293** [comment]
I've left the phone on for a couple days now. Still getting the same 'arcore has stopped' message.

**Comment by bhin293** [comment]
I've disabled google play store on the phone and restarted. The app behaves in the same way - signature check failure.

**Comment by inio** [comment]
You've *disabled* google play store?  I wasn't aware such a thing was even possible on supported devices.

This error indicates that your Google Play Services is substantially out of date.  What model of phone (or device signature) do you have and what carrier, if any?

**Comment by bhin293** [comment]
The phone is a samsung galaxy s8 model SM-G950U. Android version is 7.0. I do not have a carrier for it (bought the phone to experiment with ar), but it looks like an ATT phone from some of the other items on it.
Going to Settings, Apps, Google Play Store reveals two buttons at the top:  Disable and Force Stop. I posted the play store version in a preview comment.

**Comment by bhin293** [comment]
I noticed the 1.0 release has arrived. I did a factory reset on the phone, set up a google play store account (the google play store version on my phone is still the same as I posted above), installed arcore 1.0 from the store and tried the java demo using the new quick start instructions for android. It works without any errors now.  Thanks to all of you who took time out to take a look at this with me. Just some observations:  the old (now replaced) quickstart guides never mentioned needing google play store anywhere. Neither does the new android quick start guide. If it had been one of the steps, I would have addressed it then and probably would not have bothered you at all. In addition, following the new quick start guide and installing the app on the phone works. But running it displayes  the "please install arcore" message. The guide never mentions you have to do that manually (do you?). Someone (like me) might think they did something wrong. Thanks again. I'm happy so I'm going to close the issue if that's OK with you.

**Comment by inio** [comment]
The Google Play **Store** is not needed, but the presence of an old version of Google Play **Services** (com.google.gms) can cause problems by (if I understand correctly) pinning old certificates for com.google.* packages.

The guides should probably mention the install process on the first launch.  I'll bring that up.
