### ISSUE TITLE
arcore ndk AR_ERROR_CAMERA_PERMISSION_NOT_GRANTED

### ISSUE THREAD

**Issue by kdk96** [google-ar/arcore-android-sdk#173]
Why ArSession_resume returns AR_ERROR_FATAL instead AR_ERROR_CAMERA_PERMISSION_NOT_GRANTED if permission not granted?

**Comment by inio** [comment]
The permissions flow is changing slightly in the next release and should resolve this.

**Comment by inio** [comment]
with 1.0, you now need camera permission for session creation (and the correct error should be generated if you don't have it).
