### ISSUE TITLE
How to provide a rotation like we provide translation to the object?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#174]
I have working ar-core sample project.i was placed object using motion event and providing translation  where we want to tab the screen.but i have an issue in this objects not correctly placing because while creating anchor i have only provided translation and i have not provided rotation.How can i provide the translation and rotation for anchor object? please help me to solve this issue.

**Comment by inio** [comment]
Pose has a `makeRotation(x,y,z,w)` factory method just like makeTranslation.  To first rotate and then translate an object you would want to compose them in the other order: `translation.compose(rotation)`

**Comment by ArigarasuthanRepo** [comment]
Thank you for the help.how to find the(x,y,z,w) values for make rotation?i have x,y,z values for the translation.

**Comment by ArigarasuthanRepo** [comment]
I did with
**First i make a rotation**
``
float sqrtHalf = (float) Math.sqrt(0.5f);
Pose rotation=Pose.makeRotation(0,0,sqrtHalf ,sqrtHalf );``
**Then translate object:**
``Pose air = Pose.makeTranslation(vector3f.getX(), vector3f.getY(), vector3f.getZ())``
**And Compose**
``air.compose(rotation)``

**Create anchor using:**
``mAnchors.add(mSession.createAnchor(air))``

Is it correct?

**Comment by RegisAG** [comment]
Do you have the working for this ? 

I tried this:

```
float lineAngle = PI_value / 2;
float[] poseRotationArray = { 0.0f, lineAngle, 0.0f, 1.0f};
myAnchor.getPose().makeRotation(rulerPoseRotationArray);
myAnchor.getPose().toMatrix(mAnchorMatrix, 0);
myVirtualObject.updateModelMatrix(mAnchorMatrix, scaleFactor);
myVirtualObject.draw(viewmtx, projmtx, lightIntensity);
```

But does not seem to work. I think that it comes from the fact that myAnchor is not modified by makeRotation, as makeRotation returns a Pose but I don't see how to modify the pose of myAnchor.

Thanks for your help.

**Comment by inio** [comment]
@ArigarasuthanRepo To your first question: (x,y,z,w) are a quaternion describing the desired rotation.  See the [wikipedia article](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation) for details but the TL;DR is that if you want a rotation by &theta; about y, then set `y = sin(θ / 2)`, `w = cos(θ / 2)`, and x = z = 0.

To your second question: No, that will put it into a fixed location in space relative to the origin (the location of which is intentionally unspecified).  If you want to create an anchor in a meanful location, you should work off either the camera location or a hit result location.

@RegisAG That's not a valid quaternion.  See above.

**Comment by RegisAG** [comment]
Thanks for your answer about the quaternion.

Now, the question remains the same: how to rotate an object (for example the droid bot in the sample app) around its Y axis ? Thanks.

**Comment by inio** [comment]
@RegisAG see my last comment for how to create a rotation about the Y axis.

To create an anchor with a rotated position realtive to a `HitResult` you could do something like:

    hitResult.getTrackable().createAnchor(hitResult.getPose().compose(rotation))

**Comment by ArigarasuthanRepo** [comment]
@inio I was provide rotation like:

`Pose airRotation=Pose.makeRotation(0f,camera.getPose().qy(),-0.0f,camera.getPose().qw());
`
And making translation:
  `final Pose air = Pose.makeTranslation(vector3f.getX(), vector3f.getY(), vector3f.getZ());
`
And compose rotation like:
`final Pose newPose=air.compose(airRotation);`

Create Anchor Using:

`mAnchors.add(mSession.createAnchor(newair));`

It 's worked for me.is it correct?

**Comment by vbaicu** [comment]
In updateModelMatrix do this:
```java 
Matrix.translateM(mModelMatrix, 0, translationX, 0f, translationZ);
Matrix.rotateM(mModelMatrix, 0, rotationAngle, 0f, 1f, 0f);
```
`translationX` and `translationY` come from anchor pose.

**Comment by vijayuttam** [comment]
Hi,
As above mentioned rotation about Y axis, can we rotate object on finger movement. I have tried with given examples to rotate and translate object but it seems doesn't work. Later I used OnTouch to get rotational angle but it move very fast. What's the best idea to deal with rotation on ARCore?

**Comment by inio** [comment]
@vijayuttam Rotation angles above are in radians, so 2π (about 6.3) is a full rotation instead of the 360 you might expect.  Would that explain the moving very fast?

Also, keep an eye on #154 .
