### ISSUE TITLE
How to draw an image on the detected plane ?

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#175]
Hi,

Thanks for the great hello_ar_java demo project.

It would be really great if you could add a "PictureDrawer" class to draw an image (for example with a width of 1 meter and a height of 2 meters) on the detected plane.

Thanks !

**Comment by inio** [comment]
Thanks for the suggestion. 

However, our sample code is intended to be a very simple demonstration of the core library capabilities.  Maybe consider using Unity instead of the Java API if you're looking for help with simple things like this?
