### ISSUE TITLE
Display world origin or axes in debug mode ?

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#178]
Is there a way to display the world origin and X,Y,Z axes in debug mode ? (as with ARKit)

Would be very convenient for debug.

Thanks.

**Comment by inio** [comment]
The feature of ARKit you're describing is actually a feature of of the SceneKit integration, not ARKit itself.

Further, the origin is really kinda meaningless in an AR context.  We intentionally provide no guarantees about it's location or physical stability.  If you want a fixed reference point point, create an anchor and work relative to that.
