### ISSUE TITLE
feature request: Have vertical plane detection(e.g. walls)

### ISSUE THREAD

**Issue by nativ18** [google-ar/arcore-android-sdk#18]
I opened a thread on StackoverFlow, you can view it [here](https://stackoverflow.com/questions/45977545/detecting-wall-plane)

**Comment by nathanmartz** [comment]
Thanks for the feature request and it's something we are looking into.

**Comment by aussieburger** [comment]
Any update on this? Is it in ARCore P2 (not had time to test it yet). Else is it on a roadmap with a planned version number? Thanks in advance for the info!

**Comment by cosmo-naut** [comment]
Any information available on the current stage of the project? Especially regarding vertical plane detection or an estimate as to when such a thing would be available.

**Comment by inio** [comment]
No proper vertical planes yet, but 1.0 released today provides [detection of local planar surfaces in response to hitTest](https://devsite.googleplex.com/ar/discover/concepts#oriented_points) if there are sufficient visual features in the area.

**Comment by Nigel-Burton** [comment]
Hi @inio that link is to googleplex - is this referenced in public docs? Thanks

**Comment by inio** [comment]
[ARCore 1.2 released to developers today](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.2.0) adds vertical plane detection.  It is enabled by default when using the 1.2 SDK.
