### ISSUE TITLE
Duplicate zip entry [classes.jar:com/google/android/aidl/BaseProxy.class

### ISSUE THREAD

**Issue by carlyonj** [google-ar/arcore-android-sdk#180]
It looks like I am getting a duplicate zip entry from including both an arcore library and another library. I have tried to exclude BaseProxy but with no luck, there doesn't even exist a documentation page for BaseProxy.

Commenting out the arLibv5 library allows my app the build just fine.

`(Duplicate zip entry [classes.jar:com/google/android/aidl/BaseProxy.class]))
`

```
implementation (name: 'adobeMobileLibrary-4.13.6', ext: 'jar') 
implementation (name:'arLibv5', ext:'aar') 
```

**Comment by inio** [comment]
Whoops, yep, that's a bug. Good news is that it's already fixed for for the next release.

**Comment by carlyonj** [comment]
Is there a consumer fix for this or an ETA on the release?

**Comment by inio** [comment]
You could unpack and repack the AAR (reame to .zip, unzip, rename classes.jar to classes.zip, unzip, remove offending files, rezip, rename, rezip, rename).

I can't share any timeline right now but keep your eyes out for more info soon.

**Comment by carlyonj** [comment]
I'm actually not sure what files need to be removed. I am being told that BaseProxy is the issue but I don't know what is including that.

**Comment by inio** [comment]
It actually tells you exactly where in the exception:

* extract arcore_client.aar and open
* extract classes.jar and open
* remove com/google/android/aidl/*.class
* repackage classes.jar
* repackage arcore_client.aar

**Comment by carlyonj** [comment]
So it appears that none of my included jars or aars were the issue, none of them had aidl.

Turns out it was from com.google.vr and adding 

```

        exclude group: 'com.google.android', module: 'aidl'
        exclude group: 'com.google.vr', module: 'sdk-common'

```

fixes that issue.

**Comment by inio** [comment]
Excellent!  Leaving open until we fix this properly.

**Comment by inio** [comment]
This is fixed in 1.0.  Please update your build to [load the 1.0.0 AAR from the Google maven repo](https://devsite.googleplex.com/ar/develop/java/enable-arcore#dependencies) and you should be able to drop the excludes.

**Comment by JudeOsborn** [comment]
I am stilling running into this problem. I am using arcore-unity-sdk-v1.1.0.untitypackage.

**Comment by inio** [comment]
@JudeOsborn If you're using Unity please post over on the [Unity issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
