### ISSUE TITLE
Tracking never starts on Asus Zenfone AR

### ISSUE THREAD

**Issue by haroldmthyng** [google-ar/arcore-android-sdk#183]
Despite having a supported device for release 1.0, ARCore still fails to run on Asus Zenfone AR.

Running any of the sample java projects, such as hello_ar_java, yields a dialog notifying that the application needs the latest version of ARCore. When you click continue, you get a "Item not found. Retry" prompt. Seems the required ARCore service or APK isn't fully accessible for this supported device.

Also, the ARCore store listing within the PlayStore states "Your devices isn't compatible". So I'm unable to manually install the ARCore.apk if that's still required.

**Comment by avirodov** [comment]
Hello. Can you please send the fingerprint of your device? You can obtain it with:
`adb shell getprop ro.build.fingerprint`

**Comment by haroldmthyng** [comment]
Hey Author.

Thanks for getting back to me. The finger print is:

asus/VZW_ASUS_A002A/ASUS_A002_1:7.0/NRD90M/VZW_ASUS_A002A-V3.7.8-20170922:user/release-keys

I thought it may have been due to the device still running Android 7.0, but I see the latest ARCore release is targeting Android 7.0 and up.

Harold M Jr
Manager of Mobile Applications
Thyng

c: 312-519-8293
www.thyng.com<http://www.thyng.com>

On Feb 23, 2018, at 12:26 PM, avirodov <notifications@github.com<mailto:notifications@github.com>> wrote:

adb shell getprop ro.build.fingerprint

**Comment by inio** [comment]
Thanks for catching this!  We've pushed out a fix, so you should be able to see and install ARCore on your ZenFone now.  Please let us know if you encounter any more issues.

**Comment by haroldmthyng** [comment]
Excellent! Can confirm the device was able to find and install the latest ARCore service from Google Play when prompted.

Although I am experiencing a different kind of problem now, as point clouds are failing to generate. May be unrelated, but either way will submit a separate bug ticket if needed after I investigate and debug further. Thanks for the quick turn-around on this!

**Comment by inio** [comment]
One thing to realize about ARCore vs. Tango, is that you won't get point clouds when the device is stationary (or at least they won't update).  The mapping system needs motion to be able to triangulate feature points.

**Comment by haroldmthyng** [comment]
So far it's failing to find anything compared to running the sample on a Pixel2, which returns a point cloud almost instantly. I think the AR session is just failing to find any trackables, motion or not. Will keep you posted as I keep debugging.

**Comment by inio** [comment]
OK, just wanted to make sure expectations were reasonable since you're on a tango device :).  Since you have experience on a Pixel I assume you know what the point clouds should look/act like.

**Comment by haroldmthyng** [comment]
Hmm. Plot thickens. Seems camera tracking state always returns "PAUSED", when the sample project calls `camera.getTrackingState()`

```
result = {TrackingState@5311} "PAUSED"
 nativeCode = 1
 name = "PAUSED"
 ordinal = 1
 shadow$_klass_ = {Class@4983} "class com.google.ar.core.TrackingState"
 shadow$_monitor_ = -1944524496
```

**Comment by haroldmthyng** [comment]
Added an error log just to confirm the PAUSED state wasn't a byproduct of being in debug mode. It does in fact always return paused.

```
02-23 15:31:51.087 24433-24468/com.google.ar.core.examples.java.helloar E/native: vio_initializer.cc:287 Received image measurement before corresponding IMU measurement. [245474.8174062 < 822296.9756885]
02-23 15:31:51.099 24433-24452/com.google.ar.core.examples.java.helloar E/HelloArActivity: OnDrawFrame() stopped. Current tracking state: PAUSED
02-23 15:31:51.133 24433-24452/com.google.ar.core.examples.java.helloar E/HelloArActivity: OnDrawFrame() stopped. Current tracking state: PAUSED
02-23 15:31:51.167 24433-24452/com.google.ar.core.examples.java.helloar E/HelloArActivity: OnDrawFrame() stopped. Current tracking state: PAUSED
```

I also include an additional error message that's coming through the logs. No idea if it's related or not.

**Comment by haroldmthyng** [comment]
Let me know if you want me to create a new issue at this point as how camera is acquired and tracking are all pulled via the native handles.

**Comment by inio** [comment]
Lets just reopen this one for now

**Comment by haroldmthyng** [comment]
Sounds good to me.

**Comment by inio** [comment]
Just to anticipate the first question I'm going to get internally: A full log for running for at least 30-60 seconds would be useful.  Put it on pastebin or something to not clog up this bug.

**Comment by haroldmthyng** [comment]
Here you go:

Hello AR project Logcat: `https://pastebin.com/4xRHG6Lc`
Full device logcat: `https://pastebin.com/pLHc0a2K`

**Comment by haroldmthyng** [comment]
Just taking a wild guess, but this looks suspicious:
```
02-23 16:04:39.204 30904-10593/? D/VideoPlayerService: session[-1900996486]: asset is null, returned empty session asset
02-23 16:04:39.204 30904-10593/? E/VideoPlayerService: session[-1900996486]: no available player to getCurrentPositionMs
```

**Comment by inio** [comment]
Looking at the logs, the timestamps between IMU and camera data are WAAAAY off (like, 6 days off).  Maybe try restarting the phone?  We're still looking into how this could have happened.

**Comment by haroldmthyng** [comment]
Pyscho. That actually worked. Sample is now running on restart.

On Feb 26, 2018, at 1:58 PM, Ian Muldoon <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking at the logs, the timestamps between IMU and camera data are WAAAAY off (like, 6 days off). Maybe try restarting the phone? We're still looking into how this could have happened.

**Comment by inio** [comment]
Cool.  There's a good chance it will break again if the phone either:
1. goes into deep sleep for any length of time
2. stays up for multiple days

Please re-open this issue if it crops up again.

**Comment by haroldmthyng** [comment]
Roger that. Will do and thanks.

**Comment by inio** [comment]
Reopening as a second user has reported.

**Comment by haroldmthyng** [comment]
@inio Let me know if there's anything you want me to try, test, or log since it's fully functioning on my Asus device.

**Comment by inio** [comment]
Not much to do.  It's a known driver issue.

**Comment by Anil0319** [comment]
lenovo k8 note

getting same error of latest version ARCore required & item not found please help

**Comment by inio** [comment]
The Lenovo K8 Note is not a [supported device](https://developers.google.com/ar/discover/#supported_devices).  Please feel free to post a comment over in #89 mentioning it.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
