### ISSUE TITLE
1.0 Release on S8 "Problem Connecting"

### ISSUE THREAD

**Issue by radioraheem** [google-ar/arcore-android-sdk#184]
Hi there!

I installed today's release of arcore 1.0 directly from the play store on my Galaxy S8 (SM-G950U running Oreo) and every time I try to start an arcore related app I get the following error:

"ARcore encountered a problem connecting. Please start the app again."

Reboots and reinstalls of both ARcore and the apps have had no effect.

Anything else I should try?  Please let me know if I can provide any other information! Thanks :)

**Comment by avirodov** [comment]
Hello. This looks like a Unity issue. Can you please confirm you are running the Unity app and not the Java/C apps?

Separately, can you please verify the ARCore you installed is 1.0 and not 0.91? You can do this by looking at Settings->Apps->Application Manager->ARCore.

**Comment by radioraheem** [comment]
ARCore Version 1.0.180129103

I'm not sure about the unity/java/c question, I installed ARCore directly from the Play Store link today, so it's whatever was installed by the store.

**Comment by inio** [comment]
What app are you using?  If you're using the Solar System or Molecule apps, those were developed against Developer Preview 2 and may have some issues.

This board is intended for mostly for supporting app developers working with ARCore.  If you're having issues with a specific application, contact that app's developer.
