### ISSUE TITLE
Exception running helloAR_java on Samsung S8 SM-G950F

### ISSUE THREAD

**Issue by yuguitao** [google-ar/arcore-android-sdk#187]
Android: 7.0
ARCore ( download from google playstore): Version 1.0.180129103
Exception popup: " This device does not support AR   DISMISS"

**Comment by inio** [comment]
Duplicate of #198

**Comment by yuguitao** [comment]
fingerprint:    samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQL1:user/release-keys
I try the latest ARCore : 1.0.180129153
It still not work.
