### ISSUE TITLE
could you tell me how to pass the "supported device" test?

### ISSUE THREAD

**Issue by congguohua** [google-ar/arcore-android-sdk#188]
Hello, we are device manufucturers, could you tell me how to pass the "supported device" test?

**Comment by inio** [comment]
You should contact your Android Tech Account Manager to see what's involved in starting the process.

**Comment by ARPatrick** [comment]
hey,
did you ever reach that manager or find out any information that you could share?

**Comment by inio** [comment]
@ARPatrick if they did it would be under NDA and they could not share it.
