### ISSUE TITLE
arcore1.0 does not support huawei P9(Android7.0)

### ISSUE THREAD

**Issue by gupengcheng** [google-ar/arcore-android-sdk#189]
when i run hello_ar_java demo, it show 'This device does not support AR', can you tell me when it  will support more devices?

**Comment by inio** [comment]
@gupengcheng What is your device fingerprint?  Capture it with:

    adb shell getprop ro.build.fingerprint

**Comment by inio** [comment]
Oh, wait, sorry, that's not a supported device.

**Comment by inio** [comment]
Duplicate of #89

**Comment by inio** [comment]
Supported devices are listed here:

https://developers.google.com/ar/discover/#supported_devices
