### ISSUE TITLE
Include arcore_c_api.h in ndk

### ISSUE THREAD

**Issue by kdk96** [google-ar/arcore-android-sdk#190]
Can you include arcore_c_api.h in ndk?

**Comment by inio** [comment]
We're not quite sure what you're asking.  If you're having trouble locating the header, you can grab a copy here:

https://github.com/google-ar/arcore-android-sdk/blob/master/libraries/include/arcore_c_api.h

**Comment by inio** [comment]
ARCore is not a system service, so including it in the base NDK header distribution is not appropriate.
