### ISSUE TITLE
ARCore not supported on Nokia 5

### ISSUE THREAD

**Issue by beersheba** [google-ar/arcore-android-sdk#193]
On launch ARCore demo 'File not found' pop-up appears.

`Unexpected response code 404 for https://android.clients.google.com/fdfe/inlineDetails?doc=com.google.ar.core`

Nokia 5, API 25

**Comment by inio** [comment]
The Nokia 5 is not a [supported device](https://developers.google.com/ar/discover/#supported_devices).

**Comment by inio** [comment]
Duplicate of #89
