### ISSUE TITLE
Feature Request: Tango BW camera for tracking

### ISSUE THREAD

**Issue by adigyran** [google-ar/arcore-android-sdk#195]
That will be useful for better tracking, as i concerned color is not needed for arcore. Tango tracking through that camera is better, and then google discontinues tango 3d sensor and fisheye camera becomes useless on Asus AR

**Comment by inio** [comment]
ARCore is optimized to run on all android phones.  Using the color camera for motion tracking has advantages over using the dedicated motion tracking camera, including a much better user experience in the presence of camera occlusions.

If you want to use the feature tracking camera, TangoCore and the associated APIs still work.
