### ISSUE TITLE
Run ARcore1.0 demo on Emulator  cause :This device does not support AR

### ISSUE THREAD

**Issue by 11447416** [google-ar/arcore-android-sdk#196]
I see [https://developers.google.com/ar/develop/java/emulator](https://developers.google.com/ar/develop/java/emulator) ,ARcore1.0 can run on Emulator with Android 8.1 (Oreo),but it can't work with a error:"This device does not support AR".

My environment is below:
Android Studio 3.1 Beta 2
Build #AI-173.4580418, built on February 1, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

My emulator:
Name: Pixel_2_API_27_-_ARcore
CPU/ABI: Google APIs Intel Atom (x86)
Path: /Users/xxxx/.android/avd/Pixel_2_API_27_-_ARcore.avd
Target: google_apis [Google APIs] (API level 27)
Skin: pixel_2
SD Card: 100M
hw.dPad: no
hw.lcd.height: 1920
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_2
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.lcd.width: 1080
hw.gps: yes
hw.initialOrientation: Portrait
image.androidVersion.api: 27
hw.audioInput: yes
image.sysdir.1: system-images/android-27/google_apis/x86/
tag.id: google_apis
showDeviceFrame: yes
hw.camera.back: virtualscene
hw.mainKeys: no
AvdId: Pixel_2_API_27_-_ARcore
hw.camera.front: emulated
hw.lcd.density: 420
avd.ini.displayname: Pixel 2 API 27 - ARcore
hw.arc: false
hw.gpu.mode: auto
hw.device.hash2: MD5:bc5032b2a871da511332401af3ac6bb0
hw.ramSize: 1536
hw.trackBall: no
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.battery: yes
hw.cpu.ncore: 4
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

What can i do to deal with this problem? 
Thanks,happpy new year.

**Comment by tpsiaki** [comment]
Will you double check that you have **revision 4** of the google_apis API27 image running?  It was just released on 2/22 and added ARCore support.

In Android Studio under Tools > SDK Manager > SDK Platforms, Check the "Show Package Details" checkbox (bottom right), and make sure the Google APIs Intel x86 Atom System Image shows Revision 4 in the Revision column.

If not, you should be able to update to that and then run ARCore apps.

**Comment by 11447416** [comment]
Thank you, I update it to revision 4 ,it work fine.

**Comment by GOHILCHIRAG** [comment]
I am having same issue even if I have met all the requirements. Oreo 8.1 API 27 revision 5, Camera back to virtual scene. Arcore apk and sample both don't run. Help?

**Comment by inio** [comment]
@GOHILCHIRAG Are you using using a x86 emulator image (not arm or x86_64)?

**Comment by ilkomiliev** [comment]
Hi,
out of curiosity - how did you manage to run the samples in the emulator on MacOS? According to the link you've posted OpenGL ES 3.1 is required, my macbook pro has only 3.0 and I haven't found any mac device with support for 3.1? The output I get:

```
I/InstantRun: starting instant run server: is main process
D/: HostConnection::get() New Host Connection established 0xd61ff300, tid 2966
I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
D/EGL_emulation: eglCreateContext: 0xd666ede0: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xd666ede0: ver 3 0 (tinfo 0xe942c940)
I/Filament: FEngine (32 bits) created at 0xe6af1400
D/: HostConnection::get() New Host Connection established 0xe97235c0, tid 3515
D/EGL_emulation: eglCreateContext: 0xe9705480: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xe9705480: ver 3 0 (tinfo 0xe9703040)
E/Filament: in static std::unique_ptr<Driver> filament::OpenGLDriver::create(filament::driver::ContextManagerGL *const, void *const)
            at line 80
            in file /usr/local/google/home/mathias/sources/git/tnt/filament/filament/src/driver/opengl/OpenGLDriver.cpp
            reason: OpenGL ES 3.1 minimum needed (current 3.0)
D/AndroidRuntime: Shutting down VM
```

**Comment by inio** [comment]
Those questions were asked pre-Sceneform.  I'm not sure if Sceneform works in the emulator.

**Comment by tpsiaki** [comment]
@ilkomiliev - Sceneform currently requires OpenGL ES 3.1, which is not supported on Mac.  We are working on removing this requirement, but until we get a new release of Sceneform out that supports 3.0 you'll need to test either on a supported device, or on an emulator on Windows or Linux.

**Comment by vladtcvs** [comment]
Still have problem. I have opengl es 3.2, and android 9 (api 28 rev 6) in emulator. All arcore apps, sceneform and other, write "This device does not support AR"
