### ISSUE TITLE
Samsung S7 edge SM-9350 cannot run ARCore

### ISSUE THREAD

**Issue by inio** [google-ar/arcore-android-sdk#197]
Reposting as separate issue from @KnIfER's comment in #89.

> still v1 does not support s7 edge:SM-9350(with Qualcomm Snapdragon 820 Processor ),I can install arcore on it but can's run examples

**Comment by KnIfER** [comment]
samsung/hero2qltezc/hero2qltechn:7.0/NRD90M/G9350ZCU2BQL3:user/release-keys

**Comment by inio** [comment]
I just noticed that our supported device page doesn't actually mention the SM-935O.  However, the blog post doesn't indicate any limitation on which models of S7 edge are supported.  Not sure which is the intent, will update this soon.

**Comment by Crusage** [comment]
https://developers.google.com/ar/discover/#supported_devices
It does say Samsung Galaxy S7 SM-G930F, but i just get the message: "there was a problem parsing the package" when trying to open the apk given here: https://github.com/google-ar/arcore-android-sdk/releases/tag/sdk-preview2

**Comment by inio** [comment]
That's very odd.  Is it possible the download got corrupted somehow?  arcore-preview2.apk should have an MD5 checksum of 79a04761c340598e99c8154139db553f.

However, the preview2 apk isn't going to allow you to run apps built against the 1.0 SDK.

**Comment by Crusage** [comment]
I tried downloading it multiple times, but still the same message. Pretty sure the download did not get corrupted in any way. And i am not sure how to check the MD5 checksum

**Comment by inio** [comment]
I just found http://onlinemd5.com/, which shows the same checksum as what I got earlier.

**Comment by inio** [comment]
Is the device running at least android 7.0 (Nougat, API level 24)?

**Comment by KnIfER** [comment]
yes,the os is up to date.  
well,Just now I "hacked" through this,and successfully get JustALine v1.0.1  run——  
this may prove that arcore is still somewhat functioning on my device,although when I tap on the icon of 
JustALine,it shows a crash dialog"Arcore stopped" and then exits to desktop.  
  
my method: tap on the icon->before crash dialog popping up,keep one finger on the screen,keep moving-> crash dialog appears->use another finger,while keep the old one still on the screen,both moving->the crash dialog is somewhat "swept" away,and now I can draw in the air!  
however, after a while when I  tap on the icon,it toasts "the device does not support AR" and exits,I have to reinstall arcore v1.1.18031062

**Comment by inio** [comment]
@KnIfER If I'm not mistaken, that dialog says something like "ARCore has stopped"?

This error usually means that the GMSCore (com.google.android.gms) on your device is very out of date.  Does this device have full access to the Play Store?  If so it *should* be updating that package regularly.

**Comment by inio** [comment]
ARCore is not currently supported on China and Hong Kong variants of Samsung devices prior to the S9 (and the S9 isn't supported quite yet).  Additionally, ARCore is not supported on *any* device without regular access to the Play Store.

**Comment by KnIfER** [comment]
with 1.2 just a line won't crash now.

**Comment by inio** [comment]
@KnIfER If you look at logcat you'll probably see messages about com.google.ar.core not being "launcherable".  This is an issue on Samsung devices ending with 0 and 8 that we cannot easily fix and is the reason ARCore is not supported on these devices.
