### ISSUE TITLE
Known Issue: ARCore 1.0 is not supported on many devices after updating to Android 8 "Oreo" 

### ISSUE THREAD

**Issue by inio** [google-ar/arcore-android-sdk#198]
***OOPS!*** ARCore 1.0.180129103 is not supported on the following devices when running Android 8 "Oreo" (8.0 or 8.1):

* Samsung S8
* Samsung S8+
* Samsung Note 8
* OnePlus 5

We are working on a fix.

**Comment by Crashthatch** [comment]
Thanks for the quick fix. Will it be released soon? 
We can't upgrade our app from preview 2 until this is fixed because it will break the app for users on all affected devices.

**Comment by inio** [comment]
@Crashthatch I believe Developer Preview 2 will also fail to start on these devices when running Oreo.

**Comment by henrifly** [comment]
@inio Preview 2 did work on Samsung S8 SM-G950F with Oreo

**Comment by handymoby** [comment]
thanks for the prompt response, when will the fix be release?

**Comment by inio** [comment]
@handymoby: We don't have a release timeline yet, but are actively working on a fix.  Android Oreo introduces changes to the camera system that affect calibration on many devices, quite significantly in some cases.  To ensure a solid AR experience, we need to run tests to verify tracking performance on these devices with their final Android 8 builds.

@henrifly: It turns out that Developer Preview 2 accidentally included several preliminary device calibrations, some based on prerelease versions of Android 8.  Because of this it may run on these devices with limited performance.

**Comment by Crashthatch** [comment]
@inio I didnt notice any change between android 7 and 8 performance on my S8 SM-G950F. Preview 1 also supported this device.

We cannot release (I personally cannot even test) until it is fixed for this device.

**Comment by inio** [comment]
Good news! We expect to roll out a fix for this issue early next week.  You should get an update to ARCore from the Play Store when it becomes available.

**Comment by Crashthatch** [comment]
Fantastic news, thanks @inio!

**Comment by punitvara** [comment]
thanks. @inio  Thats absolutely great news

**Comment by inio** [comment]
The update should be fully rolled out at this point.  You should all have an update available from the Play Store to version 1.0.180129153.

**Comment by SeddyGH** [comment]
Thanks boi

**Comment by devangeill** [comment]
Im sorry but that was the old version, there's no new update on PlayStore

**Comment by yannoid** [comment]
Works for me with the new update. Thanks 👍 nice work

**Comment by Sp4iK** [comment]
Yes, I also confirm that it works with the update.

**Comment by devangeill** [comment]
Ah, got it to work now. Thanks~!

**Comment by inio** [comment]
@devangeill previous release was ...103, this is ...153

**Comment by escapees** [comment]
where is the uptade ??

**Comment by vincentfretin** [comment]
on the Play Store, search for arcore and install it.
https://play.google.com/store/apps/details?id=com.google.ar.core

**Comment by inio** [comment]
@escapees As @vincentfretin said, the you should have an update available on the Play Store.

If you don't have access to the Play Store, we don't yet have an official channel.  Knowing that there are developers without access to the Play Store that want ARCore would be good though, so let me know if that's the case.

**Comment by hofcsabaGit** [comment]
Still not working for me S8, Oreo, Exynos, ArCore, 1.0

**Comment by inio** [comment]
@hofcsabaGit What model number of S8 do you have?  In particular the SGM-G9500 and SM-G9508 distributed primarily in China and Hong Kong are not supported (see [supported device list](https://developers.google.com/ar/discover/#supported_devices)).  If it's not one of those devices, please post your device's build fingerprint (`adb shell getprop ro.build.fingerprint`) and details of what you mean by "not working".

**Comment by AdrienNeveu** [comment]
After the latest Android security update, ARCore doesn't work anymore on my S8 SM-G950F.
Restarting my device doesn't solve the issue, but reinstalling ARCore does fix the black screen. But any ARCore app crashes again after about 20 seconds and I will get the black screen until I reinstall ARCore again.

Device's build fingerprint:
`samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU1CRD7:user/release-keys`

The errors I get continuously:

```
05-02 17:43:22.538: E/native(25797): session_c_api.cc:148 ArConfig_setLightEstimationMode: session was passed NULL.
05-02 17:43:22.538: E/native(25797): session_c_api.cc:207 ArSession_configure: session was passed NULL.
05-02 17:43:22.538: E/native(25797): session_c_api.cc:527 ArFrame_acquireCamera: session was passed NULL.
05-02 17:43:22.538: E/native(25797): session_c_api.cc:496 ArCamera_getTrackingState: session was passed NULL.
05-02 17:43:22.555: E/native(25797): session_c_api.cc:527 ArFrame_acquireCamera: session was passed NULL.
05-02 17:43:22.555: E/native(25797): session_c_api.cc:496 ArCamera_getTrackingState: session was passed NULL.
05-02 17:43:22.555: E/native(25797): session_c_api.cc:183 ArConfig_setUpdateMode: session was passed NULL.
05-02 17:43:22.555: E/native(25797): session_c_api.cc:166 ArConfig_setPlaneFindingMode: session was passed NULL.
```

**Comment by hofcsabaGit** [comment]
Hi inio, and thank you for your help.

I think my device fingerprint is samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU1CRC7:user/release-keys

and my model is SM-G950F.

I started developing an ArCore app with Unity back in 17 November. Since I updated to Oreo, two weeks ago, whenever I open my development build a toast comes up saying, "This device does not support ArCore, and then quits. The same toast comes up, when opening ArCore apps form the PlayStore.

ArCore is on ArCore 1.1.180312063, and the device is an UK Exynos variant.

Thanks again, for your help,
Csaba

**Comment by inio** [comment]
@AdrienNeveu What app is producing these?  Could you try with HelloAR Java and if it fails similarly provide a logcat around the beginning of the failure.

@hofcsabaGit That definitely should be a supported device.  We're investigating.

Both: I've opened #350 to track this.

**Comment by inio** [comment]
@hofcsabaGit I just tried HelloAR Java on an S8 SM-G950F with build fingerprint samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU1CRC7:user/release-keys.  It installed ARCore 1.1.180312063 and worked perfectly.  I'll need a logcat to help debug further.

**Comment by hofcsabaGit** [comment]
Hi inio, thank you for your patience. Im attaching a logcat, around the time it happend.
[logcat.txt](https://github.com/google-ar/arcore-android-sdk/files/1970442/logcat.txt)

**Comment by inio** [comment]
@hofcsabaGit Looking through that log, I see a couple interesting things:
1. I see a lot of mention of Unity.  In general we prefer if Unity issues are posted on the Unity board instead of the Android board, which is intended to support the Java and C++ APIs.  However,
2. I see several mentions of Tango, and no occurrences of the string "ARCore-" which is generated by the early compatibility checks in the current SDK.  What version of the SDK are you using?
3. Around one session creation failure I found, I didn't see a signal log message from our internals, which seems very odd even if you were using the DP1 SDK (which you shouldn't be).

**Comment by sabithkhathim** [comment]
Same happens with SM-G930F S7 Oreo 8.0. Just a line app crashes once, and Arcore crashes like 10 times, then shows a toast that the device doesn't support ar. What details should I provide further?

**Comment by JamesR48** [comment]
Do you know if the Xiaomi Mi A1 is going to be in the supported devices list soon?

**Comment by sabithkhathim** [comment]
Started working on SM-G930F Galaxy S7 Oreo after 1.2.180425094 update. Thank you. 

https://www.apkmirror.com/apk/google-inc/arcore/arcore-1-2-180425094-release/arcore-1-2-180425094-android-apk-download/

**Comment by inio** [comment]
@JamesR48 Wrong issue for that sort of question.  Please post in #89 for our recordkeeping.

**Comment by JamesR48** [comment]
@inio sorry bro! My bad, I'll post there now

**Comment by inio** [comment]
For users finding this thread:  There is an issue with a couple devices including the Samsung Galaxy A5 where ARCore and ARCore apps will stop showing up in the Play Store after updating to Oreo.  This is not intentional (ARCore should work just fine on these devices) and will be fixed within a few days.

**Comment by JamesR48** [comment]
@inio I don't know if I can post this question here but I'm desperate to try ARCore on my Mi A1 haha, so I rooted my device and installed a Pixel XL mod with Oreo (8.1) running. I was able to download ArCore from the PlayStore thanks to that but I'm getting an error message saying "ARCore  has encountered a problem connecting. Please restart the app." Over and over again while trying to run the HelloAR.apk (also I tried building the one on your Unity SDK using Unity 2017.3.1) because the Atoms app is not rendering the camera image, just shows the UI and a blue screen...so, I was wondering if you can recognize that error message and maybe what could be causing it. Thanks!

**Comment by inio** [comment]
@JamesR48 : Making a device lie to software that it is a Pixel will not make ARCore work.  ARCore needs per-device and in some cases per-os-version calibration information for each device.

Your best bet for having ARCore work is to pick up a used older-model device that  we support.  I believe the Samsung A5 is the lowest cost option on [the list](https://developers.google.com/ar/discover/supported-devices).

**Comment by abdurrahmanTurkeri** [comment]
@inio i had seen that note 8 was in  supported devices list but i couldnt see it at updated list.Sm-N9500 device id seems not supported.
Any luck about it was supported at previous version?

**Comment by abdurrahmanTurkeri** [comment]
Ok thanks for answer @inio .Is there any possibilities make it work by installing arcore to device manually, I mean the device as  Sm-N9500  Model ID Note8.
As a developer it will be enough  to see a hello world sample.

**Comment by inio** [comment]
@abdurrahmanTurkeri At this time ARCore is not supported on Samsung devices with model numbers SM-****0 and SM-****8.  We're looking at addressing this issue, but cannot offer any guarantees or a timeline.

**Comment by MusTafaKhaled** [comment]
@inio

**Comment by lddatacom** [comment]
Hi,

I just figured out that ARCore is also not supports Sony ZX2 running Android 8.0.0. 

Just wonder if it is a known issue or should I create  a new ticket for it?

Thanks.

**Comment by BartoszBogal** [comment]
Hi,
I've got a problem with Tango Core on my new Galaxy A5. While using AR apps from Google Play, everything is right, but when I installed "ARCore APK Developer" and " WebARonARCore APK", none of examples is running and Tango Core turns off.

Thanks!

**Comment by ManojBalaji3001** [comment]
will the ARCore support Vivo v9 on future?
