### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 544531645** [google-ar/arcore-android-sdk#199]
arcore 1.0 upated only support more phone ? the open camera date also need time ?

**Comment by inio** [comment]
Sorry, not sure what you're asking about.

1.0 adds:
* Support for many new devices
* [App distribution through the Play store](https://developers.google.com/ar/develop/java/enable-arcore)
* [Oriented points](https://developers.google.com/ar/discover/concepts#oriented_points)

**Comment by inio** [comment]
If the answer above is for the wrong question or insufficient, please feel free to reopen this.
