### ISSUE TITLE
Device not supported Samsung Galaxy S8

### ISSUE THREAD

**Issue by dv-dt-spal** [google-ar/arcore-android-sdk#2]
I am getting the "This device does not support AR" while running the android sample on Samsung Galaxy S8. I have installed the arcore-preview.apk as mentioned. 

If I comment the the config check I get `java.lang.RuntimeException: Unable to resume activity {com.google.ar.core.examples.java.helloar/com.google.ar.core.examples.java.helloar.HelloArActivity}: com.google.ar.core.exceptions.UnsupportedConfigurationException` error.

I am using Android Studio 2.3.3

**Comment by nathanmartz** [comment]
What model number is your S8? Is it one of the ones listed under our [supported devices](https://developers.google.com/ar/discover/)?

**Comment by dv-dt-spal** [comment]
Mine is SM-G955U and I don't see it in the supported device list. :( Any ideas if it is going to be supported.
