### ISSUE TITLE
Camera focus with arcore camera

### ISSUE THREAD

**Issue by deeppandya** [google-ar/arcore-android-sdk#200]
Is there a way to focus camera using arcore camera ? I am working on an application where i need to put object using ARCore. and then i need to save the frames as an image.

**Comment by inio** [comment]
Currently ARCore uses a fixed focus to ensure stable camera intrinsics.  We may introduce autofocus or focus control in the future.

**Comment by inio** [comment]
Duplicate of #153

**Comment by fredsa** [comment]
Autofocus was added in the 1.4.0 release.

**Comment by Attaullah123** [comment]
Hi @fredsa,
I use 1.4.0 release of arcore but still auto focus is not working. Can you please suggest me class or method i need to call foe auto focusing
Thanks

**Comment by inio** [comment]
@Attaullah123 are you turning on auto focus?  It needs to be enabled using `Config.setFocusMode()` and then reconfiguring the session.
