### ISSUE TITLE
Pixel 2 (non-XL) compatibility problems

### ISSUE THREAD

**Issue by soderbjorn** [google-ar/arcore-android-sdk#203]
App linked with ARCore 1.0 APK on Pixel 2. When trying to determine compatibility using the recommended API, logcat says `E/ARCore-IS: requestInfo returned: -100`
What does it mean?

**Comment by soderbjorn** [comment]
It turned out to be because I was logged out of Google Play Services. Once I re-logged, that error disappeared. **However, I still cannot run ARCore on this Pixel 2** as I'm getting `UnavailableDeviceNotCompatibleException` -- and that's also the case with the sample app from the repo. It worked fine with preview 2.

**Comment by inio** [comment]
If you search the play store for ARCore, can you see it?

If not try loading market://detail?id=com.google.ar.core in chrome.

**Comment by soderbjorn** [comment]
Yes, I could see it in the Play Store. I tried selecting "Uninstall" there and ran my app again (which caused ARCore to re-install) and then it suddenly worked. So apparently some kind of confusion about version and/or ARCore installation status I guess.

**Comment by inio** [comment]
Very odd.  Glad it's working now.
