### ISSUE TITLE
release 1.0: resume tracking regression?

### ISSUE THREAD

**Issue by afedorychak** [google-ar/arcore-android-sdk#209]
Dev preview 2 has been pretty good with resuming plane tracking, especially if environment didn't change much.

With ARCore 1.0 it can't resume after what seems like trivial changes in the environment. The video demonstrates a standrad HelloAR app built using "Getting started with Unity"  article. The version or ARCore on the phone (Pixel 2) is 1.0.180129103.

https://github.com/afedorychak/arcore_issues/blob/master/issue.mp4?raw=true

**Comment by afedorychak** [comment]
Sorry, I should have posted this under arcore-unity-sdk probably (I did repost it there: https://github.com/google-ar/arcore-unity-sdk/issues/125)

**Comment by inio** [comment]
Try running your app for a bit longer and moving the device around more before pausing it.  at least 30 seconds and 50-100cm of motion should be enough.
