### ISSUE TITLE
Sample from https://developers.google.com/ar/develop/java/getting-started doesn't work

### ISSUE THREAD

**Issue by SumeraMartin** [google-ar/arcore-android-sdk#21]
Your sample application from https://developers.google.com/ar/develop/java/getting-started show Parse Exception during installation.

**Comment by nathanmartz** [comment]
Can you provide more information like a screenshot of the error or exactly
which step of the setup process isn't working? Many people have installed
this sample without issue, so most likely it's a simple oversight.
