### ISSUE TITLE
Suggest me about New phone

### ISSUE THREAD

**Issue by ranaNarin** [google-ar/arcore-android-sdk#210]
hi, 
it's a great project I really interested in this, I have downloaded demo project and Successfully run it on my friend Device that is Samsung S8, I really want to deep study in this project and I have to buy a new phone for the testing it, which is the best Phone for this in future also because I can't be offered a new Phone in future next 3 to 5 years. and also when I run it on Samsung s8, it's lots of warm in 5 minutes.

Suggest me

**Comment by inio** [comment]
Any of the devices on [our supported device list](https://developers.google.com/ar/discover/#supported_devices) should work.  If budget isn't an issue, I'd tend towards one of the newer devices: The S8 or Pixel 2 being the most obvious.

If the sky's the limit and you're in a market where **unlocked** Pixel 2 devices are available, I'd have to recommend that route.  Google has a good track record of offering OS updates for their Android devices quickly and for quite a while after release, and by getting an unlocked variant you don't need to wait for a carrier to release updates.
