### ISSUE TITLE
Add 3D object as soon as first plane identified without tap

### ISSUE THREAD

**Issue by rramprasad** [google-ar/arcore-android-sdk#215]
I have used HelloAR sample and replaced the 3D object with my own object. Now this app,identifies planes  and add 3D object after click on a plane. I need to add 3D object as soon as first plane identified.Is it possible,or I should add 3D object after click and hit result?

**Comment by Xanvial** [comment]
Yes, the easiest way is just creating an anchor on the center of detected plane. I believe this should works
```
Anchor newAnchor;
for (Plane plane : mSession.getAllTrackables(Plane.class)) {
  if (plane.getType() == Plane.Type.HORIZONTAL_UPWARD_FACING
     && plane.getTrackingState() == TrackingState.TRACKING)
  {
    newAnchor= plane.createAnchor(plane.getCenterPose());
    break;
  }
}
```

Make sure to just call it once, so it won't spam a new anchor on every update.

**Comment by inio** [comment]
Yes, as @Xanvial suggests, create an anchor on the first plane you see.

This will result in poor user experience if the first plane is not well-placed.  Allowing the user to pick a location on a plane is probably much better.

**Comment by gulnazghanchi** [comment]
This answer helped me. 

@inio you are right. this will place 3D model only once on the plane area while we call this method. 
If you missed the loading of 3D model once while you call the method. You can put your logic on

arFragment!!.arSceneView.scene.addOnUpdateListener  listener and call this method there. but this listener will be called again and again to update the scene. so you can put your local variable to check whether your model is already loaded once or not. 

call that method on addOnUpdateListener when model is not loaded.
