### ISSUE TITLE
How to disable lighting for plane in ar-core android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#216]
Iam using ar-core sample in android.i was disable lighting  extimation mode using:
`config.setLightEstimationMode(Config.LightEstimationMode.DISABLED);` 
But it was disabled only object lighting i want disable lighting while plane rendering is it possible to disable lighting?

**Comment by inio** [comment]
the Java HelloAR app does not use any lighting for it's planes.  Its planes are additively blended using constant color, getting a somewhat lit appearance as a side effect.

**Comment by harsha-main** [comment]
When I load an AR sphere with LightEstimationMode.DISABLED, I can still see part of the sphere darker, what can I do to load them without any shadows at all?

**Comment by leonsaber** [comment]
I think there is nothing happen after set LightEstimationMode.DISABLED. I was trying use Light.builder() but still not work. Fake function?????

**Comment by khyati-agarwal-zomato** [comment]
While creating the shader for plane, you can change sourceRgbBlend from BlendFactor.DST_ALPHA to BlendFactor.CONSTANT_ALPHA

**Comment by khyati18** [comment]
While creating the shader for plane, you can change sourceRgbBlend from BlendFactor.DST_ALPHA to BlendFactor.CONSTANT_ALPHA
