### ISSUE TITLE
What do devices need to support arcore?

### ISSUE THREAD

**Issue by donkii** [google-ar/arcore-android-sdk#217]
Arcore is supported only by a limited amount of devices, will it be available for older devices that have a normal camera? Is it a problem of hardware or does it just need to get software updates to work on older devices?

**Comment by inio** [comment]
ARCore needs three main pieces:

- A fast enough CPU to run the map-building algorithms.  Right now the S7 and S7 edge are bumping up against this limit. This will limit support for older devices.
- Testing to ensure the camera and IMU provide consistent timestamps across exposure, cpu load, etc.  This can require OS updates in some cases.
- Calibration of the camera and IMU, per device model.  For now this can only happen in custom-designed robotic calibration stations using special software.
