### ISSUE TITLE
How to change all plane color to white in ar-core android? 

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#218]
Iam using ar-core android sample.i want change the plane color to white sometime it showing diffrent colors of planes.how can i do that please help me?

**Comment by SimonMarquis** [comment]
Here is the table of colors used to render the planes:

https://github.com/google-ar/arcore-android-sdk/blob/dcfbbbd1661cb4c5580ae1aca34808fbffddb971/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/rendering/PlaneRenderer.java#L415-L432

You can remove all but keep the first one (white).

**Comment by inio** [comment]
@SimonMarquis yep, that looks right.

**Comment by ArigarasuthanRepo** [comment]
Thank you so much @SimonMarquis

**Comment by kaoutherbouguerra1** [comment]
Hi, 
I need to remove all plane in the android sample, any help please !

**Comment by ExtremelySunnyYK** [comment]
Remove all the other colors and add in 0x00FFFFFF
`private static final int[] PLANE_COLORS_RGBA = { 
   0xFFFFFFFF, 
   0xF44336FF, 
   0xE91E63FF, 
   0x9C27B0FF, 
   0x673AB7FF, 
   0x3F51B5FF, 
   0x2196F3FF, 
   0x03A9F4FF, 
   0x00BCD4FF, 
   0x009688FF, 
   0x4CAF50FF, 
   0x8BC34AFF, 
   0xCDDC39FF, 
   0xFFEB3BFF, 
   0xFFC107FF, 
   0xFF9800FF, 
 };`
