### ISSUE TITLE
Missing texture files in Poly virtual objects

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#219]
Hi,
I'm trying to use objects from Poly (working with the hello_ar_java ARCore sample app).

I see there are virtual objects zip files that includes only "obj" and "mtl" files,
without any textures files.
For example https://poly.google.com/view/dfSQmeuuYt3
or https://poly.google.com/view/3kIVlI-tJSc

Other files that includes "obj", "mtl", and png/jpg files - I rendered successfully.
For example: 
https://poly.google.com/view/2ivrvruGzxc 

I download the files manually from Poly website. 

Are this files corrupted?

Thanks!

**Comment by inio** [comment]
Poly models use solid colors instead of texture images.  I believe we have some sample code laying around for loading and drawing them, but I'm not sure where it is.  I'll update this once I find it.

**Comment by itanbp** [comment]
@inio I think I found the project you referred to.

This is the project, [poly-sample-android](https://github.com/googlevr/poly-sample-android/tree/master/PolySampleAndroid) and it has [MtlLibrary](https://github.com/googlevr/poly-sample-android/blob/master/PolySampleAndroid/app/src/main/java/com/example/polysample/MtlLibrary.java) for parsing solid colors mtl files, and also [ObjGeometry ](https://github.com/googlevr/poly-sample-android/blob/master/PolySampleAndroid/app/src/main/java/com/example/polysample/ObjGeometry.java) to handle the Obj file.

I see that the project also includes logic to normalize the virtual objects size

> no matter how big or small the asset is, we will scale it to a reasonable size for viewing


Thanks!
