### ISSUE TITLE
Objects were hide if i go to view inside of the 3d model in ar-core android sample project

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#220]
Iam using ar-core android sample.in the sample project objects were hided if i go to view inside of the the 3d object. but arkit objects were not hided  if i go to view the inside object.

**Comment by inio** [comment]
This is normal backface culling, and will happen with any 3D rendering system.  You can disable this with `glDisable(GL_CULL_FACE)`.

**Comment by ArigarasuthanRepo** [comment]
where to put inside glDisable(GL_CULL_FACE).

 onSurfaceCreated or OnDrawFrame method?
