### ISSUE TITLE
What does "ARCore does not support picture-in-picture mode" mean ?

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#223]
It is written in the version log https://github.com/google-ar/arcore-android-sdk/releases

that "ARCore does not support picture-in-picture mode" 

What does that mean ?

**Comment by avirodov** [comment]
Hello. You can learn more about "split screen" and "picture-in-picture" here:
https://developer.android.com/guide/topics/ui/multi-window.html

Conceptually, it allows you to run multiple apps:
![mw-splitscreen](https://developer.android.com/images/android-7.0/mw-splitscreen.png)

However, we do not support running apps in this mode.
