### ISSUE TITLE
Multiple apk version code scheme for ARCore & Non ARCore versions 

### ISSUE THREAD

**Issue by rramprasad** [google-ar/arcore-android-sdk#224]
**Response from @inio** 

> Yes. Because we use the android.hardware.camera.ar feature flag in AR-Required apps, you can use this feature flag with the Play store's Multiple APK Support. Just make sure the version code of your AR builds are always higher than the non-AR build.

Can I release multiple apk with following version code scheme?
**2401120**
- 24 - mininum Android version
- 01 - ARCore supported version
- 120 - app version name 1.2.0

**0502120**
- 05 - mininum Android version
- 01 - Non ARCore supported version
- 120 - app version name 1.2.0

If I release multiple apk 2401120 & 0502120. After that,If any update to non ARCore version,can I upload with version code 0502121? because we already uploaded 2401120,which is larger than 0502121.
Is it above versioning scheme good for future releases?

**Comment by inio** [comment]
That would work, but I'd recommend dropping the API version (making it implicit from build flavor) and put the arcore bits at the end to allow an easier path forward if you decide to drop that or go to single-apk.  So it looks like:

{major}{minor}{patch}{buildflavor}

So for your cases above you'd have:

    12001 (1.2.0 basic build, minSDK 4)
    12002 (1.2.0 ARCore-enabled, minSDK 24)

You also might want to give more than one digit for the minor and patch

**Comment by rramprasad** [comment]
@inio Yes,But If I update only 12001 version only and upload new version as 12003.Then ARCore version(12002) becomes lower. In this case,I need to update 12002 also whenever I do change in 12001.

**Comment by inio** [comment]
Ah, I see.  Mabe mixing the build type somewhere in the middle makes sense then.  Since you're likely release x.y simultaneously for both builds you could make it `{major}{minor}{build falvor}{patch}`.

**Comment by rramprasad** [comment]
So applying on 

> {major}{minor}{build falvor}{patch}
produces version codes,
12010 (but it is limited to only 10 version updates)
12020 
Is it possible to upload min version code compared to previous release high version code? Is it any Android document provided by Google?

**Comment by inio** [comment]
I'd recommend using two digits for minor and at least two digits for patch.

The [document I linked](https://developer.android.com/google/play/publishing/multiple-apks.html) back in #213 is all the docs I've found on multiple APKs.  When you have multiple APKs uploaded, users will always see the highest version code that is compatible with their device.

**Comment by rramprasad** [comment]
Okay Thank you @inio

**Comment by rramprasad** [comment]
@inio Finally I plan use following format,

**Example 1:**

> 1 01 01 000

1 --> major release
01 --> minor release
01 --> internal code for flavor 1
000 --> patch release

**Example 2:**

> 1 01 02 000

1 --> major release
01 --> minor release
02 --> internal code for flavor 2
000 --> patch release

Is it good for future releases without any issues? If I need to support different flavors for different CPU architectures,is this format makes any issues?

Also which range of numbers need to allocate for alpha & beta testing?

**Comment by inio** [comment]
That seems sensible.  The nice thing is you can always *add* digits if you decide later that you need a 3-digit flavor, for example.

**Comment by rramprasad** [comment]
> Warning: The greatest value Google Play allows for versionCode is 2100000000.

So maximum major release version is 210 with following format.
{major} {minor} {build flavor} {patch} 
001 01 01 001
...
...
209 99 99 999
210 00 00 000

Also maximum Number of build flavors is 99

**Comment by rramprasad** [comment]
I think kind of format will block at some time. If I reach 999 for a flavor, I cant provide update to the flavor forever. So adding API level is good as per the [Android Document](https://developer.android.com/google/play/publishing/multiple-apks.html). Is it any better format available to allocate room for each flavors to provide support for at least 10 years(10 * 360 days...max update per day)?

**Comment by rramprasad** [comment]
Hi @inio Finally I plan to release with this version codes. For each apk,I can provide update upto 99898 versions. Please provide your suggestions.

**APK 1:(Non ARCore version)**
218200101
...
...
218299999

**APK 2:(ARCore version)**
248300101
...
...
248399999

21 --> API level
01 --> Build flavor code
001 --> Major release
01 --> Minor release

Allocated Flavor Code ranges:
01-10 --> Flavors for Uses features
11-30 --> Flavors for Screen size
31-50 --> Flavors for Screen density
51-70 --> Flavors for CPU architectures
71-80 --> Flavors for Uses features
81-99 --> Flavors for Uses features

**Comment by rramprasad** [comment]
Oh! After lot of analysis I understand,there is no need to pre-define build-variant code(flavor code).We can order it at the time of each release. Here I have provided release scenarios.

**Release 1:**
    

> 1) 210100101  Vuforia
> 2) 240200101  ARCore

_Description : First release apps with only two flavors_

**Release 2:**
    

> 1) 210100102 Vuforia
> 2) 240200102 ARCore

_Description : Again provide update to apps with only same two flavors_

**Release 3:**
> 1) 210100103 Vuforia
> 2) 240200103 ARCore

_Description : Again provide update to apps with only same two flavors_

**Release 4:**
    

>     1) 210100104 Vuforia-ARMv7
>     2) 210200104 Vuforia-ARMv8
>     3) 210300104 Vuforia-x86
>     4) 210400104 Vuforia-x86_64
> 
>     5) 240100104 ARCore-ARMv7
>     6) 240200104 ARCore-ARMv8
>     7) 240300104 ARCore-x86
>     8) 240400104 ARCore-x86_64

_Description : Split APK based CPU and 2 Flavors(Vuforia & ARCore).Then Provide update to existing users_

**Release 5:**
    

>        210100105 Vuforia-ARMv7-mdpi
>        210200105 Vuforia-ARMv7-hdpi
>        210300105 Vuforia-ARMv7-xhdpi
>        210400105 Vuforia-ARMv7-xxhdpi
>        210500105 Vuforia-ARMv7-xxxhdpi
> 
>        210600105 Vuforia-ARMv8-mdpi
>        210700105 Vuforia-ARMv8-hdpi
>        210800105 Vuforia-ARMv8-xhdpi
>        210900105 Vuforia-ARMv8-xxhdpi
>        211000105 Vuforia-ARMv8-xxxhdpi
> 
>        211100105 Vuforia-x86-mdpi
>        211200105 Vuforia-x86-hdpi
>        211300105 Vuforia-x86-xhdpi
>        211400105 Vuforia-x86-xxhdpi
>        211500105 Vuforia-x86-xxxhdpi
> 
>        211600105 Vuforia-x86_64-mdpi
>        211700105 Vuforia-x86_64-hdpi
>        211800105 Vuforia-x86_64-xhdpi
>        211900105 Vuforia-x86_64-xxhdpi
>        212000105 Vuforia-x86_64-xxxhdpi
> 
>        240100105 ARCore-ARMv7-mdpi
>        240200105 ARCore-ARMv7-hdpi
>        240300105 ARCore-ARMv7-xhdpi
>        240400105 ARCore-ARMv7-xxhdpi
>        240500105 ARCore-ARMv7-xxxhdpi
> 
>        240600105 ARCore-ARMv8-mdpi
>        240700105 ARCore-ARMv8-hdpi
>        240800105 ARCore-ARMv8-xhdpi
>        240900105 ARCore-ARMv8-xxhdpi
>        241000105 ARCore-ARMv8-xxxhdpi
> 
>        241100105 ARCore-x86-mdpi
>        241200105 ARCore-x86-hdpi
>        241300105 ARCore-x86-xhdpi
>        241400105 ARCore-x86-xxhdpi
>        241500105 ARCore-x86-xxxhdpi
> 
>        241600105 ARCore-x86_64-mdpi
>        241700105 ARCore-x86_64-hdpi
>        241800105 ARCore-x86_64-xhdpi
>        241900105 ARCore-x86_64-xxhdpi
>        242000105 ARCore-x86_64-xxxhdpi

_Description : Split APK based CPU,Screen Density and 2 Flavors(Vuforia & ARCore).Then Provide update to existing users_

I think is very scalable solution to maintain multiple APKs. Please provide comments, if any issues in this format.

**Comment by inio** [comment]
Sounds like you've got a handle on this.  Closing.
