### ISSUE TITLE
[BUG] ANDY Texture rendering problem : hello_ar_java

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [google-ar/arcore-android-sdk#231]
The **ANDY object** that I place on the scene doesn't have the green **texture** wrapping it. Instead it appears to be black.

![screen shot 2018-03-10 at 8 43 00 am](https://user-images.githubusercontent.com/26897680/37237973-27463dbe-2442-11e8-809a-eb44c3ca482f.png)

**Comment by jwmcglynn** [comment]
@SyamSundarKirubakaran Unfortunately this is a bug in the emulator system image, so it will take some time for a new version to roll out.  The error is related to calling `glGenerateMipmap` before `glUseProgram`, which happens in the HelloAR Java app but not the C version.

In the mean time, you can work around the error by modifying HelloAR Java's ObjectRenderer.createOnGlThread, moving the shader loading code to the top of the function:

```java
    final int vertexShader =
        ShaderUtil.loadGLShader(TAG, context, GLES20.GL_VERTEX_SHADER, R.raw.object_vertex);
    final int fragmentShader =
        ShaderUtil.loadGLShader(TAG, context, GLES20.GL_FRAGMENT_SHADER, R.raw.object_fragment);

    program = GLES20.glCreateProgram();
    GLES20.glAttachShader(program, vertexShader);
    GLES20.glAttachShader(program, fragmentShader);
    GLES20.glLinkProgram(program);
    GLES20.glUseProgram(program);

    ShaderUtil.checkGLError(TAG, "Program creation");
```

**Comment by inio** [comment]
@SyamSundarKirubakaran: I believe @jwmcglynn's comment above will resolve this.  If so, the sample code will be updated in the next release.

**Comment by bhaskard** [comment]
@SyamSundarKirubakaran may i know what is the os and phone model you using in the emulator, for me none of the emulator works

**Comment by jwmcglynn** [comment]
@bhaskard Any emulator phone model will work, but you'll need Android Studio 3.1 Beta and the Google APIs Intel x86 Atom System Image (Level 27, **Version 4**).

More details here: https://developers.google.com/ar/develop/java/emulator

**Comment by bhaskard** [comment]
@jwmcglynn im using android studio 3.1 beta 4 , for me, while im trying to install the app, it simply says installing apk, even for ours, but nothing happens

**Comment by jwmcglynn** [comment]
@bhaskard Perhaps your application (or dependency) doesn't include x86 ABIs?  I recommend trying the HelloAR Java sample and see if that works for you.  Are you installing through Android Studio or installing the APK directly?

Could you attach the emulator's logcat output?

**Comment by inio** [comment]
with the 1.1 release the [sample code](https://github.com/google-ar/arcore-android-sdk/tree/master/samples) has been updated to work around this issue.
