### ISSUE TITLE
Question regarding object tracking / scene recollection

### ISSUE THREAD

**Issue by eugenepeh** [google-ar/arcore-android-sdk#232]
Hello arcore team,

Hope you wouldn't mind me asking a few questions regarding the tracking implementation.

- For the current `Trackable` implementation, is it base on Camera's knowledge of its current position and make the necessary adjustment? Hence if I place an Android on a plane created top of a checker board, the Android won't follow the checker board position?

- Is it possible for the current API to reload a past `Trackable`? 
E.g. I formed a plane in this instance -> I close the app -> I try to find (using feature vectors or descriptors) and get back the old plane again (and attach all the old anchors to it).

- Is it possible to create a `Trackable` programmatically too?

Thank you

**Comment by inio** [comment]
* Trackables are based on scene knowledge, including the estimated trajectory of the camera through the scene.  Anchors created from just a pose will be attached to the estimate of the camera's position around the time of their creation.  Anchors attached to a plane combine that with our current estimate of the plane's position.

* Not yet.  See #94 

* Not really.  All our classes have protected constructors to allow subclassing, but that's only for creating fake/mock instances for unit tests of your application code.
