### ISSUE TITLE
"Item not found." when installing ARCore in some regions/countries

### ISSUE THREAD

**Issue by parchebafieh** [google-ar/arcore-android-sdk#233]
Despite having a supported device for release 1.0, ARCore still fails to run on Samsung S8.

Running any of the sample java projects, such as hello_ar_java, yields a dialog notifying that the application needs the latest version of ARCore. When you click continue, you get a "Item not found. Retry" prompt. Seems the required ARCore service or APK isn't fully accessible for this supported device.

My device finger print:
samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQK7:user/release-keys

**Comment by esanchos** [comment]
Having same issue on my Motorola X-Play (XT1563) Android 7.1.1

**Comment by inio** [comment]
@parchebafieh That's really odd.  Could you capture a logcat from roughly the time the "latest version of arcore" dialog shows up through to getting the not found error?   Also could you grab a screenshot of the Play Store after searching for "ARCore"?

@esanchos That's expected because that device is not supported.  Feel free to make a post over on #89.

**Comment by parchebafieh** [comment]
@inio Thanks for prompt response.

[logcat.txt](https://github.com/google-ar/arcore-android-sdk/files/1805977/logcat.txt)
![index](https://user-images.githubusercontent.com/9012108/37329148-790d6524-2694-11e8-8fca-fa7900152d48.jpg)

**Comment by inio** [comment]
@parchebafieh One more thing to try: go to https://play.google.com/settings and uncheck the "show in menus" button for any devices that do not support ARCore.  If you don't have any devices listed there besides the S8 we're all ***really*** confused.

**Comment by parchebafieh** [comment]
@inio  Thank you for providing debugging options and specially the first one, I should have guessed what the problem was. We have been experiencing such issues with lots of services on the internet because of political issues. Now the problem is obvious to me, I am in Iran and by clicking on the link you provided, I would be able to see "This item is not available in your country". 

Is there a way to get rid of such rules? 

Thank you very much

**Comment by inio** [comment]
"ARCore is not available in your country.  Sorry :(.

If you're able to acquire an APK by other means and want to ensure it is authentic, we recommend first side-loading [the DP2 release](https://github.com/google-ar/arcore-android-sdk/releases/download/sdk-preview2/arcore-preview2.apk) and then installing the 1.0 build you found as an upgrade over that."

**Comment by inio** [comment]
This behavior should be improved substantially in the latest versions of Play Store.
