### ISSUE TITLE
Why the translation vector of the Anchor's 4x4 matrix always equal to 0 ?

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#237]
When I do :

myAnchor.anchor.getPose().toMatrix(mAnchorMatrix, 0);

I always get a mAnchorMatrixwith a (0,0,0) translation vector (3 first elements of the last column) like this :

###### logMatrix
0.9967071        ////         6.9189655E-18      ////      -0.08108628    ////       0.0
-4.135903E-25    ////      1.0                ////                 8.532843E-17   ////     0.0
0.08108628      ////         -8.5047455E-17     ////     0.9967071      ////         0.0
-0.17856228       ////       -0.9754161          ////         -1.0488315       ////      1.0

I don't understand why. The translation vector should not be (0,0,0) and should correspond to the position of my Anchor in the world space. No ?

What is really strange is that my droid robots (I use the ARCore demo project) are correctly positioned....

May somebody explain what I miss ?

Thanks

**Comment by inio** [comment]
The matrix is returned in column-major order, so you need to transpose it from what you have above.

**Comment by RegisAG** [comment]
THanks !!!!
