### ISSUE TITLE
Does Galaxy S8 supports ARcore

### ISSUE THREAD

**Issue by bhaskard** [google-ar/arcore-android-sdk#240]
Does Galaxy S8 supports ARcore? I am planning it for testing my AR based app

**Comment by RegisAG** [comment]
Yes. https://developers.google.com/ar/discover/#supported_devices

**Comment by inio** [comment]
Note: some models (like the SM-G950O) are not currently supported.  These models are mostly China-specific, where ARCore is not yet generally available due to restricted/no access to the Play store.

**Comment by inio** [comment]
It should be.  all the SM-G950F* devices have the same camera/IMU and report the same device fingerprint.  If it turns out to not run, that's a bug we should fix.
