### ISSUE TITLE
ARCore may not function properly on some devices when extremely hot

### ISSUE THREAD

**Issue by yoavgrosswild** [google-ar/arcore-android-sdk#242]
The screen stays black as an exception occurs inside onDrawFrame on 
Frame frame = session.update();
Also the device camera cannot be opened.
This correlates with the device being very hot. 
Only reboot solves this problem, until next cycle.

device is Galaxy S7 SM-G930F with Nougat 7.0

**Comment by inio** [comment]
Sorry, this one slipped through the cracks.  If you're still seeing this issue, could you provide a logcat capture?

**Comment by Nodjo** [comment]
I'm experiencing the same behaviour on a SM-G935F with Android 7.0

I'm attaching the crashlog


[helloar_crashlog_hot_device.log](https://github.com/google-ar/arcore-android-sdk/files/1895389/helloar_crashlog_hot_device.log)

Look for:
04-10 19:01:48.827 16363-17255/com.google.ar.core.examples.java.helloar A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 17255 (C2N-dev-looper)

**Comment by inio** [comment]
Reopening as we had a similar report on the Unity board.

**Comment by RegisAG** [comment]
Any update concerning this problem ? Note that according to my Android Vitals dashboard, this crash happens almost only on: Galaxy S7 Edge (hero2lte) (47.3% of the crashes), Galaxy S7 (herolte) (42% of the crashes), Galaxy S7 (heroltebmc) (2.2% of the crashes) => 90% of the occurences of this crash happen on S7 (running Android 7.x). Do you plan to fix this problem ? The S7 represents 20% of my installs and thus crash has a bad influence on my rating.

**Comment by inio** [comment]
If your app's performance requirements exceed that of some devices you can use the Play Store console to block access to your app on those devices.

**Comment by fredsa** [comment]
This is in face quite possibly #291, so marking as a duplicate.
