### ISSUE TITLE
Java + C HelloAR Samples do not properly declare OpenGL ES dependency

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#247]
I don't see the following feature in the manifest of the ARCore demo project 👍 

<uses-feature android:glEsVersion="0x00020000" android:required="true" />

Should I add it ?

**Comment by inio** [comment]
Oops!  Good catch.  Our sample code should declare:

    <uses-feature android:glEsVersion="0x00020000" android:required="true" />

**Comment by inio** [comment]
Fixed in 05af7029a052b8546949910fbfede0ba460dfafd.
