### ISSUE TITLE
Unexpected requestInstall() behavior: does not throw exception on unsupported device

### ISSUE THREAD

**Issue by seanadkinson** [google-ar/arcore-android-sdk#248]
For an unsupported ARCore device, we are seeing that the user is prompted to install ARCore when we call `requestInstall()`, instead of throwing `UnavailableDeviceNotCompatibleException`.

Is this expected behavior?

When the user clicks Continue to install, they get an error "Item Not Found", with a button to Retry, which does nothing.

I can work around this issue by calling `checkAvailability()` beforehand, but if the device is not compatible, it seems like that exception ought to be thrown instead of prompting for install.

Behavior is different across devices.  On a Galaxy Tab A running Android 6.0, we did not see this behavior.  On a Samsung S6, we reproduced the "Item Not Found" error.

**Comment by inio** [comment]
1. AR-Required apps assume the device is supported.  The only supported distribution channel for ARCore apps at the moment is the Google Play Store.  [Properly tagged apps](https://developers.google.com/ar/develop/java/enable-arcore) will only be offered to supported devices.
2. AR-Optional apps should always check that `checkAvailability()` returns one of the `SUPPORTED_` codes before enabling/show user interface elements that could result in a call to `requestInstall()`.

**Comment by fredsa** [comment]
Sean, I just tested a Samsung S6, using the **[hello_ar_java](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/hello_ar_java)** Java project in this repo (but with minSdkVersion 21), and saw the `UnavailableDeviceNotCompatibleException` thrown by `requestInstall()` as expected.

Do you see the exception if you run **hello_ar_java** on that same device?

**Comment by inio** [comment]
@fredsa : that's caused by the API being too low.  requestInstall will start the install flow regardless of device on API≥24.

**Comment by seanadkinson** [comment]
Thanks for the info @inio.  I've deployed the `checkAvailability` solution, which is working fine now.  I can imagine the underlying internals of why I must do it this way, but when I wrote the code the first time and saw that `UnavailableDeviceNotCompatibleException` may be thrown from `requestInstall()`, I presumed that I could take one path through the code, instead of having two methods for checking support. 

Quick note on my use case, fwiw.  We have a video calling app, and we support remote AR when the device supports it.  There is no UI that can be shown/hidden before entering the call, because the AR elements are only available during the call.  And we can't wait until you are on a call to prompt for ARCore install, because you would end up leaving the phone call to install it.  So we call `requestInstall()` **before** starting a phone call (on all devices, supported or not).  At least that's what we were doing.  Now we use `checkAvailability()` before `requestInstall()` for the reasons mentions, but you can probably imagine the code is a little awkward when `requestInstall()` has that exception it may throw.

Anyway, thanks again... will close issue.
