### ISSUE TITLE
ArSession destroy takes about 5.5-7.5 seconds

### ISSUE THREAD

**Issue by dev4711** [google-ar/arcore-android-sdk#249]
Destroying a ArSession in C++ takes about 5.5-7.5 seconds.
For example when opening the C++ example app of ArCore, closing the app with the return button and directly starting the app again, the camera image takes some time to show up again and start tracking the environment.
In my own implementation I have two Activities. The first one is a main screen with a button to start the other Activity with the ArCore implementation. When I return back to the MainActivity I destroy the ArSession in the onDestroy of the ArCoreActivity. The MainActivity is shown directly but is frozen for the time(5.5-7.5 sec) of ArSession destroy. I cannot keep the session and just pause it because I need to have a clean session for the next time starting it.
Obviously I can do this in a separate thread but should this take that long?

**Comment by inio** [comment]
We're aware of this.  As you suggest, calling it on another thread is currently the best option.

**Comment by 01098996** [comment]
I want to switch ARCoreCamera to normal camera while calling ARSession_Destory on another asyn thread , but black screen occured  on my Pixel！

**Comment by inio** [comment]
@01098996 You can pause the session and starting use the camera immediately, then destroy the session in a separate thread.

**Comment by 01098996** [comment]
It is exactly what I have done. But it's black screen.

**Comment by inio** [comment]
@01098996 That's odd.  Please file a separate issue saying that you cannot use the camera immediately after pausing the session.  That is definitely supposed to work.

**Comment by inio** [comment]
This behavior is now documented.

**Comment by inio** [comment]
@01098996 Please open a separate issue for the black screen problem.

**Comment by 01098996** [comment]
@inio Ok!
