### ISSUE TITLE
Reducing onDrawFrame calls results in a jerky behaviour

### ISSUE THREAD

**Issue by Tostifrosti** [google-ar/arcore-android-sdk#253]
I was trying to cap my onDrawFrame by enclosing some draw calls with a boolean. This boolean will once per 1000/20 fps be set to true. I noticed that the camera results in a jerky behaviour instead of a stuttering behaviour. It feels like something in Session/Frame/Camera is caching the frame, so it will jump between the new and cached frame. Even the GLES20.glClear method doesn't seem to clear all buffers (just the current frame). 

Is there some other way to clear the screen/cache that I've missed? Or is this a bug/feature in ARCore?
Thanks in advance!

**Comment by inio** [comment]
OpenGL is built around the assumption of drawing the whole image every frame.  It assumes you will start by erasing the framebuffer, then drawing into it, then displaying the completed buffer.  If you wish to carry content forward between frames, you need to be more explicit: drawing it to an off-screen texture and then drawing that to the screen each frame.

**Comment by Tostifrosti** [comment]
Thanks for the quick reply. I'm familiar with OpenGL and know that the framebuffer needs to be cleared and filled before displaying it on screen. The situation here, is that OpenGL or ARCore isn't doing this correctly (somehow). 

My current approach: 

1. Clear frame (by `GLES20.glClear`)
2. Update Camera/Frame to get the newest Frame (by mFrame = mSession.update(); mCamera = mFrame.getCamera();)
3. Draw frame in buffer (by calling `mBackgroundRenderer.draw(mFrame);`)
4. Display buffer to screen (this will be done by OpenGL)

The problem here is that I get different versions of frames (old and new ones). This is why I get a jerky experience in the app. This only happens when I am capping the FPS tho. 

I hope this makes things more clear ;)

**Comment by inio** [comment]
What did you mean by "I was trying to cap my onDrawFrame by enclosing some draw calls with a boolean"?  If `onDrawFrame` gets called, you MUST fill the buffer before returning.  Returning from `onDrawFrame` without filling the current frame buffer can result in a previous frame being displayed.  To reduce your frame rate, just have onDrawFrame sleep for a while.

**Comment by Tostifrosti** [comment]
> Returning from onDrawFrame without filling the current frame buffer can result in a previous frame being displayed.

This solved my problem! I wasn't aware that the old buffer was used if the current buffer isn't filled.
Thank you so much for helping!
