### ISSUE TITLE
ARCore Required app cannot be installed, "Purchase options" popup

### ISSUE THREAD

**Issue by tehmaestro** [google-ar/arcore-android-sdk#254]
Hi. We have an existing app in the Play Store and we used the **ARCore Required** and `minSdkVersion="24"` options, to build a dedicated apk only for ARCore enabled devices.
 
The problem appeared on Samsung Galaxy S8, Android 8.0 . When ARCore is not installed, pressing `Install` on our app, in the Play Store, shows a blank popup titled Purchase Options. This means users cannot install our app. I would like to mention that our app is free and offers in-app subscriptions.

 Is there anything we could do? Is this a bug in ARCore, or Samsung Android 8.0 update related? Did anybody else encounter this issue? Thanks.

I would also like to mention that I've tried other ARCore Required apps, like Ikea's app, and the same thing happenned.

**Comment by inio** [comment]
We're aware of this issue and working to get it resolved ASAP.  The good news is that this should appear at most once per Google account - re-attempting the app download should work.

**Comment by inio** [comment]
Good news!  The confusing "purchase options" dialog should no longer appear.  We were able to make server-side changes to fix that.

Note: There may still be *minor* issues for users installing ARCore for the first time as part of installing an AR-Required app, such as the install button requiring two clicks.
