### ISSUE TITLE
Not available on Pixel 2 android 8.0.0

### ISSUE THREAD

**Issue by ThirdPrince** [google-ar/arcore-android-sdk#257]
I can't run the app on my Pixel 2, even though it should be compatible? 
 Snackbar make message please install ARCore 
Device:  Pixel 2 android 8.0.0

**Comment by inio** [comment]
What app are you trying to run?
What country/region are you in?  There's a couple countries in which ARCore is not currently available.
Why are you still on 8.0?  8.1 has been available for quite a while.

**Comment by ThirdPrince** [comment]
I  am trying to  run ARCore Android SDK v1.0.0 samples on my Pixel 2 .
 I am in Nanjing, China.
 I trying to upgrade my Pixel2 to 8.1,Can Pixel 2 available on  android 8.1 ？

**Comment by ThirdPrince** [comment]
Hi @inio ，
com.google.ar.core.examples.java.helloar E/ARCore-IS: Play Store install service could not be bound.
availability.isSupported() return false .
 run ARCore Android SDK v1.0.0 samples on my Pixel 2 .
Is this sdk not available in China ?

**Comment by inio** [comment]
@ThirdPrince At the moment, there is no official way to acquire ARCore in China.  We’ll be supporting ARCore in China on partner devices sold there—starting with Huawei, Xiaomi and Samsung—to enable them to distribute AR apps through their app stores.  But we haven't quite gotten to that point yet.

I'm trying to see if there's a way we can provide an APK for developers that imported supported devices, but this is not a decision that is up to me.  Beyond just the distribution hurdle, we don't support any phones sold in China today (even the S8 for example) for technical reasons related to launching 3rd party background processes, such as our device calibration database.

**Comment by ThirdPrince** [comment]
Hi @inio ，
Thanks a lot !

**Comment by inio** [comment]
Good news!  The APK for ARCore 1.1 has just been added to the [release page](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.1.0).
