### ISSUE TITLE
Will Frame.hitTest (float xPx, float yPx) return more than two results?

### ISSUE THREAD

**Issue by henry82421** [google-ar/arcore-android-sdk#264]
According to the introduction of `Frame.hitTest (float xPx, float yPx)`, intersections with detected scene geometry are returned, sorted by distance from the device. I am curious where HitResult will return more than two results. I think of the situation where only a feature point overlap a plane (is this possible?). After all, is it not possible that two feature points or two planes are simultaneously cast by the ray(Rays will be blocked by the first detected Trackable?)?

Thanks!

**Comment by inio** [comment]
A hit test may contain multiple plane hit results.   Right now I believe you'll only ever see one point cloud hit result, but in the future you could get multiple of those as well.

**Comment by inio** [comment]
Closing, feel free to reopen if my answer wasn't sufficient.
