### ISSUE TITLE
Difference between session.createAnchor() to place.createAnchoer()

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#265]
Hi,
Are there any differences, between the following options:
1. Anchor list
`ArrayList<Anchor> anchors = new ArrayList<>();`
`HitResult hit = frame.hitTest(tap).get(0);`
`anchors.add(hit.createAnchor());`
`// later when needed`
`anchors.get(0);`

2. Session
`HitResult hit = frame.hitTest(tap).get(0);`
`session.createAnchor(hit.getHitPose());.`
`// later when needed`
`session.getAllAnchors().iterator().next();`

3. Trackable (Plane or Point)
`HitResult hit = frame.hitTest(tap).get(0);`
`plane.createAnchor(hit.getHitPose());`
`// later when needed`
`plane.getAnchors().iterator().next();`

If `((Plane)hit.getTrackable()).isPoseInPolygon(hit.getHitPose()) == false` then option 3 is irrelevant, but other than that - is there a best practice distinguishing between the three options?

Thanks!

**Comment by inio** [comment]
Your first option is the only correct pattern to use.  Anchors and trackables may be garbage collected if the application does not hold references to them.

**Comment by itanbp** [comment]
@inio thanks!

**Comment by inio** [comment]
Oh, also, I re-read the subject and realized I never answered that question.

Scene.createAnchor() creates an anchor at a fixed point in space, but not referenced to any understanding of the scene.  Plane.createAnchor creates an anchor at a fixed point relative to a detected plane.  If the estimate of the plane's height changes, the anchor will update.
