### ISSUE TITLE
How to add bump map to 3d object in ar-core sample android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#266]
Iam using ar-core android sample.I want to add bump mapping to the 3d object how can i do that in the android sample?

**Comment by inio** [comment]
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.

**Comment by inio** [comment]
Duplicate of #52
