### ISSUE TITLE
Plane's Polygon vs Extents

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#267]
Hi,
I was trying to figure the differences between `plane.getPolygon()` to - `plane.getExtentX()` togheter with
`plane.getExtentZ()`.
I understand that the Extent size is always bigger than the polygon size.
Also I noticed that there are cases in which `plane.isPoseInPolygon(pose) == false`  but `plane.isPoseInExtents(pose) == true`.

This leads me to the question - what is the purpose of the `Polygon`? The `Extent` is bigger, so we can anchor virtual objects to a larger surface...

Thanks!

**Comment by inio** [comment]
The polygon provides an arbitrary (convex) shape, while the extents are always a rectangle.

**Comment by itanbp** [comment]
@inio can you please elaborate more? 
is the Extent rectangle size is *always* bigger than the Polygon size?
what is the difference between them? is there accuracy the same?
what are the considerations to use one option over the other?

Thanks!

**Comment by inio** [comment]
the extent rectangle is generated based on the polygon and always circumscribes (is larger than) it.

The rectangle is primarily offered as a simpler representation for applications that need information like "there's a surface here that's about this big".  If you're doing visualization or hit testing, always prefer the polygon if you can.

**Comment by itanbp** [comment]
@inio thanks!
