### ISSUE TITLE
Adding arbitrary objects to a scene

### ISSUE THREAD

**Issue by marnore** [google-ar/arcore-android-sdk#268]
Hi,

I would like to know how to add an object to a scene, e.g. in Hello AR example. So far 3D objects were added as anchors after a user taps the screen.
Now I want to add an object at say (0, 0, 0) and an another one at (10, 1, 10), so the user sees the objects without pressing anything. Also, the objects are properly updated when the user is moving the phone.

**Comment by inio** [comment]
Absolute coordinates in ARCore are meaningless.  What you can do is:

1. Wait for a plane to be detected
2. Create an anchor attached to that plane
3. Display objects relative to that anchor's position

**Comment by marnore** [comment]
Thanks for a quick reply. I will use your suggestion
