### ISSUE TITLE
Enabling ARCore documentation for C

### ISSUE THREAD

**Issue by gpx1000** [google-ar/arcore-android-sdk#269]
https://developers.google.com/ar/develop/c/enable-arcore <-- that's missing a few steps.  It details how to get the gradle dependency setup, however, doesn't detail how to get the c libraries, set the include directories, or link / package the c libs.

The C sample code is correct in that it does all these things.

**Comment by inio** [comment]
Thanks for the pointer, we'll look into it.

**Comment by gpx1000** [comment]
If it would help, might I also suggest the following:

Specify externalNativeBuild for cmake:
android.defaultConfig.externalNativeBuild.cmake {
  abiFilters.addAll("arm64-v8a", "x86")
  targets { "native-lib", "arcore" }
}

Add the library to your CMakeLists.txt:
add_library( arcore SHARED IMPORTED )
set_target_properties( arcore PROPERTIES
	IMPORTED_LOCATION ${CMAKE_CURRENT_SRC_DIR}/src/main/jniLibs/jni/${ANDROID_ABI}/libarcore_sdk.so
	INTERFACE_INCLUDE_DIRECTORIES ${pathToArCoreSDK}/arcore-android-sdk/libraries/include
)

do similar for ndk-build


Also, I humbly suggest modifying the hello-C-sample to not do target_include_directories( libname PRIVATE ).
Private has the effect that it only has visibility for the target libname.  Any consuming library would not see the include directory.  Interface (as shown in my example above) means that any consuming library would capture the include directory.  PUBLIC means both the target name and any library consuming gets that path defined.
So if any library outside of the target libname wants arcore header resolution, they'd only need to link against arcore (like so):
target_link_libraries( UberLibName arcore )
CMake will then resolve both the header includes and the library it is linking against without developer needing to know where it lives on the file system.  In addition, I recommend making glm a header only target so it can receive the same proper treatment (can be included in any consuming target more naturally).  The nice thing about this, is it better separates concerns in the build process (if someone updates glm/arcore, they only need to update the one glm/arcore target rather than hunting through all consuming libs).
To give a concrete example, I'd recommend changing the sample CMakeLists to this:

cmake_minimum_required(VERSION 3.4.1)

# Import the ARCore library.
add_library(arcore SHARED IMPORTED)
set_target_properties( arcore PROPERTIES
	IMPORTED_LOCATION ${CMAKE_CURRENT_SRC_DIR}/src/main/jniLibs/jni/${ANDROID_ABI}/libarcore_sdk.so
	INTERFACE_INCLUDE_DIRECTORIES ${pathToArCoreSDK}/arcore-android-sdk/libraries/include
)
add_library( glm INTERFACE )
set_target_properties( glm PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES ${ANDROID_NDK}/sources/third_party/vulkan/src/libs/glm
)

# This is the main app library.
add_library(hello_ar_native SHARED
           src/main/cpp/background_renderer.cc
           src/main/cpp/hello_ar_application.cc
           src/main/cpp/jni_interface.cc
           src/main/cpp/obj_renderer.cc
           src/main/cpp/plane_renderer.cc
           src/main/cpp/point_cloud_renderer.cc
           src/main/cpp/util.cc)

target_link_libraries(hello_ar_native
                      android
                      log
                      GLESv2
                      glm
                      arcore)

**Comment by gpx1000** [comment]
Also, while looking at the sample, there's a gradle bug:

task extractNativeLibraries() {
    doFirst {
        configurations.natives.files.each { f ->
            copy {
                from zipTree(f)
                into arcore_libpath
                include "jni/**/*"
            }
        }
    }
}

That's great if and only if it is run on a clean directory.  When the version of arcore gets updated, then the next time this is run it wont refresh the files already unzipped.
add this to have it extract every run (or use some logic to set it to false when a new version is ready):
extractNativeLibraries.outputs.upToDateWhen { false }

Also recommend adding the arcore_libpath to the deleted folders on project clean (project level build.gradle task clean).  This or the above suggestion would auto solve ensuring that the gradle java lib version is the same version that the c lib is linking against.

**Comment by claywilkinson** [comment]
This has been fixed in the current release.
