### ISSUE TITLE
How to publish an app that runs offline and offers AR to devices that support it?

### ISSUE THREAD

**Issue by Nodjo** [google-ar/arcore-android-sdk#270]
I want to publish an app which offers AR as an optional, nice-to-have feature. This app runs offline.

According to the Play Store documentation (https://developers.google.com/ar/distribute/), if I make AR optional, ARCore won't be installed automatically when my app is installed. Then when the user will use it, he will be offline without access to the Play Store.

I understand the Play Store does not offer apk filtering on a feature, so I don't see how I could easily publish two apks.

How can I achieve this?

**Comment by inio** [comment]
Reading the [Multiple APK Support page](https://developer.android.com/google/play/publishing/multiple-apks.html) it sounds like the Play Store *does* allow multiple APKs based on any `<uses-feature>` filters.

However, another option is to encourage the user to  install ARCore when they first launch the app, before they would use it.  Presumably users will typically launch apps shortly after installing them, while they still have connectivity.  You can call [`checkAvailability()`](https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk.html#checkAvailability\(android.content.Context\)) a couple times after your app launches (waiting a few seconds between calls) and if it returns`SUPPORTED_NOT_INSTALLED` or `SUPPORTED_APK_TOO_OLD` show a dialog something like:

> Hey, neat, this phone supports ARCore!  If you install it now you can $COOL_THING later, even if you're offline.
> [No thanks] [Install].

If you're doing this you can also skip the user education screen with [`ArCoreApk.requestInstall(activity, ArCoreApk.InstallBehavior.OPTIONAL, ArCoreApk.UserMessageType.USER_ALREADY_INFORMED)`](https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk#requestInstall\(android.app.Activity,%20boolean,%20com.google.ar.core.ArCoreApk.InstallBehavior,%20com.google.ar.core.ArCoreApk.UserMessageType\))

**Comment by Nodjo** [comment]
Sounds good. Thank you !

2018-03-29 19:17 GMT+02:00 Ian Muldoon <notifications@github.com>:

**Comment by inio** [comment]
Closing.  Feel free to reopen if something doesn't work as you expect.

**Comment by mr-gil** [comment]
This is not an option since the user have a restricted red, where only certain urls are available. what could be a solution for this?
