### ISSUE TITLE
Removed support for dualsim devices???

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#271]
On the release page (https://github.com/google-ar/arcore-android-sdk/releases) Samsung S8 SM-G950FD 
 is mentioned as ARCore SDK Preview/Supported Devices but this device was removed from the official ARcore supported devices list (https://developers.google.com/ar/discover/#supported_devices - March 29, 2018).

Note that some variants in this list are mentioned twice (e.g. SM-A520F, SM-A720F), maybe a typo?

In this list I did not find any dualsim supported device (maybe I overlooked something).

**Comment by inio** [comment]
Looking into this.  I'm fairly sure this was dropped from the web page because the dual sim devices and essentially the same, but I understand that could be confusing.

**Comment by lvonasek** [comment]
OK, after the page update on May 17, 2018. It is ok.
