### ISSUE TITLE
What happens when device becomes compatible with ARCore through update

### ISSUE THREAD

**Issue by nilsk123** [google-ar/arcore-android-sdk#272]
Hi,

We have an application published in the store which uses 2 APK's. An APK including ARCore for devices which have the camera.ar hardware requirement, and a legacy APK for devices that don't (which has a lower version number).

My question is, lets say a device has the legacy APK installed because it doesn't support ARCore (lets say galaxy s9). In the upcoming weeks s9 will become supported through an update in its device profile and ARCore apk. Will the device then detect that the currently installed version needs to be overriden, or do we then have to implement a new release in production with the same APK's (but higher version number) to force the device to recheck this condition.

**Comment by inio** [comment]
the Play Store should auto-update those apps to include ARCore support because a newer version (higher versionCode) is available.

**Comment by nilsk123** [comment]
Thanks for the fast reply! So to be clear, it will update to the higher versionCode APK even though this apk is part of a release that already has an APK installed.

**Comment by inio** [comment]
That's my expectation based on a quick read of the auto-update logic.  I'm double-checking with the Play Store team though, since that's really the "correct" behavior.

**Comment by nilsk123** [comment]
Awesome, thanks for picking this up.

**Comment by inio** [comment]
Play store confirms that it should work that way.
