### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by abbana** [google-ar/arcore-android-sdk#273]
Hi,

we are currently implementing in ios AR with front camera and focus, with that extent we would like to ask two feature request for the next release in arcore to be able to port the code on android devices as well:

- Front camera support
- Focus support

Thanks.

**Comment by inio** [comment]
Those are covered in FR #128 and (part of) #56 respectively.

**Comment by inio** [comment]
Whoops, #153 is the canonical camera control FR, not #56
