### ISSUE TITLE
Obj rotation

### ISSUE THREAD

**Issue by abbana** [google-ar/arcore-android-sdk#276]
Hi,

I think I missed an important concept and I need an help to figure it out, hopefully it is not a bug.

In HelloArActivity.java , once the ObjectRendered.java is called the object is correctly displayed in the coordinate space, but the rotation of if is fixed ot the time it was at the starting of the session, facing the camera at that time. This way tapping the screen at any time displays the obect in the correct position, but rotated. 

Questions:

- I am missing something, or I broke the code?
- Which variable contains this value?
- If it's just my mistake, how should I fix it?

Thanks a lot.

**Comment by inio** [comment]
The Android model included in the sample is setup facing a particular direction that results in the default orientation of anchors created from hit results working nicely.  If your objects are facing the wrong direction, you need to either rotate the geometry in the model file (rotate and bake the rotation before exporting) or apply an additional rotation to the pose of each anchor before computing the view matrix.  

Add (`angle` is the rotation in radians):

    static final Pose MODEL_FIXUP = Pose.makeRotation(0, sin(angle/2), 0, cos(angle/2))

Change the line:

        anchor.getPose().toMatrix(anchorMatrix, 0);

to

        anchor.getPose().compose(MODEL_FIXUP).toMatrix(anchorMatrix, 0);

Also, nice icon ;)

**Comment by abbana** [comment]
Thanks,

that solved my issue. You can mark it as resolved.
