### ISSUE TITLE
dublicate ApplicationID for Hello_AR_Java and ComputerVision example

### ISSUE THREAD

**Issue by ayaromenok** [google-ar/arcore-android-sdk#279]
at sdkhome/examplename/app/build.gradle
ApplicationID for ComputerVision example should be different from Hello_AR_Java example

**Comment by inio** [comment]
Good suggestion.  Thanks!

**Comment by inio** [comment]
Fixed in 05af7029a052b8546949910fbfede0ba460dfafd.
