### ISSUE TITLE
Google Pixel 1st gen always return AR is not supported

### ISSUE THREAD

**Issue by Xanvial** [google-ar/arcore-android-sdk#281]
Hello,

I'm working on creating an application that will support AR optional. Based on this documentation https://developers.google.com/ar/develop/java/enable-arcore#runtime, we need to add some check to get the info whether the device supports AR or not. Currently there's a bug after I update to new ARCore 1.1.0, on Google Pixel (2016) the availability.isSupported() always return false, and availability.isTransient() returns true, so it calls the function forever.

This is my changes on sample code, just to show toast if ar is supported or not
[AR_Optional.txt](https://github.com/google-ar/arcore-android-sdk/files/1870747/AR_Optional.txt)

Note that this issue doesn't happen if change the ARCore back to version 1.0.0
Is there any mistake on my code?

**Comment by inio** [comment]
1. What country are you in?  Do you have access to the Play Store?
2. Could you include a logcat capture starting at your first call to checkAvailability running for at least 10 seconds?

**Comment by Xanvial** [comment]
1. I'm on Indonesia, note that this issue didn't happen on S8 and on Pixel itself if I use aar from v1.0.0
2. attached log, the checkavailability is called after onCreate
[log_pixel.txt](https://github.com/google-ar/arcore-android-sdk/files/1874229/log_pixel.txt)

**Comment by inio** [comment]
Definitely something up there.  Looking into what might have changed between 1.0 and 1.1 in that code.  Thanks for the report.

**Comment by inio** [comment]
One more request to help debug this: 

Open a browser on the device and go to market://details?id=com.google.ar.core

1. Are there any errors about the app not being available?
2. What version is available?

**Comment by Xanvial** [comment]
Well something strange happen, after I restart the phone it now works. I'll close this issue for now and reopen if this happen again in the future.
Thanks for the help
