### ISSUE TITLE
[Documentation] Creating anchors not currently visible

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-android-sdk#285]
As the title says, what happens when an anchor is created out of the view of the camera? I assume that at the moment of the creation, ARCore would save the visible feature points along with the anchor position, in able to adjust that later. But if there are no feature points, that would not be possible. But there is no information in the documentation that the anchor position must be inside the the camera's frustum at the moment of creation.

**Comment by iBicha** [comment]
So, If I create an anchor behind the camera, would that anchor still work?

**Comment by inio** [comment]
It will work, but it may experience substantially larger adjustments and a less physically rigid position than an anchor created in the field of view.

**Comment by iBicha** [comment]
I see, thanks for the clarification. I will close this issue for now, feel free to reopen if relevant?
