### ISSUE TITLE
How to connect two anchors with a line?

### ISSUE THREAD

**Issue by McGuiser** [google-ar/arcore-android-sdk#288]
The user can currently place two anchors on the plane, but I would like to draw a line between two anchors that I have placed. What would be the best method to go about doing this?

**Comment by inio** [comment]
Well, there's two things to think about here:

There's two options, really:

1. **Scaled Object**

You can use code like [this `rotateBetween` method](https://github.com/inio/arcore-android-sdk/blob/32e29839fb0ecf68e406c16344fc5be979c530e3/samples/hello_ar_java/app/src/main/java/org/inio/arcore/compassdemo/MathHelpers.java#L17-L35) to compute a pose that rotates a fixed object to points towards another object, and then apply a non-uniform scaling based on the distance between the objects.

2. **Generated Geometry**

You'll need to transform one or more object-space points from each anchor into world space  and then draw the geometry in world space.  You can use [`Pose.transformPoint()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Pose.html#transformPoint\(float\[\]\)) for the first part.

**Comment by McGuiser** [comment]
Thanks for the help! I've successfully computed the pose for option 1 (Scaled Object).  Does ARCore provide a way to apply non-uniform scaling? I've tried getTransformedAxis, but it's not working the way I expected.

**Comment by inio** [comment]
Nope, ARCore's poses are rigid (no scaling at all).  You can create and combine a scaling matrix using the [android.opengl.Matrix](https://developer.android.com/reference/android/opengl/Matrix.html) methods.

**Comment by ywqyunshan** [comment]
I've computed for option2 . First. I set Pose.makeTranslation ,xrotae and zroate has computed  ;second . transformPoint , but it's not working the way I expected.
