### ISSUE TITLE
ARCore only support .obj format now, will it support .fbx format in the furture?

### ISSUE THREAD

**Issue by TinoGuo** [google-ar/arcore-android-sdk#29]

**Comment by nathanmartz** [comment]
HelloAR is just a sample app and our goal is to keep it as simple as possible. We don't have plans to add more complex file formats, but there are plenty of online resources for parsing fbx.

**Comment by xiaowu4** [comment]
Hwllo, do you know how to load the .fbx file?

**Comment by dotMorten** [comment]
I recommend looking at "assimp" which can read most formats. I have successfully used that with my Xamarin Port of ARCore ( in combination with Urhosharp )
