### ISSUE TITLE
CPU Frame Size of the New ARCore 1.1 is only 640 X 480

### ISSUE THREAD

**Issue by WissamElkadi** [google-ar/arcore-android-sdk#293]
Hi
Can I get 1280 X 720 frame size from the new ARCore 1.1 ArFrame_acquireCameraImage ?

Cheers,
Wissam

**Comment by inio** [comment]
This is the primary reason I haven't closed #92 yet.  This ties in with #153.

**Comment by inio** [comment]
Duplicate of #153
