### ISSUE TITLE
Best practice to place an object at the user's feet

### ISSUE THREAD

**Issue by Nodjo** [google-ar/arcore-android-sdk#295]
Hi,

I need to place an object that's always 1 meter below the camera. So compared to the camera, x=0, y=-1, z=0. I need the object's rotation to remain consistent with the world.

The way I've achieved this is by creating a new anchor (as I can't change an existing anchor's pose) in onDrawFrame and I'm wondering if this is a good idea performance-wise, or if there's a better way of achieving this.

    override fun onDrawFrame(gl: GL10) {
   
            (...)

            if (anchor == null) {
                anchor = session!!.createAnchor(
                        frame.camera.pose
                                .compose(Pose.makeTranslation(0f, -1f, 0f))
                                .extractTranslation())
            } else {
                val currentPose = anchor!!.pose
                val translation = floatArrayOf(frame.camera.pose.tx(), frame.camera.pose.ty() - 1, frame.camera.pose.tz())
                val rotation = floatArrayOf(currentPose.qx(), currentPose.qy(), currentPose.qz(), currentPose.qw())
                val newPose = Pose(translation, rotation)
                anchor = session!!.createAnchor(newPose)
            }
            if (anchor!!.trackingState == TrackingState.TRACKING) {
                // Get the current pose of an Anchor in world space. The Anchor pose is updated
                // during calls to session.update() as ARCore refines its estimate of the world.
                anchor!!.pose.toMatrix(anchorMatrix, 0)

                // Update and draw the model and its shadow.
                virtualObject.updateModelMatrix(anchorMatrix, scaleFactor)
                virtualObject.draw(viewmtx, projmtx, colorCorrectionRgba)
            }
            (...)

    }

Thanks

**Comment by inio** [comment]
You don't need an anchor if you're using the camera's position each frame.  just

    static const Pose AT_FEET_OFFSET = Pose.makeTranslation(0, -1, 0)
    ...
    thingPose = camera.getPose().extractTranslation().compose(AT_FEET_OFFSET)

If you actually want to position it at the user's ***feet*** (on the ground) your best bet is to use plane detection and look for a large plane that is roughly 1-2 meters below the camera position.

**Comment by Nodjo** [comment]
You're right, your solution works. Thank you

**Comment by zaid13** [comment]
@Nodjo  can you plase share the code
