### ISSUE TITLE
it says > Your app's minSDKVersion must be 19 or higher. but it isn't working in any way

### ISSUE THREAD

**Issue by Gamezpedia** [google-ar/arcore-android-sdk#3]

**Comment by jguomoto** [comment]
The minimum API version of the arcore_client.aar is 19, but ARCore requires minimum API level 24 to run. This is to support applications that only partially uses ARCore functions.

**Comment by Gamezpedia** [comment]
so it means we can't use it with 6.1 || 23 versions ?

**Comment by jguomoto** [comment]
That's correct, it has to be on Android N (24) or above.
