### ISSUE TITLE
CPU access to camera frame data

### ISSUE THREAD

**Issue by tangobravo** [google-ar/arcore-android-sdk#30]
I want to run other image processing on the frame (ideally just the Y plane) and combine it with the ARCore tracking data. I'm happy to let ARCore control all the camera settings, but would just need an API to get a CPU-accessible pointer to the raw frame data.

Alternatively if there's a quick way to read back or access the SurfaceTexture on the CPU, then that would work too - any pointers appreciated. I assume the internal format of the data is some sort of YUV so rendering with OES_EXTERNAL (with implicit RGB conversion) to a framebuffer, and then reading back, feels like a lot of overhead when I just want the Y plane.

I've been after a low overhead synchronous camera->cpu->gpu pipeline for a long time on android:
https://stackoverflow.com/questions/37510487/lowest-overhead-camera-to-cpu-to-gpu-approach-on-android/37513328

It seems like HardwareBuffer added in Android O may be the best way to solve this in general, but as ARCore currently runs on Android 7 I assume you're not using that (or using it as a private API).

On iOS ARKit the ARFrame structure contains access to the YUV camera frame data. In general I've noticed ARCore and ARKit offer very compatible functionality, but this is one area I've found where ARCore is lacking.

**Comment by nathanmartz** [comment]
Thanks for the feedback and the detail on your use case. I've passed the feedback on to the ARCore SDK team.

**Comment by tangobravo** [comment]
Thanks. It would also be good to break up the Update function into a "process frame" and "upload texture" so my CPU-side processing could go on in the middle.

**Comment by inio** [comment]
On your second point, the "upload texture" is actually done by the camera so you can't process the data before it becomes a texture.  See [SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture.html).

**Comment by tangobravo** [comment]
SurfaceTexture is just one way of using the Camera API. It's possible to use an [ImageReader](https://developer.android.com/reference/android/media/ImageReader.html) as the destination for camera frames and then pass it on to a SurfaceTexture via an [ImageWriter](https://developer.android.com/reference/android/media/ImageWriter.html) (which will give a synchronous pipeline without copying the frame data, I believe). If that's what ARCore is doing then I'd like to have access to the buffer in the middle of that pipeline.

It could be that all the ARCore processing is on the GPU, although the use of point clouds suggests it's not a dense algorithm, so probably difficult to implement with OpenGL ES. ARCore could be using some other GPU compute API - I haven't explored the current state of GPU compute on android devices because I know it's far from universal at this point, but SurfaceTexture seems the wrong abstraction for processing data anyway due to the implicit colour conversion it involves.

**Comment by daranguiz** [comment]
@tangobravo Did you come across any reasonably quick way of accessing the SurfaceTexture from the CPU? glReadPixels() is the obvious one, but it's taking extremely long on my Pixel (ie 700ms per frame).

**Comment by tangobravo** [comment]
I haven't had time to dig into it yet I'm afraid. The route I'd aim for first, which I think may be the fastest way if it works, would work would be to allocate some memory that can be accessed both by GPU and CPU, declare it as a one-component texture via EGLImage and render to it as a framebuffer. Then on the GPU do the colour-conversion back to greyscale, render to that framebuffer, do the required (?) synchronization, and access the data on the CPU directly.

I think the Android 7 HardwareBuffer stuff combined with various GL extensions means this may actually be possible - HardwareBuffer allows allocating memory that can be accessed both by CPU and GPU (via EGLImage I believe) by setting the right flags.

Much work to do to try it out, but hope that gives a few pointers. If you do get that method or any other one working, it would be great to hear about it :)

And hopefully reading about the insane hoops I'm thinking about serves as more reason for Google to support a nicer way of getting to the data underlying a SurfaceTexture...

**Comment by tangobravo** [comment]
ps: My primary interest for SurfaceTexture readback is currently that's the only output supported in a ConstrainedHighSpeedCaptureSession, which gives a nice 60FPS preview on Samsung devices and isn't available through the ordinary CaptureSession that supports ImageReader.

For ARCore specifically the other approach is a bit of disassembly to see if ImageReader / ImageWriter is used internally and try to access it through reflection if so. Wouldn't be able to submit to Play Store with that but might allow experimentation during the beta phase.

**Comment by daranguiz** [comment]
Thanks! I'll report back and let you know if I can get your suggestions working. For something that feels like it should be so simple... wow. 

We're particularly interested in running additional computer vision techniques on top of ARCore. It doesn't need to be particularly fast, but it does need to be low latency. I've considered rewriting our code to use compute shaders, but that's yet another rabbit hole. Best to explore the simplest rabbit hole first (or what looks like it ought to be the simplest).

**Comment by daranguiz** [comment]
@tangobravo I ended up just using a PBO synchronously, bringing me down to an average 15ms delay. It's not the best, but it's workable. Thanks again!

**Comment by TheMachineHere** [comment]
@daranguiz I'm having lots of trouble using PBOs with ARCore. Do you by chance have your code open-source? Would help a lot. Been stuck on this for daays...

**Comment by daranguiz** [comment]
@TheMachineHere it's not open source unfortunately, I'm sorry :( My implementation is mostly based on this SO link though: https://stackoverflow.com/questions/28570710/android-opengl-es-3-0-pbo-instead-of-glreadpixels

**Comment by inio** [comment]
CPU pixel access is demonstrated in the [computervision sample code](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision)

**Comment by TheMachineHere** [comment]
@inio i keep getting null buffer from mTextureReader.acquireFrame(mFrameBufferIndex). 
Any ideas what could be the problem?

**Comment by harrywangwork** [comment]
@TheMachineHere Were you able to run the sample? What device did you use?
You will get null buffer if:
1. you did not call mTextureReader.create(...);
2. the mFrameBufferIndex was not a valid index returned from mTextureReader.submitFrame(...);
3. you did not call those functions from rendering thread.

**Comment by inio** [comment]
@TheMachineHere FYI, @harrywangwork wrote the `computervision` sample.

**Comment by TheMachineHere** [comment]
Thanks. I'm not exactly sure how it got fixed, but i went through a major overhaul of my OpenGL code and it started working lol. Thanks for your help tho :)
