### ISSUE TITLE
ARCore with VR dependency issues

### ISSUE THREAD

**Issue by erikist** [google-ar/arcore-android-sdk#300]
Hello! I would like to report a gradle dependency issue with ARCore:

Repro Steps:

1) Download `Just a Line` [source](https://github.com/googlecreativelab/ar-drawing-java) 
2) Add this dependency to your `build.gradle`
```
    implementation 'com.google.vr:sdk-videowidget:1.80.0'
``` 
3) Sync gradle and build the project

Observe: 
```
Program type already present: com.google.android.aidl.BaseProxy
Message{kind=ERROR, text=Program type already present: com.google.android.aidl.BaseProxy, sources=[Unknown source file], tool name=Optional.of(D8)}
```

**Comment by inio** [comment]
Can you test again after updating the ARCore dependency to 1.1?  This should be fixed.

**Comment by erikist** [comment]
I am getting it on `1.1` with the sample Just a Line project updated to use `1.1`

**Comment by erikist** [comment]
I can send you what I have, but all I changed (I believe, I _may_ have updated gradle) was the notation to not be Hungarian case and those gradle updates. I can confirm when I remove the `com.google.vr` dependency it works.

**Comment by erikist** [comment]
Hmmm, I will chalk it up to a gradle issue. I have synced and invalidated caches and restarted. I am experiencing this in a production app as well, but honestly, gradle is always doing weird things to me. I confirmed by cloning a fresh copy of my example project and it was fine. 👍 Thanks for your time, sorry to bug you with weird gradle issues.

**Comment by inio** [comment]
Thanks for the easy repro case.  Investigating.

**Comment by devbridie** [comment]
ARCore 1.21 doesn't ship `com.google.android.aidl.BaseProxy` anymore.
