### ISSUE TITLE
Errant model_mat definition in sample

### ISSUE THREAD

**Issue by gpx1000** [google-ar/arcore-android-sdk#301]
https://github.com/google-ar/arcore-android-sdk/blob/772bed8e2e1bc525a0d10441fa71168a9a87eb69/samples/hello_ar_c/app/src/main/cpp/plane_renderer.cc#L91

This variable is never used.  The class variable model_mat_ is used by both this function and the one following it.

**Comment by inio** [comment]
Good catch!

**Comment by inio** [comment]
Fixed in 05af7029a052b8546949910fbfede0ba460dfafd.
