### ISSUE TITLE
Feature Request: Integrate Custom Camera Module with ARCore

### ISSUE THREAD

**Issue by anujdutt9** [google-ar/arcore-android-sdk#302]
Hi,
I am working on a project in which I want to use ARCore with an external camera feed for it's AR tracking. I know ARCore uses camera along with other sensors to keep a track of the AR objects and mapping and to avoid drift.
So, for now, I can use the sensors from the phone itself but the camera feed comes from an external camera. I know that ARCore has fixed camera resolution etc. that it requires to maximize it's tracking ability. So, I can use the camera that provides the same resolution for that purpose as well.
My question is, Is this possible to do with ARCore or is there a possibility that we'll be able to do thing in the future releases of ARCore?
Thanks

**Comment by inio** [comment]
This is not possible with ARCore today, and not likely any time soon.  The camera module itself would need the inertial sensors.

**Comment by Thomas-Lettieri-IPS** [comment]
Can you integrate an external camera if you also include the required sensors (if so is there documentation)?

If you have sensor data and a video feed can you add AR?

**Comment by inio** [comment]
@Thomas-Lettieri-IPS Sorry, but we're focusing on delivering AR at scale for Android users.  Enabling custom devices would be a distraction from that effort.

**Comment by tunjid** [comment]
@inio Hello, is this on the cards for anytime soon? I'm really hoping to integrate Intel's realsense cameras as they have depth information and inertial sensors embedded in them.

**Comment by akash901** [comment]
@inio Hello, Is there any update on connecting external RGBD camera with IMU to ARCore ?

**Comment by MasterHansCoding** [comment]
I am facing a sensor issue as well, my phone doesn't have a Gyroscope, so I am building a module with IMU connected to my phone, and I want to change the source of the sensors used by the ARCore. 

Unfortunatly, the sensors and camera informations are given to this project through ar.core.Camera which is provided by a the downloaded app "Google Play for AR". 

So I guess we have to create our own library to get our customized ar.core.Camera :')
