### ISSUE TITLE
Incorrect return type for glGetuniform/attrib calls.

### ISSUE THREAD

**Issue by gpx1000** [google-ar/arcore-android-sdk#303]
https://github.com/google-ar/arcore-android-sdk/blob/772bed8e2e1bc525a0d10441fa71168a9a87eb69/samples/hello_ar_c/app/src/main/cpp/plane_renderer.cc#L69

These calls return a signed GLInt.  The time this matters is it will return a -1 when it can't find the uniform/attrib requested.
https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glGetUniformLocation.xhtml

**Comment by inio** [comment]
Thanks!  We'll look into getting this fixed as well.

**Comment by inio** [comment]
Fixed in 05af7029a052b8546949910fbfede0ba460dfafd.
