### ISSUE TITLE
No detection of vertical surfaces and super hot phone

### ISSUE THREAD

**Issue by DomDumont** [google-ar/arcore-android-sdk#305]
Hi,

I tried the HelloAR sample, the pixel (one) find horizontal surfaces without problem (floor/tables) but does not find any vertical surface (wall/screens/...).

And by the way after a 2 minutes run, the phone becomes really really hot. Is arcore too cpu expensive for the pixel ?

**Comment by inio** [comment]
From https://developers.google.com/ar/discover/concepts#environmental_understanding (emphasis mine)

> ARCore looks for clusters of feature points that appear to lie on common **horizontal surfaces**, like tables and desks, and makes these surfaces available to your app as planes. ARCore can also determine each plane's boundary and make that information available to your app. You can use this information to place virtual objects resting on flat surfaces.

New with 1.1 we've added [oriented points](https://developers.google.com/ar/discover/concepts#oriented_points) for hitTest, but that's only in response to hit tests.

The device getting hot is normal.  Doing this motion tracking takes a fair amount of compute power.  However, we're constantly trying to improve things in this regard.

**Comment by DomDumont** [comment]
Finally I got the Andy prefab spawned vertically ! It seems the detection is very sensible to lights. and I was also confused because there was no visual feedback for verticals planes. so you don't really know when the prefab is going to be spawned "vertically".
Thanks for your help.
