### ISSUE TITLE
GL Error aborts too early.

### ISSUE THREAD

**Issue by gpx1000** [google-ar/arcore-android-sdk#307]
https://github.com/google-ar/arcore-android-sdk/blob/772bed8e2e1bc525a0d10441fa71168a9a87eb69/samples/hello_ar_c/app/src/main/cpp/util.cc#L28

The for loop is appropriate; however, abort() has the effect of quitting out of the loop during the loop's body.

Try this:
void CheckGlError(const char* operation) {
    bool hasError = false;
    for (GLint error = glGetError(); error; error = glGetError()) {
        ERROR("after %s() glError (0x%x)\n", operation, error);
        hasError = true;
    }
    if(hasError) abort();
}

As written the code is the same as this:
if((GLint error = glGetError()))  {
ERROR("after %s()...");
abort();
}

**Comment by inio** [comment]
Thanks for pointing this out!

**Comment by inio** [comment]
Fixed in 05af7029a052b8546949910fbfede0ba460dfafd.
