### ISSUE TITLE
initialize ObjectRenderer caused  Screen block

### ISSUE THREAD

**Issue by scolar** [google-ar/arcore-android-sdk#308]
initialize ObjectRenderer in the method of onDrawFrame(GL10 gl) caused Screen block,the obj file size is 
10M

**Comment by inio** [comment]
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.  

It sounds like the OBJ file you're trying to load is quite large.  Our OBJ renderer only supports up to 32k unique vertices (unique position/texcoord/normal combinations).  Consider using Unity or Unreal if you're looking for more engine-level capabilities, and keep an eye on #52.
