### ISSUE TITLE
ArCore C library function ArSession_create() returns AR_ERROR_FATAL (-2)

### ISSUE THREAD

**Issue by HongkunWang** [google-ar/arcore-android-sdk#310]
Hi ARCore Team,
I'm using ArCore C library. The problem is that the C library function **ArSession_create()** returns **AR_ERROR_FATAL (-2)**, so that the AR session can not be created. In the Android logcat console, the error message is:

> **"com.omnigsoft.gameenginedemo E/third_party/arcore/ar/core/android/sdk/session_create.cc: Calling getMinApkVersion failed."**

I have add `<uses-sdk android:minSdkVersion="27" android:targetSdkVersion="27"/>` into AndroidManifest.xml file but it still report the same error.

More information: 
- I'm using Visual Studio 2015 to build my AR game prototype. To do this, I manually download "com.google.ar:core" AAR file from maven repositoty, then I manage to add "libarcore_sdk_c.so" and "classes.jar" file the app's APK package and there is no crash or class-not-found error.
- I'm able to run the ARCore sdk's hell_ar_c sample on my Pixel XL phone. The sample app is built by Android Studio.
- The code snippet is below, note that I try to create AR session with **NativeActivity**:
```
void GameEngineDemo::onCreate()
{
	ArSession* arSession = nullptr;	//AR Session

	//Get the Android activity reference by a global variable recorded in glue call-back function
	ANativeActivity* activity = _gloabl_android_activity; 

	//Get the JNI Env for the current thread
	JNIEnv* env = NULL;
	JavaVM* vm = activity->vm;
	int r = vm->AttachCurrentThread(&env, NULL);

	//Create AR session
	ArStatus status = ArSession_create(env, activity->clazz, &arSession);
	if (status != ArStatus::AR_SUCCESS)
		Application::printf(L"@@@@@@@@@@@@@@@ Failed to create AR session!, Result = %d", status);
	else
		Application::printf(L"@@@@@@@@@@@@@@@ Succeeded to create AR session!");

	// Detach env from current thread if it's not ANativeActivity's (i.e. different JNIEnv), otherwise application will crash
	vm->GetEnv((void **)&env, JNI_VERSION_1_6);
	if (env != activity->env) 
		vm->DetachCurrentThread();
	...
```
So what make **"Calling getMinApkVersion failed."** happen? 
Appreciate it for any suggestions.

**Comment by HongkunWang** [comment]
Not know how to delete this reported issue. 
I finally figured it out and manage to have the AR session created now.

**Comment by inio** [comment]
Issues can't be deleted, just closed.

If other people encounter this, you're not picking up the AndroidManifest.xml from the AAR properly.  It includes this metadata, which is critical for ensuring installation and updates are performed directly and that the API behaves as documented for the given SDK version.

**Comment by inio** [comment]
Reference:

https://developers.google.com/ar/develop/java/enable-arcore#dependencies

> Note: Gradle automatically merges additional tags from the ARCore library into your app's manifest. Do not delete these tags.
