### ISSUE TITLE
Problem with instant preview

### ISSUE THREAD

**Issue by dpacholczyk** [google-ar/arcore-android-sdk#312]
For some reasone instant preview just stopped working. I recently received an update on Samsung S8 to Android 8.0. When I try to run instant preview, Unity is just showing white background (instead of view from camera).

Beside that I receive: 
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.XR.ARBackgroundRenderer.DisableARBackgroundRendering () (at C:/buildslave/unity/build/Runtime/AR/ScriptBindings/ARBackgroundRenderer.cs:172)
UnityEngine.XR.ARBackgroundRenderer.set_mode (ARRenderMode value) (at C:/buildslave/unity/build/Runtime/AR/ScriptBindings/ARBackgroundRenderer.cs:109)
GoogleARCore.ARCoreBackgroundRenderer.Disable () (at Assets/GoogleARCore/SDK/Scripts/ARCoreBackgroundRenderer.cs:103)
GoogleARCore.ARCoreBackgroundRenderer.OnDisable () (at Assets/GoogleARCore/SDK/Scripts/ARCoreBackgroundRenderer.cs:66)

I've reinstalled arcore, instant preview, unity. Everything is in highest version

// UPDATE

I've noticed in the logcat that there is info about missing plugin:
04-15 16:44:40.185  4356  4411 E Unity   : Unable to find instant_preview_unity_plugin

// UPDATE 2
I've also noticed that the problem is related with the fact that in preview mode the code Frame.CameraImage.Texture in ARCoreBackgroundRenderer.cs returns null

**Comment by inio** [comment]
Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).

**Comment by Yaffa16** [comment]
Hey, 
I had the same issues, 
If you are using Instant Preview Input, 
add these lines to your code : 

#if UNITY_EDITOR
    // Set up touch input propagation while using Instant Preview in the editor.
    using Input = InstantPreviewInput;
#endif

This solved the "NullReferenceException: Object reference not set to an instance of an object
UnityEngine.XR.ARBackgroundRenderer.DisableARBackgroundRendering () (at ..." error for me.
