### ISSUE TITLE
[Instant App] Libraries not found

### ISSUE THREAD

**Issue by louisvalentin** [google-ar/arcore-android-sdk#315]
Hello,

I’m facing an issue when I’m trying to run AR Core (1.1.0) on an Instant App.

Errors occur only when I’m using the instant app (during the runtime). Otherwise, it is working well with the full version app.

After some researches, AR Core on Instant apps should be working ([https://github.com/google-ar/arcore-android-sdk/issues/83](https://github.com/google-ar/arcore-android-sdk/issues/83))

Phone: Samsung Galaxy S7 (SM-G930K)

For testing, I tried on AR Core sample projects:

- Hello_ar_java:

 

Error displayed: 

`Instant app: app.xxx.arcoreinstsantapp.app crashed: java.lang.UnsatisfiedLinkError: cmv[DexPathList[[zip file "/data/user/0/com.google.android.instantapps.supervisor/files/atom-cache/app.xxx.arcoreinstsantapp.app/1/feature.jar"],nativeLibraryDirectories=[/data/user/0/com.google.android.instantapps.supervisor/files/native-lib/app.xxx.arcoreinstsantapp.app/1, /system/lib, /vendor/lib]]] couldn't find "libarcore_sdk_jni.so"`

Information: The crash occurs when I’m initializing a new Session (com.google.ar.core.Session). In the public constructor of the class, the library named “arcore_sdk_jni’ is needed (but not found): `System.loadLibrary("arcore_sdk_jni");`

UPDATE: after trying on Samsung Galaxy S8 Plus (SM-955N), the bug only appears on Samsung Galaxy S7. AR Core on instant app with Samsung Galaxy S8 works pretty well.

- Hello_ar_c:

Error displayed:

`Instant app: app.xxxx.instandarcorecpp.app crashed: java.lang.UnsatisfiedLinkError: cmv[DexPathList[[zip file "/data/user/0/com.google.android.instantapps.supervisor/files/atom-cache/app.xxxx.instandarcorecpp.app/1/feature.jar"],nativeLibraryDirectories=[/data/user/0/com.google.android.instantapps.supervisor/files/native-lib/app.xxxx.instandarcorecpp.app/1, /system/lib, /vendor/lib]]] couldn't find "libhello_ar_native.so"`

- Computervision:

 

Error displayed: Not an error displayed in a specific location in my logs, but a “Google Play services for Instant Apps has stopped” dialog appears on my phone.

Am I the only one facing this issue? Could you tell me if there is a way to fix those errors?

If you need more information, feel free to ask.

Sincerely yours

**Comment by inio** [comment]
That's very odd that it works on the S8 but not S7.  We're investigating.

**Comment by inio** [comment]
Sorry, going through old bugs and it looked like nobody picked this one up.

Are you still seeing this?  If possible, could you provide a slightly more complete logcat?  There should likely be some complaints about a missing symbol around the `couldn't find "libhello_ar_native.so"`.  Also, do you know if the app is running in 32-bit or 64-bit mode on the S7?

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.

We've also added some [official docs for Instant apps](https://developers.google.com/ar/develop/java/instant-app).
