### ISSUE TITLE
Huawei P20 EML-AL00 unable to create the ARSession

### ISSUE THREAD

**Issue by 01098996** [google-ar/arcore-android-sdk#316]
I'm  run the hello_ar_c on Huawei P20. ArSession_create method always return NULL. System version is  8.1.0, ARCore APK is download from the Play Store.

Below is the log:

04-16 16:24:33.179 8352-8352/com.google.ar.core.examples.c.helloar E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
04-16 16:24:33.180 8352-8352/com.google.ar.core.examples.c.helloar E/Minikin: Could not get cmap table size!
04-16 16:24:33.190 1866-7381/? E/HsmCoreServiceImpl: onTransact in code is: 103
04-16 16:24:33.193 1721-1734/? E/ResourcesManager: failed to add asset path /data/app/com.google.ar.core.examples.c.helloar-UvC-f8OHZrpbQu-pdlFm9w==/base.apk
04-16 16:24:33.193 1721-1734/? E/ResourcesManager: failed to add asset path /data/app/com.google.ar.core.examples.c.helloar-UvC-f8OHZrpbQu-pdlFm9w==/base.apk
04-16 16:24:33.194 1721-1734/? E/ResourcesManager: failed to add asset path /data/app/com.google.ar.core.examples.c.helloar-UvC-f8OHZrpbQu-pdlFm9w==/base.apk
04-16 16:24:33.194 1721-1734/? E/ResourcesManager: failed to add asset path /data/app/com.google.ar.core.examples.c.helloar-UvC-f8OHZrpbQu-pdlFm9w==/base.apk
04-16 16:24:33.194 1721-1734/? E/ResourcesManager: failed to add asset path /data/app/com.google.ar.core.examples.c.helloar-UvC-f8OHZrpbQu-pdlFm9w==/base.apk
04-16 16:24:33.251 8335-8335/? E/Zygote: register_com_android_internal_os_Zygote num = 0
04-16 16:24:33.260 649-675/? E/AwareLog: iawared: getProcCpuset open /proc/8335/task/8380/cpuset fail errno(2)!
    iawared: getFileContent failed, errno = 2
04-16 16:24:33.280 8352-8352/com.google.ar.core.examples.c.helloar E/ActivityThread: Failed to find provider info for com.google.ar.core.services.calibrationprovider
04-16 16:24:33.280 8352-8352/com.google.ar.core.examples.c.helloar E/native: session_create_implementation.cc:208 Calling readDeviceProfile failed.
    session_create_implementation.cc:546 Failed to create calibration provider
04-16 16:24:33.280 8352-8352/com.google.ar.core.examples.c.helloar E/hello_ar_example_c: *** CHECK FAILED at /Users/Zxj/Github/arcore-android-sdk/samples/hello_ar_c/app/src/main/cpp/hello_ar_application.cc:93: ArSession_create(env, context, &ar_session_) == AR_SUCCESS
    
    --------- beginning of crash
04-16 16:24:33.280 8352-8352/com.google.ar.core.examples.c.helloar A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8352 (mples.c.helloar), pid 8352 (mples.c.helloar)
04-16 16:24:33.307 8384-8384/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'HUAWEI/EML-AL00/HWEML:8.1.0/HUAWEIEML-AL00/107(SP5C00):user/release-keys'
    Revision: '0'
    ABI: 'arm64'
    pid: 8352, tid: 8352, name: mples.c.helloar  >>> com.google.ar.core.examples.c.helloar <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
        x0   0000000000000000  x1   00000000000020a0  x2   0000000000000006  x3   0000000000000008
        x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   7f7f7f7f7f7f7f7f
        x8   0000000000000083  x9   9d5a103ffc7c07b1  x10  0000000000000000  x11  0000000000000001
        x12  ffffffffffffffff  x13  ffffffffffffffff  x14  ff00000000000000  x15  ffffffffffffffff
        x16  0000005937496fa8  x17  0000007b488721cc  x18  0000000017712358  x19  00000000000020a0
        x20  00000000000020a0  x21  0000007ac6ea3a00  x22  0000007fd7878e9c  x23  0000007aab5fcc76
        x24  0000000000000010  x25  0000007b4c1a3a40  x26  0000007ac6ea3aa0  x27  0000000000000004
        x28  0000000000000000  x29  0000007fd7878b00  x30  0000007b48827aec
        sp   0000007fd7878ac0  pc   0000007b48827b08  pstate 0000000060000000
04-16 16:24:33.308 8384-8384/? A/DEBUG: backtrace:
        #00 pc 000000000001db08  /system/lib64/libc.so (abort+104)
        #01 pc 00000000000462bc  /data/app/com.google.ar.core.examples.c.helloar-qbQ3Q68vlrtgBQCgSzieNw==/lib/arm64/libhello_ar_native.so (hello_ar::HelloArApplication::OnResume(void*, void*, void*)+316)
        #02 pc 000000000004de50  /data/app/com.google.ar.core.examples.c.helloar-qbQ3Q68vlrtgBQCgSzieNw==/lib/arm64/libhello_ar_native.so (Java_com_google_ar_core_examples_c_helloar_JniInterface_onResume+52)
        #03 pc 0000000000014950  /data/app/com.google.ar.core.examples.c.helloar-qbQ3Q68vlrtgBQCgSzieNw==/oat/arm64/base.odex (offset 0xf000)

**Comment by inio** [comment]
Ooops, look like you've discovered a bug in our supported devices list.  The China versions of the Huawei P20 isn't *quite* supported yet.  It should be soon though.

**Comment by inio** [comment]
FYI: the EML-TL00 is ***also*** not supported.  Both these models should disappear from the supported device list shortly.

**Comment by linjiangwei** [comment]
Not solved yet?
