### ISSUE TITLE
Multiplayer AR session without Unity

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#317]
Hey,
I'm curious to know are there any plans that ARCore will support multiplayer AR sessions?

I have seen an [example](https://www.youtube.com/watch?v=oNekBgognFE&feature=youtu.be&t=50m33s) of this capability by Unity, based on ARCore... but it's obviously requires working with Unity...

**Comment by inio** [comment]
Duplicate of #94

**Comment by inio** [comment]
This desire is definitely on our radar.  Unfortunately I can't comment about plans or timelines for unannounced features.
