### ISSUE TITLE
ArImage Formats

### ISSUE THREAD

**Issue by eddielong** [google-ar/arcore-android-sdk#321]
I'm using the C API to read back the camera image and have a few questions. It appears right now we get back and image 640x480 with a format of AIMAGE_FORMAT_YUV_420_888. I've noticed there are several other potential formats, RGBA888, RGBX888, RGB888, RGB555 and even JPEG.

My question is: what formats should I expect the ArImage to be in? Do I need to support the others? Is it reasonable to assume that the YUV image is to remain standard? Is 640x480 going to remain the size? This is good enough for me currently.

**Comment by inio** [comment]
For now, it will always be 640x??? in AIMAGE_FORMAT_YUV_420_888.  In the future we hope to allow more configuration of this.

The hight is variable based on the actual sensor geometry of the device.  Devices with 16:9 sensors will have a 640x360 image.

**Comment by inio** [comment]
This should be formally documented as of 1.3.
