### ISSUE TITLE
How to display model has more than one texture image?

### ISSUE THREAD

**Issue by tuzenvn** [google-ar/arcore-android-sdk#322]
I have one OBJ object and 5 texture images need to load on ARCore camera.
But the Demo #hello_ar_java have method create only one texture,

>  virtualObject.createOnGlThread(/*context=*/ this, "models/andy.obj", "models/andy.png");

Could you give me a guide?

**Comment by inio** [comment]
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.

Consider using Unity or Unreal if you're looking for more engine-level capabilities, and keep an eye on #52.

**Comment by inio** [comment]
Duplicate of #52

**Comment by itanbp** [comment]
@tuzenvn Take a look at [this ](https://github.com/JohnLXiang/arcore-sandbox/blob/0f8b22f222112768a91e944ee82a912e7d2eb46d/app/src/main/java/com/google/ar/core/examples/java/helloar/rendering/ObjectRenderer.java#L304) example, maybe it can help...
