### ISSUE TITLE
ARcore Render object without planning or touching (ANDROID STUDIO) 

### ISSUE THREAD

**Issue by Ahmednagyyy** [google-ar/arcore-android-sdk#325]
I Used the sample project which is awesome, But I want to do the following:

--> place the 3d object in specific Latlng with ( x, y, z ) for the real world positioning when I open the camera without touching or detecting the surface planning.

I made it with ARkit for IOS, but I can't with ARcore.
Couldn't understand the doc very well, I need to understand how it works and how to implement what I write above.

Thanks in advance

**Comment by inio** [comment]
ARCore does not yet provide absolute (latitude/longitude) coordinates.  #94 may provide a bit of what you're looking for.

**Comment by Ahmednagyyy** [comment]
@inio Well, I hope you add it soon.
But #94 couldn't help me enough , Now I want to add a 3d model object without surface planning I want to open the helloARactivity and see the object with , for example 

mAnchors.add(hit.getTrackable().createAnchor(
   hit.getPose().compose(Pose.makeTranslation(0, 0.2f, 0))));


want to understand how to do that

**Comment by inio** [comment]
ARCore provides device motion tracking and scene understanding tools, currently in the form of plane detection and hit testing.  It's up to developers to decide how to uses these tools.  Automatic placement of virtual content is a very application-specific behavior that requires knowledge of both  the scale of your content and the ways users will interact with it.
