### ISSUE TITLE
Rotate the virtual object around the Y axis to face the Camera

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#326]
Hi,
based on the `hello_ar_java` I'm trying to make the anchored virtual object to always face the `Camera`, giving the user the feeling the virtual object is always looking at him.

This is what I tried, it didn't work :)

In `HelloARActivity` I added:

```
float cameraDegree = camera.getPose().inverse().qy();
virtualObject.updateModelMatrix(anchorMatrix, scaleFactor, cameraDegree);
```

And in `ObjectRenderer` changed to:

```
public void updateModelMatrix(float[] modelMatrix, float scaleFactor, float angleDegrees) {
    float[] scaleMatrix = new float[16];
    Matrix.setRotateM(modelMatrix, 0, angleDegrees, 0, 1, 0);
    Matrix.setIdentityM(scaleMatrix, 0);
    scaleMatrix[0] = scaleFactor;
    scaleMatrix[5] = scaleFactor;
    scaleMatrix[10] = scaleFactor;
    Matrix.multiplyMM(this.modelMatrix, 0, modelMatrix, 0, scaleMatrix, 0);
}
```

What I'm missing? Thanks!

**Comment by thomasflynn** [comment]
Hi @itanbp , are you using GearVRf (http://gearvrf.org) for this as well?  If so, it sounds like you can use the GVRBillboard class for this.  If you open up an issue over there, Sushant can help you with it.

**Comment by inio** [comment]
If not, I've put up some sample code to [compute a rotation between two vectors](https://github.com/inio/arcore-android-sdk/blob/unsupported-geo-oriented/samples/hello_ar_java/app/src/main/java/org/inio/arcore/compassdemo/MathHelpers.java#L17-L35).

This could be used as (disclaimer: I haven't tested this code):

    static OBJECT_NATIVE_FAICING = [1, 0, 0]; // direction object faces in model
    
    float[] getPoseTranslation(Pose p) {
      float[] out = new float[3];
      p.getTranslation(out);
      return out;
    }
    
    ...
    
    float[] objectToCamera = getPoseTranslation(
        objectAnchor
            .getPose()
            .extractTranslation()
            .inverse()
            .compose(camera.getPose()));
    objectToCamera[2] = 0; // only consider x/z component of displacement
    
    Pose cameraFacingPose = objectAnchor.getPose().extractTranslation.compose(
      MathHelpers.rotateBetween(OBJECT_NATIVE_FACING, objectToCamera));

**Comment by inio** [comment]
@itanbp Cool.  Fixed the code above :).

**Comment by aurangzaibumer777** [comment]
> @itanbp Cool. Fixed the code above :).

can you send me compiled working solution for this?

thanks
