### ISSUE TITLE
Error with vertex values when using FloatBuffer.asReadOnlyBuffer on Android 7.0 devices

### ISSUE THREAD

**Issue by haroldmthyng** [google-ar/arcore-android-sdk#329]
Posting this here so it's logged someplace. This is a definite bug in the FloatBuffer class for Android 7.x devices. If you utilize the FloatBuffer.asReadOnlyBuffer method to access vertex or texture UV data, this method instead of providing a FloatBuffer that shares it's content as outlined, you WILL get incorrect floating point values if running on 7.0 and 7.1 devices.

I hit this issue implementing ray casting for object selection in OpenGL using generated bounding box collision for each object. That method works fine on Android 8.0 devices, but cost me over a week of development trying to hunt down this bug. Please generate a ticket to correct this asap.

This is the only article I found on the internet that referenced this issue. https://hub.jmonkeyengine.org/t/jme3-1-rendering-failure-specifically-for-android-7-nougat/39018/24 

I can verify this method returns incorrect results on Samsung S7, Samsung S8, Samsung Note8 and Asus Zenfone AR.

For anyone else that notices unpredictable behavior or rendering errors on 7.x devices versus 8.x, check if you're using FloatBuffer.asReadOnlyBuffer.

**Comment by inio** [comment]
Interesting!  Closing as it's not really an issue with ARCore per say, but thanks for pointing it out.

**Comment by haroldmthyng** [comment]
Np. I know this isn't the area for this ticket, but thanks for checking up on it.

**Comment by inio** [comment]
One thing that would be interesting to know:

I assume `ByteBuffer.allocateDirect().order(ByteOrder.NATIVE).asFloatBuffer().asReadOnlyBuffer()` is the problematic path.  I wonder if `ByteBuffer.allocateDirect().asReadOnlyBuffer().order(ByteOrder.NATIVE).asFloatBuffer()` is equally problematic.

**Comment by haroldmthyng** [comment]
Hmm. Hadn't tried that. Would be good to know if there's a difference there. If I get a chance I'll try it out.
