### ISSUE TITLE
how to pick obj in arcore?

### ISSUE THREAD

**Issue by scolar** [google-ar/arcore-android-sdk#330]
is frame.hitTest can pick obj in the scene?

**Comment by inio** [comment]
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine, and things such as hit testing virtual objects are not included.

Consider using Unity or Unreal if you're looking for more engine-level capabilities, and keep an eye on #52.

**Comment by inio** [comment]
Duplicate of #52
