### ISSUE TITLE
replacing the camera-/sensorfeed

### ISSUE THREAD

**Issue by ARPatrick** [google-ar/arcore-android-sdk#332]
I am working on an AR-app in which i would like to replace both the camera and sensor feed with a feed from another device like another phone or an OPi with compatible hardware. Related to this I need to find out what hardware (Camera, Gyroscopes etc.) could actually provide adequate data feeds for ARCore.
I have yet to find a way to implement any part of this. Tips on what to look into would be greatly appreciated, also if it is currently not possible to do this will it be possible in future updates?
Thanks in advance

**Comment by inio** [comment]
This is not possible.  We would need to calibrate the camera and IMU on the camera.

One option is to have two phones, run ARCore on one of them and stream video + poses to the other.  At the moment streaming video from an ARCore session will require drawing the texture into a GL context that is being captured.

**Comment by ARPatrick** [comment]
Thank you for the quick response.
Is it possible for me to calibrate the camera and IMU myself/hand of that calibration to ARCore?
Also if i were to run android and ARCore on a pi board what hardware specifications will be enough to provide the necessary data.

**Comment by inio** [comment]
Doing your own calibration is not possible at this time.

**Comment by 95lazyass19** [comment]
Hey can you please explain how to stream the arcore session in detail.
Thanks

**Comment by LeoAtreides** [comment]
Why i sdoing your own calibration not possible ? At the lowet level this is nothing different that what a hardware integrator has to do to get the front camera onto the phone. How can it be so that if you write your own kernel level driver support that this would not be possible ?
