### ISSUE TITLE
ARCore 1.1 is missing x86_64 jni binary

### ISSUE THREAD

**Issue by eddielong** [google-ar/arcore-android-sdk#333]
I'm unable to build my app which targets armeabi-v7a, arm64-v8a, x86, x86_64 when ARCore is enabled. I'm using the same gradle setup as the C-based sample app, i.e.
```
task extractNativeLibraries() {
    configurations.natives.files.each { f ->
        copy {
            from zipTree(f)
            into arcoreLibpath
            include "jni/**/*"
        }
    }
}
```
I then link in my MK file in the same way as the sample apps. 

I've looked in the `.gradle/caches/modules-2/files-2.1/com.google.ar/core/1.1.0/c5b36916aedefc034d6edc22a3663c4ab2fd86a0` and unzipped the downloaded ARCore aar I find there and can only see 3 architectures in there:

```
➜  pwd
~/.gradle/caches/modules-2/files-2.1/com.google.ar/core/1.1.0/c5b36916aedefc034d6edc22a3663c4ab2fd86a0/core/jni
➜  jni ls -al
total 0
drwxr-xr-x  5 eddielong  staff  160 19 Mar 09:15 .
drwxr-xr-x  9 eddielong  staff  288 24 Apr 14:08 ..
drwxr-xr-x  4 eddielong  staff  128 19 Mar 09:15 arm64-v8a
drwxr-xr-x  4 eddielong  staff  128 19 Mar 09:15 armeabi-v7a
drwxr-xr-x  4 eddielong  staff  128 19 Mar 09:15 x86
```

Am I missing something?

**Comment by eddielong** [comment]
I've modified the build.gradle task to work around this:

```
task extractNativeLibraries() {
    configurations.natives.files.each { f ->
        copy {
            from zipTree(f)
            into arcoreLibpath
            include "jni/**/*"
        }
        copy {
            from arcoreLibpath + "/jni/x86"
            into arcoreLibpath + "/jni/x86_64"
            include '**'
        }
    }
}
```
However this is just so I can build right now, I'm pretty sure this is a really bad thing to do.

**Comment by inio** [comment]
That might make it build but it won't run.  You could also dump an empty .so in there as long as you're using the Java API.  Our calibration only exists for the x86 emulator, so ARCore won't run on a x86_64 emulator image.

**Comment by devbridie** [comment]
ARCore now includes `x86_64` in the AAR.
