### ISSUE TITLE
running ARCore on a Pi

### ISSUE THREAD

**Issue by ARPatrick** [google-ar/arcore-android-sdk#335]
Related to the issue #332 I would like to know what hardware would be required to run ARCore on a Pi.
It is obviously not a 'supported device' but since i can equip my board with newest hardware this should issue should be minute.
More input on the matter would be very welcome and thanks again for your continued feedback.

**Comment by inio** [comment]
The required hardware components are a camera with a reasonably wide field of view and a 6-axis IMU.  However, you also need drivers that provide roughly millisecond accurate timing for everything (including exposure and rolling shutter) and finally (and most challenging) a calibration of all these pieces.  The last bit is the part that's just not going to happen.
