### ISSUE TITLE
arcore v1.1 in ue4.19

### ISSUE THREAD

**Issue by belko-vasiliy** [google-ar/arcore-android-sdk#336]
I use arcore plugin in unreal engine 4. I used your quickstart guide for it. And when I was using arcore v1.0 in ue4.18, it was OK with everithing, but when I tried arcore v1.1 in ue4.19, it wasn't. So I don't know why arcore v1.1 in ue4.19 doesn't work on samsung s7e sm-g93
[Log.txt](https://github.com/google-ar/arcore-android-sdk/files/1950166/Log.txt)
5fd.

**Comment by inio** [comment]
I suspect you noticed this already but for anyone else that lands here: Please post issues with the Unreal integration on the [google-ar/arcore-unreal-sdk issues board](https://github.com/google-ar/arcore-unreal-sdk/issues).
