### ISSUE TITLE
frame.acquireCameraImage() vs GLES20.glReadPixels()

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#337]
Hi,
I would like to understand the advantages of using `frame.acquireCameraImage()` comparing to `GLES20.glReadPixels()`.

So the first option is:
```
Image image = frame.acquireCameraImage();
ByteBuffer input = image.getPlanes()[0].getBuffer();
```

The second:
```
@Override
public void onDrawFrame(GL10 gl) {

        final int pixelData[] = new int[mWidth * mHeight];

        // Read the pixels from the current GL frame.
        IntBuffer buf = IntBuffer.wrap(pixelData);
        buf.position(0);

        // this line must be on the GLThread
        GLES20.glReadPixels(0, 0, mWidth, mHeight, GLES20.GL_RGBA, GLES20.GL_UNSIGNED_BYTE, buf);
}
```

**Comment by inio** [comment]
the `glReadPixels` approach will be much higher overhead and incur either extremely poor GPU utilization or a one-frame lag (the sample takes the lag approach), but offers an image with up to the full 1080p texture resolution. 

the `acquireCameraImage` approach has virtually zero overhead and returns an image that matches the current camera frame, but is limited to providing a 640x480 or 640x360 YUV 4:2:0 image for now.  In the future we hope to increase the resolution offered.
