### ISSUE TITLE
Anchor virtual object before Plane detection

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#338]
Hi,
I played with Google's AR Sticker app and tried to examine the virtual object anchoring logic, and I was pretty amazed :)
Look at [this](https://www.youtube.com/watch?v=KkirM4D9W88) video, my steps were:
1. I opened the camera app when the device was already pointed at the ceiling
2. I navigated to the AR Stickers tab
3. selected a virtual object, and drop it at an arbitrary point in the space, not attached to any Plane
4. the app shows a toast indicating it didn't succeed to detect a Plane
5. Stormtrooper fell to the floor, notice the shoes looks exactly above the floor

My question is, although the slight drifting when I was moving, it looks like the app has a very good estimation of the floor height, **before the `Plane` is detected**. Did I understand right? General speaking, how can this be achieved?

**Comment by inio** [comment]
They may be updating the object to a plane that appears below it, or using point cloud hit tests.

**Comment by itanbp** [comment]
@inio with more investigation it looks like the virtual objects are placed according to the gyroscope values. I checked what happens if I drop Stormtrooper while I'm standing on a chair, and indeed the virtual object was placed 30-40 cm above the floor. Does this make any sense?

**Comment by inio** [comment]
@itanbp Sounds like they try really hard to estimate where the floor might be based on typical user size.

ARCore provides device motion tracking and scene understanding tools, currently in the form of plane detection and hit testing. It's up to developers to decide how to uses these tools. Automatic placement of virtual content is a very application-specific behavior that requires knowledge of both the scale of your content and the ways users will interact with it.
