### ISSUE TITLE
How to using ArCore Demo on Android 5.1(21) platform.

### ISSUE THREAD

**Issue by bnhc** [google-ar/arcore-android-sdk#346]
ArCode only support Android 7.1, We don't have the android devices neither .If we want using ArCore on RK3288 and Android 5.1.
      Is  there a solution?

**Comment by hanhailong** [comment]
@bnhc  no solution  ^_^

**Comment by bnhc** [comment]
O ,Thank you !

**Comment by inio** [comment]
Under the hood, ARCore requires parts of the NDK camera API that only exist starting at API 24.
