### ISSUE TITLE
"Searching surfaces..." forever on virtual Pixel 2 API 27

### ISSUE THREAD

**Issue by davide1945** [google-ar/arcore-android-sdk#348]
Hi, I'm trying to run HelloAR (Java) in ARCore SDK for Android on a virtual Pixel 2 API 27, but after the app is launched it doesn't find any surface.

I followed this guide https://developers.google.com/ar/develop/java/quickstart and I'm working with:
Android Studio 3.1
API 27 (8.1) Revision 6

In the Logcat I have this output when running the HelloAR example:
05-02 11:05:46.599 4943-4978/com.google.ar.core.examples.java.helloar E/native: android_data_source.cc:495 generic::deadline_exceeded: Timed out waiting for metadata. camera_id=MotionTrackingPrimary
05-02 11:05:46.883 4943-4978/com.google.ar.core.examples.java.helloar E/native: android_data_source.cc:495 generic::deadline_exceeded: Timed out waiting for metadata. camera_id=MotionTrackingPrimary
05-02 11:05:46.903 4943-4969/com.google.ar.core.examples.java.helloar W/native: pose_manager.cc:56 GetRecentDevicePose failed. redwood::INVALID_ARGUMENT: Passed timestamp is too old. Latest VIO t:1333.96149212, latest IMU t:1335.61228, query t:1333.961492
05-02 11:05:46.908 4943-4978/com.google.ar.core.examples.java.helloar E/native: android_data_source.cc:495 CameraStatusErrorSpaceClass::ACAMERA_ERROR_METADATA_NOT_FOUND:  camera_id=MotionTrackingPrimary
05-02 11:05:46.934 4943-4967/com.google.ar.core.examples.java.helloar W/native: vio_initializer.cc:388 Dropped initialization window due to skip in data.
05-02 11:05:47.006 4943-4966/com.google.ar.core.examples.java.helloar W/native: analytics_logger.cc:197 Could not send event. Event will be dropped.
05-02 11:05:47.374 4943-4969/com.google.ar.core.examples.java.helloar W/native: pose_manager.cc:56 GetRecentDevicePose failed. redwood::INVALID_ARGUMENT: Passed timestamp is too old. Latest VIO t:1333.96149212, latest IMU t:1336.081558, query t:1334.69743
05-02 11:05:47.391 4943-4964/com.google.ar.core.examples.java.helloar W/native: pose_manager.cc:56 GetRecentDevicePose failed. redwood::INVALID_ARGUMENT: Passed timestamp is too old. Latest VIO t:1334.69743012, latest IMU t:1336.09057, query t:1334.69743
05-02 11:05:47.824 4943-4978/com.google.ar.core.examples.java.helloar E/native: android_data_source.cc:495 generic::deadline_exceeded: Timed out waiting for metadata. camera_id=MotionTrackingPrimary
05-02 11:05:47.899 4943-4978/com.google.ar.core.examples.java.helloar E/native: android_data_source.cc:495 generic::deadline_exceeded: Timed out waiting for metadata. camera_id=MotionTrackingPrimary
05-02 11:05:48.086 4943-4964/com.google.ar.core.examples.java.helloar W/native: android_data_source.cc:295 Metadata for GL texture didn't arrive. camera_id=ColorRearFacing status=generic::deadline_exceeded: Timed out waiting for metadata.
05-02 11:05:48.088 4943-4967/com.google.ar.core.examples.java.helloar W/native: vio_initializer.cc:388 Dropped initialization window due to skip in data.
05-02 11:05:48.088 4943-4967/com.google.ar.core.examples.java.helloar I/native: data_manager.cc:1044 Behind by: 0.180195 seconds, skip current frame.
05-02 11:05:48.111 4943-4978/com.google.ar.core.examples.java.helloar E/native: android_data_source.cc:495 generic::deadline_exceeded: Timed out waiting for metadata. camera_id=MotionTrackingPrimary
05-02 11:05:48.130 4943-4964/com.google.ar.core.examples.java.helloar W/native: android_data_source.cc:295 Metadata for GL texture didn't arrive. camera_id=ColorRearFacing status=generic::deadline_exceeded: Timed out waiting for metadata.
05-02 11:05:48.319 4943-4969/com.google.ar.core.examples.java.helloar W/native: pose_manager.cc:56 GetRecentDevicePose failed. redwood::INVALID_ARGUMENT: Passed timestamp is too old. Latest VIO t:1335.99819112, latest IMU t:1337.032417, query t:1335.998191
05-02 11:05:48.635 4943-4967/com.google.ar.core.examples.java.helloar W/native: vio_initializer.cc:388 Dropped initialization window due to skip in data.

Thanks in advance for your help

**Comment by inio** [comment]
For plane detection to work, you need to [move the virtual device using the WASDQE keys while holding the Alt or Option key](https://developers.google.com/ar/develop/java/emulator#control_the_ar_simulation).  Usually holding the A or D key and orbiting a surface works well.

If that doesn't help let me know and we can debug further.

**Comment by davide1945** [comment]
Thank for your reply inio.
Holding Alt key and moving my virtual device is exactly what I'm doing, but it doesn't work.

I've recorded the screen of emulated device to better explain my situation, this is the GIF: 
https://drive.google.com/file/d/15NWsYhwKZ4h3TiKQdGXGcw9sKYC7FBux/view?usp=sharing

Could it be a problem of computer performance?

**Comment by davide1945** [comment]
I've tried the same example with the same configuration of virtual device on a more powerful computer and it works perfectly. Now I'm pretty sure my problem was caused by the bad laptop performance.

Thank you very much for your reply and your time
