### ISSUE TITLE
Blurry image output

### ISSUE THREAD

**Issue by izdi** [google-ar/arcore-android-sdk#353]
Hey guys, just noticed that camera output is blurred for some reason, would appreciate the help. 
Tried C and Java latest samples, both have same effect.

Hardware: Pixel 2 
OS: 8.1.0 latest
 
![image](https://user-images.githubusercontent.com/6037501/39596530-55c7cd20-4f1b-11e8-8285-5333ac145f8a.png)

**Comment by inio** [comment]
ARCore's tracking algorithms currently require the camera be set to fixed focus, typically with a focus distance of a few meters.  If you point the camera at something further away is it any sharper?

As part of #153 we hope to enable autofocus on at least some devices.

**Comment by inio** [comment]
I've labeled this as bug because that seems *really* blurry, even for a fixed focus at several meters.

**Comment by DavidArayan** [comment]
I'd like to note that we had a similar issue on our Samsung Galaxy S8. Restarting the device or reinstalling the app did nothing. What fixed it was to open the camera app and let it re-focus which fixed the problem. It was quite a rare occurrence and not sure what caused it.

**Comment by izdi** [comment]
@inio Yes, for farther objects focus is better.

**Comment by fredsa** [comment]
Autofocus APIs were added in the 1.4.0 [release](https://github.com/google-ar/arcore-android-sdk/releases).

If you're still seeing issues after enabling autofocus in your app, but are seeing sharp images in the built-in Camera app, please feel free to reopen.
