### ISSUE TITLE
Question: Best way to kill the thread on Java implementation

### ISSUE THREAD

**Issue by abbana** [google-ar/arcore-android-sdk#359]
Hi Ionio,

I am looking for a viable way to kill the thread once I switch to another VC so I can came back to AR again and start it from the scratch.

I have looked around but found no easy solution for it. I know this is more a StackOverFlow question , but appreciate your POV on this.

Thanks.

**Comment by inio** [comment]
After pausing one `Session`, you should be able to start from scratch by creating and resuming a second `Session`.

**Comment by abbana** [comment]
Thanks,

does it shut it down also when the app is in background? Profiler shows it stills runs in background. Maybe I am doing something wrong?

**Comment by inio** [comment]
Are you calling `Session.pause()` from your activity's `onPause()`?  It might take as much as 10 seconds for things to completely spin down after that, but they should.
