### ISSUE TITLE
Instead of openGl any other way to load 3D model?

### ISSUE THREAD

**Issue by mistrydarshan99** [google-ar/arcore-android-sdk#36]
Hello,

ARCore basically, used OpenGL for loading 3D model. Is there any other way to load 3D model without the use of OpenGl?

**Comment by nathanmartz** [comment]
Right now the ARCore Java SDK does not provide asset loading or rendering
(aside from what is in the sample). You can use a higher level library like
Rajawali or libGDX, but I'm not sure that's exactly what you are looking
for. Can you give a bit more context about your use case and what kind of
solution would be ideal for you?

**Comment by mistrydarshan99** [comment]
Hi,

I have read ARCore documentation from below link : 
https://developers.google.com/ar/develop/java/getting-started

In above link, Google doesn't provide proper document,
1) How to load a 3D model?
2) How to use OpenGL? Why are we using OpenGL? What are classes of OpenGL used in ARCore?
3) How to detect surface?

Google only provides sample **java_arcore_hello_ar** without proper documentation. 

I am still confused from where to start to learn ARCore. So my main concern is providing proper documentation so that any Android Developer learn AR and properly developed AR application.

**Comment by nathanmartz** [comment]
Thanks for the context. We don't document things like 3D model loading or OpenGL programming because those concepts are not specific to ARCore, and there are already tons of great resources on the web for learning 3D graphics. Alternatively, you might want to look at a game engine like Unity or Unreal.

Surface detection is covered in the API reference and in the HelloAR sample.

**Comment by nativ18** [comment]
@nathanmartz Google Tango has sample projects that demonstrate integrating with 3rd-parties OpenGL engines like Rajawali so I wonder why ARCore doesn't have

**Comment by dotMorten** [comment]
??!? It has unity and unreal samples

**Comment by RajkumarRepo** [comment]
how to load multiple 2D texture image on a single 3D Object in Android AR- Core(java)

**Comment by harsh23tyagi** [comment]
Hi,
Is there a way wherein ARCore could use downloaded 3d models (.obj). I mean during the runtime of the app, if we could make a code to import the .obj and then use it ? a generic importer??
