### ISSUE TITLE
ComputerVision GPU_DOWNLOAD acquire YUV data

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#361]
Hi,
I have two questions regarding the computervision sample:

1. If  I choose to work with the GPU_DOWNLOAD approach with IMAGE_FORMAT_RGBA, is it possible to get the YUV image data? 
In the same way that the CPU approach exposes the image in a YUV format...
I found [bit manipulation](https://stackoverflow.com/questions/5960247/convert-bitmap-array-to-yuv-ycbcr-nv21) code to convert ARGB to YUV, but I'm not sure this is the best way, performance wise.

2.  the `TEXTURE_WIDTH` and `TEXTURE_HEIGHT` are hard-coded to `1920X1080`, with a comment `ARCore full resolution GL texture typically has a size of 1920 x 1080`.
Is this valid for each device and resolution?

Thanks!

**Comment by inio** [comment]
1. You could adjust the shader to convert the RGBA back to YUV.  OpenGL does not provide a way to directly read the underlying YUV data.

2. Currently the ARCore texture resolution is 1920x1080 on all devices, but this may change in the future.

**Comment by itanbp** [comment]
@inio thanks for the info
