### ISSUE TITLE
Increase or Maintain same model size, when translate model to z-axis (away from camera)

### ISSUE THREAD

**Issue by aswini149** [google-ar/arcore-android-sdk#365]
to move 3d model away from device, i am using the below translation,

anchors.add(session.createAnchor(frame.getCamera().getPose()
                            .compose(Pose.makeTranslation(0, 0, (float) -10))
                            .extractTranslation()));

Once i do this the model appears to be moving away and size becomes smaller. 
Is there a way of create an anchor at a particular coordinate with same model size ?

**Comment by inio** [comment]
This is a general 3D graphics question and not specific to ARCore.  Please try forums like StackOverflow for assistance with this kind of question.
