### ISSUE TITLE
Two queries RE: 1.2.0

### ISSUE THREAD

**Issue by aussieburger** [google-ar/arcore-android-sdk#366]
Two quick queries without having tested it yet:

**1.**
Where the release notes say:

"ARCore version 1.2.180425094 is expected to roll out to 100% of all Play Store users over the next few days."

Does this mean 100% of users who have a supported ARCore device or all users regardless of device (meaning all devices will suddenly be supported)?

**2.** 
Will there be an easy way to tell if the surface is a horizontal surface or a vertical surface using the unreal integration?

Many thanks in advance for the info!

**Comment by inio** [comment]
1. Your first reading is correct.  I'll make sure we update that wording to be more clear.

2. This would be better asked on the [Unreal issues board](https://github.com/google-ar/arcore-unreal-sdk/issues).  I'm not familiar with the details of our Unreal integration.
