### ISSUE TITLE
No ARcore support in Play Store after Samsung Galaxy A5 Oreo-Update

### ISSUE THREAD

**Issue by nitram2101** [google-ar/arcore-android-sdk#368]
Hi together,

after an Oreo-Update of my Samsung Galaxy A5 the Google PlayStore says, that my device is not supported. So I can't update to the new ARcore version 1.2 by using Play Store.
ARcore is still in my apps, but i can't manage it from PlayStore.

Kindly regards,
nitram2101

**Comment by inio** [comment]
What model number of A5 do you have?  Also, what is it's build fingerprint?  You can get the later with `adb shell getprop ro.build.fingerprint`.

**Comment by nitram2101** [comment]
The model number is SM-A520F.
The Fingerprint is: samsung/a5y17ltexx/a5y17lte:8.0.0/R16NW/A520FXXU4CRD5:user/release-keys

**Comment by inio** [comment]
@nitram2101 Thanks!  We should have this fixed within a few days, hopefully around the same time 1.2 makes it to 100% rollout.

**Comment by inio** [comment]
This should be fixed.  Please re-open if you have a supported device that cannot see ARCore in the Play Store.
