### ISSUE TITLE
cloud_anchor_java sample missing google-services.json file

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#369]
Hi,
I'm trying to open the `cloud_anchor_java` sample app and I get the error
```
Error:Execution failed for task ':app:processDebugGoogleServices'. > 
File google-services.json is missing. The Google Services Plugin cannot function without it. 
```

**Comment by asadullahnaweed** [comment]
This is expected. To download and build the sample app, you need to set up your own Firebase Realtime Database, download the google-services.json file, and add it to the `app` directory in your project.

Please see [Cloud Anchors for Android Quickstart](https://developers.google.com/ar/develop/java/cloud-anchors/cloud-anchors-quickstart-android#set_up_anchor_id_sharing) for more details.

**Comment by itanbp** [comment]
@asadullahnaweed thanks
