### ISSUE TITLE
Cloud anchors expiring?

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-android-sdk#371]
According to the docs, anchors visual mapping data is gone is 7 days, and sparse point map is gone in 1 day.

Does that mean, if a user creates an anchor (with whatever content) and comes back tomorrow to load it, it wouldn't work? If this is the case, that's a really weird limitation to impose?
Thanks.

**Comment by inio** [comment]
We made a conscious decision that the first offering of Cloud Anchors would not provide persistence.  It is really intended for simultaneous multi-user applications.

**Comment by inio** [comment]
Duplicate of #94

**Comment by iBicha** [comment]
@inio Is there a plan or a roadmap behind this? There are very obvious use cases where this feature is necessary. I would love to get a glance at ARCore's future plans before going ahead and implementing a custom solution (and potentially reinvent the wheel) or relying on a 3rd party service to achieve this (as far as I know, few startups are working on a similar service)
Thank you

**Comment by inio** [comment]
@iBicha So far we've been extremely quiet about feature plans.  There's a reason #27 has been sitting open since shortly after we launched this repo and it's not that I'm lazy ;).  Longer-term persistence is obvious a desirable feature, and I've left #94 open to track that.

**Comment by iBicha** [comment]
Understood, thank you for the response. I guess I will wait a bit longer and see what happens.
Cheers.

**Comment by bitcloudTheFirst** [comment]
Has this limitation been lifted yet?
