### ISSUE TITLE
Unity ARCore Strange Bug

### ISSUE THREAD

**Issue by luszukpawel** [google-ar/arcore-android-sdk#375]
So I'm having the strange bug with ARCore where I'm showing Engine in AR and my App suddenly stops refreshing and blurs the frame (see photo). 

My issue, however, is happening occasionaly in different angles and model configurations and same code and assets are working perfectly on ARKit.

I've tried to track this in console debbug with no luck.

Tested on multiple Galaxy S7

![screenshot_20180510-170855](https://user-images.githubusercontent.com/22742691/39877125-5acfa32e-5475-11e8-8a66-94de56f71c31.png)
![screenshot_20180510-170835](https://user-images.githubusercontent.com/22742691/39877127-5af55dbc-5475-11e8-861b-a8a380a0036b.png)
![screenshot_20180510-170815](https://user-images.githubusercontent.com/22742691/39877129-5b19bcb6-5475-11e8-95e2-ec09ea89b204.png)

**Comment by sam598** [comment]
Are you using Unity? How complex are your assets? Does it happen with a simple 3D model, single shader, no animation?

I've seen several Android phones experience this issue in overly complex scenes.

**Comment by inio** [comment]
From the title it sounds like you're using Unity.  Please report Unity issues on the arcore-unity-sdk issues page.
