### ISSUE TITLE
No FBX animation support for Imported Sceneform Assets

### ISSUE THREAD

**Issue by haroldmthyng** [google-ar/arcore-android-sdk#376]
More so confirmation as I've tried everything and imported FBX assets do not retain animation or skeletal animation data. Unless I'm missing something. This is the key major component to ever use a FBX asset over a static OBJ file.

Can you confirm if animated FBX's are supported within the Sceneform binary file format? Will be in an upcoming release? If not, can you generate a much needed feature request for skeletal animation support for Sceneform assets?

**Comment by inio** [comment]
Please report this on the sceneform issues page.

**Comment by haroldmthyng** [comment]
Done. Thanks!

**Comment by inio** [comment]
@Edgar-BlipparDev ARCore provides device pose, scene understanding, and a camera texture, nothing more.  Our sample code demonstrates how to use those pieces to create a minimal AR application.

[Sceneform](https://developers.google.com/ar/develop/java/sceneform/) adds a rendering framework, but it is not ARCore.  Questions/issues about it should be taken to [the Sceneform github page](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by Consti10** [comment]
maybe check out https://github.com/google-ar/sceneform-android-sdk/issues/648
