### ISSUE TITLE
ARCore for Galaxy Note 8

### ISSUE THREAD

**Issue by e3soufiane** [google-ar/arcore-android-sdk#383]
I see that Samsung Galaxy Note 8 is no more on the list of supported devices by ARCore 1.2. Does it mean that this device will no more be able to run AR if we update ARCore?

**Comment by inio** [comment]
I'm trying to figure out why the Note 8 disappeared.  We moved that list between pages with the 1.2 launch and it disappeared at that point.  This may not have been intentional.

**Comment by Edgar-BlipparDev** [comment]
I actually noticed that too I am able to run arcore just fine on Note 8 but its not listed anymore supported device

**Comment by inio** [comment]
Our [supported device list](https://developers.google.com/ar/discover/supported-devices) has been updated to include the Note8, and also be easier to read.
