### ISSUE TITLE
Feature Request: Add utility libraries to C examples

### ISSUE THREAD

**Issue by kenfast** [google-ar/arcore-android-sdk#385]
The Tango C SDK had a tango_gl library for simple OpenGL primitives and a third_party library with GLM, PNG, and FreeType.  It would be convenient to have these included with ARCore.  These are just extra C code so they don't require any ARCore support like 3D Reconstruction would.

**Comment by inio** [comment]
Our C API is primarily offered for developers integrating ARCore with an existing engine.  For new development we recommend the Java API, and strongly encourage you to look at [Sceneform](https://developers.google.com/ar/develop/java/sceneform/).

**Comment by kenfast** [comment]
I appreciate your offer to stick with the Java API and Sceneform.  If I were starting from scratch I might go that route, but I have too much time and energy invested in Tango Native development already.  I think it will be easier to try pulling the GLM code out of the old Tango SDK and making it a new project - less new stuff to learn.
Should I be concerned from this that the C API might have limited capabilities in the future?  I would hope that there will be parity in exposing the basic ARCore functionality between the Java, C, and Unity APIs.

**Comment by inio** [comment]
Sorry, yeah, that's probably your best option.

> Should I be concerned from this that the C API might have limited capabilities in the future? 

No.  Our C API will provide 100% of our API surface.  Our Java, Unity and Unreal APIs all wrap the C API for `Session` and everything accessed through it.  Because of this, even things implemented in Java (like the ArCoreApk class) gets C wrappers so they can be called from Unity and Unreal.

**Comment by kenfast** [comment]
Good answer!  That's what we want to hear.  Thanks for looking out for us C old timers.
