### ISSUE TITLE
Feature Request: provide supported device model numbers

### ISSUE THREAD

**Issue by e3soufiane** [google-ar/arcore-android-sdk#387]
I noticed that you are no more showing the model numbers of supported devices. I'm using the model number to whitelist devices, it would be great to get this information back.

**Comment by inio** [comment]
Please see [Enable ARCore](https://developers.google.com/ar/develop/java/enable-arcore) for details of how to properly restrict Play Store distribution of your app to supported devices.

We do not support distribution through other app markets at this time.

**Comment by e3soufiane** [comment]
We are already using the manifest.

We only support ARCore capable devices that pass our internal performance test hence the need to whitelist devices "manually".

It would be good if you can put model numbers of supported devices online again.

**Comment by inio** [comment]
I've filed a feature request.  However, we removed the models numbers after quite a bit of discussion so I'm not sure how likely it is to happen.

**Comment by devbridie** [comment]
Check out [the Device list (CSV file)](https://developers.google.com/ar/discover/supported-devices#google_play_csv) for instructions on how to obtain a list that includes model numbers.
