### ISSUE TITLE
LG G6 H870 Android Nougat 7.0 not supported ? 

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#390]
I have got a user who has a LG G6 H870 with Android 7.0.

He says that is not able to install the app from the store.

Do the LG G6 require Android 8 ? (not mentioned here https://developers.google.com/ar/discover/supported-devices )

Or is there a problem with this specific model number ?

Thanks.

**Comment by inio** [comment]
We believe we have enabled LG G6 devices.  I've asked the team to check.

**Comment by inio** [comment]
You caught an error in our supported device list.  The LG G6 should be marked as requiring 8.

**Comment by RegisAG** [comment]
Thanks.

**Comment by RegisAG** [comment]
Note that a few days ago, there was a column with the minimum required Android version. I have got the feeling that there were much more devices requiring Android 8 than what is mentioned now.

**Comment by inio** [comment]
Most of the devices listed as requiring Android 8.0 actually did not.  We were slightly overzealous in dropping that when creating the new page.
