### ISSUE TITLE
ARcore 1.2 Cloud anchor: Unable to change AR core Andy Android prefab Unity

### ISSUE THREAD

**Issue by fayesugar** [google-ar/arcore-android-sdk#393]
Really strange issue I'm unable to change the andy prefab in the cloud anchor controller to a different prefab or even the same prefab with a cube added to it, if I alter the prefab in anyway (or swap it) the other device on resolve will immediatly say its found the anchor and will display nothing (however the default untouched Andy works) I've checked theres no issues with the positioning or anything like that (as for one test I just added a cube to the default prefab in the same position as Andy) Really confused why this is happening, any advice would be appreciated!

**Comment by inio** [comment]
Please report this on the [Unity Issues Page](https://github.com/google-ar/arcore-unity-sdk/issues).
