### ISSUE TITLE
Arcore apk not found for download

### ISSUE THREAD

**Issue by tusharrain28** [google-ar/arcore-android-sdk#396]
Hi, I started studying ARcore when it was in the preview stage then I skipped it a bit. Want to come back to it . I remember that there was some Arcore preview apk that needed to be installed before using Arcore. But now I cannot see any such apk link on the Arcore site and reading through the documentation I think we can only download from play store now. Am I right or am I missing something?

**Comment by inio** [comment]
@drunkenplatypus Thanks for handing this one.
