### ISSUE TITLE
Private Cloud Anchor Service

### ISSUE THREAD

**Issue by zhangalex** [google-ar/arcore-android-sdk#400]
Hi all,

Recently, I have an AR collaboration project but the app cannot access the internet network. So, we cannot use google's cloud anchor service. 

Is there anyway to deploy a private cloud anchor service or a method can help me to build a my own private anchor sharing service?

Thanks,
Alex

**Comment by GokulDas027** [comment]
Is it possible now?  on ARCore 1.18

**Comment by devbridie** [comment]
There have not been any changes to this-- Cloud Anchors cannot be hosted on a private anchor sharing service at this time.
