### ISSUE TITLE
i want place an object in the air,what`s wrong?

### ISSUE THREAD

**Issue by Nullifier1571** [google-ar/arcore-android-sdk#403]
this is my code:  
`@Override
    public void onDrawFrame(GL10 gl) {
           if (!isLock) {
                session.createAnchor(new Pose(new float[]{0.1f, 0.1f, 0.1f}, new float[]{0.9f, 0.9f, 0.9f}));
                //anchors.add();
                isLock = true;
            }
   }`

when i run it in my phone,the screen blackening ，what`s wrong?

**Comment by inio** [comment]
Duplicate of #110
