### ISSUE TITLE
RGB values for a point in the acquired point cloud

### ISSUE THREAD

**Issue by Godric877** [google-ar/arcore-android-sdk#404]
Hi!

Can you please tell me if there is a way to know the colour(RGB values) of a particular point if I know the 3D coordinates of the point?

I have used the function `frame.acquirePointCloud()` to store the point cloud and then while iterating through the points, I require the RGB values of the points also.

Any help would be highly appreciated! Thanks :)

**Comment by inio** [comment]
For many points:

1. Transform the point to normalized screen coordinates (multiply my projection*view matrix and divide by w)
2. Convert the normalized screen coordinates to a pixel position in the CPU image (assume the screen is a center-crop of the CPU frame)
3. read the appropriate pixel from the CPU image and convert YUV to RGB.

For just a few points, you should be able to render the point with a shader that:

1. computes the screen space coordinates, 
2. applies a transform backed out of the result from transformDisplayUvCoords
3. samples the camera texture at the resulting UV position
4. Uses some mechanism to return that data to the CPU (counters, shader storage buffer, transform feedback, etc)

**Comment by inio** [comment]
I can't really provide help for this sort of thing.  Maybe try StackOverflow?

**Comment by Godric877** [comment]
Ok, Thank you

**Comment by ramunl** [comment]
> Hi,
> 
> I tried to follow the steps you mentioned above.
> 
> However, I am facing the following problems :-
> 
> 1. While converting from 3D coordinates to 2D screen coordinates, sometimes I observed negative values.
> 2. The visualisation of the point-cloud after igonring the negative values mentioned above does not resemble the actual colour of the object.
> 
> The code for converting 3D coordinates to 2D coordinates was taken from :-
> 
> [Convert 3D world (arcore anchor/pose) to its corresponding 2D screen coordinates](https://stackoverflow.com/questions/49026297/convert-3d-world-arcore-anchor-pose-to-its-corresponding-2d-screen-coordinates)
> 
> Below is the code I have used :-
> 
> 1. Storing the aquired image as a byte array :-
> 
> ```
> Image m_img = frame.acquireCameraImage();
> 
>       int image_width = m_img.getWidth();
>       int image_height = m_img.getHeight();
> 
>       Image.Plane[] planes = m_img.getPlanes();
> 
>       Image.Plane Y = planes[0];
>       Image.Plane U = planes[1];
>       Image.Plane V = planes[2];
> 
>       int Yb = Y.getBuffer().remaining();
>       int Ub = U.getBuffer().remaining();
>       int Vb = V.getBuffer().remaining();
> 
>       byte[] data = new byte[Yb + Ub + Vb];
> 
>       Y.getBuffer().get(data, 0, Yb);
>       U.getBuffer().get(data, Yb, Ub);
>       V.getBuffer().get(data,Yb+Ub, Vb);
> 
>       int size_total = image_width * image_height;
> 
> m_img.close();
> ```
> 1. Extracting the pixel coordinates using the link mentioned above :-
> 
> ```
> float[] anchorMatrix = new float[16];
> myanchor.getPose().toMatrix(anchorMatrix, 0);
> float[] world2screenMatrix = calculateWorld2CameraMatrix(anchorMatrix, viewmtx, projmtx);
> double[] anchor_2d =  world2Screen(myanchor.getPose(), image_width, image_height, world2screenMatrix);
> 
> double px =  anchor_2d[0];
> double py =  anchor_2d[1];
> ```
> 1. The function used for converting YUV values to RGB values :-
> 
> ```
> private static float[] convertPixelYuvToRgb(byte[] yuvData) {
>     final int CHANNELS = 3; // yuv
>     final float COLOR_RANGE = 256f;
> 
>     assertTrue("YUV pixel must be at least 3 bytes large", CHANNELS <= yuvData.length);
>     float[] rgb = new float[CHANNELS];
> 
>     float y = yuvData[0] & 0xFF;  // Y channel
>     float cb = yuvData[1] & 0xFF; // U channel
>     float cr = yuvData[2] & 0xFF; // V channel
> 
>     // convert YUV -> RGB (from JFIF's "Conversion to and from RGB" section)
>     float r = y + (1.370705f * (cr - 128));
>     float g = y - (0.698001f * (cb - 128)) - (0.337633f * (cr - 128));
>     float b = y + (1.732446f * (cb - 128));
> 
>     // normalize [0,255] -> [0,1]
>     rgb[0] = r / COLOR_RANGE;
>     rgb[1] = g / COLOR_RANGE;
>     rgb[2] = b / COLOR_RANGE;
> 
>     // Clamp to range [0,1]
>     for (int i = 0; i < CHANNELS; ++i) {
>       rgb[i] = Math.max(0.0f, Math.min(1.0f, rgb[i]));
>     }
> 
>     rgb[0] = (int) (rgb[0] * 255);
>     rgb[1] = (int) (rgb[1] * 255);
>     rgb[2] = (int) (rgb[2] * 255);
> 
>     Log.d(TAG, String.format("RGB calculated (r,g,b) = (%f, %f, %f)", rgb[0], rgb[1], rgb[2]));
> 
>     return rgb;
>   }
> ```
> The formula for conversion was taken from :-
> 
> [YUV Image Format](https://en.wikipedia.org/wiki/YUV)
> 
> under the heading **Y′UV420sp (NV21) to RGB conversion (Android)**
> 
> 1. Extracting the Y, U and V values for a pixel from the byte array and converting to RGB :-
> 
> ```
>           int y_index = (int) (py*image_width  + px);
>           int u_index = (int) (py/2 + image_width/2 + px/2 + size_total);
>           int v_index = (int) (py/2 + image_width/2 + px/2 + size_total + size_total/4);
> 
>           byte yuv_data[] = new byte[3];
>           yuv_data[0] = data[y_index];
>           yuv_data[1] = data[u_index];
>           yuv_data[2] = data[v_index];
> 
>           float[] rgb = convertPixelYuvToRgb(yuv_data);
> ```
> Please help me out as I seem stuck here. I would greatly appreciate it. Thank you ! :)

Hi,

Did you find a solution for this problem ?

**Comment by Godric877** [comment]
Hi! Yes, there was a mistake in the transformation to screen coordinates. However, I still observed negative values but at least the colour of the object matched more-or-less.

**Comment by iliuxaar** [comment]
> Hi! Yes, there was a mistake in the transformation to screen coordinates. However, I still observed negative values but at least the colour of the object matched more-or-less.

Is it possible for you to represent code now?

**Comment by sylviaGG** [comment]
@Godric877  Hi, did you find what the mistake is? I have the same problem, negative values after the transformation. How did you fix it?

**Comment by iliuxaar** [comment]
@sylviaGG , write me on my email, please. I will provide solution for you

**Comment by sylviaGG** [comment]
@iliuxaar hi, I wrote you an email yesterday,plz check

**Comment by iliuxaar** [comment]
Hello, I'm a little bit easy now. I hope it not problem for you. I will
send project for you today

вт, 23 мар. 2021 г., 10:34 sylviaGG ***@***.***>:

**Comment by iliuxaar** [comment]
Hello. let the project please. I've removed old info about customer and
etc, may forget somethink. It's very old prototype of project, there you
can find regular scanning + depth api recognition. You may remove c code
and move it into arViewModel. Also i've removed upload data and etc, so
code may seems a little bit strange and additionally i haven't device with
arcore and cant test the app, so try to check file saving by yourself. If
you don't need in depth api, regular rgb you will find in chain starting
with "processPoint" inside ArViewModel.
Hope i will be able to help you. And sorry for bad refactoring because i
haven't free time now for clearing the code, i was left company with this
project about half of the year before. Good luck

https://drive.google.com/file/d/1r3V4_g6Ebr9HDcKT-v6o36TlO2nkahOO/view?usp=sharing

вт, 23 мар. 2021 г. в 11:28, Илья Арико ***@***.***>:

**Comment by sylviaGG** [comment]
@iliuxaar Hi, thank you so much for sharing this to me. It ask the access to the drive, i send you the request. plz check!

**Comment by iliuxaar** [comment]
Recheck please

ср, 24 мар. 2021 г., 12:10 sylviaGG ***@***.***>:

**Comment by iliuxaar** [comment]
Hello. Does this project help you?

ср, 24 мар. 2021 г. в 12:19, Илья Арико ***@***.***>:

**Comment by sylviaGG** [comment]
Hi, thx for sharing, but I checked the transformation part, it use the same approach as I did. So it didn't actually solved my problem. But it still helps! Thank you so much!

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
