### ISSUE TITLE
Renderer CaptureScreenshot returning bad data

### ISSUE THREAD

**Issue by LukasStancikas** [google-ar/arcore-android-sdk#406]
Hello, i've tried the `sceneView.getRenderer().captureScreenshot( listener)`

And i've noticed some problems with it. I've tried creating a bitmap from the ByteBuffer and widht, height that i get in my result, but the image output is almost twice as small than the supplied width and height.
This is how i generate the bitmap:
```
fun onCameraClick(buffer: ByteBuffer, width : Int, height: Int): Bitmap {
		buffer.rewind()
		val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
		bitmap.copyPixelsFromBuffer(buffer)
		return bitmap
}
```
The width and height i always get is 1440x2736 (this is presumably my sceneview (aka surfaceView) size, but the bitmap is just 538x1024 size, and everything else is just transparent area.

What is even weirder is after trying to capture the image a second time, the height/width returns same size values, but bitmap is duplicated inside: [Heres a screenshot](http://oi67.tinypic.com/es6x5k.jpg)

Also, https://developers.google.com/ar/reference/java/com/google/ar/sceneform/SceneView leads to a 404 to any documentation about what SceneView has to offer

**Comment by inio** [comment]
Please report Sceneform issues on the [Sceneform issues page](https://github.com/google-ar/sceneform-android-sdk/issues).
