### ISSUE TITLE
Using the device as anchor for sceneform objects

### ISSUE THREAD

**Issue by nitram2101** [google-ar/arcore-android-sdk#407]
Hi,
i want to use the mobile device as an anchor for an sceneform object, but don't want to use planes. Is there an easy way (or methods) to use an arFragment without using the method .setOnTapArPlaneListener? The application should just start and directly show an arrow in front of the camera and moving with it. At the moment i have the solution, that i have to tap on a plane to get the arrow in front of me.

The more difficult way seems to be a workaround with not using sceneform in old ArCore 1.0 style, like the compass-app posted by @inio in another issue?

**Comment by inio** [comment]
Please report Sceneform issues on the [Sceneform issues page](https://github.com/google-ar/sceneform-android-sdk/issues).
