### ISSUE TITLE
Sceneform .sfb opacity not working

### ISSUE THREAD

**Issue by chiaolinghong3d** [google-ar/arcore-android-sdk#410]
The opacity in Material parameter does not seem to change anything when I set it to 0 or 0.5. I've tried on both obj and fbx, both don't seem to change anything.
![reference](https://user-images.githubusercontent.com/39775868/40858528-65c7315a-6593-11e8-9106-b8eb84c155b7.PNG)

**Comment by inio** [comment]
Please report Sceneform issues on the [Sceneform issues page](https://github.com/google-ar/sceneform-android-sdk/issues).
