### ISSUE TITLE
error "Invalid ray produced by view data" from frame.hitTest()

### ISSUE THREAD

**Issue by robertliebo** [google-ar/arcore-android-sdk#413]
i'm integrating ARCore into a bigger ndk project and most of it runs perfectly (session ok, getting frames with camera pose and camera image ok, also frame.getUpdatedTrackables(Plane.class) finds and updates planes) BUT: frame.hitTest() at any screen location always returns an empty List of HitResult and logcat shows error "E/native: session.cc:908 Invalid ray produced by view data!".
i'm picking up the tracking data still in a java class before handing it over via jni.

**Comment by inio** [comment]
Are you seeing the log message "Invalid value for view_size"?  If so, double-check that you're giving positive pixel dimensions to [`Session.setDisplayGeometry()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Session.html#setDisplayGeometry\(int\,%20int\,%20int\)).

**Comment by robertliebo** [comment]
that was it, thank you! the Session.setDisplayGeometry() was missing completely, after inserting a call to it, hitTest() returns HitResult's and the "Invalid ray produced by view data!" errors are gone.
(i didn't find that "Invalid value for view_size" log message though, but it could have been filtered out, i didn't save the unfiltered logcat)
