### ISSUE TITLE
Samsung S7 SM-G930F (kernel ver.3.18.14-12365438) use sample Just black screen and crash after that

### ISSUE THREAD

**Issue by MiMiTuTu212** [google-ar/arcore-android-sdk#417]
Hi,
I'm trying to run the sample(Hello AR Java) from here (ARCore Android SDK v1.2.1). Success for compile but after installing the sample on my device (Samsung S7 firmware 7.0 ver.3.18.14-12365438), just only black screen and crash after few second.
but, im trying to run the sample on my other device Samsung S7 (firmware 7.0 kernel ver.3.18.14-11104523) and  Samsung note8 (firmware 7.1.1) the sample can work properly.

I'am using ARCore version 1.2.180425134

software Information

Samsung S7 (Crash)
![s7-crash1](https://user-images.githubusercontent.com/39948782/40971157-e1d7b05c-68e6-11e8-9fe5-92a15cc627e0.png)
![s7-crash2](https://user-images.githubusercontent.com/39948782/40971189-fb58d3b2-68e6-11e8-99d7-f28fccc94d0e.png)

Samsung S7 Work Properly

![s7-work properly](https://user-images.githubusercontent.com/39948782/40971318-6f16c3a4-68e7-11e8-9fe3-5ac3bdd9426e.png)
![s7-work proprely](https://user-images.githubusercontent.com/39948782/40971324-7102c69a-68e7-11e8-874c-e21d87ce0eab.png)

Samsung Note 8 Work Properly

![note8](https://user-images.githubusercontent.com/39948782/40971419-bcfb7c36-68e7-11e8-99f1-0f2d8b2581b1.jpg)
![note8-work](https://user-images.githubusercontent.com/39948782/40971420-bdbf193e-68e7-11e8-8035-1988a1a47e9e.jpg)

Here the crash log
[crash-log.txt](https://github.com/google-ar/arcore-android-sdk/files/2072041/crash-log.txt)

can you help for the issue?

Thank You.

Regard,

MiMiTuTu

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
