### ISSUE TITLE
Interaction with anchored node

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/arcore-android-sdk#421]
Hello.

I would like to allow a user to interact with an anchored object. Unfortunately I don't see how I could implement this.

When a marker in the AugmentedImageDatabase is recognized, I want to place a 3D object on top of this AugmentedImage. For example, the real world object is a information sign, containing an image of an historic artefact. When the marker is recognized, I want to place a 3D object of this artefact on top of the image of this artefact. 

What I want to achive now is, that the user can rotate the 3D object of the artefact to see it from all sides.

So I extended Node to overwrite onTouchEvent as described in the Sceneform docs, which seems to work, but I can't get the 3D object of the artefact to react on location or rotation changes.

It seems to me, that the image tracking of ARCore resets my changes to the Node. Is this correct, or should I be able to implement the functionality described above?

I probably would be able to do this by changing the location and rotation of the anchor of the augmented image itself, but there will be other objects connected to this anchor which shouldn't be affected by the interactions of the 3D object above.

**Comment by michaelvogt** [comment]
Got it working as described in [Sceneform tracker](https://github.com/google-ar/sceneform-android-sdk/issues/59)

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
