### ISSUE TITLE
How to Zoom in and Out of Anchor in Android

### ISSUE THREAD

**Issue by kirankaushal** [google-ar/arcore-android-sdk#422]
I want to modify Hello ar sample application code .I had changed anchor image.But it's looking very big when placed on hit .I want to Zoom in and out that anchor image.And also want to move image on gesture.Anybody can help me.

**Comment by inio** [comment]
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.

Consider using [Sceneform](https://developers.google.com/ar/develop/java/sceneform/), Unity or Unreal if you're looking for more engine-level capabilities.
