### ISSUE TITLE
A strange problem (using S8)

### ISSUE THREAD

**Issue by figoche** [google-ar/arcore-android-sdk#423]
I installed my own app and other developers' app in a new S8（950U）.
The first few minutes it works，then all APP can't open the camera, one of which prompts "ARCore encountered a problem connecting. Please start the app again."
The first time I reset the phone, it worked normally for a few minutes and then had the same problem. The second time I reinstalled arcore, it still works only a few minutes
Have anyone ever met a similar problem, thank you~

**Comment by inio** [comment]
Do you have China Mobile SIM card in this device?  If so that's #350.

Also, in the future please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
