### ISSUE TITLE
Error while converting obj to sfb

### ISSUE THREAD

**Issue by mhdtouban** [google-ar/arcore-android-sdk#428]
ERROR: Jsonnet Error: [1]: RUNTIME ERROR: Parameter 'roughness' doesn't have any applicable options
	third_party/arcore/ar/rendercore/converter/data/mat_helpers.jsonnet:(162:5)-(177:24)	function <getUsedOpt>
	third_party/arcore/ar/rendercore/converter/data/mat_helpers.jsonnet:199:23-73	object <param_opt_from_name>
	third_party/arcore/ar/rendercore/converter/data/mat_helpers.jsonnet:203:23-53	object <param_init_from_name>
	third_party/arcore/ar/rendercore/converter/data/mat_helpers.jsonnet:230:26-51	object <anonymous>
	std.jsonnet:158:56-67	thunk <array_element>
	third_party/arcore/ar/rendercore/converter/data/import_meta_material.jsonnet:(11:19)-(12:44)	object <anonymous>
	During manifestation	

Command Line: /AR-Testing/app/build/sceneform_sdk/mac/converter --no_sfb --mat build/sceneform_sdk/default_materials/obj_material.sfm -a --matc AR-Testing/app/build/sceneform_sdk/mac/matc --outdir AR-Testing/app/build/.sfa771261066923969224 sampledata/BANH VONG MIN.obj 
:app:createAsset-src_47main_47assets_47BANH_32VONG_32MIN FAILED

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
