### ISSUE TITLE
How to create Model for ARCore? I got 5 or 6 Models online but I am not able to create new one. One more thing I want to know that I can add gallery or camera picture as anchor o not by ar core ?

### ISSUE THREAD

**Issue by kirankaushal** [google-ar/arcore-android-sdk#436]
How to create Model for ARCore? I got 5 or 6 Models online but I am not able to create new one. One more thing I want to know that I can add gallery or camera picture as anchor o not by ar core ?

**Comment by inio** [comment]
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.

Consider using [Sceneform](https://developers.google.com/ar/develop/java/sceneform/), Unity or Unreal if you're looking for more engine-level capabilities.
