### ISSUE TITLE
How to create Model (.obj) files for a image in android.Please help as soon as possible.I am stuck to that issue.

### ISSUE THREAD

**Issue by kirankaushal** [google-ar/arcore-android-sdk#438]

**Comment by inio** [comment]
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.

Consider using [Sceneform](https://developers.google.com/ar/develop/java/sceneform/), Unity or Unreal if you're looking for more engine-level capabilities.

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
