### ISSUE TITLE
When will AR Core support each and every Android Device?

### ISSUE THREAD

**Issue by ayan-das1234** [google-ar/arcore-android-sdk#44]
When will AR Core support each and every Android Device? , and I can't ay for Unity nor Unreal Engine so AS is my only way to make some cool AR apps so can I develop AR apps in AS without using these third party environmet?

**Comment by nathanmartz** [comment]
ARCore will support more devices over time, but right now we aren't promising that it will every support literally all Android devices (some of which don't even have gyros).
