### ISSUE TITLE
Mixing Sceneform and OpenGL GLSurfaceView

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#443]
Hi,

I am wondering of I can add objects built with Sceneform in my old-school OpenGL project (everything done in OpenGL with a GLSurfaceView).

I am afraid that no, but just to be sure....

Thanks.

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
