### ISSUE TITLE
Cloud anchors hosting calls never return in airplane mode.

### ISSUE THREAD

**Issue by claywilkinson** [google-ar/arcore-android-sdk#446]
Hello!

I was trying out the Cloud Anchors sample and it was not working, it turned out my phone was not connected to the network.
I debugged it to the Firebase transaction handler never having onComplete called.

Is there a way to check for network connectivity first? or set some timeout or other option on the transaction  so it returns?

**Comment by inio** [comment]
It sees the timeout is currently 60 seconds, which I think is a bit long.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
