### ISSUE TITLE
Can someone help me with creating multiple google anchors and should be visible all at a time? 

### ISSUE THREAD

**Issue by srikanth104** [google-ar/arcore-android-sdk#449]
I'm able modify the Firebase cloud anchor ID which would looks like multiple cloud anchors but can't able to achieve to see the multiple anchors at a time ?

**Comment by inio** [comment]
Not sure what you're asking.  Is the problem related to hosting multiple cloud anchors, or just drawing multiple objects on the screen?  If it's the drawing, have you tried with regular (non-cloud) anchors?

**Comment by srikanth104** [comment]
Drawing multiple cloud anchors and retrieving those at a time

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
