### ISSUE TITLE
Question: Anchor Rolling with the camera

### ISSUE THREAD

**Issue by abbana** [google-ar/arcore-android-sdk#452]
Hi,

I am looking for the best way to have the anchors following the roll of the device so that can stay on a fixed point on the screen, supposed that just roll is performed.
What is the suggested way to achieve this? I have looked around but not found anything that useful for this.

Thanks.

**Comment by inio** [comment]
Are you trying to basically get a fixed orientation on the screen, but located at the anchor position?  If that's the case, try
````
anchor.getPose.extractTranslation().compose(
    camera.getDisplayOrientedPose().extractRotation())
````

**Comment by abbana** [comment]
Hi Inio,

I am trying to have some anchors as buttons in the screen. My understanding is that with that I will have the anchor rolling as requested, but then I have to add a pitch rotation to let those anchor be on a plane parallel to the screen, am I correct?

Also is there any way to have a session with the world origin that is the camera itself? 
Also is possible to rotate the camera itself?

Thanks a lot.

**Comment by abbana** [comment]
Sorted.

Thanks.

**Comment by inio** [comment]
You should not use anchors for on-screen elements, they are for fixed positions in the world.  The code I provided would make an element behave like a "billboard" sprite, similar to the trees is Mario 64.

It sounds like you want camera-relative objects.  For this, you can either position them in the world relative to the camera (`camera.getDisplayOrientedPose.compose(CAMERA_REALTIVE_POSE)`) or ignore poses entirely and draw them with an identity view matrix (in place of the `Camera.getViewMatrix()`) or skip composing the view matrix into the MVP uniform.

**Comment by abbana** [comment]
Thanks Inio, that is solved, thanks for help.

**Comment by ivstka95** [comment]
@abbana can you share the solution please?
