### ISSUE TITLE
How to remove andy.obj on the View?

### ISSUE THREAD

**Issue by kmh339** [google-ar/arcore-android-sdk#455]
I try to remove the andy.sfa in Google ARcore sample sceneform on eventClickListener.

but I can't this

this is source and please help me..TT

` Button delete = (Button)findViewById(R.id.delete);
        delete.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                arFragment.setOnTapArPlaneListener(
                        (HitResult hitResult, Plane plane, MotionEvent motionEvent) -> {
                            if (plane.getType() != Type.HORIZONTAL_UPWARD_FACING) {
                                return;
                            }

                            // Create the Anchor. 
                            Anchor anchor = hitResult.createAnchor();
                            AnchorNode anchorNode = new AnchorNode(anchor);
                            anchorNode.setParent(arFragment.getArSceneView().getScene());

                            // Create the transformable andy and add it to the anchor.
                            TransformableNode obj = new TransformableNode(arFragment.getTransformationSystem());
                            obj.setParent(anchorNode);

                        });
            }
        });`

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
