### ISSUE TITLE
ARCore support on Samsung devices with model numbers ending in 0 or 8.

### ISSUE THREAD

**Issue by guilhermelima07** [google-ar/arcore-android-sdk#457]
Hello guys!

I'm wondering here when the AR Core will officially be available at Play Store on the Galaxy S9 ending in 0 or 8. I live in Brazil and my model is the SM-G9650 - by the way, I friend of mine has bought an S9+ in US, it is the same model and he has the same problem. I'm askgin because it is so widely spread that S9 supports the tech, but in fact is not what's happening.

Edit: I do know that I can sideload the app by downloading it from the official page, however the apps I tried to download, like Porsche's one does not works well. Also I can't find the popular apps on Play Store, as it is not 'compatible'.

**Comment by inio** [comment]
It sounds like we should probably turn on the 0 device on Play Store.  I'll talk to the team and see if that can happen.

**Comment by ricsmania** [comment]
I have the same device model, and I tried sideloading the 1.3 APK but got some very erratic behavior, so maybe it's not just a matter of making it available on the Play Store.

**Comment by guilhermelima07** [comment]
@inio Thank you very much man! Looking forward on it !!! Anxiously waiting for that!
@ricsmania Man, I do have problems as well with some apps, like the Measure app, the Porsche one I told before.. However I just tried the GCAM port to S9+ and it works flawlessly.
Maybe the source of the APK's we are download is not reliable. Downloading it directly from Play Store may be different! Let's see

**Comment by guilhermelima07** [comment]
@inio Hey man! Do you have any news on this regard ?? Are you sure it is a matter to just enable it on google play store ? I'm asking because I was reading the supported device list and it says that galaxies s9 ending 0 or 8 are not supported.
Thanks in Advance,

**Comment by inio** [comment]
We're working on enabling the 0 devices sold outside of China.  Stay tuned.

**Comment by guilhermelima07** [comment]
Thanks @inio !!! Looking forward to it!

**Comment by Tonieh** [comment]
Thanks @inio !! :D

**Comment by ocedalv** [comment]
It seems its been enabled on the play store for SM-G9650. It does not work, though. At least on my device. Measure can never find any surfaces so measure, so I'm not sure if something needs to be done other than enable it on the store.

**Comment by inio** [comment]
@ocedalv That sounds like #419.  See the thread, but short version is: restart to fix it for now, real fix coming in a system software update shortly.

**Comment by inio** [comment]
Samsung model numbers ending in 0 originally sold **outside** of China should now be supported on the Play Store.  Please file a new issue if you see otherwise.

Additionally, as of ARCore 1.3, most devices with models numbers ending in 0 or 8, regardless of distribution region, should work when ARCore is side-loaded.  Note that this configuration is NOT fully-supported, and you may encounter some issues.
