### ISSUE TITLE
Cannot run hellosceneform app on Samsung S7 SM-G930F with Android 8.0 official update

### ISSUE THREAD

**Issue by berkutio** [google-ar/arcore-android-sdk#459]
There was some troubles with given device running on Android 7, but I made several attempts to run the sample on Samsung S7 SM-G930F with Android 8.0. ArCore app was installed successfully from GooglePlay. The hellosceneform app itself launches perfectly, but unable to find any suitable surfaces for mapping graphic icons. 
The same situation occurs while launching another sample apps. These apps are constantly in searching for surfaces, but unable to find it.
I don't know whether is a bug or not, but it's weird.

**Comment by inio** [comment]
Just to reduce variables: Could you try the Java HelloAR sample (non-sceneform)?  I expect it will fail similarly but if it works then this is a completely different class of problem.

**Comment by berkutio** [comment]
Sure, I tried to launch the HelloAR app several times, but the app simply couldn't find the surface and the snackbar with the title "Searching for surfaces..." could be seen while the app was launched. Plus, I have installed this one https://play.google.com/store/apps/details?id=com.galewgames.towerar which is said to use the ARCore library and didn't work properly as well.

**Comment by inio** [comment]
Thanks for confirming.  That's pretty surprising.  What's your build fingerprint?  You can find it by running `adb shell getprop ro.build.fingerprint`

**Comment by berkutio** [comment]
Here it is: 
user$ adb shell getprop ro.build.fingerprint
samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU2EREM:user/release-keys

**Comment by inio** [comment]
I looked at our analytics and this device doesn't look unusual.  It seems you maybe have a device that's at the edge of the normal variation in IMU and camera intrinsics.  Unfortunately there's nothing I can do to help at this time.
