### ISSUE TITLE
ARCore HelloAR example not working

### ISSUE THREAD

**Issue by rramjee** [google-ar/arcore-android-sdk#46]
Hello friends,

I’m trying to run the helloAR example for AR core on my pixel but every time I open the app on my phone, I see a blue and gray screen with a message “searching devices”. I’m new to unity and using unity 2017.2 b9. Appreciate any help with this.

Have been trying to downgrade unity 2017 versions and debugging. But not much progress.

**Comment by nathanmartz** [comment]
Please follow the [instructions on our devsite](https://developers.google.com/ar/develop/unity/getting-started), including using 2017.2b11 or later.

**Comment by rramjee** [comment]
Thanks for your response, Nathan. I ve followed the instructions mentioned in the website and with the latest available version. But, Same result.
 Now, i’m planning To build the app using android studio and check.

**Comment by rramjee** [comment]
I have once again upgraded the unity to the latest version available but all I can see is a blue screen with a message searching for surfaces and nothing else. This time I'm pretty sure I'm following the instruction provided in the site.  I have also installed the ARCore GR app which is able to detect the plane surfaces and diamond boxes.

**Comment by agarwalmukul** [comment]
I am facing the same problem. I see a blue screen with the message searching for surfaces. I am using Unity to run the ARCore example but it is not working

**Comment by OlegNovosad** [comment]
Try to find some REALLY plain surface. At some point it took me up-to 1 minute to find it.

**Comment by rramjee** [comment]
Hi Mukul,

I did couple of things, one - go to the app info of the app and check if
your app has permission to camera. If not turn it on and restart your
phone.
Two install the arcore sdk by opening it from email.

For me, giving the app permission to camera and restart made the difference.

Regards,
Ramjee

**Comment by agarwalmukul** [comment]
Thanks a lot Ramjee! I gave the app permission to use camera. Didn't need to restart the phone, just killed the process and started the app again.

**Comment by rramjee** [comment]
Glad to know Mukul. Thanks and enjoy ARcore.
