### ISSUE TITLE
How to remove image from database at runtime?  Also, how to disable?

### ISSUE THREAD

**Issue by machenmusik** [google-ar/arcore-android-sdk#464]
I didn't see this anywhere so thought I should ask.  How does one remove an image from an AugmentedImageDatabase at runtime?  As a workaround I was going to build one up without the name to be removed, but you can't get individual images out of there...

Also, how does one disable image detection once something has been found?  E.g. pass in a database with no images? Or null?

**Comment by avirodov** [comment]
Hi, this is not currently supported. Feature request bug here: #372
