### ISSUE TITLE
WorldPosition for the AnchorNode is different while hosting and resolving. Why is this the case?

### ISSUE THREAD

**Issue by rohitagarwal3011** [google-ar/arcore-android-sdk#465]
I have hosted a cloudAnchor with multiple nodes attached to it. I am saving the worldPosition of the child nodes and use them to resolve and position the child nodes. But I could see that the positioning is messed up. So I checked the worldPosition for the anchorNode which is the parent to the child nodes and I could see that the worldPosition, while it was hosted and resolved, didn't match.

**Comment by avirodov** [comment]
Hi, from the names of fields it seems you are using Sceneform. This looks like a Sceneform issue, can you please post it on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues). If not, please re-open the issue, and I will be happy to investigate further.
