### ISSUE TITLE
Hot mobile device : optimization tips request

### ISSUE THREAD

**Issue by Vivelecurry1996** [google-ar/arcore-android-sdk#467]
Hi,

I'm using ARCore 1.2 with Unity, I'm using Samsung S7 Edge and I want to experiment Cloud Anchor.
Everytime I m using an APK to test my applications, the device turns too hot in less than 5 minutes of tracking process (and I want to develop applications for children so it is a little bit complicated). 
I've tried manual pause tracking but it didn't resolve the issue. 
I 'm not a senior developer, but do you have tips for optimization to moderate overheating ? 
Thank you in advance for an answer :)

**Comment by inio** [comment]
Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
