### ISSUE TITLE
Anchor screen location cross device 

### ISSUE THREAD

**Issue by abbana** [google-ar/arcore-android-sdk#468]
Hi,

researched but still not much literature on this so I need an help please.

AIM:
Let the anchor be displayed on the (10,10) of the screen no matter the device.

Background:
I am using an identity  view matrix.
Pose of the anchor is Pose.IDENTITY composed with a translation of -50f on z.

Where I am stuck:
 I want translation on x and y to be done so that the anchor stays on the (10,10) point no matter the focus length and screen ratio.
I think the correct way to have that done is to :
-a Get the Focus length of the device
-b get the sensor ratio / screen ratio
-c calculate how many meters in length and high the camera is able to display considering the object placed at -50 meters
d- translate the object using the value found on step c

Is that approach correct and the easiest?

If yes, how I have to interpret the output of getFocalLength? I am getting something like the below:
493.43185 493.37402
Once I have that, do exist a table in which I have the amount of meters visible at 50mt distance?
How can i apply that given my camera ratio?

If no, please let us know the procedure to achieve that.

Thanks a lot.

**Comment by inio** [comment]
The intrinsics API reflects the intrinsics of the CPU image, not the virtual camera used for rendering.  Consider using [Matrix.orthoM()](https://developer.android.com/reference/android/opengl/Matrix?hl=sk#orthoM\(float[],%20int,%20float,%20float,%20float,%20float,%20float,%20float\)) to build a "projection" matrix that maps pixel coordiantes to screen coordinates.  See [glOrtho()](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glOrtho.xml) for documentation.

That said, this question really doesn't have anything to do with ARCore.  Consider taking it to StackOverflow general 3D graphics boards.
