### ISSUE TITLE
Detecting Veritical Surfaces (Walls) using ARCore

### ISSUE THREAD

**Issue by TheMachineHere** [google-ar/arcore-android-sdk#47]
Hi, 

ARCore can effectively detect horizontal surfaces. I was curious to know whether anyone has found a way to detect vertical surfaces. My app is basically trying to detect various walls and augment objects on walls.

Has anyone found any solution?

Thanks.

**Comment by nathanmartz** [comment]
Closing as dupe of https://github.com/google-ar/arcore-unity-sdk/issues/31

**Comment by inio** [comment]
Duplicate of #18
