### ISSUE TITLE
Detecting change in camera pose

### ISSUE THREAD

**Issue by arjo129** [google-ar/arcore-android-sdk#470]
Hi,
Currently I'm developing an application which requires me to track changes in camera pose. The thing is that I am comparing the pose of the camera at two different times. To do this I create an anchor between the two frames. Subsequently I try to measure rotation along the Y-axis. The problem is that the signs are inconsistent when I rotate.

**Comment by inio** [comment]
It sounds like you're on the right track.  To measure the change between poses you should be doing something like: `prevAnchor.getPose().inverse().compose(frame.getCamera().getPose())`.  From this you can then either look at the quaternion or instead use `getZAxis()` and look at the deviation from (0,0,1)

**Comment by arjo129** [comment]
Thanks! The issue was with my own code.
