### ISSUE TITLE
Detect the real object (ex Bottle) from ArSceneView and put my virtual objects (3D models) around it.

### ISSUE THREAD

**Issue by iroidapps** [google-ar/arcore-android-sdk#473]
I am using ArSceneView with "com.google.ar.sceneform:core:1.0.0" and I can easily put my 3d models after/before the surface has been detected. But what I need is to detect a real object (e.g. Bottle on my desk) from ArSceneView and put my virtual objects (3D models) around that bottle. Has anybody done it? Or is anybody here who can help me with this?

I tried it using many algorithm and several ways but still not able to detect the bottle through ARCamera. Let me know if anybody can help me with this OR looking for the same.

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
