### ISSUE TITLE
publish shared (like ARCore) library on play store

### ISSUE THREAD

**Issue by nndnnv** [google-ar/arcore-android-sdk#475]
hi, 
i'm wondering how did you guys publish ARCore library on Play Store in a way that makes it 'required' for apps that use it to download&install ARCore library prior to installing their app.
(screenshot attached, take a look on "ARCore by Google library is required and will be installed").
i have a set of apps that share some sort of library between them and i'm interested in using the same technique as ARCore library use. (meaning, different store listing for the so called "shared" library).

![screenshot_20180707-135435_google play store](https://user-images.githubusercontent.com/1218458/42410154-d35f942a-81ed-11e8-9fc9-d8be7e595c8a.jpg)

thanks.

**Comment by inio** [comment]
There is special logic in Play Store to handle the installation of ARCore along with AR-Required apps.

**Comment by Teja337** [comment]
Hi @nndnnv  Even I'm wondering how to Install Arcore along with myApp from the play store. I don't want to see any pop up inside the app. But just want to install directly with the app from play store.

Can you please let me know if you found a way to do that.
Thanks
