### ISSUE TITLE
Regression for Galaxy S7 on ARCore 1.3.0

### ISSUE THREAD

**Issue by De-Panther** [google-ar/arcore-android-sdk#478]
Model: SM-G930FD

The tracking is lost every few seconds...
Features that worked fine on ARCore 1.2.1, don't work on 1.3.0

**Comment by inio** [comment]
I've reported this internally.  Thanks!

**Comment by inio** [comment]
From @Studiociteroni [on #419](https://github.com/google-ar/arcore-android-sdk/issues/419#issuecomment-402573521):
> I've the same problem with an Samsung S8. I resolved uninstalling ARCore 1.3.0 app and reinstalling the old ARCore 1.1.0. Now the surfaces tracking works well, however I hope these problems will be fixed with the next ARCore release.

**Comment by De-Panther** [comment]
If it helps, you can send other ARCore APKs for me to check, or run a test app if you need.

**Comment by De-Panther** [comment]
Still not fixed in 1.4

**Comment by inio** [comment]
We've looked at fleet-wide analytics and can't find any change between 1.2 and newer versions.

**Comment by De-Panther** [comment]
You can't find, but I have two S7 devices with the same issues. And by other posts here it happens on other S7 devices.
I don't know how you checked this, but the fact is, since 1.3, there are tracking issues with ARCore.

If connecting to one of my devices, or installing test apk would help in solving the issue, I'll be happy to help
