### ISSUE TITLE
I want to know if Dual Camera is now helpful to ARCore?

### ISSUE THREAD

**Issue by scaleCx** [google-ar/arcore-android-sdk#480]
I want to evaluate something based on this.
Thanks!

**Comment by snarb** [comment]
The same question about the depth camera. I thought it will be very usefull for SLAM. But after reading issues it's look like ARcore does not utilizes it. Why? Estimating correct distance to the objects should be usefull

**Comment by inio** [comment]
Nope.  the ARCore team has focused on enabling AR on the widest range of Android devices.  Focusing effort to enable features found on a very small slice of devices doesn't really help that.

**Comment by scaleCx** [comment]
I Know,ThankYou.
