### ISSUE TITLE
Is there a way, where we can put the relative layout view facing the camera

### ISSUE THREAD

**Issue by bhaskard** [google-ar/arcore-android-sdk#481]
Hi 

I am working on AR app, where I use relative layout to show some content. While I am trying to place the layout in the camera, sometime it faces my camera and sometimes it faces a different direction. 

P.S: I am putting the layout in the air by this below code

```Anchor anchor = arSceneView.getSession().createAnchor(
                frame.getCamera().getDisplayOrientedPose()
                        .compose(Pose.makeTranslation(0f, -1.2f, -2.5f))
                        .extractTranslation());
        AnchorNode anchorNode = new AnchorNode(anchor);```

Making changes the makeTranslation values, will it fix this issue?

**Comment by bhaskard** [comment]
@inio ^^

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
