### ISSUE TITLE
ARCore 1.3 doesn't work on moto g6

### ISSUE THREAD

**Issue by tomaken** [google-ar/arcore-android-sdk#483]

**Comment by inio** [comment]
Could you provide more information?  This is listed as a supported device so it *should* work.

**Comment by paragbhagwat3575** [comment]
I am also gettig an error when dealing with Moto G6. Please help as i got this phone as it was supported.

![image](https://user-images.githubusercontent.com/42042557/43599030-e3e6e788-96a3-11e8-8b09-5ea5cb64d316.png)

**Comment by eddielong** [comment]
You need to enable that ABI in your build.gradle file. The sample apps only enable arm64 and x86. The armv7 architecture is in the ARCore library.

**Comment by paragbhagwat3575** [comment]
Thanks eddieLong. How do we do that? I do not see any instructions for this

**Comment by eddielong** [comment]
In the build.gradle file for the app look for the abiFilters section. To this add `armeabi-v7a`

**Comment by paragbhagwat3575** [comment]
Thanks. That worked.

**Comment by jldelaguila** [comment]
I have installed several ARCore apps and none of them success at finding any surface. I tried the solution posted [here](https://forums.lenovo.com/t5/Moto-G6-Moto-G6-Plus-Moto-G6/ARCore-support-for-Moto-G6/m-p/4133823#M1687) (using an older release of ARCore) but every time I try an app it forces me to update to the latest version. I bought this phone for the compatibility with ARCore, please help 🙏🏻

**Comment by jldelaguila** [comment]
Update: as mentioned in this [issue](https://github.com/google-ar/arcore-unity-sdk/issues/373) after restarting the device ARCore runs normally, but if you close the app and try again, it doesn't work.

**Comment by marcosdemetrio** [comment]
+1

The same here "after restarting the device ARCore runs normally, but if you close the app and try again, it doesn't work."

**Comment by woohoou** [comment]
+1 It simple does not work, any workaround?. I try installing sample apps, and build the AR Hello from unreal engine.

The only way that work was installing an old AR Core, but cannot develop with unreal engine because ask for a newer version.

**Comment by inio** [comment]
woohoou if you can reliably reproduce ARCore working with an older version and not working with a newer version (ideally 1.6, just released) please let us know.  File a new issue that clearly calls out that this is a regression.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
