### ISSUE TITLE
How to move the object with the camera

### ISSUE THREAD

**Issue by bhaskard** [google-ar/arcore-android-sdk#484]
Hi, I am creating an AR app, where im rendering a relative layout in the Camera, I want the layout to move with the camera, how can i do it.

P.S: I am placing the anchor in the air, using camera pose

**Comment by bhaskard** [comment]
@inio @gordonbrander @eitanme @richlowenberg @jsantell

**Comment by alexander-edward-ptr** [comment]
can't you just display the view over the top of the scene without using any AR?

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
