### ISSUE TITLE
How to move object from Anchor to Anchor?

### ISSUE THREAD

**Issue by dpacholczyk** [google-ar/arcore-android-sdk#486]
My use case is:
tap on the screen and save the "point" as starting anchor
tap on the screen second time and save the "point" as end anchor
push the button that will move the object from starting to end anchor
I've built my own node that is using ObjectAnimator similar like in the solar system example. My only problem is that I do not know how to determine start and end point for the the evaluator. My first thought was to take the x,y,z from Pose of start and end anchor 
```
Vector3 start = new Vector3(startAnchor.getPose().tx(), startAnchor.getPose().ty(), startAnchor.getPose().tz());
Vector3 end = new Vector3(endAnchor.getPose().tx(), endAnchor.getPose().ty(), endAnchor.getPose().tz());

```
…

```
movingAnimation.setObjectValues(startingPoint, endPoint);
movingAnimation.setPropertyName("localPosition");
movingAnimation.setEvaluator(new Vector3Evaluator());

```
but when I do that animation is done from completely different places.
I havent found any reference to inbuild tools for such operation. 
Im using sceneform
So the question is. How to make a fluent animation (a simple slide is enough) from anchor A to anchor B

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by dpacholczyk** [comment]
moved: https://github.com/google-ar/sceneform-android-sdk/issues/221
