### ISSUE TITLE
Arcore does not work in Honor 8.

### ISSUE THREAD

**Issue by elblogbruno** [google-ar/arcore-android-sdk#487]
I'm developing an AR headset and want to use Arcore as main SLAM software but it does not work with my smartphone using HiSilicon Kirin 950 processor.
Thanks

**Comment by inio** [comment]
You should contact your Android Tech Account Manager to see what's involved in starting the process.

**Comment by inio** [comment]
Whoops, misread that.

**Comment by inio** [comment]
Duplicate of #89
