### ISSUE TITLE
Does ARcore have specific requirements for sensor?

### ISSUE THREAD

**Issue by aaronqiuchiu** [google-ar/arcore-android-sdk#49]
Does ARcore have specific requirements for sensor?

**Comment by nathanmartz** [comment]
We don't require custom sensors ala Tango, but there are some hardware and software requirements. For example, phones must include a gyro, have certain timestamping behaviors, etc.

**Comment by aaronqiuchiu** [comment]
@nathanmartz  Thanks very much for response.  Could you share me the more detail requirement for sensors. example for gyro sensor:
1. need support MAX sample rate is ?
2. the sensitivity requirement is ?
...... etc
