### ISSUE TITLE
Regression on Samsung Galaxy S7 after upgrading to Android 8.0

### ISSUE THREAD

**Issue by iskrabiskra** [google-ar/arcore-android-sdk#490]
See the attached screenshots for information about my device. I have AR Core version 1.3.180604066 installed. 
The plane detection stopped working after the last OS update push by my phone carrier (T-mobile).
The Google Measure app just can't detect the surface anymore. 
![screenshot_20180717-180209_measure](https://user-images.githubusercontent.com/41344007/42847997-d7d37fb6-89eb-11e8-88a8-91ed9048886d.jpg)
![screenshot_20180717-144125_settings](https://user-images.githubusercontent.com/41344007/42847999-d806b412-89eb-11e8-8401-8aabcbbdb480.jpg)
![screenshot_20180717-144134_settings](https://user-images.githubusercontent.com/41344007/42848003-da9933c6-89eb-11e8-930d-b9c06946b053.jpg)

**Comment by inio** [comment]
Interesting.  Does restarting the device have any effect?

**Comment by iskrabiskra** [comment]
Unfortunately, restarting the device doesn't change anything.

**Comment by inio** [comment]
Wow, fast!  I've filed an internal bug with our device enablement group.  I'll update this if I hear anything back.

**Comment by rfierro223** [comment]
I have the same issue on my galaxy s7
![Screenshot_20191207-041915_Settings](https://user-images.githubusercontent.com/53139063/70374575-e1cb7080-18a8-11ea-893e-44d9ee6c4826.jpg)

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
