### ISSUE TITLE
Augmented Image anchor inconsistent

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/arcore-android-sdk#491]
Hello.

Here is a screen recording of an augmented image I'd like to use for an application I'm prototyping right now. It shows very random behaviour. Wondering what the cause might be
https://photos.app.goo.gl/rhkvi6QPWuXRqC5W6

The quality rating of the marker image reported by arcoreimg is only 30. Can this be the reason? 

Apart from the varying location of the scene as such, these are the points I like to find a solution for:

- Either the floor plan or the background move when walking towards the left of the board, so the floor pla gets covered by the background. And this even so the floor plan is actually a child node of the background and positioned quite a bit in front of the background. 

- The two images on the left are also children of the background. When all objects are added directly to the anchornode, even the 2 images are hidden depending on the location in front of the info board. So, why do nodes that are added to the same parent are moving around?

- Because the seemingly varying position of the anchornode, the model I want to position on the ground relative to the info bard is also different every time I position the model.

The source for this scene looks like this (structure is different from real code):
`// scele in areas is 1, rotation 0
 Area backgroundArea = new Area(
              R.drawable.background,
              new Vector3(0.9f, 0.001f, 0.6f));

          CompletableFuture<Texture> textureFuture = Texture.builder()
              .setSource(getApplicationContext(), backgroundArea.getResource())
              .setUsage(Texture.Usage.DATA)
              .build()
              .exceptionally(throwable -> {
                Log.e(TAG, "Unable to create texture.", throwable);
                return null;
              });

          textureFuture.thenAccept(texture -> MaterialFactory.makeTransparentWithTexture(context, texture)
              .thenAccept(material -> {
                    ViewRenderable.builder()
                        .setView(getApplicationContext(), R.layout.user_panel)
                        .build()
                        .thenAccept(infoPanel -> {
                          attachNode(anchorNode, infoPanel, infoPanelArea);
                        });

                Node backgroundNode = attachNode(anchorNode, getTextureRenderable(material, backgroundArea), backgroundArea);
                ViewRenderable.builder()
                        .setView(getApplicationContext(), R.layout.image_interactive)
                        .build()
                        .thenAccept(interactiveImage -> {
                          CropView imageView = interactiveImage.getView().findViewById(R.id.image_interactive);
                          imageView.setImageResource(R.drawable.office_schema_front);

                          attachNode(backgroundNode, interactiveImage, schemaArea);
                        });

                    Texture.builder()
                        .setSource(getApplicationContext(), textArea.getResource())
                        .build()
                        .thenAccept(textTexture -> MaterialFactory.makeOpaqueWithTexture(getApplicationContext(), textTexture)
                            .thenAccept(textMaterial -> {
                              Renderable textRenderable = getTextureRenderable(textMaterial, textArea);
                              attachNode(backgroundNode, textRenderable, textArea);
                            }));

                    Texture.builder()
                        .setSource(getApplicationContext(), mapArea.getResource())
                        .build()
                        .thenAccept(textTexture -> MaterialFactory.makeOpaqueWithTexture(getApplicationContext(), textTexture)
                            .thenAccept(textMaterial -> {
                              Renderable textRenderable = getTextureRenderable(textMaterial, mapArea);
                              attachNode(backgroundNode, textRenderable, mapArea);
                            }));
                  }
              ));
        });
  }

  private Node attachNode(NodeParent parent, Renderable renderable, Area area) {
    Node node = new Node();
    node.setRenderable(renderable);
    node.setLocalPosition(area.getPosition());
    node.setLocalRotation(area.getRotation());
    node.setLocalScale(area.getScale());
    node.setParent(parent);

    return node;
  }

  private Renderable getTextureRenderable(Material material, Area area) {
    return ShapeFactory.makeCube(
        new Vector3(area.getSize()), Vector3.zero(), material);
  }`

**Comment by inio** [comment]
I'm not sure about the scene graph stuff (try the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues) for help with Sceneform) but the tracking failure and low image quality I can help with.

First off, You should be able to improve the Augmented Image quality by adding some background texture to the sign.  It's ok to flatten /fade it in the areas with text on top, but you could dramatically improve the tracking by having more visual features in the currently flat-colored areas of the sign.  Maybe a B&W artist's rendering of what the structure looked like, or even just a photo of the site.

The video shows two different kinds of tracking issues:  

1. when the Augmented Image first is detected it seems like device motion tracking isn't working right.  I suspect if you had placed an anchor when the image was first detected we'd see it fly off to the side.
2. After the device motion tracking is working, the detected image pose isn't that stable.  This is due to the low quality reported for the Augmented Image.  More visual features will help it track better.

**Comment by michaelvogt** [comment]
@inio 
Thank you for your answer. Sorry for the late response. Having been away for volunteer work.

Unfortunately I don't have any control of the visuals of the sign. I will not be able to be on location again for this year, to temporarily place visual elements to see if this would change anything.

For the time being, I need to take the info boards as they are. I understand that the low arcoreimg rating is a problem in regards of stability of the virtual objects, but I would expect that the resulting error is not that random, as neither the marker image nor the visual appearance of the info board changes between the separate recognitions. I was there for 2 hours trying to find a pattern for ARCore's behaviour. But it was completely random all the time.

For the recognition, I would also consider the weather at that time ideal, as it was still bright but without direct sunlight that could make the recognition even harder. There also haven't been any shadows from the trees around on the board.

The width of the augmented image is set when importing it into the database.

Regarding your suggestions, this is how I create the anchor
`if (image.getTrackingState() == TrackingState.TRACKING) {
        Anchor anchor = image.createAnchor(image.getCenterPose());`

How can I recognize if the device motion tracking is working right to delay the creation of the anchor until it is working?

I could accept that the scene moves around a bit, but being placed up to a meter in front of the info board and even flying away I wonder if this is really a arcoreimg quality rating problem.

What I'm mostly concerned about is the relative movement of the objects added to the same anchor. The floor plan (ViewRenderable) is floating 10cm above the background (ShapeFactory renderable), but when moving to the left, the floor plan is still being covered by the background. Yes, the parent of the floor plan is the background.

According information from the Sceneform team around a different issue, I understood that they don't do anything special according to tracking, just using the information they get from ARCore. So I take this as an ARCore problem.

**Comment by inio** [comment]
Currently your best bet for determining if motion tracking is working is the camera tracking state.  Unfortunately we seem to be a bit generous in when we report tracking as working.  I'm trying to group issues in that category into #528.

For the relative motion question I suggest trying to reproduce that behavior without the tracked image (using regular anchor nodes) and if successful report the bug to the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by michaelvogt** [comment]
Should be able to have a look at the camera tracking state next week.

**Comment by michaelvogt** [comment]
@inio 
Did I understand you correctly, that I should use `arFragment.getArSceneView().getArFrame().getCamera().getTrackingState()` instead of `image.getTrackingState()`?

Doing so didn't have any positive effect today for me, using a marker image with arcoreimg rating of 75 on a vertical info board. I could observe most of the already reported effects.

**Comment by inio** [comment]
No, what I was saying is that we're probably reporting things (including the camera) as tracking too often.  If the camera's not tracking everything else should go not-tracking as well so using the camera tracking state should offer no advantage.

**Comment by michaelvogt** [comment]
Understood.

You still say 'probably', but surely hope that this problem is already taken care of, so it gets fixed asap.
Closing this one, will follow issue 528
