### ISSUE TITLE
Feature request: Non-flat image detection

### ISSUE THREAD

**Issue by mistrydarshan99** [google-ar/arcore-android-sdk#494]
Hello,

I have one tracker image. If I track that image it is successfully tracked. But the same image I wrap around circle than that image is not tracked. 

If I tracked image it can successfully track but now I wrap the image around pen like Cylinder.
Now I tracked image it cannot be tracked.

I know that image is wrapped 360 degrees around pen since it cannot be tracked. But is there any way to track image in such kind of use case?

**Comment by MbrownMozenix** [comment]
Hello,

Currently I'm not aware of any way to do this in ARCore.

This can be achieved using Vuforia Cylinder Targets which can work in combination with ARCore: https://library.vuforia.com/articles/Solution/Cylinder-Targets-Guide

Hope this is helps.

**Comment by MbrownMozenix** [comment]
Another potential solution may be to break down your target image to smaller component images Which can be detected individually from different angles.

**Comment by mistrydarshan99** [comment]
Thanks, for suggesting Vuforia. And according to me in android ARCore also consider this type of use case.

**Comment by karthik-h-raju** [comment]
But is the ARCore able to recognize smaller images something wrapped around a pen? From the documentation, it says that the Augmented images should be of 15x15cm. When I tried for a planar image, it did work till 8x8cm as well; anything smaller than 5cm looses the clarity as the focus is fixed in the AR camera.

**Comment by inio** [comment]
@karthik-h-raju With the just-released version 1.4 you can enable autofocus.

**Comment by claywilkinson** [comment]
Augmented images are designed to detect flat images, as @inio pointed out, you can enable the auto focus mode to detect smaller images, but even in autofocus mode, non-flat images may not have high detection accuracy.
