### ISSUE TITLE
Feature request - Occlusion

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#497]
Google DeepMind has developed a way how to reconstruct scene from photos:
https://youtu.be/oSZkDuDoFAI (basic info)
https://youtu.be/gnctSz2ofU4 (paper info)

6d.ai gaves people access to closed beta where they can do an occlusion by generating mesh from photos with vertex density 2.5cm (currently on iOS only). When I tried to build mesh from ARcore point cloud I reached a good mesh with vertex density 15cm.

Is there a chance that we get better data to do an occlusion of 3D models with real objects?

**Comment by devbridie** [comment]
No doubt you've seen it already, but ARCore provides data that can be [used for occlusion](https://developers.google.com/ar/develop/java/depth/developer-guide).
