### ISSUE TITLE
Are there any way to remove or obfuscate this log with tag "ARCORE-IS"

### ISSUE THREAD

**Issue by gamingisfun** [google-ar/arcore-android-sdk#502]
Before I begin, I'm still new to programming, especially Android Programming,
So I don't exactly know if this is possible or not, and I will try to look for the solution myself while learning if this is actually possible.
Directly to the question, I need to know if it is possible to remove or obfuscate this log with tag "ARCORE-IS" from our project, since I think I don't want user to find out that this kind of log is included in our project.

**Comment by inio** [comment]
I don't think this is really worth being concerned about.  Is there a particular class of user or PR impact you're concerned about?

**Comment by gamingisfun** [comment]
Maybe it's just the way I want things to be transparent enough as not to log anything unnecessary for the release builds.. But if maybe it's not a good reason enough, it's okay, nevermind then... 😄
