### ISSUE TITLE
How to resolve multiple cloud anchors in one go?

### ISSUE THREAD

**Issue by rohitagarwal3011** [google-ar/arcore-android-sdk#503]
This is written in google's documentation of [Working with cloud anchors](https://developers.google.com/ar/develop/developer-guides/anchors)

**Keep objects close to anchors**
When anchoring objects, make sure that they are close to the anchor you are using. Avoid placing objects farther than a few meters from the anchor to prevent unexpected rotational movement due to ARCore's updates to world space coordinates.

If you need to place an object more than a few meters away from an existing anchor, create a new anchor closer to this position and attach the object to the new anchor.

My question is that , if we host multiple cloud anchors for objects that are placed few meters away, then while we are resolving them, how can we resolve all the cloud-anchors by scanning at a particular place?

**Comment by rohitagarwal3011** [comment]
@claywilkinson  Can you please help me out with this?

**Comment by asadullahnaweed** [comment]
Hey Rohit. So sorry for the late reply. For resolving cloud anchors, you need to be looking at the rough area where the anchor was placed. You cannot resolve anchors by looking at areas other than where they were placed.

**Comment by rohitagarwal3011** [comment]
@asadullahnaweed That's true. I have implemented that and i am able to resolve anchors by scanning roughly the area where they were placed. But the problem is that if I want to place multiple objects in a big room or a big open area then I will have multiple anchors attached to objects that are closeby and so is there a way by which i can resolve the whole scene with all the anchors and child nodes in one go ? 
If i attach multiple child nodes to a single anchor and the child nodes are a bit far away then the scene is somewhat distorted.

**Comment by inio** [comment]
@rohitagarwal3011 Your question isn't really getting much uptake here because this board is for the core Java motion tracking API, not Sceneform.  If you'd like Sceneform to provide something that can average multiple anchors together or something like that, please post a feature request on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by amirtha17** [comment]
> 

how to host multiple anchors?
