### ISSUE TITLE
How to detect collision in Arcore cloud anchor in  unity?

### ISSUE THREAD

**Issue by raj244u** [google-ar/arcore-android-sdk#504]
hi, i trying to detect touch colliion after instantiate my prefab in ARcore cloud anchor in unity.Please find solution for the same . I trying with this below:- Ray raycast = Camera.main.ScreenPointToRay(touch.position); RaycastHit raycastHit; if (Physics.Raycast(raycast, out raycastHit)) { Debug.Log("Inside ray"); if (raycastHit.collider.name == "f1") { Debug.Log("f1. collider");

             }
             if (raycastHit.collider.tag == "f1")
             {
                 Debug.Log("tag. hit");

             }

// not working......

**Comment by inio** [comment]
Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
