### ISSUE TITLE
Hit test API did not take into account hit flags PlaneWithinInfinity

### ISSUE THREAD

**Issue by wangvnn** [google-ar/arcore-android-sdk#507]
I am using Frame.RaycastAll to find all the planes that are intersected with the ray from the center all the screen.
I use TrackableHitFlags raycastFilter = TrackableHitFlags.PlaneWithinInfinity;
The problem is internally this:
ExternApi.ArFrame_hitTest(m_NativeSession.SessionHandle, frameHandle, x, y, hitResultListHandle);
sometimes does not return all the valid planes.
For example: plan1 is closer and plane 2 is further.
Sometimes the API only return plane1, instead of returning both (both are valid result)
It looks like internally the API did not use the flag PlaneWithinInfinity, because If plane2 is big enough to cover the area underneath plane1, then the API returns the correct result (2 planes) otherwise it will return 1 plane only.

**Comment by inio** [comment]
Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
