### ISSUE TITLE
How can i get a bitmap from arFragment.getArSceneView().getArFrame().acquireCameraImage();

### ISSUE THREAD

**Issue by weatherfish** [google-ar/arcore-android-sdk#510]
Image image = arFragment.getArSceneView().getArFrame().acquireCameraImage();
 ByteBuffer buffer = image.getPlanes()[0].getBuffer();
 byte[] bytes = new byte[buffer.remaining()];
 buffer.get(bytes);

but  this result bytes is all 0

**Comment by Alpkant** [comment]
I
`   private static byte[] imageToByte(Image image){
        byte[] byteArray = null;
        byteArray = NV21toJPEG(YUV420toNV21(image),image.getWidth(),image.getHeight(),100);
        return byteArray;
    }

    private static byte[] NV21toJPEG(byte[] nv21, int width, int height, int quality) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        YuvImage yuv = new YuvImage(nv21, ImageFormat.NV21, width, height, null);
        yuv.compressToJpeg(new Rect(0, 0, width, height), quality, out);
        return out.toByteArray();
    }

    private static byte[] YUV420toNV21(Image image) {
        byte[] nv21;
        // Get the three planes.
        ByteBuffer yBuffer = image.getPlanes()[0].getBuffer();
        ByteBuffer uBuffer = image.getPlanes()[1].getBuffer();
        ByteBuffer vBuffer = image.getPlanes()[2].getBuffer();

        int ySize = yBuffer.remaining();
        int uSize = uBuffer.remaining();
        int vSize = vBuffer.remaining();


        nv21 = new byte[ySize + uSize + vSize];

        //U and V are swapped
        yBuffer.get(nv21, 0, ySize);
        vBuffer.get(nv21, ySize, vSize);
        uBuffer.get(nv21, ySize + vSize, uSize);

        return nv21;
    }`
I found these method from stackoverflow and it is working. It basically converts Image to byte[] so you can save the image how you want. However, resolution is 640x480 since acquireCameraImage() doesn't give better than that.

**Comment by inio** [comment]
@weatherfish What device are you using?  Please provide the build fingerprint (`adb getprop ro.build.fingerprint`).

@Alpkant ARCore 1.4 (relesed yesterday) allow configuring CPU image resolution up to the texture resolution.

**Comment by inio** [comment]
Closing for lack of response to questions.  @weatherfish if you can tell us what device you're getting the zero image on we can investigate.
