### ISSUE TITLE
Occlusion shader + changing the render priority of the camera feed

### ISSUE THREAD

**Issue by dorhananel** [google-ar/arcore-android-sdk#511]
Hello
I am working on an ARcore app in Java and I need to create an occlusion shader.
This means that the object with he shader will still block and hide other objects behind it like a normal opaque object, but will be completely invisible.
In more technical terms a shader that does NOT update the screen pixels but still writes to the Z buffer. 

I was able to get it to work **inconsistently** by using this shader:
```{
  material: {
      name : "Custom material",
      parameters : [],
      blending : "opaque",
      shadingModel : "unlit",
      depthWrite : true,
      colorWrite : false,
  },


  fragment: |||
      void material(inout MaterialInputs material) {
          prepareMaterial(material);
          material.baseColor = vec4(0.0);
      }
  |||
}
```

and setting **both** the occlusion object and the stuff I want to hide to render priority 7.

The problem is that its incredibly glitchy and will flicker with visual artifacts at seemingly random angles.

This shows it working
<img width="526" alt="screen shot 2018-08-02 at 11 01 50 am" src="https://user-images.githubusercontent.com/6863256/43592786-4bca183a-9644-11e8-9690-1fb4be3e9ac6.png">

Here are a couple of images of it breaking
<img width="526" alt="screen shot 2018-08-02 at 10 59 52 am" src="https://user-images.githubusercontent.com/6863256/43592806-5981a0c4-9644-11e8-9a06-c1de754c261b.png">

<img width="524" alt="screen shot 2018-08-02 at 11 03 08 am" src="https://user-images.githubusercontent.com/6863256/43592816-5db0ebf0-9644-11e8-8034-214afbf62774.png">

I think all I need to get it to work is to force the rendering engine to fist render the background (camera feed) then the occlusion objects, then the object i want to hide.

**I dont seem to be able to figure out how to change the render priority of the camera feed**
**Any help would be greatly appreciated **

Thanks,
Dor

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
