### ISSUE TITLE
How the point cloud was generated?

### ISSUE THREAD

**Issue by Thaina** [google-ar/arcore-android-sdk#514]
I don't know why but the current point cloud has a hard time figure out an obvious edge between floor and walls or the wooden surface. Even floor tile that has a very clear cut edge between tile, just the tile has plain color. It hardly given any point unless there was some detailed image or some messy shaped object. It also hard to generate detected plane on these surface

I had made a point viewer to see position and project confidence as a length and white color of cube (So black square means a point with 0 confidence). And it suspiciously disappointed on these result

![screenshot_20180806-124118](https://user-images.githubusercontent.com/1042507/43699184-f0a6c0b6-9977-11e8-9004-e6eef1b94e76.png)

![screenshot_20180806-124127](https://user-images.githubusercontent.com/1042507/43699185-f0d81b20-9977-11e8-96da-f95b914d5b49.png)

![screenshot_20180806-124208](https://user-images.githubusercontent.com/1042507/43699186-f104d07a-9977-11e8-8e4e-b14412d78803.png)

My point is, are there anyway I could adjust the point cloud and plane generation with ARCore? Or anyway I could have an access to raw point cloud data?

**Comment by inio** [comment]
Point clouds are created by triangulating tracked visual features.  They're intended as a debug feature for visualizing motion tracking quality and not much else.

**Comment by Thaina** [comment]
@inio But it suspiciously seem like wherever have a lot of point cloud there would be easier to generate detected plane. So I think it was correlated and so I use it as indicator to find a place that would be easier to make a first plane

The main point here is that the current algorithm have a hard time figure out the edge, be it a line of tile or the edge and corner of the room. I think these should be the high priority feature

**Comment by inio** [comment]
Plane detection works at a lower level than the point cloud generation and considers more data.  The implementation details are proprietary.  Please feel free to file a feature request  for something concrete like providing more exact boundaries on planes.
