### ISSUE TITLE
Stereoscopic rendering support

### ISSUE THREAD

**Issue by mtee** [google-ar/arcore-android-sdk#515]
This is a feature request concerning the renderer of SceneForm. For cardboard-like head-mounted AR devices it would be great to have a way to visualize the 3D scene as a stereo view. Are there any current plans for that?

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by ckeimel** [comment]
https://github.com/google-ar/sceneform-android-sdk/issues/236
