### ISSUE TITLE
Could Google create a standard SceneGraph like the iOS  SceneKit  as an alternative to 3rd party libs or enormous envirnonments like Unity and Unreal

### ISSUE THREAD

**Issue by janerivi** [google-ar/arcore-android-sdk#52]
It seems like either you have to do either
1) low level openGl stuff,  (Huge effort to learn)
2) use a third party OpenGL Scene graph or  (Big effort to learn the api of a random third party lib)
3) you have to use the huge  Unity or Unreal game enginge environments. (huge cumbersome environments with a million things you need to learn)

After having experimented with ArKit togeather with SceneKit on IOS i must say the developer ergonomics for doing basic to medium level things is far far better on the IOS platform than on the Tango or ArCore platform.

A default SceneGraph library for Android similar to SceneKit would be very helpful.

**Comment by nathanmartz** [comment]
Thanks for the feedback. We've heard this feedback from several other sources. Are there aspects of SceneKit that you find especially valuable in the context of AR? Is there anything that you wish was part of that package but isn't?

**Comment by janerivi** [comment]
@nathanmartz  except for the annoying SceneKit-prefix "SCN" in front of everything it has a very intuitive ways to set up a tree of nodes, textures, lights, and animation. You can program a moving solar systems in a few lines of code. This means you can do a whole lot of basic to medium level 3d-graphics with a very small investment and no third party stuff. Sure if you are going to create a huge game environment with tons of game assets and very high end effects, then Unity or Unreal environment will be worth the hassle and be more convenient in the end. But for the typical case it is really overkill and a cumbersome development setup.

**Comment by iTruff** [comment]
Hi, @radvani, thanks for your answer, i think, you saved my day (or life) :)

**Comment by tillkrempel** [comment]
The Tango examples used the Rajawali library (https://github.com/Rajawali/Rajawali), which works quite well for most basic features.

**Comment by xiaowu4** [comment]
I strongly agree it. I think many developers aren't familiar with OpenGL, if they have to use the Android SDK, it's horrible to render the 3D model and other operations.

**Comment by geosky** [comment]
Rajawali is no match for Scenekit in iOS, tons of efforts need to be done.

**Comment by thomasflynn** [comment]
Take a look at gearvrf.org and https://github.com/Samsung/GearVRf.  Loads many file formats, resonance audio extension, bullet physics extension, open-source and royalty fee.  We'll add an example with ARCore in the coming weeks.

**Comment by AlagicAmir** [comment]
SceneKit for Android would be nice when we have to develop applications that need to have some kind of 3D in it. Should be easy to use as SceneKit within regular native app so that we can use advantage of other libraries as well as Java/Kotlin without need to use Unity and C#/JS just because we need one screen where we have 3D.

**Comment by fxsalazar** [comment]
[Sceneform](https://developers.google.com/ar/develop/java/sceneform/) to the rescue... #Closed

**Comment by inio** [comment]
@fxsalazar You beat me to it.

**Comment by fxsalazar** [comment]
@inio Months waiting for this................ !!!!!! 🤓

**Comment by JessHolle** [comment]
Okay, so SceneForm to the rescue, but...

What does one use on Android devices that don't support ARCore?  What about VR usages?  Where's the grand-unified-theory easy-button that works on all recent Android devices, e.g. Android 5 and up for both VR and AR?

Or am I missing something and sceneform is that?

**Comment by JessHolle** [comment]
Ah, it seems that the SceneView class now solves this for Android 7+ as long as the device supports OpenGL 3.1.

**Comment by uwemeier-sclable** [comment]
> [Sceneform](https://developers.google.com/ar/develop/java/sceneform/) to the rescue... #Closed

And it's gone!
Well, technically Google only discontinued support and [made it open source](https://developers.google.com/sceneform/develop/), but that's a euphemism for *it's dead*, imho.

[ViroCore](https://viromedia.com/virocore/) also looks kind of low on support with the last commit mid of May.

**Comment by JessHolle** [comment]
It would be really helpful if Google would shed some light and some clarity on their direction here.

Yes, it seems clear that they've "washed their hands" of Sceneform.  They open sourced it but without any real attempt to foster a community or get it rolling -- so it's effectively dead unless/until this happens.

What's not clear is why and where they're going from here.

1. What's the future of Filament?  It looks like Google put some serious effort into this renderer and covered all the bases except DirectX/D3D (which as best I can tell isn't _really_ covered by them covering Vulkan for Windows/UWP devices that are locked down such that you can't install Vulkan drivers).
2. What's the vision for a higher-level Java/Kotlin scene graph API if it's not Sceneform?  Is there one?  Or is it that everyone should just give up on any path other than using Unity or Unreal?

**Comment by chris-hatton** [comment]
+1 to everything @JessHolle said.  I'm interested in making some early developments towards 'metaverse' style Apps where the AR/VR UI is declared, by wrapping a Scenegraph in Compose.  However there doesn't seem to be any obvious choice for 3D graphics on Android at the moment, which is a sad situation for the platform.

**Comment by JessHolle** [comment]
Perhaps Google decided not to fight Unity for this the higher-level scene graph turf??

**Comment by hannesa2** [comment]
> [ViroCore](https://viromedia.com/virocore/) also looks kind of low on support with the last commit mid of May.

Just to mention it. Virocore was moved to https://github.com/ViroCommunity/virocore but it still comes with less maintainer attention.

**Comment by yshean** [comment]
> > [ViroCore](https://viromedia.com/virocore/) also looks kind of low on support with the last commit mid of May.
> 
> Just to mention it. Virocore was moved to https://github.com/ViroCommunity/virocore but it still comes with less maintainer attention.

Also the documentation site is not working. So I continued to look more an alternative and found this: https://github.com/SceneView/sceneview-android

Anyone gave that a try? What's your verdict?

**Comment by hannesa2** [comment]
> Also the documentation site is not working. So I continued to look for an alternative and found this: https://github.com/SceneView/sceneview-android

I would not count too much on documentation. For me a lot of running examples are important. 
Btw, the documentation is working for me 
https://virocommunity.github.io/
https://virocommunitycore.readme.io/docs
