### ISSUE TITLE
Incompatible app in play store  

### ISSUE THREAD

**Issue by basitsaleemmb** [google-ar/arcore-android-sdk#521]
@inio 
I have published an app on play store with optional AR feature but it still says incompatible app with your version

**Comment by inio** [comment]
I take it you figured this out?  May I ask what the problem was?

**Comment by basitsaleemmb** [comment]
thanks @inio  for you reply.
 Now, I figured this out

**Comment by joreilly** [comment]
@basitsaleemmb What was the issue?  I'm running in to I think is same issue right now

**Comment by basitsaleemmb** [comment]
Just comment <uses-sdk ..> from manifest file then it will work perfectly
