### ISSUE TITLE
request to lift the 24 hour limitation for resolving Cloud Anchor

### ISSUE THREAD

**Issue by hhung516** [google-ar/arcore-android-sdk#523]
Hello,

I know this has been asked a few times here   (#442, #378, #373) but since those issues are now closed for inactivity, I'd like to submit it as a new issue/request.

We are building an application for corporate users where the AR scene is shared among several devices. It would be really important to have the 24 hour limitation lifted, so Cloud Anchors can be resolved for a much longer period of time.

Why the 24 hour limit?

Couldn't Google come up with an additional pricing plan to make the hosted anchor data to be persistent? Is there any technical difficulty doing that?

Just charge more $$$ and make it happen, so everyone wins.

**Comment by inio** [comment]
I've recorded this as a feature request.

**Comment by hhung516** [comment]
Hi there,

Any updates regarding this feature request?

Now with the iOS 12 release, ARKit 2 is available on millions of devices which allows apps to save and load world-mapping data locally on the device, and also share with near by devices.

Really hope Google can soon take ARCroe up a notch by offering more features, including to lift the 24 hour limit on resolving Cloud Anchors, in order to compete with Apple.

**Comment by TechyMitch1** [comment]
Hello there,

Are there any updates on lifting the time limit for cloud anchors? I'd really like to be able to utilize them for persistent anchors, but the 24-hour time limit and lack of ability to serialize and/or deserialize them locally is quite prohibitive. Are there any plans to release such a feature soon? I'd also love ARCore to be able to compete with Apple and Microsoft's solutions, but this missing feature presents a bit of an issue.

**Comment by dblatner** [comment]
I suggest to completely remove the 24h limit, so one could build truly persistent experiences like MS is doing with Spatial Anchors. This would be then a complete cross-platform solution, because ARCore also supports iOS... just think about it Google ;-)

**Comment by shawmakesmusic** [comment]
Hey guys, posting here.

You've made a powerful product that could really power a whole new set of applications -- except it won't because of this limitation. We can't even start building because we're not sure if it'll be a usable platform in the future, especially with Azure Spatial Anchors which don't have this limitation.

**Comment by aurangzaibumer777** [comment]
> Hey guys, posting here.
> 
> You've made a powerful product that could really power a whole new set of applications -- except it won't because of this limitation. We can't even start building because we're not sure if it'll be a usable platform in the future, especially with Azure Spatial Anchors which don't have this limitation.

so is *Azure Spatial Anchors* support private cloud to relocalize the anchors? or azure's cloud for no time limitation?

**Comment by devbridie** [comment]
The 24h limit has been lifted, see [Session. hostCloudAnchorWithTtl()](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#hostCloudAnchorWithTtl(com.google.ar.core.Anchor,%20int)).
