### ISSUE TITLE
[QUESTION] How are transformations handled in HelloARJava

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [google-ar/arcore-android-sdk#524]
All the objects placed in the AR Scene has to maintain a position in which it is placed .i.e., on an anchor. How exactly the transformations (Translation, Rotation and Scaling with respect to the camera position) of the object placed in the AR Scene is handled (in the sample app HelloARJava) when the camera moves around.? 

I know this involves some amount of matrix math (with viewmtx, projmtx and anchor matrix) and OpenGL, an explanation with a simple code snippet (or perhaps a permalink to the code that performs this) will help or if shaders does it, a crisp explanation of how it works would be great.!

Thanks.

**Comment by SyamSundarKirubakaran** [comment]
cc: @inio @jwmcglynn

**Comment by inio** [comment]
Sorry about the slow response on this.

I suggest you read up on the Model, View, and Projection matrices and how OpenGL uses them.  [Here's one example a quick googling turned up](http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/#the-model-view-and-projection-matrices).

For the case of ARCore: the camera provides the Projection and View matrices (describing the field of view of the lens and position of the lens in the world) and anchors provide the Model matrix (describing the location of the fixed point.
