### ISSUE TITLE
How to move object with user drag?

### ISSUE THREAD

**Issue by rlarlvy153** [google-ar/arcore-android-sdk#526]
hello, I'm working on Anchor cloude example.

i put an object at the position of Anchor (hosting mode and resolving mode)
using onTouch -> ACTION_MOVE event, moved the object to the direction of user drag.

on portrait orientation, it is exactly moving to right direction.

but landscape, it moves wrong direction .
it is because android onTouch -> ACTION_MOVE event gives just x, y pixel no matter what the orientation is..

i moved the object with this process

`
redAndroidOffset[0] += dragOffsetX;
                redAndroidOffset[2] += dragOffsetY;

MODEL_MOVE = Pose.makeTranslation(-redAndroidOffset[0] ,redAndroidOffset[1], -redAndroidOffset[2]);
anchor.getPose().compose(MODEL_MOVE).toMatrix(anchorMatrixBesideRed,0)

;`

how can i move the object right direction ?..

**Comment by Canato** [comment]
@rlarlvy153  a suggestion that's not really the answer, but probably a better User Experience.

First you make the user select the object, but he don't need to drag it around, the user just need to select a new place. And you change the object anchor. In this way the user can select a object and walk free, without hand on cellphone, until the next point and release there.

**Comment by rlarlvy153** [comment]
yeah, i agree your suggestion. So, i tried it.

user clicked somewhere on the screen, then with HitTest, the first hit object(plane or point) will be an my custom object.
then, isn't the object's Pose world coord. ?

i got the Pose of hit object, and shared the Pose's T, R to nearby another phone(it is resolve mode)
but my object had different position ( a little bit diff..)

why is it different ?

**Comment by rlarlvy153** [comment]
then um...
dose the scene form sample have shared AR feature ??

i need shared and moveing something with same place in two phone..

or
do i have to merge cloude anchor and scene form ?

**Comment by Canato** [comment]
@rlarlvy153 

Yes you will need to program/code the Cloud Anchor with the Sceneform, I don't remember any sample with both, but your can be the first \o/

**Comment by rlarlvy153** [comment]
okay I'll try it.
thank you for nice ~ help :)

have a good time!!~

**Comment by inio** [comment]
Thanks @Canato for helping with this one.  

@rlarlvy153 I think it's worth filing a feature request on [Sceneform's issue board](https://github.com/google-ar/sceneform-android-sdk/issues) for some sort of drag & drop placement helper.
