### ISSUE TITLE
Instant Preview Not Connecting But Device Is Connected

### ISSUE THREAD

**Issue by Dodecadaemon** [google-ar/arcore-android-sdk#529]
I've been using ARCore and Unity to develop an app for a few months and was having a great time developing with Instant Preview until recently. For whatever reason no matter what I try I'm unable to get the ARCore Instant Preview app to show any status other than "Not connected to editor" with a red box.

Usually restarting my device and computer would solve this issue, but I've been doing that for days now without success. I can see my device listed as connected in ADB, and I've tried both USB and WIFI connections. I know it's connected because launching the app in Unity causes the Instant Preview app to open up or install if I've uninstalled it.

I'm at my wits end on what could be going on here. I'm running Unity 2018.2.3 on Windows 10, and my device is a Pixel XL running the latest Android 9 (Pie). I made several new projects and imported the latest ARCore unity package, but they all experience the same issue even when I create them in 2018.1.9.

Logcat hasn't been much help either, attached is a snippet of the output from when I try and run the app through Unity. It throws hundreds of "io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException" errors at the end, but I can't tell where it broke before that.

Thanks for reading, any help you could provide would be greatly appreciated.

[logcat.txt](https://github.com/google-ar/arcore-android-sdk/files/2285468/logcat.txt)

**Comment by inio** [comment]
Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).

**Comment by abhinav22rana** [comment]
Hi,

I also have faced this issue. Resolved by using previous version of AR core plugin.

Try ARCore 1.3 unitypackage. Hope it will help you.

**Comment by fredsa** [comment]
Specific issue to follow here:
https://github.com/google-ar/arcore-unity-sdk/issues/206

**Comment by vinayak-vc** [comment]
05-14 11:50:08.448 23458 23483 I InstantPreviewConnection: trying reconnect
05-14 11:50:08.448 23458 23483 I InstantPreviewConnection: onError: io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException

I am getting this kind of error in adb logcat
