### ISSUE TITLE
Arcore error on honor 10

### ISSUE THREAD

**Issue by Spani888** [google-ar/arcore-android-sdk#531]
Hi there,

i bought a Honor 10. Current firmware 8.1.0. The phone can't handle AR apps. (Aruler, Measure AR, Prime Ruler- AR based option). I run AR test app, and sad me this phone doesn's support AR. Can anybody help me? 

Thanks in advance

**Comment by inio** [comment]
1. Did this device ship with the Play Store?  If not, and this is a Chinese device, then it is [not currently supported](https://developers.google.com/ar/discover/supported-devices#android_china).
2. Could you please provide the build fingerprint?  This can be retrieved by running `adb getprop ro.build.fingerprint`
3. Open a browser on the device and load this URL: https://play.google.com/store/apps/details?id=com.google.ar.core.  It should launch the Play Store and provide more information about why your device is producing an unsupported code (not compatible with this version, not available in your region, etc.)

**Comment by Spani888** [comment]
Hi, 
sorry for the late, but it's a bit difficult to me do that things described above. (i dont used Android Studio ever).

1. I have Play Store on my phone, and other other named: Appgallery (i think it is the huawei store or something) If i start an app, one with needs Arcore, the phone ask me where should it downloaded from. Play Store can download it, Appgallery says This app is not available in this region. 

2. There is the fingerprint:
C:\Users\Spani\AppData\Local\Android\Sdk\platform-tools>adb shell getprop ro.build.fingerprint
HONOR/COL-L29/HWCOL:8.1.0/HUAWEICOL-L29/120(C432):user/release-keys

3. If open ur link ARcore says me: I have several devices which compatible with the app. If i click there, show me: Huawei COL-L29.

**Comment by pappd** [comment]
Hi,

I have the same problem. According to the official list of supported device Honor 10 shall run ARCore. I bought my device in Europe in this week and Play Store show me that my device is supported and I can install from Play Store. In spite of this I can’t use any ARCore apps, I get several error messages. I tried to install manually v1.3.0 but it didn’t help, the apps require the latest version.

Device ID: COL-L29 (C432) Android 8.1

Thanks your help is advance!

**Comment by Spani888** [comment]
Hi, 
I got an firmware updtate juat now. Now it works.

**Comment by inio** [comment]
Sounds like this is fixed?
