### ISSUE TITLE
ARCore 1.4.0 critical issue on sync / compilation

### ISSUE THREAD

**Issue by OlegNovosad** [google-ar/arcore-android-sdk#532]
Stackoverflow thread is [here](https://stackoverflow.com/questions/51858588/android-arcore-in-emulator-issue/51872844#51872844)

Basically this occurred when I updated my project ARCore and Sceneform to 1.4.0 version. During build I received next issue:

**Class content provided for type descriptor com.google.ar.core.h actually defines class com.google.ar.core.H Message{kind=ERROR, text=Class content provided for type descriptor com.google.ar.core.h actually defines class com.google.ar.core.H, sources=[Unknown source file], tool name=Optional.of(D8)}**

Was not able to Google it so the only thing I tried after all recommendations on similar issues - downgrade version and it started to work.

**Comment by inio** [comment]
That's pretty odd.  We'll look into it.

From the SO post: you got this error when building for the x86 emulator, right?  I don't think architecture would affect clearly Java-related build-time issues, but just in case it matters I want to document that.

**Comment by inio** [comment]
On the upside, congrats on being the first person to ever ask about this diagnostic message!

**Comment by inio** [comment]
This is starting to sound like your build system might be part of the problem.  Try turning off proguard and any other postprocessing and see if that changes anything.

**Comment by OlegNovosad** [comment]
Funny thing. I tried to disable proguard and it did not help. The thing helped is answered at StackOverflow [here](https://stackoverflow.com/a/51208713/1378564)

Firebase Performance Plugin was causing a lot of troubles and after adding to **app** gradle file this:

```groovy
if (!project.gradle.startParameter.taskNames.any { taskName ->
    taskName.toLowerCase().contains('assemble') && taskName.toLowerCase().contains('debug') }) {
    apply plugin: 'com.google.firebase.firebase-perf'
}
```

and to **main** gradle file this:

```groovy
if (!project.gradle.startParameter.taskNames.any { taskName ->
    taskName.toLowerCase().contains('assemble') && taskName.toLowerCase().contains('debug') }) {
    classpath("com.google.firebase:firebase-plugins:1.1.5") {
        exclude group: 'com.google.guava', module: 'guava-jdk5'
    }
}
```

Issue disappeared. But still it would be great to have more descriptive error messages in such cases.

**Comment by efthymios1991** [comment]
@OlegNovosad Did you manage to solve this one? I am getting a similar error caused by the firebase-performance as well
