### ISSUE TITLE
ARCore not supported on Sony Xperia XZ2 compact although listed in supported devices?

### ISSUE THREAD

**Issue by vicung** [google-ar/arcore-android-sdk#536]
Google has updated the list of supported devices and added the Sony Xperia XZ2 Compact with the annotation that Android 8.0 or later with software update after Aug 2018 (security patch level 2018-08-05 or later) is required.
However when I open ARCore on my XZ2 Compact in the Play Store there's still a message that my device is not compatible with this version. I downloaded and installed the latest ARCore.apk manually but still can't open any ARCore Apps (I used JustLine to test and it closed the app with the error message  "ARCore was terminated")
I have the latest software update with Android 8.0.0 (Build 51.1.A.11.26) installed and checked for Updates but there are none.
Upon further investigation I noticed that my latest security update is from Aug 1st 2018 and the required security patch level 2018-08-05 isn't even released yet. Maybe it will prevent some confusion if you add this device only after the requirements can be actually fulfilled or is there a way to get this security patch?
![screenshot_20180823-132845 1](https://user-images.githubusercontent.com/1176013/44522982-9bb0c480-a6d8-11e8-9729-df05df976c6a.png)

**Comment by inio** [comment]
Based on your mention of "ARCore was terminated" I wonder if your device **shipped with the Google Play Store**.  Devices distributed in China not on the list of devices specifically supported in china are not supported.

**Comment by vicung** [comment]
Thank you for your reply. The company I'm working for provided me this device and we are based in Germany. I am sure they buy the company devices from official german adistributors but I'll ask the department too.
Does this restriction only apply to the distribution and usage location or also to the manufacturing location? I'm not sure if the phone is manufactured in China (some parts most probably are) but I'll check if I can find some information on the package or manual.

**Comment by inio** [comment]
Hmm, that's interesting.  I suppose we might have listed this one a bit early then.  I'll ask the device enablement group and get back to you.

**Comment by Benji6974** [comment]
I actually have the same problem, I buy it in official company in France. I noticed that the numbers between USA and Europe / Asia are not the same. For example in the USA there is only with one sim H8314 and Europe + Asia is with double sim H8324 ,I think the sim does not affect the AR ^^

**Comment by inio** [comment]
This should have been fixed with ARCore 1.5.  Please let us know if you still have issues on these devices.
