### ISSUE TITLE
how can i load sfb model to view in normal fragment? 

### ISSUE THREAD

**Issue by rhonip** [google-ar/arcore-android-sdk#541]
ModelRenderable.builder()
    .setSource(this, R.raw.andy)
    .build()
    .thenAccept(renderable -> andyRenderable = renderable)
    .exceptionally(
        throwable -> {
        Log.e(TAG, "Unable to load Renderable.", throwable);
        return null;
    });
i want to render/view the above model in fragment without Arfragment. just to view the model with touch event.

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
