### ISSUE TITLE
Sceneform ArFragment Auto Permission Handling messing with MULTIPLE PERMISSION

### ISSUE THREAD

**Issue by MuhammadAasharib** [google-ar/arcore-android-sdk#543]
Hi,
I am trying to take multiple permissions. But when I first time run app after installation app pops up "request permission" windows only for ARCore Camera permission. When I open application for next time then it asks for remaining permissions.
My question for developers is whether sceneform sdk messes with the permissions I set in the android manifest?

Thankyou.

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
