### ISSUE TITLE
[improvement] Option for appearance of detected planes

### ISSUE THREAD

**Issue by jumpjack** [google-ar/arcore-android-sdk#545]
It would be useful to enable the user to change appearance of detected planes: transparency, color, dots size/shape,...

**Comment by inio** [comment]
ARCore does not directly provide visualization of detected planes - that's entirely implemented in our sample code which you are free to change as you wish.

If this request is about behavior of SceneForm, please post it to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
