### ISSUE TITLE
Nokia 6.1/Nokia 6 (2018) Support?

### ISSUE THREAD

**Issue by Kostya-OniL** [google-ar/arcore-android-sdk#548]
I can see Nokia 6.1/Nokia 6 (2018) in the supported device list. Despite of that I can not make work sample project HelloAR for Unity on my phone. It seems that plane is not detected and visualized. My configuration:
-Nokia 6 2018(model TA-1043)
-Android 8.1.0
-ARCore 1.4.18
Could please provide any comments? Is it valid configuration and the phone model supported by ARCore?

**Comment by inio** [comment]
What's the build fingerprint of your device?  `adb shell getprop ro.build.fingerprint`.

**Comment by Kostya-OniL** [comment]
Nokia/Plate2_00WW/PL2_sprout:8.1.0/OPR1.170623.026/00WW_2_22J:user/release-keys

**Comment by inio** [comment]
Sorry I haven't gotten back to you sooner.

Are you still experiencing issues?  Does restarting the device improve anything?  Could you provide a screen recording and/or logcat dump while the problem is occurring?

**Comment by Kostya-OniL** [comment]
I have just updated Unity and Android Studio to the newest version and it works. The problem might have been because of ..\Android\Sdk\tools. There was an issue with it and I used older tools version to build .apk file as it did not work with default one. But now everything it OK. Thanks for supporting my case. I am happy now)
