### ISSUE TITLE
ViewRendrable with an imageview only showing one image 

### ISSUE THREAD

**Issue by Hssine095** [google-ar/arcore-android-sdk#549]
When i create 2+ viewRendrables with imageview (one rendrable for each image detected)  only the first one shows an image the others only show one color.

![screenshot_20180903-145207_ardemo](https://user-images.githubusercontent.com/11528598/44990508-1f946780-af89-11e8-907e-19a512e9a110.jpg)

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
