### ISSUE TITLE
the main reason why ARcore limited to a few devices only

### ISSUE THREAD

**Issue by anewnewworld** [google-ar/arcore-android-sdk#55]
could you please briefly share why only a few devices are allowed to launch ARcore?
is it limited to certain sensors? or need extra calibration data? or what?

**Comment by nathanmartz** [comment]
We wanted to get the ARCore preview out as early as possible so that developers could start building and learning as quickly as possible. Each device takes time to calibrate, so we wanted to start with a couple of popular, high quality phones, and then expand afterwards.

**Comment by uchennafokoye** [comment]
Is Samsung s8+ supported (SM-G95U). I tried to run the sample after installing following the install and I get, "This device does not support AR."
