### ISSUE TITLE
How to make my instantiated game object to face me ?

### ISSUE THREAD

**Issue by Shahrukh95** [google-ar/arcore-android-sdk#552]
I have instantiated an object onto a detected plane. I have a joystick that also moves that object. I want that object to always face the camera as the user moves his/her phone around. In my PlayerController script I added this code:

```
	public Camera firstPersonCamera;

	void Update(){
		//Rotate Player as camera is rotated by the Player
		transform.LookAt(firstPersonCamera.transform);
	}
```
In the inspector, I add the "FirstPersonCamera" prefab provided by ARCore to this script. However, the object does not face me.

The objective here is to rotate the object as the camera moves so that the joystick I have added that moves the object, always moves it the correct way no matter from which angle the user is viewing it.

**Comment by inio** [comment]
Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
