### ISSUE TITLE
How to make the detected plane not overlapping each other

### ISSUE THREAD

**Issue by sadbacon1148** [google-ar/arcore-android-sdk#554]
My model is a cave that has an invisible cube (cube with depthmask shader) under the it. It works fine when there's no overlapping but whenever the detected plane was overlapping each other the invisible seems to be visible, can anybody help? Thank you in advance.

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
