### ISSUE TITLE
Set Default Configuration

### ISSUE THREAD

**Issue by cvasquez-github** [google-ar/arcore-android-sdk#558]
Is there a way to set the default/global configuration, I mean the default setting, not per session?
Like being able to change the default FocusMode from Fixed to Auto?
Thanks

**Comment by inio** [comment]
Nope, and we don't really see a value in this setup.  Is the a particular use case you're thinking of?

**Comment by cvasquez-github** [comment]
That would be very useful specially when using a third party library/sdk that uses ARcore technology without exposing its settings. For instance, Vuforia SDK, that supports ARcore for improved surface detection but does not provide access to ARcore settings like FocusMode, so it is Fixed by default, preventing a proper tracking of objects and patterns. Having a direct way to access the default/global configuration would fix that problem.

**Comment by inio** [comment]
Please file a request with that library to either expose the setting or expose the Session object so that you can change the configuration..
