### ISSUE TITLE
MI 6x Updated to MIUI10 still not support

### ISSUE THREAD

**Issue by LJHhahaha** [google-ar/arcore-android-sdk#559]
I am a Unity user,my phone is XIAOMI 6X, I have tried befor update MIUI10,  yesterday  i updated to MIUI10， i tried again，still black screen， little disappointed。

**Comment by inio** [comment]
The Xiaomi 6X is not on our [Supported Device List](https://developers.google.com/ar/discover/supported-devices).

**Comment by inio** [comment]
Duplicate of #89
