### ISSUE TITLE
Change the camera configuration

### ISSUE THREAD

**Issue by nativ18** [google-ar/arcore-android-sdk#56]
Hi, how can I change the camera configuration(like we usually do with camera.getParameters()) 
or at least get a reference to the camera instance?

By configuration I mean - picture resolution, preview resolution, bitrate, white balance and so on

**Comment by nathanmartz** [comment]
This is not supported in ARCore as we need to maintain control over these parameters to maximize tracking quality. Can you give more context about what kind of control is most critical for you?

**Comment by nativ18** [comment]
Thanks for the quick answer. The most important parameters for us are the picture_size, quality and preview_size.

Can you please elaborate on how do you choose the above 3 in AR session?

**Comment by nathanmartz** [comment]
If you want to get the camera image data, use [Session.setCameraTextureName()](https://developers.google.com/ar/reference/java/com/google/ar/core/Session.html#setCameraTextureName(int)). You can blit that into whatever format you like, save it, etc. 

Regarding getters and setters for the camera, we're looking into APIs for this in the next update, but there are limits to how much control we can give while maintaining tracking.

**Comment by inio** [comment]
With Developer Preview 2, we've added [computervision sample code](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision) that shows how to get CPU access to the pixel data.

**Comment by inio** [comment]
Duplicate of #153

**Comment by sniejadlik** [comment]
I am trying to run ARCore 1.0 on my ASUS AR phone (insert disgruntled tango development rant here)
When I run any of the tango apps the image is brighter than when I run the ARCore apps.  I cannot even get my camera to show any details without full sunlight, any shadows are super dark and useless for detecting points for tracking.  There clearly is/was a setting in Tango that allowed for exposure of the camera that is not available in ARCore. What are my best options for getting this to work correctly?
