### ISSUE TITLE
Failure INSTALL_FAILED_VERSION_DOWNGRADE

### ISSUE THREAD

**Issue by sorianog** [google-ar/arcore-android-sdk#560]
Hello all,

I'm going through the [ARCore Cloud Anchors tutorial](https://codelabs.developers.google.com/codelabs/arcore-cloud-anchors/#1). I am attempting to push the ARCore apk for a physical device, Google Pixel Android 9 and I am getting the following adb error:

`adb: failed to install ARCore_1_2.apk: Failure INSTALL_FAILED_VERSION_DOWNGRADE`

This error also occurs with the 1.4 version of the sdk.  Does anyone have a fix?

Thanks!

**Comment by inio** [comment]
This step is no longer required.  I'll have the docs updated.

**Comment by sorianog** [comment]
@inio Quick response. Wow! But I already opened this...
https://github.com/googlecodelabs/arcore-cloud-anchors/issues/5

**Comment by devbridie** [comment]
Docs have been updated.
