### ISSUE TITLE
Unity - AR Session not compatible with GLTF

### ISSUE THREAD

**Issue by philmaas** [google-ar/arcore-android-sdk#562]
https://github.com/KhronosGroup/UnityGLTF/issues/235

With the GLTF plugin enabled for android, every scene with an AR Core session crashes on launch after the unity splash screen.
Not sure how to debug this or what the issue is.

**Comment by philmaas** [comment]
this seems to be resolved using the json .dll from this package instead of the one from the build, in case anyone encounters this issue. 
https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347
Working on ios and android now. A il2cpp compiler error on ios gave me the hint, that the issues might be with the newtonsoft.json.dll

**Comment by inio** [comment]
Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
