### ISSUE TITLE
Software to create similar model used in ARCore?

### ISSUE THREAD

**Issue by eugenepeh** [google-ar/arcore-android-sdk#564]
First time working with 3D modeling here,

May I know what kind of software will allow me to create a model like [andy](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/hello_ar_java/app/src/main/assets/models) demo'ed in HelloAR?

Thank you.

**Comment by inio** [comment]
This is a fairly simple 3D model that could be created in Almost any 3D modeling package.

However, ARCore's sample code is only intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding.  Content creation to work with the example asset loading code is not within the scope of this forum.

**Comment by khurramengr** [comment]
@inio i just want to place simple **Arrow** instead of the **Andy** object, but i couldn't find any example of how to get .png diffused texture file from .obj file.
Can you please guide me further?
