### ISSUE TITLE
ARCore should utilize `-flattenpackagehierarchy` before releases

### ISSUE THREAD

**Issue by exallium** [google-ar/arcore-android-sdk#566]
I'm sorry if this is the wrong place, but ARCore does not flatten heirarchies, and happens to use obfuscation before release.  This can cause conflicts with other pre-obfuscated libraries.

**Comment by inio** [comment]
Thanks for the suggestion.  We'll look into adding this to our Proguard config.

**Comment by inio** [comment]
We've gone with -keeppackagenames for the SDK.  That should solve the problem as well, right?

**Comment by exallium** [comment]
Yes! this should still resolve the packaging conflict.

**Comment by inio** [comment]
This is fixed in ARCore 1.6 which was released yesterday.
