### ISSUE TITLE
how to draw more andy model? (native AR Cloud)

### ISSUE THREAD

**Issue by rlarlvy153** [google-ar/arcore-android-sdk#567]
i wanna draw another andy model beside anchor andy

In java version, I could draw another andy with 
getAnchor pose, compose translation and rotation, draw...

but native version, i cannot draw another andy.
plz give me a short sample with translation and rotation

thank you

**Comment by inio** [comment]
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.

Consider using [Sceneform](https://developers.google.com/ar/develop/java/sceneform/), Unity or Unreal if you're looking for more engine-level capabilities.
