### ISSUE TITLE
 Crash due to java.util.concurrent.TimeoutException thrown in Session.nativeDestroySession

### ISSUE THREAD

**Issue by shaulabalqis** [google-ar/arcore-android-sdk#569]
Hi, I'm experiencing this crash issue in ARCore v1.4.0

FATAL EXCEPTION: FinalizerWatchdogDaemon
E/AndroidRuntime(26426): java.util.concurrent.TimeoutException: com.google.ar.core.Session.finalize() timed out after 10 seconds
E/AndroidRuntime(26426): 	at com.google.ar.core.Session.nativeDestroySession(Native Method)
E/AndroidRuntime(26426): 	at com.google.ar.core.Session.finalize(Unknown Source:10)
E/AndroidRuntime(26426): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
E/AndroidRuntime(26426): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
E/AndroidRuntime(26426): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
E/AndroidRuntime(26426): 	at java.lang.Thread.run(Thread.java:764)

This issue happen randomly. I reproduce it by opening and closing the AR feature in my app a few times.  The device I use is Google Pixel XL fw 9 (device finger print : google/marlin/marlin:9/PPR1.180610.009/4898911:user/release-keys). But as I see in Fabric, this issue is not restricted to this specific device. This issue also happen in ARCore v1.3.0. Can you please help me find any resolve to this? Your help will be appreciated.

**Comment by shaulabalqis** [comment]
You're welcome. Also, can you please tell me the estimated time for the fix and when is the next release?

**Comment by inio** [comment]
This should be fixed with [ARCore 1.5](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.5.0) which was released today.
