### ISSUE TITLE
New preview update?

### ISSUE THREAD

**Issue by Ernie1998** [google-ar/arcore-android-sdk#57]
Would there be any new update for ARcore preview? Or the next release would be the public release version?

**Comment by hanhailong** [comment]
@Ernie1998 The waiting time is too long，and the flowers are all thanks...

**Comment by lvonasek** [comment]
I read on G+ that there will be update before the end of the year but it will be still preview release... Do not expect much.

**Comment by AliShug** [comment]
Any news would be reassuring. @nathanmartz Can you enlighten us?

**Comment by avirodov** [comment]
Developer preview 2 is now available.
