### ISSUE TITLE
ArPlane_getPolygonSize number of elements question

### ISSUE THREAD

**Issue by markreidvfx** [google-ar/arcore-android-sdk#571]
I get how to use ArPlane_getPolygonSize and divide by 2 to get the vertex count but the docs says it retrieves the number of elements (not vertices) in the boundary polygon.  What is a polygon 'element' ?

**Comment by inio** [comment]
In this context "element" means "element of an array", so a single floating point value.

**Comment by markreidvfx** [comment]
Ah, so its size of the float array needed to store both the x and z coordinates of the polygon. Thanks for clarification!
