### ISSUE TITLE
[Question][Improvement] ARCore Node implementation

### ISSUE THREAD

**Issue by ManuelTS** [google-ar/arcore-android-sdk#575]
Why is ARCore [Node](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/Node) not a subclass of Java's [DefaultMutableTreeNode](https://docs.oracle.com/javase/10/docs/api/javax/swing/tree/DefaultMutableTreeNode.html)?

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by ManuelTS** [comment]
My mistake, will comply, for future reference, well yeah... the [reference](https://github.com/google-ar/sceneform-android-sdk/issues/334).
