### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by adrinieto** [google-ar/arcore-android-sdk#583]
We want to use ARCore inside our library that doesn't have support for Java 8 for compatibility reasons. We don't want to add support for Java 8 because this will force the apps using our library to add support for Java 8 too. Is there a way to do this?

The only way to make it work is by adding these lines in the library and in the apps.
```groovy
compileOptions {
   sourceCompatibility JavaVersion.VERSION_1_8
   targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by inio** [comment]
I'm not aware of any ARCore APIs that require Java 8 datatypes.  Some of our sample code may use Java 8 features but you should be able to rewrite those pieces fairly easily.  Is there a particular API that requires Java 8?

Note: if this relates to Sceneform (not com.google.ar.core classes), please post this request on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by adrinieto** [comment]
Yes, i was talking about Java 8 features. 
I was using the Sceneform SDK by mistake, sorry. In Sceneform are required but not in ARCore.
Now it builds :+1:
