### ISSUE TITLE
ARCore Support OpenGL 3.0?

### ISSUE THREAD

**Issue by TheMachineHere** [google-ar/arcore-android-sdk#59]
Does ARCore Support OpenGLES 3.0? Or does it only work on 2.0?

**Comment by stetro** [comment]
I could imagine that 3.0 or 3.1 is supported since you are in charge of providing a glcontext to ARCore and you're most likely run android >= 5.0. You could try to set the EGL Context Client Version in the sample to 3.

**Comment by nathanmartz** [comment]
Both GLES 2.x and 3.x should work fine.
