### ISSUE TITLE
ARCore Issue on Galaxy S7 Edge

### ISSUE THREAD

**Issue by michaelheiml** [google-ar/arcore-android-sdk#590]
_Originally posted by @michaelheiml in https://github.com/google-ar/arcore-android-sdk/issues/419#issuecomment-425365145_

Although not mentioned, I tested ARCore 1.5 on Galaxy S7 Edge (SM-G935F) and it does not work. The plane detection seems to work faster and it finds planes repeatedly within 2-4 sec, but they are lost within a few seconds (before 1.5, planes were found once after device restart, then never again). Sometimes it looks as the planes found "swim away" out of screen, then tracking is lost. Sometimes the tracking is lost immediately, planes disappear instantly. Tested with the AR Measure app from Google.

**Comment by inio** [comment]
Could you record a video and provide a logcat dump (for just your app process of possible) that matches the video?

**Comment by michaelheiml** [comment]
Hi @inio its a bit hard to catch the "swimming" but watch from second 0:07 on:

https://photos.app.goo.gl/fesLQb45pY6S4Gu39

Recognising surface does only work after reboot for some minutes or until I start the camera app.

As you also see in the video, the tracking keeps getting lost after a few seconds, comes back again, gets lost and so on.

If the phone is on for more than a few minutes, the blue dots appear for a few seconds, then disappear, then reappear again and so in (but at no point, a surface to place items is drawn).

**Comment by stewe93** [comment]
Hy! 

This issue relates to this I think (reported by me): https://github.com/google-ar/sceneform-android-sdk/issues/407
Logcat is there, if you need any other information i will provide it asap. Could repeat this on Pixel 2 XL too.

**Comment by fredsa** [comment]
@michaelheiml I'm unable to access the video (404)

**Comment by michaelheiml** [comment]
@fredsa 

Here the groundplane pops in and out alternating:
https://photos.app.goo.gl/zXJyZ3ZhNGfvhcEfA

Here the groundplane "swims" (at 0:07)
https://photos.app.goo.gl/D2qWaWHJnUi1jVnMA

**Comment by fredsa** [comment]
@michaelheiml The environment appears very dark in this video, which is challenging from a tracking perspective. Please try an environment that isn't as dark. I believe you'll find that tracking works better.

**Comment by michaelheiml** [comment]
Sorry to disagree but the video is recorded in bright daylight, it only seems so dark because I set the recording cameras' brightness (exposure?) to match the phone screen. It's not a matter of environment brightness.
