### ISSUE TITLE
Webxr

### ISSUE THREAD

**Issue by soniapello** [google-ar/arcore-android-sdk#598]
It 's a question not an issue
Just to know if arcore have any plan to add an api for webxr or anything to allow javascript developer use arcore in their future webxr work

**Comment by inio** [comment]
If such plans existed, we couldn't discuss them before they were formally announced.

I suggest keeping an eye on the [WebAronARCore repo](https://github.com/google-ar/WebARonARCore) repo, but for now not much has happened there in a while.
