### ISSUE TITLE
Galaxy S8 SM-G950F failing to load sample

### ISSUE THREAD

**Issue by MateusZitelli** [google-ar/arcore-android-sdk#6]
The following error message is triggered when loading the sample:

```
java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context)
```

**Comment by inio** [comment]
Have you installed arcore-preview.apk on the device? This is described in the [Prepare Your Device section](https://developers.google.com/ar/develop/java/getting-started#open-sample).

arcore-preview.apk is needed to run ARCore apps.

**Comment by MateusZitelli** [comment]
Great, that was the problem!

**Comment by jaakla** [comment]
So it works? The official list does not have it, it has SM-G950FD (twice!), but not that one.

**Comment by MateusZitelli** [comment]
Yes it works, probably you just spotted a typo in a Google webpage.

**Comment by dhawalbanker** [comment]
But now G950FD is removed from the list altogether. Not even listed on wedsite.

@MateusZitelli is this temporary or permanent?

**Comment by inio** [comment]
The SM-G950FD is just the dual-sim version of the G950F and should carry the same build fingerprint.  Could you capture a logcat from launching the app to receiving the not supported message?

**Comment by inio** [comment]
Is it possible that this is related to #198? Are you on Andorid 8 and if so are you running ARCore 1.0.180129153 (with a 5 in next to last position).

**Comment by dhawalbanker** [comment]
@inio Thanks for your reply. This might be related to #198. I do have latest ARCore from App Store 1.0.180129153, but still the same issue.
