### ISSUE TITLE
This device not support Samsung Galaxy s8+

### ISSUE THREAD

**Issue by uchennafokoye** [google-ar/arcore-android-sdk#60]
Is Samsung s8+ supported (SM-G95U). I tried to run the sample after installing following the install and I get, "This device does not support AR."

**Comment by fredsa** [comment]
@uchennafokoye During the _developer preview_ this is expected as the S8+ is not listed as one of the [supported devices](https://developers.google.com/ar/discover/).

**Comment by inio** [comment]
Duplicate of #89

**Comment by inio** [comment]
@uchennafokoye Good news: select models of the S8+ are now supported.  Check the list to see if your model is included:

https://developers.google.com/ar/discover/#supported_devices

**Comment by Ernie1998** [comment]
@inio This is sad. Still no support for G9500(Hong Kong)... 😭

**Comment by NorbertLovasz** [comment]
still not supported on S8+ SM-G955F .

**Comment by Ernie1998** [comment]
@NorbertLovasz Go look at the table again. There is G955F support.

**Comment by naranja840** [comment]
Like @NorbertLovasz, i still getting the "This device not support ARCORE" message. I see my G955F is in the table, but i cant make it works. (sorry for my inglish)
