### ISSUE TITLE
About depth sensor

### ISSUE THREAD

**Issue by kagong** [google-ar/arcore-android-sdk#603]
I am currently working with tango phone (asus zenfone ar)
Q) In arcore, can I use the depth sensor  as in Tango

**Comment by claywilkinson** [comment]
Thanks for the question.  Unfortunately,our efforts are focused on enabling AR experiences on conventional smartphones using only the IMU and color camera. This may include depth sensing from motion parallax beyond the feature point tracks offered today, but in the near term don't expect any enabling of additional depth sensors such as was found on the Tango devices.
