### ISSUE TITLE
Allowing unsupported devices to attempt to run

### ISSUE THREAD

**Issue by smurfhunter** [google-ar/arcore-android-sdk#605]
As ARcore progresses to rather outstanding quality, it's become well known in modders interested in the software that this software is capable of running on "unsupported" hardware (most notably the OnePlus 3, a close cousin of the supported 3T and the RedMi Note series), and it seems that to get these devices working, you have to put more effort into getting ARcore to allow you to run the software.

I'm aware that support is a very tedious thing, but why not allow it to run on devices that are not officially supported? It seems like a needless blockade from stopping those who want to pursue tinkering with the software on older devices than anything.

(to be clear, I'm not implying you should support these devices, but a one time notice of an "unsupported" device would be a huge step up for the community with older devices who want to try anyway)

**Comment by inio** [comment]
(copying my response from the other thread where this came up for the benefit of people who find this thread first)

We're looking at ways for ambitious developers and users to try ARCore on unsupported devices, and maybe even help us refine and test calibrations for them, but this poses two problems:

1. We have no way to grant a specific user's device access to AR-Required apps, so this would likely be for development purposes only for the time being.
2. We don't have a way (yet) for users to help debug bad experiences with verbose logs or recordings or anything like that.

Until at least one of those two problems is fixed, providing a way for ARCore to run on uncertified devices is pretty low value both for us and users.  Sorry 😞 .

**Comment by smurfhunter** [comment]
@inio, what is stopping the existence of a generic phone profile as a fallback if a device does not exist in ARCore, or adding a verbose log output into a version here on github?

**Comment by inio** [comment]
@smurfhunter 

1. A generic profile would not work on almost any devices.  See cases like #419 and #585 where deviations in behavior from the calibration completely cripple ARCore.
2. ![verboselogging_tn](https://user-images.githubusercontent.com/458571/47399273-91b53d00-d6ec-11e8-8caa-65190aa45d49.jpg)

**Comment by mwvent** [comment]
I would love the have the device profile database folder search path extended to a user writable location such as the SD card.

This can work, there are already releases on XDA developers of flashable zips to add ARcore support for various devices and user feedback indicates these work.

All these zips contain is the .protobuf file to be written to the the /data/data/...blah/device_profile_2_database folder - but of course this means tampering with the device to allow writing there. I for one am not willing to 'root' my device but do feel sad that those who do have more freedom with ARCore.

It's a fairly trivial code change for you guys to open this up, I really hope you will consider it.

**Comment by inio** [comment]
Resolved by tomthecarrot/arcore-for-all#139
