### ISSUE TITLE
We Need Support ARCore For Asus Zenfone 5Z

### ISSUE THREAD

**Issue by jackssl** [google-ar/arcore-android-sdk#607]
Hi Developers ,
   Please Support For ARCore For Asus Zenfone 5Z (ZS621KL) This Is  Latest Flagship Killer . Why You Are Not Supporting Asus Zenfone 5Z.. Please Give Support 
![screenshot_20181016-165718](https://user-images.githubusercontent.com/44197685/47013435-c6614b80-d164-11e8-99ec-08bbbbed5db9.jpg)

**Comment by inio** [comment]
Duplicate of #89

**Comment by ErickeMaciel** [comment]
Please add ARCore for Zenfone 5z
