### ISSUE TITLE
Please integrate MLKit or Tensorflow in ARCore

### ISSUE THREAD

**Issue by shubh261096** [google-ar/arcore-android-sdk#611]
I am trying to make an application where it first identifies the object and then render the same object using ARCore.  It's a feature request

**Comment by dhammikamare** [comment]
@shubh261096 you can refer to this ["3D Scanner for ARCore" app](https://play.google.com/store/apps/details?id=com.lvonasek.arcore3dscanner) and [wiki](https://github.com/lvonasek/tango/wiki/3D-Scanner-for-ARCore) , which does the same
