### ISSUE TITLE
AR apps can't detect any surface (OnePlus 6)

### ISSUE THREAD

**Issue by dimosdim** [google-ar/arcore-android-sdk#617]
Hello! I need some help with the AR apps! I tried everything but they can't detect any surface...! Thank you in advance! Device: Oneplus A6003

**Comment by inio** [comment]
@dimosdim What is the build fingerprint of your device?  You can get this by running `adb shell getprop ro.build.fingerprint`.

**Comment by inio** [comment]
@faruqy87 Please file a separate issue, and include the build fingerprint (see previous comment)

**Comment by dimosdim** [comment]
@inio I fixed it! Everything is working great now! Thank you! 😊 Case closed
