### ISSUE TITLE
Accessing Camera Frame Bytes Directly Instead of Rendering it

### ISSUE THREAD

**Issue by TheMachineHere** [google-ar/arcore-android-sdk#62]
Hi, 

I want to access the camera capture frame bytes directly from ARCore instead of rendering it. 

Some Context: 
I'm trying to take the camera bytes, convert it into texture, apply some shaders, convert back to bitmap, apply CPU algorithms to that bitmap like flood fill (which can't be done on GPU), convert back to texture, apply additional shaders, render image. 

What would be the best way to do this?

Is there a way to access camera frame bytes directly (instead of having it render on the screen)?

**Comment by TheMachineHere** [comment]
@nathanmartz  Any help would be greatly appreciated

**Comment by andrelevi** [comment]
+ 1 Would like to know this as well.

**Comment by nathanmartz** [comment]
Sorry for the slow reply here. The best way to access the camera data is to use [Session.setCameraTextureName()](https://developers.google.com/ar/reference/java/com/google/ar/core/Session.html#setCameraTextureName(int)) to access the camera data. Then write a bit of GL to blit that to a texture you can read from, render with, etc.

**Comment by inio** [comment]
With Developer Preview 2, we've added [computervision sample code](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision) that shows how to get CPU access to the pixel data.
