### ISSUE TITLE
Moto G6 does not detect planes

### ISSUE THREAD

**Issue by OmegaJune** [google-ar/arcore-android-sdk#621]
During the Unite LA 2018 workshop, I could not get HelloAR to work correctly on my Motorola Moto G6.
Ran the HelloAR app and could not detect planes on Motorola Moto G6 phone. Same HelloAR build works fine on Pixel phone that was provided for the workshop.

C:\Users\omega>AppData\Local\Android\Sdk\platform-tools\adb.exe logcat -s Unity
--------- beginning of system
--------- beginning of main
10-23 16:04:42.785 28182 28197 D Unity   : Loading ARCore V1+ path.
10-23 16:04:42.828 28182 28197 I Unity   : SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 8, Memory = 2856mb
10-23 16:04:42.828 28182 28197 I Unity   : SystemInfo ARM big.LITTLE configuration: 8 big (mask: 0xff), 0 little (mask: 0x0)
10-23 16:04:42.829 28182 28197 I Unity   : ApplicationInfo com.google.ar.core.examples.unity.helloar version 1.0 build fa629045-d087-498c-b617-4db6fac94c28
10-23 16:04:42.829 28182 28197 I Unity   : Built from '2018.2/release' branch, Version '2018.2.11f1 (38bd7dec5000)', Build type 'Release', Scripting Backend 'mono'
10-23 16:04:42.976 28182 28197 E Unity   : Unable to find unitygar
10-23 16:04:43.009 28182 28197 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_EXT_mul
10-23 16:04:43.009 28182 28197 D Unity   : tisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance
10-23 16:04:43.009 28182 28197 D Unity   :  GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation
10-23 16:04:47.281 28182 28197 E Unity   : Unable to find arcore_instant_preview_unity_plugin
10-23 16:04:47.563 28182 28197 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range
10-23 16:04:47.563 28182 28197 E Unity   :
10-23 16:04:47.563 28182 28197 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 338)
10-23 16:04:47.563 28182 28197 E Unity   :

**Comment by inio** [comment]
1. What is your build fingerprint? (`adb shell getprop ro.build.fingerprint`)
2. If you restart the device, does it work once? (behavior mentioned in #483, but if you see the same thing I think I'll dedup that one onto here as there's some other confusing noise in that bug)

**Comment by OmegaJune** [comment]
motorola/ali/ali:8.0.0/OPSS27.104-15-10-4/4:user/release-keys

I restarted the device and I still have the same issue where the HelloAR app doesn't detect planes.

**Comment by inio** [comment]
I just noticed your log shows you're using Unity.  Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
