### ISSUE TITLE
RESOURCE_EXHAUSTED sooner than expected

### ISSUE THREAD

**Issue by MathiasGilson** [google-ar/arcore-android-sdk#622]
Hi, 
I've got a function that calls `session.resolveCloudAnchor(anchorId)` for 4 different anchors each 2 seconds. That should make 120 calls per minutes to the ARCore Cloud Anchor API but instead I get the following error

`RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'arcorecloudanchor.googleapis.com/anchors_read_requests' and limit 'ReadsPerMinutePerProjectPerUser' of service 'arcorecloudanchor.googleapis.com'`

And when I check my API quota it says that I've made more than 300 Read requests in less than 30sec

After further tests, I found that when I call `session.resolveCloudAnchor(anchorId)` once, it counts for 5 Read requests, is it the expected behavior?

Many thanks

**Comment by inio** [comment]
I've asked the Cloud Anchor team to respond to this.

**Comment by MathiasGilson** [comment]
Thanks

**Comment by MathiasGilson** [comment]
Any news ?

**Comment by jrullman** [comment]
The API implementation already does retrying on its own.
We recommend you wait until an anchor fails resolving before retrying yourself.

**Comment by MathiasGilson** [comment]
Ok, how can I know that the resolving has failed?

**Comment by inio** [comment]
During hosting calling `getCloudAnchorState()` on the returned anchor will return `TASK_IN_PROGRESS`.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
