### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by underworld9** [google-ar/arcore-android-sdk#623]
I have found a memory leak when closing a session. (stopping & destroying the arCore activity)
found using the Android Profiler.
There are some objects with names like "bkm", "big", "bff", etc. that get increased by 2 after a session was opened. So after opening a session 7 times these objects have an allocation count of 14.

![after_session_started_1_time](https://user-images.githubusercontent.com/38068535/47660787-0cbc9e80-db98-11e8-9ae9-12665f39b243.jpg)
![after_session_started_7_times](https://user-images.githubusercontent.com/38068535/47660788-0cbc9e80-db98-11e8-94c7-63db9769333b.jpg)

I have tested this Memory Leak in several different ArCore samples.
new samples and older ones.
the Memory Leak happens in every single one of them! every time the Activity is destroyed.
it never happens if the Activity is saved and stopped.
i also have created an App that does nothing except 
set the content view to: com.google.ar.sceneform.ux.ArFragment
and the Memory Leak happens every time.

every session increases the memory by an average of 3,5 MB.

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
