### ISSUE TITLE
XZ3 issupported but missing on supported devices list (documentation bug)

### ISSUE THREAD

**Issue by nilsk123** [google-ar/arcore-android-sdk#628]
Hi,

We use the list (https://developers.google.com/ar/discover/supported-devices) of supported devices to decide whether or not we're going to invest in technology like ARCore.

Right now, the Sony Xperia XZ3 is supported by ARCore but is not on that list. I wonder if there are more

**Comment by inio** [comment]
Seems to have been fixed!
