### ISSUE TITLE
Feature request: add PointCloudLibrary to ARCore and JNI calls for it to ARCore?

### ISSUE THREAD

**Issue by kenyee** [google-ar/arcore-android-sdk#633]
Maybe as a separate artifact because it's such a pain to build/include from source?  A lot of the code in that library is useful since ARCore seems to be missing some features from Tango's SDK.

E.g., something as simple as finding the Oriented Bounding Box for a registered point cloud is more pain than it needs to be instead of a few lines of code that call PCL methods.

**Comment by inio** [comment]
The point cloud is currently only intended for debug visualization and minor uses like oriented points.  The data quality is not sufficient for reconstruction purposes so we're not interested in providing helpers for that sort of stuff.

**Comment by kenyee** [comment]
If we filter the point cloud based on confidence (e.g., 0.7), it seems to be accurate enough for object size estimation (roughly +- 1cm per dimension though I wish it were better).  If ARCore is intended to replace Tango's use cases, it would be nice to have APIs that help w/ bounding box detection, etc...ArCore seems to have some collision detection code too (Box, etc.)

The point cloud data was *very* helpful for debug visualization in my current project :-)

**Comment by devbridie** [comment]
Point clouds are now in [`Frame.acquirePointCloud()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquirePointCloud()).
