### ISSUE TITLE
Need To duplicate or copy / paste added node after scaling its size with same scaling in plane beside node.

### ISSUE THREAD

**Issue by HEMAL-VES** [google-ar/arcore-android-sdk#635]
Hi

I am trying to make one demo application in which I want to add some option like copy / paste selected node, remove node, etc...

I have done remove node point. Now, I am trying to duplicate / copy-paste added node after scaling and resize node, but, not get success for duplicate the edited node in plane. The duplicate node will be same as added or edited (scaling or resized) node.

Can any one tell how can I duplicate / copy-paste that node in application? Is there any easy way to do that?

**Comment by HEMAL-VES** [comment]
Well there is no such functionality for copy and paste same (after scaling and resizing) added anchor node that's why I am asking this point here. If available then give me some suggestion for that.

**Comment by kolboch** [comment]
how can anchor node has scale or size? Do you mean objects ? 
Looking into docs there is only Vector3 for position and Quaternion for rotation and i do not really see why there should be option to copy or scale/ resize the AnchorNode?
[AnchorNode](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/AnchorNode)

**Comment by HEMAL-VES** [comment]
Sorry, I mean to copy and paste the same object after scaling or resizing it with the required size.

**Comment by kolboch** [comment]
As I thought it is not related to SDK! You have to figure it out on your own. I develop in Unity so there I have access to current scale and rotation of object but there is no method from SDK to copy objects. You have to implement it on your own, do some button or detect touch - the way to trigger that. Feel free to experiment, on thing for sure to achieve such result you have to store the reference to the placed object. I would really recommend to post this question on stackoverflow as it is not SDK related, and moreover in the future it would be easier for people to find if they face similar problem.

**Comment by HEMAL-VES** [comment]
OK thanks

**Comment by inio** [comment]
@HEMAL-VES Sorry for @kolboch's tone, they are not a member of the ARCore team.  If you're using Sceneform, please post to the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

@kolboch If you're going to post here please take a more civil tone.
