### ISSUE TITLE
Unable to detect vertical plane

### ISSUE THREAD

**Issue by HEMAL-PATEL** [google-ar/arcore-android-sdk#636]
Hi

I am trying to detect a vertical plane like wall to add image view on a vertical plane. But did not find the vertical plane. As per the default config for a session that can find both planes as a horizontal and vertical plane. But unable to find a vertical plan.

How to find a vertical plane in android application?

Please help me.

**Comment by siny-yao** [comment]
https://stackoverflow.com/questions/53256147/android-unable-to-detect-vertical-plane

**Comment by inio** [comment]
Vertical plane detection requires many visual features on the plane for it to be detected.  Could you post a screenshot or even better a video of your desired use case?

**Comment by inio** [comment]
We added vertical plane detection back in version 1.2.  You need to explicitly enable it using `Session.configure()` setting the plane finding mode to `HORIZONTAL_AND_VERTICAL`.

**Comment by ShemuelZhaoQAQ** [comment]
> Vertical plane detection requires many visual features on the plane for it to be detected. Could you post a screenshot or even better a video of your desired use case?

which is the visual feature ？I only detected vertical plane one time on version  1.12 by set  HORIZONTAL_AND_VERTICAL  mode.  Is there any way to detect vertical plane all the time ?
thank you

**Comment by devbridie** [comment]
Using `Config.PlaneFindingMode.VERTICAL` will continue to find vertical planes. If ARCore isn't detecting many, make sure that there are enough visual features such that ARCore will be able to distinguish the wall.
