### ISSUE TITLE
Not working on Xperia xz premium Android PIE

### ISSUE THREAD

**Issue by Indashio** [google-ar/arcore-android-sdk#639]
Arcore not working after update Xperia xz premium to Android pie firmware 47.2.A.0.306
Does not find the ground Only many dots Not compatibile

**Comment by Indashio** [comment]
:/

**Comment by avonwyss** [comment]
Sony Xperia XZ1 Compact (47.2.A.0.306) is also incompatible, cannot install from Play Store.

**Comment by Indashio** [comment]
New build firmware today. I wonder if we will lose access to arcore with every system update. I often use it. Unfortunately, I can not do it now. Frustrating

**Comment by inio** [comment]
@Indashio Sorry about not responding when I initially tagged this.

What is your build fingerprint?  You can get this by running `adb shell getprop ro.build.fingerprint`.

We're working on some improvements that should make ARCore much less sensitive to changes in device behavior especially changes in timestamping, so this should hopefully improve in the future.

**Comment by fizixman83** [comment]
@inio I added a similar issue here for the XZ1 Compact: https://github.com/google-ar/arcore-android-sdk/issues/660

I too have had no luck getting ARCore detecting surfaces since updating to Android 9. Lots of points being picked up, but no surfaces generating. It worked perfectly fine on Android 8 prior to the update.

**Comment by Indashio** [comment]
@inio 

ro.build.fingerprint=Sony/maple_dsds/maple_dsds:9/YOSHINO-2.2.0-CAF-181103-0550/1:user/dev-keys

I am waiting for an update for a long time. I had to change my build.prop and root oem cust.prop for xz3 + xz3 fingerprint and now arcore working on my xz premium with xz3 prop I think it's on xz premium Oreo it's working better. I often use arcore. I had to look for a way :/ I look here every day with hope of updating

**Comment by richard3575** [comment]
We're seeing the same issue on Sony XZ Premium - since PIE update ARCore is unusable as it cannot find any surface (surfaces it previously found no problem)
Also experiencing the same issue on Samsung Tab S3 - but this has Android 8.0.0
samsung/gts3lltexx/gts3llte:8.0.0/R16NW/T825XXU2BRG3:user/release-keys

**Comment by fizixman83** [comment]
@inio: ARCore 1.6 has resolved all my tracking issues on the Xperia XZ1 Compact with Android 9. Thanks for  the update!

**Comment by richard3575** [comment]
@inio unfortunately ARCore 1.6 has not fixed our Sony issue. We've tested 1.6 and still have the same issue.
(Sorry can't get build fingerprint as device on holiday with dev - without PC access. Can get in 1 week)

**Comment by avonwyss** [comment]
The 1.6 update did not help for me either.
FIngerprint `Sony/G8441/G8441:9/47.2.A.0.306/1344763102:user/release-keys`

**Comment by avonwyss** [comment]
In the meantime I got another Pie update for the XZ1C and ARCore 1.6 now seems to work.

**Comment by fredsa** [comment]
Closing as this issue should be fixed after installing the latest available Android firmware updates for Sony Xperia XZ Premium, as well as updating to ARCore SDK 1.6.0 (which will ensure that the device is running ARCore 1.6.0 or later).
