### ISSUE TITLE
Using the china version of arcore, it is very difficult to identify the plane

### ISSUE THREAD

**Issue by Terran-Marine** [google-ar/arcore-android-sdk#641]
The test phone
1.MI 8   Xiaomi
2.P20    Huawei

With arocre downloaded from Xiaomi app store/Huawei Apps Gallery, it is very difficult to identify arcore.
But I use the same phone, and there is no problem with installing arcore1.5.3 on github.

 Xiaomi app store            arcore 1.5.180910096
Huawei Apps Gallery       arcore 1.5.180910096

**Comment by inio** [comment]
1.5.180910096 is (I think) our release 1.5.1.  We'll try to get the latest version up on those stores.

For the P20, you might also be experiencing an intermittent issue we're seeing on this device family (#585 #642).

**Comment by Terran-Marine** [comment]
Thx.
Looking forward to version 1.6
