### ISSUE TITLE
[device support] Huawei Nova 3 is not supported 

### ISSUE THREAD

**Issue by louisongbh** [google-ar/arcore-android-sdk#646]
I am facing a "This device does not support AR" when I am running the HelloSceneForm sample based on the tutorial at https://developers.google.com/ar/develop/java/quickstart.

My device info : 
Model : Huawei Nova 3 
Android : 8.1.0
API : 27 
AR Core Version : 1.5.180910096 (Downloaded from Google Play Store)  
Device fingerprint : `HUAWEI/PAR-LX9/HWPAR:8.1.0/HUAWEIPAR-LX9/112(C636):user/release-keys`

Checked from https://developers.google.com/ar/discover/supported-devices that Huawei Nova 3 is supported. Therefore, I am wondering is there any configurations that I have setup wrongly?

Few lines from logs 

```
11-03 11:06:47.614 21542-21542/com.google.ar.sceneform.samples.hellosceneform E/aks: Invalid Camera Type: -1
11-03 11:06:47.625 21542-21542/com.google.ar.sceneform.samples.hellosceneform E/native: session_create_implementation_shared.cc:677 Device is not supported.
11-03 11:06:47.625 21542-21542/com.google.ar.sceneform.samples.hellosceneform V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: did not need to detach thread. (Called from line 632.)
11-03 11:06:47.625 21542-21542/com.google.ar.sceneform.samples.hellosceneform E/native: session_create_implementation.cc:82 Failed to create calibration provider.
11-03 11:06:47.625 21542-21542/com.google.ar.sceneform.samples.hellosceneform W/native: session_create_implementation.cc:83 ArSession_createWithSettingsImplementation_private returning ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE: .
11-03 11:06:47.625 21542-21542/com.google.ar.sceneform.samples.hellosceneform V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 62.)
    JniHelper: thread already attached. (Called from line 62.)
    ~JniHelper: did not need to detach thread. (Called from line 62.)
11-03 11:06:47.628 21542-21542/com.google.ar.sceneform.samples.hellosceneform E/StandardArFragment: Error: This device does not support AR
    com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException'
```

Hope to see this is being rectified. Thanks.

**Comment by inio** [comment]
Sorry about missing this for so long.  There should be a log message printed a few lines earlier from the ARCore process (not your app) that mentions "device_profile_HWPAR_accelerometer".  Would it be possible to get that line?

**Comment by louisong97** [comment]
Hi, wish to know is this issue is being solved yet. Appreciate it for your help. Really hope that I am able to develop AR applications on my current available devices

**Comment by devbridie** [comment]
The Nova 3 should be supported now-- if you're still encountering problems, feel free to open up a new issue.
