### ISSUE TITLE
Feature Request: Ability to read captured camera frame

### ISSUE THREAD

**Issue by seanadkinson** [google-ar/arcore-android-sdk#65]
I need to be able to access the raw pixel data that was captured from the camera per-frame.  I've seen suggestions of [rendering to a RenderTexture](https://github.com/google-ar/arcore-unity-sdk/issues/11) or [reading pixels with glReadPixels](https://stackoverflow.com/a/45987608/194065), but I actually want access to the video feed without the AR elements.  Is this possible, or on the roadmap for the near future?  Thanks!

**Comment by stetro** [comment]
My idea would be to use a separate surface in `BackgroundRenderer` (from the sample code). There you could render every frame on the surfaces texture and use `ImageReader` callbacks or an `Encoder` to access the video frames. Examples can be found in Googles Grafika Repository https://github.com/google/grafika

**Comment by eddielong** [comment]
Would also love to be access the raw pixel data per frame. For my use case getting camera properties back, such as the principle point and focal length is pretty crucial - I would like to add this to the feature request. It is stopping me from getting feature parity with ARKit.

**Comment by eddielong** [comment]
I was playing around yesterday, I made some hacks to get back the data I wanted. Not saying people should actually do this but just shows the information is all there but hidden away
https://github.com/parrotbait/arcore-hacks

**Comment by avirodov** [comment]
Please see the new developer preview 2 sample 'computervision':
https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision
