### ISSUE TITLE
[ARCore is unsupported on Samsung Galaxy A6+]

### ISSUE THREAD

**Issue by Margulka** [google-ar/arcore-android-sdk#653]
Hello, dear developers. I would really like it if you released the ARCore for Samsung Galaxy A6+. Why ARCore is aviable for A6, but not for A6+? Please, add ARCore for A6+.

**Comment by Canato** [comment]
This was asked 3 issues ago: https://github.com/google-ar/arcore-android-sdk/issues/650

Besides my answer in the link, maybe would be even more help full to research and study how a mobile can be ARCore compatible.

**Comment by inio** [comment]
Duplicate of #89

**Comment by Pavel401** [comment]
Hi sir The basic A6 is supported Arcore, but the A6+ is not supported. plz, add A6+ to Arcore Family.
Already the A8 and A8+ support google arcore ,so why A6+ does not.


So I request to look at our A6+ and bring it to Arcore family

**Comment by chnouman** [comment]
Please remove the support from A6+. The way it is working in A6 is not acceptable. Very poor performance.
