### ISSUE TITLE
ArCore does not find surface any more on Moto Z2 force Android 8.0

### ISSUE THREAD

**Issue by chriswattz** [google-ar/arcore-android-sdk#659]
I bought an Motorola Z2 force to develop with ArCore. It worked for 3 Days (surface was found in seconds) , now all apps using ARCore stopped working including my Unity Apps (HelloAR) that i tested on the device. The apps do start (IKEA and others) but they do not find any surface. No error messages. The camera access for the ARcore apps are granted. Any idea why Arcore does not work any more? I reinstalled the ARCore software from App store but no change. I can see the particles very shortly coming up and disappearing but no surface found. I did not change something on the phone...what can i do ?

**Comment by chriswattz** [comment]
After additional testing i think this issue is a performance problem. Is there a way to push the ARCore excecution up ? Are there any performance tools in ArCore to use the full power of the system?

**Comment by fizixman83** [comment]
Might be crazy, but try restarting your device and see if tracking picks up better.

https://github.com/google-ar/arcore-android-sdk/issues/419

**Comment by inio** [comment]
Thanks for the report.  Could you try updating to ARCore 1.6 (released yesterday) and checking if you still see this behavior?  If you are still seeing it, please respond with your build fingerprint, accessible by running `adb shell getprop ro.build.fingerprint`.

**Comment by chriswattz** [comment]
Thanks for the advice. What i did the last days was resetting my phone (hard reset) and i recognized that first time run of an ARCore App was fine but the second run was problematic again. So i checked the App and saw that it seems to be running still (i forced quit). Tracking was a bit better but not really fast. Now i checked with ARCore 1.6 and i think it is better than before. Still i have to force quit (before restart of an ARCore app) and it is working quiet well now. I will go on testing the next days to see how it does behave.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
