### ISSUE TITLE
Feature request: add a LineRenderable

### ISSUE THREAD

**Issue by kenyee** [google-ar/arcore-android-sdk#661]
It's nice that we have triangle mesh renderables we can attach to nodes, but it'd also be nice to be able to add a node that is a set of lines.  I.e., it'd be nice to be able to attach something like this to a node:
https://github.com/googlecreativelab/justaline-android/blob/master/app/src/main/java/com/arexperiments/justaline/rendering/LineShaderRenderer.java
but it doesn't look like it can be attached to a node...seems to want some lower level OpenGL support to work.

ArKit (iOS) has a line draw method that's missing from ArCore.  There are a few workarounds...e.g., making a cyclinder or 3D rect into a pseudo "line" like this:
https://stackoverflow.com/questions/51951704/how-to-draw-line-between-two-anchors-in-sceneform-in-arcore/52816504#52816504
which seems inefficient because you're creating a new node for each line segment.

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by kenyee** [comment]
Sorry @inio...didn't know there was a separate sceneform repo :-(
