### ISSUE TITLE
Feature Request: Make PointCloud implement Closable

### ISSUE THREAD

**Issue by stetro** [google-ar/arcore-android-sdk#669]
I missed the release function in `PointCloud`.
Would be nice make the `PointCloud` class `Closable` to avoid memory leakage.

```kotlin
frame.acquirePointCloud().use { pointCloud ->
    // ... use point cloud
}
```

**Comment by inio** [comment]
Good suggestion!

**Comment by devbridie** [comment]
Currently, PointCloud implements Closeable.
