### ISSUE TITLE
Can ArCOre make video ? how to do it ? 

### ISSUE THREAD

**Issue by 544531645** [google-ar/arcore-android-sdk#67]

**Comment by nathanmartz** [comment]
Can you be more specific? Are you trying to record video in your app? If
so, there is no built in ARCore functionality for that, but you should be
able to do it yourself using the camera texture provided in Session.

**Comment by 544531645** [comment]
yes I want  trying to record video in my  app, camera texture provided in Session how to do it .do you have example?

**Comment by stetro** [comment]
Hi, you could take a look into https://github.com/google/grafika how to use an encoder to record a video from the texture. Maybe it suites your use case.

**Comment by nathanmartz** [comment]
That's a reasonable suggestion, stetro. I'm closing this as it's not really a bug report but a "how to" question, and those should be posted to StackOverflow.
