### ISSUE TITLE
Sample apps crash - Samsung Galaxy S7 (SM-G930U)/ Oreo (8.0.0)

### ISSUE THREAD

**Issue by michaelbarbero** [google-ar/arcore-android-sdk#670]
Applications stop immediately.

I noticed this same error for all application I've tested : missing /system/framework/oem-services.jar
I attached Logs from arcore-android-sdk sample apps and virocore lib (which currently implements arcore 1.5)

- Android Studio: 3.2.1
- ARCore SDK for Android: 1.6.0 / 1.5.0
- Device manufacturer, model, and O/S:  Samsung Galaxy S7 (SM-G930U) / Oreo (8.0.0)
- ARCore: 1.6.181112096

**Comment by michaelbarbero** [comment]
Same thing with Google Measure -> Unknown ARCore Error (Fatal Exception)

(https://play.google.com/store/apps/details?id=com.google.tango.measure&hl=en_US&rdid=com.google.tango.measure&showAllReviews=true)

I caught the exceptions from Android Studio (log attached)

Hope that helps.

[google measure.txt](https://github.com/google-ar/arcore-android-sdk/files/2661724/google.measure.txt)

**Comment by michaelbarbero** [comment]
I've tested it all against my newly Huawei mate 20 lite and everything is working like a charm. Definitely I don't recommend Galaxy S7 for ARCore development...

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
