### ISSUE TITLE
Remove ads on installing screen

### ISSUE THREAD

**Issue by tangobravo** [google-ar/arcore-android-sdk#673]
The flow when requesting an install via the `ArCoreApk_requestInstall` involves a popup over my app.

That's fine, but the dominant part of the popup (>75% of the height of the popup) is dedicated to "You might also like" play store install ads. At least on my test device these have no relevance to my app (or ARCore). I'm not sure if this is backed up by numbers but for me personally I feel much more like cancelling the popup as it feels like a popup ad with an "x" on it rather than a necessary module install for the part of the app I am using.

Our app is very clean and ad-free and this popup is really incongruous in the app flow.

![screenshot_20181211-101830_google play store](https://user-images.githubusercontent.com/770066/49794879-85cf1a00-fd30-11e8-9269-3d2c52ce2137.jpg)

Distributing ARCore via Google Play may be a necessary evil for device support and updates. For me it is important to recognise the user cost of this install flow, and the flow should be made as minimal and non-disruptive as possible (efforts to reduce the install size would also help here of course).

I realise this may be an issue for the Play Store team rather than ARCore but would appreciate recognition of the importance of this.

**Comment by inio** [comment]
Good news: We've had some motion on this.  No timeline yet but things are looking hopeful.

**Comment by inio** [comment]
This should be fixed.  Please don't hesitate to let us know if the ads show up again!
