### ISSUE TITLE
Frame Synchronization and Acquire Camera Image - Question

### ISSUE THREAD

**Issue by EbadSyed** [google-ar/arcore-android-sdk#675]
I am trying to integrate ArCore in an existing application which uses Camera 2 API for capturing and viewing images, and want to integrate ArCore in it particularly to track Camera (Acquire Camera Pose) and capture 3D Point Clouds.

Would it create conflicts if I call session.update to acquire frame and getCamera in the same application already accessing and viewing Camera View ?

If no would the frames on ArCore and Camera Preview be synchronized ?

Or is it recommended to use ArCore as the base and use Texture and Image provided by ArCore for rendering the view ?

**Comment by inio** [comment]
At the moment you need to let ARCore have exclusive control of the camera.  Keep an eye on #153 for possible updates in this space.

**Comment by devbridie** [comment]
The [Shared Camera Sample](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/shared_camera_java/app/src/main/java/com/google/ar/core/examples/java/sharedcamera/SharedCameraActivity.java) shows how the camera2 APIs can be used to share the camera with ARCore.
