### ISSUE TITLE
Model color problem

### ISSUE THREAD

**Issue by siny-yao** [google-ar/arcore-android-sdk#676]
### VERSIONS USED
- Android Studio: 3.2.1
- ARCore SDK for Android: 1.6.0
Test phone：
Pixel2,SM-G9300,MIX2S,HUAWEI Mate20
I use ArFragment, I found that the color of the 1.6.0 version and the 1.5 version of the model is very different, I want to know the reason?
The first picture is version 1.5
The second and third pictures are version 1.6.0
![1544685665459_](https://user-images.githubusercontent.com/25580281/50001987-98b84780-ffd9-11e8-9f0c-7793e8c33d56.jpg)
![1544787306716](https://user-images.githubusercontent.com/25580281/50001992-9d7cfb80-ffd9-11e8-9f94-e8f506d753d1.jpg)
![1544786658601](https://user-images.githubusercontent.com/25580281/50001996-9f46bf00-ffd9-11e8-8920-ef17fd2bb4ca.jpg)

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).
