### ISSUE TITLE
ArCoreApk.getInstance().checkAvailability doesn't verify devices that need updated OS versions

### ISSUE THREAD

**Issue by kenyee** [google-ar/arcore-android-sdk#677]
### VERSIONS USED
- Android Studio: 3.4 Canary 8
- ARCore SDK for Android: 1.6
- Device manufacturer, model, and O/S: Nexus 6, Android 7.1.1

### STEPS TO REPRODUCE THE ISSUE
 1. get device above (note that compatibility list says Nexus 6p needs Android 8.0 but this is a Nexus 6)
 2. start app w/o arcore installed
 3. the ArCoreApk.getInstance().checkAvailability will bounce users to the play store to download ArCore
 4. user can't download it because the device is not a 6p or the Android OS is too low a version
This is a bad UX...the compatibility check should verify the 8.0 requirement or the device.

### WORKAROUNDS (IF ANY)
We're just going to set our min Android version to 8.0 to be safe

**Comment by kenyee** [comment]
Actually would also be nice to be able to have some sort of flag to checkAvailability for LOW_ACCURACY, MEDIUM_ACCURACY, HIGH_ACCURACY or FAIR, GOOD, BEST experiences.

What we're finding is devices are radically different in how well they handle AR...e.g, the best devices can pick up the floor and surrounding super quick (latest Pixels), then there are ones that have a good experience (e.g., Samsung S8 devices), then there are ones that are just plain poor experience (e.g., Nexus 6p running Android 8.0...slow at picking up floor and environment...overheats...etc.)

Would be nice to able to just target the better experience devices....

**Comment by inio** [comment]
> the ArCoreApk.getInstance().checkAvailability will bounce users to the play store to download ArCore

I'm confused by your report.  `checkAvailability` should not be capable of launching the Play Store.  Is it possible you're calling `requestInstall` instead?  In AR-Optional apps this should not be called before `checkAvailability` returns a `SUPPORTED` code.

**Comment by inio** [comment]
Please file a separate feature request for your 2nd item.  Having a bug and feature request in a single issue makes keeping tracking things a lot harder.

**Comment by kenyee** [comment]
Made a dumb mistake and didn't check the checkAvailability result properly and it jumped to the ArFragment which then jumped to the play store to install ARCore :-(
Closing issue.
