### ISSUE TITLE
About recording

### ISSUE THREAD

**Issue by w2xx** [google-ar/arcore-android-sdk#678]
### VERSIONS USED
- Android Studio: 
3.2.1
- ARCore SDK for Android: 
1.6
- Device manufacturer, model, and O/S: 
HUAWEI p20pro

When I got the texture for recording, I found that the final image had a stretching problem. How can I record videos, or can I provide examples of recording videos?

**Comment by claywilkinson** [comment]
The "stretching" problem usually means the aspect ratio of the recording texture compared to the ARCore view.  There are more details on the [video recording with Sceneform](https://developers.google.com/ar/develop/java/sceneform/video-recording) page and that also points to a sample which is new for 1.6

Does your stretching problem happen with the sample app as well?

**Comment by inio** [comment]
Please post issues related to Sceneform on the [google-ar/sceneform-android-sdk issues board](https://github.com/google-ar/sceneform-android-sdk/issues).

**Comment by w2xx** [comment]
@inio I post issue to scenform before, but they said that the original camera data could not be achieved with scenform and needed to be done with opengl.[https://github.com/google-ar/sceneform-android-sdk/issues/83](url)
