### ISSUE TITLE
Memory leak: Activity being held onto by com.google.tango.jni.TangoCameraNative.mContext.

### ISSUE THREAD

**Issue by VikAdvani** [google-ar/arcore-android-sdk#68]
It appears that com.google.ar.core.Session requires an Activity context as an argument to its constructor which leads to this leak.

Our app consists of two activities, the 1st is the Main Activity which is a list of AR experiences to launch into, that consists of standard Android UI. The 2nd, is our AR based Activity which starts an ARCore Session. 

When we go from our Main Activity into the AR based Activity and then go back to our Main Activity the ARCore based Activity leaks since TangoCameraNative is still holding on to it. 

To remove the leak, we used reflection to invoke the private constructor of Session which takes a android.content.Context. This private constructor allows us to pass an Application Context instead of an the Activity's Context and fixed the memory leak. This isn't a shippable solution but proved the leak was due to the Session holding onto the Activity Context.

Please let us know when this is fixed as this will allow people to develop apps that launch to and from an AR experience without leaking.

We used the reflection code below to confirm the leak would be fixed using the private Session constructor:
```
 // not prod code, used to test if mem. leak occurs using private Session constructor. 
    Class<?> iTangoClazz = Class.forName("com.google.ar.core.ITango");
    constructor = Session.class.getDeclaredConstructor(Context.class, iTangoClazz);
    constructor.setAccessible(true);

    Class<?> cTangoWrapper = Class.forName("com.google.ar.core.TangoWrapper");
    Constructor<?> tangoWrapperConstructor = cTangoWrapper.getDeclaredConstructor();
    tangoWrapperConstructor.setAccessible(true);

    Object tangoWrapperObj = tangoWrapperConstructor.newInstance();
    mSession  = (Session)constructor.newInstance(activity.getApplicationContext(),tangoWrapperObj);

```

**Comment by avirodov** [comment]
This is now fixed in developer preview 2 release.
