### ISSUE TITLE
Huawei nova 3 bug

### ISSUE THREAD

**Issue by japolo95** [google-ar/arcore-android-sdk#680]
Huawei nova 3, no applications installed, brand factory new. Emui version is 8.2.0 and Android 8.1.0.
1.installed ar core from play store (version 1.6.181112099, the app did not asked for any permissions
2.installed Measure (from Google, so assuming should work)
3.started Measure and got "unknown ARCore error (fatal exception)
4.tried also Just A Line app and getting "AR not supported on this device error"
5.checked if nova 3 is compatible with ARCore and yes it is (from official Google list of supported devices)

Is this a bug in Emui or in ARCore? Please, is there anyone who could help me? Thanks

**Comment by inio** [comment]
Sounds like a bug on our end.  Could you do the following:

1. What is the build fingerprint of this device?  `adb shell getprop ro.build.fingerprint` will display it.
2. Please capture a logcat showing the messages generated around the failure.

**Comment by fredsa** [comment]
Please file a new issue with the requested information if you're still experiencing issues.
