### ISSUE TITLE
POCO F1 Ar issue

### ISSUE THREAD

**Issue by thapliyalshivam** [google-ar/arcore-android-sdk#682]
I am using unity and ARCORE to test Sample test HelloAr scene from codelaps. 
Unfortunately, it always shows 
"Failure to initialize!
your hardware doesn not support this application."
I have also downloaded ARcore from app store and tried everything.
any help would be appreciated.

**Comment by inio** [comment]
I believe this is a Unity issue.  Please post issues with the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).
