### ISSUE TITLE
Transformation from "CPU Image Coordinates" to Image View.

### ISSUE THREAD

**Issue by EbadSyed** [google-ar/arcore-android-sdk#686]
Image returned by Frame#acquireCameraImage() has a larger view than the view displayed on the screen. 

When comparing the CPU image to Screen View, the CPU image seems to have a larger field of view. Also, after image processing when I try overlaying some boxes over screen view they were not perfectly aligned while the box on downloaded CPU image was accurately aligned.

How can I transform CPU Image coordinates to the Image viewed on the screen ? 
What is the size of image on the screen view ?

**Comment by claywilkinson** [comment]
@EbadSyed  can you show what you are experiencing?  The size of the camera image and the gpu texture dimensions are available in the [CameraConfig](https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/CameraConfig) which you can access from `Session.getCameraConfig()`.   What sizes are you getting?  Typically the CPU image is much smaller than the GPU.  It can also be rotated 90 degrees from what you expect due to the way the Android Camera API works.

I have not seen any issues when calcuating a scale factor for x and y   as view.width / image.width and then multiplying to scale any points within the CPU image back to the screen view.

Can you share an example of how the FOV is different?

**Comment by EbadSyed** [comment]
Here is the saved 640X480 Image

/home/ebad/Pictures/ar/original890911385855357.png

Here is the Screen Shot of the "View"

/home/ebad/Pictures/ar/Screenshot_2019-01-10-16-32-08-369_com.fma.system1.png


In the 640*480 you have some view under the table as well a little extra view on the sides. Could be a problem with my code but I think the View is "Zoomed" or "Cropped".

**Comment by EbadSyed** [comment]
Here is the saved 640X480 Image

![original890911385855357](https://user-images.githubusercontent.com/16402043/50966378-9244bf00-14f6-11e9-8553-8d4e935ed557.png)

Here is the Screen Shot of the "View"

![screenshot_2019-01-10-16-32-08-369_com fma system1](https://user-images.githubusercontent.com/16402043/50966424-aab4d980-14f6-11e9-828e-a2426de4fcb9.png)

In the 640*480 you have some view under the table as well a little extra view on the sides. Could be a problem with my code but I think the View is "Zoomed" or "Cropped".

**Comment by EbadSyed** [comment]
Image Size is 640X480

Texture Size is 1920X1080

**Comment by EbadSyed** [comment]
@claywilkinson I just noticed the transformCoordinates2d function. I am confused on how to exactly use this. Will the format of "float[] inputVertices2d" will be like {x,y,x,y} ?

Also in Coordinates2d, public static final Coordinates2d VIEW ,what does "Android view, display-rotated, (x,y) in pixels." exactly means ?

**Comment by EbadSyed** [comment]
[https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/Frame#transformCoordinates2d(com.google.ar.core.Coordinates2d,%20float[],%20com.google.ar.core.Coordinates2d,%20float[])](url)

`public void transformCoordinates2d (Coordinates2d inputCoordinates, float[] inputVertices2d, Coordinates2d outputCoordinates, float[] outputVertices2d)` released in V1.7 solves the problem.

**Comment by DoctorB** [comment]
Hi EbadSyed, did you manage how to crop the recognized image by ARCore directly from its frame.acquireCameraImage()?

**Comment by alexs7** [comment]
@EbadSyed Do you have any updates regarding this ? Is the format as you said ? {(x,y),(x,y)...}

**Comment by EbadSyed** [comment]
> Hi EbadSyed, did you manage how to crop the recognized image by ARCore directly from its frame.acquireCameraImage()?

@DoctorB 
I acquired 640*480 image directly from frame.acquireCameraImage. It's not cropped, its the full image. The live view is cropped a little and that's by default.

**Comment by EbadSyed** [comment]
> @EbadSyed Do you have any updates regarding this ? Is the format as you said ? {(x,y),(x,y)...}

@alexs7 
Yes thats the format

float[] pixelCoords = {x1,y1,x2,y2};
float[] viewCoords = new float[4];

                    // Actual Transformation
                    frame.transformCoordinates2d(Coordinates2d.IMAGE_PIXELS,
                            pixelCoords,
                            Coordinates2d.VIEW,
                            viewCoords);

**Comment by DoctorB** [comment]
@EbadSyed
I see. So do you think is it possible to get from this frame only the image's portion that contains the recognized object? I understand only how to get the center of it but I don't understand how to get its rectangle or at least the dimensions. If you have any idea could you please lead me the way? Thank you in advance

**Comment by EbadSyed** [comment]
@DoctorB 

I am not exactly sure how to do it accurately. There are various methods of estimating the location in 3D.

One thing you can try to do is.

1) Use Tensorflow lite or any other to recognize and detect the object in Image.
2) You'll have the 2D coordinates from this process of the object in Image.
3) Check your point cloud and locate points in that area only. (3D points translated to 2D)
4) Use those points to estimate the location of the object.

**Comment by flankechen** [comment]
@EbadSyed thanks for your post, it your solution just transform single coordinate from "rendering space" to "cpu image space"? I have a mask image from cpu image, it sounds not very good to transfrom the whole image.

**Comment by EbadSyed** [comment]
@flankechen my solution was for a single point.

You can maybe use the depth map released in the latest version. (Only available on specific devices)

**Comment by sylviaGG** [comment]
Hi, @EbadSyed 
I am working on how to get those 2Dpixel points from point cloud.But I am stucking somehow. There was one post on stackoverflow describing how to do this, but it seems have some issue there.
I now have a 3D point in homogeneous coords, the 2D point should be ModelViewProjection matrcs(4*4) * 3D ponit(1*4). Now the result is 1*4 vector, I could divided each element by the 4th element and results in a 1*3 vector in normal coordinate, then how could I proceed to get the pixel point on the CPU image? 
Thx!

**Comment by alexs7** [comment]
You multiply the pose matrix with the 4-element vector. The last element should be 1. The third should be "w", which is the scale - if I recall correctly. So you could divide the first 2 values (x,y) with w, and that should give you the images coordinates. Just note that the pose in ARcore is the inverse from what most people would think, I think it takes you from the phone coordinate system to the world one, instead of the other way around, so you might need to use the inverse of that.

**Comment by sylviaGG** [comment]
@alexs7 Thank you for the quick reply! 

I have one question about this pose matrix. I do not have a anchor for this 3D point, it is just a normal point from the frame.acquirePointCloud(). SO how could I get this pose matrix?

My final goal is to get the RGB value for those 3D points on the frame.

Thx!

**Comment by alexs7** [comment]
Check this on how to get the pose: https://developers.google.com/ar/reference/java/com/google/ar/core/Camera
you might need `getViewMatrix()` I think

**Comment by sylviaGG** [comment]
I already have this view matrix in the transformation. Like in the helloAr example:
`// Get projection matrix.
 camera.getProjectionMatrix(projectionMatrix, 0, Z_NEAR, Z_FAR);
    // Get camera matrix and draw.
 camera.getViewMatrix(viewMatrix, 0);

Matrix.multiplyMM(modelViewProjectionMatrix, 0, projectionMatrix, 0, viewMatrix, 0);`

**Comment by alexs7** [comment]
Let's say you have a point 3D (x, y, z) => P. If you multiply that point by the viewMatrix, and the intrinsics matrix (K) that should give you the 2D coordinates. So it would look something like this: (x, y, w) = K * viewMatrix * P, then you can divide by w. Hope this helps.

**Comment by sylviaGG** [comment]
Thank you for this clarification. 
camera.getProjectionMatrix returns the projection matrix of the camera in that frame, Does this has the intrinsic information? But the size of it is 4*4. I am really confused at this point. I know the normal camera projection matrix should be a 3*4 matrixs, so I can get the result I want.

**Comment by alexs7** [comment]
Yes, sorry, I guess you can use that matrix too. Depends what you want to do.
