### ISSUE TITLE
import com.google.ar.core.Frame; not found

### ISSUE THREAD

**Issue by ManuelTS** [google-ar/arcore-android-sdk#688]
I found already a [stackoverflow question](https://stackoverflow.com/questions/53456936/class-com-google-ar-core-frame-not-found-when-gradle-is-compiled-with-java1-8) for this issue but with no answers at all, so I retry it here with more detail. In the .java file viewed with 
```
Android Studio 3.2
Build #AI-181.5540.7.32.5014246, built on September 17, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-43-generic
```
`import com.google.ar.core.Frame;` is not found. The project `build.gradle` file contains
```
dependencies {
   classpath 'com.android.tools.build:gradle:3.2.0'
   classpath 'com.google.ar.sceneform:plugin:'1.6.0' 
}
```
and in the module `build.gradle` contains
```
compileOptions {
     sourceCompatibility JavaVersion.VERSION_1_8
     targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by fredsa** [comment]
Documentation here:
https://developers.google.com/ar/develop/java/quickstart
