### ISSUE TITLE
Is arcore-unity-sdk forum dead? No one writes back.

### ISSUE THREAD

**Issue by FUBAR2077** [google-ar/arcore-android-sdk#690]
Hello, is any moderator on arcore-unity-sdk branch? Last action from moderator or any answer was ~26 Nov?

Anyone knows if it's alive and who I can write to in order to assign more workforce into this and ARCore whatsoever? ARCore becomes behind ARKit 2 badly..

**Comment by mpottinger** [comment]
@FUBAR2077 I sure hope not.

**Comment by fredsa** [comment]
Apologies to not writing back sooner. See my comment on issue #775
