### ISSUE TITLE
'error retrieving information from server 'DF-BA-AH-01'' Impossible to install ARCore app

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#693]
### SPECIFIC ISSUE ENCOUNTERED

Many users have the error message "error retrieving information from server 'DF-BA-AH-01' (and perhaps other similar error messages) when trying to install my free or paid app using ARCore.

It is hard to determine how many users have this message but according to several concordant statistics, I suspect that almost 50% of the users trying to install my ARCore app can't install it because of this bug.

It seems that this bug appeared (or increased significantly) beginning of November 2018.

And it seems that it increased a second time significantly around January 4th, 2019.

And a third time around January 8th (seems to be the biggest increase of the rate of occurence of this bug).

Note that the users who cant' install the app because of this bug can anyway leave a rating on Google Play (that is weird because normally a user can leave a rating only after install). It induces a drop in my daily ratings since beginning december 2018 (and much more significantly since January 4th and 8th) because the users complain about being not able to install my app :(

I see also drops in my installs:
- 42% drop of my installs between Nov 26th and Nov 28th (installs coming back to normal afterward)
- 40% drop of my installs between Dec 10th and 12th (installs coming back to normal afterward)
- 66% drop of my installs between Jan 7th and 10th (seems starting coming back to normal but to early to say if it will be the case...)

In these three periods, my daily rating dropped significantly because of the users complaining about not being able to install the app. I also received many emails from unsatisfied users.

I can see in the Google Play Console stats that the conversion rate on my app description is directly linked to the occurence rate of the bug. The conversion rate can be reduced of 50% on the periods where the bug occurs the most. For example, my conversion rate is reduced of 50% compared to normal weeks on the week Jan 7th to 13th.

Note that this 'DF-BA-AH-01' seems to be encountered by other persons:
- here: https://productforums.google.com/forum/#!msg/play/3dV1K-yk9XY/B0iuvo4nCAAJ Somebody says > 'If trying to install an AR app based on ARcore then you may need to install ARcire separately first.' (I don't know if this solution works ; even if it works, it is not a solution as my users do not know that they have to do that)
- here: https://play.google.com/store/apps/details?id=com.planeta.BowieMobile Another developer has the same problem with its app and mentions:
> 'IMPORTANT
> A Play Store issue is causing download issues for some people. If you see error code DF-BA-AH-01 or RH-01, we suggest you try the following:
> - Follow the steps outlined here https://support.google.com/googleplay/answer/7513003?hl=en to clear your play store cache.
> - Download the ARCore app separately and then try to download again
> 
> We apologize for the inconvenience and are working with the Play Store to resolve these issues as quickly as possible.'
- and even here (Google AR Measure app !): https://play.google.com/store/apps/details?id=com.google.tango.measure&showAllReviews=true Nicolas COURTECUISSE commented on Jan, 10th 2019 : > 'impossible de télécharger. Erreur lors de la récupération des informations depuis le serveur ([df-ba-ah-01])'

Note that my app is compiled with ARCore 1.0. I but it has probably no influence on this bug as the Measure app by Google also has this bug whereas it is probably compiled with last ARCore version.

### VERSIONS USED
- Android Studio: N/A
- ARCore SDK for Android: compiled with 1.0
- Device manufacturer, model, and O/S: unknown ; probably random
- Android versions : unknown, probably all

### STEPS TO REPRODUCE THE ISSUE
 1. Try to install the app
 2. 'error retrieving information from server 'DF-BA-AH-01'' Impossible to install ARCore app
 

### WORKAROUNDS (IF ANY)
See above.

### ADDITIONAL COMMENTS
Random bug.

**Comment by lvonasek** [comment]
My app is compiled with ARCore 1.6 and I also receive reports to this bug.

**Comment by littleylv** [comment]
My APP also got one ⭐️by users who could not install because of 'DF-BA-AH-01' 😥

**Comment by agGitHub** [comment]
Question to @lvonasek  and @littleylv : did you see an increase of the number of bugs over the same periods as us? With the same order of magnitude on the number of downloads? This would perhaps help the ARCore/Google Play teams identifying the problem. Thanks.

**Comment by lvonasek** [comment]
Not on my side.

**Comment by agGitHub** [comment]
Update for Google team. The first bad comments and emails I received about this problem started beginning of November. But the problem started to become critical end of November as mentioned in my question. I really need an urgent fix of this problem. I continue this morning to receive emails and bad ratings... Huge problem.

**Comment by fredsa** [comment]
Thank you for reporting this issue. The additional "me too" comments are helpful as well.

If possible, would each of you please indicate:
1. Whether your app is "AR Optional" or "AR Required" ([doc](https://developers.google.com/ar/develop/java/enable-arcore))
2. If your app is "AR Optional": do your users see the issue when installing your app OR when installing ARCore after launching the app OR both?

And, if you know
3. Does the issue appear to region specific (e.g. certain parts of the world, but not others)?
4. Does the issue appear to be specific to GSuite accounts (either business or education) or regular Gmail accounts?

**Comment by lvonasek** [comment]
I had three reports only (my app is still in beta on GP), also my feedback is not so helpful

1. AR required
2. ---
3.two reports are from USA, one from Russia
4.mostly likely regular Gmail accounts

**Comment by agGitHub** [comment]
Hi Fred.

For me:
1. AR required
2. N/A
3. According to the comments left by the users, I am sure that it happens at least on the following Android version/language/device (no info on the country in the reports):

Android   version | Language | Device
-- | -- | --
8.0 | Country : india (language : ?) | Moto X (4)   (payton)
8.0 | en ? | Galaxy Note8 (greatlte)
8.0 | en ? | Galaxy Note8 (greatlte)
8.0 | es | Galaxy S9+ (star2qltechn)
8.0 | es | Galaxy S9 (starqltechn)
8.0 | id | alaxy A8(2018) (jackpotlte)
8.0 | id | Galaxy J7 (j7y17lte)
8.0 | kr | Galaxy Note8 (greatlteks)
8.0 | nl | Galaxy S8 (dreamlte)
8.0 | pt | Xperia XZ Premium (G8142)
8.0 | ru | Galaxy S8
8.0 | tr | Galaxy S8+ (dream2lte)
8.0 | tr | Galaxy S7 (herolte)
8.0 | vi | Galaxy S9+ (star2lte)
8.1 | ar | Galaxy J7 (j7y17lte)
8.1 | fr | P20 Pro (HWCLT)
8.1 | fr | Galaxy S8 (dreamlte)
8.1 | hi | Moto G (5S) Plus (sanders_n)
8.1 | pl | Mate 20 lite (HWSNE)
8.1 | ro | Mate 20 lite (HWSNE)
unknown | en | sanders_n
unknown | ro | herolte

Conclusion => It seems that this bug happens:
**- probably only on Android 8 and 8.1** (no negative feedbacks for Android 7.x and 9.x)
- probably in any language/country
- on many kinds of devices

4. According to the emails I receive, almost of them are from "@gmail.com"  emails. A few are with other extensions. I don't know if they perhaps logged two accounts on their phone (one perso gmail and one pro gmail with their pro extension). It is the case on my phones but I never saw this bug.

Note that I asked to one or two users if they have the same error when trying to install another app working with ARCore : they said that they have no problem with the other ARCore app. I think that this does not mean that the problem occurs only with my app (can be seen on the store that happens on many ARCore apps) but just means that it happens randomly on some apps and that it does not affect all the ARCore apps on a same device. It is also possible that an app cannot be installed because of this bug at a defined time but can be installed later (a same device is sometimes buggy and sometimes not buggy?).

Hope this helps.

**Comment by littleylv** [comment]
@agGitHub  No. Just couple of users complaining this problem.

@fredsa Hi.
1. AR required
2. N/A
3. 
- CA, Galaxy S9
- US, Galaxy S8+
- ?, huawei mate 20
- US,  Galaxy S9
- UK, ?
4. Regular accounts

**Comment by agGitHub** [comment]
@fredsa  Thanks for your great support. I will let you know if we see any other problems. Regards.

**Comment by tammojan** [comment]
I'm seeing this error code while trying to install Duolingo on a pocophone. Android version 9, language NL. Not sure it is AR related.

**Comment by ronrotty** [comment]
For your customers to be able to install this, you must roll back ARcore install (uninstall to packaged version).  Then install your ap.  Then, you can reinstall ARcore.  Not sure why, but this works.
