### ISSUE TITLE
LG V35 ThinQ: Auto-focus does not work

### ISSUE THREAD

**Issue by ptc-dberry** [google-ar/arcore-android-sdk#694]
### SPECIFIC ISSUE ENCOUNTERED

Enabling auto-focus via ARCore does not work on an LGV35 ThinQ.
Run the computer_vision_c sample, set auto focus to on and the gpu rendered image will not change or come into focus. The image is the same with or without auto-focus on. Running the same application on a Samsung Note 9, you can clearly see auto-focus operating when it is turned on.

### VERSIONS USED
- Android Studio: 3.1.4
- ARCore SDK for Android: 1.6
- Device manufacturer, model, and O/S: LG V35, ThinQ, LM-V350
lge/judyp_lao_com/judyp:8.0.0/OPR1.170623.032/18334162876b7.FGN:user/release-keys

- ARCore: 1.6
 Packages:
      versionName=1.6.181112096
      signatures=PackageSignatures{8950115 [53bcc66f]}
  Hidden system packages:
      versionName=0
      signatures=PackageSignatures{519991 []}
      packages
      packages
      packages
      packages

  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
Packages:
      versionName=1.6.181112096
      signatures=PackageSignatures{8950115 [53bcc66f]}
  Hidden system packages:
      versionName=0
      signatures=PackageSignatures{519991 []}

- Output of `adb shell getprop ro.build.fingerprint`: 

lge/judyp_lao_com/judyp:8.0.0/OPR1.170623.032/18334162876b7.FGN:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Run the computer_vision_c sample, set auto focus to on and the gpu rendered image will not change or come into focus. The image is the same with or without auto-focus on. Running the same application on a Samsung Note 9, you can clearly see auto-focus operating when it is turned on.

The regular app camera auto-focus works as expected.

**Comment by inio** [comment]
Unfortunately we were unable to get some LG devices' primary back-facing camera working with ARCore.  On these devices we use the secondary camera which is fixed focus.  On these devices enabling auto-focus mode has no effect.

We'll be updating the docs soon to reflect this.

**Comment by ptc-dberry** [comment]
Thanks for the update and appreciate you looking into this. It would be nice that in this case you could make the developer aware that auto focus was not available. For example ArConfig_getFocusMode() should return AR_FOCUS_MODE_FIXED so you could check that the ArConfig_setFocusMode() succeeded. Based on the sample code I believe it is returning AR_FOCUS_MODE_AUTO.

Alternatively ArSession_configure could return an error or a warning, when auto focus was set to on on these devices..

**Comment by fredsa** [comment]
API Reference documentation and the ARCore Support Devices page (https://developers.google.com/ar/discover/supported-devices) have been updated.
