### ISSUE TITLE
how to disable vertical plane in my code.. need help asap

### ISSUE THREAD

**Issue by ishaang10** [google-ar/arcore-android-sdk#697]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        arFragment=(ArFragment) getSupportFragmentManager().findFragmentById(R.id.ux_fragment);
        assert arFragment != null;
        ArSceneView arView= arFragment.getArSceneView();
        Scene scene=arView.getScene();

        ModelRenderable.builder().setSource(this,Uri.parse("armchair.sfb")).build()
                .thenAccept(modelRenderable -> chickenren=modelRenderable).exceptionally(throwable -> {
            Toast.makeText(this,"unable",Toast.LENGTH_LONG).show();
            return null;
        });

        arFragment.setOnTapArPlaneListener(
                (HitResult hitResult, Plane plane, MotionEvent motionEvent)->{

                    if(plane.getType() != Plane.Type.HORIZONTAL_UPWARD_FACING)
                        return;

                    Anchor anchor = hitResult.createAnchor();
                    AnchorNode anchorNode = new AnchorNode(anchor);
                    anchorNode.setParent(scene);

                    TransformableNode chicken = new TransformableNode(arFragment.getTransformationSystem());
                    chicken.setParent(anchorNode);
                    chicken.setRenderable(chickenren);
                    chicken.select();

                });

**Comment by claywilkinson** [comment]
Do you mean how to configure the session so you can remove this check?
``` 
        if(plane.getType() != Plane.Type.HORIZONTAL_UPWARD_FACING)
                    return;
```

To do this you need to configure the session's plane finding mode.

The best way to do this is to extend ArFragment and override `getSessionConfiguration`
```
  @Override
  protected Config getSessionConfiguration(Session session) {
    Config newConfig = session.getConfig();
    newConfig.setPlaneFindingMode(Config.PlaneFindingMode.HORIZONTAL);
    return newConfig;
  }
```
Then use your subclass in the layout instead of ArFragment.

For a quick and dirty solution you can just add to `onResume()` in your activity

```
  @Override
  public void onResume() {
    super.onResume();
    Session session = arView.getSession();
      Config newConfig = session.getConfig();
      newConfig.setPlaneFindingMode(Config.PlaneFindingMode.HORIZONTAL);
      session.configure(newConfig);
    }
```

**Comment by ishaang10** [comment]
already figured that out and forgot to close this. thanks alot sir .. :)

**Comment by hadibeiki** [comment]
I want only to detect vertical plan, try many codes but not successes ,
can i ask you how to do that!?
