### ISSUE TITLE
Feature request - 3D Reconstruction library

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#698]
ARCore has a plane detection which enables app developers to place the content. However this scene understanding is not good enough for advanced usecases like e.g. physics. There was already one feature request https://github.com/google-ar/arcore-android-sdk/issues/50 requesting the same however it was closed without bringing any solution.

Tango3DR library is used on ARCore works currently this way https://www.youtube.com/watch?v=lf_0V9VIt_w. However it is very complicated to integrate it into the app and it works on Android only.

In this paper https://dl.acm.org/citation.cfm?id=3275041 is described a method to create dense point cloud (or depth map) from the image sequence.

**Comment by barnjamin** [comment]
https://drive.google.com/file/d/1AABFJ3NgD5DAo5JEpEjWZrcQNzjZnvW9/view heres a link to the pdf of that paper

**Comment by lvonasek** [comment]
I am closing this. Developers could use the deprecated Tango3DR library, I opensourced 3D Live Scanner using that:
https://github.com/lvonasek/3DLiveScanner

The experience with 3D reconstruction is bad in interiors as ARCore has limited motion tracking capabilities (https://github.com/google-ar/arcore-android-sdk/issues/1347)
