### ISSUE TITLE
Sample hello_ar_c fails to build

### ISSUE THREAD

**Issue by matcegla** [google-ar/arcore-android-sdk#699]
### SPECIFIC ISSUE ENCOUNTERED
After opening the sample hello_ar_c in Android Studio, the project fails to build with a message
```
Cause: executing external native build for cmake /home/matcegla/surfaces/ar-core/sdk/arcore-android-sdk/samples/hello_ar_c/app/CMakeLists.txt
```
The issue persists on all C samples, but Java samples build and work correctly.

### VERSIONS USED
- Android Studio: 3.3
- ARCore SDK for Android: 1.6.0
- Device manufacturer, model, and O/S: N/A
- ARCore: N/A
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: N/A

### STEPS TO REPRODUCE THE ISSUE
 1. Install Android Studio(`~/surfaces/ar-core/android-studio`), NDK and CMake(via SDK Manager), ARCore SDK(version 1.6 from Releases in `~/surfaces/ar-core/sdk`).
 2. Open the hello_ar_c sample(Open an existing Android Studio project and opened the `samples/hello_ar_c`).
 3. Try to build project (Build > Make project).

### ADDITIONAL COMMENTS
I am running Ubuntu 18.10 with no major alterations.

**Comment by claywilkinson** [comment]
Can you share the specific error messages?  This looks like the high level error that cmake failed.  You might need to toggle the view in the build window to see the text  error messages from cmake. (or build in the terminal window).

**Comment by matcegla** [comment]
Thanks! It turns out that ninja was not installed, even though the quickstart page does not mention this requirement.
