### ISSUE TITLE
Google Pixel app keeps stopping

### ISSUE THREAD

**Issue by stopsatgreen** [google-ar/arcore-android-sdk#7]
Updated Android Studio, downloaded sample files, installed app on Pixel. App HelloAR Java won’t load, keeps stopping. Android version 7.1.2, 5 August security patch.

**Comment by inio** [comment]
Without a logcat it's difficult to diagnose, but have you installed arcore-preview.apk on the device yet? This is described in the [Prepare Your Device section](https://developers.google.com/ar/develop/java/getting-started#open-sample).

arcore-preview.apk is needed to run ARCore apps.

**Comment by stopsatgreen** [comment]
Ah! I’d set my device up using the AR on the Web instructions, which lacked that step, and missed it when changing to Android Studio. Thanks!
