### ISSUE TITLE
Will camera be provided in version 1.0?

### ISSUE THREAD

**Issue by 544531645** [google-ar/arcore-android-sdk#70]

**Comment by 544531645** [comment]
Is the user able to call the camera to take pictures and other things?

**Comment by nathanmartz** [comment]
You can already get the camera image data via Session.getCameraTextureName(). We will not be able to expose full control of the camera while ARCore is running as that would lead to poor tracking quality in many cases.

**Comment by 544531645** [comment]
why I no this method ..

**Comment by 544531645** [comment]
I only find setCameraTextureName

**Comment by nathanmartz** [comment]
Sorry, typo on my part. That's the function I was referring to.

**Comment by 544531645** [comment]
no but I want get the camera image and get video

**Comment by 544531645** [comment]
how I can take picture and record video like use camera

**Comment by nathanmartz** [comment]
The [docs for that API](https://developers.google.com/ar/reference/java/com/google/ar/core/Session.html#setCameraTextureName(int)) explain how to use it to get the underlying OES texture. If you want to know how to work with OES textures, there are good online materials, and this issue tracker is just for problems with the SDK, not general "how to" questions.

**Comment by inio** [comment]
With Developer Preview 2, we've added [computervision sample code](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision) that shows how to get CPU access to the pixel data.
