### ISSUE TITLE
Samsung Tab S3: not able to find stable surfaces in ARCore

### ISSUE THREAD

**Issue by richard3575** [google-ar/arcore-android-sdk#701]
Tested on:

Sony ZX premium – (working well) pointing to the floor within seconds finds the floor and puts the white grid on it.

Samsung S3 Tab (listed as supported device) – (not working well) same floor, it takes near a minute sometimes to find the floor and then only shows purple or red gird, which then swims away or disappears. It is not stable enough to use.

The Issue – we saw this happen on the Sony ZX, it was working awesome, then an OS update from Nougat to PIE made it totally unusable.. However that has since been rectified with an OS patch from Sony. The Samsung S3 is still unusable.

Devices: Samsung S3 Tab SM-T825, Android 8.0.0
Samsung S3 Tab Build fingerprint:
samsung/gts3lltexx/gts3llte:8.0.0/R16NW/T825XXU2BRL2:user/release-keys
Android Studio: 3.3
ARCore 1.6 Packages: versionName=1.6.181112096

Note: the original app was developed in Unity, however with no changes to the app and only a change to the OS (from 8.0 to 9.0) on the Sony ZX it appears that that was the issue. We have since done tests on the Android Studio HelloAR package with similar results

Sequence of events:

Sept 2018 
- ARCore app created and tested on Sony ZX Premium (Android 8.0)
- Works great, very well in finding ground plans quickly and accurately. Mostly finding white grid surfaces.

Mid-Oct 2018 
- Sony ZX OS update to PIE 9.0 – same app now will not find ANY surfaces, it just cannot find any surface at all and the app is useless (issue reported by another user #639 ) 

Dec 2018 
- Samsung S3 Tab purchased (as it’s listed as a support device) as Sony device not working. 
- Same app is giving the same results – it just will not find any surfaces what so ever. 
- Other apps tested on device ARMeasure, Ikea app, Measure from Google. Same results, unable to find accurate surfaces

End-Dec 2018 
- Sony ZX – gets a new OS update from Sony and is now back to how it was – working nicely, quickly and accurately.

End-Jan 2018 
- To-date – Samsung S3 Tab has all updates installed, but still giving very poor experience.

Reading github there are a number of other reported similar issues. 
Similar issues: #639   #659  #419  #590 (not sure about the last 2, but they sound similar)

Also, if you look at the reviews for   https://play.google.com/store/apps/details?id=com.google.tango.measure&showAllReviews=true 
You’ll see there’s a lot of negative reviews about the app not finding surface (yeah, I know a good 60% of those will be on unsupported devices, or bad surfaces and user error, but still there’s a lot of “not working” issues there).

@fredsa  requested we do the following:
Please try running the unmodified HelloAR sample project. When doing so:

	Download the latest ARCore for Android SDK (releases page)
	Connect an ARCore supported device
	Make sure you device is up to date (running the latest available version of the o/s)
	Verify that the latest version of ARCore is installed

I have done this and still get the same results – the Sony ZX is very good and the Samsung is poor (whilst it can find surfaces, they are not stable)
Logcat’s from both devices for both for “HelloAR” are attached
[log-samsungS3Tab_HelloAR.txt](https://github.com/google-ar/arcore-android-sdk/files/2803606/log-samsungS3Tab_HelloAR.txt)
[log-sonyZXPremium_HelloAR.txt](https://github.com/google-ar/arcore-android-sdk/files/2803607/log-sonyZXPremium_HelloAR.txt)

Please advise as this is listed as a support device and we have a client looking to purchase a number of them, however due to the stability we can not deliver a viable solution.

Thank you
-Richard

**Comment by richard3575** [comment]
Hi @fredsa any thoughts on this issue? We've done as you requested and attached the logs - we're really perplexed - we need a tablet that can work with ARCore.  
Thanks in advance for your help!

**Comment by fredsa** [comment]
Thank you @richard3575. Forwarding to our certification and QA team to reproduce.

**Comment by richard3575** [comment]
Also someone else has reported on Samsung S4 Tab #720 

It's been almost 3 months since this was first reported and as an issue #591 and we're still no closer. We've provided the requested logs and will provide any further details you require. 
Thank you

**Comment by fredsa** [comment]
@richard3575 Would you be able to attach a video recording of the problematic plane finding on your **Samsung Tab S3**, using `adb shell screenrecord --bugreport`?

**Comment by richard3575** [comment]
hi @fredsa  We’ve been trying to capture the issue, however, I have to say the Tab is now performing much better. Not perfect, and when we run it next to the Sony Xperia it’s clear the Sony is faster and more stable. However, the Samsung Tab is now again usable and finding surfaces. 

I’m not sure what has changed, I know we updated ARCore to 1.7 recently, I’m not sure if there was any other updates.
For reference the fingerprint is: samsung/gts3lltexx/gts3llte:8.0.0/R16NW/T825XXU2BRL2:user/release-keys
We can close this issue now. 

Thanks for your help.
