### ISSUE TITLE
Number of expected API calls when hosting/resolving a Cloud Anchor

### ISSUE THREAD

**Issue by roycho111** [google-ar/arcore-android-sdk#707]
Hi there,

I'm working on ARCore Cloud Anchor and I have some questions.

1. I found out that when i call XPSession.CreateCloudAnchor(anchor), write request of cloud anchor api goes up by one, but also read request goes up as well. Is this intended?

2. When XPSession.ResolveCloudAnchor(anchorId) is called, read request goes up by seven. Is this normal? or am I doing something wrong here?

**Comment by fredsa** [comment]
Hi @roycho111 — it's currently normal / expected to see multiple API calls being made.

1. In addition to the call to "host" the anchor, the implementation may perform status checks that result in additional reads.
2. If an anchor cannot immediately "resolve", then additional calls are made.

—

To confirm that your own app is making the expected number of API calls, compare your app's behavior with that of the unmodified Cloud Anchors sample app. You should expect to see similar behavior there. Note, you may see a different number of API calls in different sessions, depending on the current state of the API, and how easily the Anchor is able to resolve itself.
