### ISSUE TITLE
[device support]Huawei P20 Pro UnavailableDeviceNotCompatibleException

### ISSUE THREAD

**Issue by littleylv** [google-ar/arcore-android-sdk#708]
I filled an issue (#664) before. Now P20 Pro can install my APP, but throws an exception `UnavailableDeviceNotCompatibleException` .
Maybe this issue is duplicate of #429 and #646 
When can I expected to get this fixed?

Thanks.

**Comment by Raerion** [comment]
@littleylv I'm having the same problem as you and many other people, even with Android 9 and the new ARCore 1.7.
The main issue about this problem seems to be #585 which is still open.

**Comment by Wandrer** [comment]
Which P20 Pro do you have? SingleSIM or DualSIM?

**Comment by SalvatoreMeschini** [comment]
Model: CLT-L29 (Huawei P20 Pro)
Build number: 9.0.0.195 (C432E5R1P9) GPU TURBO
AR Core: 1.7.190128066

does **NOT** work:

* Google Measure shows "_Unknown ARCore Error (Unavailable DeviceNotCompatibleException)_"
* AR Ruler shows something like "_Failed to create AR session_".

The device is **DUAL SIM**.

**Comment by fredsa** [comment]
In addition to device manufacturer, model, and O/S, please include:
- ARCore version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Device fingerprint:
   Output of `adb shell getprop ro.build.fingerprint`

**Comment by SalvatoreMeschini** [comment]
ARCore version:
**Packages:
    versionName=1.7.190128066
Hidden system packages:
    versionName=0**

Device fingerprint:
**HUAWEI/CLT-L29/HWCLT:9/HUAWEICLT-L29/195C432R1:user/release-keys**

Google Measure shows the following error message: "Unknown ACCore error (Unavailable DeviceNotCompatible Exception)".

Other AR-based apps show similar messages.

**Comment by SalvatoreMeschini** [comment]
This is what I found in my Logcat:

02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for UUpC5W
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for CLT-L29/HWCLT_accelerometer-lsm6dsm_OFILM
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for J1ASAV
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for HWCLT_accelerometer-lsm6dsm_OFILM
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for ioG7OZ
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for CLT-L29
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:421 Could not locate device profile for HUAWEI/CLT-L29/HWCLT_accelerometer-lsm6dsm_OFILM:9/HUAWEICLT-L29/195C432R1:user/release-keys
02-28 11:56:07.393 E/native (19540): calibration_jni.cc:184 **No device profile available for build fingerprint HUAWEI/CLT-L29/HWCLT_accelerometer-lsm6dsm_OFILM:9/HUAWEICLT-L29/195C432R1:user/release-keys**
02-28 11:56:07.395 E/native (19487): **session_create_implementation_shared.cc:870 Unable to obtain device profile from the content provider: generic::not_found: Device is not supported.
02-28 11:56:07.395 E/native (19487): session_create_implementation.cc:108 Failed to create calibration provider.
02-28 11:56:07.395 W/native (19487): session_create_implementation.cc:109 ArSession_createWithSettingsImplementation_private returning ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE: .**

**Comment by Wandrer** [comment]
OK next question.

As many antivirus solutions on the PC platform are badly interfering with apps and this error clearly shows that the configuration data can't be loaded from the contend provider. 

1. Which antivirus solution do you use?
Options: The buildin one, none, a different one with version number and GoogleAppStore link

2. Is there some kind of filter active either on your Router or at your provider? 
UK has a filter with 1% porn and 99% nonporn for example.

**Comment by SalvatoreMeschini** [comment]
> OK next question.
> 
> As many antivirus solutions on the PC platform are badly interfering with apps and this error clearly shows that the configuration data can't be loaded from the contend provider.
> 
> 1. Which antivirus solution do you use?
>    Options: The buildin one, none, a different one with version number and GoogleAppStore link
> 2. Is there some kind of filter active either on your Router or at your provider?
>    UK has a filter with 1% porn and 99% nonporn for example.

I'm not sure that this comment is related to the current issue. In any case, I don't use an antivirus and the same issue happens regardless of the network (4G, Wifi, ...).

From what I can see, there's a mismatch between the device build fingerprint and the build fingerprint retrieved by ARCore. That's why the device is incorrectly reported as "Device is not supported" / AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE.

Likely there are some missing entries in the compatibility database and/or the build fingerprint is not detected correctly...

**Comment by SalvatoreMeschini** [comment]
Version 1.8.190311076 fixed this issue.
