### ISSUE TITLE
Augmented face demo is missing

### ISSUE THREAD

**Issue by hcGuyue** [google-ar/arcore-android-sdk#709]
I cannot find the augmented face demo in the release files. Is that missing? Then, how to use it based on the v1.7.0 sdk?

**Comment by lvonasek** [comment]
Currently there is an example code for Unity and Unreal only:
* [Unity Augmented Face](https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets/GoogleARCore/Examples/AugmentedFaces)
* [Unreal Augmented Face](https://github.com/google-ar/arcore-unreal-sdk/tree/master/AugmentedFaces)

**Comment by michaelvogt** [comment]
There is also a [sample using Sceneform](https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/augmentedfaces)

**Comment by michaelmauzy** [comment]
Here's some documentation:
[Developer Guide for Augmented Faces for Sceneform](https://developers.google.com/ar/develop/java/sceneform/augmented-faces-developer-guide)
[Developer Guide for Augmented Faces for Unity](https://developers.google.com/ar/develop/unity/augmented-faces/developer-guide)
[Developer Guide for Augmented Faces for Unreal](https://developers.google.com/ar/develop/unreal/augmented-faces/developer-guide)

**Comment by AndroidDeveloperLB** [comment]
@michaelvogt While it seems this is the only one that works straight within Android Studio, it seems the sample has about 0.5 sec delay between what I do and what I see. Also, the mask (ears and nose in this case) seem to move a lot even though I stand still.
:(

**Comment by michaelvogt** [comment]
Well, that virtual objects move is a big problem in general with ARCore. Whether you place an object on a plane or through a marker image. This completely destroys the illusion.

But, I don't see a delay on my phone. Which device do you use?

**Comment by AndroidDeveloperLB** [comment]
@michaelvogt I have Pixel 2 with Android P (stock) , PQ2A.190205.002 .
You can notice the difference in time by moving your head left and right (like saying "no" in most cultures ) quickly.
Maybe I exaggerated a bit and it's not 0.5 seconds, but it is noticeable. It's not smooth.

**Comment by michaelvogt** [comment]
Yes, I see the same, together with the same bad tracking as with ARCore images. 

Known since the beginning and nothing changed since.

**Comment by fredsa** [comment]
Closing this issue which was about locating the Augmented Faces samples. Links to those above.

For tracking quality, let's continue to use #534.
