### ISSUE TITLE
Example Missing?

### ISSUE THREAD

**Issue by joecaraccio** [google-ar/arcore-android-sdk#710]
I was going through some of the AR Core content..and noticed specifically this example:
https://youtu.be/ttdPqly4OF8

Is that example available anywhere? Would love to see how they created that drawer (right word for that component?) and how they made the components adjustable.

Any ideas?

**Comment by fredsa** [comment]
Hi @joecaraccio.

Not sure if you're also a Unity developer. If you were, there's an [ObjectManipulation](https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets/GoogleARCore/Examples) sample in the latest ARCore SDK for Unity. Unfortunately, there's not one yet for a 2D (on-screen) "drawer" that users can use to select 3D content from.

However, if you're inspired and would like to develop your own, I can suggest looking through our [Augmented Reality Design Guidelines](https://designguidelines.withgoogle.com/ar-design/). See specifically, the section on [content placement](https://designguidelines.withgoogle.com/ar-design/content/content-placement.html)
