### ISSUE TITLE
Add support for "OnePlus 3"

### ISSUE THREAD

**Issue by tom2048** [google-ar/arcore-android-sdk#711]
Could you add support for OnePlus3? It's almost the same device as already supported OnePlus3T.

**Comment by zenxxz** [comment]
Please support OP3

**Comment by gmartinsnull** [comment]
This would be much appreciated.

**Comment by devbridie** [comment]
No update on this device, unfortunately. #89 tracks device support requests, so I'm closing this one as a dupe.
