### ISSUE TITLE
ARCore Elements incorrectly sets `minSdkVersion=27`, does not support ARCore supported phones (Samsung Galaxy S7 / Asus Zenfone AR)

### ISSUE THREAD

**Issue by FUBAR2077** [google-ar/arcore-android-sdk#712]
I have a problem - I have Samsung Galaxy S7 which is supported by ARCore but the ARCore Elements app does say that it does not support my device, can you please help me with this issue?
If this is not the right place then where can I write for support to this app as apps-help@google.com listed on app site is no-reply email?

**Comment by michaelvogt** [comment]
Yes, same here 🤦

With the Asus Zenfone AR. Clearly shows the ARCore teams attitude. Unbelievable.

**Comment by FUBAR2077** [comment]
Any updates on this subject @nvictornvictor ?

**Comment by fredsa** [comment]
In addition to device manufacturer, model, and O/S, could you please add:
- ARCore version
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Device fingerprint
  Output of `adb shell getprop ro.build.fingerprint`

**Comment by FUBAR2077** [comment]
Hello @fredsa ,thanks for reply :)

Manufacturer: Samsung
Model: SM-G930F
O/S: Android *.0.0 , version number R16NW.G30FXXS3ERLF
ARCore versionName=1.7.190128066

Let me know if you need anything else

**Comment by fredsa** [comment]
Thanks, by *.0.0 I assume you mean 8.0.0.

Could you also include the output of `adb shell getprop ro.build.fingerprint`

**Comment by FUBAR2077** [comment]
Yes, sorry, should be 8.0.0

output from command:
samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXS4ESAE:user/release-keys

**Comment by fredsa** [comment]
Thank you @FUBAR2077.

It looks like the `android:minSdkVersion` was unintentionally set to `27` (Android 8.1) which is why you're currently seeing the app as unavailable on your 8.0.0 device.

**Comment by FUBAR2077** [comment]
Ok, thank you for checking :) Who can I contact to enable it for device in future updates?

**Comment by fredsa** [comment]
Please follow this issue for any updates. The ARCore Elements app will also become installable once the `minSdkVersion` has been fixed.

**Comment by Jace-Samsung** [comment]
Encountered issue on Samsung Note 8 device with Android version 8.0.0.

**Comment by Logician724** [comment]
I am having the same problem with my samsung galaxy s8+, hope this gets fixed soon.

**Comment by SirLouLou** [comment]
The same problem on my Galaxy S7 Edge. Any updates yet?

**Comment by fredsa** [comment]
Thank you for your continued patience, and apologies for the delay. We're working on getting the app updated with the correct `minSdkVersion`.

**Comment by fredsa** [comment]
The "ARCore Elements" app (https://play.google.com/store/apps/details?id=com.google.ar.unity.ddelements) should now correctly specify `minSdkVersion=24`.

**Comment by FUBAR2077** [comment]
Thank you :)

Yet, there is still no update on the store though - the version that is there currently is from 14.02.2019, can you please ask the team to upload new one?

**Comment by Jace-Samsung** [comment]
Thanks @fredsa for fixing and notifying!

**Comment by fredsa** [comment]
Apologies for marking this fixed. The update has been published, but is still being incrementally rolled out. We expect the rollout to reach 100% of users/devices over the next few days.

**Comment by fredsa** [comment]
Rollout reach 100% early last week.

**Comment by hi-sanchoman** [comment]
Hi!
Oppo RX17 Pro does not support :(
In some countries it is also known as Oppo R17 Pro.
ARCore is supported. Version is: 1.8.190311106
Android verion: 8.1.0

Please, help!
