### ISSUE TITLE
[BUG] Pink camera feed when using OpenGL ES2

### ISSUE THREAD

**Issue by Guzse** [google-ar/arcore-android-sdk#713]
### SPECIFIC ISSUE ENCOUNTERED
The camera feed becomes pink as if I'm missing a texture when using OpenGL ES2 in Unity. The error doesn't occur with OpenGL ES3.

### VERSIONS USED
- Unity: 2018.1.7f1 
- ARCore SDK for Android: 1.6.0
- Device manufacturer, model, and O/S: all devices, tested on Galaxy Note 7
- ARCore: 
    Packages:
      versionName=1.7.190128066
- Output of `adb shell getprop ro.build.fingerprint`: 
samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXS3ERLF:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Create new Unity Project
 2. Implement ARCore
 3. Set Graphics API to "OpenGL ES2", disable Multithread Rendering
 4. Use standard ARCore prefab, remove standard camera
 5. Buidl and test game

**Comment by fredsa** [comment]
Would you mind filing the issue in the ARCore SDK for Unity issue tracker?

https://github.com/google-ar/arcore-unity-sdk/
