### ISSUE TITLE
Add support for "Razer Phone 2"

### ISSUE THREAD

**Issue by Anirudh901** [google-ar/arcore-android-sdk#715]
could Razer phone 2 be added as a whitelisted device please

### SPECIFIC ISSUE ENCOUNTERED
Could Razer phone 2 be added as a whitelisted device, please

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: Razer phone 2
- ARCore: 1.7
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by MadKingEzekeil** [comment]
Seconding this

**Comment by ahmaddarbandi0322224977** [comment]
SM-J701F/DS  Android 8.1.0

**Comment by GearWalker** [comment]
Sry, for a dump question. How the process of adding support for a new device?

**Comment by RealoFoxtrot** [comment]
Discovering this issue, it's an oddity, as ARCore 1.5 has Razer Phone 1 Support

**Comment by RESizemore** [comment]
Would like to add to this request. I work for a VR/AR company and I am unable to show off our product built on ARCore using my Razer Phone 2.

**Comment by rlyhate** [comment]
Can we finally get ar support for razer phone 2?

**Comment by Toasterizzle** [comment]
Definitely something that'd be appreciated. With Minecraft Earth coming up, it'd be nice to actually use my purpose built "gaming" phone for well... playing popular games

**Comment by skyser2003** [comment]
+1
Razer phone 1 is supported but 2 isn't, this is weird

**Comment by Anirudh901** [comment]
Does not look like it's happening
