### ISSUE TITLE
CheckAvailability it's giving too many false positives

### ISSUE THREAD

**Issue by firetrap** [google-ar/arcore-android-sdk#716]
### SPECIFIC ISSUE ENCOUNTERED
The API created to check if the ARCore is supported it's not giving correct information neither in 1.7.0 not in previous one.

### VERSIONS USED
- Android Studio: 3.3.1
- ARCore SDK for Android: 1.7.0
- Device manufacturer, model, and O/S: Xiaomi mi A2
- ARCore: Not Supported
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. Run the check and see the result
 2. Example: 
''ArCoreApk.Availability availability = ArCoreApk.getInstance().checkAvailability(this);
        if (availability.isTransient()) {
            // Re-query at 5Hz while compatibility is checked in the background.
            new Handler().postDelayed(this::checkArcoreAvailability, 200);
        }
        isArcoreSupported = availability.isSupported();''

### WORKAROUNDS (IF ANY)
None

**Comment by fredsa** [comment]
Note that the device you listed (Xioami mi A2) is currently list on the support devices page:
https://developers.google.com/ar/discover/supported-devices

Please specify what value is returned by `checkAvailability()`.

**Comment by firetrap** [comment]
> Note that the device you listed (Xioami mi A2) is currently list on the support devices page:
> https://developers.google.com/ar/discover/supported-devices
> 
> Please specify what value is returned by `checkAvailability()`.

I don't know where you see that Xiaomi mi A2 it's listed.
The only devices i see are:

Xiaomi | Mi 8, Mi 8 SE | No support for CPU image access.
-- | -- | --
Mi Mix 2S |  
Mi Mix 3 |  
Pocophone F1

**Comment by todoranalex** [comment]
Hi, are there yet any workarounds for this issue?

**Comment by kobe-anacoimbra** [comment]
Hi! Any updates on this problem? I am still getting some false positives here!

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
