### ISSUE TITLE
Add support for "Xiaomi Mi A2"

### ISSUE THREAD

**Issue by HandaTakuya** [google-ar/arcore-android-sdk#717]
Why Mi A2 not support ARCore (SD660, 6GB RAM, 128GB ROM) but Nokia 7 plus (SD660, 4GB RAM, 64GB ROM) support ARCore ?

**Comment by alexbertis** [comment]
Would be nice if someone just gave some information. I think it's not too much to ask.

**Comment by evertonstz** [comment]
Probably because Nokia ported it  to their phone and Xiaomi is too incompetent to care.

**Comment by kobe-anacoimbra** [comment]
I have the same question ...

**Comment by devbridie** [comment]
No news on support for the A2 just yet. #89 is tracking device enablement requests.
