### ISSUE TITLE
Load Runtime Model : Failed resolution of: Lcom/google/common/io/Files

### ISSUE THREAD

**Issue by eddydn** [google-ar/arcore-android-sdk#718]
When i use load runtime Model 3D , i have error and this exception have show in my log cat

This is my code : 

 ModelRenderable.builder()
                        .setSource(MainActivity.this, RenderableSource.builder().setSource(
                                MainActivity.this,
                                Uri.parse(GLTF_ASSET),
                                RenderableSource.SourceType.GLTF2).build())
                        .setRegistryId(GLTF_ASSET)
                        .build()
                        .thenAccept(modelRenderable -> {

                            Anchor anchor = hitResult.createAnchor();
                            AnchorNode anchorNode = new AnchorNode(anchor);
                            anchorNode.setParent(arFragment.getArSceneView().getScene());

                            createModel(anchorNode,modelRenderable);

                        }).exceptionally(
                        throwable -> {
                            Log.d("ERROR3D",throwable.getMessage());
                            Toast toast =
                                    Toast.makeText(MainActivity.this, "Unable to load renderable " +
                                            GLTF_ASSET, Toast.LENGTH_LONG);
                            toast.setGravity(Gravity.CENTER, 0, 0);
                            toast.show();
                            return null;
                        });

I'm use Sceneform 1.7.0 version

**Comment by fredsa** [comment]
Would you mind filing an issue in the Sceneform SDK for Android tracker?
https://github.com/google-ar/sceneform-android-sdk
