### ISSUE TITLE
Cloud Anchor host fails `ERROR_HOSTING_DATASET_PROCESSING_FAILED`

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#719]
Hi,
I'm recently encountering an issue that didn't exist before.
When trying to host a cloud anchor, the first hosting process fails with CloudAnchorState `ERROR_HOSTING_DATASET_PROCESSING_FAILED`. 
The following host requests, within the same `Session`, work as expected.

I first encountered this issue several days ago, and it repredoced multiple times.
Using `com.google.ar.sceneform.ux:sceneform-ux:1.6.0`, can't use 1.7.0 becuase of [this issue](https://github.com/google-ar/sceneform-android-sdk/issues/531).

Thanks!

**Comment by fredsa** [comment]
Seeing `ERROR_HOSTING_DATASET_PROCESSING_FAILED` is possible.

When this happens in your app, please retry (using [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff)).

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
