### ISSUE TITLE
Samsung Galaxy Tab S4: Jittering and unstable tracking

### ISSUE THREAD

**Issue by luruke** [google-ar/arcore-android-sdk#720]
### SPECIFIC ISSUE ENCOUNTERED
After experiencing problems using unity sdk, I thought to test directly the official sample in Java and I was able to replicate the same issue.

See screencast: https://photos.app.goo.gl/7pVQyXiVVjxV9n1r7

(See also https://github.com/google-ar/arcore-unity-sdk/issues/512)

### VERSIONS USED
- Android Studio: `3.2.1`
- ARCore SDK for Android: `v1.7.0`
- Device manufacturer, model, and O/S: `Samsung galaxy tab s4 (t830) – android 8.1.0`
- ARCore: `versionName=1.7.190128066`
- Output of `adb shell getprop ro.build.fingerprint`: 
`samsung/gts4lwifixx/gts4lwifi:8.1.0/M1AJQ/T830XXU2ARK4:user/release-keys`

### STEPS TO REPRODUCE THE ISSUE
 1. Build and run official sample `augmented_image_java` on the samsung tab s4
 2. Notice jittering and unstable tracking

**Comment by luruke** [comment]
Just for info, the device is listed as "Supported device" – https://developers.google.com/ar/discover/supported-devices

Is that the expected behaviour of ARCore?

**Comment by richard3575** [comment]
hi @luruke Are you noticing any jittering issues and instability on surface tracking? Ie dropping an object on the floor instead of an image marker? We have experienced some similar issues with the Samsung S3 tab, it takes a long time to map the surfaces, and when it does it’s unstable (this is compared to other devices that detect quicker and maintain stability).
For more details on these issues check you #701

**Comment by luruke** [comment]
Yes @richard3575 , also surface detecting acts very weird and it's totally unstable.

**Comment by luruke** [comment]
So apparently, after run different tests with similar devices, It looks that the S4 Tab in my posses has some hardware issue (maybe due a mis-calibration of the sensors?).

Waiting a new devices to be able to confirm this.

**Comment by fredsa** [comment]
Thanks, @luruke. Let us know if you encounter similar issues on other devices. If not, I think we can probably assume that the device was bad (manufacturing defect, bad component, etc.)

**Comment by luruke** [comment]
Hello @fredsa , today I received the replace of the device.
Definitely the experience is much more stable and consistent, so I'll close the issue.
