### ISSUE TITLE
Camera pose inAccuracy on Android 

### ISSUE THREAD

**Issue by funkymonk161994** [google-ar/arcore-android-sdk#722]
### VERSIONS USED
- Android Studio: 3.3.1
- ARCore SDK for Android: Not sure if it's the same but, "com.google.ar.sceneform.ux:sceneform-ux:1.6.0"
- Device manufacturer, model, and O/S: Google Pixel 3 XL , Android Version 9
- ARCore: Packages:
    versionName=1.7.190128066
Hidden system packages:
    versionName=0

- Output of `adb shell getprop ro.build.fingerprint`: google/crosshatch/crosshatch:9/PQ2A.190205.001/5163636:user/release-keys

This was done by placing certain objects at three different places using camera pose (API Call: camera.getPose()) on press of a physical button (volume key) and was tested over multiple times to check for consistency.

### STEPS TO REPRODUCE THE ISSUE
1. Place three anchors at three different physical location using Camera Pose, 
2. Measure distances between anchors and log the distances as well camera pose for each of the point
3. Reset the session by starting the app

When done over multiple times, it was found that the distance measured between the three points changed by +-7cm to +-40cm in some cases. I understand the limitation of ARCore and this would be fine if the error was within +- 5 cm. 

But I would like to know if it is a bug that I am seeing or if it can be improved by any means.

### WORKAROUNDS (IF ANY)
I have tried various workarounds, e.g. checking point cloud density and also checking if origin of each frame captured at the three physical point shifted or not. It seems that mapping done by ARCore to record physical displacement of device in relation to camera pose is sometimes not accurate.

### ADDITIONAL COMMENTS
I found that Camera Pose is used because it is most stable (this issue was observed 3-4 out of 50-60 repetitions) if user input (touch on the screen) is not required instead of doing a Hit test.

I am more than happy to share my results as I tried to log and observe if I could potentially catch a pattern to correct this.

**Comment by fredsa** [comment]
We recommend attaching virtual objections to anchors on trackables (planes, Augmented Images). The goal is have those objects feel and appear attached to world.

**Comment by fxvn78** [comment]
I am using Arcore v1.14 and see the same issue even with an Anchor in place. My repro is even easier. Simply record the camera pose in the UI, move the device around and return it to the same place the camera pose was  captured. If using an anchor, create the anchor at the pose (use an image to to render it so you can see), move the device around, then move the device to fit on the virual image.

In both cases, the devices mostly shows the same pose but it seems that if there is a different plane (only known cause I am using ARcore to render the planes) captured during the movement, the coordinates can be way off. Mostly is it close but every once so often it is way off.

Any suggestions on how to report this or find a work around is appreciated.
