### ISSUE TITLE
AR_ERROR_NOT_TRACKING: Cannot create anchors while the camera is not tracking.

### ISSUE THREAD

**Issue by joecaraccio** [google-ar/arcore-android-sdk#725]
When leaving the ARFragment, and attemping to then resume it.. I guess this issue:

`AR_ERROR_NOT_TRACKING: Cannot create anchors while the camera is not tracking.`

at first I was getting issues about the scene being paused, I was able to get past that error by calling:

`            arFragment.getArSceneView().getSession().resume();
`

However, the camera is not in tracking state apparently. Is there a way to restart that process? I did quite a bit of looking through the docs but couldn't find any sort of method to properly resume camera tracking

**Comment by devbridie** [comment]
In case this comes up again, [`Camera.getTrackingFailureReason()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getTrackingFailureReason()) will state why the tracking has been paused.
