### ISSUE TITLE
Incompatibility between ARCore 1.0 / last ARCore app / Android 9

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#727]
### SPECIFIC ISSUE ENCOUNTERED

Bad ratings on devices running Android 9 since a few weeks (would say beginning february). My app is (still) compiled with ARCore 1.0.

### VERSIONS USED
- Android Studio: N/A
- ARCore SDK for Android: 1.0
- Device manufacturer, model, and O/S: Android 9.0

### STEPS TO REPRODUCE THE ISSUE
I don't know what is the exact problem as the users using Android 9 just give a bad rating without leaving a comment. Until end of January, I had good ratings on Android 9. Since beginning February (and even more since February 12th), the ratings on Android 9 seem to decrease drastically.

### WORKAROUNDS (IF ANY)

Do you think that my problem is due to an incompatibility between:
- Android 9
- last version of ARCore app on Google Play
- my app compiled against ARCore 1.0

Thanks.

**Comment by fredsa** [comment]
Could you please provide more detail? It's not possible for us to reproduce your issue without more information.

**Comment by agGitHub** [comment]
Hi. I don't know what is the exact issue. All what I see is that the cumulated average rating of my app seems to accelerate its decrease at each release of the Google Play ARCore app.

I see especially:
- on Dec 3-4th : a drop and the beginning of a long decrease of the cumulated average rating for the users using my app with Android 8.1 (this cumulated average rating increased before this update)
- from Feb 12th: increase of the decrease of my cumulated average rating for the users using Android 9

I don't know how to explain this. The app becomes less accurate? Less reliable?

Regards.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
