### ISSUE TITLE
Inconsistent notes for Xiaomi devices on the Supported Devices page

### ISSUE THREAD

**Issue by egedib** [google-ar/arcore-android-sdk#729]
As of March 3, 2019, the [official Supported Devices](https://developers.google.com/ar/discover/supported-devices) page does not have the _No support for CPU image access._ note for Xiaomi Mi Mix2S, Mi Mix 3 and Pocophone F1, Google Play variants, but the China variants have. Is this a typo or is CPU Image Access getting fixed?

Just for curiosity: what could be _missing_ in Xiaomi devices? Other phones with Snapdragon 845 currently supports the feature.

**Comment by fredsa** [comment]
Apologies for the confusing formatting of the HTML table on that page. The "No support for CPU image access" restriction currently applies to all Xioami devices listed.

We hope to remove this restriction in a future version of ARCore.

**Comment by fredsa** [comment]
I'm going to close this issue. Hope to have the supported devices page updated shortly.

**Comment by fredsa** [comment]
Fixed in ARCore SDK 1.8.0
