### ISSUE TITLE
ArAugmentedFace arcore_c_api

### ISSUE THREAD

**Issue by yeguangrong** [google-ar/arcore-android-sdk#730]
Is the latest version c_api surport the AugmentedFace?  I have try to use ArSession_createWithFeatures interface to obtain AugmentedFace data, and the detected faceCount if correct，bug when I use "ArAugmentedFace_getCenterPose" this inteface to get ArPose data, your SDK always return the following error log info "E/native: session_c_api.cc:2009 ArAugmentedFace_getCenterPose: out_pose was passed NULL."

**Comment by yeguangrong** [comment]
oh！I have fix this problem!

**Comment by fredsa** [comment]
Great news
