### ISSUE TITLE
Is it possible to get documentation in Android Studio ?

### ISSUE THREAD

**Issue by ManuelTS** [google-ar/arcore-android-sdk#733]
Coming from the [Sceneform issue #348](https://github.com/google-ar/sceneform-android-sdk/issues/348) started in October of 2018, the javadoc documentation of ARCore inside Android Studio would be fruitful.

Why is the documentation as .zip for Android Studio not downloadable when the documentation is online? In my humble opinion, the .zip should be downloadable since the first release of ARCore. I mean, how do you ARCore guys read the documentation? Also online for more traffic and click generation? Or did I miss the ARCore documentation .zip file download for Android Studio somewhere?

**Comment by maximrahlis** [comment]
Any update on this? Really inconvenient to work without documentation in the IDE..

**Comment by ManuelTS** [comment]
Not from my site, unfortunately.

**Comment by ManuelTS** [comment]
Eight months later, still no update.

**Comment by devbridie** [comment]
Can't give any promises here, but this is definitely on the radar and needs some work on technical and legal aspects. Will keep the thread updated.

**Comment by devbridie** [comment]
This has been released in 1.27.
![image](https://user-images.githubusercontent.com/442644/135846035-caed66c7-0406-4d87-8017-23ad71dc5f41.png)
