### ISSUE TITLE
arcore-prevew.apk doesn't work in a multi-user environment

### ISSUE THREAD

**Issue by ktaka** [google-ar/arcore-android-sdk#74]
arcore-preview.apk (i.e. Tango Core) doesn't work in a multi-user environment. It crashes every time.
With using Pixel, I've found an error message in logcat below.

`Abort message: 'tango_application.cc:237 Check failed: generic::DirectoryExists(config_.config_files_directory) Given path for config files /data/data/com.google.tango/files/config/ does not exist.'`

You know, the pass will be changed under a multi-user environment like `/data/user/{ID}`.

**Comment by nathanmartz** [comment]
Thanks for the bug report. We're looking into it!

**Comment by inio** [comment]
This should be fixed with Developer Preview 2.  Please let us know if it isn't!

**Comment by ktaka** [comment]
Thanks.
It works fine!
