### ISSUE TITLE
frame.acquirecameraimage throws exception

### ISSUE THREAD

**Issue by yoavmiron** [google-ar/arcore-android-sdk#741]
### SPECIFIC ISSUE ENCOUNTERED
frame.acquireCameraImage was working just fine, until I integrated openCV library into the app 
(built around the helloAR app), in order to run some CV operations on images. Before I even used any openCV functionality, frame.acquireCameraImage stopped working altogether, and started throwing NotYetAvailableException. I guess maybe adding openCV made the slower somehow and caused this(?). Is there a way to work around that issue, or maybe an alternative to openCV that won't cause this?

### VERSIONS USED
- Android Studio: 3.2.1
- ARCore SDK for Android: couldn't find which
- Device manufacturer, model, and O/S: Huawei p20 lite running Oreo 8.1, Samsung Galaxy S7 running Oreo 8.0
- ARCore: 1.7.0
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: adb wasn't recognized...

### STEPS TO REPRODUCE THE ISSUE
 1. Integrate the OpenCv library into the helloAR example
 1. Try to use frame.acquirecameraimage

**Comment by fredsa** [comment]
Have you looked at the two (C/Java) computer vision samples?
https://github.com/google-ar/arcore-android-sdk/tree/master/samples

Not sure if it's useful, but you can configure blocking mode
https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/Config.UpdateMode
