### ISSUE TITLE
Samsung A30 support?

### ISSUE THREAD

**Issue by Sathish-n** [google-ar/arcore-android-sdk#742]
Samsung have launched a wide range of mid-range devices this month. The M series - M10, M20, M30 and the A series - A10, A30, A50. I currently have an A30. Will it support arcore as old models like Samsung A7 are being supported?

**Comment by mr-gil** [comment]
What about galaxy s10 ? . and the xiaomi mi9?

**Comment by ramuchilla** [comment]
No, Samsung M series not supporting ARCore

**Comment by Udayraj123** [comment]
This list should is last updated in April, doesn't have the M series yet
https://developers.google.com/ar/discover/supported-devices

**Comment by riktimmondal** [comment]
Will there be any support for samsung M30 in future?

**Comment by rickyayri** [comment]
Hey, there is someone that knows if will there be any support for Samsung A10 in the future?

**Comment by sandyfriend** [comment]
A30 supported.

**Comment by Sanscripter** [comment]
What about A30S?
