### ISSUE TITLE
Complete point cloud in ARCore

### ISSUE THREAD

**Issue by RicardoLuna** [google-ar/arcore-android-sdk#743]
For every frame, the ARCore returns a new point cloud using the function **Frame.acquirePointCloud()** but this is a "partial" point cloud and It's not "global" or complete. Sometimes this point cloud is refined and I need that result. I am trying to save all the points in the current state for 3D reconstruction however I need the entire point cloud, for that, I update it if a new point cloud is added. Does there exist another way to return the "complete"(It contains all points in current time) point cloud?

**Comment by devbridie** [comment]
Sorry for having left this one unanswered for so long-- no such thing currently exists in ARCore. Instead, you could build up your own "global" point cloud by saving partial data from PointCloud using [`getIds()`](https://developers.google.com/ar/reference/java/com/google/ar/core/PointCloud#getIds()) as a stable anchor.
