### ISSUE TITLE
Shared camera access with Sceneform

### ISSUE THREAD

**Issue by Thilo1992** [google-ar/arcore-android-sdk#744]
Hello,
is it possible to use the shared camera access from ARCore in combination with Sceneform (ArFragment or ArSceneView)? My own approaches didn´t work. Has someone tried it?

**Comment by IvanFiveHundredFourteen** [comment]
@Thilo1992 have you found a solution?
i am trying to do the same, no luck

**Comment by Thilo1992** [comment]
No, i think it isn´t possible.

**Comment by Mehequanna** [comment]
I was trying to do this as well. I was following the SharedCamera how to here in the Android Docs: https://developers.google.com/ar/develop/java/camera-sharing
I was getting an error about methods not being implemented. What were the issues you two ( @Thilo1992 @IvanFiveHundredFourteen ) saw preventing shared camera access?

**Comment by lancefi** [comment]
Anyone have any more information about this?

**Comment by SunitRoy2703** [comment]
I'm trying tonight let's what happens

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale. If this is still an issue, you can use the newly [open-sourced Sceneform SDK sources](https://github.com/google-ar/sceneform-android-sdk/tree/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform) to try to diagnose the problem, or find a community-reared fork in which the issue has been addressed.
