### ISSUE TITLE
Render Object at specific area

### ISSUE THREAD

**Issue by Aniketrajput039** [google-ar/arcore-android-sdk#749]
I want to know that can we place object without detecting plane means that instead of using plane can we take particular area or rectangle from user and try to render object at that place.
Is it possible.?
Thank you.
 @fredsa 
@

**Comment by VidhiLatitude** [comment]
How can I put 3D object on onTouchevent and setScale for see far object ?

**Comment by fredsa** [comment]
We recommend that you always place objects attached to an anchor, so ARCore is able to maintain the object's position relative to the world.

It is possible to place an object that is not attached to anything (there's an API for that you can find in the reference docs), but it is not recommended.
