### ISSUE TITLE
Scale Models when detecting an image and overlaying the model

### ISSUE THREAD

**Issue by knightcube** [google-ar/arcore-android-sdk#756]
### SPECIFIC ISSUE ENCOUNTERED
I am using Augmented Images to overlay a 3d model on top of a poster. After placing it on the poster I want to scale the size of it according to my needs. I tried using TransformableNode like so 
```
private void placeModel(ModelRenderable modelRenderable, Anchor anchor) {
        AnchorNode anchorNode = new AnchorNode(anchor);
        TransformableNode transformableNode = new TransformableNode(arFragment.getTransformationSystem());
        transformableNode.setParent(anchorNode);
        transformableNode.setRenderable(modelRenderable);
        transformableNode.select();
//        anchorNode.setRenderable(modelRenderable);
        arFragment.getArSceneView().getScene().addChild(anchorNode);

    }
```
However after getting projected on the poster the model drifts away probably because it cannot detect a plane to stay fixed to. Is it possible to scale the model in runtime using pinch to zoom in and zoom out gesture?  

### VERSIONS USED
- Android Studio: `3.2.1`
- ARCore SDK for Android: `1.8.0`
- Device manufacturer, model, and O/S: `Nokia, 7 plus, Android`
- ARCore: `1.8.190311076`
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: `Nokia/Onyx_00WW/B2N_sprout:9/PPR1.180610.011/00WW_3_51F:user/release-keys`

**Comment by fredsa** [comment]
For Sceneform issues, use https://github.com/google-ar/sceneform-android-sdk
