### ISSUE TITLE
audio capability

### ISSUE THREAD

**Issue by t-simeongordon** [google-ar/arcore-android-sdk#759]
Hi i've been looking through this repo for Voice Commands with Amazon Lex.

ive set up lex with sumerian for vr which works perfectly fine but when i look into arcore this doesnt seem transferable.

is there a way to pass voice commands/audio recordings so that lex can pick this up through sumerian on the app you've created. 

thanks :)

**Comment by fredsa** [comment]
I think you are looking for a different issue tracker.
