### ISSUE TITLE
Feature request: equivalent to iOS Quicklook

### ISSUE THREAD

**Issue by eugenelozada** [google-ar/arcore-android-sdk#760]
Is this something planned or in the works?   Thinking of perhaps a standard AR scene viewer app built in to the ARCore APK that can be triggered by firing off a specific intent or as a registered viewer for specific file types (.gltf, fbx etc.).  This scene viewer can implement best practice user interactions, light and environment probes etc. 

Something like this would contribute considerably to getting AR.    We already use it to great effect in iOS/Safari and is a low barrier to entry to get clients (and their customers) to try out AR.

**Comment by streamgao** [comment]
+1 same question. or any plan to support usdz in ARCore?

**Comment by eugenelozada** [comment]
Ok so I just watched the 'Whats New in ARCore' session

https://youtu.be/e0B28zBn9JE?t=4785 

Tt seems that this feature is going to be supported by Scene Viewer / Model View in 1.9.  The ARCore site was also updated https://developers.google.com/ar/develop/java/scene-viewer .  In the site it mentions how to trigger it from a web site, is it also possible to trigger this from an native app by firing some kind of intent?

**Comment by makc** [comment]
> https://youtu.be/e0B28zBn9JE?t=4785

says the video is not available (

**Comment by fredsa** [comment]
Here's the published video for the What's New in ARCore session:
https://www.youtube.com/watch?v=pdRpCJ5acrA

Scene Viewer documentation can be found here:
https://developers.google.com/ar/develop/java/scene-viewer

**Comment by olancedev** [comment]
> Ok so I just watched the 'Whats New in ARCore' session:
> 
> https://youtu.be/e0B28zBn9JE?t=4785
> 
> Tt seems that this feature is going to be supported by Scene Viewer / Model View in 1.9. The ARCore site was also updated:
> 
> https://developers.google.com/ar/develop/java/scene-viewer .
> 
> In the site it mentions how to trigger it from a web site, is it also possible to trigger this from a native app by firing some kind of intent?

Yes, It is posibile, do this code in android
`Intent sceneViewerIntent = new Intent(Intent.ACTION_VIEW);
sceneViewerIntent.setData(Uri.parse("https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF/Avocado.gltf"));
sceneViewerIntent.setPackage("com.google.android.googlequicksearchbox");
startActivity(sceneViewerIntent);`
