### ISSUE TITLE
AR Core not supported on Moto G6

### ISSUE THREAD

**Issue by pikachupotter** [google-ar/arcore-android-sdk#765]
I've seen on the ARcore website that it is supported on the moto G6, however when I go to search it in google play store it doesn't appear. I find it through searching on previously downloaded and it is telling me this version isn't supported on my device. 

Considering I have a moto G 6 that is updated to the latest andriod update I do not get why it cannot function with the latest version...

**Comment by ARGs-code** [comment]
ARCore is supported on the MotoG6, I use one of them along with other phones for testing. Try searching for ARCore by Google on the play store. I just uninstalled and reinstalled it from the play store, it should be working just fine.. Screenshot below taken today from my MotoG6

![Screenshot_20190417-110455](https://user-images.githubusercontent.com/15038504/56298937-0c41a100-6101-11e9-8518-a335004055de.png)

**Comment by pikachupotter** [comment]
@ARGs-code 

From the files I hope have. Attached it should show that a. searching for ARcore yields no results for the app and b. when I find it through previously installed apps on another phone it tells me this version is not supported on my device. 
![Screenshot_20190417-161612](https://user-images.githubusercontent.com/49661962/56299918-e03c1500-612c-11e9-9f58-216c08c87d67.png)
![Screenshot_20190417-161635](https://user-images.githubusercontent.com/49661962/56300031-15486780-612d-11e9-85d2-b800074c46c1.png)

**Comment by ARGs-code** [comment]
Very odd. I'm not sure what the issue is then, sorry. It definitely works for my MotoG6 though & it's currently Running Android Version: 8.0.0

**Comment by pikachupotter** [comment]
@ARGs-code I have just found out why it wasn't working, I have the Moto G 6 play, which isn't under the supported devices. Silly night shift brain wasn't picking up all the details aha. Thanks for your help though!
