### ISSUE TITLE
Feature request: Setting the ARCamera's far and near clipping planes

### ISSUE THREAD

**Issue by valnenov** [google-ar/arcore-android-sdk#766]
I am using ARcore to render objects in a large field - an actual 30x60m hockey rink. Unfortunately my objects get clipped at a distance of about 10-15 meters from the rear camera. I am looking for a way to programmatically set the far and near clipping planes. My research has revealed that several developers are facing the same issue but no one has come up with a solution. I have posted my question on several user groups with no luck. 

Please, advice if I have missed some obvious solution. If not, I would like to respectfully request the addition of such feature in the upcoming releases of ARcore. I am currently using version 1.8 with Android Studio and a Huawei Mate 20 Lite phone. Thanks. 

Here FYI is the same issue faced by another developer and their observations. 
https://stackoverflow.com/questions/54926644/arcore-rendering-objects-200m-far-from-camera

And some of my posts:
https://arcore.slack.com/messages/C2UH7EF7Y/convo/C2UH7EF7Y-1553055399.048400/
https://medium.com/@val_56035/hi-yuliya-i-came-across-your-article-while-searching-for-ways-to-set-the-far-clip-plane-in-the-dda96748abf6?source=responses---------0-30--------------------

**Comment by guerwan** [comment]
@valnenov Using Sceneform, you can set the far clip plane like this: arFragment.getArSceneView().getScene().getCamera().setFarClipPlane(…);

**Comment by fredsa** [comment]
Let's track this in the Sceneform issue tracker:
https://github.com/google-ar/sceneform-android-sdk/issues/679

**Comment by valnenov** [comment]
Thank you Stéphane Guérin,

Tried it and it worked. Much appreciated.

Val
