### ISSUE TITLE
Samsung Galaxy J5 and J7 supported, but not J6

### ISSUE THREAD

**Issue by alexbertis** [google-ar/arcore-android-sdk#768]
### SPECIFIC ISSUE ENCOUNTERED
ARCore is supported for lower-end Samsung devices such as J5 (2017) and J7 (2017), but there's no support for the Galaxy J6 (2018), which carries esentially the same SoC as the first one.

### VERSIONS USED
- Android Studio: 3.4
- ARCore SDK for Android: 1.8
- Device manufacturer, model, and O/S: 
- ARCore: 
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by jeveloper** [comment]
"Same Soc" doesn't automatically qualify google ar team to add support. I have a PH-1 phone that is very similar to Pixel and has a stock android OS and no idea when Google will add ARCore support.

**Comment by devbridie** [comment]
No news on the J6 at the time, but we're tracking supported devices requests in #89.
