### ISSUE TITLE
HORIZONTAL_DOWNWARD_FACING planes tracking issue

### ISSUE THREAD

**Issue by parkerschnepf** [google-ar/arcore-android-sdk#77]
Planes detected on the ceiling (downward facing) always have an extent of 0, no matter how large they appear to be when drawn using the PlaneRenderer example code (and they do appear to draw correctly). This seems to prevent hit testing against downward facing planes. All upward facing planes I've tested always have positive numbers for the extents and can be successfully hit tested.

**Comment by avirodov** [comment]
This is now fixed in developer preview 2 release.

**Comment by aussieburger** [comment]
Did anyone get this working in P2? I'm testing with the Unreal integration and it does not appear to be working at all (ceiling detection)
