### ISSUE TITLE
Verify if ARCore is compatible and  if it is installed without internet conexion

### ISSUE THREAD

**Issue by mr-gil** [google-ar/arcore-android-sdk#771]
The app that I am developing, have blocked access to internet , only  have access to specific IP's in the local host.

The problem is that I cant validate if ARCore is compatible, because to check this validation is necesary internet, and is the same to check if the user have installed ArCore. 

I have a specific URL to provide the APK to the user, but, since the native validation dont provide a method without internet conexion to check if the apk is installed, updated, or compatible, this is nod a good approach.

Are you planning to do a update?

**Comment by fredsa** [comment]
Duplicate #772
