### ISSUE TITLE
Wich url used ArCore to validate compatibility?

### ISSUE THREAD

**Issue by mr-gil** [google-ar/arcore-android-sdk#772]
Wich url used ArCore to validate compatibility?

I want to grant access only to specific urls, because the connectivity of the user is restricted, but I cant find the url that ArCore uses to check the compaibility, according the documentation :

> Note, checkAvailability() may need to query network resources to determine whether the device supports ARCore. During this time, it will return UNKNOWN_CHECKING. To reduce the perceived latency and pop-in, apps should call checkAvailability() once early in it's life cycle to initiate the query, ignoring the returned value. This way a cached result will be available immediately when maybeEnableArButton() is called

**Comment by fredsa** [comment]
The check is basically handled by the Google Play Store app. If the [ARCore](https://play.google.com/store/apps/details?id=com.google.ar.core) app is already installed and up to date, then no network connection is needed. If the app is not installed, or out of date, then a network connection is required to install or update the app. Note that "up to date" here means that the version of ARCore that is installed on the device needs to be the same as or newer than the SDK version that was used to build the app.
