### ISSUE TITLE
Arcore emulator in Ubuntu

### ISSUE THREAD

**Issue by ajaykmr2292** [google-ar/arcore-android-sdk#776]
### SPECIFIC ISSUE ENCOUNTERED
I can start the AR emulator in Ubuntu-16.04 using the instructions mentioned [here](https://developers.google.com/ar/develop/java/emulator). The emulator starts and it shows `Press Alt to move camera`  when the `Hello sceneform` app starts. But when I press `Alt` (along with QAWSED keys), the camera does not move. I think this issue is only with Ubuntu (Alt works perfectly fine on Windows).

Maybe the issue is because of the special key status for `ALT` in Ubuntu. Please tell me how to fix this issue.

I think one way is to change the keyboard shortcut for VIRTUAL CAMERA CONTROL from `ALT` to something else in emulator. Other way is to remove the special key status for `ALT` in Ubuntu.

Please tell me a solution for any of the two methods or any other method which solves the issue.

### VERSIONS USED
- Ubuntu - 16.04.6
- Android Studio: 3.4
- Device manufacturer, model, and O/S: Emulator

**Comment by AndroidLibrariesYoutube** [comment]
I have also faced the same problem while using ubuntu 16.04.

**Comment by esh-b** [comment]
@AndroidLibrariesYoutube any solution?

**Comment by fredsa** [comment]
Thank you for reporting this. Would you mind filing an issue with the Android Studio team?

https://developer.android.com/studio/report-bugs
