### ISSUE TITLE
Figuring out if Anchor is visible in current screen

### ISSUE THREAD

**Issue by TheMachineHere** [google-ar/arcore-android-sdk#78]
I allowing users to place anchors. 

I need to be able to:
        1) Check if the Anchor is in the current screen. (ie, if you place an anchor, go around 360 
                        degrees, comeback, there would be a flag that would be true)
        2) Check the 2D Screen location (x,y) of where the anchor is. (ie, convert 3D world coordinate 
                        into 2D screen coordinate)

How can I do this?

**Comment by inio** [comment]
This is mostly outside the scope of ARCore itself, and is more of a general 3D graphics question.  Each frame ARCore can give you the [anchor's location](https://developers.google.com/ar/reference/java/com/google/ar/core/Anchor.html#getPose\(\)) and the camera's [projection](https://developers.google.com/ar/reference/java/com/google/ar/core/Camera.html#getProjectionMatrix\(float[],%20int,%20float,%20float\)) and [view](https://developers.google.com/ar/reference/java/com/google/ar/core/Camera.html#getViewMatrix\(float[],%20int\)) matrices, but beyond that it's really just a graphics question.

Stackoverflow might be a better venue for this sort of question.  For example:

https://stackoverflow.com/questions/2407363/how-do-you-determine-when-an-object-is-drawn-on-screen-in-opengl
