### ISSUE TITLE
How to use ARCore's calibration data

### ISSUE THREAD

**Issue by Space4ARDev** [google-ar/arcore-android-sdk#784]
Does anyone knows how to use ARCore's calibration data?
Especially gyro, accel scale and misalignment.
Thanks.

**Comment by fredsa** [comment]
Sorry, currently there's no support for doing so.

**Comment by Space4ARDev** [comment]
Hello fresda, could you please explain me what is misalignment value x,y,z in the arcore calibration data?
Thanks.
