### ISSUE TITLE
I am integrating ARcore sceneform in my Android Native Project . I am facing below issue while opening camera. It happens some times only . I am not able to find the exact issue .

### ISSUE THREAD

**Issue by suryanadiminti99** [google-ar/arcore-android-sdk#785]
E/third_party/arcore/ar/sceneform/android/jni/arsceneview_jni.cc: nativeReportEngineType: Couldn't get session's nativeHandle 2019-05-15 19:30:28.411 22577-22577/com.innovare.plugxr

E/NdkImageReader: AImageReader_getWindow 2019-05-15 19:30:28.600 22577-22577/com.innovare.plugxr

E/native: session.cc:1527 Invalid ray produced by view data! 2019-05-15 19:30:28.850 22577-22577/com.innovare.plugxr

A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0x728e1b48 in tid 22577

**Comment by fredsa** [comment]
For Sceneform issues, please use https://github.com/google-ar/sceneform-android-sdk

When filing an issue please provide the requested information listed in the issue template.

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`:

**Comment by drummor** [comment]
Packages:
    versionName=1.9.190422056
Hidden system packages:
    versionName=0
