### ISSUE TITLE
Coordinate Mapping

### ISSUE THREAD

**Issue by TFreudi1** [google-ar/arcore-android-sdk#79]
Is there a relation between the world coordinate system of ARCore to real distances (meters) ?
So for example that a point 0,0,1 is 1 meter in front of me?

The Problem behind ... I have my Position and the Position of othe rthings in a metrical coordinatesystem and want to place it.

**Comment by robertjuh** [comment]
As far as i know, iPhone can do this quite accurately. But they might be having specialised hardware. I'm planning to figure this out as well as im working on something where a metric understanding of the world is also important.

**Comment by TFreudi1** [comment]
Ahh Ok I will have a look in that
https://github.com/ProjectDent/ARKit-CoreLocation
Maybe I get some ideas from that.

**Comment by inio** [comment]
Units in ARCore C and Java apis are meters (Unity as well I think, Unreal is probably cm).
