### ISSUE TITLE
What is the default near and far clipping distance ARCore uses ?

### ISSUE THREAD

**Issue by aj019** [google-ar/arcore-android-sdk#790]
### SPECIFIC ISSUE ENCOUNTERED
Projection Matrix not changing even on changing far and near clipping distance. That means there are default values that are being used internally and i would like to know that.

### VERSIONS USED
- Android Studio:  3.1.1
- ARCore SDK for Android: 1.4.0
- Device manufacturer, model, and O/S: One plus 6

### STEPS TO REPRODUCE THE ISSUE
 1. In the getProjectionMatrix modify the near and far parameter, it will stilll give the same projection matrix

### WORKAROUNDS (IF ANY)
Trying to figure out still

**Comment by devbridie** [comment]
For anybody happening upon this via a search engine, I used the following fragment to confirm that the near and far clipping values do affect the projection matrix:

```
for (float near = 0.1f, far = 100.0f; near < 50f && far > 50f; near += 1f, far -= 1f) {
  camera.getProjectionMatrix(projectionMatrix, 0, near, far);
  StringBuilder sb = new StringBuilder();
  for (float value : projectionMatrix) {
    sb.append(value);
    sb.append(", ");
  }
  Log.i("TEST", "New projection matrix values "  + sb.toString());
}
```

If you're still having issues, please feel to open up a new bug. Closing this one due to age.
