### ISSUE TITLE
Mi 9 / 9 SE Support

### ISSUE THREAD

**Issue by Andreybest** [google-ar/arcore-android-sdk#791]
Will Mi 9 and Mi 9 SE soonly get ARCore support? It's been awhile since the release of this phones.

**Comment by denisk20** [comment]
Mi 9 seems to be supported, but what about SE?

**Comment by Andreybest** [comment]
> 
> 
> Mi 9 seems to be supported, but what about SE?

Latest apk is not working on Mi 9 SE

**Comment by toXel** [comment]
Version 1.11.0 is now working on my Mi 9 SE!

**Comment by S-o-T** [comment]
> Version 1.11.0 is now working on my Mi 9 SE!

Same for me.

**Comment by Andreybest** [comment]
Yep, works for me too. Thank you!
