### ISSUE TITLE
ARCore issue with Pixel 2

### ISSUE THREAD

**Issue by sidmahajan** [google-ar/arcore-android-sdk#794]
I am creating a basic app with just the **AR Core Device** prefab. The app crashes on opening. When i uninstall ARCore by Google and reinstall it the App will start for the first time. But then if i try to open the app again it will show a blank screen and go to the home screen. 

AR Core SDK - 1.9.0
Unity -  2018.3.12f1
Phone - Pixel 2 
Android - 9
adb shell getprop ro.build.fingerprint :
**google/walleye/walleye:9/PQ3A.190505.001/5373320:user/release-keys**

Logs Attached:
[PointPlane.txt](https://github.com/google-ar/arcore-android-sdk/files/3221081/PointPlane.txt)

**Comment by cvetelinast** [comment]
Looks like this issue:
https://github.com/google-ar/arcore-android-sdk/issues/789

**Comment by sidmahajan** [comment]
Issue has been resolved
