### ISSUE TITLE
Can i place my own anchor for ARCore 2.0

### ISSUE THREAD

**Issue by Wangxuefeng92** [google-ar/arcore-android-sdk#795]
Can i place my own anchor for ARCore 2.0

**Comment by liho00** [comment]
ARCore 2.0 has not been released yet.
https://github.com/google-ar/arcore-android-sdk/releases

What do you mean own anchor? Can you describe precisely?

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
