### ISSUE TITLE
Transparency / Cutout doesn't work in SceneViewer / AR preview / AR view for GLB file

### ISSUE THREAD

**Issue by hybridherbst** [google-ar/arcore-android-sdk#796]
### SPECIFIC ISSUE ENCOUNTERED

Objects with transparency and cutout materials show up without transparency in AR SceneViewer, replacing all transparent parts with black.

I originally posted that issue [in the GoogleWebComponents/model-viewer repo](https://github.com/GoogleWebComponents/model-viewer/issues/577), but I think it's actually an ARCore issue since it renders correctly in model-viewer.

![image](https://user-images.githubusercontent.com/2693840/58514506-750d4600-81a2-11e9-99c3-578876d8a98f.png)
_That's how it's supposed to look_

![image](https://user-images.githubusercontent.com/2693840/58514523-7e96ae00-81a2-11e9-99a2-ee10ccb19deb.png)
_That's the result in ARCore Preview_

### VERSIONS USED
- ARCore APK: 1.9.1
- Device manufacturer, model, and O/S: Samsung Galaxy S7, Xiaomi Mi 9, Honor 7X

### STEPS TO REPRODUCE THE ISSUE
 1. Visit https://cobalt-gondola.glitch.me/ on a Android device with ARCore installed.
 1. Scroll down to the last embedded model. Note that it has circles and triangles (which are actually quads with cutout / transparency).
 1. Click on the "AR Preview" icon in the bottom right. Note that now everything has black areas where it formerly was transparent.
 1. Click on AR. Note that the issue persists.

### WORKAROUNDS (IF ANY)
None

### ADDITIONAL COMMENTS
You can download the glb file from glitch if needed for further testing.

**Comment by devbridie** [comment]
Seems to be solved in the current release-- please feel free to open a new issue if this is still a problem.
