### ISSUE TITLE
How to place 2d image and video on vertical as well  as horizontal plane of the target size

### ISSUE THREAD

**Issue by Anushree278** [google-ar/arcore-android-sdk#797]
Hi,

I am creating an app in which i have to show image or video and  after finding target,i have to get image from internal memory and to get the size of target image and show the mp4 video or image on the target image using ARcore in android

I have tried giving position to center and displayorientedpose and also get the size of augmentedimage.getextentX and passed it on vector position but it is not helping me for vertical plane as for horizontal it is working perfectly.

How to show image or video on the target image and of the size of target image.

Please help.

**Comment by shliama** [comment]
I did exactly that - check the sources https://proandroiddev.com/arcore-sceneform-simple-video-playback-3fe2f909bfbc
