### ISSUE TITLE
Sample build fail with NDK r20

### ISSUE THREAD

**Issue by psklf** [google-ar/arcore-android-sdk#804]
### SPECIFIC ISSUE ENCOUNTERED

When build hello_ar_c sample project, build fail.

```
  1 error generated.
  FAILED: Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=i686-none-linux-android24 --gcc-toolchain=Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -Dhello_ar_native_EXPORTS -I../../../../src/main/cpp -IAndroid/Sdk/ndk-bundle/sources/third_party/vulkan/src/libs/glm -isystem/Project/SampleCode/arcore-android-sdk/samples/hello_ar_c/../../libraries/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -Wall -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/hello_ar_native.dir/src/main/cpp/jni_interface.cc.o -MF CMakeFiles/hello_ar_native.dir/src/main/cpp/jni_interface.cc.o.d -o CMakeFiles/hello_ar_native.dir/src/main/cpp/jni_interface.cc.o -cSampleCode/arcore-android-sdk/samples/hello_ar_c/app/src/main/cpp/jni_interface.cc
  In file included fromSampleCode/arcore-android-sdk/samples/hello_ar_c/app/src/main/cpp/jni_interface.cc:21:
  In file included from ../../../../src/main/cpp/hello_ar_application.h:30:
  In file included from ../../../../src/main/cpp/background_renderer.h:26:
  In file included from ../../../../src/main/cpp/util.h:31:
  ../../../../src/main/cpp/glm.h:20:10: fatal error: 'glm.hpp' file not found
  #include "glm.hpp"
           ^~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

```

### VERSIONS USED
- Android Studio: Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 2, 2019
JRE: 1.8.0_152-release-1343-b16-5323222 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-21-generic

- ARCore SDK for Android: 1.9.0
- Device manufacturer, model, and O/S: N/A
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`N/A
- Output of `adb shell getprop ro.build.fingerprint`: N/A

### STEPS TO REPRODUCE THE ISSUE
 1. Build the hello_ar_c project
 1.
 1.

### WORKAROUNDS (IF ANY)

Use the NDK  of version 19c

### ADDITIONAL COMMENTS

Can't find the GLM in NDK directory (version 20)

**Comment by fredsa** [comment]
Thanks for reporting this issue. This issue is caused by the fact that NDK r20 stopped bundling `glm` as part of the Vulkan distribution.

Options if this issue is blocking you:
1. Workaround this issue by using NDK version 19c (as suggested above)
2. Wait for the fix for the inclusion of the `glm` library in an upcoming release of the ARCore SDK for Android
3. Patch the current release manually (requires some work):
   * Use the public `glm` from https://glm.g-truc.net/0.9.9/index.html
   * Update sample, including proper include paths and changes to `glm.hpp`
