### ISSUE TITLE
Resolving cloud anchors blocks UI thread

### ISSUE THREAD

**Issue by kostyabakay** [google-ar/arcore-android-sdk#807]
I saw the answer from @asadullahnaweed about cloud anchors resolving process limitations in #503. In my case, I need to host and resolve multiple anchors in real-time. I decided to implement a solution where app resolves anchors periodically in the background while the camera is working. Cloud Anchors API allows performing up to 300 resolve requests per minute. Unfortunately, I understood that method call `session.resolveCloudAnchor(anchorId)` blocks UI thread even when it works in the background thread. I suppose the reason is that Session instance works with UI thread inside. So when I want to resolve 10 anchors my camera freezes for a few seconds. I tested this on Google Pixel and Samsung Galaxy S7. Is there any way to implement real-time interaction between devices using Cloud Anchors API?

**Comment by asadullahnaweed** [comment]
Thanks for raising this. I'll investigate this and get back to you with an update soon.

**Comment by sergeyfitis** [comment]
@asadullahnaweed I have the same problem. When trying to work with multiple anchors in real-time. Initialization time is too long. Around 5-10 sec. Any solution for this?

**Comment by kostyabakay** [comment]
Hi @asadullahnaweed! I see that in v1.12.0 release you were improved Cloud Anchors. Was this issue fixed in the current release?

> resolveCloudAnchor() (Java) and ArSession_resolveAndAcquireNewCloudAnchor() (NDK) will no longer timeout or fail when the ARCore Cloud Anchor API service is unreachable, or the anchor cannot be immediately resolved. Instead, the API will continue to attempt to resolve the provided anchors until they are detached.

**Comment by vberezkin** [comment]
Looks fixed in 1.12.0

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.

**Comment by amirtha17** [comment]
> hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free
How to resolve multiple anchors in android?
