### ISSUE TITLE
Play Video using media player on Augumented image

### ISSUE THREAD

**Issue by AmanpreetYatin** [google-ar/arcore-android-sdk#808]
i want to play video on scaaned/augumented image node but my media player some time zoom and some time goes beyond the augumented image width ..please help me to resolve this issue..thanks

**Comment by shliama** [comment]
I did exactly that - check the sources https://proandroiddev.com/arcore-sceneform-simple-video-playback-3fe2f909bfbc

**Comment by amanpree** [comment]
thanks for reply

> I did exactly that - check the sources https://proandroiddev.com/arcore-sceneform-simple-video-playback-3fe2f909bfbc

thanks for the reply, I 'll check and get back to you if I am facing any problem.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.

**Comment by ThomasGorisse** [comment]
## With Sceneform Maintained:
https://github.com/ThomasGorisse/sceneform-android-sdk

### Augmented Image Video texture

![Augmented Images 01](https://user-images.githubusercontent.com/6597529/124591171-47ecf080-de5c-11eb-9196-8fe123e7ea58.gif)

| ![Video texture 01](https://user-images.githubusercontent.com/6597529/124379676-b85b0c80-dcb8-11eb-8250-d7ec7a449fad.gif) | ![Video texture 02](https://user-images.githubusercontent.com/6597529/124379556-13403400-dcb8-11eb-9b56-00e36979eb0f.gif) | ![Video texture 03](https://user-images.githubusercontent.com/6597529/135055851-3d3dca81-2943-4f21-b778-5fd32fa46145.gif) |
| - | - | - |

```java
public void onAugmentedImageTrackingUpdate(AugmentedImage augmentedImage) {
    // If the image is already detected, for better CPU usage we do not need scan for them
    if (imageDetected) {
        return;
    }
    if (augmentedImage.getTrackingState() == TrackingState.TRACKING
                && augmentedImage.getTrackingMethod() == AugmentedImage.TrackingMethod.FULL_TRACKING) {
         // Setting anchor to the center of Augmented Image
        AnchorNode anchorNode = new  AnchorNode(augmentedImage.createAnchor(augmentedImage.getCenterPose()));

        MediaPlayer player = MediaPlayer.create(this, R.raw.my_video);
        player.start();
        VideoNode videoNode = new VideoNode(this, player, chromaKeyColor, null);
        videoNode.setParent(anchorNode);
    }
}
```

**[sample project...](https://github.com/ThomasGorisse/sceneform-android-sdk/tree/master/samples/augmented-images)**
