### ISSUE TITLE
missing APIs compared to arkit

### ISSUE THREAD

**Issue by boehm-e** [google-ar/arcore-android-sdk#809]
Hi,

I would like to know if APIs such as :
- skeleton tracking
- body occlusion
are going to be developped for ArCore.
Google ArCore has great potential, why not put more devs on it? 
Google has a great knowlage with ML, so it would probably not be so hard (for a big company like Google) to do what Apple did, right ?

Cheers,

**Comment by Indashio** [comment]
And why ARCore is available in IOS but Arkit is not available on Android And why Google tested apps first on iPhone? Why Google thing about Apple but Apple don't thing about Google ?

**Comment by liho00** [comment]
https://github.com/google-ar/arcore-android-sdk/issues/775

**Comment by boehm-e** [comment]
Yes , I'm aware about #775 but, since they released ARCore 1.9 with augmented image full tracking and face tracking, I assume it is not dead.
It seems like there is not enough people involved in the development of this technology.
Full image tracking is supported by other SDK for a long time now (without latency), but google only released it since 2month (with 100ms latency on my pocophone).
I'm sure they got the knowledge to develop what Apple did, but why don't they use it?

**Comment by boehm-e** [comment]
they have already done human body segmentation on mobile device in Youtube Stories : 
https://ai.googleblog.com/2018/03/mobile-real-time-video-segmentation.html?m=1
...

**Comment by DavidArayan** [comment]
Need to keep in mind that Android device hardware is incredibly fragmented with many manufacturers. Apple owns and controls their entire hardware lineup, giving them an edge when it comes to developing new software, frameworks or API's etc.. Also need to keep in mind that the latest ARKit features such as the body tracking/occlusion are exclusive to their most recent hardware (not sure if that will change upon final release).

Google could always deliver cutting edge features on the Pixel lineup, what's the market share of pixels compared to other android devices at the moment? Question for someone else to google...

**Comment by boehm-e** [comment]
Yes I know that hardware is fragmented, but they just got the model running on pixel 2, a majority of phones running ArCore are capable of running the inference. So the issue does not seems to be the fragmentation. 
To me the issue is the fragmentation inside Google: youtube team develop this technology, and ArCore team does not seems to have access to it :/

**Comment by sergeyfitis** [comment]
@boehm-e You are naive :)
They(ARCore team) barely can handle all stuff on native Android Platform, even on their own devices Google Pixel.

**Comment by boehm-e** [comment]
Maybe the ARCore team can't.
What I mean is that, google teams should work together.
Maybe they don't care.

**Comment by andymule** [comment]
+1 skeleton tracking

**Comment by boehm-e** [comment]
They are in the right path : 
- [ArCore depth API](https://developers.googleblog.com/2019/12/blending-realities-with-arcore-depth-api.html)

**Comment by ismailnurudeen** [comment]
I'm building an app that allows users try on t-shirts, I want to detect from the user's neck to the user's waist and place an object there. 

Is it body occlusion that would allow me to do that with Arcore or there's currently a way to do it?

**Comment by Andrec-Dxs** [comment]
@ismailnurudeen did you manage to implement this app? if so, what did you use?

**Comment by devbridie** [comment]
Nothing new to share on people segmentation or skeleton tracking, unfortunately.
