### ISSUE TITLE
ARCOre Crash on Xiaomi Mi 8

### ISSUE THREAD

**Issue by 0b01001101** [google-ar/arcore-android-sdk#812]
The new Update of Arcore[12.6.19] chrashes after an ar app[Measure, Google Ar Search] is opened.
The old Version of ARCore[21.5.19 from https://arcore.de.uptodown.com/android] it works

Xiomi Mi 8 MIUI Global 10.3 | Stable 10.3.2.0
![grafik](https://user-images.githubusercontent.com/20306567/60122522-a66b3880-9785-11e9-89d1-c9b0a10fdb7b.png)

Error message:
![grafik](https://user-images.githubusercontent.com/20306567/60122540-b1be6400-9785-11e9-81d5-f9763e429cc8.png)

**Comment by xsvobo34** [comment]
Confirming same issue occurred on my phone same Xiaomi release, none of ARcore aps are working just black camera instead.

**Comment by fabiopoiesi** [comment]
I have the same problem on my Mi8.

**Comment by undefined-bob** [comment]
Confirming on Mi8 (latest ARCore version installed)
Tried using Google Measure app, get following error:

unknown ARCore error (FatalException)

I'm using 10.3.3.0 PEACNXM (stable) from xiaomi.eu

**Comment by fabiopoiesi** [comment]
I tried ARCore 1.7 and it works. I'll stick to it until the issue gets solved.

**Comment by JuvsProgramer** [comment]
I have MIUI 10.3.3, ARcore is broken here

**Comment by Guilherm456** [comment]
The same is happening here on my Mi 8

**Comment by shaowei1983** [comment]
Still crash on arcore 1.10

**Comment by undefined-bob** [comment]
Confirming its working again. Version 1.10.190603116 update from 19. July 2019
Thanks for the update, guys

**Comment by Guilherm456** [comment]
For me it has returned to work with the latest version of ARCore (19 of July 2019)
