### ISSUE TITLE
 Arcore.apk version upgrade caused xiaomi 8 device crash

### ISSUE THREAD

**Issue by 136296634mn** [google-ar/arcore-android-sdk#814]
I found a serious bug, arccore.apk version ARCore by Google 1.10.190603066, xiaomi 8 devices crash, issue FatalException in onResume #261, when I rolled back the arco.apk version, the problem was solved. I hope that when you upgrade the arcole.apk version, you can consider compatibility more, because many client devices automatically update arcore.apk by default, thank you very much. @avirodov   @jguomoto @nvictornvictor

**Comment by Xispeo** [comment]
+1 last ARCore 1.10 runtime installed on my Xiaomi fails to function with any application generated with  unity, with ARCore SDKs from 1.7 to 1.10 and Unity versions from 2018.3 to 2019.1.
I had to manually install ARCore runtime 1.9.1 on my Xiaomi to get ARCore functionning again.

This is a critical issue for anyone deploying an ARCore-based application on the Play Store ^^
No unit tests guys ?! :o

**Comment by as3635629** [comment]
1.10.190603066  不兼容

**Comment by beyondny** [comment]
1.9.0 is okay for me .

**Comment by 136296634mn** [comment]
> 1.9.0 is okay for me .


I'm talking about the version of arcore. apk, not the version of arcore.

**Comment by 136296634mn** [comment]
> > 1.9.0 is okay for me .
> 
> I'm talking about the version of arcore. apk, not the version of arcore.
When you try to upgrade to arcore. apk  version 1.10.190603066, will it crash?

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
