### ISSUE TITLE
Creating anchor for current camera pose not working

### ISSUE THREAD

**Issue by seop-archisketch** [google-ar/arcore-android-sdk#815]
I want to add an anchor of the current camera (its position and angle, etc.) so when anchors update to be more accurate during the ARSession, I want to use those values for later. 

So, when triggered, I call the code below (stores forward vectors and translations):
``` kotlin
val frame = fragment.arSceneView.arFrame
if (frame != null) {
    val camera = frame.camera
    val pose = camera.displayOrientedPose
    val translation = pose.translation
    val zAxis = pose.zAxis
    val backwardVector = Float3(zAxis[0], zAxis[1], zAxis[2])
    val forwardVector = -backwardVector
    val position = Float3(translation[0], translation[1], translation[2])
    positions.add(position)
    forwardVectors.add(forwardVector)
    if (camera.trackingState == TrackingState.TRACKING) {
        anchors.add(session!!.createAnchor(pose))
    } else {
        Log.e(TAG, camera.trackingFailureReason.name)
    }
}
```

But it gives me error on `createAnchor()` function:
```
com.google.ar.core.exceptions.NotTrackingException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:134)
    at com.google.ar.core.Session.nativeCreateAnchor(Native Method)
    at com.google.ar.core.Session.createAnchor(Session.java:93)
    ...
```

### VERSIONS USED
- Android Studio: 3.4.1
- ARCore SDK for Android: `'androidx.core:core-ktx:1.0.2'` in app-level Gradle
- Device manufacturer, model, and O/S: Samsung Galaxy S8
- ARCore: 1.10.190603066 (from settings -> app -> ARCore -> App info)

**Comment by devbridie** [comment]
For what it's worth, the given fragment does work for me on the latest version of ARCore. I'm closing this due to age and can't repro, but if this is still giving you trouble, please feel free to reopen.
