### ISSUE TITLE
Child node not showing, when parent's worldRotation is changed

### ISSUE THREAD

**Issue by pjonceski** [google-ar/arcore-android-sdk#817]
SPECIFIC ISSUE ENCOUNTERED
Hi,
I am adding an Anchor that contains a parent Node .The parent node contains one children Node .

This is the code that i use to add the parent:
`Node().apply { modelObject?.let { val anchorNode = AnchorNode(anchor).also { anchor -> anchor.setParent(fragment.arSceneView.scene) } this.setParent(anchorNode) this.renderable = it }`
The code to add the node:
`Node().apply { renderable = viewRenderable setParent(parent) localPosition = Vector3(0f, 0.005f, 0.005f) localScale = Vector3(0.5f, 0.5f, 0.5f) } `
Then on every frame update i change the worldRotation on the parent node.
The parent node is rendering ok but I get flicker effect on the child node. As i move the camera sometimes it will be shown but then it goes away.

To update the parent node I use this code which is from the ArCore tutorials:
`val cameraPosition = fragment.arSceneView.scene.camera.worldPosition val direction = Vector3.subtract(cameraPosition, parentNode.worldPosition) val lookRotation = Quaternion.lookRotation(direction, Vector3.up()) parentNode.worldRotation = lookRotation`

### VERSIONS USED
- Android Studio: 3.4.1
- ARCore SDK for Android: 1.8.0
- Device manufacturer, model, and O/S: Samsung s8/s10+, Pie(9.0)

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale. If this is still an issue, you can use the newly [open-sourced Sceneform SDK sources](https://github.com/google-ar/sceneform-android-sdk/tree/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform) to try to diagnose the problem, or find a community-reared fork in which the issue has been addressed.
