### ISSUE TITLE
S8+ saying "AR not supported"

### ISSUE THREAD

**Issue by ai2015-try** [google-ar/arcore-android-sdk#819]
![WhatsApp Image 2019-07-11 at 12 01 55](https://user-images.githubusercontent.com/52096856/61021442-13144300-a3d4-11e9-991a-968c39839a60.jpeg)

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by sergeyfitis** [comment]
@ai2015-try Device model number? SM-???

**Comment by devbridie** [comment]
This device should be supported now. If you're still seeing this, feel free to open a new issue as a bug.
