### ISSUE TITLE
hand recognition

### ISSUE THREAD

**Issue by 544531645** [google-ar/arcore-android-sdk#82]
There's a method like the onPreviewFrame, I need to do hand recognition

**Comment by inio** [comment]
with Developer Preview 2, we've added a [computer vision sample](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision).  This sample show how to get CPU access to the camera image data (albeit somewhat inefficiently).

Hope that answers your question.

**Comment by Thaina** [comment]
As of today we have augmented face. I think we should also have augmented hand feature and could use it as input data in the next version

**Comment by valnenov** [comment]
I would be very interested in experimenting with hands / palms / fingers recognition. Any idea when this might be available?!?

**Comment by ChanduMnS** [comment]
> With Developer Preview 2, we've added a [computer vision sample](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision). This sample show how to get CPU access to the camera image data (albeit somewhat inefficiently).
> 
> Hope that answers your question.

@inio 
I'm not able to open the link. :( Kindly help

**Comment by michaelvogt** [comment]
@ChanduMnS 
Try this one: https://github.com/google-ar/arcore-android-sdk/tree/master/samples

**Comment by ChanduMnS** [comment]
> @ChanduMnS
> Try this one: https://github.com/google-ar/arcore-android-sdk/tree/master/samples

Thanks @michaelvogt 
I'm getting a gradle issue while building saying dependecy de.javagl:obj:0.2.1 is not resolved. I'm under a proxy network. Do you know any probable cause of this? @inio
