### ISSUE TITLE
SIGILL Thread-20-[hdr_lighting]

### ISSUE THREAD

**Issue by swantmon** [google-ar/arcore-android-sdk#822]
### SPECIFIC ISSUE ENCOUNTERED
I get an error using HDR lighting on ARCore 1.10 implemented within a native C++ application. The SIGILL happens on startup of the application.

Here is the SIGILL information:
Thread-20-[hdr_lighting]

SIGILL (signal SIGILL: illegal instruction)

___lldb_unnamed_symbol24136$$libarcore_c.so 0x00000079e797b2cc
___lldb_unnamed_symbol24133$$libarcore_c.so 0x00000079e797b1fc
___lldb_unnamed_symbol23155$$libarcore_c.so 0x00000079e78d05d0
___lldb_unnamed_symbol23275$$libarcore_c.so 0x00000079e78e8858
___lldb_unnamed_symbol23153$$libarcore_c.so 0x00000079e78d03b4
___lldb_unnamed_symbol24166$$libarcore_c.so 0x00000079e797d2c4
___lldb_unnamed_symbol24193$$libarcore_c.so 0x00000079e797f244
___lldb_unnamed_symbol22726$$libarcore_c.so 0x00000079e7878560
___lldb_unnamed_symbol22698$$libarcore_c.so 0x00000079e78749e8
___lldb_unnamed_symbol22658$$libarcore_c.so 0x00000079e7872010
___lldb_unnamed_symbol30770$$libarcore_c.so 0x00000079e7b55bf4
___lldb_unnamed_symbol30870$$libarcore_c.so 0x00000079e7b5b38c
___lldb_unnamed_symbol30809$$libarcore_c.so 0x00000079e7b57a04
__pthread_start(void*) 0x0000007a873c61e4
__start_thread 0x0000007a8736717c

### VERSIONS USED
- Android Studio: 3.4.2
- ARCore SDK for Android: 1.10.0
- Device manufacturer, model, and O/S: Google Pixel 3XL
- ARCore: 1.10.190603106
google/crosshatch/crosshatch:9/PQ3A.190705.003/5600800:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Activate AR_LIGHT_ESTIMATION_MODE_ENVIRONMENTAL_HDR in config
 2. Build & run application

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
