### ISSUE TITLE
Does camera focus mode affect positional tracking?

### ISSUE THREAD

**Issue by pahlvinc** [google-ar/arcore-android-sdk#823]
### SPECIFIC ISSUE ENCOUNTERED
When switching camera focus mode it seems it causes positional tracking issues and the camera drifts around making it look like the GameObjects are drifting around. 

### VERSIONS USED
- Device manufacturer, model, and O/S: Samsung, Galaxy S7, 7.0
- ARCore: 1.10.0

### STEPS TO REPRODUCE THE ISSUE
 1. Build a scene with a visible GameObject and a button to switch camera focus mode. 
 2. Switch camera focus mode and watch the GameObject.  
 

### ADDITIONAL COMMENTS
Is there a way to control the camera focus more specifically? Has anyone had this issue before?

**Comment by devbridie** [comment]
For optimal AR tracking performance, we recommend using the focus mode provided by the default session config. See [`Config.FocusMode`](https://developers.google.com/ar/reference/java/com/google/ar/core/Config.FocusMode).
