### ISSUE TITLE
[device support] Xiaomi 9T (Android 9) is not supported

### ISSUE THREAD

**Issue by sacesare** [google-ar/arcore-android-sdk#827]
Device with snapdragon 730 is not supported, anyone to comment ?

**Comment by beyondny** [comment]
try ARCore 1.9.0 and don't update.

**Comment by sacesare** [comment]
Error initialization of ARCore - DeviceNotSupported error, same as 1.10.

**Comment by giangiangian** [comment]
While it is still not officially supported, I just found that latest release works with PoGo on MI9T if you install the APK from https://github.com/google-ar/arcore-android-sdk/releases .

**Comment by sacesare** [comment]
Confirmed, that's work on v1.11.0
