### ISSUE TITLE
How to get the initial coordinate system？

### ISSUE THREAD

**Issue by beyondny** [google-ar/arcore-android-sdk#828]
Hi,
I need ARCore camera position for recording. But I found that initial ARCore session with a different direction has different results. Which means that I have to convert the initialized coordinates system to my own coordinates system. It sounds like a programer's problem, but I need to know the initialized coordinate system with different directions.

**Comment by beyondny** [comment]
the camera position:  frame.getCamera().getPose().getTranslation() depends on the initialized coordinate system which based on the device direction.

**Comment by FannyWF** [comment]
i also need  to do it .  do u  have some solutions ?

**Comment by devbridie** [comment]
Check out [`Camera.getPose()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getPose()). You'll have to find a transformation from local coordinate space to your own coordinate system, and probably matrix multiply using [`Pose.getTranslation()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Pose#public-float[]-gettranslation).
