### ISSUE TITLE
Cannot get distortion parameter from ACameraMetadata

### ISSUE THREAD

**Issue by nedfex** [google-ar/arcore-android-sdk#836]
### SPECIFIC ISSUE ENCOUNTERED
I was modifying the sample code hello_ar_application.cc in sample/hello_ar_c, and trying to get intrinsic and distortion parameters, however the Tags did not contain such attributes, here is the code I added after background_renderer_.Draw(ar_session_, ar_frame_) in the function void HelloArApplication::OnDrawFrame()
```shell
 int32_t count = 0;
    const uint32_t* tags = nullptr;
    ACameraMetadata_getAllTags(cameraMetadata, &count, &tags);
    LOGI("Metadata available %d tags: ", count);
    for (int tagIdx = 0; tagIdx < count; ++tagIdx) {
      LOGI("Found camera tag: %I", tags[tagIdx]);
      if (ACAMERA_LENS_DISTORTION == tags[tagIdx]) {
        LOGI("ACAMERA_LENS_RADIAL_DISTORTION available!!!!");
      }
    }
ACameraMetadata_const_entry entry = {0};
    camera_status_t cameraStatus = ACameraMetadata_getConstEntry(
        cameraMetadata, ACAMERA_LENS_DISTORTION, &entry);
    if (cameraStatus == ACAMERA_OK) {
      LOGI("Dist coeff: ");
      //            for (size_t i = 0; i < 6; i++)  {
      //                RORLOG_INFO << "coeff "  << i << ": " <<
      //                entry.data.f[i];
      //            }
    } 
 ```
Does anyone have idea how to get those values?
Also, are images came out from ndk undistorted or not by default?

Thanks

### VERSIONS USED
- Android Studio:  3.4.2
- ARCore SDK for Android:  28 (android 9)
- Device manufacturer, model, and O/S: pixel3, pixel3 XL
- ARCore: versionName=1.11.190715106
    signatures=PackageSignatures{7df0262 version:3, signatures:[53bcc66f], past signatures:[]}
Hidden system packages:
    versionName=0
    signatures=PackageSignatures{8aee2ae version:0, signatures:[], past signatures:[]}
    packages
    packages
    packages
    packages
- Output of `adb shell getprop ro.build.fingerprint`: google/crosshatch/crosshatch:9/PQ1A.181205.006/5108886:user/release-keys

**Comment by JaimeIvanCervantes** [comment]
I am also interested on this: when I acquire the came image, is the image undistorted already? If it's not undistorted, would it be possible to get the distortion coefficients?

**Comment by devbridie** [comment]
Currently no update on this, but this is duplicating #112. The image that comes out of ARCore is distorted.
