### ISSUE TITLE
Will list of 60 fps supported devices include more Snapdragon 835/newer devices?

### ISSUE THREAD

**Issue by andrelevi** [google-ar/arcore-android-sdk#839]
Right now only the Pixel 2/3 devices support 60 fps targeted AR with ARCore v.1.11.0. Will Samsung devices like the s8, s9, s10 support 60 fps in the near future as well?

**Comment by timototito** [comment]
Hiii andrelevi have  you worked with ARCore 1.11.0 with augmented image detection because due to with latest ARCore is providing previous frame results for new frame

**Comment by andrelevi** [comment]
> Hiii andrelevi have you worked with ARCore 1.11.0 with augmented image detection because due to with latest ARCore is providing previous frame results for new frame

Hi, sorry, but I have not worked with augmented image detection at all.

**Comment by wisockijunior** [comment]
we really need to get support for Snapdragon 845/855 AR enhanced capabilities

**Comment by devbridie** [comment]
No news to share on 60 fps device support.
