### ISSUE TITLE
Is ARCore client going to support store version of ARCore for Pixel devices?

### ISSUE THREAD

**Issue by ritsu1228** [google-ar/arcore-android-sdk#84]
It looks like the ar client included in this repo only works with the arcore preview version. On Monday, Pixel devices begin to receive [arcore update](https://play.google.com/store/apps/details?id=com.google.ar.core) from play store, which I assume is an official release. Unfortunately, this client crashes on the arcore store version.

I am wondering what would the timeline be for an updated client that works with the arcore released in play store. Am I supposed to uninstalled the store release and load this preview instead?

**Comment by inio** [comment]
We just released ARCore Developer Preview 2, which is nearly the same version as
is available on Pixel devices, powering AR Stickers.  *However*, This is still a
developer preview.  Breaking changes may be made before the 1.0 release,
and applications based on Developer Preview 2 should not be widely distributed
or offered on app stores.

**Comment by fredsa** [comment]
@ritsu1228 Note that the original preview release (`arcore-preview.apk`) used a different package name than Developer Preview 2 (`arcore-preview2.apk`) / Play store, so the Play store update should not interfere with your original Developer Preview app.

In any case, please do checkout the new Developer Preview 2 SDK and updated ARCore service, both available from the [releases](//github.com/google-ar/arcore-android-sdk/releases) page.

(If you'd still like to get your original preview app working, please confirm that you've installed the original `arcore-preview.apk`.)

**Comment by ritsu1228** [comment]
@inio @fredsa Thanks a lot! Preview 2 seems to work pretty good with the Play store version of arcore. I intend to work with preview 2 instead of the original preview and it saves the hassle to manually load the original arcore service package.

**Comment by fredsa** [comment]
Great to hear. Thanks for the update.
