### ISSUE TITLE
2d hand Drawing

### ISSUE THREAD

**Issue by HaiderSaleem** [google-ar/arcore-android-sdk#841]
Is there anyway of 2d drawing similar to "Just a line", but instead of drawing in air i want to draw on 2d space like shelf/table or wall!

**Comment by SimonMarquis** [comment]
Yes you can draw only on detected planes.  
You can take a look at my [AR-Toolbox](https://github.com/SimonMarquis/AR-Toolbox) and especially the [Drawing](https://github.com/SimonMarquis/AR-Toolbox/blob/18fc006ebcde43213b31a86ad8da231c8010e162/app/src/main/java/fr/smarquis/ar_toolbox/Nodes.kt#L251-L340) class.

It is mostly based on [googlesamples/sceneform-samples](https://github.com/googlesamples/sceneform-samples/tree/master/drawing) for the drawing rendering, and uses a CollisionPlane as reference when available.

**Comment by HaiderSaleem** [comment]
yeah, i know that but i need it to be drawn on surface rather than in air.
i have tested your app, its great but its not what i want, i want to draw line on surface likewise we placing object on surface.

**Comment by SimonMarquis** [comment]
It does definitely draw on planes.  
The distance to the plane must be lose enough (less than 2 meters), otherwise it will simulate a drawing at 0.5 m from the camera.

![output](https://user-images.githubusercontent.com/1921278/63228594-77a59780-c1f5-11e9-82b9-d9b478c53d64.gif)

**Comment by HaiderSaleem** [comment]
great, is it possible to draw it on point cloud using gl surface view?
p.s: i have edited the distance parameters and it seems to be working within your project.

**Comment by HaiderSaleem** [comment]
> It does definitely draw on planes.
> The distance to the plane must be lose enough (less than 2 meters), otherwise it will simulate a drawing at 0.5 m from the camera.
> 
> ![output](https://user-images.githubusercontent.com/1921278/63228594-77a59780-c1f5-11e9-82b9-d9b478c53d64.gif)

thanks, using your code i have completed my project. :)
