### ISSUE TITLE
1.11.0 then ARSceneview is not providing updated image trakable

### ISSUE THREAD

**Issue by jmhemadri** [google-ar/arcore-android-sdk#843]
### SPECIFIC ISSUE ENCOUNTERED
Augmented Image detection is working perfectly with 1.10.0 when i updated the ARCore verion from 1.10.0 to 1.11.0 then ARSceneview is not providing updated image trakable in addUpdateListener in Android

### VERSIONS USED
- Android Studio: 3.42
- ARCore SDK for Android:  v1.11.0
- Device manufacturer, model, and O/S:  Pixel 3.1, Android 9

### STEPS TO REPRODUCE THE ISSUE
 private fun onUpdateFrame(frameTime: FrameTime) {
intIndex = intIndex+1;
if (isComputingFrame){
    Log.e("Frames", "Dropped")
    }else {
    isComputingFrame = true
    val frame = getViewDataBinding().arSceneView.arFrame
    val colorCorrectionRgba = FloatArray(4)
    frame?.getLightEstimate()?.getColorCorrection(colorCorrectionRgba, 0)
    handler?.post {
        if (frame != null) {
            Log.e("Frames","image index --> "+intIndex)
            getViewModel()?.processFrameForDetection(frame)
            } else {
            isComputingFrame = false;
        }
    }
}

**Comment by Consti10** [comment]
We are also having problems regarding AR Images with the 1.11.0 version, downgrading to 1.10.0 fixed them.
(Both arcore and sceneform)

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
