### ISSUE TITLE
Add ARCore support to custom Android device.

### ISSUE THREAD

**Issue by JL-Vidinoti** [google-ar/arcore-android-sdk#845]
Hello,
We are working with a hardware company that created their own Android device.
What are the steps to be done for adding ARCore support? What do they need to do?
Is there any documentation available on the ARCore integration?
Thank you,
Johan

**Comment by devbridie** [comment]
OEM device manufacturers wishing to certify new devices should refer to the Google AR OEM Portal for a complete list of requirements.
