### ISSUE TITLE
Sync a depth camera to ARcore

### ISSUE THREAD

**Issue by maorp** [google-ar/arcore-android-sdk#846]
Hi. Im trying to use arcore pose with a pointcloud from an extrenal depth camera attached and calibrated to an ARcore smartphone. When static i get good results but when moving i cant use the pose because of the relative time offset between the cams. 
So im asking if there's a way to hardwire a sync signal to an ext camera from arcore. Maybe more of a HW problem...
Ill be happy to hear any solution or reference. Cheers!

**Comment by brookman** [comment]
I am interested in your approach. What camera are you using and how did you connect it to the smartphone?

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
