### ISSUE TITLE
Error with the release of the camera cause error in Samsung Note 9 

### ISSUE THREAD

**Issue by CristianTorrado** [google-ar/arcore-android-sdk#847]
On many occasions with this particular device,  The user observe is that it is not possible to create the session of the camera because the resource is not released.

Only corrected when the user restarting the device.

**VERSIONS USED**
- Android Studio: 3.5
- Language: Kotlin 
- ARCore SDK for Android: 11
- Device manufacturer, model, and O/S:  Samsung Note 9 / Android 8
- ARCore Trace:  I don't have the trace because the issue is replicated in an user device and i don't access to the device. 

We used the ArCore Example to replicate : 
https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/hellosceneform

**STEPS TO REPRODUCE THE ISSUE**
 1. Run the SeceneForm Example apk in the Samsung Galaxy  Note S9
 2. Close the app and run the app again 

Another comments: 
In other device our application run without problema like this. We have the same problem in the Moto G6 with ArCore 1.7 and later the problem was fixed in ArCore 1.8 after report it.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale. If this is still an issue, you can use the newly [open-sourced Sceneform SDK sources](https://github.com/google-ar/sceneform-android-sdk/tree/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform) to try to diagnose the problem, or find a community-reared fork in which the issue has been addressed.
