### ISSUE TITLE
Making point cloud relative to start of service

### ISSUE THREAD

**Issue by nativ18** [google-ar/arcore-android-sdk#86]
PointCloud data seems to be relative to the point cloud's Pose. 

* This information is taken from the Unity documentation and is missing on the Android one.

I was wondering if I can get the point cloud coordinates from "start of service" in meters(like I could in Tango).

**Comment by stetro** [comment]
What about translating and rotating the poincloud points by the current camera pose? 
Since we don't have a depth pose anymore?

**Comment by avirodov** [comment]
This is now fixed in developer preview 2 release. Point cloud points are now in world coordinate frame, so they don't require an additional pose.
