### ISSUE TITLE
Fatal Exception when Creating Session on Samsung Galaxy S10

### ISSUE THREAD

**Issue by shaulabalqis** [google-ar/arcore-android-sdk#879]
Hello ARCore team,

We've encountered a **FatalException** issue while creating Session on Samsung Galaxy S10 (Samsung SM-G973U1 fw 9.0). 
Build fingerprint : samsung/beyond1qltesq/beyond1q:9/PPR1.180610.011/G973USQU1ASAT:user/release-keys.

Currently, we're using ARCore v1.10.0. We've tried to update to v1.11.0 and the exception still persist. We've also tried running _hello_ar_java_ and _augmented_image_java_ into this device and the exception can be reproduced. Here's the screenshot I got from both sample project

![Screenshot_20190905-132954_HelloAR Java](https://user-images.githubusercontent.com/27556483/64317390-c7e86c00-cfe1-11e9-9ded-f7c2e8039534.jpg)
![Screenshot_20190905-132944_AugImg Java](https://user-images.githubusercontent.com/27556483/64317389-c454e500-cfe1-11e9-9a98-6b9a7f15a381.jpg)

Here I attached logs from our app and from _hello_ar_java_
[log_Session_FatalException_HelloAR.txt](https://github.com/google-ar/arcore-android-sdk/files/3577741/log_Session_FatalException_HelloAR.txt)
[log_Session_FatalException_APP.txt](https://github.com/google-ar/arcore-android-sdk/files/3577742/log_Session_FatalException_APP.txt)

For the meantime, ARCore feature in our app is disabled on this device. Can you help me resolve this exception? Any help will be appreciated

**Comment by sandyfriend** [comment]
physical camera didn't match device profile

2019-09-05 13:09:13.383 31692-31692/? E/native: status.cc:153 generic::internal: Physical cameras don't match device profile. Camera not found. camera_id=2, cameras count=2 at third_party/arcore/ar/infrastructure/android/cameras.cc:130
2019-09-05 13:09:13.383 31692-31692/? E/native: session_create_implementation_shared.cc:1624 Failed to initilize the data source - -2
2019-09-05 13:09:13.383 31692-31692/? E/native: session_create_implementation_shared.cc:1625 CreateLiveSessionWithMostDependencies returning ArStatusErrorSpace

**Comment by blackarrow13** [comment]
Same issue was reported here for ArCore 1.5, OnePlus A5000 : https://github.com/google-ar/arcore-android-sdk/issues/595
I also have it, ArCore 1.14, Sony Xperia ZX3

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
