### ISSUE TITLE
App froze when adding multiple view renderables

### ISSUE THREAD

**Issue by amarkovits** [google-ar/arcore-android-sdk#888]
On Android 10 on a Pixel 3 when I add a lot of viewrenderables with an imageview playing a gif the views shows up but the app freeze for about 5 seconds, and then it works fine. This did not happen on Android 9. 
In the logs I see this error while the app is frozen (it shows up multiple times):

> W/OpenGLRenderer: dequeueBuffer failed, error = -110; switching to fallback

Any idea how to fix this?

**Comment by thomasmso** [comment]
Same here. I'm on Android 10 Pixel 3 with latest version of Chrome with the version code `386509238`.

**Comment by midhunkeekkara** [comment]
anyone solved?

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale. If this is still an issue, you can use the newly [open-sourced Sceneform SDK sources](https://github.com/google-ar/sceneform-android-sdk/tree/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform) to try to diagnose the problem, or find a community-reared fork in which the issue has been addressed.
