### ISSUE TITLE
Given Cannonical face mesh for agumented face is not appropriate.

### ISSUE THREAD

**Issue by MehmoodArib** [google-ar/arcore-android-sdk#895]
I am working on Arcore Agumented face and i am trying to put jewellery on face.
i am creating the model fiiting it on the provided cononical face mesh . i am using blender for that but when i run it on actual device model  ,it looses it's position.  
[https://drive.google.com/open?id=10qCkQ2muxkpwApmWMpLAEHgcfSxvNvxB]
(https://drive.google.com/open?id=10qCkQ2muxkpwApmWMpLAEHgcfSxvNvxB)

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
