### ISSUE TITLE
Fatal signal 11 (SIGSEV) when loading GLTF from URI

### ISSUE THREAD

**Issue by ubikapps** [google-ar/arcore-android-sdk#897]
### VERSIONS USED
- Android Studio: 3.5
- ARCore SDK for Android: 1.12
- Device manufacturer, model, and O/S: Pixel 3, Android 10
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`

Packages:
    versionName=1.12.190826056
Hidden system packages:
    versionName=0
Active APEX packages:
Inactive APEX packages:
Factory APEX packages:

- Output of `adb shell getprop ro.build.fingerprint`: 
google/blueline/blueline:10/QP1A.190711.020/5800535:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Init sceneform without AR
 2. Load GLTF from https://poly.googleapis.com/downloads/fp/1569337314120380/4_emmjE3OtU/0GGxvDX2Bqe/model.gltf
into:
 ```
ModelRenderable.builder()
                .setSource(
                    context, RenderableSource.builder().setSource(
                        context,
                        uri,
                        RenderableSource.SourceType.GLTF2
                    )
                        .setRecenterMode(RenderableSource.RecenterMode.ROOT)
                        .build()
                )
                .setRegistryId(uri)
                .build()
                .thenAccept {
                    renderable = it
                    addNodeToScene(it)
                    addTouchListener()
                }
                .exceptionally {
                    Crashlytics.logException(it)
                    return@exceptionally null
                }
```
 3. App crashes with: 
``` A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x6f12ee9f88 in tid 2067 (AsyncTask #1), pid 849 ```

**Comment by SimonMarquis** [comment]
When using [glTF-Validator](http://github.khronos.org/glTF-Validator/), it shows 3 errors that might lead to runtime crash when loading it through sceneform:

```json
[
    {
        "code": "MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS",
        "message": "accessor.min and accessor.max must be defined for POSITION attribute accessor.",
        "severity": 0,
        "pointer": "/meshes/0/primitives/0/attributes/POSITION"
    },
    {
        "code": "MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS",
        "message": "accessor.min and accessor.max must be defined for POSITION attribute accessor.",
        "severity": 0,
        "pointer": "/meshes/1/primitives/0/attributes/POSITION"
    },
    {
        "code": "MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS",
        "message": "accessor.min and accessor.max must be defined for POSITION attribute accessor.",
        "severity": 0,
        "pointer": "/meshes/2/primitives/0/attributes/POSITION"
    }
]
```

**Comment by ubikapps** [comment]
Thanks @SimonMarquis. I am exporting from Blender before uploading to Poly. I'll see if I can clean up the models
