### ISSUE TITLE
Blurry video in AR Mode on Pixel3

### ISSUE THREAD

**Issue by sumitkamath** [google-ar/arcore-android-sdk#899]
### SPECIFIC ISSUE ENCOUNTERED
The shared_camera_java sample is blurry when the switch it toggled to AR mode on a Pixel 3. This can be fixed by changing the focus mode to FIXED instead of AUTO, but we would like to add support for AUTO.

### VERSIONS USED
- Android Studio: 3.5
- ARCore SDK for Android: 1.12
- Device manufacturer, model, and O/S: Google, Pixel 3, Android 9 PQ2A.190305.002
- ARCore: 1.12.190826056
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: google/blueline/blueline:9/PQ2A.190305.002/5240760:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Build and run shared_camera_java, toggle the switch to AR Mode and observe the unfocused image

### WORKAROUNDS (IF ANY)
Switch to FIXED focus mode, but this removes AUTO focus.

**Comment by victormun** [comment]
Hey! 

I faced a similar issue which was not having AUTO FOCUS on a Pixel 3 until I found [this official documentation](https://developers.google.com/ar/discover/supported-devices) that states: "When 60 fps camera capture mode is active, the camera uses fixed focus". If you lower the FPS of the rear camera to 30fps, it may remove the blurryness.

Regards!
