### ISSUE TITLE
When will support other devices?

### ISSUE THREAD

**Issue by ChuuMong** [google-ar/arcore-android-sdk#9]
I have a Galaxy S8+ and Galaxy Note5.

I want the app to work on these devices.

**Comment by nathanmartz** [comment]
Thanks for your feedback. I don't have specific dates for these devices, but I've passed the request along to the device support team.

**Comment by crossle** [comment]
S8+ support plz

**Comment by sooxiaotong** [comment]
does it support S7 edge in the future?

**Comment by J4S0Nc** [comment]
S8+ Please!

**Comment by MTRNord** [comment]
@nathanmartz what about "legacy" devices like a one plus one which is already some years old but should provide enough power for something like AR?

**Comment by romanvfp** [comment]
Lenovo Phab2 Pro, too, please! Otherwise it is kind of weird that it supports more advanced TangoCore but does not support ARCore, while I am sure that technologically it can support ARCore
