### ISSUE TITLE
Add support for "Xiaomi Black shark"

### ISSUE THREAD

**Issue by lucley64** [google-ar/arcore-android-sdk#900]
Why Black shark not support ARCore (SD845, 6GB RAM, 128GB ROM) but all other xiaomi devices support ARCore ?

**Comment by shaulawindy** [comment]
Still not support

**Comment by rogeriosmorais** [comment]
I'm never buying a blackshark again, support is the worst and the "extra features" are garbage.

**Comment by devbridie** [comment]
No update on this device currently. #89 is tracking device support.
