### ISSUE TITLE
Feature request: support for Xiaomi Mi 8 Lite and Pro

### ISSUE THREAD

**Issue by OldShaterhan** [google-ar/arcore-android-sdk#903]
I'm asking for introduce ARCore support for Xiaomi Mi 8 Lite and Mi 8 Pro, as Mi 8 SE and Mi 8 are supported.

Xiaomi Mi 8 and Mi 8 Pro shares much of their configuration, there are nearly no changes between them:
https://www.mgsm.pl/pl/porownanie/xiaomi-mi8pro-vs-xiaomi-mi8/

and Mi 8 Lite has a bit more differences to 8 SE, but still is a high-end model:
https://www.mgsm.pl/pl/porownanie/xiaomi-mi8se-vs-xiaomi-mi8lite/

#89

**Comment by onestep** [comment]
Hello ARcore development team. I am here to support original request and to ask you to add support for Xiaomi Mi 8 Pro, since its hardware is mostly the same as in Mi 8.
Phone code name is `equuleus`. I can provide any additional information if needed.

**Comment by migueldaipre** [comment]
+ 1

**Comment by migueldaipre** [comment]
+ 1

**Comment by devbridie** [comment]
Thanks for the feedback. We're tracking supported devices requests in #89.
