### ISSUE TITLE
 Samsung A9(SM-A920F) compatibility

### ISSUE THREAD

**Issue by SfantuVlad** [google-ar/arcore-android-sdk#905]
Why is the A8 compatible but the A9 not?
The A9 even has the depth camera.

**Comment by PriestOfAdanos** [comment]
I wanna Play Minecraft, lemmie play

**Comment by saenzalberto** [comment]
+1 Its weird that lower end /older phones are on the support list and this one is not.

**Comment by devbridie** [comment]
No update on the A9. #89 is tracking device support.
