### ISSUE TITLE
how to track object when it went off screen

### ISSUE THREAD

**Issue by MonipichMP** [google-ar/arcore-android-sdk#908]
![track](https://user-images.githubusercontent.com/39157246/66629946-6002f200-ec2d-11e9-88ed-2a83ae66b9e3.png)
how to do track object when it went off-screen so people can know which angle they will go?

**Comment by SinanAkkoyun** [comment]
It stays there automatically. If that's not enough, just store the location of the last seen object and refer to that.

**Comment by chnouman** [comment]
@SinanAkkoyun show us some code.

**Comment by MonipichMP** [comment]
@SinanAkkoyun give us some code plz
