### ISSUE TITLE
How add scaling for 3d object inside surfaceview in ar-core android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#91]
how add scaling like zoom,rotate objects inside surfaceview in ar-core?

**Comment by inio** [comment]
If you're asking about the user interface: Right now we aren't offering any manipulation widgets like this.

If you're asking about the programming side:  Both scaling and rotation can be accomplished by multiplying the object's pose matrix with an additional transformation matrix.  On that java side that means `android.opengl.Matrix` methods `multiplyMM()', `rotateM()`, and `scaleM()`.

**Comment by ArigarasuthanRepo** [comment]
Any examples are there? i can't find examples.

**Comment by hannesa2** [comment]
Here you have the usage https://github.com/googlevr/gvr-android-sdk/blob/3bd22d73c3d68b760b99957bb557c8ab6b1755b3/samples/sdk-controllerclient/src/main/java/com/google/vr/sdk/samples/controllerclient/OrientationView.java#L286

`Matrix.rotateM(tmpMatrix2, 0, -startFromSensorTransformation[0], 0, 1, 0);`

I'm interested in this too, please **share** your solution. Thank you !

**Comment by inio** [comment]
Duplicate of #154
