### ISSUE TITLE
I am transforming a simple vector (0,0,-1) to screen coordinates using worldToScreenPoint

### ISSUE THREAD

**Issue by deepoptics** [google-ar/arcore-android-sdk#910]
Hi

I am transforming a simple vector (0,0,-1) to screen coordinates using worldToScreenPoint,
And I am getting a NON center location ... Any Idea ?:

scene.getCamera().worldToScreenPoint(scene.getCamera(), new Vector3(0, 0, -1.0f));
returns:

546.8531, 954.8098, 0.0, (View : 1080, 1895)

Thanks Dov

**Comment by littleylv** [comment]
You must have misunderstand what "Coordinate System" is.

If you want a center screen point, you should never use a (0,0,-1) vector. Instead using a world position related to current camera position(the position in front of camera transform will always in center of screen)

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
