### ISSUE TITLE
FileNotFoundException loading GLTF from URI

### ISSUE THREAD

**Issue by ubikapps** [google-ar/arcore-android-sdk#911]
### VERSIONS USED
- Android Studio: 3.5.1
- ARCore SDK for Android: 1.12
- Device manufacturer, model, and O/S: Pixel 3, Android 10
- ARCore: 1.12.190826106

### STEPS TO REPRODUCE THE ISSUE
1. Init sceneform without AR
2. Load GLTF from https://poly.googleapis.com/downloads/fp/1571149375885956/2P3FXTshxjR/ayoS_trliLr/icon3dface.gltf
into:
ModelRenderable.builder()
               .setSource(
                   context, RenderableSource.builder().setSource(
                       context,
                       uri,
                       RenderableSource.SourceType.GLTF2
                   )
                       .setRecenterMode(RenderableSource.RecenterMode.ROOT)
                       .build()
               )
               .setRegistryId(uri)
               .build()
               .thenAccept {
                   renderable = it
                   addNodeToScene(it)
                   addTouchListener()
               }
               .exceptionally {
                   Crashlytics.logException(it)
                   return@exceptionally null
               }
3. GLTF failes to load with attached FileNotFoundException
[gltf.log](https://github.com/google-ar/arcore-android-sdk/files/3730122/gltf.log)

### ADDITIONAL COMMENTS
GLTF shown as valid by [glTF-Validator](http://github.khronos.org/glTF-Validator/)

**Comment by SimonMarquis** [comment]
I guess it might be because the internal GLTF parser doesn't support embedded (base64 encoded) buffers (or bufferViews).
There is a 172272-bytes base64 buffer at the end of the gltf file
