### ISSUE TITLE
Samsung Tab A 10.1 (2019) Support

### ISSUE THREAD

**Issue by ugurkanates** [google-ar/arcore-android-sdk#912]
This device has 3GB ram ,10.1 nice LED screen and pretty powerful cameras. Runs at Oreo (9.0) and still doesn't supported by ARCore 

Is there any progress for this device?

https://www.gsmarena.com/samsung_galaxy_tab_a_10_1_(2019)-9582.php

GPU : 

Mali-G71 MP2
--
CPU
Octa-core (2x1.8 GHz Cortex-A73 & 6x1.6 GHz Cortex-A53)
--

**Comment by Maar10ve** [comment]
Yes, I also look forward for ARCore support for this device!

**Comment by ZeProf2Code** [comment]
Will it be added?

**Comment by ugurkanates** [comment]
I would hope so , hardware is more than capable.

**Comment by Lateron** [comment]
Any movement on the support?

**Comment by amorino** [comment]
Any updates?

**Comment by donalhunt** [comment]
Added to Issue #89. Please upvote comment there.

Repository owners: you can de-dupe this now.
