### ISSUE TITLE
I want to place an object without tapping at specific location.

### ISSUE THREAD

**Issue by mdshahim** [google-ar/arcore-android-sdk#922]
I am trying to **place an object in my office  without tapping** , please tell me how to place an object to a specific location.
I tried to get position of anchor from different location: 
**anchor.getPose();** method
and after getting x y z points i tried to put on anchor by
**plane.createAnchor(newPose(float value));**
 but failed :( please help me out of this.

I am trying to put objects at different locations.

**Comment by chnouman** [comment]
You need to use hitResult and then you'll be able to get the Planes. You'll get pose and it will help you to build an Anchor. At this anchor, you can place any item.

**Comment by chnouman** [comment]
BTW you need to search this on StackOverflow.

**Comment by mdshahim** [comment]
> BTW you need to search this on StackOverflow.

I tried to  set Pose too , On tap but the object could not be able to placed at static location.

**Comment by chnouman** [comment]
If you are trying with world position I'll not a good solution. You need to
detect plan.

**Comment by HemanParbhakar** [comment]
Session session = arFragment.getArSceneView().getSession();

    float[] position = { 0, 0, -0.75 };       // 75 cm away from camera
    float[] rotation = { 0, 0, 0, 1 };

    Anchor anchor =  session.createAnchor(new Pose(position, rotation));

    anchorNode = new AnchorNode(anchor);
    anchorNode.setRenderable(yourModelRenderable);
    anchorNode.setParent(arFragment.getArSceneView().getScene());
