### ISSUE TITLE
Did ARCore supported on Android One?

### ISSUE THREAD

**Issue by Jason-LI-M** [google-ar/arcore-android-sdk#923]
Did ARCore supported on Android One? I checked the ARCore official website and Android One didn't mention there.
[https://developers.google.com/ar/discover/supported-devices#android_play]

**Comment by devbridie** [comment]
There isn't a distinction made for Android One, so any device listed on the [supported devices](https://developers.google.com/ar/discover/supported-devices) page should be compatible with ARCore (e.g. Moto G Pro).
