### ISSUE TITLE
does arcore support usb (uvc) camera ?

### ISSUE THREAD

**Issue by jaccen** [google-ar/arcore-android-sdk#924]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by jaccen** [comment]
does arcore support usb (uvc) camera ?

**Comment by sandyfriend** [comment]
No, ARCore don't support any USB camera.

**Comment by bhaskar041** [comment]
Has their been any new support added for usb camera

**Comment by BBDevSw2** [comment]
any update for usb camera support?
