### ISSUE TITLE
Add support for Razer Phone 2 (coming minecraft earth)

### ISSUE THREAD

**Issue by enux85** [google-ar/arcore-android-sdk#932]
add ARcore for razer phone 2 support, RP2 is really fast app and great grapichs

**Comment by BPMOmega** [comment]
Seconded.

**Comment by popit42** [comment]
Thirded.  I love my Razer phone, it's clear the hardware is there and Minecraft Earth and FNAF:AR look fantastic, so I would love to be able to play them on my favourite phone.

**Comment by Sliicy** [comment]
4th, add Razer Phone 2.

**Comment by Thebombuknow** [comment]
5th, Razer Phone 2 is faster than the Pixel 3a, yet the 3a supports ARCore and the Razer Phone 2 doesn't.

**Comment by sandyfriend** [comment]
Duplicate of #89
