### ISSUE TITLE
SFA reference and "Augmented Images developer guide for Android" are outdated

### ISSUE THREAD

**Issue by stewe93** [google-ar/arcore-android-sdk#933]
Documentation: 
https://developers.google.com/ar/develop/java/sceneform/sfa

Problem: 
The linked documentation is outdated. For example the `model.attributes` part says `Possible values are`:
- Color
- Orientation
- Position
- TexCoord

But if you generate sfa from an fbx file that includes animation the generated values for me is: 
attributes: [
      'Position',
      'TexCoord',
      'Orientation',
      '**BoneIndices**',
      '**BoneWeights**',
],

---------------------------------------------------------------------------
Documentation:
https://developers.google.com/ar/develop/java/augmented-images/guide

Problem:
"To create an empty image database at runtime, use the no-arg AugmentedImageDatabase() constructor:" There isn't any no-arg ctor, for reference: https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/AugmentedImageDatabase

Would you please update these?

**Comment by devbridie** [comment]
This has been fixed in the meantime.
