### ISSUE TITLE
DeadlineExceededException

### ISSUE THREAD

**Issue by dov-deepoptics** [google-ar/arcore-android-sdk#936]
Hi All
I am getting **DeadlineExceededException** when calling **acquireCameraImage**:

I am overloading ArSceneView onBeginFrame method .... trying to be synced with frames - but no luck -  Any Ideas ??

 public class MySceneView extends ArSceneView {
    public MySceneView(Context context) {
        super(context);
    }

    public MySceneView(Context context, AttributeSet attributeSet) {
        super(context, attributeSet);
    }

    @Override
    protected boolean onBeginFrame(long l) {
        boolean isUpdated  = super.onBeginFrame(l);
        Frame currentFrame = getArFrame();
        if (isUpdated) {
            try {
                ArImage arImage = (ArImage) currentFrame.acquireCameraImage();
                arImage.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return  isUpdated;
    }
}

**Comment by janbolat** [comment]
Any luck guys?
I also opened a ticket, but haven't heard anything:
https://github.com/google-ar/sceneform-android-sdk/issues/996

**Comment by Madonahs** [comment]
Any luck on this? `com.google.ar.core.exceptions.DeadlineExceededException` just got it.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale. If this is still an issue, you can use the newly [open-sourced Sceneform SDK sources](https://github.com/google-ar/sceneform-android-sdk/tree/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform) to try to diagnose the problem, or find a community-reared fork in which the issue has been addressed.
