### ISSUE TITLE
Device support (SM-A20(e))

### ISSUE THREAD

**Issue by nikoskon2003** [google-ar/arcore-android-sdk#939]
Samsung Galaxy A20 and A20e have enough resources to run AR Core, since some supported devices have lower specs. So there should not be any problems supporting the device!

**Comment by ElgenTidwell** [comment]
i keep trying everything, but no matter what it says not compatible with this version, help please!

**Comment by fartboygh** [comment]
This. I was told this had all the capabilities for AR when I got it.

**Comment by TBM13** [comment]
Any news about this? I have a Galaxy A20 and would love to enjoy AR

**Comment by icorreacm** [comment]
Why samsung A20 is not certificated? A los of people could use AR and they are waiting for Google only say that it's OK

**Comment by TBM13** [comment]
Seems like the A20 is now supported

**Comment by s12227054** [comment]
> Seems like the A20 is now supported

I installed ARCore to play FNAF AR, it's not.

**Comment by TBM13** [comment]
> > Seems like the A20 is now supported
> 
> I installed ARCore to play FNAF AR, it's not.

It works fine for me. The Play Store doesn't show it as incompatible like before and performs like expected.
Not sure if it has something to do but i recently got the July 2020 update that comes with the July security patch.

**Comment by s12227054** [comment]
> > > Seems like the A20 is now supported
> > 
> > 
> > I installed ARCore to play FNAF AR, it's not.
> 
> It works fine for me. The Play Store doesn't show it as incompatible like before and performs like expected.
> Not sure if it has something to do but I recently got the July 2020 update that comes with the July security patch.
You mean the android 10 patch? Is your model number SM-A20E? I have that update and it doesn't work.

**Comment by s12227054** [comment]
> > > Seems like the A20 is now supported
> > 
> > 
> > I installed ARCore to play FNAF AR, it's not.
> 
> It works fine for me. The Play Store doesn't show it as incompatible like before and performs like expected.
> Not sure if it has something to do but I recently got the July 2020 update that comes with the July security patch.

Is it the Android 10 patch? I updated to that patch and I use the model stated AKA SM-A205U.

**Comment by TBM13** [comment]
> > > > Seems like the A20 is now supported
> > > 
> > > 
> > > I installed ARCore to play FNAF AR, it's not.
> > 
> > 
> > It works fine for me. The Play Store doesn't show it as incompatible like before and performs like expected.
> > Not sure if it has something to do but I recently got the July 2020 update that comes with the July security patch.
> 
> Is it the Android 10 patch? I updated to that patch.
Yes

**Comment by s12227054** [comment]
> > > > > Seems like the A20 is now supported
> > > > 
> > > > 
> > > > I installed ARCore to play FNAF AR, it's not.
> > > 
> > > 
> > > It works fine for me. The Play Store doesn't show it as incompatible like before and performs like expected.
> > > Not sure if it has something to do but I recently got the July 2020 update that comes with the July security patch.
> > 
> > Is it the Android 10 patch? I updated to that patch.
> 
> Yes

Can you send a video of it working?

**Comment by devbridie** [comment]
Galaxy A20(e) has been added to the support list.
