### ISSUE TITLE
FatalException: ARFrame.update

### ISSUE THREAD

**Issue by idstein** [google-ar/arcore-android-sdk#940]
### SPECIFIC ISSUE ENCOUNTERED
com.google.ar.core.exceptions.FatalException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:145)
        at com.google.ar.core.Session.nativeUpdate(Native Method)
        at com.google.ar.core.Session.update(Session.java:74)

### VERSIONS USED
- Android Studio: 3.5.1
- ARCore SDK for Android: 1.13
- Device manufacturer, model, and O/S: Sony, XZ1, Android 9
- ARCore: 1.13.191007106
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: Sony/G8341/G8341:9/47.2.A.11.228/3311891731:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 E/native: error_policy_util.cc:151 
    #######################################################
    ARCore Fatal Error
    Copy paste the block below until END
    ###################### BUILD ID ######################
     BUILD_USERNAME build-secure BUILD_HOSTNAME oxf6.prod.google.com BUILD_DIRECTORY /export/hda3/borglet/remote_hdd_fs_dirs/rabbit-prod.secure-alloc.build-secure.113.536079300067.14b334fb3717c109/mount/tmpfs/rabbit/workspaces/11337855945316597703/google3 BUILD_EMBED_LABEL arcore_1.13_20191007_RC010 BUILD_BLAZE_RELEASE release blaze-2019.09.28-1 (mainline @271678982) WORKSPACE_STATUS_COMMAND_ARGUMENT /export/hda3/borglet/remote_hdd_fs_dirs/rabbit-prod.secure-alloc.build-secure.113.536079300067.14b334fb3717c109/mount/tmpfs/rabbit/workspaces/11337855945316597703/-oxf6-a188-33362-107a9504df02b-595b4d851bebd_embed_changelist_ VERIFIABLE 1 BUILD_CLIENT build-secure-info:source-uri BUILD_DEPOT_PATH //depot/branches/vr_arcore_release_branch/273204670.2/google3 BUILD_CLIENT_MINT_STATUS 1 BUILD_USERNAME vr-builder BUILD_DIRECTORY /google/src/files/276618081/depot/branches/vr_arcore_release_branch/273204670.2/OVERLAY_READONLY/google3 BUILD_ID a628e9ed-44d4-4db7-94e6-109043b4f5bc BUILD_REQUEST_ID bbq-9384cf0e-873d-4d93-8057-6a439341c962 SRCFSD_TASK_BNS /bns/ox/borg/ox/bns/build-secure/rabbit-prod.secure-srcfsd/113 BUILDRABBIT_DEBUG_BBQID http://go/bbqid?uuid=bbq-9384cf0e-873d-4d93-8057-6a439341c962 BUILDRABBIT_TASK_BNS /bns/ox/borg/ox/bns/build-secure/rabbit-prod.secure-worker/113 BUILD_BASELINE_CHANGELIST 273204670 BUILDRABBIT_DEBUG_BUILD_ID http://go/buildrabbit-build-id/a628e9ed-44d4-4db7-94e6-109043b4f5bc SOURCE_URI googlefile:/google_src/files/276618081/depot/branches/vr_arcore_release_branch/273204670.2/OVERLAY_READONLY/google3 BUILDRABBIT_BLAZE_BINARY_PATH /google/src/files/276618081/depot/branches/vr_arcore_release_branch/273204670.2/OVERLAY_READONLY/google3/tools/blaze BUILD_REQUEST_ID bbq-9384cf0e-873d-4d93-8057-6a439341c962 OBJFSD_TASK_BNS /bns/ox/borg/ox/bns/build-secure/rabbit-prod.secure-objfsd/113 BUILD_VERSION_MAP map 0 { // } BUILD_CHANGELIST 276618081 BUILD_WORKER_VERSION buildrabbit-worker_20191018_0_RC00 BUILDRABBIT_DEBUG_LOG_ARCHIVE_DIR http://cnsviewer/cns/ox-d/home/build-logs/log_archives/a6/a628e9ed-44d4-4db7-94e6-109043b4f5bc 
    ######################## BEGIN #######################
    ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:51	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=51
    ARCoreError: third_party/arcore/ar/core/session.cc:1248ACameraMetadata_getConstEntry	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/session.cc?g=0&l=1248
    ######################### END ########################

**Comment by pondpondnaja** [comment]
got the same problem too

**Comment by MGaidamaka** [comment]
got the same after recent EMUI update
Google Pixel 1 and 4 the same

**Comment by hiteshkamani** [comment]
Any one have solution for the same?

**Comment by miredirex** [comment]
For me, this happens when a session has **augmentedImageDatabase** in its config

**Comment by idstein** [comment]
Any update on this issue? We now receive that exception on various devices in production.

Among others
Samsung S7, S8, S9, A70 & Xioami Redmi Note 8, Poco F1

**Comment by henrikyn** [comment]
Any updates?

Happens on Google Pixel 4 XL, Galaxy Note9 and Huawei P20 Pro using ARCore sceneform 1.15.

**Comment by SGTjeong** [comment]
Facing the same issue on Galaxy S8.
It's weird cuz It was working properly until last week

**Comment by Kashif-E** [comment]
anyone solved this issue getting it on my samsung galaxy s7 edge

**Comment by devbridie** [comment]
There isn't enough information in this stack trace to diagnose the issue;

```
com.google.ar.core.exceptions.FatalException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:145)
at com.google.ar.core.Session.nativeUpdate(Native Method)
at com.google.ar.core.Session.update(Session.java:74)
```

is the stack trace for any error that can arise from `Session.update` native code.

If you're still experiencing this, please open a new issue with a complete log trace using a current version of the SDK.

**Comment by behelit** [comment]
That IS the complete stack trace. ARCore does NOT log enough information, why don't you add some details when a fatal error occurs? Wouldn't that make the most sense??
