### ISSUE TITLE
Wrong obfuscation may cause illegal-access-error

### ISSUE THREAD

**Issue by Feng23** [google-ar/arcore-android-sdk#943]
### VERSIONS USED
- Android Studio: None
- ARCore SDK for Android: https://mvnrepository.com/artifact/com.google.ar/core/1.13.0
- Device manufacturer, model, and O/S: None
- ARCore: 1.13.0
- Output of `adb shell getprop ro.build.fingerprint`: None

### STEPS TO REPRODUCE THE ISSUE
No repro, figured out the issue through static analysis.
Class `a.a.a` is calling a package-private method `android/media/Image$Plane."<init>":()V` from Android SDK 28.

The caller method from `a.a.a`
```
$ javap -c arcore113/classes/a/a/a.class
Compiled from "VisibleImage.java"
public abstract class a.a.a extends android.media.Image$Plane {
  public a.a.a();
    Code:
       0: aload_0
       1: invokespecial #4                  // Method android/media/Image$Plane."<init>":()V
       4: return
}
```

The callee method is package-private in android sdk 28
```
$ javap /tmp/android-28/android/media/Image\$Plane.class
Compiled from "Image.java"
public abstract class android.media.Image$Plane {
  android.media.Image$Plane();
  public abstract int getRowStride();
  ...
}
```

### WORKAROUNDS (IF ANY)
Do not obfuscate `a.a.a`, make the class be in the same package as its super class `Image$Plane`.

**Comment by devbridie** [comment]
In case this is still a problem-- https://stackoverflow.com/questions/59991168/duplicate-class-names-in-two-external-third-party-obfuscated-libraries offers a work around that shadows ARCore's duplicated namespace.
