### ISSUE TITLE
Status of ARCore support for picture-in-picture mode

### ISSUE THREAD

**Issue by Chrisvin** [google-ar/arcore-android-sdk#946]
What is the current official stance on ARCore support for picture-in-picture mode?

I realize that it was explicitly pointed out in [release v1.0.0](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.0.0) that "ARCore does not support picture-in-picture mode", the same was also intimated in [issue #223](https://github.com/google-ar/arcore-android-sdk/issues/223).

But it's been nearly 2 years since that point,
What is the current state of support?
If it is supported, are there any samples that can be shown for reference?
If not, then are there any plans to support picture-in-picture in the future?

**Comment by Chrisvin** [comment]
Any updates regarding this?

**Comment by aepstein824** [comment]
It's tough to say that we support it, but ARCore should be more robust to being used in picture-in-picture now. ARCore 1.14's CAMERA_UNAVAILABLE TrackingFailureReason change will be of interest to you https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.14.0 .
