### ISSUE TITLE
Restarting ARCore session , reseting ARCore world coordinate system.

### ISSUE THREAD

**Issue by FannyWF** [google-ar/arcore-android-sdk#948]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android:

### STEPS TO REPRODUCE THE ISSUE
 1. i tested  the solution for restarting ARCore session in reference , but it didnt work.
 2. The New solution  i found   in stackflow worked , replacing old fragment with  new fragment. 
 3. But i encountered new question.  every fragment had a updateListener .when i replaced the new fragment ,its updatelistener didnt work. 

****### when i clicked the button , the old fragment would be replaced by the new fragment.but the new updateListener in new fragment didnt work ,i cant figure out the question** **

Activity.java
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_demo_ar);
        arFragment =  (ArFragment) getSupportFragmentManager().findFragmentById(R.id.ux_fragment);
        onUpdateListener1=frameTime -> {
            arFragment.onUpdate(frameTime);
            System.out.println("fragment=111111");
        };
        scene.addOnUpdateListener(onUpdateListener1);
  findViewById(R.id.fabIndoorLocation).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                DemoArActivity.ReplaceFragment();
                arFragment=(ArFragment) getSupportFragmentManager().findFragmentById(R.id.ux_fragment);
                addUpdateListener(arFragment);
            }
        });
        context=this;
}
 private void addUpdateListener(ArFragment arFragment){
        System.out.println("addUpdateListener");
        onUpdateListener=frameTime -> {
            arFragment.onUpdate(frameTime);
            System.out.println("addUpdateListener fragment replace");
        };
        arFragment.getArSceneView().getScene().addOnUpdateListener(onUpdateListener);
    }
    public static void ReplaceFragment(){
        ArFragment arFragment=new AugmentedImageFragment();
       context.getSupportFragmentManager().beginTransaction()
                .replace(R.id.ux_fragment, arFragment).commit();
    }

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
