### ISSUE TITLE
ARCore Augmented Image how to create a new Object Renderer at runtime

### ISSUE THREAD

**Issue by GabLogronio** [google-ar/arcore-android-sdk#949]
I'm expanding the "Augmented Image" Arcore project in Android Studio using Java, and i would like to create at runtime new Objects Renderer in order to spawn new objects on the augmented Image. I saw the "Hello AR" project, but in that example it creates more instances of the same object, and therefore use the same Object Renderer. I need to create different objects and so I think I need to create different Objects Renderers.

I tried to create all of the Object Renderers I need in the "createOnGlThread" method but it takes time, while i'd prefer to create them at runtime. The problem it gives me is in the shader tho. It can't create them outside the "createOnGlThread" method as the "GLES20.glCreateShader(type)" method in the ShaderUtil always returns 0, and "GLES20.glGetShaderiv(shader, GLES20.GL_COMPILE_STATUS, compileStatus, 0);" returns 0 in the compileStatus too and it launches the RuntimeException("Error creating shader.").

How can I create an Object Renderer outside the "createOnGlThread" method?

**Comment by devbridie** [comment]
For anybody coming across this in search results, the Android documentation has [a short section on interacting with the GL thread from a different thread](https://developer.android.com/reference/android/opengl/GLSurfaceView#handling-events).

**Comment by bitamirshafiee** [comment]
surfaceView. queueEvent{}

this will be a magic. use queueEvent for communication between mainThread and GLThread.
