### ISSUE TITLE
Reloading the scene in ARCORE loses the camera access Unity.

### ISSUE THREAD

**Issue by kharalsuman007** [google-ar/arcore-android-sdk#95]
Scenario:

Lets says Scene1 in unity uses ARCore camera and you move to scene2 by clicking a button where ARcamera is no longer needed and uses Unity Maincamera. Scene1 works perfectly when you open the app and there is no problem with loading Scene2 but if you try to go to Scene1 again from Scene2 , The app is not using device Camera anymore and the screen is blue. Is this the known issue or you just have to keep the ARCoreDevice gamobject not to be destroyed when loading new scenes.

Note: - I am using SceneManager.LoadScene(levelName, LoadSceneMode.Single); for loading new scenes and my device is Samsung S8 but I guess it has nothing to do this :)

**Comment by inio** [comment]
Thanks for the report!  Unfortunately, this issues tracker is specific to the Java and C APIs.  Please report this over on the [arcore-unity-sdk issues page](https://github.com/google-ar/arcore-unity-sdk/issues).  I've given the team a heads up though.
