### ISSUE TITLE
TrackingStateHelper.java   can  not  find

### ISSUE THREAD

**Issue by caoeryang** [google-ar/arcore-android-sdk#950]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by devbridie** [comment]
This file can be found [e.g. in hello_ar_java.](https://github.com/google-ar/arcore-android-sdk/blob/9461160f6b1ebaf9070368b52795444267b7acab/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/common/helpers/TrackingStateHelper.java)
