### ISSUE TITLE
please add support for xiaomi note 8 pro please

### ISSUE THREAD

**Issue by dulajdanu** [google-ar/arcore-android-sdk#953]
please add ar core support for xiaomi note 8 pro please

**Comment by harowosegbe** [comment]
Please Add Xiaomi Note 8 pro

**Comment by sandyfriend** [comment]
#89

**Comment by sandyfriend** [comment]
Duplicate of #89

**Comment by call0fcode** [comment]
It works now. This version in APKMirror did the trick:

[Google Play Services for AR 1.16.200302046 (arm64-v8a + arm-v7a) (Android 7.0+)](https://www.apkmirror.com/apk/google-inc/arcore/arcore-1-16-20030204-release/google-play-services-for-ar-1-16-200302046-android-apk-download/)

Don't forget to uninstall any installed previous version of the app (also delete its data).

**Comment by harowosegbe** [comment]
Finally, it works! Thank you @call0fcode
