### ISSUE TITLE
ARCORE not  working on MI A3 Device

### ISSUE THREAD

**Issue by rbermudez** [google-ar/arcore-android-sdk#956]
### SPECIFIC ISSUE ENCOUNTERED

All applications and examples use ARCORE loop in the scanning View,  not detect the floor plane. The same aplications are working fine in SAMSUNG A8.

[https://ibb.co/DzVGS16](https://ibb.co/DzVGS16)

### VERSIONS USED
- Android Studio: 3.5.2
- ARCore SDK for Android: 1.13
- Device manufacturer, model, and O/S:  MI A3, M1906F9SH, Android 9
- ARCore: 
  Packages:
    versionName=1.13.191007106
Hidden system packages:
    versionName=0
- Output of `adb shell getprop ro.build.fingerprint`: 
Xiaomi/laurel_sprout/laurel_sprout:9/PKQ1.190416.001/V10.3.6.0.PFQMIXM:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1.Install any app use arcore
 2. Wait to scanning view

**Comment by josecm1** [comment]
Hello, I just bought a Xiaomi MI A3 and when I tried ARCore elements and other AR apps like AR TOYS, FROGGIE JUMP, MEDICION, it can't find any floor neither.

**Comment by josecm1** [comment]
Hi, I have good news, it works!

I tried to calibrate the Accelerometer with different applications in playstore, but none worked well (I found that the horizon was not horizontal when using the camera's "straightening" function and I thought it could be for this). Then I found a post saying how to enter the Xiaomi tests:

https://forum.xda-developers.com/mi-a3/help/sensor-issue-t3984067

And it is putting this code in the phone call application:
* # * # 6484 # * # *

There you can calibrate several sensors. After it I tried ARCore again, it didn't work either.

Then, I fall into that Google had installed everything I had from my previous phone, including Samsung applications (when restoring the account on the new phone).
I have uninstalled several Samsung applications and now it works perfectly!

Hope this help for you, regards!

**Comment by Ranchhort** [comment]
So I got MiA3 Mobile and in that ARCore service is not able to detect the surface too, neither I can see 3D animals not I can use ruler or measurement app based on AR. Solution is very simple in that case.

You need to calibrate the Accelerometer and restart yur device, thats it. But calibrating Accelerometer using MI command which @josecm1  mentioned is bit difficult despite having plane surface you will find it difficult to tilt your mobile and calibrate +45 and -45 so for that I will suggest you can download [https://play.google.com/store/apps/details?id=redpi.apps.accelerometercalibrationfree](url). Put your phone on Plain surface and start calibrating and sit back. in 15-30 sec it will calibrate. Restart is recomended for this and then you are good to go.

**Comment by pbtank** [comment]
Well I had a problem in which Google maps and camera straightening worked fine but any ar related app failed to find plane or anything. I just downloaded the app you suggested and calibrated and also restarted 2-3times and after all that it worked so don't know exactly which one worked but ya you can try all the three, *#*#6484#*#* or app calibration or even check for updates, it will surely work!

**Comment by pbtank** [comment]
Well the app you're referencing for the calibration [Is actually here!](https://play.google.com/store/apps/details?id=redpi.apps.accelerometercalibrationfree)

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
