### ISSUE TITLE
Using draco compressed objects leads to crash

### ISSUE THREAD

**Issue by karntrehan** [google-ar/arcore-android-sdk#957]
### SPECIFIC ISSUE ENCOUNTERED
Draco compressed gltf causes crashes on ArCore

### VERSIONS USED
- Android Studio: 3.6 Canary 11
- ARCore SDK for Android: 1.13.0
- Device manufacturer, model, and O/S: OnePlus 6T
- ARCore: 1.13.191007106
- Output of `adb shell getprop ro.build.fingerprint`: OnePlus/OnePlus6T/OnePlus6T:9/PKQ1.180716.001/1909112330:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1(a). Load a draco compressed gltf into renderable.
 1(b). You can also try to load a draco compressed glb

### WORKAROUNDS (IF ANY)
None that we are aware of

### ADDITIONAL COMMENTS
The draco compressed gltf are created using [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline). The object renders without an issue on [gltf-validator](http://github.khronos.org/glTF-Validator/) but leads to a crash on ArCore.

Repository to try out:  https://github.com/pratish549/ArCore-Sample

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale. If this is still an issue, you can use the newly [open-sourced Sceneform SDK sources](https://github.com/google-ar/sceneform-android-sdk/tree/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform) to try to diagnose the problem, or find a community-reared fork in which the issue has been addressed.
