### ISSUE TITLE
E/ARCore-AuthenticationManager Exception

### ISSUE THREAD

**Issue by NolanOfficial** [google-ar/arcore-android-sdk#959]
### SPECIFIC ISSUE ENCOUNTERED
When loading multiple projects containing ARCore, including the Sample apps provided by Google's AR page, I receive an exception error: 

_'E/ARCore-AuthenticationManager: Exception during AuthenticationManager construction: com.google.android.gms.common.GoogleApiAvailability'._ 

To my understanding, it's related to the Google Play Services for AR. It does not affect the functionality of any of the applications (so far), but it is concerning for any future updates that may come across them. This issue has been continuing for me since November 22, 2019. 

I've attached the LogCat here (as well as down below): [LogCatError.txt](https://github.com/google-ar/arcore-android-sdk/files/3927664/LogCatError.txt)

### VERSIONS USED
- Android Studio: 3.5.2
- ARCore SDK for Android: All
- Device manufacturer, model, and O/S: Samsung, Galaxy S9, 8.0.0
- ARCore: **Packages: versionName=1.13.191007106**
- Output of `adb shell getprop ro.build.fingerprint`:   **samsung/starqlteue/starqlteue:8.0.0/R16NW/G960U1UEU3ARL1:user/release-keys**

### STEPS TO REPRODUCE THE ISSUE
 1. Load the project
 2. Run the project
 3. Within the application, start an ARCore Session
 4. Once a session has been loaded, the exception error will appear within the logcat. 

### ADDITIONAL COMMENTS
So far, no workarounds have been found, but I will update this ticket with any new information. 
[LogCatError.txt](https://github.com/google-ar/arcore-android-sdk/files/3927664/LogCatError.txt)

**Comment by praveenbbhati** [comment]
@NolanOfficial Did you get any solution? or waiting for google ar core team?

**Comment by NolanOfficial** [comment]
> @NolanOfficial Did you get any solution? or waiting for google ar core team?
No solution has been found yet. We tried a few methods that we will try again around the end of December, but until then, we're waiting on Google.

**Comment by NolanOfficial** [comment]
This has been fixed with the new Google Play Service update as of February 6, 20202.
