### ISSUE TITLE
Arcore Help required on Pinch and Zoom

### ISSUE THREAD

**Issue by rramjee** [google-ar/arcore-android-sdk#96]
I'm using Unity to to instantiate an industrial object on tap of the screen similar to Hello AR example. I want to be able to extend this by providing an option to pinch and zoom the object.  I'm not sure if I'm explaining myself well. if you look at the video on youtube "https://www.youtube.com/watch?v=dwWPSnog3Xo" and specifically between 2:14 to 2:20s of the video, they are able to pinch and zoom .  Basically, I'm looking for some guidance on how to pinch and zoom.

**Comment by inio** [comment]
This issue was moved to google-ar/arcore-unity-sdk#65
