### ISSUE TITLE
Razer phone 2

### ISSUE THREAD

**Issue by Darciukas** [google-ar/arcore-android-sdk#963]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by Sliicy** [comment]
Please add Razer Phone 2 to the list of supported Google AR Core devices already.
Why can't anyone tell us **WHY** it won't work? Why are these requests being closed without **EXPLANATIONS**?

**Comment by jd0yle** [comment]
At the very least, an explanation would be awfully nice.

**Comment by DaniellaKalinda** [comment]
so has anyone been able to get AR apps working/deployed on the razer phone 2? I thought this phone was for gamers? The phone seems to have a great processor and RAM. Considering getting one for my workplace as we've started working in AR...very new to this so any explanation is appreciated:)

**Comment by Vernon-Accela** [comment]
> so has anyone been able to get AR apps working/deployed on the razer phone 2? I thought this phone was for gamers? The phone seems to have a great processor and RAM. Considering getting one for my workplace as we've started working in AR...very new to this so any explanation is appreciated:)

People have gotten it to work by emulating their phone fingerprint to an AR compatible device. Not easy or warranty friendly, but proves that the phone can handle ArCore easily.

**Comment by Sliicy** [comment]
@Vernon-Accela can this be done for non-rooted devices?
And also, how is it done?

**Comment by DaniK-gif** [comment]
I ended up getting the samsung galaxy s9 based off comparing a couple
phones (
https://www.gadgetsnow.com/compare-mobile-phones/Razer-Phone-2-vs-OnePlus-7-vs-Samsung-Galaxy-S9-vs-Google-Pixel-3A
).
It's been working really well (highly recommend getting a case and screen
protector as well). If RAM is important to you, you may still be
interested in trying the Razer 2 (has an 8gb ram where s9 has 4gb).
However, based on some reviews, it looked like a 50/50 chance of your AR
app working with the Razer 2 (which is why I opted against it).

Would be good to know if it's worked for others.

**Comment by popit42** [comment]
Even though Razer seems to have removed this phone from their website, it seems like a bunch of people still have it and I know we'd all really like to use a bunch of these AR apps, so is there any sort of information or hope we can get?

**Comment by devbridie** [comment]
I can't give any details on this device specifically, but device support for ARCore is related to OEM willingness to participate, usage numbers, and hardware capabilities.

No update on this device, unfortunately. We're tracking device support requests in #89.
