### ISSUE TITLE
how to calculate eulerangles in arcore face argument

### ISSUE THREAD

**Issue by hoangtocdo90** [google-ar/arcore-android-sdk#965]
Hi,
I am using ar core in a mobile project,
I want to find Euler Angles from the detected face.
In iOS, I convert Augmented Face to a SCNGeometry object and simply get eulerAngles from the SCNGeometry object.
https://github.com/google-ar/arcore-ios-sdk/blob/master/Examples/AugmentedFacesExample/AugmentedFacesExample/FaceMeshGeometryConverter.swift

Now I'm stuck in android, please help me how to find Euler Angles like ios version in android.
Thanks

**Comment by devbridie** [comment]
For anybody coming across this in search results--

1. Use [`AugmentedFace.getCenterPose()`](https://developers.google.com/ar/reference/java/com/google/ar/core/AugmentedFace#public-pose-getcenterpose)
2. Get the quaternion using [`Pose.getRotationQuaternion()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Pose#getRotationQuaternion()) 
3. Use a quaternion to Euler conversion (many implementations available, one from [Android OSS](https://android.googlesource.com/platform/external/jmonkeyengine/+/59b2e6871c65f58fdad78cd7229c292f6a177578/engine/src/core/com/jme3/math/Quaternion.java#278))
