### ISSUE TITLE
Honor 20 PRO

### ISSUE THREAD

**Issue by drozd2000** [google-ar/arcore-android-sdk#974]
Hi there, Huawei created this new device: Honor 20 PRO, Model YAL-L41.
Please add this device to the list.
Thank you!

**Comment by taiebbh** [comment]
Yess please , we're waiting since a long time...

**Comment by sandyfriend** [comment]
#89

**Comment by farhanm1410** [comment]
Hi is there any update in this issue? Is Honor 20 Pro support ARCore?
