### ISSUE TITLE
Xiaomi Mi 9 Lite not supported

### ISSUE THREAD

**Issue by radioactiveguy** [google-ar/arcore-android-sdk#975]
I would like to ask the developers to give support on the Xiaomi Mi 9 Lite, please.
It has very similar specifications to Xiaomi Mi 9, which is already supported.
Kind regards!

**Comment by gekkareijin** [comment]
I'd like to support this request Thank you.

**Comment by EymireWorld** [comment]
I support too. Xiaomi Mi 9 Lite have almost the same as Xiaomi Mi 9 SE, but SE now support.
Pls make support for Mi 9 Lite, heve :
    • Android 9
    • API level 28

**Comment by pozhiloy-enotik** [comment]
I'd like to participate in this request

**Comment by revan1611** [comment]
+1

**Comment by DrHaaax** [comment]
+1

**Comment by olindenau** [comment]
Yes, please be so kind and support Xiaomi mi  9 lite.

**Comment by cripap05** [comment]
vorrei supportare anch'io questa richiesta

**Comment by YOLO105** [comment]
+1

**Comment by KYSARTYY** [comment]
I just open play store , and saw that arcore is finally on mi 9 lite, i downloaded it  , check in some games and it work

**Comment by devbridie** [comment]
Yup, the device has been added to the supported devices list!
