### ISSUE TITLE
Is there any plan for an android 3D engine like Scenekit in iOS?

### ISSUE THREAD

**Issue by geosky** [google-ar/arcore-android-sdk#98]
There are tons of java-based 3D engines or cross-platform C++ engines for choosing, but which one for Android? It's quite unwise to import a huge 3D game engine, like u3d, into a native android app. While, we find it quite helpful to have  Scenekit in iOS. Building a native AR iOS app using Swift is much easier.

**Comment by nirajsanghvi** [comment]
This issue looks like a dupe of #52

**Comment by inio** [comment]
Duplicate of #52
