### ISSUE TITLE
"arcore-1.13.0.aar" is conflict with "sdk-videowidget-1.40.aar"

### ISSUE THREAD

**Issue by xiaosenlin** [google-ar/arcore-android-sdk#981]
hi，
       our project needs to use arcore-1.30.0.aar and sdk-videowidget-1.40.0.aar，but these aar packages are  obfuscated.They have the same classpath: com.google.a.a.c.class etc.  Code compilation error........
       Is there a solution？Can anyone provide aar without confusion ?
       Thanks.

**Comment by devbridie** [comment]
[This StackOverflow answer](https://stackoverflow.com/questions/59991168/duplicate-class-names-in-two-external-third-party-obfuscated-libraries) demonstrates how to rename the problem classes.
