### ISSUE TITLE
How to place 3d Object at perticular point without using the camera in SceneView

### ISSUE THREAD

**Issue by suraj-0387** [google-ar/arcore-android-sdk#985]
I want to place an 3d object but I do not want to display it on camera but it shout should draw it at specified point using Java code.

**Comment by vinayak15** [comment]
Hello, regarding your comment 
Even I was doing a related project, right now I am facing issue to draw 3d object on camera view at a particular position
For position I a using media pipe and for 3d object, I was thinking of using arcore 
When using arcore with media pipe display was getting a lot slower and it was destroying the user experience 
So can you please tell me if you achieved this task then what was your approach
I want to displayer fbx 3d file on the camera view of media pipe

**Comment by devbridie** [comment]
If you're not using the camera, it sounds more like a job for something like [SceneViewer](https://developers.devsite.corp.google.com/ar/develop/java/scene-viewer) or [Filament's Model Viewer](https://github.com/google/filament/blob/main/android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt).
