### ISSUE TITLE
Samsung A30s/A50s Support

### ISSUE THREAD

**Issue by EBDERLERL** [google-ar/arcore-android-sdk#986]
Samsung released a new refresh of the A series a few months ago (A30s/A50s), the previous models were already compatible with arcore. I currently own a A30s. Will there be support for the new models?

**Comment by fartboygh** [comment]
Needs compatibility with a20 first.

**Comment by sandyfriend** [comment]
#89

**Comment by vophongnguyen89** [comment]
I'm using a50s but don't know if the developers support it

**Comment by vophongnguyen89** [comment]
I'm using a50s but don't know if the developers support it

**Comment by sandyfriend** [comment]
A50/A50s and A30 are supported. Please check
https://developers.google.com/ar/discover/supported-devices

**Comment by Shaunimsorry** [comment]
can somebody with these devices verify if they are working with AR ? are you able to run ar measure apps etc ?

**Comment by pavelk0508** [comment]
When will a30s support be available?

**Comment by pavelk0508** [comment]
and how do you comment on this? It works https://www.tuttoandroid.net/google/play-services-per-ar-asus-rog-phone-2-xiaomi-mi-9t-pro-xperia-5-723747/

**Comment by Artnoc1** [comment]
a30d

**Comment by devbridie** [comment]
These devices are currently supported.
