### ISSUE TITLE
Unconsistent list of compatible devices beteween ARCore web page and Developer console

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#987]
There is a list of ARCore compatible devices here:
https://developers.google.com/ar/discover/supported-devices

And as explained on this page, a csv can also be downloaded from the developer console.

The problem is that these two list are not consistent. Some devices listed on the ARCore page are not present in the csv ; and some devices present in the csv list are not listed in the ARCore page.

May you explain why these lists are not consistent ? Which list is the most reliable ?

Thanks.

**Comment by agGitHub** [comment]
Here is a table presenting the inconsistencies : https://www.justbeamit.com/uuupk

The empty cells show the lines where the is an inconsistency.

**Comment by lvonasek** [comment]
The link is not valid

**Comment by agGitHub** [comment]
> The link is not valid

corrected !

**Comment by lvonasek** [comment]
One source of the issue are wrong names, examples:
Google Nexus 5X is LGE Nexus 5X
Google Nexus 6P is Huawei Nexus 6P
Huawei Honor V20 is Huawei Honor View 20

Another source of the issue is that ARCore list not up-to-date

**Comment by agGitHub** [comment]
Ok. So the reliable list is the list of the Google Play console ? Please confirm. Thanks.

**Comment by lvonasek** [comment]
Exactly. Note that I am not Googler. Google stopped actively answering here during 2018.

**Comment by devbridie** [comment]
The canonical supported device listing will always be the Play Store's supplied list; [the table on the supported devices page](https://developers.devsite.corp.google.com/ar/discover/supported-devices) is a summary.

**Comment by lvonasek** [comment]
@devbridie the link you shared is not publicly available.

**Comment by devbridie** [comment]
Sorry, it's the [public Supported Devices page](https://developers.devsite.corp.google.com/ar/discover/supported-devices#google_play_devices).
