### ISSUE TITLE
How can I convert ByteArray from ImageMetaData() to Bitmap?

### ISSUE THREAD

**Issue by Sam1211** [google-ar/arcore-android-sdk#99]

**Comment by inio** [comment]
The ImageMetadata provides metadata about the image, not the image itself.  If you want CPU access to the pixels, look at our [computervision sample](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision).

**Comment by Sam1211** [comment]
I'm trying to convert the ByteBuffer to Bitmap.I am trying the following:-

- Covert ByteBuffer to Byte[] and then Byte[] to Bitmap. However, when I execute the following code I get 'null' in the 'bmp'.

`byte[] imgBytes = new byte[imageBuffer.buffer.remaining()];
Bitmap bmp= BitmapFactory.decodeByteArray(imgBytes,0,imgBytes.length);`

Is there any other way I should try?

I'm still new to this and trying to understand as much as I can.

Thank You.

**Comment by inio** [comment]
Where are you getting the ByteBuffer from?  I don't see any returned by ImageMetaData.

If you're looking at the ComputerVision sample, you need to create a bitmap and then copy the pixel data into it.   Something like:

    Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
    bitmap.copyPixelsFromBuffer(imageBuffer.buffer);

You also likely will need to adjust the shader so that it remaps the channels to produce ARGB data.  In particular you'll want to change TextureReader.java:124 from:

    gl_FragColor = texture2D(sTexture, v_TexCoord);
to something like:
    gl_FragColor = texture2D(sTexture, v_TexCoord).argb;  // or maybe bgra

**Comment by Sam1211** [comment]
@inio I'm getting my ByteBuffer from CameraImageBuffer. 

I did try the above method. But I get an exception of 
` Buffer not large enough for pixels`. 

I tested with various values but I keep on getting the above error. If I take a number like 1024*1024 for width. I get 

`java.lang.OutOfMemoryError`

**Comment by inio** [comment]
That error means that your image is too big, not too small.  The width and height for the Bitmap should match those passed to `TextureReader.create()`.  Also make sure the `position()` of the buffer is zeroed before passing it to `copyPixelsFromBuffer`

**Comment by Sam1211** [comment]
I tried the following:
`Bitmap bitmap = Bitmap.createBitmap(IMAGE_WIDTH, IMAGE_HEIGHT, Bitmap.Config.ARGB_8888);`

`bitmap.copyPixelsFromBuffer(imageBuffer.buffer.position(0));`

I have defined width and height and it's the same I'm passing in 

`mTextureReader.create(CameraImageBuffer.IMAGE_FORMAT_I8, IMAGE_WIDTH, IMAGE_HEIGHT, false);`

I also tried with `keepAspectRatio: true` but 

I still get the same error `Buffer not large enough for pixels` :(

**Comment by inio** [comment]
Oh, you're using I8!   Bitmap doesn't offer a grayscale config.  Either switch the Bitmap.config to ALPHA_8 or texture reader to RGBA8 and you'll have better luck.

**Comment by Sam1211** [comment]
That help's a lot. Thank You.

Have a nice day :)

**Comment by IrisSofia** [comment]
Sam1211 can you please share your code i need to do convert bytearray from imagemetadato to bitmap
