### ISSUE TITLE
Scene Viewer AR module "Couldn't load object". Online previewer blank screen on mobile.

### ISSUE THREAD

**Issue by krizbastek** [google-ar/arcore-android-sdk#990]
Hi.

I have two problems.
I created system using Scene Viewer AR. Everything worked 1 month ago but now when i implement new glb. files after click "view in your space" i  have message that "Couldn't load object. Looks like there's something wrong with this object".
I tried to load old glb. files which worked. Also i checked it with template Astronaut.glb file. But no results.

Next i try load all files by https://arvr.google.com/scene-viewer-preview on mobile device but after import there was only black screen. 
On desktop version this problem not appear.  

### VERSIONS USED
- ARCore SDK for Android: 
- Xiaomi mi 9/ Pixel 3XL 
- ARCore 1.14.191118106

### STEPS TO REPRODUCE THE ISSUE
 1. Download https://github.com/GoogleWebComponents/model-viewer/blob/master/packages/shared-assets/models/Astronaut.glb to your mobile phone. 
 2. Open https://arvr.google.com/scene-viewer-preview on Edge browser.
 3.  Load Astronaut.glb file. 

### ADDITIONAL COMMENTS
I think that the problem is with scene viewer tool after ARCORE update.

**Comment by devbridie** [comment]
It seems that the scene viewer previewer is incompatible with Android due to Spectre mitigations; see 
https://www.chromestatus.com/feature/5171863141482496.

I've kicked it up with the relevant team.

**Comment by wezside** [comment]
This is not particular to the web scene viewer preview. We are experiencing problems where previous GLB files used to open up in AR Core Scene Viewer using an HTML intent and now they stopped working. The error in Logcat is 

` Failed to Load Gltf url '<url>.glb' reason: Failed to create InputStream.`

Is there any other way to figure out why these GLB files are failing?
