### ISSUE TITLE
Is ARCore World coordinate system left-handed or right handed?

### ISSUE THREAD

**Issue by alexs7** [google-ar/arcore-android-sdk#991]
I am a bit confused regarding the coordinate system or ARCore. It says [here](https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/Pose) that it is right-handed but that is for the pose of the camera? Meaning each pose's LOCAL coordinate system.

What about the world coordinate system ? It says [here](https://stackoverflow.com/questions/54235895/arcore-world-alignment) it is left handed ? ...

Thanks

**Comment by devbridie** [comment]
All poses are defined to use the right-handed coordinate system, that is, +Y up, -Z "forward", and +X right.
