### ISSUE TITLE
Note 10 Plus 5G Camera Freezing

### ISSUE THREAD

**Issue by MichealReed** [google-ar/arcore-android-sdk#992]
Please see this topic in the Samsung forums:
https://eu.community.samsung.com/t5/Galaxy-Note10-Note10-Note10-5G/AR-games-unplayable-freezing-Note-10-plus/td-p/1490513

I do not personally have a Note 10 Plus, so I have little access to diagnose, but recently a user testing our app has reported the same. The user described it as a freeze whenever he moved too quickly. After a quick search the above forum post showed, and a user mentions the same here:
https://github.com/google-ar/arcore-android-sdk/issues/980

Unsure on which github repository provides the best visibility for escalation, so I am posting this issue in both.

Unity repository issue: https://github.com/google-ar/arcore-unity-sdk/issues/689

**Comment by MichealReed** [comment]
Issue has been escalated to Samsung here:

https://eu.community.samsung.com/t5/Galaxy-Note10-Note10-Note10-5G/AR-games-unplayable-freezing-Note-10-plus/m-p/1536478#M1886

We need users affected by this issue to submit logs to the Samsung Members app for their QA team.

**get logs:**
https://support.samsungknox.com/hc/en-us/articles/115013353688-How-do-I-capture-logs-to-troubleshoot...
 
**download app:**
https://play.google.com/store/apps/details?id=com.samsung.android.voc&hl=en_US

**submit logs:**
https://www.samsung.com/ca/support/mobile-devices/samsung-members-how-to-submit-an-error-report/

**Comment by dungnguyen234** [comment]
i note that the new update of Google Play AR service have fix this error

**Comment by MichealReed** [comment]
@dungnguyen234 I verified that the user was running the Dec 18th update. Seems this did not fix in all cases.

**Comment by HereafterMills** [comment]
Im having this issue as well. Not exactly though, AR works, but really badly. I do get a complete freeze/crash on the note 10 plus if i cover up the camera even for a second.

**Comment by MichealReed** [comment]
@HereafterMills can you please make sure you are running the latest release as outlined here?

https://github.com/google-ar/arcore-android-sdk/issues/982#event-3015827634

Latest release date for google services for AR should be 02/06/20. Please let me know if this solves your issue so I can close and provide an update to our users. I don't have a note 10+ to personally test with.

**Comment by HereafterMills** [comment]
@MichealReed  Super strange. I have the last update on Feb 3rd 2020. No option to update.

**Comment by HereafterMills** [comment]
@MichealReed Assuming you are talking about Google Play Services for AR, right?

**Comment by MichealReed** [comment]
@HereafterMills try sideloading from here:  https://github.com/google-ar/arcore-android-sdk/releases

**Comment by HereafterMills** [comment]
@MichealReed Yep, That did seem to make it MUCH better. Will get back to work on Monday to do some more exhaustive testing and report back here. 

Thank you!

**Comment by MichealReed** [comment]
Cool, closing this issue for now. Thanks for testing!
