### ISSUE TITLE
Black screen with Dexguard obfuscation

### ISSUE THREAD

**Issue by pmolinfe8** [google-ar/arcore-android-sdk#994]
After activating Dexguard on my ARCore based project, my AR camera is black, probably due to obfuscation of Arcore Session or other class related to AR package.

You can see the AR object but the scene is full black

I tried every rules in my dexguard-project.txt  but no one works for me.

### SPECIFIC ISSUE ENCOUNTERED

SPECIFIC ISSUE ENCOUNTERED
VERSIONS USED
Android Studio: None
ARCore SDK for Android: 1.13.0
Device manufacturer, model, and O/S: All models
ARCore: 1.13.0

### STEPS TO REPRODUCE THE ISSUE
 My dexguard rules:

#dont obfuscate
#-dontobfuscate

-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}
-keepclassmembers public class com.google.ar.core.Session {
  static <methods>;
}
-keepclassmembers class com.google.ar.core.** { *; }
-keep class com.google.ar.** { *; }
-keep class com.google.vr.** { *; }
-keep class com.unity3d.unitygar.** { *; }
-keep class com.unity3d.plugin.** { *; }
-keep class com.google.atap.tangoservice.** { *; }
-keep class com.google.tango.** { *; }
-keepclassmembers class com.google.ar.core.Pose {
  private <fields>;
}

### ADDITIONAL COMMENTS

 if I discomment -dontobfuscate works fine

**Comment by Hubknox** [comment]
Did you manage to find a solution?

**Comment by Hubknox** [comment]
-keepresources */* should fix it. You should narrow it down further from there though.

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
