### ISSUE TITLE
Depth API

### ISSUE THREAD

**Issue by boehm-e** [google-ar/arcore-android-sdk#996]
Hi,

I would like to know (and i'm not the only one) when will be the ArCore Depth API SDK released ?

Thank you for the great work :)

**Comment by wisockijunior** [comment]
ARCore 1.15 just released, yet no news on Depth API...

https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.15.0

**Comment by mpottinger** [comment]
Yes I also don't understand, I am impatient because I am excited about it, but why so long after it is announced, when it is already working in select apps such as Houzz and web search.

**Comment by andersemil** [comment]
They only finished the call in january so its still only select few devs who have access.

**Comment by wisockijunior** [comment]
will it support ToF cameras?

Att
Renato Wisocki Junior
renato@wisockijunior.com.br



Em seg., 9 de mar. de 2020 às 13:03, Anders Emil <notifications@github.com>
escreveu:

**Comment by wisockijunior** [comment]
ARCore 1.16 just released, yet no news on Depth API...

**Comment by boehm-e** [comment]
I am confined and bored, please give this API so we can play with it 😁

**Comment by Mesalcode** [comment]
Is there any update? I finally want to try it out.

**Comment by boehm-e** [comment]
So much time without any update, even zero demo from the beta testers who filled the form and got the chance to try it out....
Maybe there was no beta testers, who knows ...

**Comment by mpottinger** [comment]
@boehm-e Yeah, a little frustrating isn't it? It already works in their own search app, and in the Houzz app, so why not just release it already after so long?? Weird.

**Comment by boehm-e** [comment]
@mpottinger yes rly frustrating... Thinking to switch to Iphone.

**Comment by Zumbalamambo** [comment]
finally they have released it !!!!!

**Comment by gorastudio** [comment]
> finally they have released it !!!!!

Where??

**Comment by mpottinger** [comment]
Finally!!!! Can't wait to try it out. Never doubted it for a second 😅

**Comment by RGregat** [comment]
Maybe a total stupid question, but will the Depth API also  improve the anchoring stability? Or are the Depth API and the way how we anchor Anchor/AnchorNode on the Scene, two completly different things?

**Comment by andrey-melnikov** [comment]
Sadly lots of phones are not supporting Depth API. So is mine :(

**Comment by mpottinger** [comment]
@RGregat I'm not inside Google  so I don't know what they may have added, but from what I understand, and also what I have seen trying out the new API is that it is completely separate.

The old system for anchoring etc hasn't changed and this just allows occlusion effects.

Hit testing still works on limited features instead of the depth map. 

If you convert the depth to world coordinates you could have hit testing bring back results anywhere on the screen, but accuracy may be less than desirable.

I find the accuracy to be lower with this than an actual hardware depth sensor. It is good enough for occlusion, but not 3D scanning, etc

**Comment by RGregat** [comment]
I see, so the main use case is more the occlusion of real world objects. I don't want to complain this is also awesome, but I still stick to Sceneform and for that the Depth API is currently nothing for me. But I will give it try on Unity, as I started a couple of days ago to learn Unity + AR Foundation.

**Comment by boehm-e** [comment]
@RGregat yes I don't get why it has been archived :/
Maybe I will try to add depth API to openframeworks.

**Comment by Zumbalamambo** [comment]
ARCore with Depth API is bad. Really produces a squiggly UI.

**Comment by Zumbalamambo** [comment]
@RGregat no... it made it even worse, unfortunately.. I was expecting that it will make it good as well...

**Comment by toolgate** [comment]
Hello.
"ARcore Depth Lab" application is not available on my Xiaomi mi 9t pro.
But it is on the list of supported devices (Redmi K20 pro)

**Comment by boehm-e** [comment]
@toolgate , I don't see the redmi k20 / k20 pro supported by the depth api. They support arcore but not the depth api.

**Comment by devbridie** [comment]
You've probably already seen that Depth API has been launched publicly! If there are any problems, please feel free to open up a new issue.
