### ISSUE TITLE
Xiaomi Redmi note 8 pro is not supported

### ISSUE THREAD

**Issue by rockwind158** [google-ar/arcore-android-sdk#997]
Hello! 
When will Xiaomi Redmi note 8 pro be supported?

**Comment by sandyfriend** [comment]
#89

**Comment by call0fcode** [comment]
It works now. This version in APKMirror did the trick:

[Google Play Services for AR 1.16.200302046 (arm64-v8a + arm-v7a) (Android 7.0+)](https://www.apkmirror.com/apk/google-inc/arcore/arcore-1-16-20030204-release/google-play-services-for-ar-1-16-200302046-android-apk-download/)

Don't forget to uninstall any installed previous version of the app (also delete its data).
